### ISSUE TITLE
Compiling for 2.80

### ISSUE THREAD

**Issue by TesseraSkye** [JacquesLucke/animation_nodes#1001]
I might be looking in all the wrong places, but I can't seem to compile for 2.80. The 2.8 branch seems to want to compile 2.79, which is very odd to me. Is there documentation I'm not seeing?

**Comment by OmarSquircleArt** [comment]
Which platform do you want to compile to? What do you mean by *"seems to want to compile 2.79"*? What gave you that impression.

**Comment by JacquesLucke** [comment]
We should just change the setup.py in the blender2.8 branch to use expect Python 3.7 by default :)

For now, just use the `--noversioncheck` option.

**Comment by TesseraSkye** [comment]
@JacquesLucke Thanks, will do!
@OmarSquircleArt The compiler errors point to an incorrect version of python, assuming I'm trying to compile 2.79. This is from the 2.8 branch.
