### ISSUE TITLE
Animation not updating during render - Blender 2.8 Beta

### ISSUE THREAD

**Issue by Draise14** [JacquesLucke/animation_nodes#1003]
Currently, when I try render out an animation with AN (2 node trees), even with the update on Auto, Always, Per Frame change, the update doesn't happen during a Render Animation to file. 
Each frame comes out with no AN activity, neither in Eevee and Cycles. 

I'm using Blender 2.8 Beta, and AN 2.1 for 2.8, python . 

I can do an Open GL render of the viewport without a problem, as that does update. 

Why would this be? Is this a bug?

**Comment by OmarSquircleArt** [comment]
Yes, this is a bug. Unfortunately, we haven't been able to pin point its cause yet.

**Comment by Draise14** [comment]
I did build the AN trees in 2.79b then migrated them. Maybe that's the issue? 

Has it ever rendered animations in 2.8 before?

**Comment by OmarSquircleArt** [comment]
I don't think this is an issue. Everybody is complaining about this bug, so you are not alone. Blender crashes after the second or third frame for me, so I am experiencing problems as well.

**Comment by wwkayak** [comment]
Just FYI, it will render if you "bake to keyframes". Not a pretty fix, but it'll work for now :)

**Comment by alessandro-zomparelli** [comment]
I'm having the same problem with the code of Tissue. 
Seems that the handlers doesn't works in render mode... To me seems a Blender 2.80 bug. 
In Blender 2.79b I used the handler frame_change_post, now seems that there are more handlers. I tried render_pre and render_init, but it crashed after few frames....

**Comment by VideoBombala** [comment]
Hi!
The baking to frames was my first option. 
Now i solve the same problem (crash/not render) with rendering by script. It's fine for me, render works very well:

```
import bpy

for step in range(1, 100):
    
    bpy.context.scene.frame_set(step)
    bpy.data.scenes["Scene"].render.filepath = 'd:/3D RENDER/2019 01 13/image.jpg_%d.jpg' % step
    bpy.ops.render.render( write_still=True )
```

**Comment by nviogne** [comment]
When you "append" a node tree made in 2.79 into blender 2.8, there's a new scene that is created with all objects of the 2.79 scene. If this is your case, just delete the scene in outliner window and it will work.

**Comment by OmarEmaraDev** [comment]
Lets continue the discussion in issue #1200 .

**Comment by AticAtac80** [comment]
> Just FYI, it will render if you "bake to keyframes". Not a pretty fix, but it'll work for now :)

Once baked to kfs, next step is to render animation? I tried this but anim nodes still not updates...
Thanx
