### ISSUE TITLE
Performance Problems with "Number List Math (Add)" Node

### ISSUE THREAD

**Issue by ogierm** [JacquesLucke/animation_nodes#1007]
Hey,
the Number List Math node is very slow for me. I used a loop to get the same functionality and it's for some reason much faster.
I'm using the latest 2.8 build from the releases section on this repo on a 2.8 buildbot build from yesterday

![image](https://user-images.githubusercontent.com/29630575/51394097-d1e45a00-1b39-11e9-8a8d-0248d9cdb8c9.png)

My list (green circle) has 21 double digit elements. The number list node (blue circle) needs 4.5ms for summing it, the node group / loop (orange circle) needs 0.01ms.

**Comment by OmarSquircleArt** [comment]
Can you make a more minimal example and upload the blend file here?

**Comment by OgierM** [comment]
Yup, here it is.

![image](https://user-images.githubusercontent.com/29630575/51409587-927e3380-1b62-11e9-87bf-b38f05022cf1.png)

It even needs tons of time for an empty list...

[performance_problems_number_list_node.zip](https://github.com/JacquesLucke/animation_nodes/files/2774315/performance_problems_number_list_node.zip)

**Comment by OmarSquircleArt** [comment]
A single execution may not be the best metric, can you try multiple executions? I don't see those numbers:

![node tree](https://user-images.githubusercontent.com/25300994/51410839-6ff21780-1b6e-11e9-8b1f-104949624b57.png)

Can you try this node tree?

**Comment by OgierM** [comment]
1) Yes I did execute that tree a couple dozend times / had "always" running. My results are consistent. I also had that porblem in 2 files now.

2) Your results match with mine 
![image](https://user-images.githubusercontent.com/29630575/51413174-476a1d80-1b6e-11e9-89fc-4b1a248c2b8b.png)

3) Maybe the source is a problem with the implicit Integer to Float conversion? That would be consistent with my node group that just accepted integers.
![image](https://user-images.githubusercontent.com/29630575/51413273-a62f9700-1b6e-11e9-9659-84c3f0996356.png)

**Comment by OmarSquircleArt** [comment]
No, it is not the implicit conversion, I just tested it and it had negligible effect.
I still can't get the numbers you are getting, I even tested the build in the release page.
Can you test how it scales with input? Measure the time when the list contains 10, 100, 1000, .... elements.
Maybe @JacquesLucke should take a look.

**Comment by OgierM** [comment]
![image](https://user-images.githubusercontent.com/29630575/51427441-4978be80-1bf8-11e9-87e5-ad0136d88107.png)

**Comment by OmarSquircleArt** [comment]
Can you measure this?
![test](https://user-images.githubusercontent.com/25300994/51428269-6b7b3c80-1c0a-11e9-8430-a1c50bb85365.png)

**Comment by OmarSquircleArt** [comment]
It seems the `fromValues` method is the root of those regressions then. Sorry, but I have no idea what could be causing this.
If you want a workaround for now, you can use this expression `numpy.sum(list.asNumpyArray())`. While making sure numpy is imported in the advanced node settings.

**Comment by OgierM** [comment]
Hm, okay
