### ISSUE TITLE
Blender 2.8 crashes during rendering

### ISSUE THREAD

**Issue by uzikisi** [JacquesLucke/animation_nodes#1009]
Hi,

I'm not sure this is the right place to ask but i don't know where to write,

Blender 2.8 beta is continously crashing when i try to render an animation 

I tried both in eevee and cycles but both of them crashes, is there a specific rendering set up that would prevent the crashing? 

(I never had problems with 2.79)

Best Regards

**Comment by Clockmender** [comment]
Is this problem related to Animation Nodes? If not you should not be posting here, try https://blenderartists.org/ as a good place to be for answers.

If its is AN related, we will need to know exactly that shows the problem related to what you are doing, so post a blend file at least, or an image of your node tree. But I have to say 2.8 is Beta software, or is it still Alpha? and as such is not officially released and therefore must be assumed to be un-reliable.

I would only use 2.8 for testing, never for production work and I would not be surprised if it crashed all the time, until it is released as "Stable and Fit For Purpose".

Cheers, Clock.

**Comment by OmarSquircleArt** [comment]
Yes, we are aware about this issue. However, we haven't been able to resolve it yet. It maybe related to a bug in Blender itself.

**Comment by OgierM** [comment]
Yup i do have the constant crashing aswell - but pretty much only in relation with AN. Additionally you should also disable Auto Execution in AN before baking anything, that usually results in a crash for me, too.

**Comment by VideoBombala** [comment]
Hi!
I solve the same problem with rendering by script. It's fine for me, render works very well:

```
import bpy

for step in range(1, 100):
    
    bpy.context.scene.frame_set(step)
    bpy.data.scenes["Scene"].render.filepath = 'd:/3D RENDER/2019 01 13/image.jpg_%d.jpg' % step
    bpy.ops.render.render( write_still=True )
```

**Comment by Patochun** [comment]
I confirm. You save my work.

**Comment by vrnico** [comment]
@VideoBombala 

Thanks for getting me past the crash!

**Comment by Strange-love** [comment]
Nice work

**Comment by uzikisi** [comment]
i make the renders using view> viewport render animation without a single
problem, it works perfect and very very quick.


i have a question but i don't know where i can ask it

i want to make this using animation odes but no chance, can someone help me?

Here is the example  https://www.instagram.com/p/BlqJY1QBDCA/

**Comment by RathalosArt** [comment]
@VideoBombala Hey i have a question about your code.
Does it work with the newest version of blender 2.8?
Because whatever i do i can't run it.
I'd love to hear from you because i really need the rendering process not to crash xD
Thank you ^^

**Comment by VideoBombala** [comment]
> @VideoBombala Hey i have a question about your code.
> Does it work with the newest version of blender 2.8?
> Because whatever i do i can't run it.
> I'd love to hear from you because i really need the rendering process not to crash xD
> Thank you ^^

Hi @RathalosArt  ! 
It really works with 2019-04-24 22:25 version and above.

Unfortunately the Animation nodes does not work with tne newest version which is 2019-05-22 21:50 (Win 64).
Just nothing happens, even no error. The picture does not change.

**Comment by RathalosArt** [comment]
@VideoBombala They work but not well, some keyframes don't work haha.

https://youtu.be/jPfBKezmr0A

The export as a video wouldn't work so i had to export each frame and put the video together manually.

**Comment by Ariqsniper** [comment]
> Hi!
> I solve the same problem with rendering by script. It's fine for me, render works very well:
> 
> ```
> import bpy
> 
> for step in range(1, 100):
>     
>     bpy.context.scene.frame_set(step)
>     bpy.data.scenes["Scene"].render.filepath = 'd:/3D RENDER/2019 01 13/image.jpg_%d.jpg' % step
>     bpy.ops.render.render( write_still=True )
> ```

can you explain it I don't know where it was written. whether it is written in the script in a blender or something.because I am still learning about this blender application and found the same crash.

**Comment by dragere** [comment]
@Ariqsniper the script was written in Python for Blender, but you shouldn't need it anymore. Please update your [Animation Nodes](https://blender.community/c/graphicall/Xdbbbc/) and [Blender](https://www.blender.org/download/).

**Comment by uzikisi** [comment]
Please provide a link for the latest version of AN

25 Tem 2019 Per 08:38 tarihinde dragere <notifications@github.com> şunu
yazdı:

**Comment by Aidelank** [comment]
Well, this problem still exists today, looks like we have to keep using this script...

**Comment by OmarSquircleArt** [comment]
@Aidelank Did you try using the latest 2.81 test build?

**Comment by OmarEmaraDev** [comment]
Lets continue the discussion in issue #1200 .
