### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by taji** [JacquesLucke/animation_nodes#1010]
This may already be available, but I'm not seeing it.  I'd like to be able to add a text comment node.  This node's only purpose is to document details about your node graphs.  A good example of this is found in the node based audio application Bidule by Plogue:

![image](https://user-images.githubusercontent.com/702031/51445772-7ac3be00-1cce-11e9-956a-4fc9b393418a.png)

The orange Comment_0 node doesn't have any connectors. But you can add this type of node as many times as you want.  Double-clicking the node opens the text window.  You can resize the text box for as large a text document as you wish (also supports scrolling).  On project load all text boxes are closed. 

(I know about Text Input node, but it only displays a single line)

Is this already available and I'm just missing it?

**Comment by OmarSquircleArt** [comment]
You can use frames to do that:
![Comments](https://user-images.githubusercontent.com/25300994/51465243-37219080-1d70-11e9-89d5-236cc3c3da04.png)

For single line comments, you can just edit the label of the frame. For multi-line comments, you can use a text block. You can also change the width, height, and color as you wish.

**Comment by taji** [comment]
Exactly what I was looking for. :-)  This is what I was looking for.  Details on how to add the frame:  Shift + A | Layout | Frame.
