### ISSUE TITLE
Trouble loading sound in Bake Sound node

### ISSUE THREAD

**Issue by Nikofant** [JacquesLucke/animation_nodes#1011]
Hey! I'm new to all of this, so bear with me :)

I'm trying to bake a sound to the Bake Sound note for use in an audio visualizer, but unfortunately it's not working correctly. This is what I do, First, I press [this](https://i.imgur.com/PP8igZw.png), and then [this pops up.](https://i.imgur.com/rBvAwLo.png). 

Do you know why this happens? And how to fix it?

**Comment by Nikofant** [comment]
It's working if I add it normally through the Video Sequence Editor, but why it's not working in AN, I have no idea...

**Comment by OmarSquircleArt** [comment]
Which AN version are you using?

**Comment by dragere** [comment]
I have a similar Problem:
I can load the sound in the node, but when baking average this error gets thrown:

> Traceback (most recent call last):
>   File "...\animation_nodes\operators\dynamic_operators.py", line 52, in invoke_InvokeFunction
>     return self.execute(context)
>   File "...\animation_nodes\operators\dynamic_operators.py", line 58, in execute_InvokeFunction
>     self.an_executeCallback(self.callback, *args)
>   File "...\animation_nodes\extend_bpy_types.py", line 28, in _executeCallback
>     executeCallback(callback, *args, **kwargs)
>   File "...\animation_nodes\operators\callbacks.py", line 25, in executeCallback
>     callback(*parameters, args, kwargs)
>   File "...\animation_nodes\operators\callbacks.py", line 40, in executeNodeCallback
>     getattr(node, functionName)(*args, **kwargs)
>   File "...\animation_nodes\nodes\sound\bake.py", line 158, in bakeAverageSound
>     soundData = bake(sound, low, high, attack, release)
>   File "...\animation_nodes\nodes\sound\bake.py", line 332, in bake
>     removeObject(object)
>   File "...\animation_nodes\nodes\sound\bake.py", line 346, in removeObject
>     bpy.context.scene.objects.unlink(object)
> AttributeError: 'bpy_prop_collection' object has no attribute 'unlink'


When baking spectrum blender crashes instantly with this error:

> Traceback (most recent call last):
>   File "...\animation_nodes\nodes\sound\bake.py", line 264, in invoke
>     self.timer = context.window_manager.event_timer_add(0.001, context.window)
> TypeError: WindowManager.event_timer_add(): required parameter "window" to be a keyword argument!
> 
> location: C:\Program Files (x86)\blender-2.80.0-beta\2.80\scripts\modules\bpy\ops.py:198
> 
> location: C:\Program Files (x86)\blender-2.80.0-beta\2.80\scripts\modules\bpy\ops.py:198
> Error: Traceback (most recent call last):
>   File "...\animation_nodes\nodes\sound\bake.py", line 264, in invoke
>     self.timer = context.window_manager.event_timer_add(0.001, context.window)
> TypeError: WindowManager.event_timer_add(): required parameter "window" to be a keyword argument!
> 
> location: C:\Program Files (x86)\blender-2.80.0-beta\2.80\scripts\modules\bpy\ops.py:198
> 
> Traceback (most recent call last):
>   File "...\animation_nodes\operators\dynamic_operators.py", line 52, in invoke_InvokeFunction
>     return self.execute(context)
>   File "...\animation_nodes\operators\dynamic_operators.py", line 58, in execute_InvokeFunction
>     self.an_executeCallback(self.callback, *args)
>   File "...\animation_nodes\extend_bpy_types.py", line 28, in _executeCallback
>     executeCallback(callback, *args, **kwargs)
>   File "...\animation_nodes\operators\callbacks.py", line 25, in executeCallback
>     callback(*parameters, args, kwargs)
>   File "...\animation_nodes\operators\callbacks.py", line 40, in executeNodeCallback
>     getattr(node, functionName)(*args, **kwargs)
>   File "...\animation_nodes\nodes\sound\bake.py", line 168, in bakeSpectrumData
>     frequencyRanges = [{"low" : item.low, "high" : item.high, "name" : ""} for item in self.spectrumFrequencyRanges])
>   File "C:\Program Files (x86)\blender-2.80.0-beta\2.80\scripts\modules\bpy\ops.py", line 198, in __call__
>     ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
> RuntimeError: Error: Traceback (most recent call last):
>   File "...\animation_nodes\nodes\sound\bake.py", line 264, in invoke
>     self.timer = context.window_manager.event_timer_add(0.001, context.window)
> TypeError: WindowManager.event_timer_add(): required parameter "window" to be a keyword argument!
> 
> location: C:\Program Files (x86)\blender-2.80.0-beta\2.80\scripts\modules\bpy\ops.py:198
> 
> 
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1
> Error   : EXCEPTION_ACCESS_VIOLATION
> Address : 0x00007FF794CD1E25
> Module  : C:\Program Files (x86)\blender-2.80.0-beta\blender.exe

I use Animation Nodes v2.1

**Comment by OmarSquircleArt** [comment]
@dragere The sound bake node was removed and replaced by a new sound system. This system should be available starting from next build.
