### ISSUE TITLE
Offtopic question. Please.

### ISSUE THREAD

**Issue by grinvaldsjanis** [JacquesLucke/animation_nodes#1015]
Sorry, it's not related with AN, but with the knowledge You most probably have.  I could not find any decent answer to my problem:

I would like to have a single material for multiple objects but change one or more properties inside the material(like colour, roughness, transparency), but anchored to a specific object. Is it even possible? Or should I make separate instances of material anyway and common things just keep in a material group?
It's just that those objects are multiple - about 70, and I would like to use same NLA Action for all of them in different times, but similar.

What would You recommend to do?

Thank You for not kicking!

**Comment by 3DSingh** [comment]
Hi @grinvaldsjanis ...
You can achieve this by assigning different **Vertex Color** to individual objects or **Object Index** (is a faster method) then use vertex color or object index to controls the color, roughness etc. of objects. This question is already answered by **Omar Ahmad** on blender.stackexchange.com, see "Coloring Objects" section: https://blender.stackexchange.com/questions/101299/render-100k-objects-each-with-independent-color-and-scale-through-time

**Comment by grinvaldsjanis** [comment]
Hi. ThankYou for an answer. My interest was to control individually single property of same material for about 70objects in the timeline - not procedurally. And some of the objects are text which should remain un-destructed.
While working today on objects it appeared that even some nodes in copied materials become multiuser - that made me even more frustrated.
