### ISSUE TITLE
Missing node input

### ISSUE THREAD

**Issue by alanbyvale** [JacquesLucke/animation_nodes#1019]
On the Mac version there is no location input node on the Object Transforms Output
<img width="211" alt="screenshot 2019-01-27 at 14 29 23" src="https://user-images.githubusercontent.com/43404322/51802249-fb8b3880-223f-11e9-8f47-b1e2b48f5f53.png">

**Comment by OmarSquircleArt** [comment]
To enable the location input, press the X, Y, and Z buttons on the first row.

**Comment by alanbyvale** [comment]
Thank you. Obviously not got my brain in gear today!
