### ISSUE TITLE
No nodes link in newer Blender 2.8 Daily Builds

### ISSUE THREAD

**Issue by xitnow** [JacquesLucke/animation_nodes#1021]
I am still new to Github, but I have been searching for weeks and have not seen this mentioned anywhere, so I want to make sure that this is either a problem that I need to (can) fix or that will get addressed in the next release.

I have tried to run animation nodes of every daily build of blender, but all versions after 2.80.37 are completely unable to connect or function in any way that I can see (including specific non-animation nodes).  I can try to submit this directly to the 2.8 builds but I was wondering if it is a known AN issue.

Here is a screenshot: 
![image](https://user-images.githubusercontent.com/47127646/51875566-826d0d80-2333-11e9-9a30-8813ca879505.png)
This is with Blender v.2.80.42
![image](https://user-images.githubusercontent.com/47127646/51875685-f3142a00-2333-11e9-9185-58acdb527272.png)

If any other information is needed let me know,
thanks,

**Comment by OmarSquircleArt** [comment]
Can you show us the output/errors printed in the console?

**Comment by xitnow** [comment]
Yeah that would have made sense to check first, here:

![image](https://user-images.githubusercontent.com/47127646/52017829-8c6b4980-24b6-11e9-9b1e-a18e9a233879.png)

(Also if there is a way to save the console to a log file I can do that too)

**Comment by xitnow** [comment]
I've tried again to do a fresh uninstall and a fresh install of Animation Nodes (2.1.3) to no avail.

And the console seems to give the same Attribute error under blender_ui.py

**Comment by OmarSquircleArt** [comment]
Yes, this issue is already fixed. New builds should work as expected. So wait for new builds to come.
