### ISSUE TITLE
Animation node 2.79-2.80 failed

### ISSUE THREAD

**Issue by Atsukicreater1** [JacquesLucke/animation_nodes#1022]
<img width="1280" alt="2019-01-30 3 25 28" src="https://user-images.githubusercontent.com/47065755/52011761-dcdaab00-24a6-11e9-99b1-876f207993a3.png">
<img width="1280" alt="2019-01-30 3 36 50" src="https://user-images.githubusercontent.com/47065755/52011767-e19f5f00-24a6-11e9-8ad2-7eda9bb793a8.png">

 Hello, I'm first time installed Animation Node i beed watching a lot video on youtube how to installed read on website about problem that i been have right now but still does not help me to fixed because i been have only one node installed and it's telling me that i have older version but i don't have any old version pls can some explain what i should to do because it's getting me really annoying. It's my third day that i been trying to solve this problem.

**Comment by denis130** [comment]
You need to uninstall the addon and remove the folder of the addon (animation_nodes), the folder location is displayed at the last line of the error message.

**Comment by Atsukicreater1** [comment]
<img width="1280" alt="2019-01-30 9 49 19" src="https://user-images.githubusercontent.com/47065755/52027388-407dcc00-24d9-11e9-9b47-06aa2a24c101.png">
 
Like that? it's still doesn't work
