### ISSUE TITLE
get random points on a mesh error!

### ISSUE THREAD

**Issue by jsanders2019** [JacquesLucke/animation_nodes#1023]
HI,I am newer to animation nodes, i want to get some random points on a mesh object via scripts in bleder 2.8,but i was in trouble ,as the screenshot below:
![2019-02-01_07-22](https://user-images.githubusercontent.com/45086977/52112143-9f118a00-2640-11e9-94e6-fbb5eb8b8826.png)

could you help me? Thanks in advaced!

**Comment by OmarSquircleArt** [comment]
[SE Link](https://blender.stackexchange.com/questions/131040/how-to-get-random-points-on-a-mesh-via-blender-animation-nodes-2-8)
