### ISSUE TITLE
Wiggle Action Node Failed

### ISSUE THREAD

**Issue by jsanders2019** [JacquesLucke/animation_nodes#1028]
Animation Nodes 2.1 in blender 2.8 Wiggle Action Node Fail,is it a bug?

![2019-02-09_12-44](https://user-images.githubusercontent.com/45086977/52516769-1e1f4780-2c6b-11e9-8796-fe4d2c8ff4f2.png)

**Comment by OmarSquircleArt** [comment]
Yes, I can confirm it. Thanks for the report !

**Comment by OmarSquircleArt** [comment]
Fixed in 75675a5.
