### ISSUE TITLE
Sound from Sequence doesn't accept many sound files - AN 2.1.3

### ISSUE THREAD

**Issue by aryarovana** [JacquesLucke/animation_nodes#1029]
I'm using Mac OSX Mojave 10.14.2, with latest Blender 2.8 update (Built with build bot Feb 8th), and I also had to compile the animation nodes 2.1 myself because the existing releases date back to December and I needed the updates in January. so far it worked fine everything else works fine I got the new nodes. and with some soundtracks it works, I tested it with a couple of music tracks, but it just seems to favor some over the other. It wasn't related to the format as it can read .mp3, .wav and .m4a. Also, it didn't have anything to do with bitrate I suppose I tried to match my sound quality with the bitrate of the ones that worked with no success.
Inside the attachment is a blend file with two soundtracks packed into, it's the default scene of the blender so nothing fancy, and I didn't even make any special arrangements in the node tree. it's just one node, and when you select the first Track (Mapping Mountains) it works quite fine, but if you switch to second one (Mystic Queen), it gets the red borders and it asks for a bug report or something.
I looked in the console too, there wasn't much:

`# Node: 'WaveMusic' - 'Sound From Sequence'
try:
    _sound_3dg1 = _3dgaak4ixtmfydu.execute(_sequence_3dg0)
    pass
except Exception as e:
    animation_nodes.problems.NodeRaisesExceptionDuringExecution('_3dgaak4ixtmfydu').report()
    raise`

![screen shot 1397-11-21 at 06 13 37](https://user-images.githubusercontent.com/7544542/52528767-28892200-2cfb-11e9-9b89-111d9ebcfc35.png)

[Bug Report For Animation Nodes 2.1 Sound from Sequence.zip](https://github.com/JacquesLucke/animation_nodes/files/2848475/Bug.Report.For.Animation.Nodes.2.1.Sound.from.Sequence.zip)

**Comment by OmarSquircleArt** [comment]
Thanks for the report! Fixed in a59577e.

**Comment by taharkaub** [comment]
Hey @aryarovana I have been trying to build the newer branches of AN with the new sound nodes for MacOS but have been running into an issue when building. Are you able to share how you got it to build from the source or your compiled AN zip?

**Comment by aryarovana** [comment]
@taharkaub Sure! this is the link to my compiled AN zip:
[animation_nodes_v2_1_macOS_py37.zip](https://github.com/JacquesLucke/animation_nodes/files/2858936/animation_nodes_v2_1_macOS_py37.zip)

and as for how to build:
You need python 3 and cython. type this in terminal to see if you got python3:

`python3 --version`

if it printed out `Python 3.7.0` you are good to go, if not download and install python 3.7 for macOS. then you need to install cython. and for that, you can either use conda (which is how I did it at first but it took 8 GB on my 128GB MacBook so I deleted it) or use pip. in order to install pip type this in terminal:

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
then:
`sudo python get-pip.py`
this should install pip, then all you need to do is to enter this in terminal:
`pip3 install cython`
careful to use pip3, cause in macOS the default python which comes with Xcode is 2.7 and pip installs cython for that version.
if you got this far, you need to build the AN from source, download the latest version from GitHub make sure you are in the correct branch (blender 2.8), then open the folder in terminal with something like this:
`cd /Downloads/animation_nodes-blender2.8`
then you gotta build it:
`python3 setup.py build --export --noversioncheck`

if you couldn't build you might need to install X-Code as well, also you might need to install gcc latest version too. if you got into trouble let me know :)

cheers
