### ISSUE TITLE
nodes for bone animation

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#103]

**Comment by AdmiralPotato** [comment]
I was about to animate a squid today and thinking that this would be the perfect task for Animation Nodes. This would be a nice feature to have. :)

:+1:

**Comment by enzyme69** [comment]
![screen shot 2016-09-19 at 11 10 05](https://cloud.githubusercontent.com/assets/3952687/18620640/ea98b070-7e59-11e6-983b-5ed67ffbfa95.png)

@JacquesLucke 
If I am not wrong, there is no convenient node to deal with Bones inside Armature yet? Hmm.... How to hack this.

**Comment by JacquesLucke** [comment]
You are right. There are no nodes for bone animations yet.
I'll look into this later, but at the moment I definitly have enouph other stuff to do.

**Comment by enzyme69** [comment]
Ok, it will be in the wishlist...

**Comment by scorpion451** [comment]
Suggestion: 
As a short term fix until you have time to create proper rigging nodes, create variants of the attribute node that can be given an armature and the name of a bone, and automatically parse that into "pose.bones({name of bone}).matrix" 

It's a little thing, but even something that simple would save a few seconds of copying, pasting, and typing each time I have to set one of those up. May not sound like much, but I mostly use this addon for creating semi-automated animation systems for complex character armatures. When I'm reading in information from a dozen bones to and outputting that info to a dozen other bones, all that typing gets tedious pretty quickly.

**Comment by JacquesLucke** [comment]
Thanks for the suggestion. I still don't know much, and I'm not really a fan of short term fixes..
Not sure if this will make into the next release, however you can quickly create such a node for youself:

![set bone location](https://cloud.githubusercontent.com/assets/5881326/23897658/41b7c5b0-08ae-11e7-8b5c-3a077714178f.PNG)

Hope it helps :)

**Comment by scorpion451** [comment]
That does help!

I didn't know that's what the expression node did; that's basically the last paragraph of my suggestion, right there.  ^_^

**Comment by enzyme69** [comment]
Thanks for the Expression and Group example, @JacquesLucke Interesting!

If we modify it so it works with Script Node:
![screen shot 2017-03-15 at 16 38 45](https://cloud.githubusercontent.com/assets/3952687/23935097/fb70e384-099d-11e7-983a-4725f3fbe5ac.png)

**Comment by enzyme69** [comment]
Tested the expression + group method, with Script Node to get all names of bones.
![screen shot 2017-03-15 at 16 41 12](https://cloud.githubusercontent.com/assets/3952687/23935136/389e6cfe-099e-11e7-947b-9e461c5dd58e.png)

```
import bpy

BoneNames = []

ob = bpy.data.objects['Armature']

for bone in ob.pose.bones:
    BoneNames.append(bone.name)
    

```

**Comment by scorpion451** [comment]
Thought I'd share some of what I came up with:
This one reads and outputs all the transform info from a bone in one handy package.  
![bone-nodes-input](https://cloud.githubusercontent.com/assets/11708455/23963591/be9280b2-097f-11e7-8ef9-2a91a989be0b.png)
In the process of messing around with this one I accidentally figured out something interesting, too: for bones, the .matrix property is the bone's absolute pose space matrix. The .matrix_basis property is the bone's local transform matrix. Some experimenting revealed that you can only control one of these at a time, but being able to look at the absolute position of a bone while controlling it's local position still opens up a lot of interesting potential. (I'm currently playing with basic ragdoll setups!)

**Comment by scorpion451** [comment]
Did some more messing around, came up with this:
![bone-properties-2](https://cloud.githubusercontent.com/assets/11708455/24120041/33a4e20a-0d81-11e7-9cb8-e3cf5dd3fd01.png)
[bone properties.txt](https://github.com/JacquesLucke/animation_nodes/files/856256/bone.properties.txt)

Probably a towering monument to inefficient computing, but you give it an index number for a property in that text file, it looks up the corresponding name and returns that and the property's current value.

If nothing else, it's a great way to browse what information is actually available in an instant-feedback sort of way; from there I can make a hard-coded node to pull up a desired property more efficiently.

**Comment by enzyme69** [comment]
Ideally, it should become some kind of drop down list :) Next door, at Sverchok, we are trying to sort this Object ID stuff.

**Comment by enzyme69** [comment]
@scorpion451 .matrix property is the bone's absolute pose space matrix. The .matrix_basis property is the bone's local transform matrix.  ==> are these really true bone position?

My Blender Bone familiarity is very basic, so far I am seeing Armature as Edit Bone and Pose Bone. 

So far, I am animating the OFFSET via Pose Bone. The default value is the Edit Bone.

BBones (Bendy Bones) is interesting and can have more control, different way of controlling it.

For someone who understand technical rigging and animation, and good with Math, Animation Nodes can probably work as it is for rigging... maybe building nodes along the way.

The thing with Animation Nodes, I imagine if one day somebody ported all Blender Constraints as Nodes for use inside it, that will be interesting then.

**Comment by scorpion451** [comment]
> @scorpion451 .matrix property is the bone's absolute pose space matrix. The .matrix_basis property is the bone's local transform matrix. ==> are these really true bone position?

So long as the armature object is at (0,0,0) and is not rotated or scaled, then pose space will be the same as world space. If you want to calculate absolute world position after you've moved, scaled, or rotated the armature as an object, you need to multiply the pose space matrix by the armature's matrix:
![pose-space-to-world-space](https://cloud.githubusercontent.com/assets/11708455/24156943/09789db4-0e26-11e7-90f2-a953b10bd3bb.png)
 
> For someone who understand technical rigging and animation, and good with Math, Animation Nodes can probably work as it is for rigging... maybe building nodes along the way.

It works beautifully, really, especially now that I know about the expression node and I can really start cobbling together exotic things! 

One example I've been working on is a node that writes vectors or quat rotations to a text file, and another node that reads them back in (cutting them up into chunks that the parse number node could plug into "combine" nodes was the tricky part).  Now that I've got a way to cache information between frames, I can turn that into a node that calculates instantaneous rotational speed and linear velocity. Once I have the bugs worked out from _that_, I can begin work on the true alchemist's stone: bone physics nodes! 8D

**Comment by enzyme69** [comment]
This thread is still pretty wild for my brain. AN Bone access, perhaps constraints.... might be cool.

**Comment by hunter0012** [comment]
i hope there will be something like retargetting nodes for motion captures and stuff like coping bone rotations with offset from one character rig to another with the ability to add some mathematics for copying and blending rotation from more then one source (character rig) if anyone knows a good book or video tutorials on how to do this kind of stuff with python to expose it in animation node i would love to know about and i will try to make a retargetting nodes

**Comment by Clockmender** [comment]
Is this helpful?

![screen shot 2018-12-18 at 17 13 30](https://user-images.githubusercontent.com/29657804/50170667-5a2bd100-02e8-11e9-9571-24814cabb025.png)

The nodes I made ^^ and the page in my [website](https://clockmender.uk/blender/animation-nodes/bones/) explains how they are used. I had to make a "Bone" socket, not too arduous a task.

Just bear in mind that you may need to do some vector maths to cope with any offsets from the Armature to Global origin, again, pretty easy to do. Maybe these can be incorporated into AN at some time...

I don't know of any book, or tutorial, I just worked it out for myself and am happy to help here if I can.

Cheers, Clock.

**Comment by hunter0012** [comment]
sorry to bother, thanks a lot
just a one more think i had a bone copy location from another one and i
can't figure out how can i bake the animation to keyframes so i can export
it to game engine
again sorry to bother and thanks so much

**Comment by denis130** [comment]
You can use a script node for that, I didn't find another way to do that. It's a bit slow so you will have to use AV sync or Frame Dropping.
```
if record:
    for p_bone in bpy.data.objects["Armature"].pose.bones:
        p_bone.keyframe_insert("rotation_quaternion", frame = bpy.context.scene.frame_current)
        p_bone.keyframe_insert("location", frame = bpy.context.scene.frame_current)
```

**Comment by hunter0012** [comment]
awesome thanks again
i really need to read the python api

**Comment by denis130** [comment]
@JacquesLucke is it possible to integrate the bone sockets that @Clockmender have made? and also a node that inserts keyframes for bones?
