### ISSUE TITLE
[Blender 2.8] Crash when baking sound

### ISSUE THREAD

**Issue by SolarLiner** [JacquesLucke/animation_nodes#1030]
Trying to bake a sound from Animation Nodes crashes Blender 2.8.

**Steps to reproduce**:

1. Add a Bake Sound node
2. Load an audio file
3. Press Bake (either one, though they give different tracebacks)

I've included the Blender crash reports in the attached files:
[blender.crash_amplitude.txt](https://github.com/JacquesLucke/animation_nodes/files/2849384/blender.crash_amplitude.txt)
[blender.crash_spectrrum.txt](https://github.com/JacquesLucke/animation_nodes/files/2849385/blender.crash_spectrrum.txt)

**Comment by OmarSquircleArt** [comment]
Thanks for the report! But the Bake Sound node was removed and replaced by a better sound system. New builds should have this new feature.

**Comment by SolarLiner** [comment]
Oh that's exciting! Can't wait to try it out!

**Comment by OmarSquircleArt** [comment]
@SolarLiner A sneak peak:
https://twitter.com/OmarSquircleArt/status/1084881010234404864
I also shared the blend file somewhere in this tweet chain, so you can it it.

**Comment by SolarLiner** [comment]
I was planning on doing something else but now I'll just get a build of AN going just to play with this!
