### ISSUE TITLE
Visibility node causes render crash in v2.1 for Blender 2.8

### ISSUE THREAD

**Issue by patrickhill** [JacquesLucke/animation_nodes#1036]
I'm using a compare statement to toggle the visibility of two objects which causes a render crash.

<img width="887" alt="screen shot 2019-02-21 at 7 28 03 am" src="https://user-images.githubusercontent.com/2302078/53169138-73802080-35aa-11e9-9c07-a089e9eaf56b.png">

Blender version:
<img width="523" alt="screen shot 2019-02-21 at 7 32 56 am" src="https://user-images.githubusercontent.com/2302078/53169332-f0ab9580-35aa-11e9-9f70-f3c73a10b081.png">

**Comment by OmarSquircleArt** [comment]
I don't think it is particularly related to the node itself, Blender crashes whenever we render any animation computed using AN. But I will try to replicate it.

**Comment by OmarEmaraDev** [comment]
Lets continue this discussion in issue #1200.
