### ISSUE TITLE
AN 2.1 Blender 2.79 How to Install

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1037]
Hello @OmarSquircleArt I have some questions please.

You said in another thread that I can install AN 2.1 on my Mac, but I have no idea how to do this, or where to get the full source from, having spent a lot of time looking for such a release, so:

1) Are you planning a release of 2.1 for Blender 2.79?
2) if not where do I get the latest source code from?
3) What do I need to do to make an installation zip file?
4) Can I add my own nodes to the source to make a modified installation for myself?
5) Some of my nodes depend on PyGame and SoundDevice python libraries, so can I add these into the Add-on and if so how? I know where to get the .whl files from, but it might be better to copy these libraries to a sub-directory of AN and reference them from there (environment variable perhaps?), I am thinking of the Blender-App/Resources/.../Site-Packages entries for these two libs. This is where I installed them and  think there were some other bits that also got installed there:

![screen shot 2019-03-04 at 15 49 10](https://user-images.githubusercontent.com/29657804/53744545-272fbd00-3e95-11e9-8c93-9807977c51cf.png)

I think it was everything that went in on 15 Jan 2019...

Any help gratefully received as one day I hope to be able to make my own full AN Add-on for 2.8.

Thanks, Clock.

**Comment by OmarSquircleArt** [comment]
There are official test builds for AN v2.1 Blender v2.79 Python v3.6/v3.5, you can find that [release here](https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_testbuilds_2).

1. I don't think that such a release will happen. All development will happen to 2.8 from now as far as I know.
2. The latest source for v2.79 is available in the `v2.1` [branch here](https://github.com/JacquesLucke/animation_nodes/tree/v2.1).
3. You will need to compile Animation Nodes from source. To do this, you will need three things. Those things are easily available through any package manager, do you have a package manager in OSX? I will give you more details once you setup your development environment.
4. Sure, make the modification to the source, compile again and you are good to go.
5. I don't know how things work in OSX, but that should work.

**Comment by Clockmender** [comment]
Thanks for the reply, I have "Homebrew" installed -  https://brew.sh

Will that do the job?

**Comment by OmarSquircleArt** [comment]
Yes, brew seems like the thing we need. Install the `cython`, `gcc`, and `python` packages.

**Comment by Clockmender** [comment]
I think `python` is already installed on my Mac, or is that a Brew Package? Sorry for delay in replying...

**Comment by OmarSquircleArt** [comment]
I don't know honestly, can you execute `python -V`? Forget about python for now, we will to it later if needed.

**Comment by Clockmender** [comment]
users-MacBook-Air:~ mac$ python -V
Python 2.7.15
users-MacBook-Air:~ mac$

**Comment by OmarSquircleArt** [comment]
Ah, no, that won't work. Do you have something that depends on python 2?

**Comment by Clockmender** [comment]
Not sure, it came with MacOS I presume... I have tried to install python and the terminal is just sitting there saying:

```
users-MacBook-Air:~ mac$ brew install cython
Updating Homebrew...


```

**Comment by OmarSquircleArt** [comment]
I guess you should wait for it to update. Can you execute `brew list | grep python`?

**Comment by Clockmender** [comment]
users-MacBook-Air:~ mac$ brew list | grep python
python
python@2
users-MacBook-Air:~ mac$ 

Brew is now downloading...

and it did this: `Pouring python-3.7.2_2.high_sierra.bottle.tar.gz`

**Comment by OmarSquircleArt** [comment]
Good, that means it have both python version. Carry on.

**Comment by Clockmender** [comment]
I have downloaded and extracted the source zip file... Should I add my stuff to that now?

**Comment by OmarSquircleArt** [comment]
Did you download from the release page?

**Comment by Clockmender** [comment]
From this: `The latest source for v2.79 is available in the v2.1 branch here.` (in your reply reply, is that right?), or should I take this: `There are official test builds for AN v2.1 Blender v2.79 Python v3.6/v3.5, you can find that release here.`

**Comment by OmarSquircleArt** [comment]
If you don't mind, I have some homework to do now as it is due tomorrow morning. Can we carry on tomorrow?

**Comment by Clockmender** [comment]
Of course, sorry I am being a bit "slow" today...

**Comment by OmarSquircleArt** [comment]
The problem is that github only provides the zip for the master branch, not the one we want. So download the one from the release page. [This one.](https://github.com/JacquesLucke/animation_nodes/archive/v2.1_testbuilds_2.zip).

Have to go now, will talk to you tomorrow.

**Comment by Clockmender** [comment]
Thank you, talk tomorrow.

**Comment by OmarSquircleArt** [comment]
@Clockmender I just realized that this source file is not the latest. You will have to clone it directly. I assume you have `git` installed, if not, install it. Then execute the following:

```
cd your_preferred_directory
git clone https://github.com/JacquesLucke/animation_nodes.git
cd animation_nodes
git checkout v2.1
```
Where `your_preferred_directory` is the directory where you keep your sources. This downloads the latest source and switch to the v2.1 branch.

Also, what python version is your blender linked with? Is it bundled? You can know that from the python console inside blender.

**Comment by Clockmender** [comment]
So sorry, I have not been able to get on this today, Mrs. C has been unwell, maybe tomorrow. I am fairly sure the bundled python is 3.5

Thanks, Clock.

**Comment by OmarSquircleArt** [comment]
I think you can make blender fallback to the system python by removing the bundled python, but your version have to match. So it may not work. Where did you download this blender build? I think latest blender 2.79 uses python 3.7, so downloading that should solve all of our problems.

**Comment by OmarSquircleArt** [comment]
If 2.79b tuned out to use 3.7 as I predicted. Then you should install it from `brew cask` instead of downloading it manually.

**Comment by Clockmender** [comment]
I normally use the latest Official Release, but I also have:

![screen shot 2019-03-06 at 18 24 18](https://user-images.githubusercontent.com/29657804/53904062-18840a00-403d-11e9-8e51-4dd1bf407d3c.png)

Which uses Python 3.6.2, which is no good either...
`
PYTHON INTERACTIVE CONSOLE 3.6.2 `

So I think I will probably wait for 2.8 and AN2.1 Official Releases, whenever that happens, I am not sure it is worth putting in huge effort for something that will become redundant very shortly. My additional nodes can be aded manually to AN very easily, so maybe that is the best option.

Are there things in 2.1 for B-2.79 that are worth chasing, given that they were last worked on some time ago?

What do you think?

**Comment by OmarSquircleArt** [comment]
I see. Yah it will probably take some effort to get it to work in the current state. Is there a reason why you don't want to use 2.8 right now?

Are you asking what features were added fro, 2.0 to 2.1 for b2.79?

**Comment by Clockmender** [comment]
> Are you asking what features were added fro, 2.0 to 2.1 for b2.79? Yes, were there any major changes?

I am a bit reluctant to go with 2.8 just now as it seems to change every day! I have this version:

![screen shot 2019-03-06 at 18 37 48](https://user-images.githubusercontent.com/29657804/53904867-fa1f0e00-403e-11e9-9b6c-ba8af0fd19b2.png)

But I don't have AN for it yet, I guess it's a time issue of getting down to learning how to compile AN for Blender. I have never done this before, so maybe I am a bit lazy in my old age (over 60) to learn something that will go away with an official release of AN.

Also I understand I will need to change all my nodes to use the new ErrorHandling routines rather than label messages. That is quite a lot of work. given how many nodes I have made. Also I need to see if any of them are obviated by what you have done in the new 2.1 for b-2.8. Maybe lots of other things as well. I made a new "Bone" socket, that may be obsolete under AN2.1? if not it will need looking at also.

I have updated my MIDI Bake node, just now, to use Dictionaries and external common functions stored in a python file in the node directory, to make things more efficient and in line with more modern practices than I learned when I was working.

**Comment by OmarSquircleArt** [comment]
I believe most of your nodes will work out of the box, you don't have to use UI Error Extensions, in fact, not all nodes use them. So don't worry too much about your nodes, they will work with little to no modifications.

A lot of things were added to v2.1, here are some of the things I can remember:

- Virtual Lists: They are lists that can extend/repeat themselves if they are short, or fill themselves if they are empty. They allow us to do some effects very easily. [An example.](https://twitter.com/OmarSquircleArt/status/976174667743494146)
- SIMD noise: A very fast noise functions were added. This allows us to do things like:

![](https://i.stack.imgur.com/epT3l.png)

and:

![](https://i.imgur.com/kQNdkjf.gif)

- L Systems: There is now a node that can make L Systems. This allow you to make tree structures and the like. [Example.](https://twitter.com/robert_trirop/status/979806449198125056).

- Actions: There is now a new type called Action. It is an abstract representation of animations. Can be used to make all sort of cool animations. Not really finished though.

- Variouse nodes were added/vectorized/optimized: Including more mesh generation nodes, more offset nodes, more falloff nodes, ...
- Variouse Speed ups and optimizations.
- Workflow improvements: Sockets now remembers their configurations and reconnect automatically.
- Probably more, but thats what I remember now.

**Comment by Clockmender** [comment]
Thanks for that! I will get latest 2.8 at the weekend and have a play. What do I need to do to get AN 2.1 on it?

**Comment by OmarSquircleArt** [comment]
Jacques just released new Mac builds for 2.8 a minutes ago. Download the builds from [here](https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1.4), install it and you should be good to go.

**Comment by Clockmender** [comment]
Thank you! I'll try it in a day, or so. Lots to do tonight....

**Comment by OmarSquircleArt** [comment]
Alright, let me know if you need anything. Should we close this issue?

**Comment by Clockmender** [comment]
Yes, I think it is now resolved - thanks for your help.
