### ISSUE TITLE
undefined symbol in Blender2.8 branch Linux compile

### ISSUE THREAD

**Issue by sorinv** [JacquesLucke/animation_nodes#1038]
After compiling and installing in Blender, I get this error when Blender opens:

ImportError: /blender-2.8/2.80/scripts/addons/animation_nodes/libs/FastNoiseSIMD/wrapper.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN22FastNoiseSIMD_internal16FastNoiseSIMD_L3C1Ei

OS: Centos 7
Python: 3.7.2

Any ideas what I can do to go past this issue?

**Comment by JacquesLucke** [comment]
Is gcc available in your terminal?

There was probably an error when compiling the FastNoiseSIMD library. Unfortunately the build process does not stop as it should sometimes in this case.

This library is build directly after the Cythonizing is done. Can you see if there are any errors?

**Comment by JacquesLucke** [comment]
The error probably happens when this script is executed.

https://github.com/JacquesLucke/animation_nodes/blob/blender2.8/animation_nodes/libs/FastNoiseSIMD/source/compile_linux.sh

**Comment by sorinv** [comment]
You are correct that the error comes from compiling that library. However, it seems to be caused by something else, not a lack of gcc. Here's the error message I get:

```
In file included from FastNoiseSIMD_avx2.cpp:48:0:
FastNoiseSIMD_internal.cpp: In function ‘SIMDf L3_FUNC_CellularValueEuclideanSingle(SIMDi, SIMDf, SIMDf, SIMDf, SIMDf)’:
FastNoiseSIMD_internal.cpp:293:47: error: ‘_mm256_undefined_ps’ was not declared in this scope
```
Any ideas if I'm missing a library? There seems to be no information on the net about this issue.

**Comment by sorinv** [comment]
In the end I had to follow this step from the library compile guideline:
If AVX2 in unsupported on your compiler, disable AVX2 compilation by commenting out "#define FN_COMPILE_AVX2" in FastNoiseSIMD.h

https://github.com/Auburns/FastNoiseSIMD/wiki/Compiler-Settings

Even though my compiler should support AVX2.

**Comment by JacquesLucke** [comment]
Looks like I never had to deal with a compiler that does not support AVX2. Glad you figured it out.
