### ISSUE TITLE
Line Operator Node display error!

### ISSUE THREAD

**Issue by jsanders2019** [JacquesLucke/animation_nodes#1040]
I used line operator node to generate a line mesh,i can not see it in the 3D viewport in object mode but in editor mode,is it a bug?
![peek an bug](https://user-images.githubusercontent.com/45086977/53932090-f89f2580-40d2-11e9-9687-901b528e52ce.gif)

**Comment by OmarSquircleArt** [comment]
I can replicate that. It seems Animation Nodes is doing as expected. So, this is likely a bug in Blender and you should report that to Blender instead.
