### ISSUE TITLE
The Convert Plane Type Node seems to be broken for me

### ISSUE THREAD

**Issue by ogierm** [JacquesLucke/animation_nodes#1047]
I tried to recreate [this](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/geometry/project_point_on_plane.html?highlight=project%20point%20on%20plane) setup from the documentation. This happens:

![image](https://user-images.githubusercontent.com/29630575/54156965-9e41f400-4447-11e9-8f37-1df755c85f44.png)

**Comment by OmarSquircleArt** [comment]
Fixed in 08b995a.
