### ISSUE TITLE
How do I use the new sound spectrum for falloff?

### ISSUE THREAD

**Issue by jonnelafin** [JacquesLucke/animation_nodes#1051]
So I don't have any idea how to use this type of a node, so could give me a little tip for that?
![Capture7](https://user-images.githubusercontent.com/29503504/54479153-c011f100-4822-11e9-8cc5-7a851e5de871.PNG)

**Comment by OmarSquircleArt** [comment]
If you are asking how to construct a falloff from it, just use a *Custom Falloff* node. The node itself is straight forward, time goes in, spectrum data goes out.

![Node Tree](https://user-images.githubusercontent.com/25300994/54480228-8c3cc880-482e-11e9-8e30-94c7a9a8c17f.png)

**Comment by jonnelafin** [comment]
Thanks! Solved my problem just great!
