### ISSUE TITLE
AN error while trying to activate the add-on.

### ISSUE THREAD

**Issue by HafeezDembos** [JacquesLucke/animation_nodes#1052]
I get this error when trying to activate AN after I have installed it.
![AN_error](https://user-images.githubusercontent.com/27173073/54562398-351e2b80-49c7-11e9-9f2c-d8a8ff52643a.png)

**Comment by HafeezDembos** [comment]
These are the latest releases of AN and of Blender, as of today.

**Comment by OmarSquircleArt** [comment]
Can you try removing the the addon entirely and install it again?

**Comment by HafeezDembos** [comment]
It seems like it activated after the error.

**Comment by OmarSquircleArt** [comment]
What do you mean by "after the error"?

**Comment by HafeezDembos** [comment]
I left blender open since yesterday (after it gave me the error when I tried to activate the add-on), so when you told me to try uninstalling it, I went to do so in the add-ons tab and saw that Animation nodes 2.1.4 is checked. 
I hope I made sense.

**Comment by OmarSquircleArt** [comment]
But the error is still printed on the terminal?
