### ISSUE TITLE
Adding sound falloff produces an error

### ISSUE THREAD

**Issue by toshicg** [JacquesLucke/animation_nodes#1053]
Blender 2.8 daily build
![image](https://user-images.githubusercontent.com/48702545/54575869-4273fe00-4a39-11e9-8250-66281415a72f.png)
Animation Nodes v2.1.4 

When I try to add a sound falloff I get an error
![image](https://user-images.githubusercontent.com/48702545/54575932-89fa8a00-4a39-11e9-8ff5-c075df256aa8.png)

**Comment by OmarSquircleArt** [comment]
The sound falloff node was removed for now, but it will be added later. We just forgot to remove the menu entry.
