### ISSUE TITLE
No "Sound Falloff" node in v2.1.4 

### ISSUE THREAD

**Issue by zanovis** [JacquesLucke/animation_nodes#1059]
There seems to be no node for Sound Falloff in this build!

**Comment by OmarSquircleArt** [comment]
The node was temporarily removed and will be added later. Will probably be available the next build.

**Comment by ViRiXDreamcore** [comment]
There also seems to be no Bake Sound node. Is this for the same or similar reason?

**Comment by zanovis** [comment]
Correct. With the new AN build, frequency spectra will be computed in real
time and won't require the extra button presses.

**Comment by 3pointedit** [comment]
Not having to bake will be great! Looking forward to the return of sound nodes

**Comment by OmarSquircleArt** [comment]
The Sound Falloff node was just added in #1075.
