### ISSUE TITLE
I need to send you a private file, I have a crash when trying to render, and it happens only with Animation Nodes enable

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#1060]
I need to send you a private file, I have a crash when trying to render, and it happens only with Animation Nodes enable so I want to share with you the project file, but I have to do it privately since it is from a current project.

In the end I get an Out Of Core error, but it only happens when I have animation nodes enabled (and used of course).

Cheers!

**Comment by OmarSquircleArt** [comment]
We are aware about the crashes during rendering. Unfortunately, this is a bug in blender itself and we will have to wait until they resolve it. You can follow this on [T60094](https://developer.blender.org/T60094). If after this get fixed you still experience the bug, we will investigate your crash separately.

**Comment by juangea** [comment]
Ok... now with today's code (25/03/19) I get a crash trying to enable Animation Nodes addon :P

**Comment by OmarEmaraDev** [comment]
Lets continue this discussion in issue #1200.
