### ISSUE TITLE
Bake Particles could cause bledner crash

### ISSUE THREAD

**Issue by Tokenyet** [JacquesLucke/animation_nodes#1062]
I'm forced to restart my computer a copule of times, and found the problem eventually...

In my scene, I just use 1000 cubes particle from a plane, and just hit the bake button. The memory usage would be increascing to my Memory Maximum, and the problem is I use a bunch of AN nodes.

Eventually, I stop the Execution of All nodes, and could bake It without breaking blender (and my computer, tho).

I thought If there should be a mechanism to prevent AN Execution when particles are baking? If not, this could cause the terrible problem potentially.

**Comment by OmarSquircleArt** [comment]
This seems like something you should take care of. Why are you executing while baking? Is due to frame change automatic execution?
Also, isn't baking a blocking operation? Won't other operations stop until it is done?

**Comment by OmarEmaraDev** [comment]
Fixed in #1294 and b1ac938.
