### ISSUE TITLE
Suggestion: Clear All Caches

### ISSUE THREAD

**Issue by zippy731** [JacquesLucke/animation_nodes#1063]
Please add a "Clear All Subprogram Caches" button to the left tools panel.

I use subprogram caches in AN subprograms a lot. However, if I want to clear the caches, I need to walk through the various nodes and click "clear cache" individually. This is tedious and error prone on complex node trees.

Is there any built-in way to reset / clear all the subprogram caches at once?  I did not see any mention in docs nor tutorials I've seen.

If not, it would be a nice feature to add.

**Comment by OmarSquircleArt** [comment]
Looks like a nice feature to add. We will look into it.
