### ISSUE TITLE
Sound Nodes and AudaSpace

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1064]
This is not an "Issue" as such, more a request for information. Are you familiar with this:

https://github.com/neXyon/audionodes

and

https://archive.blender.org/wiki/index.php/User:NeXyon/GSoC2010/Audaspace/

I have been asked to look at this and see if it is possible to use either the Aud python library, or some of these nodes, or the code in them, in Animation Nodes, with the purpose of making a "simple" system to compose and playback music.

The basic design would be something along the lines of animated objects, or a "Piano Roll" type structure that causes sound clips to be played, probably small .ogg files perhaps. The system needs to be able to play multiple sounds simultaneously and this can be achieved with "AudioNodes" as linked above. There are generators in here that will make notes and also some filters, so for example it can generate a note of 440Hz and play that for say 1 second.

The first issue for me, I have got the Aud library to work in a simple script node, is that the execution stops and restarts at every frame change. This means that an audio clip is not played in its entirety, so the real question is:

Is it possible to start an event of playing a sound at one execution of AN and have it persist until it's time setting is fulfilled? In other words, start playing a sound at say frame 50 and have that sound continue to play until frame 100?

**Comment by OmarSquircleArt** [comment]
Yes, I am familiar with AUD. I actually did something very similar a while ago, you can see my test here: https://twitter.com/OmarSquircleArt/status/849336903044390913

This was done using the SoundDevice library though, because AUD didn't support certain things at the time. The problem you are facing may be related to your sound configuration. I had to spend sometime to configure my ALSA or Pulse Audio sound environment to support software and hardware mixing. See this: https://github.com/spatialaudio/python-sounddevice/issues/81#issuecomment-312508285

**Comment by Clockmender** [comment]
OK thank you! I got this far before reading your reply:

![Screen Shot 2019-03-26 at 12 01 17](https://user-images.githubusercontent.com/29657804/54995607-fc7de380-4fbe-11e9-8cf4-33ba80d070bb.png)

the Code is the script node is this:

```python
import aud
device = aud.device()
s = aud.Factory(file)
if play:
    device.play(s)
```

Simple beyond belief I know, but it gets me started! My "Periodic Trigger" is used to activate the play function, or the rotation of the two key objects. These need to change to just one frame keyed at a rotation, rather than many as I have at present, so the sound is only triggered once. I will then look at generating sounds, once I have the playback sorted.

This plays multiple sounds at once (something I couldn't get Sounddevice to do...), the problem is that the files don't get played in their entirety, the next execution on AN stops the sound, or starts it again at the beginning. So, I need to understand how you "threaded" the system so it sends the sound off to the device and lets it play to the end. I will study this at some length to get my head around it.

thank you for your help, how are your exams going?

**Comment by Clockmender** [comment]
Yay!!!! Got it to work:

![Screen Shot 2019-03-26 at 17 09 16](https://user-images.githubusercontent.com/29657804/55018066-f9e4b380-4fe9-11e9-9d24-e5c813696a8d.png)

I don't need all the frequency generating nodes you have used with SoundDevice because AudaSpace has a very nice function, here is a code snippet from my node: 

```python
            dev = aud.device()
            snd = aud.Factory.sine(freq,samples)
            if self.squaB:
                snd = snd.square(self.squaV)
            snd = snd.limit(0,duration)
            handle = dev.play(snd)
```

The `Factory.sine` bit, which you can then square and apply filters to, although I have not done that bit yet. The secret to success was stopping the node executing before the note was played in full. this I did by storing all the "handle" parameters in a dictionary and only allowing a new note to be made if the old one had expired. The `limit(0,duration) `bit sets the time for the note to start and stop playing, this is in seconds.

The good thing is that AudaSpace plays multiple notes at the same time. I have built a lookup function in an external .py file that translates the note input into a frequency.

Next I need to drive this from some form of animation, like a piano roll, or animated piano keys.

Thank you very much for pointing me in the right direction and sorry I got a bit pissy last week...

**Comment by OmarSquircleArt** [comment]
@Clockmender But wouldn't simultaneously playing the same note be necessary to implement things like chords?

Exams are going fine, still 4 to go though, thanks for asking!

**Comment by Clockmender** [comment]
OK I see your point, but, if you consider a pianists for example, they can only play one note once at a time, they can play it as part of a chord, with other notes, then play it on its own then as part of a second chord.

So, If I play a simple C major, I play C, E & G, then might play E major, so I play E G# & B. E is in both chords, but I would release C, E & G, if only for a split second before pressing E, G# & B. What I am trying to say is there is never a requirement to play an individual note twice at once for one instrument, but there is a need to play more than one note at any time.

To complicate matters, I might have two instruments in my animation, so I might have a keyboard and a saxophone - now I do need to play the same note twice simultaneously, once on the piano and once on the sax. To accommodate this, I have one node for the piano and one for the sax, so the piano note might only last half a second and the sax note might last 2 seconds and start at the same time as the piano. This can be accommodated by two nodes playing the same note, say E5, at the same time, but with different filters applied so they sound differently.

In order to maximise performance of the system I am thinking that I need to work out how many notes are going to be played simultaneously at any time in the piece. The maximum might be only 8 notes (I have only got 10 fingers after all!), in which case I need only 8 of the new node I just made. I can then "read" all the inputs and put them in a list, then send the first note information to the first node, the next to the second node, etc. It would not be very difficult to know when a node is free to be used again, simply by reading the dictionary contained in it as this holds its "release" frame. Bear in mind the node I have just written takes only a note name, duration and volume, so it can play E4, stop for 1 frame, then play C7 with ease. Once I have added the filters, it can play two different instruments, one after the other.

One of my most played tunes is "The Entertainer" by Scott Joplin, as my memory serves me, there are 55 individual noted played, but never more than 7 at once. So to do this I would only need 7 of my nodes.

Sorry to ramble on, but I think my logic stacks up. I thought long and hard before making the node, to make sure it was as flexible as possible. I intend adding other inputs to take care of filters and echo for example, a long way to go still and if you see any faults in my logic, please let me know.

Cheers!

PS. I have just done a quick test and played a scale, each note separately, and it only needs one node as only one note is being played at any point in time. If I add an underlying 3 note chord, I still only need 4 nodes to play potentially any chord and any note anywhere on the piano keyboard.

**Comment by OmarSquircleArt** [comment]
I see. That make sense. Thanks for clarifying that. I might do some tests to see the capabilities of AUD at some point. Are you developing this on a branch on your fork? I can't seem to find it.

**Comment by Clockmender** [comment]
There's nothing uploaded yet, but I will try to get this node on in a day or so. I know that you can join sounds with Aud, so one option for a chord is to get the base note and make a sound of that then join the next note, then join the last note to the previously joined pair.

As I understand it you can only join two sounds at once. So a "chord" node would only want the base note, say C3 and it would then get the frequencies for E3 and G3 from my function script, then make the three sounds, join them together and the play the resultant sound. This would be a more efficient way to go, I will try this tomorrow, it's getting late for me now... Full 5 note chords could also be done automatically from just the base note, just needs a more complex lookup function.

**Comment by Clockmender** [comment]
This comment seems to have disappeared:


'OK I see your point, but, if you consider a pianists for example, they can only play one note once at a time, they can play it as part of a chord, with other notes, then play it on its own then as part of a second chord.

So, If I play a simple C major, I play C, E & G, then might play E major, so I play E G# & B. E is in both chords, but I would release C, E & G, if only for a split second before pressing E, G# & B. What I am trying to say is there is never a requirement to play an individual note twice at once for one instrument, but there is a need to play more than one note at any time.

To complicate matters, I might have two instruments in my animation, so I might have a keyboard and a saxophone - now I do need to play the same note twice simultaneously, once on the piano and once on the sax. To accommodate this, I have one node for the piano and one for the sax, so the piano note might only last half a second and the sax note might last 2 seconds and start at the same time as the piano. This can be accommodated by two nodes playing the same note, say E5, at the same time, but with different filters applied so they sound differently.

In order to maximise performance of the system I am thinking that I need to work out how many notes are going to be played simultaneously at any time in the piece. The maximum might be only 8 notes (I have only got 10 fingers after all!), in which case I need only 8 of the new node I just made. I can then "read" all the inputs and put them in a list, then send the first note information to the first node, the next to the second node, etc. It would not be very difficult to know when a node is free to be used again, simply by reading the dictionary contained in it as this holds its "release" frame. Bear in mind the node I have just written takes only a note name, duration and volume, so it can play E4, stop for 1 frame, then play C7 with ease. Once I have added the filters, it can play two different instruments, one after the other.

One of my most played tunes is "The Entertainer" by Scott Joplin, as my memory serves me, there are 55 individual noted played, but never more than 7 at once. So to do this I would only need 7 of my nodes.

Sorry to ramble on, but I think my logic stacks up. I thought long and hard before making the node, to make sure it was as flexible as possible. I intend adding other inputs to take care of filters and echo for example, a long way to go still and if you see any faults in my logic, please let me know.

Cheers!

PS. I have just done a quick test and played a scale, each note separately, and it only needs one node as only one note is being played at any point in time. If I add an underlying 3 note chord, I still only need 4 nodes to play potentially any chord and any note anywhere on the piano keyboard.'

Not sure why, but it should be between @omars last two comments???

**Comment by Clockmender** [comment]
New Node & Functions now on my Branch under Master/nodes/daw

**_VERY_** Experimental just now, but you can have a look at what I have done so far - needs AUD of course.

**Comment by Clockmender** [comment]
@OmarSquircleArt Quick question:

I want to set two init values in the create function as in this code:

```python
    def execute(self,noteName,frequency,volume,duration,squaV,samples,revB,process):
        self.use_custom_color = True
        self.useNetworkColor = False
        self.color = (1,0.8,0.5)
        if self.soundFile is not '':
            noteName = ''
            frequency = 0
```

It has the desired effect but does not update the values in the node, is there a way to do this please?
Perhaps "node.refresh",or something similar?

**Comment by OmarSquircleArt** [comment]
@Clockmender Which file is that? Do you want to change the socket values? If you want the socket values to change, you have to use something like `self.inputs[index].value = 5` where `index` is the index of the input.

**Comment by Clockmender** [comment]
It's a node file:

```python
import bpy
import aud
import os
from bpy.props import *
from ... base_types import AnimationNode
from ... events import propertyChanged
from . daw_functions import getIndex, getFreq, getChord

class GenrerateSound(bpy.types.Node, AnimationNode):
    bl_idname = "an_GenrerateSound"
    bl_label = "SOUND Generate"
    bl_width_default = 150

    message = StringProperty()
    soundFile = StringProperty()
    soundName = StringProperty()

    def draw(self,layout):
        col = layout.column()
        col.scale_y = 1.2
        self.invokeSelector(col, "PATH", "loadFile",
            text = "Load Sound File", icon = "NEW")
        if self.message is not '':
            layout.label(self.message,icon="NONE")

    def create(self):
        self.newInput("an_TextSocket","Note","noteName")
        self.newInput("an_FloatSocket","Frequency","frequency",default=440,minValue=0)
        self.newInput("an_FloatSocket","Volume","volume",default=0.2,minValue=0.001,maxValue=1)
        self.newInput("an_FloatSocket","Duration (s)","duration",default=1,minValue=0)
        self.newInput("an_FloatSocket","Square Value","squaV",default=0,minValue=-0.99,maxValue=0.99)
        self.newInput("an_FloatSocket","Samples","samples",default=44100,minValue=5000)
        self.newInput("an_BooleanSocket","Reverse","revB",default = False)
        self.newInput("an_BooleanSocket","Process","process",default = True)
        self.newOutput("an_SoundSocket","Sound","sound")

    def loadFile(self,path):
        self.soundFile = str(path)
        self.soundName = str(os.path.basename(path))
        self.message = 'File Loaded: '+self.soundName

    def execute(self,noteName,frequency,volume,duration,squaV,samples,revB,process):
        self.use_custom_color = True
        self.useNetworkColor = False
        self.color = (1,0.8,0.5)
        if process:
            if noteName is not '':
                self.soundFile = ''
                self.message = ''
                indX = getIndex(noteName)
                if indX in range(0,107):
                    freq = getFreq(indX)
                else:
                    self.message = 'Note Invalid'
                    return snd
                snd = aud.Factory.sine(freq,samples)
            elif frequency > 16.35160:
                self.soundFile = ''
                self.message = ''
                snd = aud.Factory.sine(frequency,samples)
            elif self.soundFile is not '':
                snd = aud.Factory(self.soundFile)
                if revB:
                    snd = snd.reverse()
                squaV = 0
            else:
                return None
            if squaV != 0:
                snd = snd.square(squaV)
            snd = snd.limit(0,duration)
        else:
            snd = None
        return snd
```

In the `loadFile `function I want to set the `noteName` input to '" and set the frequency to 0. I'll try what you said and report back later, just playing with IIR/FIR Filters at the moment....

**Comment by Clockmender** [comment]
@OmarSquircleArt - Perfect! Thank you, that worked a treat. Code below for the function:

```python
    def loadFile(self,path):
        self.inputs[0].value = ''
        self.inputs[1].value = 0
        self.soundFile = str(path)
        self.soundName = str(os.path.basename(path))
        self.message = 'File Loaded: '+self.soundName
```

Here, my AUD Biquad Filter Node, with the Sound Generator & Volume node:

![Screen Shot 2019-03-28 at 18 27 14](https://user-images.githubusercontent.com/29657804/55183186-3699e180-5187-11e9-9c82-a08096bb76cb.png)

**Comment by Clockmender** [comment]
@OmarSquircleArt Another quick question if I may"

I have a button on a node like this:

`self.invokeFunction(col, "volUp", icon = "TRIA_UP")`

and a function call:

```python
    def volUp(self):
        self.vol1 = self.vol1+0.05
```

Thing is I have 10 Volume Up icons and 10 Volume Down icons, so is there a way to pass to the function which Volume Up icon has called it, or do I need a separate function for each icon?

**Comment by OmarSquircleArt** [comment]
I think you can do that by passing a `data` parameter to the `invokeFunction`, like `invokeFunction(..., data = "vol2")`. Then you can adjust the function to take this data as a parameter to be something like:

```python
def volUp(self, data):
    setattr(self, data, getattr(self, data) + 0.05)
```

Does this work?

**Comment by Clockmender** [comment]
I am out until this afternoon, I’ll report back later. Thanks for this!

**Comment by Clockmender** [comment]
Perfect again! thank you!

![Screen Shot 2019-03-29 at 14 31 44](https://user-images.githubusercontent.com/29657804/55239829-67cdec80-522f-11e9-9372-972e1d535d0d.png)

I'm building a Parametric Equaliser for the sound, using the High & LowPass filters....

**Comment by Clockmender** [comment]
My first Sequencer and Synth:

![Screen Shot 2019-03-31 at 09 14 04](https://user-images.githubusercontent.com/29657804/55286586-759d8200-5395-11e9-82b9-a2c02612c6c1.png)

Thanks for al the help!

**Comment by OmarSquircleArt** [comment]
@Clockmender Oh nice :smiley: . Make a video about it!

**Comment by Clockmender** [comment]
Just got some tidying to do on the code and I'm out the rest of the day, so I should be able to video it running tomorrow. I noticed that I have a slight issue using the `an_SoundSocket` socket, in that it does not return `None` if there is no input...

**Comment by OmarSquircleArt** [comment]
I think that if there is no input it would return an empty sound, that is `len(sound.soundSequences) == 0`.

**Comment by Clockmender** [comment]
Thanks, I solved it by using this code:` if 'aud.Sound' in str(snd):` but I will look at yours tomorrow.

**Comment by Clockmender** [comment]
I think I'll use my idea - if `'aud.Sound' in str(snd):` as this makes sure the incoming sound is only an AUD sound, not a sound sequence. Is that OK? I tried your code and plugged a sound bake into it (Blender 2.79 AN2.0) to see what happened and it did not like it!

**Comment by OmarSquircleArt** [comment]
@Clockmender Oh, I though you were talking about our sound object. In which case, you can use the `isinstance` function of python.

**Comment by Clockmender** [comment]
OK so this should work:

```python
if isinstance(snd,Sound):           # It's an AN Sound Sequence
    self.message = "Wrong Type Of Sound Connected"
    return None
else:
     # Do something with it.
```

That will make sure it's not an AN Sound?

**Comment by OmarSquircleArt** [comment]
@Clockmender Yes, I think so.

**Comment by Clockmender** [comment]
@neXyon has Kindly provided us with a `modulate()` function in AudaSpace, so now I can do this with it:

![Screen Shot 2019-04-06 at 21 03 35](https://user-images.githubusercontent.com/29657804/55674677-90995600-58af-11e9-9692-0706736df0d2.png)

I am very happy! This function multiplies one sound by another...

BTW, how do I get rid of these warnings:

```
Warning: 'an_viewport_input_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an.selection_pie' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_falloff_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_material_menu' doesn't contain '_MT_' with prefix & suffix
```

I am assuming I need to modify the AN Add menu a little?

**Comment by OmarSquircleArt** [comment]
@Clockmender I already fixed those warnings in the latest blender2.8 branch.

**Comment by Clockmender** [comment]
Thanks, but I have my own menu to fix also...

**Comment by Clockmender** [comment]
@OmarSquircleArt Quick question: This code does not set a default, can you give me a hint please?

`self.newInput("an_FloatSocket","Samples","samples",default=44100,minValue=5000)`

Thanks!

**Comment by OmarSquircleArt** [comment]
@Clockmender Commit fd4599e have the edits you should do to get rid of those warnings. Instead of `default = 44100` use `value = 44100`.

**Comment by Clockmender** [comment]
Thank you! I am out until later, so replying from my phone. I will sort out my menu when I get home and the “value” bit.

**Comment by Clockmender** [comment]
All works well, thank you!

I now have an AudaSpace driven FM Synthesiser, with optional Sound Filters ( can add as many as I want on each channel:

![Screen Shot 2019-04-07 at 18 40 38](https://user-images.githubusercontent.com/29657804/55687420-b6ccfd80-5964-11e9-9dac-a83130200483.png)

**Comment by Clockmender** [comment]
@OmarSquircleArt Just a quick note: You missed these two changes in node_panel.py:

```python
def drawSocketLists(layout, node):
    row = layout.row(align = True)

    size = max(len(node.inputs), len(node.outputs), 1)

    if len(node.inputs) > 0:
        col = row.column()
        subrow = col.row(align = True)
        subrow.label(text = "Inputs")
        subrow.operator("an.move_input", text = "", icon = "TRIA_UP").moveUp = True
        subrow.operator("an.move_input", text = "", icon = "TRIA_DOWN").moveUp = False
        col.template_list("AN_UL_SocketUiList_Normal", "", node, "inputs", node, "activeInputIndex", rows = size, maxrows = size)

    if len(node.outputs) > 0:
        col = row.column()
        subrow = col.row(align = True)
        subrow.label(text = "Outputs")
        subrow.operator("an.move_output", text = "", icon = "TRIA_UP").moveUp = True
        subrow.operator("an.move_output", text = "", icon = "TRIA_DOWN").moveUp = False
        col.template_list("AN_UL_SocketUiList_Normal", "", node, "outputs", node, "activeOutputIndex", rows = size, maxrows = size)
```

The two changes to "AN_UL_SocketUiList_Normal" in your commit [fd4599e](https://github.com/JacquesLucke/animation_nodes/commit/fd4599e3cea5146913185621302c274a6fd57b49)

Cheers, Alan

**Comment by Clockmender** [comment]
Just a quick note: You missed these two changes in node_panel.py:

```python
def drawSocketLists(layout, node):
    row = layout.row(align = True)

    size = max(len(node.inputs), len(node.outputs), 1)

    if len(node.inputs) > 0:
        col = row.column()
        subrow = col.row(align = True)
        subrow.label(text = "Inputs")
        subrow.operator("an.move_input", text = "", icon = "TRIA_UP").moveUp = True
        subrow.operator("an.move_input", text = "", icon = "TRIA_DOWN").moveUp = False
        col.template_list("AN_UL_SocketUiList_Normal", "", node, "inputs", node, "activeInputIndex", rows = size, maxrows = size)

    if len(node.outputs) > 0:
        col = row.column()
        subrow = col.row(align = True)
        subrow.label(text = "Outputs")
        subrow.operator("an.move_output", text = "", icon = "TRIA_UP").moveUp = True
        subrow.operator("an.move_output", text = "", icon = "TRIA_DOWN").moveUp = False
        col.template_list("AN_UL_SocketUiList_Normal", "", node, "outputs", node, "activeOutputIndex", rows = size, maxrows = size)
```

The two changes to "`AN_UL_SocketUiList_Normal`" in your commit fd4599e

Cheers, Alan

**Comment by OmarSquircleArt** [comment]
@Clockmender Yah, I already fixed it in a latter commit, namely b3900c5.

**Comment by Clockmender** [comment]
You're welcome!

**Comment by Clockmender** [comment]
@OmarSquircleArt A video for you, shows animations built directly from MIDI csv file, using my MIDI Bae node and sound generated by AudaSpace and my extension nodes to AN. I will try to get these on my GItHub soon, I am still testing...

https://vimeo.com/329301448

Cheers, Alan.

PS. Thanks for all your help with this.

**Comment by OmarSquircleArt** [comment]
@Clockmender Thanks for sharing. Very nice!
