### ISSUE TITLE
Animation Nodes Issue - Blender 2.8 - Windows

### ISSUE THREAD

**Issue by sam-jose333** [JacquesLucke/animation_nodes#1067]
![Screenshot (1)](https://user-images.githubusercontent.com/48976181/55050783-d42acf00-5028-11e9-908a-9dfc43a07d0c.png)

I don't know what to do.

**Comment by OmarSquircleArt** [comment]
You have to remove Animation Nodes entirely and then install it again.

**Comment by sam-jose333** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/48976181/55125148-2dedd080-50df-11e9-8bc6-a6d210663fc1.png)

Still didn't work.

**Comment by OmarSquircleArt** [comment]
@sam-jose333 I am pretty confident that an old version of Animation Nodes was still present when you installed the new version. Blender use multiple directories to store addons. What you should do is search those directories for a folder called `animation_nodes` and removed it. Make sure to check all possible directories. Then try installing again.

**Comment by OmarSquircleArt** [comment]
@sam-jose333 Have a look at this page:
https://docs.blender.org/manual/en/latest/getting_started/installing/configuration/directories.html#ms-windows

**Comment by OmarEmaraDev** [comment]
@sam-jose333 Can you report back on this?

**Comment by Sturmlicht** [comment]
Hey there. I tried to install the 2.8 version. I have Blender on D drive and added a custom path for installing the add on in the folder under scripts. So far it created the animation_nodes-blender2.8 folder.

However if this folder is there, the Add-on will not show up under Blender Preferences.
If I push the folder "animation_nodes" up, the Add on will show up in the preferences, however enabeling it will give me the following message 
![image](https://user-images.githubusercontent.com/39851803/68371629-63f83600-013f-11ea-9ff7-c073a22e4e56.png)

I see it is saying that there is more than one folder with animation nodes, the only one left is then the empty animation_nodes-blender2.8 folder, which does not want to get deleted xD

I am new to blender and installing add ons. So I am clearly falling into any pit there is to find. :(

**Comment by Sturmlicht** [comment]
Is this .py related to animation node add on? 
![image](https://user-images.githubusercontent.com/39851803/68372038-60b17a00-0140-11ea-8bf9-4d4038a3797f.png)

**Comment by OmarEmaraDev** [comment]
@Sturmlicht  Did you download Animation Nodes from https://animation-nodes.com/?
Run the file explorer as administrator and delete the file, with blender closed.

**Comment by Sturmlicht** [comment]
I downloaded from github 
![image](https://user-images.githubusercontent.com/39851803/68470821-1eaa3600-021d-11ea-8fd7-0e64d8e47a87.png)
I could remove the empty folder after restarting the PC xD

I will try with the version from your link!

**Comment by Sturmlicht** [comment]
So I downloaded from the above link the 2.8 windows version - I got animation_nodes_v2_1_windows_py37.zip

I installed the zip over the preferences in my custom path. I appeared in the Add-on list but when trying to enable, I get the following:

![image](https://user-images.githubusercontent.com/39851803/68471054-adb74e00-021d-11ea-9090-6c4dcb2ceb28.png)

**Comment by OmarEmaraDev** [comment]
Install `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).

**Comment by Sturmlicht** [comment]
Thanks OmarEmaraDev, this helped! Thanks a lot!

**Comment by Sturmlicht** [comment]
Ok, so I have it finally enabled.
![image](https://user-images.githubusercontent.com/39851803/68485851-419a1180-0240-11ea-8edd-98379717e469.png)

I wanted to follow some of the videos of this tool, but the node editor stays empty

![image](https://user-images.githubusercontent.com/39851803/68485802-2e874180-0240-11ea-93d5-2188cf008b73.png)

**Comment by Sturmlicht** [comment]
Solved, I needed to restart Blender after enabeling the add-on!

**Comment by Sturmlicht** [comment]
I encountered another issue. If I open up a previously created file, that I wanted to use to test this add-on. the add-ons search bar stays blank as noted above. So it actually wasn't the restart but with a new scene the search bar will appear. 
So there might be problems with using the add-on with already created files in Blender 2.8?

**Comment by Sturmlicht** [comment]
Not sure if it is still ok to continue this bug entry, However it is still windows and blender 2.8 issues xD 

So I am trying to follow the Dynamic Vertex Weight and Color Nodes for Animation Nodes.. Video on youtube and the nodes do look different which kinda means I cannot follow. When serching I could find the two red nodes with vertex but not that blue node, which means I cannot set the setting. Not sure how to work around this. And the Video is still 2019 so I assumed it is not too old xD

![image](https://user-images.githubusercontent.com/39851803/68580460-b6ef2780-0476-11ea-8b06-2a92b52e8a6d.png)

**Comment by Sturmlicht** [comment]
I am also not able to link bright blue with black and Vertex Location with the Location point of the evaluate Falloff node.

again blue/left from the video and red/right from the current Add-on 
![image](https://user-images.githubusercontent.com/39851803/68582457-0b94a180-047b-11ea-8736-857fcdc5e3e0.png)
I marked where should links be able to put according to the video with the annotation feature

**Comment by OmarEmaraDev** [comment]
@Sturmlicht The video you are watching uses a custom Animation Nodes build. So you probably need to install this custom build.

**Comment by Sturmlicht** [comment]
that's what I did in the first place, as you can see above in my pictures.  But you said I should get the one from that official page xD 

I will try to download the extranodes branch and install it from github, right? 

any ideas why it does not work with already created scenes?

**Comment by OmarEmaraDev** [comment]
No, but I suggest you wait a day or two, the node you are looking for is going to be merged to master soon, see #1226.

**Comment by Sturmlicht** [comment]
Oh nice, yes, I will wait than. I am back at the old issue where the add on with the extension does not show up in the preferences. Anyways, thank you for your support :)
