### ISSUE TITLE
FastNoise compilation error: LNK1112

### ISSUE THREAD

**Issue by dragere** [JacquesLucke/animation_nodes#1071]
This is the same issue as #1005, but i dont know how it was fixed.

When i run "setup.py build" in the "x64 Native Tools Command Prompt for VS 2017" console, i encounter this error:

<details> 
  <summary>FastNoiseSIMD_windows.lib(FastNoiseSIMD.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'</summary>
<code>...
54/105:
running build_ext
building 'animation_nodes.libs.FastNoiseSIMD.wrapper' extension
creating build\temp.win32-3.7\Release\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs
creating build\temp.win32-3.7\Release\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs\FastNoiseSIMD
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs\FastNoiseSIMD\source "-IC:\Program Files (x86)\Python37-32\include" "-IC:\Program Files (x86)\Python37-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /TpC:\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cpp /Fobuild\temp.win32-3.7\Release\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.obj
wrapper.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs\FastNoiseSIMD\source "/LIBPATH:C:\Program Files (x86)\Python37-32\libs" "/LIBPATH:C:\Program Files (x86)\Python37-32\PCbuild\win32" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17134.0\um\x64" FastNoiseSIMD_windows.lib /EXPORT:PyInit_wrapper build\temp.win32-3.7\Release\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.obj /OUT:C:\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cp37-win32.pyd /IMPLIB:build\temp.win32-3.7\Release\Users\H\source\other\animation_nodes\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cp37-win32.lib /NODEFAULTLIB:LIBCMT
FastNoiseSIMD_windows.lib(FastNoiseSIMD.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'.
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x86\\link.exe' failed with exit status 1112</code>
</details>

specs:
- clean clone of the blender2.8 branch
- Windows 10 64-bit
- 64-bit AMD processor

[fullCompilerLog.txt](https://github.com/JacquesLucke/animation_nodes/files/3026511/fullCompilerLog.txt)

**Comment by OmarSquircleArt** [comment]
I can see some 32-bit applications being used. Like python. Could this be the problem?

**Comment by dragere** [comment]
You were right, i reinstalled Python and Cython and now it works.

Thank You
