### ISSUE TITLE
lag zooming and panning in the node editor

### ISSUE THREAD

**Issue by Lynchon83** [JacquesLucke/animation_nodes#1072]
May be has something to do with blender, but navigating around the editor (no matter how many nodes I have or if the graph is being executed or not) is very laggy. This is something very annoying when you are working with big graphs. This won't happen in the shader editor and is something that occurs in 2.79 and 2.8.

Anyone experiencing the same thing?

**Comment by OmarSquircleArt** [comment]
Do you have automatic execution enabled?

**Comment by Lynchon83** [comment]
All executions are switched off. I've noticed it happens when subprograms are placed.

**Comment by Lynchon83** [comment]
I can't reproduce it again, so probably is better to close the issue.
