### ISSUE TITLE
Strange crash with AN turned on

### ISSUE THREAD

**Issue by brothermechanic** [JacquesLucke/animation_nodes#1073]
@JacquesLucke , can you check my 2.79.7 blender file?
https://drive.google.com/open?id=1JZiPyi38sAX5l_85EIxgoHmkvmhXsfKu
strange crashes when i switch to compositor

**Comment by brothermechanic** [comment]
I found bug!
This happends if I build blender with DWITH_LLVM=ON
With DWITH_LLVM=ON my scene works with AO addon fine

**Comment by OmarEmaraDev** [comment]
@brothermechanic Are you still experiencing those crashes?

**Comment by brothermechanic** [comment]
Hello)
This was so long ago)))
An today we have 2.81)
But we have to test, but i can't test it now

**Comment by OmarEmaraDev** [comment]
If the problem is gone in the current builds then you don't need to test. I will close this issue, but feel free to reopen if you get trouble again. :)
