### ISSUE TITLE
Convert to Text Node

### ISSUE THREAD

**Issue by dragere** [JacquesLucke/animation_nodes#1076]
Is the 'Convert to text' node necessary?
In my tests it always returns the same as the generic 'Convert' node.

![image](https://user-images.githubusercontent.com/26360562/55561505-90079080-56f2-11e9-8fd5-a65596649580.png)

**Comment by OmarSquircleArt** [comment]
It is more explicit and cleaner. The convert node is also a *Passive* node, so I think we should just keep it.

**Comment by dragere** [comment]
Alright
