### ISSUE TITLE
can't install AN on 2.8

### ISSUE THREAD

**Issue by trburns2007** [JacquesLucke/animation_nodes#1079]
![Screenshot (112)](https://user-images.githubusercontent.com/49292592/55591403-13c57b00-56fb-11e9-9cd1-c1283f7130b4.png)

**Comment by TWINGSISTER** [comment]
That happened to me, too this very morning. Think that   .pyd  are version specific and need to be recompiled. Don't know if I am able to do this and bang out a new version. Hold on.... 
Actually the idea of having my Python addons going 400x faster is enough to take a look at it.

**Comment by OmarSquircleArt** [comment]
Where did you download this build? This is the one you should be installing:
https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1.4

**Comment by TWINGSISTER** [comment]
OK, thank. the Readme points to https://github.com/JacquesLucke/animation_nodes/releases/latest

**Comment by TWINGSISTER** [comment]
Well 2.1.4 crashes at line 18 in _init_.py i.e. raises exception
try: from . import test_compile
except: traceback.print_exc()

if "test_compile" not in globals():

**Comment by TWINGSISTER** [comment]
No way out, also  2.1 crashes at activation!

**Comment by atselman** [comment]
![can't install addon](https://user-images.githubusercontent.com/49819004/57182819-49ae7880-6ece-11e9-8d64-0a58e3d73b60.PNG)

**Comment by cannibalox** [comment]
> 
> 
> ![can't install addon](https://user-images.githubusercontent.com/49819004/57182819-49ae7880-6ece-11e9-8d64-0a58e3d73b60.PNG)
. remove addon
. make sure 'auto run python scripts' is enabled in the prefs, save prefs
. reinstall addon

**Comment by so-lost** [comment]
I also cannot install it on the latest blender 2.8 build, any fix to this? I tried the above suggestion by cannibalox

**Comment by OmarEmaraDev** [comment]
The crash should be fixed now. Feel free to reopen if you are still experiencing it with the latest build.
