### ISSUE TITLE
Animation Nodes (v2.1) crashes while rendering when the "3D Viewer Node" is connected (blender 2.79)

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1082]
Hi Omar,

Animation nodes (v2.1) crashes while rendering when "3D Viewer" Node is enabled or disabled in blender 2.79. When I disconnected the "3D Viewer" node then blender does not crash. Blender does not show any error message on terminal but the crashed file has this:
 # backtrace
./blender(BLI_system_backtrace+0x1d) [0x1bc30dd]
./blender() [0x119a369]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f55f13a14b0]
/usr/lib/nvidia-384/libGL.so.1(+0xcb109) [0x7f55f2768109]

and here is the screenshot of my node-tree:
![Screenshot from 2019-04-06 19-34-13](https://user-images.githubusercontent.com/30294746/55670567-bde00700-58a3-11e9-884b-338a2b15da7e.png)

**Comment by OmarSquircleArt** [comment]
Is this the full backtrace? This seems like a bug in Nvidea's OpenGL implementation, but I am not sure.

**Comment by 3DSinghVFX** [comment]
Yes, this is the full backtrace. However, in blender 2.8, 3D Viewer Node is working without any problem.

**Comment by OmarSquircleArt** [comment]
The 2.8 implementation of the node uses modern OpenGL. The 2.7x version uses legacy OpenGL. So they are quite different.

**Comment by 3DSinghVFX** [comment]
OK. But blender 2.79 still crashes even if I disable the GPU in blender settings.

**Comment by OmarSquircleArt** [comment]
Disable the GPU? You mean render from the CLI?

**Comment by 3DSinghVFX** [comment]
Disabled in preferences as well as in render settings.
![Screenshot from 2019-04-07 16-19-53](https://user-images.githubusercontent.com/30294746/55682461-51234600-5951-11e9-9fde-c3c4bf0eb309.png)

**Comment by OmarSquircleArt** [comment]
Those are the compute devices for Cycles, they have nothing to do with out point of discussion. You can't really disable OpenGL, it is the thing that draws everything in Blender.

**Comment by 3DSinghVFX** [comment]
The OpenCL and OpenGL are the newest version on my OS but still the same problem.

**Comment by 3DSinghVFX** [comment]
I think blender should not crash at least when I disable the 3D Viewer Node.

**Comment by OmarEmaraDev** [comment]
@3DSinghVFX Do you still experience the crash? Maybe after updating the nvidia driver?

**Comment by 3DSinghVFX** [comment]
@OmarEmaraDev The crash is still happening in Blender 2.79c (Latest build). At the end of this month, I'll install a fresh Ubuntu 16.04/18.04 LTS on my laptop, then I'll test it again and let you know. For the time being, I think we close this issue.
