### ISSUE TITLE
[Feature Request] Adding Collection Operations as replacement for Object Group Operations

### ISSUE THREAD

**Issue by radifar** [JacquesLucke/animation_nodes#1086]
When I'm trying the Spawn Rigid Body with AN tutorial from Youtube (https://www.youtube.com/watch?v=G1ysjPeLKSQ) I realize that there is no Object Group Operations in AN 2.1 for Blender 2.8. I suspect that this is caused by the change in Blender from Group to Collection. Therefore the Objects can not be moved to RigidBodyWorld Collection. I hope that Object Collection Operations node or something similar is added to fix this (collection) issue.

Best regards,
Radif

**Comment by OmarSquircleArt** [comment]
Thanks for bringing this to our attention! We will look into it.

**Comment by dragere** [comment]
I simply copied the [Group Operations Node](https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/nodes/object/object_group_operations.py) to 2.8 and came across these issues: 
- removing a object from it's sole collection will remove it from the view layer and view port:
 ![inCollection](https://user-images.githubusercontent.com/26360562/56518172-0b64a100-653f-11e9-8b03-264eacf43e39.gif)
 - adding an object to a collection causes it to appear twice:
![toCollection](https://user-images.githubusercontent.com/26360562/56518204-29320600-653f-11e9-8113-f629e67fe33a.gif)

It'll just be a design decision on how to deal with it.

**Comment by OmarSquircleArt** [comment]
@dragere I think this is the user's responsibility. Not sure if Jacques would agree.

**Comment by dragere** [comment]
I think so, too. Should I then create a pull request?

**Comment by OmarSquircleArt** [comment]
@dragere Sure, but better wait for the pull request you have already to be merged.

**Comment by OmarSquircleArt** [comment]
Added in #1088.
