### ISSUE TITLE
Suggestion: allow users to nest the object instance node

### ISSUE THREAD

**Issue by ogierm** [JacquesLucke/animation_nodes#1089]

**Comment by juangea** [comment]
A better explanation will help devs to understand what you mean, I personally don't have a clue :)

**Comment by dragere** [comment]
You cannot use the Object Instancer in any subprogram: 
![image](https://user-images.githubusercontent.com/26360562/58386913-d1d3f980-8006-11e9-8e7e-389156174b5a.png)
I don't know why, but I suppose there's a good reason.
