### ISSUE TITLE
request : elastic and bounce options for interpolation

### ISSUE THREAD

**Issue by 3delic** [JacquesLucke/animation_nodes#109]
these two dynamic interpolation types are very useful for motion graphics and are available in blender with the "back" one.

**Comment by JacquesLucke** [comment]
totally true. I just didn't found a good implementation for these interpolation types. 
Maybe you can try to get the same effect with the interpolation node using a custom interpolation

**Comment by 3delic** [comment]
Gutes Geburtstag !

I tried with custom interpolation, it's possible but hard to do and not accurate.

**Comment by JacquesLucke** [comment]
Danke :D

Do you think it would be good to be able to convert a fcurve into an interpolation type? (in addition to the custom interpolation in the node)

**Comment by 3delic** [comment]
I dont see how I would use it for now, maybe to add modifiers, noise or stepped for ex, to an interpolation, not sure.
Maybe to edit an interpolation more accurately, and "bake it" to a new interpolation type, it seems complicated to me, but I cant really figure out how.

**Comment by JacquesLucke** [comment]
Okay. I will come back to this issue in a few days :)

**Comment by 3delic** [comment]
Thx, I'll try to understand better how it could interact, still learning AN.
