### ISSUE TITLE
No Length definition for Mesh [default: len(mesh.vertices)]?

### ISSUE THREAD

**Issue by tfwio** [JacquesLucke/animation_nodes#1090]
Hi!

[Using windows and the 2.8 branch]

There's a particular new tut on youtube featuring AN: https://www.youtube.com/watch?v=C95mi7lKt8o  
It seems to work in the vid but I couldn't get it to.

First thing I did was check the generated **Debug -> Execution Code** which gave me the inkling to check the following in `nodes/list/get_list_length.py`.

```python
# Node: 'AN Tree' - 'Get List Length'
try: _length_tx21 = len(_mesh_gk25)
except Exception as e:
    print(e)
    _length_tx21 = 0
```
It complained that `object of type 'animation_nodes.data_structures.meshes.mesh_data.Mesh' has no len()`.

The following fixed it for me :)

```diff
diff --git a/animation_nodes/data_structures/meshes/mesh_data.pyx b/animation_nodes/data_structures/meshes/mesh_data.pyx
index e12fcff4..15e9babb 100644
--- a/animation_nodes/data_structures/meshes/mesh_data.pyx
+++ b/animation_nodes/data_structures/meshes/mesh_data.pyx
@@ -50,6 +50,9 @@ cdef class Mesh:
 
         self.derivedMeshDataCache = {}
         self.uvMaps = OrderedDict()
+    def __len__(self):
+        return len(self.vertices)
+        pass
 
     def verticesTransformed(self):
         self.derivedMeshDataCache.pop("Vertex Normals", None)
```

![image](https://user-images.githubusercontent.com/1386695/57052978-9127d100-6c50-11e9-9c91-89f6d3bf37dc.png)

**Comment by OmarSquircleArt** [comment]
Thanks for the suggestion. But it doesn't really make sense to define the length of the mesh as the length of its vertices. Just use the *Vertex Locations* output to get the length.

**Comment by tfwio** [comment]
Thanks, that makes sense.  Apparently I miss-steeped in the tut there.
;)
