### ISSUE TITLE
"Subprograms, Remove" options do not display properly in the Node-Editor bar in Blender 2.80

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1091]
Hi...
Some times "Subprograms, Remove" options get behind the node-tree option, then it becomes difficult to use them, here is screenshot: 
![Screenshot from 2019-05-04 14-54-20](https://user-images.githubusercontent.com/30294746/57177077-e4329b80-6e7d-11e9-9153-bff7b0ab0205.png)
Thanks :)

**Comment by OmarEmaraDev** [comment]
Fixed in 74e2097.
