### ISSUE TITLE
Render stuck "Cancelling..."

### ISSUE THREAD

**Issue by zachThePerson** [JacquesLucke/animation_nodes#1093]
The attached file is made with the latest 2.1.4 2.8 release, however I originally discovered this issue in the 2.79 release.

It seems to be that when I enable the compositor, and then add some kind of Animation Nodes output like a Viewer or Material Output, it causes the compositor to get stuck in an infinite "Cancelling..." loop.

I can reliably reproduce this on my end, however I'm not sure if it occurs on other machines as I don't have any other machines to test it on atm.

[breakTest.zip](https://github.com/JacquesLucke/animation_nodes/files/3153086/breakTest.zip)

The 2.8 example file is attached. The bug _should_ happen immediately when the file is opened, with the "Cancelling..." bar going crazy.

**Comment by OmarSquircleArt** [comment]
I can replicate this with the viewer node. Does this happen with 2.7x as well?

**Comment by zachThePerson** [comment]
Yes, originally it was discovered in a 2.79 project file.
