### ISSUE TITLE
Problem with loop node and Matrix nodes

### ISSUE THREAD

**Issue by arniswillow** [JacquesLucke/animation_nodes#1094]
Hello,

I was building myself a tool and ran into an issue with the loop node.

It's returning accumulative values instead of regular values in the viewport. A 3D viewer node kind of fixes it. You can see the bug when you cut the noodles of the viewer.

I'm using AN 2.1.4 with Blender 2.8.
Example blend: [`DB download`](https://www.dropbox.com/s/nlvbcp2jd5odl2w/loopNodeProb.blend?dl=0)

I presume this is worth looking into.

**Comment by OmarSquircleArt** [comment]
Please provide more information as I can't download the file, a screenshot should also help.

**Comment by 3DSinghVFX** [comment]
@OmarSquircleArt I have downloaded his file, It looks like 3D Viewer node is blocking some data.
I have attached two screenshots, one with 3D Viewer Node is connected and another when 3D Viewer Node is disconnected,

**3D Viewer Node is connected:**
![loopNodeProb](https://user-images.githubusercontent.com/30294746/57399379-b6878280-71ee-11e9-9911-821d0faf0104.png)

**3D Viewer Node is disconnected:**
![loopNodeProb1](https://user-images.githubusercontent.com/30294746/57399435-d5861480-71ee-11e9-9cf3-5792d43d817c.png)

**Comment by OmarSquircleArt** [comment]
Thanks @3DSinghVFX ! It is probably related to data copying. Can you activate the Copy option for the Y+ list (In the advanced node setting) and see if it works as expected?

**Comment by OmarSquircleArt** [comment]
Can somebody upload the file here on github so that I can investigate it?

**Comment by 3DSinghVFX** [comment]
I have attached the blend file. If I disconnect the 3D Viewer Node but enable the Copy option then shows the same problem.

[loopNodeProb.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/3159070/loopNodeProb.blend.zip)

**Comment by arniswillow** [comment]
@3DSinghVFX Thanks for the support :)
I activated the copy option and it did work, thank you!

**Comment by OmarSquircleArt** [comment]
You relied on the offset node to edit the data and get a different offset at each iteration, you should never do that. What happens is that we you connect the viewer node (Or any other node), AN decides to copy the data instead of modifying it, and you get a constant offset instead. To have a similar effect, you can use a reassign parameter node.

Moreover, you may want to use the *Replicate Spline* node with a *Linear Distribute Matrix* node instead  to do the replication.
