### ISSUE TITLE
Rendering Crash, Any ways to render?

### ISSUE THREAD

**Issue by conquerorcode** [JacquesLucke/animation_nodes#1095]
I know that the rendering crash is a known issue and I just wanted to know if there is a way to render that doesn't crash

**Comment by OmarSquircleArt** [comment]
You can try this [script](https://github.com/JacquesLucke/animation_nodes/issues/1009#issuecomment-464411399) in this thread.

**Comment by conquerorcode** [comment]
I tried this script but it only results in image outputs is there a way for a video output?

**Comment by conquerorcode** [comment]
NVM IGNORE
