### ISSUE TITLE
Apply modifier in Mesh Object Input Node does not work in blender 2.8

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1099]
Hi Omar,
Apply modifier on mesh object input node does not work because in recent API changes they have removed the apply modifier option. I have found the solution to get the applied modifier mesh but I'm not sure it is the correct way or not (Mesh Object Input Node):  

        yield "if useModifiers:" 
        yield "    sourceMesh = object.evaluated_get(AN.utils.depsgraph.getActiveDepsgraph()).to_mesh() if object else None"
        yield "else:"
        yield "    sourceMesh = object.an.getMesh(AN.utils.depsgraph.getActiveDepsgraph()) if object else None"

**Comment by OmarSquircleArt** [comment]
Thanks! But this should probably be fixed somewhere else.
Fixed in 33a6b95.
