### ISSUE TITLE
Installing AN failed latest versions

### ISSUE THREAD

**Issue by jumpyjumpo** [JacquesLucke/animation_nodes#1101]
Hello,

I installed the latest version of Blender 2.8 and AN today, with last modifications on AN code and I can't install it, saying version 2.8x of Blender is required.

![Capture2](https://user-images.githubusercontent.com/50735405/57970926-beca8500-7987-11e9-898e-6407cdbd08fa.PNG)

**Comment by OmarSquircleArt** [comment]
I can't replicate this with the very latest of both. Did you build An yourself?

**Comment by jumpyjumpo** [comment]
I installed the 2.1.4 from here, I manage to install it on Blender, but it don't works. So I downloaded the latest version of the code frome here also, then replace all the files in the animation node script folder.

Then I can't activate AN in blender.

**Comment by OmarSquircleArt** [comment]
Well you can't download the code from here directly, AN have to be compiled using the blender2.8 branch. Recent API changes meant that all available builds will no longer works. So you will have to wait until new builds come out.
