### ISSUE TITLE
No keyframe animation

### ISSUE THREAD

**Issue by dimitripaiva** [JacquesLucke/animation_nodes#1104]
While we can set keyframes on node parameters, whose color changes indicating keyframes existence, they don't have any effect on the viewport and the objects itself.

**Comment by OmarSquircleArt** [comment]
As far as I know, key-framing properties of custom nodes is not supported in Blender, so this will not work in Animation Nodes.

I think that key-framing defies the point of AN anyway, use Animate nodes instead. Alternatively, Jacques mentioned before the idea of having a controller object, where you set the key-frames to an object and sample its values in AN.

**Comment by Clockmender** [comment]
> As far as I know, key-framing properties of custom nodes is not supported in Blender, so this will not work in Animation Nodes.

I agree, whilst you can RMB-Click an entry box in AN and add a keyframe, it has no effect whatsoever. There are many instances where I have used a keyframed object and then used the "Object Transforms Input" node to get values of Location, Rotation and Scale to pass to a node tree.

**Comment by Clockmender** [comment]
@OmarSquircleArt as @dimitripaiva has not had the simple, common courtesy to at least acknowledge the response to his question, shouldn't you close it?

**Comment by OmarSquircleArt** [comment]
Lets poke @dimitripaiva first. Is this the answer you were looking for?

Also, please see #820.

**Comment by dimitripaiva** [comment]
> @OmarSquircleArt as @dimitripaiva has not had the simple, common courtesy to at least acknowledge the responses to his question, shouldn't you close it?

I'm sorry. I was not trying to dismiss all your effors. I think it's a little rude to say I don't have enough courtesy to acknowledge something, as you don't know me neither my time. I just saw an email regarding this thread for pure coincidence and I thank @OmarSquircleArt  for the kindness to give me a chance to answer first and for his time to answer my questions.

**Comment by OmarSquircleArt** [comment]
@dimitripaiva I am sure ClockMender didn't mean that in a bad way.
Anyway, we will make sure to implement a fix if Blender allowed key-framing it in a future release. Let me know if you need anything else.
