### ISSUE TITLE
no Get Spline Samples node in Blender 2.8?

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#1108]
I can't find the "get spline samples" node in Blender 2.8, where is it?

**Comment by felipetorrents** [comment]
Try with Evaluate splines node instead

**Comment by juangea** [comment]
Mmmmh... I don't think this should be closed, Get Spline Samples and Evaluate Spline are two different things, Get Spline Samples gives you an array of points, while with Evaluate Spline you have to arrange that array, Get Spline Samples simplifies the node graph a lot.

Is there a reason why this is not present in 2.8 build?

**Comment by OmarSquircleArt** [comment]
@juangea Not sure what you mean. Enabling *Evaluate Range* option makes the node acts exactly like Get Spline Samples and even provides more information. Can you elaborate?

![Node Tree](https://user-images.githubusercontent.com/25300994/58380609-5bf27280-7fb3-11e9-9abb-d8278f734ccd.png)

**Comment by juangea** [comment]
AAAAAh!

Ok, so enabling the Range option gives the same output!

Thanks, I missed the range part :)

All it's ok with this now :)
