### ISSUE TITLE
AN not working at all, not even connecting nodes

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#1109]
Hi.

I'm connecting nodes but as you can see in the picture, nothing is working, nothing is moving and no teven the nodes are changing when I connect them.

Build from today.

![image](https://user-images.githubusercontent.com/20524718/58380680-42055f80-7fb4-11e9-8e7c-ad2ecee6653e.png)

**Comment by OmarSquircleArt** [comment]
Is this an Animation Nodes built today?

**Comment by juangea** [comment]
Nope, I have not built it my self, is the one from the releases link, has that been updated recently? because the version number is the same

**Comment by OmarSquircleArt** [comment]
I see. Those builds no longer works due to a recent API change. We already fixed that but haven't updated the builds. What OS are you on?

**Comment by juangea** [comment]
Linux and Windows :)

**Comment by OmarSquircleArt** [comment]
If you can, try building AN from the blender2.8 branch and it should work. If you can't, you can download a non-official windows build from https://prenninger.com/3d/. Let me know if you want help building it on Linux.

**Comment by juangea** [comment]
Yes please, I don't have experience building AN, I build Blender, but not AN, I would prefer to build both versions instead of testing a different build, so since my main rig is linux and it's where I need to work right now, how can I do that? :)

Thanks!

**Comment by OmarSquircleArt** [comment]
Which distribution are you using?

**Comment by juangea** [comment]
Mint, Ubuntu base

**Comment by OmarSquircleArt** [comment]
First, make sure you have the `python`, `cython`, and `python-numpy` packages installed. Those are all the dependencies you need.
Then clone the AN repository and checkout to the `blender2.8` branch.
Then execute `python setup.py build --export`, this will generate the zip folder which you can then install.

**Comment by juangea** [comment]
ok, going to do it rigth away, thanks!

**Comment by juangea** [comment]
Will the same work in windows?

**Comment by OmarSquircleArt** [comment]
No, for windows, check the [build guide](https://animation-nodes-manual.readthedocs.io/en/latest/dev_guide/setup/windows.html). You can also directly copy the compiled files into the addons directory as follows. Create a `conf.json` that include the path to your addons folder by executing:

```
echo '{"Copy Target" : "/some/thing/some/thing/2.80/scripts/addons"}' > conf.json
```
Then build AN using `python setup.py build --copy`.

**Comment by juangea** [comment]
I get this error on linux:

test_compile.c:16:10: fatal error: Python.h: No existe el archivo o el directorio

**Comment by OmarSquircleArt** [comment]
You are missing the python header files, install the `python-dev` package.

**Comment by juangea** [comment]
It seems I already have it:

![image](https://user-images.githubusercontent.com/20524718/58381215-acb99980-7fba-11e9-9756-701819d919fd.png)

**Comment by OmarSquircleArt** [comment]
Can you execute `ls -l /usr/include | grep python`? Do you see `python3.7m` printed or something?

**Comment by juangea** [comment]
I used python3.7 command

![image](https://user-images.githubusercontent.com/20524718/58381256-50a34500-7fbb-11e9-9d59-da357f773363.png)

**Comment by OmarSquircleArt** [comment]
Ok, what about `ls -l /usr/include/python2.7m | grep Python.h`? Are you sure you are compilling with python 3.7?

**Comment by juangea** [comment]
![image](https://user-images.githubusercontent.com/20524718/58381312-079fc080-7fbc-11e9-8925-17dcf9509c51.png)

**Comment by juangea** [comment]
Yes I am, I use the python3.7 command and if I run python3.7 -V it tells me it's 3.7

**Comment by OmarSquircleArt** [comment]
Everything seems to be in order, not sure why this is happening.

**Comment by juangea** [comment]
I find a possible problem, if I run python3.7 -V I get 3.7.2

But If I try to install Python3.7 with apt install it tells me that Python is already installed in the version 3.7.1.1

**Comment by OmarSquircleArt** [comment]
This seems like something to report the mint maintainers. Not sure, but can you try installing `libpython3-dev`?

**Comment by juangea** [comment]
I'm trying forcing the uninstall and install of python 3.7.1 and trying to ignore 3.7.2

**Comment by juangea** [comment]
Ok, I solved some problems, now I'm using Python 3.7.1
the one from APT.
Installed also Cython, Cython3, Python3-apt, Python-apt Python3.7-dev but I'm still getting errors:

```
Run PyPreprocessor
--------------------------------------------------

1/7: data_structures/virtual_list/virtual_clists.pyx
2/7: data_structures/virtual_list/virtual_clists.pxd
3/7: data_structures/action/action_types.pyx
4/7: data_structures/action/action_types.pxd
5/7: data_structures/lists/base_lists.pyx
6/7: data_structures/lists/base_lists.pxd
7/7: data_structures/lists/convert.pyx


Run Cythonize
--------------------------------------------------

1/106:
Traceback (most recent call last):
  File "setup.py", line 232, in <module>
    main()
  File "setup.py", line 68, in main
    main_Build(args[1:], configs)
  File "setup.py", line 151, in main_Build
    changedFileStates = build(skipCompilation = "--nocompile" in options)
  File "/home/jgea/animation_nodes/animation_nodes/_setuputils/generic.py", line 241, in wrapper
    function(*args, **kwargs)
  File "setup.py", line 188, in build
    execute_Cythonize(setupInfoList, addonDirectory)
  File "/home/jgea/animation_nodes/animation_nodes/_setuputils/cythonize.py", line 8, in execute_Cythonize
    task.execute()
  File "/home/jgea/animation_nodes/animation_nodes/_setuputils/cythonize.py", line 25, in execute
    cythonize(self.path, compiler_directives = {"language_level" : "3"})
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 899, in cythonize
    ctx = c_options.create_context()
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 590, in create_context
    self.cplus, self.language_level, options=self)
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Main.py", line 75, in __init__
    from . import Builtin, CythonScope
  File "/usr/lib/python3/dist-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/usr/lib/python3/dist-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/usr/lib/python3/dist-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "/usr/lib/python3/dist-packages/Cython/Compiler/Visitor.py", line 15, in <module>
    from . import ExprNodes
  File "/usr/lib/python3/dist-packages/Cython/Compiler/ExprNodes.py", line 2844
    await = None
          ^
SyntaxError: invalid syntax
```

**Comment by OmarSquircleArt** [comment]
It seems your Cython package is not up to date, it has something to do with a reserved keyword in the new python version. Maybe you should remove the cython package and install it through python pip (I would consider this a bad practice).

Thank god I don't use mint. :smile:

**Comment by juangea** [comment]
Ok, finally I fixed everything with my weird python install and build it without trouble, but it still don't work

![image](https://user-images.githubusercontent.com/20524718/58386651-165d9600-8003-11e9-9972-91f599c61a7f.png)

In the terminal I get this error:

![image](https://user-images.githubusercontent.com/20524718/58386658-2a08fc80-8003-11e9-9068-5b68ab16e011.png)

**Comment by juangea** [comment]
Ok, forget it... this was getting me crazy!!!

I enabled the addon without closing blender, it's perfectly working!!!

Thanks!!!!

**Comment by OmarSquircleArt** [comment]
That's good to hear. Have fun!
