### ISSUE TITLE
animation nodes not running

### ISSUE THREAD

**Issue by olivierpiraux** [JacquesLucke/animation_nodes#1112]
Hello,
i have the last version of Blender 2.80.72 installed and the version 2.1.4 of Animation Nodes.
The script seems not starting even if i start the code with the button "execute node tree" i get the following error: "the animation Nodes addon is not able to setup the execution units for the node tree."
The simple tree that i am trying to run in attachment. Thanks in advance for your feedback.
<img width="2628" alt="Screenshot 2019-05-31 at 09 00 05" src="https://user-images.githubusercontent.com/42712435/58687720-ba886980-8382-11e9-8c8c-3e2e0254f268.png">

**Comment by dragere** [comment]
Please take a look at #1109 or #1107.

**Comment by olivierpiraux** [comment]
is it possible to get a link to a fresh build for MAC OS ?
regards

**Comment by OmarSquircleArt** [comment]
There will be new official builds next week.

**Comment by olivierpiraux** [comment]
ok thanks a lot.

**Comment by olivierpiraux** [comment]
any news about the update ?
thanks in advance

**Comment by OmarSquircleArt** [comment]
@olivierpiraux Sorry for the delay, there have been some issues with the builds. I will get back to you as soon as the new builds come out.

**Comment by olivierpiraux** [comment]
thanks  !
