### ISSUE TITLE
AN Auto-Setting Float Input Precision

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1113]
Hi,

I enter a value for a frequency in my node:

![Screen Shot 2019-06-03 at 17 28 09](https://user-images.githubusercontent.com/29657804/58818141-47eae880-8625-11e9-8c15-b7b1b0cc87ed.png)

This represents a known note frequency (GS7) and it gets changed to this:

![Screen Shot 2019-06-03 at 17 28 17](https://user-images.githubusercontent.com/29657804/58818218-7799f080-8625-11e9-9918-58c9761dcef8.png)

Which is **NOT** a recognised note frequency - how do I stop AN doing this?

I need this to be able to resolve frequencies into note names.

**Comment by OmarSquircleArt** [comment]
The value didn't actually change, AN just draws a low precision version of the actual value for compactness. If you click on it again, you will get the same value you entered before.

If you prefer more precision, you can pass a high precision value (up to 6) to the float property definition in the `sockets/float.py` file like this:

```
value: FloatProperty(default = 0.0, precision = 6,
        set = setValue, get = getValue,
        update = propertyChanged)
```

**Comment by Clockmender** [comment]
Hmm, I just clicked it...

![Screen Shot 2019-06-03 at 20 51 26](https://user-images.githubusercontent.com/29657804/58830097-6d85eb00-8641-11e9-990d-057ef712ba12.png)

I also trapped it with a message and it came back as 3322.44 - The output says "Not A Note" because the node cannot find 3322.44 in my list, the nearest entry is 3322.438. So sorry that didn't do it....

**Comment by OmarSquircleArt** [comment]
I see, sorry, my bad. It seems related to significant figures.
Did you try the `precision = 6` parameter I mentioned?

**Comment by Clockmender** [comment]
Sorry I just updated my last post, I will try tomorrow...

**Comment by OmarSquircleArt** [comment]
I would highly recommend that you represent the values in integer millihertz instead. Generally it is bad idea to compare floats.

**Comment by Clockmender** [comment]
Yes I understand that, particularly in Blender where, for example, if you look at the coordinates of an object at 21.0 you might get something like 21.00000005 returned. But if I use a Float Number node for a frequency of 92.49861 (FS2) I get 92.5 returned, this makes the note out of tune.

In reality I understand I need 6, or 7 significant figures and I need to work in significant figures, rather than precision, to get a note in tune. This makes it difficult to use any Float sockets for frequencies.

Setting the precision to 6 for a frequency of 92.49861 returns:

![Screen Shot 2019-06-04 at 07 51 56](https://user-images.githubusercontent.com/29657804/58857714-cc794d80-869d-11e9-9ae7-623c8f141b76.png)

So this won't work either as the precision changes from C0 to B10. If I enter 15804.27 (B9) I get 15804.269531 displayed in the Float Number node with precision set to 6! I guess I have to find a way to get the nearest number from my frequency list, or a number within a tight margin, to whatever AN/Blender wants to change the Float Value to. I will investigate further.

I could do that with code like this:

```python
# inpF = Input Frequency
# outF = Output Frequency
# freqList = Frequency Master List

outF = 0
for v in freqList:
    if v > inpF * 0.95 and v < inpF * 1.04:
        outF = v
```

I am not sure if this is as efficient as:

```python
def findNote(freqI):
    idx = next((i for i, x in enumerate(noteFreq) if x == freqI), -1)
    noteName = noteList[idx] if idx > -1 else "Not a Note"
    return noteName
```

One option is to only allow users to input note names, rather than frequencies, but this might cause problems when trying to get notes in tune from a morphing object, I don't know that yet. I might want a tune played from an object changing shape, if I calculate the frequency from a changing shapekey, or vertex location, it is going to be out of tune. I will think some more, as slight changes in frequency sound awful, just try rotating a machine head on a guitar 5 degrees and listen to the result, eeeeek!

Thanks for the input!

**Comment by OmarSquircleArt** [comment]
Won't representing the frequency using integers solve the problem? Perhaps using millihertz?

**Comment by Clockmender** [comment]
The thing there is that the lower frequencies have a need for far more precise decimals than the higher ones. The problem with harmonic frequencies is that they are a logarithmic scale, so C0 to C1 doubles the frequency, C1 to C2 again doubles the frequency. Semitone rises multiply the first frequency by a multiple of the twelfth root of 0.5 - a 1 semitone rise might be from one note to another like E to F, or might be from one note to a sharp, like A to AS. I could multiply everything by 100000 - that would give integers to work with, or I could do this:

```python
def findNote(freqI):
    # get index of closest frequency to input
    idx = min(range(len(noteFreq)), key=lambda i: abs(noteFreq[i]-freqI))
    noteName = noteList[idx] if idx > -1 else "Not a Note"
    return noteName
```

This returns the index of the nearest frequency to the input frequency in my master frequency list, then finds this index in the master note list. This solves the problem for **all** other scenarios where I have to convert a frequency to a note. I can optionally compare the input and output frequencies to see if they are within a tolerance of say 2%, or return "Not a Note". So something like:

```python
def findNote(freqI):
    # get index of closest frequency to input
    idx,freqO = min(enumerate(freqList), key=lambda x: abs(x[1]-freqI))
    if freqO in range(freqI * 0.98, freqI * 1.02):
        # Process note else return "Not a Note"
       noteName = noteList[idx]
    else:
        noteName = "Not a Note:
```

Thanks again for your valuable input.
