### ISSUE TITLE
Crashing upon execution and Auto Execution fails

### ISSUE THREAD

**Issue by CPeek23** [JacquesLucke/animation_nodes#1114]
Auto execution didn't change anything whenever I moved my objects despite being set to always
Crashed when I tried to execute by pressing the "Execute Node Tree" button.
v2.1.4, Blender 2.8
Node Setup: 
![Capture4](https://user-images.githubusercontent.com/51345363/58840765-9059d480-862c-11e9-8c1e-900b51450fe2.PNG)

Console:
![Capture23](https://user-images.githubusercontent.com/51345363/58840773-9a7bd300-862c-11e9-9665-1d72fb82621a.PNG)

**Comment by OmarSquircleArt** [comment]
Thanks for the report! This has already been fixed, new builds with the fix should be released this week.
