### ISSUE TITLE
Lsystem node doesnt work

### ISSUE THREAD

**Issue by jverkhovykh** [JacquesLucke/animation_nodes#1115]
Hello people!
Lsystem node connected to mesh object output doesn't provide any response. Any ideas how to solve it?
![image](https://user-images.githubusercontent.com/48492997/58974164-39463200-87db-11e9-8d1f-81838b6df3b2.png)

**Comment by OmarSquircleArt** [comment]
The *Mesh Object Output* node is trying to tell you something. You have to enable Mesh output by pressing the little dot.

**Comment by jverkhovykh** [comment]
> The Mesh Object Output node is trying to tell you something. You have to enable Mesh output by pressing the little dot.

> 
I was thinking the same and pressed at it but nothing happens
![image](https://user-images.githubusercontent.com/48492997/58975169-c5595900-87dd-11e9-8bc7-d82b9f6a260b.png)

**Comment by jverkhovykh** [comment]
> 
> 
> The _Mesh Object Output_ node is trying to tell you something. You have to enable Mesh output by pressing the little dot.
I thought the same but still doesn't work.
![image](https://user-images.githubusercontent.com/48492997/58975249-f46fca80-87dd-11e9-81fa-623687263ddf.png)
or I'm stupid af

**Comment by OmarSquircleArt** [comment]
Blender will not show the object because it is composed of only edges. Try selecting the object and entering edit mode to see the actual mesh.

**Comment by jverkhovykh** [comment]
> 
> 
> Blender will not show the object because it is composed of only edges. Try selecting the object and entering edit mode to see the actual mesh.

Still doesn't work 😒
And I've tried to look at edge and vertex selecting modes - nothing

**Comment by dragere** [comment]
You can try this setup:
![image](https://user-images.githubusercontent.com/26360562/58978966-478d5180-87cd-11e9-90f6-9d75d1dbdba4.png)

**Comment by jverkhovykh** [comment]
> 
> 
> You can try this setup:
> ![image](https://user-images.githubusercontent.com/26360562/58978966-478d5180-87cd-11e9-90f6-9d75d1dbdba4.png)

Doesn't work, mate.
Anyone has similar problem? Or is it just me who can't figure it out?

**Comment by OmarSquircleArt** [comment]
Are you sure you have a working AN version? Does anything work at all? Try to experiment more with the node tree, debug the output of each step, see where this leads you.

**Comment by jverkhovykh** [comment]
I have the latest version, I believe, that is downloadable. 
Alright I will try to mess more with AN

**Comment by OmarSquircleArt** [comment]
The latest one that is downloadable doesn't work. Can you please tell me if any thing other than this works in AN?

**Comment by jverkhovykh** [comment]
> 
> 
> The latest one that is downloadable doesn't work. Can you please tell me if any thing other than this works in AN?

No it's not. I've tried some things, like creating ropes etc, but nothing is working, so I've downloaded the 2.1 release but it's not working neither.

**Comment by OmarSquircleArt** [comment]
Yah that is expected. This is not really related to the L-system node. The current builds no longer work due to an API change. New builds with a fix will be release soon and you will be able to test this.
