### ISSUE TITLE
Cyrillic text causes crash

### ISSUE THREAD

**Issue by Almaz** [JacquesLucke/animation_nodes#1116]
When you insert in Text Input node a text consisting of Cyrillic characters, the application crashes.

**Comment by OmarSquircleArt** [comment]
Are you sure that this is the cause of the crash? Is there anything printed in the terminal?

**Comment by Almaz** [comment]
I tried many different types of text, but only Cyrillic caused the crash. But now I don't sure.
I use Ubuntu and didn't see the terminal.
Sample Cyrillic text: Кириллица

**Comment by OmarSquircleArt** [comment]
You can open Blender from a terminal manually in order to get a terminal.

Is this on 2.8? I will try to replicate that.

**Comment by 3DSinghVFX** [comment]
I have checked and it is working,

![Screenshot from 2019-06-07 02-17-03](https://user-images.githubusercontent.com/30294746/59065490-72a99b00-88ca-11e9-87e4-576b98c7cfc8.png)

@Almaz Can you please share the blend file?

**Comment by OmarEmaraDev** [comment]
@Almaz Can you report back on this?
