### ISSUE TITLE
Spline shape key are not taken into effect

### ISSUE THREAD

**Issue by benny7770** [JacquesLucke/animation_nodes#1118]
Hi ya! I really need some help. If you have time please have a read. 

I have a small blend that has 3 curves that have a series of shape keys and that are animated over 150 frames. I wanted to have a mesh spanning all three shape keys and use the curves to deform the mesh over time. I decided that the Animation Nodes addon would help using the loft system, so I learnt alittle about AN and away I went building a node system to "Loft" a mesh over the span of the curves. I got alittle way in and was able to create a loft mesh but I have no idea how to actually keep it connected to the curve vertices while they animate so the mesh deforms.

 Here is my blend file. ( Blender 2.8, AN 1.2) https://blenderartists.org/uploads/short-url/lOFEPogNV1WXDA5J88BumCVXfqQ.blend

Any!! help woud be much appreciated.

**Comment by OmarSquircleArt** [comment]
This seems like a limitation of the system. The objects needs to be evaluated at the depsgraph in order for shape keys to take effect. We have been especially having trouble with the depsgraph in 2.8.

We will look into it.

**Comment by benny7770** [comment]
Hi Omar! Thankyou so much for looking into my problem. Your title renaming is very accurate! Thankyou for helping me.

**Comment by benny7770** [comment]
Hi Omar! I hope you are well! This thread is going to go stale soon. Just wondering if you have time to inform me of any progress concerning the issue with the limitations of the depth graph with spline shape keys. Peace!

**Comment by OmarEmaraDev** [comment]
Hi Benny, thanks for getting back to us!

Unfortunately, Blender currently does not provide access to evaluated splines from python. I will take a look at the Blender code to see if this is something we can patch ourselves, but other than that, there is nothing we can do here, sorry.
