### ISSUE TITLE
Animation Nodes is not working in Blender 2.8 on Linux

### ISSUE THREAD

**Issue by amsaid1989** [JacquesLucke/animation_nodes#1119]
I have installed the latest build of Animation Nodes in Blender 2.8 for Linux.

It seemed to install properly without any warnings.

However, when I switch to the Animation Nodes view, and try to do anything, nothings actually happens. For instance, if I try instancing an object, the instances are not created. The same with all other nodes.

When I check the terminal, I find these warnings that appear after launching Blender:

> register_class(...):
Warning: 'an_mesh_finalizing_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_spline_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_animation_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_interpolation_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_material_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_particle_system_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_fcurve_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_id_keys_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an_sound_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_rotation_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_sequence_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_kdtree_bvhtree_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_boolean_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_viewer_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_color_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_subprograms_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_problems_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an_tree_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an_list_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_layout_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_create_list_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_SocketUiList_Normal' doesn't contain '_UL_' with prefix & suffix
register_class(...):
Warning: 'an_vector_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_overview_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an_viewport_input_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an.context_pie' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_developer_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an_templates_menu_in_header' doesn't contain '_HT_' with prefix & suffix
register_class(...):
Warning: 'an_node_settings_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an_create_list_menu_extended' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_combine_list_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_matrix_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an.selection_pie' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_combine_list_menu_extended' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_number_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_object_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_geometry_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_object_utils_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_auto_execution_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'an_mesh_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_falloff_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_mesh_generators_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_text_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'an_mesh_operators_menu' doesn't contain '_MT_' with prefix & suffix
Registered Animation Nodes

**Comment by OmarSquircleArt** [comment]
It seems you are using an old build of AN. The builds in the release page are old and will not work. New AN builds will be released soon.

**Comment by amsaid1989** [comment]
I see. I was, indeed, using the build on the release page. I will try building it myself then and see what happens. Thank you @OmarSquircleArt
