### ISSUE TITLE
Explore order of operation and deps graph (inside and outside addon)

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#112]
The order of execution it's not obvious and definitely not obvious to the user. 

We commented on the forum, but this is a global and somewhat exhaustive issue. Still, considering that nodes are essentially a visual ordering of operations, not having the grasp of operations and depsgraph is quite error prone (or at least a turn off). 
There is an issue of users not knowing the logic or deps graph operations logic, but after all, this addon invites the not so scripting kind to "script" visually.

I would separate this in two:
1.order inside anim nodes 
2.relation to outside blending (deps graph)

So far I am able to tell these:
2. outside 
-object nodes are executed first, before constraints,
(generally after parenting, but do consider respective matrices)
-object data (mesh,text..) is executed first, before bones, shape keys and modifiers
(exception to the apply modifiers check...)
 *This is rather correct and natural considering the blender way 
[order: object>mesh // parenting>constraints >>  bones> shape keys> modifiers]

-addon seam to beat key frames (fcurves), but is beaten by drivers
still to explore this..

I'll continue to tackle this especially in combinations ...

1. inside
[maybe more related to the design of the addon /ui]
  To keep it general, I consider 
a.The usage/usecases should decide the correct way, in time..
b.Some more consistency with B nodes (cyc, compositor ..) should be there

  Specifically
There is an issue (user pov, visual) with node trees not always having a clear input - output. 
It is logical in many cases, as I dive into them, but is somewhat confusing visually, at least as beginner. I would not immediately change this but take small steps in organizing or documenting. 

For example the separation of loops in loop and loop call, this breaks the noodle chain, (while also being a not very visual concept also). Groups, the same ... 
Or, in consistency, maybe wherever there is a list output, there should be a length output too

but this is a very long discussion... Let's take it step by step ..
Or take it as a reminder to explore this :)

**Comment by kopias** [comment]
As a fresh user of animation nodes (but blender fan for a long time) :

1. some simple doc with order of execution would be nice especially as a part for custom nodes guide. There is also order of execution of node trees or maybe they are combined somehow? (btw. why I cant remove node tree?)

2. about loops ui: never have problems with this concept (im using frame nodes to visualize connection). Better solution would be to use group node but thats not supported by pynodes currently. I would leve the current design and return to it when we will have groups.
