### ISSUE TITLE
Offsetted letters are shifted

### ISSUE THREAD

**Issue by Almaz** [JacquesLucke/animation_nodes#1120]
When you rotate a separated text 90 degrees on the X-axis, some letters shift on the Y-axis.
Nodes chain: [Separate Text Object]-[Object ID Key]-[Offset Matrix]-[Offset Matrix Output]

**Comment by OmarSquircleArt** [comment]
Please provide a screenshot of the issue you are facing.

**Comment by Almaz** [comment]
Blend-file: http://bit.ly/2WBJi08
Screenshot: https://nimb.ws/gXbWzZ

**Comment by OmarSquircleArt** [comment]
It seems like the characters are in their right position. Why do you think there is a shift?

**Comment by Almaz** [comment]
https://nimb.ws/BhH3gx

**Comment by OmarSquircleArt** [comment]
This is not a bug, the origin of the characters are just not in the right place, so after rotation, you perceive the characters as shifted.

**Comment by Almaz** [comment]
So how to align all characters in such cases?

**Comment by OmarSquircleArt** [comment]
@Almaz Just make sure the origin of the characters lie on the axis of rotation.

**Comment by Almaz** [comment]
Is it possible to automate this using some node?

**Comment by OmarSquircleArt** [comment]
Changing the origin position? I don't think there is an easy way to do this.
