### ISSUE TITLE
Time code does not work

### ISSUE THREAD

**Issue by somasimple** [JacquesLucke/animation_nodes#1121]
Hi Jacques,
It seems ther is some problem wwith AN
Best regards

![animation_nodes](https://user-images.githubusercontent.com/51692275/59246426-a400ce80-8c1c-11e9-984e-366adf8e5d12.PNG)

**Comment by OmarSquircleArt** [comment]
Which AN build are you using? Can you share a screenshot of the node tree? Is there anything printed in the terminal?

**Comment by somasimple** [comment]
I'm using the version 2.1.4.
Here is the blend file
[nernst_experiment280_03.zip](https://github.com/JacquesLucke/animation_nodes/files/3275442/nernst_experiment280_03.zip)

**Comment by OmarSquircleArt** [comment]
Did you download this build from the release page?

**Comment by somasimple** [comment]
No,
I did from there
https://prenninger.com/3d/

**Comment by OmarSquircleArt** [comment]
Thanks for the report! Will solve this as soon as possible.

**Comment by OmarSquircleArt** [comment]
Fixed in 9185fc8.
