### ISSUE TITLE
AN Crashes when frame is changed

### ISSUE THREAD

**Issue by markersniffen** [JacquesLucke/animation_nodes#1124]
Blender 2.80 (x64 - daily build from 6/14/19)
Animation Nodes v2.1.4 - py37 (downloaded 6/14/19)
Blender file: https://drive.google.com/file/d/1tvyr5NgdmvtOH32g3bP6J6HNc6OHd5UO/view?usp=sharing

When I try to move to a new frame (arrow keys, drag the timebar, etc) Blender immediately crashes. This doesn't happen if I disable the AN addon. If I remove "E1" from the object node on the left side of the "Center Path" node tree, things seem to start working, however if I scrub quickly, and perhaps past the in and out points, it will crash again. If I try to bake the particles (with E1 still set as the object in the node), it also crashes.

Hopefully this is helpful, I know there's a lot of variables and I tried to spend some time narrowing down when the crash happens.

![AN debug](https://user-images.githubusercontent.com/44777080/59511764-1f64b900-8e85-11e9-863c-fee87ffc5cb7.png)

**Comment by OmarSquircleArt** [comment]
Thanks for the report! We are aware about the source of the crash and will solve it as soon as possible. Avoid using the particle system nodes and the *Apply Modifiers* option for now, as they will all cause Blender to crash.

**Comment by 3DSinghVFX** [comment]
@OmarSquircleArt I'm using the latest blender build (21 June 2019), Mesh Input Node and Particle Systems from Object Node are working,
![Screenshot from 2019-06-23 10-03-54](https://user-images.githubusercontent.com/30294746/59971677-541bf300-959e-11e9-9fc5-82aa84326d7c.png)

**Comment by OmarSquircleArt** [comment]
@3DSinghVFX huh, it seems to be working here as well. Another API change, except it is in our favor.

Lets leave this open for sometime until we make sure it is fully working.
