### ISSUE TITLE
Blender crashes when trying to access vertices locations for an animated alembic mesh

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#1125]
I import an alembic cache, there are just vertices, no faces or edges (because in reality they are particles).

Then I put this setup:

![image](https://user-images.githubusercontent.com/20524718/59570405-fe27e680-9097-11e9-9fc2-1fda3ce2701b.png)

As soon as I press "Use Modifiers" Blender crash.

**Comment by OmarSquircleArt** [comment]
We are aware about this issue. And we are working on it. Two things will crash Blender currently, the *Use Modifier* option and *Particle System* nodes. So avoid them for now.

**Comment by juangea** [comment]
Ouch, in fact I was going to use this with the particles node... what a pity! 

Any idea with what bug is related? (to track it down)

As a workaround for the time being, in Blender 2.79 works at least :)

**Comment by OmarSquircleArt** [comment]
@juangea The bug is caused by a violated context access inside a timer. In order to apply modifiers or access particles, we have to evaluate the depsgraph. The evaluated depsgraph is only accessibly through the context, which doesn't exist, hence the crash.

In order to solve this, we have to get the evaluated depsgraph from data, which Blender currently doesn't allow. The only solution I see is to patch Blender in order to allow the viewlayer to provide the evaluated depsgraph. I plan to try this once I have the time.

**Comment by juangea** [comment]
oh, great, I think this would be pretty important, not just for this but for many things, this should open other possibilities with Python, and this was possible in 2.79, so it should be possible before 2.80 release

Have you communicated this to core devs? maybe they see this as an actual bug and they can fix it.

**Comment by OmarSquircleArt** [comment]
@juangea I talked to Jacques about it, but nothing was decided or anything. I am pretty busy right now with GSoC, so I will look into this more thoroughly as soon as I have the time.

**Comment by OmarSquircleArt** [comment]
@juangea It appears the API changed again, but this time to our advantage. Can you test this again and see if it is working?

**Comment by juangea** [comment]
Yes, I saw a commit that undo some particle related things, I'll try it later today :)

Thanks for the heads up!

**Comment by juangea** [comment]
@OmarSquircleArt now it works without problem, but when trying to assign the new particles output value, it seems to assign it perfectly during the frame, but just after ending the frame calculation Blender overwrites the particles position and they got back to their original position.

I think it's the same problem found by @scorpion81 in the Molecular addon

**Comment by juangea** [comment]
He told me the problem and the solution he applied:

basically I oriented myself here:

https://docs.blender.org/api/blender2.8/bpy.types.Depsgraph.html

the particles are only in the evaluated version
but if you wanna make changes, you do them on the original object afaik, this is being automatically propagated to the evaluated version
