### ISSUE TITLE
Nodes connection

### ISSUE THREAD

**Issue by jvansynghel** [JacquesLucke/animation_nodes#1126]
I work with an Win10 laptop, a Mac i7 and a MacBook Pro.
On all the computers do I have the same problem:
If I want to connect one node to another (with the connection-line), the second node don't takes the value of the first (connected) node.
The line is drawn, but their is no value taken over.

I work with Blender 2.8
AN version: 2.1.4

**Comment by OmarSquircleArt** [comment]
You are probably using an old build. What build are you using, where did you download it from?

**Comment by jvansynghel** [comment]
I dit the download from: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1.4 <https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1.4>

I dit it for Windows and for Mac. Both have the same result. 
No connection between the nodes.

The Blender version is 2.8



Regards,





Johan Van Synghel







Johan Van Synghel
ICT-consultant

Minister Tacklaan 83 - 8500 Kortrijk
Groene Biezenlaan 61 - 8660 De Panne

Tel.: 0497 533 448
Tel.: 056 25 59 25

BTW/ON: 0524 302 232
IBAN: BE20 4632 1375 7156
BIC van KBC: KREDBEBB











Web:
www.macinfo.be <http://www.macinfo.be/>
www.de-computerdokter.be <http://www.de-computerdokter.be/>
Email:
johan@macinfo.be <mailto:johan@macinfo.be>
info@de-computerdokter.be <mailto:info@de-computerdokter.be>

"Not the technology itself is important...but the application of technology!"

**Comment by OmarSquircleArt** [comment]
Thanks for the report! The build you are using is not up to date and thus doesn't work. We already fixed that, please wait until new build are released.

**Comment by jvansynghel** [comment]
Thanks for your answer.


Johan Van Synghel
ICT-consultant

Minister Tacklaan 83 - 8500 Kortrijk
Groene Biezenlaan 61 - 8660 De Panne

Tel.: 0497 533 448
Tel.: 056 25 59 25

BTW/ON: 0524 302 232
IBAN: BE20 4632 1375 7156
BIC van KBC: KREDBEBB











Web:
www.macinfo.be <http://www.macinfo.be/>
www.de-computerdokter.be <http://www.de-computerdokter.be/>
Email:
johan@macinfo.be <mailto:johan@macinfo.be>
info@de-computerdokter.be <mailto:info@de-computerdokter.be>

"Not the technology itself is important...but the application of technology!"
