### ISSUE TITLE
Build for py 3.7

### ISSUE THREAD

**Issue by Jytesh** [JacquesLucke/animation_nodes#1127]
Can someone build it for Py 3.7 which is used by blender 2.8's latest release.

**Comment by OmarSquircleArt** [comment]
The release page already have builds for python 3.7, however, they are outdated.
New builds will be released soon, keep an eye out.

**Comment by Jytesh** [comment]
> The release page already have builds for python 3.7, however, they are outdated.
> New builds will be released soon, keep an eye out.

Where are they can you link it?

**Comment by OmarSquircleArt** [comment]
@Jytesh https://animation-nodes.com/#download
