### ISSUE TITLE
Switching between Object and Edit Mode 2.8

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1128]
Hi,

This code works in blender 2.79 in a script node:

```python
import bpy
import bmesh
import numpy as np
from math import acos, pi, sqrt
mesh = obj.data
verts = mesh.vertices
bpy.ops.object.mode_set(mode='OBJECT')
edges = [e for e in obj.data.edges if e.select]
bpy.ops.object.mode_set(mode='EDIT')
```

But doesn't in 2.8, how do I do this now, I can find no documentation anywhere. I doesn't like the switch to Object Mode.

Cheers, Clock.

**Comment by OmarSquircleArt** [comment]
You shouldn't use `bpy.ops` in Animation Nodes. Those operators need context, which is something we don't have in Animation Nodes. There may be hacks to overcome this, like context overwrite, not sure if this will work in 2.8 though.

What are you trying to do?

**Comment by Clockmender** [comment]
Yep, I know I shouldn't do that, but this was an old script, from when I didn't know better....

The problem is getting up to date bmesh from an object in Edit mode, so I need to work on the selected vertices/edges, but these change of course. So now I am using:

```python
bm = bmesh.from_edit_mesh(obj.data)
edges = [e for e in bm.edges if e.select]
# Process edges.
.
.
.
.
bmesh.update_edit_mesh(obj.data)
```

Which. appears to work well, I was only flipping to Object mode to update the selection, poor practice in 2.8, so now I am doing it properly (I hope). The node will take two selected edges and merge them at their intersection point, like this:

Before:

![Screen Shot 2019-06-23 at 17 11 41](https://user-images.githubusercontent.com/29657804/59979006-12a93900-95da-11e9-934e-fde8da17e56b.png)

After:

![Screen Shot 2019-06-23 at 17 11 49](https://user-images.githubusercontent.com/29657804/59979010-18068380-95da-11e9-8d02-f6534cde5d01.png)

It works for any possible combination of converging edges, and warns if they are parallel. I am using `numpy vstack, hstack and cross` to find the intersection point.

**Comment by OmarSquircleArt** [comment]
@Clockmender Not sure exactly why you want to toggle modes. Is the selection status only updated upon toggling?

**Comment by Clockmender** [comment]
Normally yes, but I think I can sort this another way, can I not switch modes in animation nodes?

**Comment by OmarSquircleArt** [comment]
I don't think so, we probably can't.

**Comment by Clockmender** [comment]
I can't find any way to do this other than with a `bpy.ops` call, so I will work with a bmesh instead and check the object is in Edit mode; `if obj.mode != 'EDIT':` etc.

Thanks!
