### ISSUE TITLE
AN 2.1.4  doesn't seem to work in the latest blender 2.8

### ISSUE THREAD

**Issue by SpiralInfinity** [JacquesLucke/animation_nodes#1129]
The latest build of  animation nodes seems that doesn't work with 23.06 Blender 2.8 build on Linux Mint.
I am simply trying to use mesh nodes to for some simple vertex displace but everything turns red. 
I tried everything including  cleaning the old installation and do it from scratch but it seems that nothing helps. Is there any fix for these issues ?

I guess we have to wait for new version of animation nodes when 2.8 is released or what  would be amazing is if "everything  nodes" replace it soon .This is the main reason I started looking towards Blender. :)

**Comment by OmarSquircleArt** [comment]
Did you compile Animation Nodes yourself? Where did you get the build?

**Comment by SpiralInfinity** [comment]
I downloaded them from [here](https://github.com/JacquesLucke/animation_nodes/releases), but I just found out that this is old. So I compiled this one [here](https://github.com/JacquesLucke/animation_nodes/commit/08726850fa41b7d5246183d2f229781ea0540163) and now it seems to work.
Sorry for the noise! 
Thanks!

P.S. I really hope everything nodes comes out soon :)

**Comment by OmarSquircleArt** [comment]
No problem. :)
