### ISSUE TITLE
Новичок

### ISSUE THREAD

**Issue by changhai69** [JacquesLucke/animation_nodes#1130]
![Снимок](https://user-images.githubusercontent.com/52234877/60161077-f9de9480-9820-11e9-8700-845f2cd2b40f.PNG)

**Comment by OmarSquircleArt** [comment]
What Animation Nodes build are you using? Where did you download it from?

**Comment by changhai69** [comment]
https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1.4

**Comment by OmarSquircleArt** [comment]
@changhai69 Unfortunately, this build no longer works with latest 2.8. Please wait until new builds are released or try to find a more recent non official build.

**Comment by changhai69** [comment]
Благодарю!
