### ISSUE TITLE
Can't compile latest AN on windows

### ISSUE THREAD

**Issue by SpiralInfinity** [JacquesLucke/animation_nodes#1131]
Can't  compile the latest build on windows. This is the eroror I am getting:

LINK : fatal error LNK1181: cannot open input file 'FastNoiseSIMD_windows.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
I think I installed all of the build tools on windows but is windows and everything has to be complicated......
On linux everething works fine.
Can you let me know if I am missing something and how I can compile it on windows?

**Comment by bestdani** [comment]
Maybe I can help, this is my personal "it magically works" when compiling AN (for blender 2.8) on my Windows 10 system following this text file that I have created from scattered information I found online, hopefully the same procedure works for you.

> Start Menu->Visual Studio 2015->VS2015 x64 Native Tools Command Prompt
> 
> %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 8.1
> 
> (compile on c:\animation nodes\ (see shortcut) since compiling here gives errors for unkown reasons)
> cd c:\animation nodes\
> 
> py -3.7 setup.py build --export --noversioncheck

**Comment by JacquesLucke** [comment]
I had the same issue lately (I think). LazyDodo was able to help me. I had to run the following commands before compiling: `set DISTUTILS_USE_SDK=1`, `set PY_VCRUNTIME_REDIST=No thanks`.
I'm not sure why this is necessary now, but was not earlier.

**Comment by RPeter-335** [comment]
> I had the same issue lately (I think). LazyDodo was able to help me. I had to run the following commands before compiling: `set DISTUTILS_USE_SDK=1`, `set PY_VCRUNTIME_REDIST=No thanks`.
> I'm not sure why this is necessary now, but was not earlier.



> I had the same issue lately (I think). LazyDodo was able to help me. I had to run the following commands before compiling: `set DISTUTILS_USE_SDK=1`, `set PY_VCRUNTIME_REDIST=No thanks`.
> I'm not sure why this is necessary now, but was not earlier.

did the same..then a new error popped up error: command 'cl.exe' failed: No such file or directory

**Comment by OmarEmaraDev** [comment]
@RP335 Looks like you need to call `vcvarsall.bat` first.
