### ISSUE TITLE
Random number and random text produce no result

### ISSUE THREAD

**Issue by Horse44** [JacquesLucke/animation_nodes#1132]
In the latest version of Blender 2.8, Random number reads 'none' with a viewer node, 'print code' reads key error ('node tree', 'random number'), random text is the same except nothing comes up for print or write code.
(MacOS High Sierra, 10.13.4, Intel Iris Pro Graphics 6200 1536 MB)

**Comment by OmarSquircleArt** [comment]
You are probably using an old version of Animation Nodes that no longer words with latest 2.8 builds. You can wait until new AN builds are released or you can try to build it yourself.

**Comment by Horse44** [comment]
This is with 2.1.4 that is installed already in Blender - would this then be the case? And do you have a link for something about constructing AN builds? thanks.

**Comment by OmarSquircleArt** [comment]
Yes, no official builds works at this moment. There is a build guide for Windows:
https://animation-nodes-manual.readthedocs.io/en/latest/dev_guide/setup/windows.html

**Comment by Horse44** [comment]
thanks again.
