### ISSUE TITLE
Some suggestions for workflow improvement

### ISSUE THREAD

**Issue by grinvaldsjanis** [JacquesLucke/animation_nodes#1133]
Making some project with decent(biting off more than can chew) numbers of groups, loops, networks, and realised that some improvements could help to manage and navigate better.

**Node Migration**
1. Ability to migrate (unique) nodes/node-networks between trees without making copies.
1.1 I think that cut/paste of nodes/networks should migrate them without making new copies.
1.2 right/click and Node menu could provide delivery of subprograms, networks or disconnected nodes to another node tree.

**Quick travel between related nodes**
2. Quick view to subprogram/group network from invoke or grouped node. Useful in big networks or between node trees.
2.1 Could be possible also to find/show/highlight/select all the invoke/grouped nodes. Could be an issue if those are propagated in different node trees. Maybe it is possible to show them in a list with characteristics like "in node tree 'Nodetree_1' in group 'MyGroup1'". If the project is well sorted, one should be having an idea of which each node of them could be.

**Comment by OmarEmaraDev** [comment]
I will close this for now. Feel free to reopen if you have further feedback.
