### ISSUE TITLE
ANIMATION NODES ''GET SPLINE SAMPLES'' PROBLEM 

### ISSUE THREAD

**Issue by caslumar1990** [JacquesLucke/animation_nodes#1134]
hello , i wanna to instance some objects in a spline

i saw some tutorials and i cannot find this node GET SPLINE SAMPLES in my node tree search

someone help me plz!!!!!!!

**Comment by caslumar1990** [comment]
im using         

animation_nodes_v2_1_windows_py37

**Comment by OmarSquircleArt** [comment]
See:
https://blender.stackexchange.com/questions/143567/animation-nodes-curve-and-objects
