### ISSUE TITLE
AN | Error: auto execution and node status updating 

### ISSUE THREAD

**Issue by Rafael1793** [JacquesLucke/animation_nodes#1135]
When you create a node, doesn't Auto Execute.
And the nodes doesn't update or refresh, for example, if you use a object instacer and conect the obejcts output to an object matrices you will notice that the object input doesn't change, and nothing happens. This happen with all the nodes that I try.

The bug is very easy to see because this make the AN addon unusable.

Sorry for my English

**Comment by OmarSquircleArt** [comment]
This issue has already been fixed. Please wait until new official builds of Animation Nodes come out.
