### ISSUE TITLE
No output on Mac

### ISSUE THREAD

**Issue by fvlasie** [JacquesLucke/animation_nodes#1136]
I cannot get AN to change anything in the viewport. I am on MacOS Mojave 10.14.5.

I have installed the latest Blender 2.8 and AN 2.1.4

Blend file attached.

TIA

<img width="501" alt="Screen Shot 2019-07-03 at 2 18 33 PM" src="https://user-images.githubusercontent.com/33334298/60625809-babebf00-9d9d-11e9-8868-8b0b3712e6b8.png">

<img width="1133" alt="Screen Shot 2019-07-03 at 2 24 31 PM" src="https://user-images.githubusercontent.com/33334298/60626026-505a4e80-9d9e-11e9-996f-ecbdaec5861d.png">

[ANtest.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/3356863/ANtest.blend.zip)

**Comment by OmarSquircleArt** [comment]
Thanks for the report! This has already been fixed, please wait for new official builds to be released.

**Comment by fvlasie** [comment]
Great! Thank you!
