### ISSUE TITLE
Fails to install on official builds for centos 7 

### ISSUE THREAD

**Issue by tkoham** [JacquesLucke/animation_nodes#1137]
other addons install fine, most recent build fails with error about a stdc++.so.6 mismatch.

**Comment by OmarSquircleArt** [comment]
Which builds of Animation Nodes and Blender are you using?

**Comment by tkoham** [comment]
The 64 bit betas from blender.org/download, on the creative reference platform (centos 7.6) no changes made to the OS except installing nuke and resolve. 

Tried the 2.1.4 releases as well as the previous release that lists itself as 2.8 compatible

**Comment by OmarSquircleArt** [comment]
I see, can you attempt to build it yourself on this platform?

**Comment by tkoham** [comment]
sure, but it might take a bit, I'll need to rip out python 36 and reinstall

**Comment by OmarSquircleArt** [comment]
Animation Nodes allow building using any python version using the `--noversioncheck` flag, just in case you didn't know.

**Comment by tkoham** [comment]
ah, that is useful
I'll report back when I get a chunk of free time.

**Comment by 3DSinghVFX** [comment]
@tkoham you can download **non-official** builds of Animation Nodes from graphical: https://blender.community/c/graphicall. For Linux: https://blender.community/c/graphicall/tdbbbc/

**Comment by verbal007** [comment]
Having a similar issue myself on CentOS 7.6.
Using a build of AN that I pulled today.

Unfortunately this is on a machine that I do not have admin privileges for, so I cannot build from scratch.
```
Traceback (most recent call last):
  File "/opt/blend281/2.81/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user234/.config/blender/2.81/scripts/addons/animation_nodes/__init__.py", line 166, in <module>
    auto_load.init()
  File "/home/user234/.config/blender/2.81/scripts/addons/animation_nodes/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/home/user234/.config/blender/2.81/scripts/addons/animation_nodes/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/home/user234/.config/blender/2.81/scripts/addons/animation_nodes/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/opt/blend281/2.81/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user234/.config/blender/2.81/scripts/addons/animation_nodes/libs/FastNoiseSIMD/__init__.py", line 1, in <module>
    from . node_base import Noise3DNodeBase
  File "/home/user234/.config/blender/2.81/scripts/addons/animation_nodes/libs/FastNoiseSIMD/node_base.py", line 6, in <module>
    from . wrapper import (
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/user234/.config/blender/2.81/scripts/addons/animation_nodes/libs/FastNoiseSIMD/wrapper.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by OmarEmaraDev** [comment]
I don't think there is anything we can do on our end. You are using an outdated system that is incompatible with the available official Animation Nodes builds.

I am guessing the only solution for you is to build things yourself, let us know if you need any help with that.

**Comment by verbal007** [comment]
@OmarEmaraDev , thank you for the quick response.

Sad to hear this, as I was hoping to share some of the great examples I've collected with some of the Houdini artists here at the studio.  I remained hopeful as SV seems to have installed fine.

That being said, as you pointed out, perhaps I can find someone in the studio that is willing to assist me in making a build.

Wish me luck!
