### ISSUE TITLE
No Update

### ISSUE THREAD

**Issue by insertcoindottv** [JacquesLucke/animation_nodes#1138]
Hello guys, we have here some trouble with AN 2.1.4 with Blender 2.8 2019-07-02.
We got no update at all using nodes. 
Any new version ? any fix or something else.
Work without AN is really hard for us...
Help plz.
Thanks.
Max.

**Comment by insertcoindottv** [comment]
Found a working version after go crazy here..
https://prenninger.com/3d/
Thanks Chris Prenninger so...

**Comment by OmarSquircleArt** [comment]
This issue has been fixed already, it is just that the official builds are not updated yet. Please wait for updated builds to be released.

**Comment by insertcoindottv** [comment]
Thank you Omar, but for a issue like this we hoped to find the fix on the official github instead of spending hours figuring out and trying to solve the problem.
Hope the best.
Max

**Comment by OmarSquircleArt** [comment]
Yes, sorry for the inconvenience. We will try to release new official test builds soon.

**Comment by insertcoindottv** [comment]
Thank you Omar. Have a nice day.
Ciao!
