### ISSUE TITLE
object instancer not creating collection of instances

### ISSUE THREAD

**Issue by ab-in** [JacquesLucke/animation_nodes#1139]
![show](https://user-images.githubusercontent.com/25300994/60710210-730d7400-9f12-11e9-8ca1-89bebc231eb3.png)

ubuntu19.04, latest beta, nvidia rtx2080

**Comment by OmarSquircleArt** [comment]
Thanks for the report! I can't replicate this. Is there any error printed on the terminal? Does everything work except this?

**Comment by ab-in** [comment]
oh so sorry, please remove that issue, I forgot to execute the node tree, I thought it does it automatic because auto execute was set. so I would say, auto execute dosn't work right.

**Comment by ab-in** [comment]
Sorry, i forgot to press execution node tree button, because i thought it
execute automatic. Auto execute was set, so maybe auto executing dosnt work
as I thought. I will remove that issue

Omar Ahmad <notifications@github.com> schrieb am Fr., 5. Juli 2019, 10:47:
