### ISSUE TITLE
Nodes Not Effecting objects. 2.8 Mac AN 2.1.4

### ISSUE THREAD

**Issue by akrillic** [JacquesLucke/animation_nodes#1140]
v2.1.4 appears to install successfully on mac after the system 'spins' for a while. However after adding nodes and attributing them to objects no effect takes place. Could someone help me diagnose the problem please?

Many thanks in advance
<img width="1678" alt="Screenshot 2019-07-05 at 23 13 26" src="https://user-images.githubusercontent.com/52582880/60743492-89e7b100-9f7a-11e9-8c68-62bffe66f6a7.png">

**Comment by OmarSquircleArt** [comment]
Thanks for the report! This issue has already been fixed, please wait until new official builds are release.
