### ISSUE TITLE
3D Viewer Node crash the Blender 2.8

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1141]
Hi...
I have found that on the latest blender 2.8 builds, 3D Viewer Node crashes the Blender 2.8,
![3DViewer1](https://user-images.githubusercontent.com/30294746/60963699-1ef9f980-a32f-11e9-95ef-394f38e7c034.png)

Message in the crash file:
![Screenshot from 2019-07-10 16-23-27](https://user-images.githubusercontent.com/30294746/60963715-2d481580-a32f-11e9-82d3-097778e84cc3.png)

Blend File (Enable the auto execution to run the node-tree): [3DViewer1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/3377111/3DViewer1.blend.zip)

**Comment by OmarSquircleArt** [comment]
I can't replicate this. Does this happen whenever you use the Viewer node? Do you builds Blender yourself?

It seems like the source of the bug is in the Python C API ...

**Comment by 3DSinghVFX** [comment]
Omar, I have installed the fresh blender, a fresh build of AN and still it is crashing. I have noticed that blender does not crash when there is no 3D Viewport but as soon as I open the 3D Viewport then blender crashes :(

**Comment by 3DSinghVFX** [comment]
I tried to build blender few days ago but showed some error then I left it. Is it conflicting?

**Comment by 3DSinghVFX** [comment]
I have found that this problem occurs when I connect any Matrix Socket (e.g., Matrix distribute, Matrix Compose) to 3D Viewer Node.
![3dview1](https://user-images.githubusercontent.com/30294746/60999045-d3b80900-a377-11e9-8934-bf1f18cd1d02.png)

**Comment by OmarSquircleArt** [comment]
I can replicate this now. Thanks for the report! Will investigate.

**Comment by OmarSquircleArt** [comment]
Hey @3DSinghVFX , can you please execute the following and tell me if Blender crashes? Thanks!

```python
import bpy
import gpu
from gpu_extras.batch import batch_for_shader

vertex_shader = '''
    uniform mat4 viewProjectionMatrix;

    in vec3 position;
    out vec3 pos;

    void main()
    {
        pos = position * float(gl_VertexID) / 2.0;
        gl_Position = viewProjectionMatrix * vec4(position, 1.0f);
    }
'''

fragment_shader = '''
    in vec3 pos;

    void main()
    {
        gl_FragColor = vec4(pos, 1.0);
    }
'''

coords = [(1, 1, 1), (2, 0, 0), (-2, -1, 3)]
shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
batch = batch_for_shader(shader, 'TRIS', {"position": coords})


def draw():
    shader.bind()
    matrix = bpy.context.region_data.perspective_matrix
    shader.uniform_float("viewProjectionMatrix", matrix)
    batch.draw(shader)


bpy.types.SpaceView3D.draw_handler_add(draw, (), 'WINDOW', 'POST_VIEW')
```

**Comment by 3DSinghVFX** [comment]
@OmarSquircleArt Yes, it crashes the Blender 2.8.

**Comment by JacquesLucke** [comment]
https://developer.blender.org/D5231

**Comment by OmarSquircleArt** [comment]
Can confirm that this commit fixes the problem. I also update the shader in 41b545a.

The patch didn't make it to the release candidate, so avoid drawing matrices for now. We will close this as soon as the patch makes it to master.

**Comment by 3DSinghVFX** [comment]
I have tested with the latest Blender build, AN is still crashing with 3D Viewer Node. I think the patch has not made it to the master branch.

**Comment by OmarSquircleArt** [comment]
Pretty sure it was commited to master, see B576963. I just build it from latest source and it worked. Maybe try with tomorrow's build.

**Comment by 3DSinghVFX** [comment]
Okay. I'll try it tomorrow :)
