### ISSUE TITLE
Sound Spectrum Frequencies 

### ISSUE THREAD

**Issue by 18gtorres** [JacquesLucke/animation_nodes#1142]
Not sure if this is an issue, but whenever I use the Sound Spectrum Node and use Full to get all the frequencies from a song, the number of frequencies I get corresponds to the scene's fps. Is there a way around this or is this a bug?
![image](https://user-images.githubusercontent.com/49108791/61086201-d9edca00-a3f7-11e9-9a2e-c90b6e3f9fdc.png)
![image](https://user-images.githubusercontent.com/49108791/61086221-e6722280-a3f7-11e9-9ecc-26cf36eb75f0.png)

**Comment by OmarSquircleArt** [comment]
This is not a bug. The sound have a fixed sample rate, the more frames per second you have, the less samples each frame will have. Does this make sense?

**Comment by 18gtorres** [comment]
I understand, but how come? How do I adjust rate? I'm having trouble finding it in AN.

**Comment by OmarSquircleArt** [comment]
How do you adjust the same rate?

**Comment by 18gtorres** [comment]
Yes, I want more samples.

**Comment by OmarSquircleArt** [comment]
@18gtorres You have two options to get more samples:

- Increase the *Minimum Duration* parameter in the *Advanced Node Settings*. This will increase the spectral resolution of the spectrum, but you will get overlapping spectrums.
- Interpolate the output samples manually. This will increase the samples, but the spectral resolution will stay the same. In other words, you won't get any new information.
