### ISSUE TITLE
Object Input Linked to Output Not Updating Field

### ISSUE THREAD

**Issue by ClickActionFilms** [JacquesLucke/animation_nodes#1143]
![Capture](https://user-images.githubusercontent.com/16901314/61153570-382ab380-a4b1-11e9-8846-ca0b3e5ba940.JPG)
Using Blender 2.8 with AN 2.1.3 and I'm thinking this is not the correct behavior. New to this plugin so I apologize if this is normal functioning.

**Comment by OmarSquircleArt** [comment]
You are using an outdated version of Animation Nodes. If you are on Linux or Windows, you can download the following builds:
https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1.4

If you are on Mac, please be patient while a Mac version become available.
