### ISSUE TITLE
animation nodes for Mac blender 2.8

### ISSUE THREAD

**Issue by 3omar9** [JacquesLucke/animation_nodes#1145]
<img width="833" alt="Screen Shot 2019-07-12 at 8 30 10 PM" src="https://user-images.githubusercontent.com/52842530/61164508-d9caf880-a4e3-11e9-8e7a-691c39293de4.png">

Hey, 
AN 2.1.4 for Mac doesn't exist anymore any updates or other way to install AN on a MacBook Pro blender 2.8 candidate 
Thanks

**Comment by OmarSquircleArt** [comment]
You will have to build it yourself or wait until we find somebody who can maintain a Mac build.

**Comment by 3omar9** [comment]
Thanks for the respond 
I wish I could, not even the previous versions work on blender 2.8 on Mac

**Comment by luca259** [comment]
I uploaded build for mac (commit 41b545a 15/07/2019):
https://blender.community/c/graphicall/nfbbbc/

**Comment by 3omar9** [comment]
Thanks for the work you have done,  after I installed your build I am getting this error 
anyway to fix that?
<img width="659" alt="Screen Shot 2019-07-16 at 4 22 50 PM" src="https://user-images.githubusercontent.com/52842530/61327099-282f0e80-a7e6-11e9-9e97-8858a3162cab.png">

**Comment by OmarSquircleArt** [comment]
Thanks @luca259 ! Can anyone confirm if this works as expected?

@3omar9 You need the numpy python module to run Animation Nodes. Either use a Blender build with numpy or try to download it yourself.

**Comment by 3omar9** [comment]
It works like a charm ! Thank you so much guys really appreciate the hard & creative work and suggestions @OmarSquircleArt @luca259 @JacquesLucke

**Comment by g3ntile** [comment]
I'm not a developer, just a mac user with some limited scripting and shell skills, I regularly compile my own master branch, and managed to compile a few other branches successfuly. I wasn't anyway been able to compile this addon myself. Maybe if someone can take the time to explain briefly the process, and I manage to compile it myself I have no problem uploading it to GA. 
And a really big thank you to all you guys for all this great work.

**Comment by OmarSquircleArt** [comment]
@g3ntile I haven't tried this before, but you need three things:

1. Python 3.7.
2. Cython.
3. A C Compiler.

All of those are available on Homebrew if you are going to use it. After installing those, move to the source directory and invoke the `setup.py` file as follows:

```
python setup.py build --export
```

The `--export` option will create a `.zip` file can be installed from Blender as one would normally do.

**Comment by g3ntile** [comment]
@OmarSquircleArt Thank you! I'll try

**Comment by fvlasie** [comment]
Just to confirm that the Mac build is working for me in the Blender 2.8 release candidate.
Great work everyone!

**Comment by OmarSquircleArt** [comment]
So, I guess we can close this now.
