### ISSUE TITLE
blender 2.8 AN 2.1 win 10(64) no autoexecution

### ISSUE THREAD

**Issue by EugeneBlenderLife** [JacquesLucke/animation_nodes#1147]
I have the latest Blender 2.8 (beta d663048696b2) + AN 2.1.3

- cube
- AN window
- checked "autoexecution"
- either "always" checked or not
- three tick below are on

no any executions I need to press Execute Node Tree

(any suggestions?)

**Comment by OmarSquircleArt** [comment]
You are using an old version of Animation Nodes, please this this build instead:

https://blender.community/c/graphicall/Xdbbbc/
