### ISSUE TITLE
Animation Nodes not working in latest builds of Blender 2.8

### ISSUE THREAD

**Issue by KrayneCG** [JacquesLucke/animation_nodes#1148]
For some reason Animation nodes no longer works in blender 2.8.  It was working just fine in previous iterations of Blender 2.8:
(blender-2.80.0-git.0e78e3038d02-windows64 April ‎3, ‎2019 and back)
but when I updated to a new daily build: 
(blender-2.80.0-git.c252fe7a32ab-windows64 ‎July ‎4, ‎2019 and forward)
it just.... stopped.  When I open a new node tree and throw in an object instancer, nothing happens.  A collection in the outliner should appear immediately as I scrub the instances up, but nothing at all happens in the viewport or outliner.
 
The time-per-frame in the top left goes up as I add instances and nodes, so its doing SOMETHING but I get no result at all anywhere else.

So for now, I have to do all my AN stuff in the april 3 build, bake it there then copy it into the latest build for it to work.  Please say I won't have to do this for long.

Thanks!

**Comment by OmarSquircleArt** [comment]
Where did you get your Animation Nodes build?

**Comment by luca259** [comment]
Using the 2.80 release candidate I have the same problems.
The error occurs due to the lack of `scene.update()` method in the `execution/auto_execution.py` file (https://docs.blender.org/api/master/bpy.types.Scene.html).
I tried to replace it with `scene.frame_set(scene.frame_current)` and it works.

Hope this helps.

**Comment by KrayneCG** [comment]
I'm pretty sure I got it from here a few months ago (February 22) but I see that it is 2.0.  Is a later release out?

**Comment by KrayneCG** [comment]
Alright… how do I do that?  I’m sorry, I haven’t written scripts since JavaScript and I only did a bit of C++ coding for fun (I hated C++’s class system). I haven’t learned Python so I have no idea how to implement your fix.
Thanks for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by luca259** [comment]
I'm sorry, my mistake, was related to another problem with an old version; the last version (2.1.4) working properly.

**Comment by OmarSquircleArt** [comment]
Please try this builds instead:

https://blender.community/c/graphicall/Xdbbbc/

Does it work?

**Comment by KrayneCG** [comment]
Hmmm no.  I think I made a mistake, I tried to install the new version over the old one without first removing it.  Now when I click the check box to activate tha addon, I get this message:
(blenderror.jpg)
Then when I expand it and click on the remove button I get this error:
(blenderror2.jpg)

I tried deleting all versions of blender 2.8, cleaned the registry, then re-installed the release candidate.  That didn’t work.  Then I tried deleting everything with “blender” in the filename or path (except, of course, for my project folder) and that broke windows.
So I loaded up the restore point I created before starting any of that and decided to ask for more help.
How do I remove older versions of AN and where does Blender put its UI preferences?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by OmarSquircleArt** [comment]
I don't use Windows, so I don't know where addons are installed exactly. However, there is a user and a system-wide directories where addons can be installed. So AN could be there, even if you removed Blender itself.

**Comment by KrayneCG** [comment]
Ohh thank you.  I found it in c:\users\krayne\appdata\roaming\Belnder Foundation\Blender\2.80\scripts\addons\animation_nodes
For some reason, I didn’t see it in my previous searches.
Aaaaaand… it WORKS!  Thank you SO much!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by eman11110** [comment]
I try to use animation node in blender 3.00 and didn't work
what can i do ??

**Comment by OmarEmaraDev** [comment]
@eman11110 How does it not work? Does it give any errors?
