### ISSUE TITLE
Fails when try to rename an object

### ISSUE THREAD

**Issue by luca259** [JacquesLucke/animation_nodes#1149]
With all the nodes with input the name of the object (e.g. Object Transforms Output node) if you click on button and holding down `CTRL` to rename object when there is no inserted object name the procedure fails. AN for Blender 2.8 last commit 41b545a.

The button:
![Screen Shot 2019-07-18 at 14 08 48](https://user-images.githubusercontent.com/52927955/61456253-e1682280-a965-11e9-8de4-70fafb198f02.png)

Trace log:
![Screen Shot 2019-07-18 at 14 10 30](https://user-images.githubusercontent.com/52927955/61456277-f3e25c00-a965-11e9-8d7b-18b6b02ae520.png)

The problem seems to be solved by applying the following simple (no error message) patch to the `sockets/object.py` file that does not allow to rename, unless it has been selected:
```
46,49c46,50
<             bpy.ops.an.rename_datablock_popup("INVOKE_DEFAULT",
<                 oldName = self.object.name,
<                 path = "bpy.data.objects",
<                 icon = "OBJECT_DATA")
---
>             if self.object:
>                 bpy.ops.an.rename_datablock_popup("INVOKE_DEFAULT",
>                     oldName = self.object.name,
>                     path = "bpy.data.objects",
>                     icon = "OBJECT_DATA")

```

Thanks

**Comment by OmarSquircleArt** [comment]
Thanks! Do you want to make a pull request?
