### ISSUE TITLE
inside Loop variable list

### ISSUE THREAD

**Issue by kopias** [JacquesLucke/animation_nodes#115]
To use variables inside loop you need to pass them to "Loop Call" node.
To add variable input you have 'new list' or 'new option' on "Loop Start" Node and list type is set automatically based on what you connect to but...
right away you cannot connect it to "Get Element" list node and for users it will indicate that this is not possible, but that's wrong assumption, you just need to initialize "Get Element" node

if im not making sense here, try to recreate this basic instance setup:
http://www.pasteall.org/blend/35305

possible solution:
maybe move 'new list' and 'new option' to "Loop Call" ?

**Comment by JacquesLucke** [comment]
do you think something like I did with the script node is also a possible solution?: https://www.youtube.com/watch?v=5bVosFKVTHI&list=UU5ABAuGEvBMmau-1xJsNw6w

**Comment by og76** [comment]
my two cents: adding sockets like the script node would be great for loops and groups ..

**Comment by JacquesLucke** [comment]
This is true. I will make a new issue for that
