### ISSUE TITLE
New node tree is overlapping subprogram button on Blender 2.8 RC for osx

### ISSUE THREAD

**Issue by funtomas78** [JacquesLucke/animation_nodes#1152]
Hi there. Iv found one glitch . If i make new node tree. The small menu overlapping subprogram button. Maybe is not topic for blender developers. But just letting you know. Thanks Jan
![Snímek obrazovky 2019-07-19 v 23 15 25](https://user-images.githubusercontent.com/53055083/61566033-25991700-aa7b-11e9-995e-93509f77304d.png)
![Snímek obrazovky 2019-07-19 v 23 15 30](https://user-images.githubusercontent.com/53055083/61566034-25991700-aa7b-11e9-8c77-d2632de93982.png)

**Comment by funtomas78** [comment]
I meant is topic for blender developers.

**Comment by OmarSquircleArt** [comment]
Thanks for the report! This is a duplicate for #1091.
