### ISSUE TITLE
Blender 2.8 install issue Numpy missing (traceback error)

### ISSUE THREAD

**Issue by cgmatter** [JacquesLucke/animation_nodes#1154]
I'm having issues installing the newest 2.1.4 AN on the release candidate of blender from blender.org. I have ensured that there are no lingering animation_nodes folders in the scripts folder etc (and I have also tried 2.1). Here is the error I keep getting (and I am also running 64 bit so that shouldnt be the issue):
![errorsnip](https://user-images.githubusercontent.com/53167098/61611245-5454f000-ac29-11e9-9cdb-add971ba4591.PNG)

**Comment by cgmatter** [comment]
also I did some digging around my blender 2.8 files and found this:
![snip2](https://user-images.githubusercontent.com/53167098/61612673-37222080-ac2d-11e9-8092-49a2d871a177.PNG)
so numpy should be installed? Why this issue then?

**Comment by OmarSquircleArt** [comment]
Can you try to `import numpy` from the Blender console and see if it works?

**Comment by OmarEmaraDev** [comment]
@cgmatter Can you report back on this?

**Comment by dronov-dmitry** [comment]
![изображение](https://user-images.githubusercontent.com/9892891/71768362-02293200-2f1e-11ea-8fc8-3557274477a2.png)

**Comment by OmarEmaraDev** [comment]
@dronov-dmitry Which Blender build are you using? Does it come with portable python or does it us the system python?

**Comment by dronov-dmitry** [comment]
@OmarEmaraDev 
1) blender 2.82
2) it come with implement inside blender python 3.7.5.. When i import numpy from system python 3.6.9 it import correctly
![изображение](https://user-images.githubusercontent.com/9892891/71768501-25081600-2f1f-11ea-91a9-d8f4b6020795.png)

**Comment by OmarEmaraDev** [comment]
Because the python and numpy versions match. In case of Blender, you are importing numpy made for 3.6 while Blender users 3.7.

I meant where did you get the build? Did you downloaded it from the Blender website, from the package manager, or compiled it yourself?

**Comment by dronov-dmitry** [comment]
I get it here: https://askubuntu.com/questions/169542/how-do-i-install-the-latest-blender-3d-builds-from-a-ppa#169546
sudo add-apt-repository ppa:thomas-schiex/blender
sudo apt-get update
sudo apt-get install blender

**Comment by OmarEmaraDev** [comment]
To quote the PPA:

> For NumPy to work with Python 3.7 or higher on Python 3.5 based distributions, please install numpy with pip.

I am guessing the same apply for your distribution. Alternatively, just download a portable build from Blender.

**Comment by dronov-dmitry** [comment]
I run blender 2.81 from site https://www.blender.org/download/
and numpy run
![изображение](https://user-images.githubusercontent.com/9892891/71769219-d2caf300-2f26-11ea-9c28-a357bf97d92f.png)
thnx a lot
