### ISSUE TITLE
Official Releases of Animation Nodes

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1155]
Hi Chaps!

At the moment I am running Blender 2.8 from 6 April 2019 (blender-2.80.0-git20190406.542725d3e973-x86_64) with the latest AN 2.1.4 release (march 2019) and no patches, simply because this works. I have been reading all the issues since with all the problems and wished to avoid these...

So my question is; When will we have an official release that works with official 2.8, given that official 2.8 is nearly with us? I am running on a Mac but the way, it would be nice to know this so I can plan an orderly transition from my current setup.

Thanks, Clock.

**Comment by OmarSquircleArt** [comment]
As far as I know, there won't be any releases. Currently, we started relying on the community to provide test builds in graphicall, and we will continue like this for sometime.

Development is mostly halted for now, Jacques is very busy making us Functions nodes. I try to maintain AN by fixing bugs and making sure it works as expected, but I can't do more until I finish GSoC.

**Comment by Clockmender** [comment]
OK, but the latest releases for 2.1 are march 2019, I don't think these will work with RC1, or RC2 - I will wait to see what happens...

**Comment by OmarSquircleArt** [comment]
Those builds are not from march, they are from last week. It is just that the post is from march.

https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1.4

**Comment by Clockmender** [comment]
OK!
