### ISSUE TITLE
Create node groups

### ISSUE THREAD

**Issue by RodeyOrg** [JacquesLucke/animation_nodes#1158]
Hi, I'd really like to be able to save my node tree setups as groups and reuse. But the option seems always greyed out. 

Can someone please help. 

AN 2..04
BD 2.79b

Thanks

**Comment by OmarSquircleArt** [comment]
Which options is grayed out?

**Comment by Clockmender** [comment]
Have you read this: https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/group.html

It will explain how to use Groups. If you want to copy a node tree from one project to another, just select all nodes - CTRL+C - CTRL+V in new project/nodetree/whatever.

Please always post a image of the problem, so we can better diagnose the issue.

**Comment by RodeyOrg** [comment]
> Which option is grayed out?

@OmarSquircleArt 

This one:

![Screen Shot 2019-07-28 at 00 51 56](https://user-images.githubusercontent.com/44178760/62000573-13018c00-b0d2-11e9-9263-755f3eedc3b5.png)

**Comment by RodeyOrg** [comment]
> Have you read this: https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/group.html
> 
> It will explain how to use Groups. If you want to copy a node tree from one project to another, just select all nodes - CTRL+C - CTRL+V in new project/nodetree/whatever.
> 
> Please always post a image of the problem, so we can better diagnose the issue.

Thanks, I had read this before, (noted about the screenshot). 

This is not quite what I am looking for— I simply meant a way to store/save nodes for reuse later, at _any_ point and in _any_ project.

**Comment by OmarSquircleArt** [comment]
Animation Nodes does not support Blender's node groups. See my answer here for an alternative:

https://blender.stackexchange.com/questions/79711/process-of-turning-groups-of-animation-nodes-into-templates-for-easy-reuse#answer-117274

**Comment by RodeyOrg** [comment]
> Animation Nodes does not support Blender's node groups. See my answer here for an alternative:
> 
> https://blender.stackexchange.com/questions/79711/process-of-turning-groups-of-animation-nodes-into-templates-for-easy-reuse#answer-117274

Oh I see :( 

Thanks.

**Comment by RodeyOrg** [comment]
PS I am possibly missing something obvious, but how do I actually save the subprograms for reuse in other projects/files?

This is my reference:

https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/group.html
