### ISSUE TITLE
I just cannot find the node in the list when installing

### ISSUE THREAD

**Issue by windwe2** [JacquesLucke/animation_nodes#1160]
I just cannot find Animation node in the add on list after I choosed the Zip file I download in Blender 2.79 and 2.8 when I try to install. So that I cannot active it. My system is Win10.  What should I do? 
![批注 2019-07-28 152231](https://user-images.githubusercontent.com/53392740/62003597-be9af280-b14b-11e9-9cf2-cee1989ec6ba.jpg)

**Comment by OmarSquircleArt** [comment]
Did you download the following build?

https://blender.community/c/graphicall/Xdbbbc/

**Comment by samytichadou** [comment]
Hi, had the same issue on a graphicall build, it was caused by special characters in the name of the zip and its subfolder. If you have the same issue, you can resolve it by getting rid of the - . in folder's name. Cheers!

**Comment by 3DSinghVFX** [comment]
@windwe2 Probably, you have installed the source code of AN. So first remove the AN files from the addon folder then install newly AN build, **the download button is in the red square**, https://blender.community/c/graphicall/Xdbbbc/

![Screenshot from 2019-08-30 12-24-10](https://user-images.githubusercontent.com/30294746/63999673-9d9a3880-cb21-11e9-87bd-db9389a3f084.png)

**Comment by OmarEmaraDev** [comment]
@windwe2 Can you report back on this?
