### ISSUE TITLE
Crash when trying to instance a collection instance

### ISSUE THREAD

**Issue by ogierm** [JacquesLucke/animation_nodes#1161]
Hi,

I'm trying to instance collection instances (I want to use this to wrap an ocean modifier in a collection and then lay it out in a grid), but unfortunately Blender crashes when toggling "Copy Full Object".

Here is a minimal example:
[crash.zip](https://github.com/JacquesLucke/animation_nodes/files/3439452/crash.zip)

**Comment by ogierm** [comment]
For now a good workaround is to manually duplicate them and then use AN to lay them out in the grid.

**Comment by OmarSquircleArt** [comment]
Thanks for the report! I can replicate that. We will look into it.

**Comment by OmarSquircleArt** [comment]
Fixed in 1a3edda.

**Comment by OmarSquircleArt** [comment]
See Blender bug report T67857.
