### ISSUE TITLE
Red Frames

### ISSUE THREAD

**Issue by ElPunia** [JacquesLucke/animation_nodes#1163]
Hi, I switch from B3D2.8 RC to the last one and now all boxes inside animation nodes editor appear in red. I've tried to uninstall many times...but no success.

**Comment by OmarSquircleArt** [comment]
Can you open the console/terminal and show us the printed lines?

**Comment by ElPunia** [comment]
I'm working on it....after reset computer, it worked.... now I'm looking
for one missing node. Sorry for the question I maybe had to reset computer
before contacting you. Maybe is a kind of firewall from security dept. at
office....I will talk with them to know what are they doing with
permissions.

P.D. I attach the actual state of AN (working) but with alert that at least
one undefined node.

Thank you very much.

**Comment by OmarSquircleArt** [comment]
The undefined node is probably a node that doesn't exist in your AN version. AN doesn't maintain backward compatibility.

Is this issue resolved then?

**Comment by ElPunia** [comment]
Yes. Thanks a lot!!!

**Comment by ElPunia** [comment]
Good morning. Has Set Vertex Weight nodes removed from last version?
I'm using this version, because the other gave me errors...
https://blender.community/c/graphicall/Xdbbbc/

Thank you very much.

**Comment by 3DSinghVFX** [comment]
@ElPunia Actually, that node is available in this AN + ExtraNodes build: https://blender.community/c/graphicall/xdbbbc/

**Comment by ElPunia** [comment]
Good morning...still having trouble to use estra nodes

I've tried several times....even in manual mode copying folders with new
nodes....All I get is this mesaage when I try to install:

[image: B3D_28_AN_activation_error.png]

I'm using Blender 2.8 version and downloaded the Animation Nodes addon from:

https://blender.community/c/graphicall/xdbbbc/

Could you please, spot me in what am I failing? Last version of AN 2.1.4
withou extra nodes worked fine...

Thank you very much.

**Comment by 3DSinghVFX** [comment]
@ElPunia the attached image did not open.
