### ISSUE TITLE
Wiggle Falloff Node does not give smooth animation when the seed is not zero in blender 2.79/2.8x

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1164]
Hi...
I have just found that wiggle falloff node does not give smooth animation when the seed is not zero in blender 2.79 and 2.8x. 
Thanks :)

![screen](https://user-images.githubusercontent.com/30294746/62446466-6cc41f00-b780-11e9-8db0-da325b986f2e.png)

**Comment by OmarSquircleArt** [comment]
I can replicate this. Thanks for the report!

**Comment by mattdw** [comment]
Looking at the code, it's using c floats in the node, and multiplying the seed by a pretty large constant. Converting the 'evolution' calculation to double makes a big difference but doesn't totally fix it.

**Comment by OmarEmaraDev** [comment]
Fix in 2879b5c.
