### ISSUE TITLE
Set Keyframes Node is not working

### ISSUE THREAD

**Issue by lime517** [JacquesLucke/animation_nodes#1165]
The Set Keyframes node doesn't seem to be working. I have a simple node setup where a light gets brighter the closer an empty object gets to it. I have a Set Keyframes node that is enabled, but no keyframes are getting set. I've also enabled the 'record' button, but still - no keyframes.
 I need to bake this to an animation since AN doesn't work while rendering animations. 

You can see my example scene here:
[test.zip](https://github.com/JacquesLucke/animation_nodes/files/3472580/test.zip)

This seemed to be working with 2.8 RC1, but I have yet to confirm that.

**Comment by lime517** [comment]
Update, not working in RC1, though I've been able to get the set keyframes node working in another test scene, leading me to believe that it's a scene issue..... Will follow up when I figure out more!

**Comment by OmarSquircleArt** [comment]
Your node tree scene is set to `Scene.001` while your are working on `Scene`. In the *Animation Node Tree* panel, change the scene to `Scene` and everything should work as expected.

Did this work?

**Comment by lime517** [comment]
Yup. That was definitely it. 
Thank you SO much.
