### ISSUE TITLE
Combine Mesh node not work correctly

### ISSUE THREAD

**Issue by jaxxtrend** [JacquesLucke/animation_nodes#1167]
blender 2.8
When not connect edges or connect incomplite edge indices list polygons not drawing and i see message about missing edges.
I expect edge indices auto generate if i connect vertices and polygon lists. Like in doc example.

**Comment by OmarSquircleArt** [comment]
The documentation is for version v2.0. In v2.1, edges has to be supplied explicitly. You may generate them from polygons using the *Polygons To Edges* node.

**Comment by jaxxtrend** [comment]
Thanks.
