### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by PJCSpencer** [JacquesLucke/animation_nodes#1169]
Hi there,

Recently tried to install on my MacBook Pro 2015, MacOS Mojave (10.14.6) but failed with the following message.

<img width="654" alt="Screenshot 2019-08-11 at 12 55 20" src="https://user-images.githubusercontent.com/12965628/62833517-e99b4100-bc37-11e9-87b2-63f2508d1180.png">

**Comment by OmarSquircleArt** [comment]
Which Animation Nodes build are you using? Can you try this build:
https://blender.community/c/graphicall/nfbbbc/

**Comment by MarsBCN** [comment]
Peter, 
I've just compiled a python3.7 version for osx. Feel free to check if it works for you:

[animation_nodes_v2_1_macOS_py37.zip](https://github.com/JacquesLucke/animation_nodes/files/3498898/animation_nodes_v2_1_macOS_py37.zip)

The sources are from a 2.1.4 source zip file

**Comment by PJCSpencer** [comment]
Hi there,
@MarsBCN Just installed using the compiled version you uploaded and it appears to work as expected. Thank you so much! Really really great.

Theres a warning message after install, see attached.

<img width="822" alt="Screenshot 2019-08-14 at 20 47 52" src="https://user-images.githubusercontent.com/12965628/63051735-ac53df00-bed5-11e9-8e6f-876c8b47a5ef.png">

**Comment by OmarSquircleArt** [comment]
@MarsBCN I suspect this build will install but will not work properly. You should build from the  blender2.8 branch.

@PJCSpencer This is a standard warning, no need to worry.

**Comment by MarsBCN** [comment]
@OmarSquircleArt  I think the sources were from the 2.8 

@PJCSpencer 
I have linux and OSX plugings compiled from the git 2.8 branch in my fork. Tested on the blender 2.8 release and the git blender 2.8 development branch+sculp mode (Pablo Dovarro mod).
[https://github.com/MarsBCN/animation_nodes/tree/blender2.8](url)
Check that build if the other do no work as expected.

**Comment by OmarSquircleArt** [comment]
Ah, Ok. In this case, everything should work as expected. Closing.
