### ISSUE TITLE
Object Matrix Input does not work during Rendering

### ISSUE THREAD

**Issue by fohly** [JacquesLucke/animation_nodes#1171]
As far as I can tell the "Object Matrix Input" node does not work when rendering an animation.
It just returns the same matrix every frame.
In the viewport it works as expected. It also bakes fine.

I tested this with the build from here: https://blender.community/c/graphicall/Xdbbbc/
On Windows 64 bit with the 2.80 release.

Here is a little file to reproduce this:
[animation_render_matrix.zip](https://github.com/JacquesLucke/animation_nodes/files/3511214/animation_render_matrix.zip)

The cube at the bottom has keyframes to move from left to right.
The nodes should
(1) make suzanne follow the cube and
(2) update the text at the top to show the position of the cube.

However, if you start an animation render, you will see that suzanne will stay in one place and the text will not update.

**Comment by OmarSquircleArt** [comment]
I am getting a crash, but this is probably related to the rendering issues of the depsgraph as we update all view layers appropriately.

**Comment by 3DSinghVFX** [comment]
I able render this with "Object Matrix Input" and "Object Transforms Input" Node as input for "suzanne" object. In both cases,  "suzanne" object does not follow "cube" object in rendering and remains still.

**Comment by OmarEmaraDev** [comment]
Fixed in #1294 and b1ac938.
