### ISSUE TITLE
2.80 Objects From Group was removed

### ISSUE THREAD

**Issue by julianusx** [JacquesLucke/animation_nodes#1176]
The blender2.8 branch removed Objects From Group in commit f6ee04c587a2424502a68253386f6039f7bda613.

Was this intentional? In that case what is replaced with?

Thx

**Comment by OmarSquircleArt** [comment]
*Groups* were removed from Blender 2.8 itself. You may use *Collections* instead. The *Collection Info* node can be used as an alternative to the *Objects From Group* node.

**Comment by julianusx** [comment]
Thanks. That makes sense.
It would be nice to update the documentation, to make it easier to migrate.
