### ISSUE TITLE
I can’t install animation nodes

### ISSUE THREAD

**Issue by danielhamen** [JacquesLucke/animation_nodes#1179]
I have blender 2.79 and I am trying to do walls animation nodes but it keeps saying I have other files of animation nodes but I don’t. I 
![image](https://user-images.githubusercontent.com/54770658/64077156-6bace180-cc9b-11e9-9150-efcb3ba32154.jpg)

Here is a picture

I have downloaded this before but I already uninstalled it.

If anyone can help that would be greatly  appreciated☺️

**Comment by OmarSquircleArt** [comment]
There are three possible locations where addons can be stored. The extra version is probably in one of them. Go to every location and delete the folder called `animation_nodes` manually.

**Comment by danielhamen** [comment]
I did and it still won’t work

**Comment by OmarEmaraDev** [comment]
@danielhamen Are you still having trouble installing Animation Nodes?

**Comment by danielhamen** [comment]
No I had to do some weird stuff I don’t exactly know what I did but it
worked thanks though

**Comment by OmarEmaraDev** [comment]
I see. We will make sure to update the installation guide to make things more clear in the future.
