### ISSUE TITLE
object instancer does not create new Action/fcurves, but uses the same as original

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#118]
[instancer / copy full object / deep copy all or any]
instances use same action/fcurves as the original, while they should have new ones, as is the case with manual duplication (shift+D). 
This happens both
- For "key actions" or other mesh related for deep copy
- For any "action/fcurve" for copy full object

This is wrong because:
- it is not obvious/consistent -you don't know it
- when you operate on an instance you end up spoiling the original +erratic results
- there is no immediate way to get a new action/fcurve for each i

see example blend where 
Cube is the original -> CubeAction  +shape key -Key action
Cube.001 instance -> CubeAction + shape key -Key action (same)
Cube.002 manual   -> CubeAction.001 +shape key -Key action 002  created for it 
https://drive.google.com/file/d/0BzzAoBwXO8dsLWpfM2JURzhWYUE/view?usp=sharing

Note that 
*each time you make a manual duplicate there is a new action/fcurve created, even if undo and shiftD again. so in the case of many instances, there may be an issue ..
*This is even more tricky and hidden as animnodes/scripts operate after fcurves (they beat the fcurves), so for usual direct manipulation (transforms output, obj matrix output etc) you get the expected result, so you don't see this immediately.
*This is not the case with drivers, due to the nature of driver implementation (every driver for himself, not part of action) And drivers beat everything anyway.

got into that while trying to manipulate f curves in script and while creating keyframes with set key node

**Comment by og76** [comment]
related to #106, but also for deep copy (case of shape key animations)

**Comment by JacquesLucke** [comment]
I look into it now

**Comment by og76** [comment]
first glimpse it works OK for copy full object, including constraints etc
animation_data.action

for deep copy, still not doing the key actions (different job as it is related to the mesh data)
data.shape_keys.animation_data.action

looking in the dope sheet seams to have created another key.007 action, but the fcurve is the same?
I'm kinda lost
lookin in the outliner/data blocks under actions I see clearly 3 cube actions but only 2 key actions

**Comment by JacquesLucke** [comment]
I'm thinking about removing this functionality again, because it clutters the code and isn't really needed. The object instancer should be used to create objects which are animated with other nodes.

**Comment by og76** [comment]
Well, I cannot say about clutter, but about the need and uses, I do. If the shapekey key actions is an issue, you may vary well drop it as that is really marginal, and from what I can tell is more of a bad implement for an inherited thing. But for the rest, do not.

And animating with nodes was exactly what I was trying to do. 
 Examples:
- After creating Fcurve with the very set key node for the original, sort of baking to an Fcurve, the instances would have the Fcurve altered in whatever way, including moving keys on x, thus on the timeline. This cannot work but with Fcurves (or in nla editor, but that's another story)
- Or imagine original having follow path constraint with respective animation (fcurve in offset..) and instances having that fcurve altered so that they follow path but random or otherwise.

However, I'd say that (obviously pleading for keeping the functionality):
- I needed fcurves because in the current (hope to be changing) implementation, only for objects with f curves we are exposed to certain time/frame info, meaning access to frame data before or after without the need to iterate the whole scene thru all frames, as the object info is mining
- there is no direct or nodes way to insure separation of fcurves/actions if needed, as I need in the examples above
- there is no other place in Blender where the fcurves/actions are kept the same, but more importantly, it is error prone as it is not expected
- instancer can be a good replacement for dupli methods in objects and particles where one needs control with nodes and such, so I would not limit the purpose for inside nodes
- instances work well with constraints and modifiers, where I use such with influencing parameters with nodes. 

If the usage is not convincing I'll prepare some blends

**Comment by JacquesLucke** [comment]
Ok I think I got an idea how to implement that, but unfortunally I won't be able to do it this week. Next week should be possible :)

one or two simple .blends would be awesome

**Comment by og76** [comment]
here two blends
1
path follow constraint, especially cause it uses fcurve to work
https://drive.google.com/file/d/0BzzAoBwXO8dsalVxQy1maVYyYUU/view?usp=sharing
keyframes of instances are altered by math/index

note that I can have many key points and add an extra loop (inside that loop) to iterate thru the number of key points etc

2
distance traveled, look ahead, wheel rotations 
https://drive.google.com/file/d/0BzzAoBwXO8dsRlE2Zm1ucEpYd2s/view?usp=sharing
I need an fcurve for each cube to determine the wheel rotation for each circle. The rest of the noodle does not matter here, it's all about the keypoints moving instead of direct matrice intervention, cause scripts and other modifiers do not change the original fcurves.

notes
- it is all about a very bad fcurve implementation imho, and I say that cause of the way other sofware do it, where the fcurve would be updated by the respective modifications. this is another topic and hope to change during deps graph refactor

- the actual wheel rotation/distance traveled/look ahead are tricks based on so called velocity [that is actually the vector distance frame(n) - frame(n-1)], possible where there is an fcurve.

**Comment by JacquesLucke** [comment]
the examples are great, thank you

Ok, as I said I don't have time to work on that this week, but I will clean it up a bit, so that the clutter disappears :)

**Comment by og76** [comment]
Thank you, no rush. I don't know what clutter are you talking about anyway ;)
