### ISSUE TITLE
Blender crashes/closes unsuspectingly using Text object output node

### ISSUE THREAD

**Issue by Raster556** [JacquesLucke/animation_nodes#1180]
My render keeps crashing at the same point when using animation nodes. What I could figure out is that the Text Object Output node is causing the problems only in renders. In the viewport it is totally fine.
![Capture](https://user-images.githubusercontent.com/48934509/64477241-d740f400-d15e-11e9-899d-0220a4a984fc.PNG)

I have no idea why this happens and I get no errors. Just the blender application closing unsuspectingly.

**Comment by Raster556** [comment]
It happens when using text object output

**Comment by OmarSquircleArt** [comment]
Unfortunately, this is a known issue with Blender. We are waiting for Blender to fix this upstream.

**Comment by OmarEmaraDev** [comment]
Lets continue this discussion in issue #1200.
