### ISSUE TITLE
AN 2.8 - Crashes when instantiating empty

### ISSUE THREAD

**Issue by julianusx** [JacquesLucke/animation_nodes#1182]
Blender 2.80.75, AN 2.1.4
To reproduce:
Open new file in blender.
Add empty object.
Open Animation Nodes
Add Object Input, select Empty
Add Object Instancer. Connect Object Input
Set count to 1
Crash

**Comment by OmarSquircleArt** [comment]
I can't replicate this issue, can you attach the crash report?

**Comment by julianusx** [comment]
I missed one step. Enable Copy Full Object
Log attached.
I also attached sample blender file, set count to 1 and it crashes
[blender_debug_output.txt](https://github.com/JacquesLucke/animation_nodes/files/3587869/blender_debug_output.txt)

[blender-crash.zip](https://github.com/JacquesLucke/animation_nodes/files/3587870/blender-crash.zip)

**Comment by OmarSquircleArt** [comment]
I see, thanks for the report! This was caused by a bug in Blender which was reported in T67857. But we also added a mitigation in 1a3edda, so updating Animation Nodes should fix the issue.
