### ISSUE TITLE
I can not install animation nodes

### ISSUE THREAD

**Issue by OliwerTwist** [JacquesLucke/animation_nodes#1185]
![Снимок](https://user-images.githubusercontent.com/54227534/64934602-9ab27e00-d86b-11e9-8da7-3d54e6a5cf13.PNG)
vb

Python 3.7.4
Blender 2.8
Windows 10

**Comment by OliwerTwist** [comment]
I installed python version 3.5.3

**Comment by 3DSinghVFX** [comment]
You are using the old build. Please try the latest build of Animation Nodes, you can download the build from here: https://blender.community/c/graphicall/Xdbbbc/

**Comment by OmarEmaraDev** [comment]
@OliwerTwist Did the issues you were having get resolved?

**Comment by OliwerTwist** [comment]
yes thanks for asking

вс, 6 окт. 2019 г., 19:32 Omar Emara <notifications@github.com>:
