### ISSUE TITLE
Possible insight into the particle rotations issue

### ISSUE THREAD

**Issue by scorpion451** [JacquesLucke/animation_nodes#1187]
Not really this is the optimal place to share this info, honestly, but it seems like the sort of thing worth sharing somewhere, and I think it's probably relevant to being able to reinstate a functional version of the particle rotation output for the particle info node:

When using the very helpful information here from Omar Ahmad to access the particle rotation: https://blender.stackexchange.com/questions/106848/blender-animation-nodes-particle-information/106875#106875

I discovered something odd about the quaternions it returns- the elements seem to be scrambled compared to the normal order. That is, they're listed [z, w, x, y] rather than [w, x, y, z]. I'm kind of baffled why anyone would code it like that, but needless to say swapping the plugs around using a seperate quat/combine quat so things are in the right order made a huge difference.

I'm partly wondering if this was the "unreliable" aspect of the rotation info cited as the reason for removal? I know it took me forever to realize this is what was going on- it's such a bizarre issue that I assumed it was some odd gimble-locking or update lag issue before I really looked at the numbers in the viewer. I could easily see it being passed off as normal blender weirdness before anyone ever considered that the API might neglect to mention it had the coordinates in an absurd order.

**Comment by OmarSquircleArt** [comment]
Thanks for pointing this out! I will investigate this and get back to you.

**Comment by OmarEmaraDev** [comment]
From my experiments, it seems the correct quaternion is :

```
(x, y, z, w) * (sqrt(2)/2, 0, 0, -sqrt(2)/2)
```

So I think we can reimplement the rotation output using this equation.

**Comment by OmarEmaraDev** [comment]
Implemented in 26e15e5, thanks for your help!
