### ISSUE TITLE
Attach AN tree to an object for Linking / Appending

### ISSUE THREAD

**Issue by mahesh0806** [JacquesLucke/animation_nodes#1189]
Can we attach the Animation nodes tree to an object or collection, So that when linking or appending the collection, the AN tree will also be included with it?

**Comment by 3DSinghVFX** [comment]
Hi :)
In the present version of AN, we can't attach an AN-tree to an object. Second thing is, as far I know, there is no option/feature in the blender to make a collection for Node-Trees of any kind.

**Comment by OmarEmaraDev** [comment]
Unfortunately, linking support for Animation Nodes will not be considered for technical difficulties. Your other suggestion is similar to #1178, and we can track it there.
