### ISSUE TITLE
Type Corrected info message in script node

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1190]
I'm doing some testing with Animation Nodes and the script node and I'm not sure how to get rid of the text circled in blue that says **zlist-type Corrected, ylist-Type Corrected, and xlist-type corrected** 
see section circled in blue in the gif.

Here's whats in the python script node.

```
import math

xlist = [math.cos(x) * math.exp( - x**2/1000) for x in range(0,length)]
ylist = [math.sin(x) * math.exp( - x**2/1000) for x in range(0,length)]
zlist = [ x/4 for x in range(0,length)]


```

![type_corrected](https://user-images.githubusercontent.com/28985314/65433459-0d32d900-ddeb-11e9-87e6-95dc0b53d599.png)

![Type_corrected-2019-09-23_09-55-19](https://user-images.githubusercontent.com/28985314/65433471-13c15080-ddeb-11e9-8349-bbdc54df487a.gif)

I'm using Animation Nodes 2.1.4 running Ubuntu 18.04 64bit Linux

**Comment by 3DSinghVFX** [comment]
@stillpointx There is an option in N-panel of Script Node to hide "Correct Output Types" :)
![an_script_test](https://user-images.githubusercontent.com/30294746/65439825-662f5b00-de45-11e9-8c87-76e66f36a9af.png)

**Comment by stillpointx** [comment]
Thanks for the quick reply what type / how can I change it in the python script for this message not to pop up if enabled?

**Comment by OmarEmaraDev** [comment]
Animation Nodes have its own list structures. For instance, float lists are actually `DoubleList` objects. Animation Nodes can automatically convert a scalar list to a `DoubleList`, which is what is happening in this case.

Alternatively, you may create the `DoubleList` directly in the script. There are many ways to do so.

- You may use the `fromValues` method to create the object from a list of values:
```python
DoubleList.fromValues(math.cos(x) * math.exp( - x**2/1000) for x in range(0,length))
```
- You may preallocate the list and fill it:
```python
xList = DoubleList(length)
for i in range(length):
    xList[i] = math.cos(i) * math.exp( - i**2/1000)
```
- You may use numpy:
```python
import numpy
t = numpy.linspace(0, length, length)
xList = DoubleList.fromNumpyArray(numpy.cos(t) * numpy.exp( - t**2/1000))
```

Notice that `DoubleList` is imported by default, so it needn't be imported.

**Comment by stillpointx** [comment]
Thanks!!
