### ISSUE TITLE
AN2.1.2 Mesh /Mesh generators not rendering in 3d viewport

### ISSUE THREAD

**Issue by starzar** [JacquesLucke/animation_nodes#1192]
(2.79bBlender/ An2.1.2 /Windows10-64/Py35)
Mesh/Mesh Generators are not rendering in the 3d viewport.
Also on connecting the mesh generator  nodes to the 3d viewer , the option to edit the size/material does not pop up .  

However ,object do get generated.

![KritaTemplate](https://user-images.githubusercontent.com/38550930/65615457-fea91500-dfd6-11e9-8aec-0fb44bc6ca1c.jpg)

**Comment by OmarEmaraDev** [comment]
The 3D Viewer node doesn't have the ability to show Meshs, only vectors and matrices.
