### ISSUE TITLE
Unable to install AN on MacBookPro Blender 2.81

### ISSUE THREAD

**Issue by GrahamWilkins** [JacquesLucke/animation_nodes#1193]
I'
![SCREEN SHOT](https://user-images.githubusercontent.com/40180953/65768350-ab46dc00-e128-11e9-95fb-a930c8fcfaf1.jpg)
m trying to load AN into Blender 2.79 - 2.8 and/or 2.81 but it fails each time. It appears to load but when I try to activate it I get an error message suggesting I have previous versions that must be deleted.

I have cleared any previous versions to no avail using the option provided, an error message suggests the file path of these undeleted animation nodes .../Library/Application Support/Blender/2.81/, but no such file exist on my MacBookPro. I cannot find any solution that I understand on-line

**Comment by OmarEmaraDev** [comment]
There are three places in which addons can be installed in your system. Please identify those path and try to remove the `animation_node` folder from there.

**Comment by GrahamWilkins** [comment]
I cannot identify the path???

**Comment by GrahamWilkins** [comment]
I have identified the path Index of file:///Users/xxxxxxxxxx/Library/Application Support/Blender/2.81/scripts/addons/animation_nodes-master/ but the path does not exist beyond file:///Users/xxxxxxxxxx/Library/Application Support/

**Comment by GrahamWilkins** [comment]
Closed this in error ... I have identified the path Index of file:///Users/xxxxxxxxxx/Library/Application Support/Blender/2.81/scripts/addons/animation_nodes-master/ but when I try to find the actual path file:///Users/xxxxxxxxxx/Library/Application Support/ it does not exist beyond Support?

**Comment by GrahamWilkins** [comment]
I finally discovered the file, now trying to recreate the project I was working on before I came to a grinding halt. I may be back soon!
