### ISSUE TITLE
Does AN 2.1.4 have a way to decimate geometry?

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1194]
I have a blend file which animates the growth of a Lorenz Attractor it's about 3 million vertices when the animation reaches the end.

The points / animation is created from an equation / python script.  At each frame the vertices grow.  Is there a way to decimate the vertices in Animation Nodes or does anyone know of another way to prevent the vertices from growing so much / lessen them during the animation? 

https://github.com/JacquesLucke/animation_nodes/files/3650323/an_script_strange_attractors_marble.blend.zip

**Comment by OmarEmaraDev** [comment]
Can you please make a simplified file for us to look at? Also, I think such questions are better suited for [blender.stackexchange.com](blender.stackexchange.com),

**Comment by stillpointx** [comment]
Thanks.  I deleted what I could from the file and posted the question to blender.stackexchange.com
