### ISSUE TITLE
Crash - rendering curves from animated vertices using loop of animation node.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1196]
Hi, i am a newbie in AN.

In short:
I am using animated vertices to generate curves. As the vertices come from instances of object and "object mesh data" node seems not accepting lists of object, I use a loop to do such kind of work.
If I preview the work, with auto-execution turned on, everything works fine. If I were to render it however, blender will crash.

**My experiments and failure**:
1. Baking keyframe will not work in this case, because it doesn't bake the generation of different curves across frames. I have to turn the animation node on and ask program to calculate everything each frame.
2. "Set keyframe" does not work, because the curve is always generated with location values being "X-0, Y-0, Z-0". The same as scale value so they are useless.
3. "Cache once per frame" in loop generates a static curve eventually - this is the part that I don't really understand why, but it just doesn't work in this case. Other options shows either static curve or not caching (These are almost expected though.)
4. Initially all works are done in 2.80 and AN 2.1. Before posting, I have tried the newest built of blender 2.81 (updated Sep 29th). Surprisingly, it actually got rendered out several frames with animation. But soon it crashes.

So the question is, **is there way to successfully render such kind of scene?**, with curves generated from moving vertices without crashing system? I hope there is a solution as good as "baking keyframes" or so.

**The attached file is a simplified model** of my problem. In this model, several curves have been created from >=2 empties. (Note: in my real case, curves are created from object mesh data and objects are instanced). Caution, my final result possibly need to use a loop.
If you are able to successfully render the animation please try to add up amount of empties to see whether it still works?
[https://drive.google.com/file/d/1aTBmUVG0LyIuZp0ylu5XqhnJTzNoo433/view?usp=sharing](url)

Also a note, to calculate AN at each frame, it takes less than 1 ms. Although this still doesn't prevent crash at all.
Finally, about my laptop:
Win-10. x64
Blender Ver. 2.80 (& 2.81-ff10ff782bde)
AN Ver. 2.1
CPU- i7 6700HQ, 2.6-3.2 GHz.
RAM 16 GB.

GPU:
intel 
Navidia GTX970M (3 GB Virtual memory)

**Comment by OmarEmaraDev** [comment]
Hi Gerstmann,

Unfortunately, this bug is caused by Blender itself, so we haven't found a solution to this yet. See #1009 for possible workarounds. Also, can you try rendering from the console?

**Comment by Gerstmann-Bradley** [comment]
> Hi Gerstmann,
> 
> Unfortunately, this bug is caused by Blender itself, so we haven't found a solution to this yet. See #1009 for possible workarounds. Also, can you try rendering from the console?

Yes! I have tried it! It works really well! Holly Thanks Omar for suggestion and Thanks VideoBombala for making the script!

**Comment by OmarEmaraDev** [comment]
Lets continue this discussion in issue #1200.
