### ISSUE TITLE
Unable to Enable animation node addon in Ubuntu 18.10

### ISSUE THREAD

**Issue by mass9** [JacquesLucke/animation_nodes#1197]
Getting this error!

![Screenshot from 2019-10-01 17-01-31](https://user-images.githubusercontent.com/30389597/65958683-98584280-e46d-11e9-9100-d32de7a3ce03.png)

Downloaded AN zip for the first time. Blender version:2.80 
Python version 3.7

**Comment by thankjura** [comment]
remove previous installation and will download AN v2.1.4 from releases page

**Comment by mass9** [comment]
![Screenshot from 2019-10-01 18-08-00](https://user-images.githubusercontent.com/30389597/65962545-8fb83a00-e476-11e9-8fe1-b28bd3535ee4.png)
![Screenshot from 2019-10-01 18-08-12](https://user-images.githubusercontent.com/30389597/65962559-9777de80-e476-11e9-856a-3ad1ab164099.png)

**Comment by OmarEmaraDev** [comment]
Which build of Animation Nodes is this?

**Comment by mass9** [comment]
Downloaded from this website
https://blender.community/c/graphicall/Wdbbbc/

**Comment by 3DSinghVFX** [comment]
@mass9 Please remove the old (any) existing Animation Nodes files from the addon folder `/Usrname/.config/blender2.80/script/addons/`and then install new Animation Nodes https://blender.community/c/graphicall/Wdbbbc/

**Comment by mass9** [comment]
7th download start's working. I don't know what happen.

Thank You everyone
