### ISSUE TITLE
do not work animation

### ISSUE THREAD

**Issue by 1modeller1** [JacquesLucke/animation_nodes#1198]
![Screenshot from 2019-10-01 20-59-29](https://user-images.githubusercontent.com/56038776/65979621-06f9c800-e48f-11e9-80b8-cdab5cbd7330.png)

(Ubuntu)

**Comment by Clockmender** [comment]
So - are you running the animation? I guess not as nothing is happening. try pressing "Play" in Timeline and see what happens, since you are using Time Info, you **must** run animation.

**Comment by 1modeller1** [comment]
Yes, I press play, but it do not work.

**Comment by OmarEmaraDev** [comment]
Which build of Animation Nodes are you using?

**Comment by 1modeller1** [comment]
![Screenshot from 2019-10-01 21-25-23](https://user-images.githubusercontent.com/56038776/65981286-365e0400-e492-11e9-8d18-5f4d386d562b.png)

**Comment by OmarEmaraDev** [comment]
This is an outdated build of Animation Nodes, please uninstall this build and install a more recent one.

**Comment by 1modeller1** [comment]
Please, can you give me more recent one version?

**Comment by Gerstmann-Bradley** [comment]
> Please, can you give me more recent one version?

I suppose here you are, it is 2.1.4.
https://blender.community/c/graphicall/ffbbbc/

Also your socket seems abnormal. you can try to relink them. The location should disappear instead of showing 000. this is equally true to object socket. I think these linkages are broken in the tree and that's why it's not working.

**Comment by 3DSinghVFX** [comment]
> Please, can you give me more recent one version?

Here is the link for the recent version of Animation Nodes for Blender 2.8x for Linux OS: https://blender.community/c/graphicall/Wdbbbc/

**Comment by OmarEmaraDev** [comment]
@1modeller1 Can you report back, did your issue get resolved?

**Comment by 1modeller1** [comment]
I downland Animation Nodes on link that you give me, but it don't work.
![Screenshot from 2019-10-05 17-22-30](https://user-images.githubusercontent.com/56038776/66254834-4842ee00-e795-11e9-911a-2f40e8d06480.png)

**Comment by 1modeller1** [comment]
I downland Animation Nodes on link that you give me, but it do not work.
![Screenshot from 2019-10-05 17-31-16](https://user-images.githubusercontent.com/56038776/66254876-0d8d8580-e796-11e9-8c7c-7d840b619967.png)
![Screenshot from 2019-10-05 17-22-30](https://user-images.githubusercontent.com/56038776/66254877-0fefdf80-e796-11e9-9cfd-fdc1d6218498.png)

**Comment by 3DSinghVFX** [comment]
@1modeller1 Please remove the existing version of Animation Nodes and also old files if present in the addons folder.

**Comment by 1modeller1** [comment]
Thank you! it work normal
