### ISSUE TITLE
Possible to instancing objects on specific vertices of an object?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1199]
Hi, once I thought I would post this question in stack exchange, but as I think this question is highly relevant to AN, I decide to post it here? If I want to instance objects on specific vertices of another object, I need its vertex location and length.
Normally, beyond AN, I will think to set a vertex group to do such kind of work, but I find I may not succeed in this case. Basically all related nodes are outputing "weight/color". No vectors can be output, and the list length will be as long as the whole list. It's ok to use weight to multiply original vectors, to leave only selected vectors at original position and unselected-vertices at 0,0,0.. But I don't know the next step to eliminate these unselected vertices from the list. 

Potentially we can do "if else"-like scripting in AN, but I am not familiar with this area at all so I will probably just leave the question here. If you have any insight inn this question, please teach me. Thanks.
Currently I will be satisfied with "full-or-none" results, meaning the detailed weight painting don't need to be considered in my case.

**Comment by OmarEmaraDev** [comment]
It seems you are just looking for the *Mask List* node, see the following example:

![Example](https://user-images.githubusercontent.com/25300994/66252356-fa10f900-e75a-11e9-818b-65f7bbe4e99b.png)
