### ISSUE TITLE
animation nodes again do not work

### ISSUE THREAD

**Issue by 1modeller1** [JacquesLucke/animation_nodes#1202]
![Screenshot from 2019-10-08 16-52-25](https://user-images.githubusercontent.com/56038776/66393734-bc2b0380-e9ec-11e9-85d7-6543d67010aa.png)
![Screenshot from 2019-10-08 16-52-18](https://user-images.githubusercontent.com/56038776/66393739-bd5c3080-e9ec-11e9-9237-3efb02849ba2.png)

**Comment by OmarEmaraDev** [comment]
What Blender and Animation Nodes builds are you using?

**Comment by 1modeller1** [comment]
Blender 2.80.75
Animation nodes 2.1.4 for Linux

**Comment by OmarEmaraDev** [comment]
@1modeller1 Where did you get your Animation Nodes build?

**Comment by 1modeller1** [comment]
I downloaded it here 
![Screenshot from 2019-10-10 15-57-36](https://user-images.githubusercontent.com/56038776/66563448-38515280-eb77-11e9-861b-d7c539ead8fb.png)

**Comment by 3DSinghVFX** [comment]
@1modeller1 I have tested this AN build and it is working fine on my pc which Ubuntu 16.04 LTS, 
![screen](https://user-images.githubusercontent.com/30294746/66567384-b7995300-eb84-11e9-9227-ec45eef4548b.png)

**Comment by 1modeller1** [comment]
Yes, first it worked good, but when I experimented with node "list create object" this addon broken.

**Comment by 3DSinghVFX** [comment]
@1modeller1 Create Object List and Combine Object Lists Nodes are working on mine pc. Can you try again with a new download file? It may be the downloaded file was broken.  

![screen](https://user-images.githubusercontent.com/30294746/66581995-b117d500-eb9e-11e9-8141-dc0efcd04672.png)

**Comment by 3DSinghVFX** [comment]
I have updated the AN build today. Can you try the newest build? Please let us know whether it is working or not :)

**Comment by 1modeller1** [comment]
Add-on install but when I make some nodes it don't and if I turn off and turn on add-on it shows error that it show before. Sorry that I didn't say, before your update it was also.

**Comment by 3DSinghVFX** [comment]
@1modeller1 Does this also happen on Blender 2.81?

Please run the Blender from the terminal and use the AN. Upload a screenshot of the terminal which may help us to understand the problem.

**Comment by 1modeller1** [comment]
[video with error.zip](https://github.com/JacquesLucke/animation_nodes/files/3723160/video.with.error.zip)

**Comment by 3DSinghVFX** [comment]
@1modeller1 I have tested the latest AN build many times on blender 2.80 and 2.81(_on Ubuntu 16.04 LTS_), it is working fine without any error. Sorry, I have no idea why are you getting that error message while re-enabling the addon.

@OmarEmaraDev Please look at this issue.

**Comment by OmarEmaraDev** [comment]
Unfortunately, I can't reproduce the error and don't exactly know what is causing it.

**Comment by OmarEmaraDev** [comment]
@1modeller1 Can you please disable all other addons and try Animation Nodes again?

**Comment by 1modeller1** [comment]
Thank you for help. Sorry, it don not work because I made one mistake, but now all work good.
