### ISSUE TITLE
 Saving Sound Spectrum Node crashes AN 2.1.4/2.1.5 in Blender 2.80.75

### ISSUE THREAD

**Issue by baudouin-hub** [JacquesLucke/animation_nodes#1207]
I'm running Windows 10 64bit and Blender 2.80.75, trying to install 2.1.5 but i'm getting the following error. Tried installing on 2.81, same story. Manually deleted old AN installation directories etc. 
![Screenshot_3](https://user-images.githubusercontent.com/56549778/66869527-e9a11f80-ef9f-11e9-8d9a-8d0907d04536.png)

**Comment by baudouin-hub** [comment]
I tried installing 2.1.5 because I was trying to set up a small sound reaction system, which works up until the point to where I save the file. As soon as I save I get a general execution error that remains until I reboot Blender a couple of times. 
![Screenshot_4](https://user-images.githubusercontent.com/56549778/66869810-7055fc80-efa0-11e9-96f3-63628e6d7997.png)

**Comment by OmarEmaraDev** [comment]
Thanks for the report! We will look into it.

**Comment by baudouin-hub** [comment]
Little update: so I managed to get 2.1.5 running: https://blender.community/c/graphicall/ffbbbc/ < that version. But the problem I have with the sound nodes remain. It all works fine up until the point where I save the setup. 

Read prefs: C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'object_fracture_crack'
cmolcore not working
Warning: class FSPY_BLENDER_OT_import_project contains a property which should be an annotation!
C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\fspy_blender\__init__.py:50
    assign as a type annotation: FSPY_BLENDER_OT_import_project.filter_glob
    assign as a type annotation: FSPY_BLENDER_OT_import_project.update_existing_camera
    assign as a type annotation: FSPY_BLENDER_OT_import_project.import_background_image
register_class(...):
Warning: 'FontSelectorPanel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'FontUIList' doesn't contain '_UL_' with prefix & suffix
register_class(...):
Warning: 'object.custom_menu' doesn't contain '_MT_' with prefix & suffix
register_class(...):
Warning: 'object.custom_panel' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'object.bygenmodify' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'object.bygentools' doesn't contain '_PT_' with prefix & suffix
mb_lab updater verbose is enabled
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_install_popup'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_install_popup'>
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_check_now'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_check_now'>
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_update_now'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_update_now'>
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_update_target'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_update_target'>
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_install_manually'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_install_manually'>
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_updated_successful'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_updated_successful'>
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_restore_backup'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_restore_backup'>
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_ignore'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_ignore'>
cls BA: <class 'MB-Lab-master.addon_updater_ops.addon_updater_end_background'>
cls: <class 'MB-Lab-master.addon_updater_ops.addon_updater_end_background'>
mb_lab Updater: Read in json settings from file
Tissue: Numba not installed
Warning: class BlenderOsmPreferences contains a property which should be an annotation!
C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-osm\__init__.py:527
    assign as a type annotation: BlenderOsmPreferences.dataDir
    assign as a type annotation: BlenderOsmPreferences.assetsDir
    assign as a type annotation: BlenderOsmPreferences.mapboxAccessToken
    assign as a type annotation: BlenderOsmPreferences.osmServer
Warning: class BlosmDefaultLevelsEntry contains a property which should be an annotation!
C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-osm\gui\__init__.py:779
    assign as a type annotation: BlosmDefaultLevelsEntry.levels
    assign as a type annotation: BlosmDefaultLevelsEntry.weight
register_class(...):
Warning: 'PanelBlosmExtent' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'PanelBlosmSettings' doesn't contain '_PT_' with prefix & suffix
register_class(...):
Warning: 'PanelBlosmBpyProj' doesn't contain '_PT_' with prefix & suffix
Warning: class BlenderOsmProperties contains a property which should be an annotation!
C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-osm\gui\__init__.py:779
    assign as a type annotation: BlenderOsmProperties.terrainObject
    assign as a type annotation: BlenderOsmProperties.osmSource
    assign as a type annotation: BlenderOsmProperties.osmFilepath
    assign as a type annotation: BlenderOsmProperties.dataType
    assign as a type annotation: BlenderOsmProperties.mode
    assign as a type annotation: BlenderOsmProperties.minLat
    assign as a type annotation: BlenderOsmProperties.maxLat
    assign as a type annotation: BlenderOsmProperties.minLon
    assign as a type annotation: BlenderOsmProperties.maxLon
    assign as a type annotation: BlenderOsmProperties.coordinatesAsFilter
    assign as a type annotation: BlenderOsmProperties.buildings
    assign as a type annotation: BlenderOsmProperties.water
    assign as a type annotation: BlenderOsmProperties.forests
    assign as a type annotation: BlenderOsmProperties.vegetation
    assign as a type annotation: BlenderOsmProperties.highways
    assign as a type annotation: BlenderOsmProperties.railways
    assign as a type annotation: BlenderOsmProperties.defaultRoofShape
    assign as a type annotation: BlenderOsmProperties.singleObject
    assign as a type annotation: BlenderOsmProperties.ignoreGeoreferencing
    assign as a type annotation: BlenderOsmProperties.levelHeight
    assign as a type annotation: BlenderOsmProperties.defaultLevels
    assign as a type annotation: BlenderOsmProperties.defaultLevelsIndex
    assign as a type annotation: BlenderOsmProperties.straightAngleThreshold
    assign as a type annotation: BlenderOsmProperties.loadMissingMembers
    assign as a type annotation: BlenderOsmProperties.subdivide
    assign as a type annotation: BlenderOsmProperties.subdivisionSize
    assign as a type annotation: BlenderOsmProperties.terrainResolution
    assign as a type annotation: BlenderOsmProperties.terrainPrimitiveType
    assign as a type annotation: BlenderOsmProperties.overlayType
    assign as a type annotation: BlenderOsmProperties.overlayUrl
    assign as a type annotation: BlenderOsmProperties.setOverlayMaterial
    assign as a type annotation: BlenderOsmProperties.setupScript
    assign as a type annotation: BlenderOsmProperties.assetsDir
    assign as a type annotation: BlenderOsmProperties.treeDensity
    assign as a type annotation: BlenderOsmProperties.makeRealisticLayer
    assign as a type annotation: BlenderOsmProperties.litWindows
    assign as a type annotation: BlenderOsmProperties.materialType
    assign as a type annotation: BlenderOsmProperties.blenderMaterials
    assign as a type annotation: BlenderOsmProperties.wallTexture
    assign as a type annotation: BlenderOsmProperties.listOfTextures
    assign as a type annotation: BlenderOsmProperties.materialScript
register_class(...):
Warning: 'Properties_meshinfo' doesn't contain '_PT_' with prefix & suffix
Registered Animation Nodes
Font Selector --- Font Folders Up to Date
Font Selector --- Settings Loaded
Read blend: D:\000. PROJECTEN\001. PERSONAL PROJECTS\001. MUTE\Mute 26\persons sound.blend
Font Selector --- Font Folders Up to Date
Font Selector --- Settings Loaded






Traceback (most recent call last):
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\units.py", line 58, in setupExecutionUnits
    unit.setup()
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 26, in setup
    exec(self.setupCodeObject, self.executionData, self.executionData)
  File "setup: 'NodeTree'", line 20, in <module>
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\sockets\sound.py", line 42, in getValue
    soundSequence = SoundSequence.fromSequence(sequence)
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 26, in fromSequence
    soundData = getCachedSoundDataFromSound(sequence.sound)
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 39, in getCachedSoundDataFromSound
    return getSoundData(sound.factory)
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\data_structures\sounds\sound_sequence.py", line 42, in getSoundData
    if sound.specs[0] == sampleRate:
AttributeError: 'NoneType' object has no attribute 'specs'
Traceback (most recent call last):
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\utils\handlers.py", line 44, in always
    handler()
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\events.py", line 36, in sceneUpdated
    evaluateRaisedEvents()
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\events.py", line 44, in evaluateRaisedEvents
    event_handler.update(event.getActives())
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\utils\recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\event_handler.py", line 23, in update
    executeNodeTrees(nodeTrees)
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\auto_execution.py", line 15, in executeNodeTrees
    nodeTree.autoExecute()
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\base_types\node_tree.py", line 87, in autoExecute
    self._execute()
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\base_types\node_tree.py", line 105, in _execute
    success = unit.execute()
  File "C:\Users\Lenovo T460s\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes.problems.ExecutionUnitNotSetup

**Comment by OmarEmaraDev** [comment]
@baudouin-hub Are your sounds packed in the blend file or read from a file on disk?

**Comment by baudouin-hub** [comment]
Not exactly sure if I do one or the other. The MP3 is loaded from a file on disk within the sound spectrum node. This way it is also saved into a blend file. Seems like it is in this file since it is larger then a usual blend file. I stripped away all the other nodes and experimented with just the sound spectrum node and I can confirm that the problem is there, not in the further setup of nodes.

**Comment by OmarEmaraDev** [comment]
Ok. I just replicated the issue. It seems it happens when the sounds are packed. The AUD sound object is none when the sound is packed, seems to be a Blender bug.

**Comment by OmarEmaraDev** [comment]
Fixed in e48ac04.

**Comment by baudouin-hub** [comment]
Thanks!

**Comment by OmarEmaraDev** [comment]
@baudouin-hub The original error you reported can be fixed by installing `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).
