### ISSUE TITLE
Time Info -> Frame Rate is rounded

### ISSUE THREAD

**Issue by chconnor** [JacquesLucke/animation_nodes#1209]
In e.g. a 29.97 fps project, the Time Info node "Frame Rate" is rounded, making it impossible to use for accurate calculations:

[http://lacinato.com/pub/blender/AN_fps_bug.png
](http://lacinato.com/pub/blender/AN_fps_bug.png
)

**Comment by OmarEmaraDev** [comment]
Thanks for the report! Fixed in 35c16fd.

**Comment by chconnor** [comment]
Brilliant, thanks!
