### ISSUE TITLE
Curve node: Why the result turns black?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#121]
http://www.pasteall.org/blend/35879
After using smooth node, the final object turns black. Why?

**Comment by JacquesLucke** [comment]
the file doesn't crash here. Or which material panel do you mean?

btw. you have to use recalculate the normals before making the object smooth. There is a node for that

**Comment by JacquesLucke** [comment]
this has nothing to do with the curve nodes

**Comment by LeonCheung** [comment]
Sorry Jacques, I just found it happens to my f553aba blender build, not just for this node set up...

**Comment by LeonCheung** [comment]
But I still wonder why it turns black

**Comment by JacquesLucke** [comment]
![recalc normals](https://cloud.githubusercontent.com/assets/5881326/7445914/d67acefa-f1c6-11e4-9838-8fa555af99fb.PNG)

**Comment by LeonCheung** [comment]
Ah I see! I'm a bit stupid this time...  :P

**Comment by LeonCheung** [comment]
btw, I noticed that the value setting can be set to negative value, which makes no sense, maybe it's better to limit that?

**Comment by JacquesLucke** [comment]
which value?

**Comment by LeonCheung** [comment]
All resolution values for all curve nodes.

**Comment by JacquesLucke** [comment]
ah yees, I can do this maybe, but shouldn't be such a big deal

**Comment by LeonCheung** [comment]
I thought it can be useful when setting values by dragging left and right. just found it appears very easy to make it negative in this way.

**Comment by LeonCheung** [comment]
SInce you've already answer the initial "why black" question, I think it can be closed. Thanks.
