### ISSUE TITLE
Proposal: add a matrix math node the divide method  ( solving rotate with ralative object )

### ISSUE THREAD

**Issue by cxdcxdcxd198** [JacquesLucke/animation_nodes#1210]
it could get a ralative matrix of two matices
![screen](https://user-images.githubusercontent.com/51414955/67155870-7bff4580-f349-11e9-9f92-bd5b210bedaa.JPG)

**Comment by OmarEmaraDev** [comment]
Could you elaborate a bit on why this is useful?

**Comment by cxdcxdcxd198** [comment]
![screen2](https://user-images.githubusercontent.com/51414955/67158397-21c2ac80-f36a-11e9-9962-6ba6ab74d7d7.JPG)

**Comment by OmarEmaraDev** [comment]
Ok, I suppose we can add an operator for that. Thanks for the suggestion.

**Comment by cxdcxdcxd198** [comment]
[test files blender 2.81.15 AN 2.1.5.zip](https://github.com/JacquesLucke/animation_nodes/files/3747879/test.files.blender.2.81.15.AN.2.1.5.zip)
Just add my test file   :)
