### ISSUE TITLE
Sound from Sequences / Sound Spectrum unable to get data or loses sync from edited sounds on VSE timeline

### ISSUE THREAD

**Issue by krupax** [JacquesLucke/animation_nodes#1212]
I've been using AN for a good while on some productions where we use speech audio to drive animation and have just migrated to 2.8 and thus the new 2.1.x (initially v14 but today updated to v15 to see if it helped - it didn't)

What I'm seeing is that it works really well with the new live / realtime sound spectrum node but doesn't seem to allow easy editing of the audio channel in the same way the previous version did...

If I just let a single audio stream run, even if I move it on the timeline, it stays in sync all the way through but if I make a cut and the leave a gap, odd things happen - sometimes there's no signal at all, but mostly there is but it seems to lose sync. 

I've made up a small 
[sound nodes demo.zip](https://github.com/JacquesLucke/animation_nodes/files/3772051/sound.nodes.demo.zip)
file (attached) and I hope I've managed to pack the audio correctly to demonstrate this phenomenon...

cheers

Chris

**Comment by OmarEmaraDev** [comment]
Fixed in 8a12992. New builds should be up in couple of minutes.

Thanks for the report!

**Comment by krupax** [comment]
Woa, that was fast, didn't think you'd even get to looking at it today!

I'll finish this section of animation and then try it out, if not today then hopefully over the weekend :)

cheers!

Chris

**Comment by krupax** [comment]
Just looking at checking this fix - do I download the latest build or simply replace the two changed files?

cheers,

Chris

**Comment by OmarEmaraDev** [comment]
Both approaches should work, so do what you think is best.

**Comment by krupax** [comment]
Ah cool, I'll try just the changed files and see :)

cheers!

**Comment by krupax** [comment]
Just tried it - replaced the two changed files and works a treat!

Many thanks Omar :D
