### ISSUE TITLE
Missing 'Type' option in 'Object Matrix Output'

### ISSUE THREAD

**Issue by akordowski** [JacquesLucke/animation_nodes#1213]
According to the AN [docs](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/object/matrix_output.html) the 'Object Matrix Output' should have an 'Type' option. But in AN 2.1.4 with Blender 2.80.75 it is missing.

Has it been removed or is there an other way to apply the 'Type'?
Thank you in advance!

**Docs**
<img width="166" src="https://animation-nodes-manual.readthedocs.io/en/latest/_images/matrix_output_node.png">

**AN 2.1.4 with Blender 2.80.75**
<img width="166" src="https://user-images.githubusercontent.com/9746197/67619127-181cc700-f7f8-11e9-96d9-e37213fa4877.png">

**Comment by OmarEmaraDev** [comment]
The option was moved to the *Advanced Node Setting* panel.
