### ISSUE TITLE
Can't import AN 2.1.5 into v2.80.75 on Windows 10

### ISSUE THREAD

**Issue by AksuTAMK** [JacquesLucke/animation_nodes#1214]
Hi and thank you for your continued work with this add-on.

I tried to download the latest daily, but I get the error message displayed in the image (red).
I have tried re-downloading and reinstalling both Blender and AN, but nothing seems to work.

When trying to remove the add-on I get the blue error message. I have to restart Blender to remove the add-on.

I am at a loss, and welcome any and all advice!

OS: Windows 10
Blender 2.80.75
AN 2.1.5

![blenderErrir](https://user-images.githubusercontent.com/54892958/67642522-4512cc00-f915-11e9-9e0c-508eb075de7f.JPG)

**Comment by OmarEmaraDev** [comment]
Can you try installing `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2)?

**Comment by AksuTAMK** [comment]
That did the trick!

Awesome, thank you for your help!
