### ISSUE TITLE
Blender 2.80.75 on Windows 10. How to import Animation Nodes?

### ISSUE THREAD

**Issue by khdhhde21** [JacquesLucke/animation_nodes#1215]
Hello. I wanted to try Animation Nodes with Blender 2.80.75 on Windows 10 and downloaded animation_nodes-blender2.8.zip. After importing, the add-on doesn't show in the add-ons window. Are there any additional steps to import it or should I use a different branch? Thanks!

**Comment by OmarEmaraDev** [comment]
Animation Nodes needs to compiled, so you can't just grab the source from github. You can download the latest builds from the Animation Nodes website.

https://animation-nodes.com/

**Comment by khdhhde21** [comment]
Thank you. Just tried it. I think it's the THE way to do animations in Blender!
