### ISSUE TITLE
I cannot, as hard as I try, install animation nodes

### ISSUE THREAD

**Issue by samuelbecket** [JacquesLucke/animation_nodes#1216]
I have tried every release, I can find, uninstalled and reinstalled blender - making sure to delete the userpref.blend file. I have spent the hours, gone through the forums. I don't know what I am doing wrong. Here are the error logs:

![Screenshot (62)](https://user-images.githubusercontent.com/30017535/67738728-c6359600-f9dd-11e9-9a50-8eaf13860375.png)
I got this one from the download from https://animation-nodes.com/#download

When I go to Omar Emara's release I get nothing:
![Screenshot (60)](https://user-images.githubusercontent.com/30017535/67738871-4825bf00-f9de-11e9-8210-ec49caee01eb.png)
That is the file is "installed" and when I look in the directory animtion nodes is there however I am unable to run them as I can't pull them up.

This is the error i get from the download on blender.community
![Screenshot (58)](https://user-images.githubusercontent.com/30017535/67738942-963ac280-f9de-11e9-903e-4f7ccf952b89.png)

What can I possibly do differently? Where is the one place I should be downloading this from?

**Comment by OmarEmaraDev** [comment]
Use the build from the Animation Nodes' website, but first install `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).
