### ISSUE TITLE
Animation doesn't work when linking a file.

### ISSUE THREAD

**Issue by khdhhde21** [JacquesLucke/animation_nodes#1217]
When linking a .blend file with an Animation Nodes animation, the animation doesn't show in the container file. Is this supposed to work and if not, is there a workaround? Thanks.

**Comment by OmarEmaraDev** [comment]
Not sure what you mean. Can you elaborate?

**Comment by khdhhde21** [comment]
Sorry. First, create a .blend file with an animation. Then create a new file and File>Link the first file. The model is visible, but not animated. The animation nodes tree is missing too. Try to File>Link the node tree from the first file, but that doesn't help.

**Comment by OmarEmaraDev** [comment]
I don't think there are workarounds at the moment. Your proposal seems very similar to #1189, is this what you want?

**Comment by khdhhde21** [comment]
Yes, #1189 looks right. I mostly wanted to make sure that I'm not missing something obvious. This would be nice to have, but for now I can bake keyframes. This seems to work for linking.

**Comment by OmarEmaraDev** [comment]
Alright. Lets merge this to #1189 then.
