### ISSUE TITLE
Issue with ANodes

### ISSUE THREAD

**Issue by tejasdotchavan** [JacquesLucke/animation_nodes#1218]
Hi Jacques,
AN in 2.8 is giving this error:
![image](https://user-images.githubusercontent.com/48234361/67964050-8fa88700-fc3a-11e9-8019-70d5dad34ebf.png)
Have you faced this before? I tried reinstalling blender but to no avail :(

**Comment by OmarEmaraDev** [comment]
Which Animation Nodes build are you using? Can you show us the node tree? Can you attach the output of the console?

**Comment by OmarEmaraDev** [comment]
Can you report back on this?

**Comment by tejasdotchavan** [comment]
Hi Omar, sorry for the late reply. I tried to reinstall it, but I am getting a new error now while trying to activate the add on:
![Untitled](https://user-images.githubusercontent.com/48234361/68909459-46534e00-0789-11ea-8b7f-6b00645c2a16.png)
I installed the latest version from:
https://animation-nodes.com/#download
That is AN v2.1 for Blender2.8x

**Comment by OmarEmaraDev** [comment]
Install `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).

**Comment by tejasdotchavan** [comment]
Thanks Omar, it is working now :)
