### ISSUE TITLE
Can't make work ANodes on Blender 2.8 or 2.81 on MacOS

### ISSUE THREAD

**Issue by Insaisissable** [JacquesLucke/animation_nodes#1220]
Hi,
After installing the add-on I can't make it work. I installed and uninstalled it several times but there's always the same error that pops up. Please see the image attached.
![Screenshot 2019-11-01 at 23 29 59](https://user-images.githubusercontent.com/25798181/68060506-ea0c1b00-fd00-11e9-9774-324775c62eed.png)

**Comment by OmarEmaraDev** [comment]
Please remove any version of Animation Nodes first before installing Animation Nodes, manually if you have to.

**Comment by Insaisissable** [comment]
I have to do it manually otherwise it doesn't work. Could you suggest me what to delete and where I could find those components? I'm working on MacOS Mojave v10.14.6. Thank you!

**Comment by OmarEmaraDev** [comment]
You will find a folder called `animation_nodes` in the addons directory, just delete it. I don't use MacOS, so I don't exactly know where the addons directory is, but there are multiple ones, so make sure to check all of them.

**Comment by Insaisissable** [comment]
Ok. Thanks... I did delete every installation and the add-on is still not working. This time the error is different. Please take a look to the image attached. Is there a newer version of the add on than 2.14?
![Screenshot 2019-11-02 at 11 42 42](https://user-images.githubusercontent.com/25798181/68069873-a1874880-fd66-11e9-83f2-616507926b58.png)

**Comment by OmarEmaraDev** [comment]
Yes, download the latest build from Animation Nodes' website.
https://animation-nodes.com/

**Comment by Insaisissable** [comment]
Thank you!

**Comment by Insaisissable** [comment]
I don't want to be a pain in the a... Err again. Took the latest version from the site but it doesn't seem possible to be installed.  Please take a look to the image attached.
![Screenshot 2019-11-02 at 15 36 06](https://user-images.githubusercontent.com/25798181/68072561-7b25d500-fd87-11e9-9d4c-d9928f7226e6.png)

**Comment by OmarEmaraDev** [comment]
Can you try disabling all other addons and see if it will work?

**Comment by Insaisissable** [comment]
When I disable the other add-ons A-Nodes becomes available and its box can be checked...
![Screenshot 2019-11-02 at 16 23 41](https://user-images.githubusercontent.com/25798181/68073134-369d3800-fd8d-11e9-9887-9b1edf604713.png)

**Comment by Insaisissable** [comment]
Could it be an add-on conflict?

**Comment by OmarEmaraDev** [comment]
That's what I am suspecting. Can you please check which addon is conflicting? Disable one by one and see if Animation Nodes works.

**Comment by Insaisissable** [comment]
Ok. I will try to find out. If I do, I will come back to report here. Thank you!

**Comment by Insaisissable** [comment]
These were all the add-ons that were checked before installing the AN add-on and when the error popped-up. I don't get any error for the moment. 
![Screenshot 2019-11-02 at 17 26 43](https://user-images.githubusercontent.com/25798181/68073972-22116d80-fd96-11e9-8176-713bc43ef978.png)
![Screenshot 2019-11-02 at 17 27 07](https://user-images.githubusercontent.com/25798181/68073973-22aa0400-fd96-11e9-8de5-876ebf132178.png)
![Screenshot 2019-11-02 at 17 27 34](https://user-images.githubusercontent.com/25798181/68073974-22aa0400-fd96-11e9-86ac-a2e3d43386b2.png)

**Comment by OmarEmaraDev** [comment]
So the error doesn't occur anymore even after you re-enable the addons?

**Comment by Insaisissable** [comment]
It didn't occur so far. I will keep you informed if I have an issue with it.

**Comment by OmarEmaraDev** [comment]
Ok, lets close this for now then.
