### ISSUE TITLE
Animation Nodes Blender 2.8 Macbook Pro (macOS Mojave)

### ISSUE THREAD

**Issue by AnthonyWeir** [JacquesLucke/animation_nodes#1223]
Nodes stopped working completely, nothing would input or output. Forced to restart, work now.
<img width="1680" alt="Screen Shot 2019-11-05 at 7 48 39 PM" src="https://user-images.githubusercontent.com/57422503/68258647-5e96d080-0005-11ea-8e9d-d7ee6c0d7c41.png">

**Comment by OmarEmaraDev** [comment]
Can you replicate the error again?

**Comment by RAIOvisual** [comment]
Hi!! I've got render mistakes making animation render but when I render a single frame the render its ok!
Macbook pro, Mojave, blender 2.8, AN 2.1.5
<img width="1680" alt="Captura de pantalla 2019-11-10 a las 10 16 37" src="https://user-images.githubusercontent.com/57586589/68541714-6a86e780-03a3-11ea-9433-45eb8ccb9c6d.png">

**Comment by OmarEmaraDev** [comment]
@RAIOvisual See #1200.

**Comment by RAIOvisual** [comment]
thanks for the support!!!

**Comment by RAIOvisual** [comment]
One question? Is the crash in windows too or only in MacOS?

**Comment by OmarEmaraDev** [comment]
@RAIOvisual It happens in all platforms.

**Comment by RAIOvisual** [comment]
thanks again!!

**Comment by OmarEmaraDev** [comment]
@AnthonyWeir Can you report back on this?

**Comment by AnthonyWeir** [comment]
The issue was replicated multiple times. It seemed if anything changed with a loop, like an undo, it would freeze the nodes.

**Comment by OmarEmaraDev** [comment]
@AnthonyWeir Ok, are you using the latest build from https://animation-nodes.com/?

**Comment by OmarEmaraDev** [comment]
Can you report back on this?

**Comment by AnthonyWeir** [comment]
Hey Omar, sorry for the late reply haven’t used the animation nodes in a
minute, I’ll try to check it out today or tomorrow and let you know. I
noticed it happened mainly with loops.
