### ISSUE TITLE
Object Instancer Node with large number of instances crashed the Blender 2.80/2.81

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1224]
Hi,
Enabling or Disabling the **Copy Full Object** and/or **Deep Copy** option of Object Instancer Node with 1000 (or More) instances crashes the Blender 2.80/2.81. I'm using Ubuntu 16.04 LTS. It is also happening on [Mac OS](https://blender.community/c/graphicall/phbbbc/) (see the comment by  denyskurnosov).

Crash Report:
[blender.crash.txt](https://github.com/JacquesLucke/animation_nodes/files/3812929/blender.crash.txt)

**Comment by OmarEmaraDev** [comment]
I can't replicate the issue. Seems like a blender bug, can you replicate it with a minimal script?

**Comment by 3DSinghVFX** [comment]
Yes, I have only used the Object Instancer Node and Cube object,
 
![Peek 2019-11-06 13-56](https://user-images.githubusercontent.com/30294746/68281245-3b1f6480-009d-11ea-9cd2-33019a1f7cd5.gif)

**Comment by OmarEmaraDev** [comment]
I meant, can you reproduce the problem using a minimal python script?

**Comment by 3DSinghVFX** [comment]
Yes, I have only used the Object Instancer Node and Cube object,
 
![Peek 2019-11-06 13-56](https://user-images.githubusercontent.com/30294746/68281245-3b1f6480-009d-11ea-9cd2-33019a1f7cd5.gif)

**Comment by 3DSinghVFX** [comment]
Blender does not crash with a script:

![screen](https://user-images.githubusercontent.com/30294746/68284411-7c1a7780-00a3-11ea-8db9-172d93b3e5f4.png)

**Comment by Fake-User** [comment]
I am having the same issue here on both mac and win with the object instancer

**Comment by Fake-User** [comment]
My above issue turned out to be the same as #1200

**Comment by OmarEmaraDev** [comment]
Can you test this again? We refactored the Instancer node, so maybe this no longer happens.
