### ISSUE TITLE
Get the actual location an object with consraints?

### ISSUE THREAD

**Issue by khdhhde21** [JacquesLucke/animation_nodes#1227]
I have an object moving along a path using Follow Path constraint. Even though the object moves, its Location is always (0,0,0) in Item>Transform inside Blender. **Object Transforms Input** node also shows (0,0,0) in the Location output. Is there any way to get the actual global location of this object in AN? (I need it to calculate the distance between this object and the camera)

**Comment by OmarEmaraDev** [comment]
You can use the *Object Matrix Input* for those kind of cases where the *Object Transforms Input* doesn't provided up to date information. It will return a matrix, but you can simply decompose it and get the location from there.

**Comment by khdhhde21** [comment]
That works. Thank you!
