### ISSUE TITLE
Python 3.7.0

### ISSUE THREAD

**Issue by monsieur42** [JacquesLucke/animation_nodes#1228]
Hi!

I want to use the plugin width the "sculpt mode features" branch of blender but it use python 3.7.0 and when I want to activate the plugin it says Animation Nodes has been compiled for python 3.5.3

Can you help me to compile with the right version of python?

Cheers,
Miklós

**Comment by OmarEmaraDev** [comment]
Animation Nodes uses Python 3.7 by default, you are probably using an old source. Download a build from https://animation-nodes.com/ or just compile the master branch using python 3.7.

**Comment by monsieur42** [comment]
Oh sorry! Excelent, thank you very mutch.
(Than you probably want to update the link "Download the latest version here:" on the github front page. :) )

**Comment by OmarEmaraDev** [comment]
@monsieur42 Oh, thanks for noting that! We will update the README.
