### ISSUE TITLE
Getting all object's children and filtering them by name.

### ISSUE THREAD

**Issue by khdhhde21** [JacquesLucke/animation_nodes#1231]
Is it possible to get all object's children and filter them by name? This would be similar to using "Collection Info" > "Filter Object List", but for an object instead of a collection.

**Comment by OmarEmaraDev** [comment]
You can just use an expression node with the following expression:

![Node Tree](https://user-images.githubusercontent.com/25300994/68839674-d631c300-06c9-11ea-8ce8-e4673fbe13d5.png)

**Comment by khdhhde21** [comment]
Thank you. The expression node is so useful!
