### ISSUE TITLE
There is an edge that references a not existing vertex

### ISSUE THREAD

**Issue by Amonra725** [JacquesLucke/animation_nodes#1232]
I have some troubles with verticies or edges. When Im trying to pull data from sound sequence and put it on subdivided grid, grid disolves and never appears. Near the combine mesh node appears error "There is an edge that references a not existing vertex". What should I do? https://drive.google.com/open?id=1NMbjE_Dyfx9SvEjcZoCZeF4CEKVOfgi5 Screenshot
https://drive.google.com/open?id=1CshoPo96mHF1HdGSwGN9qMzPprbtjya1  Blend File

**Comment by OmarEmaraDev** [comment]
Please attach a screenshot of the whole node tree.

**Comment by Amonra725** [comment]
![GitHub2](https://user-images.githubusercontent.com/57760352/68868099-f7190900-0707-11ea-9c28-ac827ecfb80b.png)

**Comment by OmarEmaraDev** [comment]
Well, the error is exactly as you would expect. When slicing, you removed some of the vertices. To do segmentation correctly, you should do something like this:

![20191114-173051](https://user-images.githubusercontent.com/25300994/68870934-58d77400-0704-11ea-8175-dcc90cade5e1.png)

**Comment by Amonra725** [comment]
Thanks! It worked!
