### ISSUE TITLE
fail to active animation node in Blender 2.80

### ISSUE THREAD

**Issue by windwe2** [JacquesLucke/animation_nodes#1234]
![QQ图片20191116135628](https://user-images.githubusercontent.com/53392740/68988859-1be0be00-0879-11ea-9da0-6592afc67e3b.png)

When I try to active the animation node in blender 2.8, it appears this error notice. I don't know why. the animation node I try to install is from https://animation-nodes.com/#download under blender2.8X. And I have installed the C++ which mentioned in the install guide. 

Any idea why? And how can I solve this problem?

**Comment by OmarEmaraDev** [comment]
Install `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).

**Comment by windwe2** [comment]
Thank you very much. Problem solved.
