### ISSUE TITLE
Creating and registering a new node inside a third party addon

### ISSUE THREAD

**Issue by maybites** [JacquesLucke/animation_nodes#1235]
Is it possible to create a new node for AN inside another addon, i.e. one that would appear inside the 'add' menu once the other addon is enabled?

My attempts fail. python complains when I try to do something like this:

import bpy
from bpy.props import *
from collections import defaultdict
from ....animation_nodes.sockets.info import toIdName
from ....animation_nodes.base_types import AnimationNode

dataByIdentifier = defaultdict(None)

class OSCInterfaceNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_OSCInputNode"
    bl_label = "OSC Interface"

with an error:

    from ....animation_nodes.sockets.info import toIdName
`ValueError: attempted relative import beyond top-level package`

any suggestions?

**Comment by JacquesLucke** [comment]
Addons are top-level packages in Blender. So you cannot import them relatively. Instead try `from animation_nodes.sockets.info import toIdName`.

**Comment by maybites** [comment]
thanks, that worked!
