### ISSUE TITLE
Increment rotation angle using quaternions.

### ISSUE THREAD

**Issue by khdhhde21** [JacquesLucke/animation_nodes#1236]
I'm trying to rotate a cube using quaternions. The goal is to increment the rotation angle with each frame. I did a similar animation with Euler angles, but encountered a gimbal lock.

This works, but has a gimbal lock (Euler):
![nodeTree 1](https://user-images.githubusercontent.com/33406277/69109263-34053880-0a45-11ea-860d-528b30251ad4.PNG)

This doesn't work (quaternions):
![nodeTree 2](https://user-images.githubusercontent.com/33406277/69109277-41222780-0a45-11ea-9003-8a8afa9998d6.PNG)

I'm not sure if the cube Rotation Mode should be set to XYZ Euler or Quaternion (WXYZ).

If the cube is set to Rotation Mode: XYZ Euler, the Quaternion output in Object Transforms Input doesn't change even if I rotate the cube manually.

If the cube has to be set to Rotation Mode: Quaternion (WXYZ), which output node should be used for that? Or is my approach just completely wrong?

**Comment by OmarEmaraDev** [comment]
See the note about the *Object Transforms Input* node in the [documentation](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/object/object_transforms_input.html#notes).

**Comment by khdhhde21** [comment]
Thank you for clarifying that the cube has to be set to Rotation Mode: Quaternion (WXYZ). Which output node should be used to rotate the cube? The Object Transform Output doesn't rotate a cube set to Quaternion rotation mode.

**Comment by OmarEmaraDev** [comment]
I think the *Object Matrix Output* node should work in this case.

**Comment by khdhhde21** [comment]
Thank you. Now the cube responds to quaternion adjustments, but the scale is also being affected. Here is the nodeTree:

![nodeTree 3](https://user-images.githubusercontent.com/33406277/69645567-5c3bfb00-1034-11ea-9cfb-7a8eb0a90564.PNG)

**Comment by OmarEmaraDev** [comment]
@khdhhde21 Sorry, I didn't see your comment until now. That's because your quaternion is not normalized, insert a *Normalize Quaternion Math* node before converting to get a correct matrix.

**Comment by OmarEmaraDev** [comment]
We fixed that in 5af8a63. Thanks for the report!
