### ISSUE TITLE
Need node note/comment like Houdini

### ISSUE THREAD

**Issue by blackgun** [JacquesLucke/animation_nodes#1237]
As we know, Houdini has the most powerful node system, which one tiny feature "note" is very helpful to understand a complex node tree , where to start, which is which, this inner "note" node is like documentation, super helpful. Can we add this tiny but helpful feature?

**Comment by Fake-User** [comment]
This can already be done in vanilla blender in multiple ways
https://blender.stackexchange.com/questions/7825/is-there-a-way-to-make-comments-in-the-node-editor

**Comment by OmarEmaraDev** [comment]
Can you elaborate? Not sure I get what you mean.
