### ISSUE TITLE
math sinus function into an math add node result in zero.

### ISSUE THREAD

**Issue by LahiruVIP** [JacquesLucke/animation_nodes#1238]
I used a sin function inside a loop and when i add the sinus result with the x component of an separate vector it always results into a zero.
[https://imgur.com/gallery/rKNQsFC](https://imgur.com/gallery/rKNQsFC)

**Comment by OmarEmaraDev** [comment]
Can you please show the whole node tree? Could they be just canceling each other?

**Comment by LahiruVIP** [comment]
Bug fixed itself on their on own. Either by restarting blender on my computer. Since I didn't save the bugged file and moved on with different nodes i can't reproduced the bug any more.

**Comment by OmarEmaraDev** [comment]
Ok, feel free to reopen if you encounter the behavior again.
