### ISSUE TITLE
Not working in 2.81 ?

### ISSUE THREAD

**Issue by Azagwen** [JacquesLucke/animation_nodes#1239]
I tried loading the addon in 2.81, but it kept refusing to activate and even refused to remove itself.

I get this big error message when loading it :
![image](https://user-images.githubusercontent.com/30528331/69486821-2d652f80-0e50-11ea-8487-9fdd4b33cf89.png)

I suppose this is normal since the add-on hasn't be adapted to 2.81 yet ?,
but I prefer to ask.

**Comment by OmarEmaraDev** [comment]
Install `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).

**Comment by OmarEmaraDev** [comment]
See #1240.
