### ISSUE TITLE
Is it possible to sort list from object instancer nodes?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1241]
Currently there is no way to input object instancer nodes into a loop, so I have to do everything related to object instancer outside the loop.
If I generated 50 objects for a loop, and If I were to reuse the loop, I need to duplicate object instancer node and plug it to a duplicated loop. This causes a limitation of proceduralness, because I have to manually duplicate/delete instancer node and loop. It also makes difficult to work with high amount of such operations, that I have to duplicate everything 10 times for 10 loops.
I was thinking a long time to sort list from the output of object instancer node. For example, I want to create 100 objects at once, and sort 50 for one loop, and the other 50 for the other, such as using "mask list" or "filter object list by name" node if possible. But I am noob enough that it confuses me how to do this correctly, so would anyone give some suggestions for this? Thanks.

**Comment by OmarEmaraDev** [comment]
Not entirely sure what you are trying to do. But if you want to split a list of 100 objects into two groups, you can use the *Slice List* node. After that, you can sort the list in which ever way you want.

**Comment by Gerstmann-Bradley** [comment]
> Not entirely sure what you are trying to do. But if you want to split a list of 100 objects into two groups, you can use the _Slice List_ node. After that, you can sort the list in which ever way you want.

Great! I didn't know that! I tested and It worked well. Thanks you so much!
