### ISSUE TITLE
Nodes Not Connecting in Blender 2.81

### ISSUE THREAD

**Issue by CFlandre** [JacquesLucke/animation_nodes#1243]
Not exactly sure if this is the right place to submit this, but figured I'd give it a try.

When building and installing the "blender-plugin-animation-nodes-git 2.1.5.r5357.1b013502-1" version of Animation Nodes from the AUR, the installation completes successfully.

However, nodes do not appear to be connecting properly:

![Screenshot_2019-11-26_10-52-29](https://user-images.githubusercontent.com/3211267/69649444-0b7bd080-103b-11ea-9f2b-e0aafaf708ba.png)

Additionally, no errors are being generated in the console. 

Currently running Blender 2.81. Some assistance would be appreciated!

**Comment by OmarEmaraDev** [comment]
Auto Execution needs to be enabled for the sockets to connect properly.
And yes, we do officially support the AUR package `blender-plugin-animation-nodes-git`, so feel free to report any issues you encounter here.

**Comment by CFlandre** [comment]
Thanks for getting back to me!

Using default settings (with Auto-Execution set to "Always"), the nodes exhibit the same behavior as reported. The changes provided in the screenshot were actually made because the issue had been occurring previously.

I would be happy to test again, but I'm currently at work and can't take pictures at the moment. I'll be happy to submit more tonight if you need them.

Thanks again!

**Comment by CFlandre** [comment]
Hello again!

I am back for the night, and have started testing again.

Here is a screenshot of the node exhibiting the same behavior with Auto-Execution on:
![Screenshot_2019-11-26_21-48-23](https://user-images.githubusercontent.com/3211267/69689304-8cb48100-1096-11ea-9879-e97e41caec1f.png)

I've tried reconnecting the nodes and recreating the nodes with the new option enabled, to no avail.

Thank you again for your help!

**Comment by OmarEmaraDev** [comment]
And you are saying there are no errors in the terminal? When did you last update the package? Did you have Animation Nodes already installed before installing the package?

**Comment by CFlandre** [comment]
You are correct! Enabling/Disabling the addon in the "Preferences Menu" doesn't generate any errors in the terminal, nor does creating/connecting nodes.

I am able to get an error when I hit the "Tab" key, but I'm not entirely sure it's related:


> Traceback (most recent call last):
  File "/usr/share/blender/2.81/scripts/addons/animation_nodes/operators/network_navigation.py", line 20, in execute
    activeNetwork = activeNode.network
  File "/usr/share/blender/2.81/scripts/addons/animation_nodes/base_types/nodes/base_node.py", line 539, in network
    return getNetworkWithNode(self)
  File "/usr/share/blender/2.81/scripts/addons/animation_nodes/tree_info/__init__.py", line 176, in getNetworkWithNode
    return _networks.networkByNode[node.toID()]
KeyError: ('MainTree', 'Time Info')
location: <unknown location>:-1

I installed Animation Nodes _after_ I upgraded Blender to version 2.81; I had upgrade to get the newer features for Blender, but had noticed the absence of motion graphics tools, and AN seemed to fill that gap.

Thank you for your help!

**Comment by OmarEmaraDev** [comment]
hmmm, this is very weird, I am also on Arch and can't replicate that. Can you try removing the package and installing Animation Nodes manually from the website?
https://animation-nodes.com/#download

**Comment by CFlandre** [comment]
Attempting to install the zip file gives me the following error:

> There is a Python version mismatch.
Your Blender build uses: (3.8.0)
Animation Nodes has been compiled for: (3.7.5)

**Comment by OmarEmaraDev** [comment]
Ah, of course. My bad.
I am not sure what is going on, but I will try to replicate your issue on my end.

**Comment by CFlandre** [comment]
Thank you!

If you'd like me to perform any kind of testing, let me know and I would be happy to help you through this as much as possible.

Thanks again!

**Comment by OmarEmaraDev** [comment]
I still can't replicate the issue for some reason. Can you go into the `/src/animation_nodes` directory and execute `git log -1`?

**Comment by OmarEmaraDev** [comment]
hmmm, wait, I didn't update python to 3.8. I will do a system upgrade later, build again, and see if I can replicate the issue.

**Comment by CFlandre** [comment]
Okay, no problem! Let me know if there's anything that I can assist you with! =)

**Comment by OmarEmaraDev** [comment]
Fixed in d6684ea. Thanks for the report!
