### ISSUE TITLE
Frame "grouping" mechanism is confusing.

### ISSUE THREAD

**Issue by kalmdown** [JacquesLucke/animation_nodes#1248]
Current interaction for grouping objects in a frame Is confusing because my expectation is to drag out a frame and resize it around the things I want to encompass. 

Request: Be able to drag a frame to surround nodes and have that be the same as dragging nodes into a frame.

**Comment by OmarEmaraDev** [comment]
I am pretty sure this is a Blender functionality, it is not related to Animation Nodes. Am I correct?

**Comment by kalmdown** [comment]
I don't know. How does one learn where Blender.core stops and an Add-on starts?

**Comment by OmarEmaraDev** [comment]
We only implement a frame selected nodes operator. So this is a feature of Blender. You can add that proposal in https://blender.community/c/rightclickselect/
