### ISSUE TITLE
No Working Version for 2.8 Ubuntu 18.04

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1249]
Title says it all, I can find no working version for Blender 2.81 on Ubuntu. I have tried every version I can find on the 'net, many hours of frustration...

Where can I get one from, is there one?

**Comment by 3DSinghVFX** [comment]
Hi...
You are right. The Animation Nodes from [http://animation-nodes.com/](http://animation-nodes.com/) in Blender 2.81 (Ubuntu 16.04 LTS) showed an error message while enabling in the addon menu.

However, Animation Nodes compiled on my pc worked without any error. You can download the compiled build of AN from https://blender.community/c/graphicall/Wdbbbc/, maybe that works on your OS.

**Comment by Clockmender** [comment]
Yes that one worked, but the one that Google turned up earlier today on Graphicall didn't.....

Thanks!

**Comment by OmarEmaraDev** [comment]
Did the build from animation-nodes.com ever worked on ubuntu? Since when did it start failing? What is the error message exactly?

**Comment by 3DSinghVFX** [comment]
Omar, this is the error message:
![Screenshot from 2019-12-05 00-03-19](https://user-images.githubusercontent.com/30294746/70249279-2fa98100-17a2-11ea-96f5-20e11fef6a1d.png)

**Comment by OmarEmaraDev** [comment]
Did it ever work?

**Comment by OmarEmaraDev** [comment]
Lets continue this in #1240.
