### ISSUE TITLE
Crashes Blender VSE During Animation Render: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by bastianilso** [JacquesLucke/animation_nodes#1252]
very likely related to issue #1200.

Using animation nodes v2_1_windows_py37.zip downloaded today, Blender crashes with the below error while rendering an animation from the Blender VSE. The crash is reproducible for me every time - I cannot render this video without expecting a crash under the way (if not several, sometimes just after one frame).

[crash-reproducer.zip](https://github.com/JacquesLucke/animation_nodes/files/3940293/crash-reproducer.zip)

open the scene and Ctrl+F12.
![image](https://user-images.githubusercontent.com/3967945/70446988-44399200-1a9e-11ea-9840-464fd0ccc246.png)

Setup shown below:
![image](https://user-images.githubusercontent.com/3967945/70447100-7c40d500-1a9e-11ea-818e-681f925890d3.png)

**Comment by OmarEmaraDev** [comment]
Did you try the solutions presented in #1200?

**Comment by bastianilso** [comment]
@OmarEmaraDev rendering from command line seem to work just fine. Most likely the problem would be solved with the same solution, so I will close this issue for now.
