### ISSUE TITLE
Object ID Key node is not working

### ISSUE THREAD

**Issue by grinvaldsjanis** [JacquesLucke/animation_nodes#1253]
It outputs the same 0 for locations and rotations as well as scale 1, although objects in a 
![bug](https://user-images.githubusercontent.com/6594177/70517636-88ca3980-1b41-11ea-9db1-65d4c97c1159.jpg)
the collection is scattered and all have diff.locations and rotations. They are also affected by 2 "Locked track" constraints. I tried to disable constraints for 5 of them, it did not influence the (?)bug.

Maybe it's important that objects are instanced with copied constraints and the same material.

**Comment by OmarEmaraDev** [comment]
Solved by adding ID Keys From Transforms as described in the ID key documentation page.

**Comment by newemka** [comment]
I think this issue needs to be reopened, Initial transform from ID Keys isn't working with Collection info.

**Comment by OmarEmaraDev** [comment]
@newemka Can you show me the node tree?

**Comment by newemka** [comment]
![image](https://user-images.githubusercontent.com/3755089/99189612-4f8f4600-2762-11eb-8971-578b3e8367a6.png)

maybe i'm missing a node, once i add the matrix output all my objects get positioned to origin 0,0,0.

**Comment by OmarEmaraDev** [comment]
@newemka Can you double check if you actually created the keys? In the 3D viewport, in the side bar, in the AN panel, click *From Current Transforms* while selecting the object.

**Comment by newemka** [comment]
@OmarEmaraDev ok I get it, now it's working, thank you so much, now i understand what was my mistake.
