### ISSUE TITLE
Sort list node

### ISSUE THREAD

**Issue by piotrkopiczynski** [JacquesLucke/animation_nodes#1254]
Hi Omar,

what happened with sort list node ?
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/list/sort_list.html

Thank you for everything :)

**Comment by OmarEmaraDev** [comment]
The Sort List node was removed and was replaced by the Sort Number node. Is this what you were looking for?

**Comment by piotrkopiczynski** [comment]
It's ok. I was looking at the menu. I rarely use ctrl + A
Thank you.
