### ISSUE TITLE
sound sequence problems

### ISSUE THREAD

**Issue by nikstru** [JacquesLucke/animation_nodes#1255]
I'm having problems with the sound related nodes. The input only works for a couple of minutes then becomes "dead" - doesn't give any information out. It starts working again if i delete the sound file and put it back in blender, but only for another couple of minutes... The real issue here is that when i try to render an animation, blender crashes after the first frame. 

please help!

**Comment by nikstru** [comment]
i've figured out that the problem is in the sequence input node, but i've tried everything i could come up with..

![Capture](https://user-images.githubusercontent.com/58919194/70869915-fdf89d00-1f8d-11ea-90ea-a5f8ee1342a5.PNG)
![Capture1](https://user-images.githubusercontent.com/58919194/70869916-fe913380-1f8d-11ea-8eb5-7ac81f8b5f8f.PNG)

**Comment by OmarEmaraDev** [comment]
The crash is due to #1200. Does the Sequence Input node output None after couple of minutes?

**Comment by nikstru** [comment]
If i try rendering without the audio input there are no issues with it. 
It goes to "none" after a couple of gestures I don't think it is exactly relevant to the time, i am not sure which gestures exactly but starting rendering is one of them.

**Comment by OmarEmaraDev** [comment]
I can't replicate the issue unfortunately. Can you prepare a minimal scene to replicate the issue?

**Comment by nikstru** [comment]
here is a project file with the same issue 
[animation nodes problem.zip](https://github.com/JacquesLucke/animation_nodes/files/3980235/animation.nodes.problem.zip)

**Comment by OmarEmaraDev** [comment]
Unfortunately, I can't replicate the issue.
When the issue occur, can you check the value of the Node Tree Scene in the T menu?

**Comment by nikstru** [comment]
what do you mean with the value of the node tree? Inside this dropoff menu?

![Capture2](https://user-images.githubusercontent.com/58919194/71325687-7ad8c900-24f0-11ea-8e41-3bc3ef4c68bc.PNG)

**Comment by OmarEmaraDev** [comment]
Yes, this one. Is this always set to Scene?

**Comment by nikstru** [comment]
yes

**Comment by OmarEmaraDev** [comment]
Can you show us the terminal output when the issues happens? Do you have multiple scenes?

**Comment by nikstru** [comment]
I only have one scene, i'm not sure what u mean with the terminal output maybe this.. 
it looks like this before i hit render and works in the interface, but after it goes to "none" like the other veiwer.
![Capture](https://user-images.githubusercontent.com/58919194/71445596-25cccb00-271b-11ea-989f-d02ddc67aeba.PNG)

**Comment by OmarEmaraDev** [comment]
Are you on Windows?

**Comment by nikstru** [comment]
yes

**Comment by OmarEmaraDev** [comment]
When the error occurs, go to Window -> Toggle System Console. Then show us the output of the console.

**Comment by nikstru** [comment]
![Capture1](https://user-images.githubusercontent.com/58919194/71445854-d045ed80-271d-11ea-8b45-d427699e4982.PNG)

**Comment by OmarEmaraDev** [comment]
Are you sure you are using the latest Animation Nodes build? Download the latest build from: 
https://animation-nodes.com/

**Comment by nikstru** [comment]
yes i have this build installed
