### ISSUE TITLE
"From Curve" interpolation node causes an error in Animation nodes (blender 2.82 alpha)

### ISSUE THREAD

**Issue by Dihotom** [JacquesLucke/animation_nodes#1257]
In recent builds Curve interpolation node gives an error in blender 2.82 (2.81a works as expected)
![error](https://user-images.githubusercontent.com/22814165/71163493-43eb8480-225e-11ea-9e96-c412658fc5d2.png)

**Comment by OmarEmaraDev** [comment]
Fixed in a51e572. Thanks for the report!
