### ISSUE TITLE
Axis / within bounds manipulation and reset action

### ISSUE THREAD

**Issue by Gelenov** [JacquesLucke/animation_nodes#1259]
Hi
im trying to do Rubik Cube - 9 cubes per face x 3
Select all 9 cubes works fine for any face ... then turn on any axis ... 
id like to do this with rig / bone ? for education so once turned it has to reset like the gizmo or simple box select
quaternion seems not to work because there is no clear/reset option for new position of cubes once they have been turned - action complete followed by auto reset ?
thanks

**Comment by OmarEmaraDev** [comment]
Can you elaborate? I am not entirely sure what you are asking.

**Comment by Gelenov** [comment]
Hi
i put 9 cubes together ... like ONE face of Rubik cube
i must now box select all to rotate on xyz
ok now make three of these - 9 cubes each = 27 cubes = rubik cube
select one side (9 cubes) and rotate
so every time different parts of cube become xy or z axis
i want one controller ... like bone  to control ONE side all the time just
like turning Rubik cube sides
so far it cannot be done ... if u parent 9 cubes together ... then u can
only move them once
every time a face moves it will need NEW parent (if u use parents - i did
but it fails) ... or better a new box select automatically

i need 9 bones to control all sides of the cube xyz 3 for x 3 for y 3 for z
then it can work BUT only if there is box select
how to put box select into armature ? and reset it every time you change
one axis to another ?
thanks

**Comment by OmarEmaraDev** [comment]
Are you looking to do that in Animation Nodes?

**Comment by Gelenov** [comment]
if it can be done yes ... im looking at Sverchok as well ... (on their site
someone has similar request i saw last week)
it was just something i want to do if possible ... not priority at all
would be fun though
thanks

**Comment by OmarEmaraDev** [comment]
I see. Github is more for discussing matters related to AN development. It is best that you direct your questions to other places like blender.SE. Closing for now.

May I suggest you take a look at this answer:
https://blender.stackexchange.com/questions/77756/animation-nodes-rubiks-cube
