### ISSUE TITLE
Create sockets in loop like in script node

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#126]

**Comment by og76** [comment]
groups too?

**Comment by JacquesLucke** [comment]
yes

**Comment by JacquesLucke** [comment]
https://github.com/JacquesLucke/animation_nodes/commit/e7e604323e87316ef4163bba86b90729406a62ad

![loop new socket button](https://cloud.githubusercontent.com/assets/5881326/7583236/dfcad332-f893-11e4-972d-5cbd53c43d64.PNG)

Please leave this open for the groups
