### ISSUE TITLE
repeatable blender crash when rendering (not 1200?)

### ISSUE THREAD

**Issue by chconnor** [JacquesLucke/animation_nodes#1260]
Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid 64 Bits
GeForce GTX 1060 6GB/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 390.116
Blender 2.81 (sub 16), branch: master, commit date: 2019-12-04 11:32, hash: rBf1aa4d18d49d
[AN version ... will update if you need it -- rendering now -- downloaded a week or so ago]

Hi -- when rendering an animation I am getting a crash. (If I delete or disable the AN's in various ways, the crash doesn't happen.) I have seen issue #1200 , and this might be different? I am only setting the Z positions of objects with a custom script triggered by AN.

I have stripped a demo project down as much as I can (see attached.) The file crash_demo.csv is associated as well: my script parses it, so you'll need to put that in /tmp/. (or change the specified path in the AN tree.)

When I "render animation" it usually crashes after a few frames. Sometimes it locks up the computer instead.

[crash_demo.zip](https://github.com/JacquesLucke/animation_nodes/files/3997414/crash_demo.zip)

I have a CLI render going now and so far it is working OK, so that does sound like 1200...

In the process of working on this I think I also found an (unrelated?) blender bug, which I mention in case it's relevant in some way: https://developer.blender.org/T72667

Here is the stack trace generated:

```
# Blender 2.81 (sub 16), Commit date: 2019-12-04 11:32, Hash f1aa4d18d49d
bpy.context.area.ui_type = 'OUTLINER'  # Property
bpy.context.space_data.params.filename = "crash5_demo.blend"  # Property
Saved "crash5_demo.blend"  # Info

# backtrace
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(BLI_system_backtrace+0x1d) [0x14ee84d]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12cbb79]
/lib/x86_64-linux-gnu/libc.so.6(+0x41100) [0x7f676aab4100]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(BLI_ghash_lookup+0x38) [0x14aacb8]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_ZN3DEG19graph_id_tag_updateEP4MainPNS_9DepsgraphEP2IDiNS_13eUpdateSourceE+0x1f0) [0x14f88a0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_ZN3DEG13id_tag_updateEP4MainP2IDiNS_13eUpdateSourceE+0x55) [0x14f9315]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x1596e3b]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x1568e26]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_BaseMathObject_WriteIndexCallback+0x23) [0x443b273]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x44458ee]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyObject_GenericSetAttrWithDict+0x73) [0x191cfa3]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(PyObject_SetAttr+0x4f) [0x191c49f]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x44c3) [0x12c3433]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x8cce) [0x12c7c3e]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalCodeWithName+0xadc) [0x198c36c]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(PyEval_EvalCodeEx+0x3e) [0x198c49e]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(PyEval_EvalCode+0x1b) [0x198c4cb]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x1989ab5]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyMethodDef_RawFastCallKeywords+0x2cc) [0x18da92c]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyCFunction_FastCallKeywords+0x25) [0x18da9d5]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x9440) [0x12c83b0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x88dc) [0x12c784c]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x88dc) [0x12c784c]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x88dc) [0x12c784c]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x8cce) [0x12c7c3e]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyFunction_FastCallDict+0x2a6) [0x18da396]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x2f0f) [0x12c1e7f]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalCodeWithName+0xadc) [0x198c36c]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyFunction_FastCallKeywords+0xa6) [0x18da456]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x88dc) [0x12c784c]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x8cce) [0x12c7c3e]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyEval_EvalFrameDefault+0x8cce) [0x12c7c3e]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12bdec0]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(_PyFunction_FastCallDict+0x2a6) [0x18da396]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x1574e3a]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(BLI_timer_execute+0x4a) [0x46aceaa]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(wm_event_do_notifiers+0x2e) [0x16a75ae]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(WM_main+0x28) [0x169dcd8]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender(main+0x2fe) [0x1237f7e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f676aa9709b]
/path/to/blender/blender-2.81a-linux-glibc217-x86_64/blender() [0x12c849c]
```

**Comment by OmarEmaraDev** [comment]
Unfortunately, by looking at the stack trace, this seems very much like #1200. You will have to render from the CLI for now until we figure out a workaround. Sorry for the inconvenience.

**Comment by chconnor** [comment]
Thanks for the reply -- a couple questions if you have the time:

I have about 6 months of projects coming up that I was planning to use AN with.

- given that my render worked from the CLI this time, is it safe to assume that it will work in the future with other projects? (They will be running the exact same scripts, doing the same kind of things to the same objects, but with other stuff happening in the proejct.)

- my project isn't making much use of AN anyway -- I'm really just using it to trigger my custom script on every frame change. If I don't use AN at all and just figure out how to script that myself (assuming it's possible for my beginner skill level), will I avoid this bug entirely? I.e. is it a bug having to do with AN + blender? Or is it something more to do with the python API of blender, so I'll run it to it either way?

- I saw in #1200  that the bug was being looked in to and worked on. Sorry to poke; just curious if it was in the "we're working on it, we have leads" category, or more like the "nobody is really on top of it at Blender HQ due to limited resources" category.

Thanks for any info, and for AN!

**Comment by OmarEmaraDev** [comment]
- I don't want to give you a guarantee. But generally yes, things should work fine from the CLI, or simply by using the script given in #1200.
- If you really don't use AN that much. You can just use an application handler to execute your script every frame, let me know if you need any help with that. See: 
https://docs.blender.org/api/current/bpy.app.handlers.html
However, you may still encounter the crash above. (Animation Nodes uses application handlers and timers in the background)
- I believe Sergey said the cause of the bug is a design issue with the dependencies graph in Blender. The use of timers or handlers will trigger the crash, but it is much less likely to happen when you have no UI, hence why we said render from the CLI. The Blender developers consider this a known issue and they don't seem to be working on it for the time being. When I said "we are looking into it", I meant that we are looking into workarounds to implement in Animation Nodes, not that we are looking into fixing it in Blender itself; only god and Sergey knows how the dependencies graph works. :smiley:

**Comment by chconnor** [comment]
Thanks!

Is this [the blender bug](https://developer.blender.org/T62074) you refer to?

**Comment by OmarEmaraDev** [comment]
@chconnor No, this one. [T60094](https://developer.blender.org/T60094)
