### ISSUE TITLE
[BUG] "Curve interpolation" node seems broken

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1261]
Win10.
Blender 2.81
Currently most updated Ver. of AN with "Insert vertex color layer".
![broken curve interpolation](https://user-images.githubusercontent.com/55994236/71421823-4d546280-264b-11ea-86ef-f4460943c5ab.png)

I loaded the factory setting of blender, issue can't be solved.
Reinstallation of AN also didn't solve the problem.
I think this didn't happen earlier, but it happens now. Will look forward to an answer. Thanks.

**Comment by OmarEmaraDev** [comment]
I am guessing this is due to a change in the Blender API. Can you test on a daily Blender build?

**Comment by Gerstmann-Bradley** [comment]
> I am guessing this is due to a change in the Blender API. Can you test on a daily Blender build?

Correct, it works in the most advanced version of blender 2.82 updated in 12.24.2019. hmmmmm

**Comment by OmarEmaraDev** [comment]
I updated the node two days ago to accommodate the API change, that meant older versions will no longer work. You can revert a51e572 temporarily until you choose to update.

Closing for now.
