### ISSUE TITLE
Possible to duplicate data from "curve interpolation"?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1262]
Sorry to send another question about curve interpolation.
If I shift+D a curve interpolation, data won't be duplicated and it will be reset back to standard linear.
sometimes I want to save a copy of interpolation, but because of this I can't. Although in general this may rather be a minor issue, but still kind of sad.

**Comment by OmarEmaraDev** [comment]
Fixed in f86e1eb. Thanks for the report!
