### ISSUE TITLE
Viewport Input node not in "add" menu

### ISSUE THREAD

**Issue by moongaze** [JacquesLucke/animation_nodes#1264]
Hi ,

As the title states, I haven't been able to find the viewport input node in the add menu. I discovered this node through a tutorial, where it is fetched through ctrl+A search. I am using version 2.1.5 
Are there other nodes I might not be aware of that aren't listed?
I might be blind, but I've iterated through the add menu several times and can't see it...

I also noticed a typo in the Grease Pencil menu-> Objcet Material Output

Awesome add-on by the way!

Regards

**Comment by OmarEmaraDev** [comment]
Thanks for pointing this out. We will make sure to add that to the menu.

**Comment by OmarEmaraDev** [comment]
Added in 174c802.
