### ISSUE TITLE
Some proposals/? of subprogram: pre-hiding sockets, vectorized input, object instancer?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1266]
**1. pre-hiding sockets of group input subprogram.**
While I was trying to make some presets using "group input" node, I realized because of many sockets, a subprogram turns to be huge while it's not necessary like that.
A comparable example is "object mesh data" node, which is a native node within AN. When it's called, not all sockets available will be shown in the first place. I hope I can also hide some sockets in my group subprogram preset before it's being called, so that the size of node doesn't always seems large.

**2. Is it possible to vectorize the input of a subprogram?**
Still about the group input node, many times I can either choose "float" or "float list" and plug it into radius of "spline from points" node, while the radius socket is vectorized and can receive single/multiple inputs, the subprogram can only choose one of them. (Switch can't work because inputs has to be of the same type as well)
It's very tricky that AN has no node group function but subprogram instead. Especially in such kind of case I feel the subprogram can't really replace "node group" function.

**3. is it possible for "object instancer" being in the subprogram?**
This is a problem for long and I suppose developers must be aware of that. It will cause errors when  the"object instancer" is in any kind of subprogram. Thus it's impossible to make a group for it, and it turns obligatory to repeatedly use many nodes to achieve some simple function.
For example, If I frequently need to place objects on a grid with some variation, it's obligatory to use more than three nodes to do the work, and I feel it will be more convenient if it can be built in a preset, but whatever preset is being made, it has to be in the downstream of object instancer node.

----------------------------------
I don't want to explode this github with too many/frequent questions so I merged them into a single post.
Or if agreed, later on I will post separates posts if the topics are different.

**Comment by OmarEmaraDev** [comment]
I will get back to you tomorrow.

**Comment by OmarEmaraDev** [comment]
1. I think this is something we can do. Thanks for the suggestion!
2. I will need to think about the possibility of doing so. It seems very problematic.
3. I don't think this is something we will be working on. The implementation of this is particularly hard because we need to keep track of objects created using the node.

**Comment by Gerstmann-Bradley** [comment]
> 1. I think this is something we can do. Thanks for the suggestion!
> 2. I will need to think about the possibility of doing so. It seems very problematic.
> 3. I don't think this is something we will be working on. The implementation of this is particularly hard because we need to keep track of objects created using the node.

Don't worry, take your time and thanks for your reply. I am not technician so can only suggest some thoughts without knowing the difficulty behind.

Particular for the 3rd,  recently as I was learning Sverchock node in blender, I realize they don't have instancer node, but soon as you put a list of data (such as matrices), it seems automatically generating multiple instances. I don't know what is actually behind these nodes to do such a work, but I am wondering about the difference.

**Comment by OmarEmaraDev** [comment]
I am not very familiar with Sverchok, so I don't know how they do things. But I will look into it.

**Comment by OmarEmaraDev** [comment]
Subprogram socket hiding was implemented in f445b15. Thanks for the suggestion!

We tried your other suggestion but it didn't really work out. We might give it a try again in the future, but for now, I will not consider it.

**Comment by Gerstmann-Bradley** [comment]
Hi Omar. I have one question. Currently we can pre-hide "input socket", but is that possible to pre-hide "output socket" as well? it may be little difficult to do? How do you think about it?

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley This is already possible. Is it not working?

**Comment by Gerstmann-Bradley** [comment]
Here is an example of what I am talking.
The new feature is listed in 1 and it allows to hide "input socket"/parameter sockets of subprogram.
However, I am also thinking about 2, in which we can hide "output socket" by default. For example, object mesh data node contains many output, but by default it only shows 3. 
Maybe this function is already possible in subprogram, but I unfortunately have no idea how to do so. The panel in "list generator" obviously looks different from those "parameter sockets". 
Another thing is that, Group subprogram and loop subprogram have different ways to setup the output. I am afraid it will be difficult for you to achieve what I am suggesting?
![Example](https://user-images.githubusercontent.com/55994236/91768193-43f0a200-ebab-11ea-97d1-b648600d2983.png)

**Comment by Gerstmann-Bradley** [comment]
Oh, wait, I see how to do so. thanks
