### ISSUE TITLE
Proposal: smooting lists

### ISSUE THREAD

**Issue by grinvaldsjanis** [JacquesLucke/animation_nodes#1269]
The proposal title might be self-explanatory. Idea is to have a node which
- inputs list with floats, and maybe even vectors(not sure) and other types;
- offers similar algorithms for smoothing, maybe with iterations and other variables;
- outputs smoothened list, ideally - I would add delta(means difference) list in output, as a hidden option probably.

P.S - Probably there are other useful, practical math things which can be done with lists and vectors

**Comment by OmarEmaraDev** [comment]
While such smoothing might be useful, I think it is not clear or general enough to implement as a dedicated node. In particular, there is no explicit spatial correspondence between list elements either as floats or vectors, while for meshes that is quite clear. It should be quit easy to create a subprogram for that, so I think users should do for now.
