### ISSUE TITLE
Animate nodes treat duration under 1.00 (0.32,0.54 ..) as 1.00 

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#127]
Animate nodes do not allow duration under 1. Durations like 0.66 or 0.87 are considered 1.00
It seams to be by design. Is this How it's intended? 
Not a big deal, but if so, maybe limit the duration  to min 1.00 so that I can see ...
(I was setting that around and took a while to realize why nothing was changin..)

https://drive.google.com/file/d/0BzzAoBwXO8dseENCQWlNbk9rUnc/view?usp=sharing
if not clear, play with durations under 1 and see no effect

**Comment by JacquesLucke** [comment]
This was a mistake by me. The duration has to be higher than zero. When I wrote this I didn't took subframes into account so the minimum duration was 1. Should be fixed now

https://github.com/JacquesLucke/animation_nodes/commit/e73848ae860a22595762c713a36192de13483913

**Comment by og76** [comment]
it's ok now. all three
