### ISSUE TITLE
retrieve socket index for object material output?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1271]
I was fracturing an object and put two different materials on outer surface and inner surface of pieces. Fracturing in blender is not procedural, the material being set is being set. It's possible to use object material output node to put materials on all these pieces, but it seems it can only put one material on a single object through nodes. I know and did a workaround to solve this issue, but if possible, I wish to have the ability to **retrieve different material socket**, as we can **in set vertex color node**.

**Comment by OmarEmaraDev** [comment]
I am not sure what you are asking. But you can put multiple materials using the *Object Material Output* node by inputting a list of materials.

**Comment by Gerstmann-Bradley** [comment]
> I am not sure what you are asking. But you can put multiple materials using the _Object Material Output_ node by inputting a list of materials.

Ooops, didn't realize it's possible for multiple inputs. thanks for answering!
