### ISSUE TITLE
Proposal: Node shrinking

### ISSUE THREAD

**Issue by grinvaldsjanis** [JacquesLucke/animation_nodes#1273]
To optimise overview of the tree, sometimes there is a repetitive work on "closing" node with the arrow on the header of node and then, slide it such small so You can still see that title or formula of the node. There could be some shortcut or left-click option for shrinking the node as small as possible but leaving header text visible.

**Comment by OmarEmaraDev** [comment]
You can just select all then hide the node.

**Comment by grinvaldsjanis** [comment]
> You can just select all then hide the node.

Ok. Then shrinking horizontally left, because some math nodes still can occupy a lot of space, and Houdini approach starts to look reasonable.

**Comment by OmarEmaraDev** [comment]
I am not sure this is something we should add in AN. Perhaps you should propose this to Blender instead.

**Comment by grinvaldsjanis** [comment]
What about drawing a "cloud" around subprograms automatically?

**Comment by OmarEmaraDev** [comment]
Not sure what you mean. Do you mean a frame?

**Comment by grinvaldsjanis** [comment]
Maybe it could be a frame but could be like nameless zone

**Comment by OmarEmaraDev** [comment]
If you want to frame a group of nodes, it is sufficient to use the Ctrl + F shortcut. Isn't this what you want?

**Comment by grinvaldsjanis** [comment]
> If you want to frame a group of nodes, it is sufficient to use the Ctrl + F shortcut. Isn't this what you want?

One thing is to frame any sufficient group of nodes for highlighting, but other is automatical - not manual kind of border around all the nodes together which are related to the subprogram. It should not require any effort but helps visually divide trees. I think trees could also repel each other as a whole, in kind of bubble, so there's no possible to overlap nodes from different trees

**Comment by OmarEmaraDev** [comment]
I don't think this is something we will implement. Subprograms already have unified colors for identification, and I think this is enough. You may increase the saturation in the addon preferences for more contrast. You may also manually frame if you choose to.

**Comment by OmarEmaraDev** [comment]
Feel free to reopen if you want to discuss this further.
