### ISSUE TITLE
Converting animated splines to animated meshes

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1274]
Instead of creating an animated spline I'm trying to create the exact same animation but using **meshes**.  I used Loft Splines > Combine Mesh > Mesh Object Output.  But nothing is generated.

![screenshot-December-29-2019-14:00:40](https://user-images.githubusercontent.com/28985314/71561372-a35a4900-2a43-11ea-9bc8-b9bbaf1a7b7e.png)

The reason for converting to meshes is to export the animation using Verge3d so the animation will work / be adjustable over the internet using a browser (Verge3d only works with meshes).

I'm using Ubuntu 18.04 64bit Linux
Blender 2.81
Using Animation Nodes 2.1.5
[an_script_question_edit_question_no_bake_mesh.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4008446/an_script_question_edit_question_no_bake_mesh.blend.zip)

**Comment by OmarEmaraDev** [comment]
You should use the *Mesh From Spline* node. And don't do that inside the loop, use the output of the loop instead.

**Comment by 3DSinghVFX** [comment]
Here is the modified version of your node-tree for _Mesh From Spline_ node,
![an_script_question_edit_question_no_bake](https://user-images.githubusercontent.com/30294746/71561665-7f2c5580-2a9f-11ea-8ea4-f505011f1038.png)

**Comment by stillpointx** [comment]
Thanks!!!
