### ISSUE TITLE
Some feature requests - new falloff types (memory,mesh),memory node,tracer,color improvements etc

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1276]
These are some features which is nice to have on AN. Iam a c4d user, so most of requests are related to c4d features.

**1. New falloff types**
- **Mesh falloff** : A falloff type that can adapt mesh shape. AN have object conroller but it can only adapt spherical shape.currently we can create mesh falloff using kd or bvh trees but something built in would be easier.

- **Memory falloff** : A node that can store previous states of falloff in memory. 
example :
![memory falloff demonstration](https://user-images.githubusercontent.com/46858047/71593167-f376ff80-2b58-11ea-90ea-09a4f3db8823.gif)

**2. Additional nodes** 

- **Memory node** : This node stores previous states of input in memory.How long input data is stored is controlled by history depth. Input can be anything float,vector,color,matrix etc. [Explanation of memory node in c4d](https://youtu.be/CqS4uDwuH5c)
Here is the solution made using struct datatype (vector,matrix,float,color) ([I followed same approach as particle tracing](https://blender.stackexchange.com/questions/105090/how-to-store-particle-locations-in-a-list)) :
![struct memory](https://user-images.githubusercontent.com/46858047/71594443-f0cad900-2b5d-11ea-96b2-bffb88d3f796.gif)

- **Tracer node** :  Helps to create object trails.This node takes a vector location as input and outputs spline traces.

- **Separate connected polygon node** : It takes mesh as input and outputs a mesh list containing connected polygons. Same as "separate by loose parts" function in blender.

**3. Color nodes improvement** : 

- vectorized separate and combine color nodes

- color mix node having blend modes like overlay,screen,multiply,softlight etc

**4. Mix node like in sverchok**

- Instead of separate vector and matrix mix node, a single mix node with drop down list would be nice. vectorization of inputs and factor are welcome.
sverchok mix node : 
![sverchok mix](https://user-images.githubusercontent.com/46858047/71595394-61bfc000-2b61-11ea-9064-f5396f7b1767.gif)

**5. Ability to hide subprograms from menu** : It would be nice to have an option to hide subprograms like loop,group etc from menu. Some times subprograms like loops from other node tree make menu untidy and difficult to find. 

**6.More noise types** : More noises like c4d would be nice. if possible [curl noise](https://youtu.be/udU2f3vcip8) are always welcome. 

**7. ON OFF switches** : Nodes having activate switch would be helpful.

**Comment by OmarEmaraDev** [comment]
Hi, thanks for your suggestions!

Some of those suggestions are definitely doable and will happen, others would need some discussion first. I will get back to you on those later.

**Comment by OmarEmaraDev** [comment]
Hi @harisreedhar,

- Mesh Falloff was already added by Kuldeep.
- It was decided before that any kind of memory nodes will not be allowed in Animation Nodes as it goes against its design. So unfortunately, we will not work on those memory nodes for the time being.
- Separate By Loos parts was suggested in #1578 and will be tracked there.
- Color nodes were already vectorized.
- Color Mix can be added. Could be a good patch for new comers.
- Mix nodes were already vectorized, there is still some work to be done, but we have a pending pull request for that.
- Curl noise was talked over with Kuldeep, will present a proposal to Jacques later.
- Conditional execution was suggested in #1027. But wasn't accepted, might try to restore that again later.

Proposals that were not discussed can have their own issues if needed to be tracked better, so feel free to do that.
