### ISSUE TITLE
A dumb question about trigger

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1279]
Is it possible to set "scene collection" for collection trigger? Obviously the answer is not at the current moment.
But when I am too lazy to specify which collections should serve as trigger collection, I simply hope to use all collections for trigger. I am personally not satisfied to add a bigger collection, that hold all other collections inside and serve as a trigger. This is because increasing even a single hierarchy meaning all collections will be shift to right for one unit, it wastes some space in interface....

I have tried to use "scene" trigger, but I don't know how to get "location" attribute for objects within the whole scene....So have to ask here for some suggestions.

**Comment by OmarEmaraDev** [comment]
Don't all objects in the scene belong to a master collection? Wouldn't it be sufficient to use this master collection?

**Comment by Gerstmann-Bradley** [comment]
> Don't all objects in the scene belong to a master collection? Wouldn't it be sufficient to use this master collection?

For organizations, I make different collections (each for parts of modelings, like a room has window, door, closet and so on), which has the same hierarchy as the master collection. I can put all collections under this master collection for sure, and use this master collection as trigger, but generating an additional hierarchy isn't my preference. While scene collection is the true "master collection", it's not usable.

I think this is a dumb question because it's minor and basically solvable using workaround. But generating an addition hierarchy for such a purpose seems a waste for me.

**Comment by OmarEmaraDev** [comment]
I see, I was under the impression that the master collection was a standard collection. It seems it is only accessible per scene. What do you propose the UI for choosing the master collection should be?

**Comment by Gerstmann-Bradley** [comment]
> I see, I was under the impression that the master collection was a standard collection. It seems it is only accessible per scene. What do you propose the UI for choosing the master collection should be?

I was thinking about this,
I think it may be complicate to change UI. This is a blender issue, and this only becomes an issue when talking about AN in this case. So maybe changing UI is not too preferred.
--------------
At the end I think the easiest way to do the work is **to simplify the way to make a trigger** if possible. Usually when I want to activate a collection for trigger, three types of parameters (location, rotation, scale) are all included. This makes it troublesome to expand for collections that have the same hierarchy. Just including two collections of the same hierarchy already requires 6 triggers.

By reading manuals it seems the essence of setting triggers is through scripting.
is that possible, that **I just need to choose a collection and it automatically use all three types of parameters for trigger, instead of just one of them**?

**Comment by OmarEmaraDev** [comment]
You can write as much parameters as you want with a comma as a separator. For instance, `scale,location,rotation_euler`.

![20200103-164830](https://user-images.githubusercontent.com/25300994/71729508-9cb74180-2e48-11ea-8ecc-9446ddfcdcd3.png)

**Comment by Gerstmann-Bradley** [comment]
> You can write as much parameters as you want with a comma as a separator. For instance, `scale,location,rotation_euler`.
> 
> ![20200103-164830](https://user-images.githubusercontent.com/25300994/71729508-9cb74180-2e48-11ea-8ecc-9446ddfcdcd3.png)

Oh great! I didn't know that! thanks!
