### ISSUE TITLE
Bake to keyframe via scripts not work...

### ISSUE THREAD

**Issue by rampagedog12** [JacquesLucke/animation_nodes#1284]
Damn.. I misclick.. post issues without content....
I am trying to bake to keyframe via scripts. I write a code to override the context, but it doesn't work...

```
import bpy

context = bpy.context

ngs = bpy.data.node_groups
tempt = context.screen.areas[0].ui_type
context.screen.areas[0].ui_type = 'an_AnimationNodeTree'
override = context.copy()

bpy.ops.an.bake_to_keyframes(override, startFrame=0,endFrame=250)

del override
context.screen.areas[0].ui_type = tempt
```

I got the errors below. The error same as one that I didn't use override context.
![image](https://user-images.githubusercontent.com/25874618/72097226-e50fad00-32e9-11ea-9bbb-3da91e42ab4a.png)

**Comment by OmarEmaraDev** [comment]
Since this is a model operator, you just need to call it with `INVOKE_DEFAULT`.
```
bpy.ops.an.bake_to_keyframes("INVOKE_DEFAULT", startFrame=0, endFrame=250)
```
