### ISSUE TITLE
Improve/additional function of "append to list"

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1285]
1. Currently its' behavior is to append element to the last.
I think it may potentially be better to append to any places possible (according to index number chosen).
Or at least having the ability to append to the beginning.
Now to append things at beginning, I need to reverse the list, this may be minor but still as an extra work.
2. other times I want to append element but keep the list length the same.
So I need to add a "slice list".
Functionally there is no problem, but practically it adds more nodes.
So I was thinking it may be better to make slice list function native within append to list node?
Or in such a case maybe it more behave like a "replace list element" node? I don't know.

I thought about making a node group, but later I realize there are different type of lists.
group/loop input can't switch between type of input.
If I make things generic, I still need to convert things at the end outside the group, it still adds nodes and doesn't save nodes as much as expected.
I think it may be potentially better if AN can improve this node to do such a function so that less nodes will be used? Or maybe add a complete new "replace list element" node as mentioned earlier?

**Comment by OmarEmaraDev** [comment]
So to summarize, you want:
- An Insert List Element At Index node.
- Allow multi element set in the Set Element node.

**Comment by Gerstmann-Bradley** [comment]
> So to summarize, you want:
> 
> * An Insert List Element At Index node.
> * Allow multi element set in the Set Element node.

Yes, you are basically right.
In terms of the second proposal, "set element node" is exactly what I was looking for. but having multi element set can definitely be cool, although currently I can't come up with a specific case that I need it.

**Comment by OmarEmaraDev** [comment]
Implemented in 29d08ee. Thanks for the suggestion!
