### ISSUE TITLE
User naming of nodes

### ISSUE THREAD

**Issue by kalmdown** [JacquesLucke/animation_nodes#1286]
I am using AN with visualization tools and need the elements to be addressable by name (like states, counties, zip codes) so that code can find them easily. I also export to Unity and "instance_dhdha_00" is not helpful. 

Would also be helpful when debugging within Blender to be able to look through the list and quickly ID what AN has created. 

- Thanks!

**Comment by OmarEmaraDev** [comment]
Not entirely sure what you are asking for. Can you elaborate?

**Comment by kalmdown** [comment]
An example - I have a setup that takes the names of the US states and creates text objects from them. The objects that AN creates are named instance_hghff_01 etc. I would like them named AL_label, AK_label, AZ_label, etc. This allows me to check that my nodes ran correctly, but more importantly, when I use them later lets me easily address them by name in code, whether in Blender or Unity.  
Similarly, when I create graphs I want the data points (bars, wedges, points, etc) to be uniquely ID'd by some meaningful system so they can be addressed easily in code.

Sometimes I am just using AN to quickly create systems in complex relationships but afterward would like to bake the nodes and work with individual objects. In that case, when creating architectural elements, I would like the names of the objects to be Window_East_1, Window_East_2, etc. so that when it is time for me to edit that they are easily identifiable. 

Best would be, in Object Instancer nodes a naming input with the ability to generate names via rules or pull names from sources like GSheets, CSV, Excel, etc - as well as other data to generate objects.

**Comment by OmarEmaraDev** [comment]
I don't think this is something we will do.

You may add custom properties to the objects to store the data that you wish to store. You can also rename your objects easily before exporting. What do you think about this approach?

**Comment by kalmdown** [comment]
It is **not** easy to rename objects after the fact. It is extremely error-prone after more than 5 objects. I just did it for the states and misspelled two of them. It becomes even more problematic if the names are contextual - names of states, positions of objects in space, items in visualizations, object's relationships within hierarchies. Going back to the objects and intuiting what their name should be in by finding them in 3D space is extremely error-prone. 

I think this is an important issue. There is no part of design or working in 3D apps where naming is not important. I would be very happy to work with whoever to work through issues to make this work. 

I assume the issue you see is how to verify unique naming while running the nodes. There would need to be mechanisms in place when objects are created that impart or verify uniquiness. In an Object Instancer, there would be a name input. If not filled AN would do what it currently does. Otherwise, it should take input or use relationships between nodes to help make it so. 

The simplest solution is to replace "instance_fhfhf_" with a user string. In that case, either AN would need to check other flows to see what the prefix is or, if need be the "_fhfhd_" can be retained somewhere in the name to assure uniqueness for object sets. For a more robust solution, let users use more context to build the name. In that case the Object Instancer would need to check when running to see if the name exists and if so throw a "Object name not unique" error.

**Comment by OmarEmaraDev** [comment]
Perhaps you misunderstood me. I am not proposing to name theme manually. Just use an attribute output node after unlinking the instancer node, or simply use a script. For example, given the node tree:

![20200117-214142](https://user-images.githubusercontent.com/25300994/72641224-47b01b00-3972-11ea-8b23-bb559e15f792.png)

After unlinking, I can do:

![20200117-214312](https://user-images.githubusercontent.com/25300994/72641249-5565a080-3972-11ea-822c-49127251a818.png)

You may also store custom attributes in the objects for more advanced setups.

**Comment by kalmdown** [comment]
I guess that is a solution for when the assets won't be used further in AN, but is inefficient if the assets will be updated throughout multiple pipelines. 

I would still prefer the ability to name objects on creation. It's less error-prone, more efficient and more elegant.

**Comment by kalmdown** [comment]
Well I tried the setup above ... but ended up with randomly named objects.

You can see the text list on the right. That was the order of objects in the Collection. As you can see in the collection that order didn't pass through. And the objects are misnamed...as you can see in the 3D view since AS should be selected but MH is the 3D object that is selected.

<img width="2560" alt="Screen Shot 2020-01-17 at 10 38 41 PM" src="https://user-images.githubusercontent.com/2244894/72659822-7c27d500-397a-11ea-8ea0-f9c4b71431e3.png">

**Comment by OmarEmaraDev** [comment]
Ok. We will consider your proposal. But it might take some time. I will get back to you.

**Comment by kalmdown** [comment]
Do you know if it would be quick/easy to fix the issues causing the flow
you proposed to fail? As a short term way to be able to get work done. - K

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
@kalmdown I would just store a custom property on the objects with the required name. Then rename the objects using that custom property after unlinking from the node.

**Comment by kalmdown** [comment]
I assume I use the Object Attribute Output node for that. Manual says if you give it a name it doesn't recognize that it will create one so I entered "rename" in the expression field but AN says "Attribute not found". Also tried converting to text before feeding to the OAO node.

<img width="779" alt="Screen Shot 2020-01-20 at 9 19 14 AM" src="https://user-images.githubusercontent.com/2244894/72746124-329bdd80-3b66-11ea-901b-f2dc0a268a38.png">

**Comment by OmarEmaraDev** [comment]
The relevant parts from the documentation states:

> Custom properties can also be edited using this node by typing `[“Property Name”]` in the expressions field, if there was no such custom property, it will be created.

So you need to enter `["rename"]` instead.

**Comment by OmarEmaraDev** [comment]
Implemented in 4895f74.

You can now rename objects safely.

![20200130-180251](https://user-images.githubusercontent.com/25300994/73473467-817f1980-4395-11ea-827a-86ae98490bc7.png)

Thanks for the suggestion!

**Comment by kalmdown** [comment]
Wow. Thanks so much. Really appreciate it!

Let me know if I can ever help in any way. I'm only beginning to code c#,
don't know much Python but am a senior UX architect if it is ever of use.

- Kar

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
Sure. I will let you know if we ever need anything. Thanks!

**Comment by kalmdown** [comment]
What is the roadmap forward for AN, especially considering Everything Nodes?

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
We don't follow a specific road map. We will do whatever contributors/users want for now.
Everything Nodes probably won't overlap Animation Nodes for a long time. We will add support for Function Nodes in AN once it becomes possible. Other than that, I don't there is anything to consider for now.
