### ISSUE TITLE
Add menu is empty

### ISSUE THREAD

**Issue by kalmdown** [JacquesLucke/animation_nodes#1287]
Only happening for this specific blend doc. I created a new blend doc and all the nodes are there.

MacOS 10.15.2
Blender 2.81.16
AN 2.1.5

<img width="811" alt="Screen Shot 2020-01-17 at 5 22 33 PM" src="https://user-images.githubusercontent.com/2244894/72656159-54227c80-394e-11ea-9758-565199588f4a.png">

**Comment by OmarEmaraDev** [comment]
Is there anything printed on the terminal?

**Comment by kalmdown** [comment]
No. And it isn't happening again on that file. Transient issue...

**Comment by kalmdown** [comment]
Figured out what does it. 

3D Editor Side Panel > Tool > Workspace > Filtering. Turning off Animation Nodes kills all of its menus and panels in all views. Shouldn't do that. I would expect that to only remove the AN tab in the 3D Editor Side Panel but not effect the AN view.

**Comment by OmarEmaraDev** [comment]
It appears a "Workspace" is essentially a window layout with any region/editor. So I think this is the expected behavior of the operator. What do you think?

**Comment by kalmdown** [comment]
I don't think the user expects to lose the functional content of a window
when they think they are hiding tabs in another editor. I assumed filtering
AN would just hide the AN tab in the 3D Editor, not randomly cause AN to
become bizarrely non-functional. It didn't hide the AN editor. It just
broke it. There is no value in this working this way and only issues. If AN
has any control over what gets effected by this filter the result needs to
be understandable, either just the AN tab in the selected Editor gets
hidden, or the whole AN Editor gets hidden or it's menus and windows do not
get affected.

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
But my point is, the purpose of this option doesn't seem to be related to the 3D veiwport, it seems to be related the workspace as a whole. So the current behavior would make more sense, except maybe for the fact that it doesn't hide everything.

The API and the documentation provide zero information on this, so we can't know for sure. But as addon developers, even if we wanted to change the behavior, we can't. This is not something that is exposed to us through the API as far as I know.

**Comment by kalmdown** [comment]
Sorcar menus and panels still work in its editor when filtered out of 3D
Editor:
[image: image.png]

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
Sorry, but I don't really have any resources to figure this out. I will perhaps try to ask the developer responsible for this.

**Comment by OmarEmaraDev** [comment]
It appears the filter is applied globally to all Panels, Menus, Keymaps, and Manipulators. This is described in [D3076](https://developer.blender.org/D3076). So the current behavior is the expected one. So I wouldn't consider this an issue with AN.

**Comment by kalmdown** [comment]
Not sure what about D3076 infers that an Add-on should be broken when
filtered.

Considering that Sorcar acts appropriately I wouldn't say this is expected.
Why is it able to function properly when filtered?
----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
It is not broken, its panels and menus are just not shown.
> This patch supports per-workspace filtering of: Panels, Menus, Keymaps & Manipulators, so a workspace can be set to only show certain add-ons.

Filtering is done automatically on all addons by default by matching against their names. I am guessing Sorcar was just matched incorrectly.
> The tags used for filtering are arbitrary, for now the convention of matching add-on names is used.

**Comment by kalmdown** [comment]
I care about user perception of usability, not whether a tool is
"technically" working correctly but badly designed. There is no value in AN
hiding the contents of the Add menu when the rest of the Editor is active.
For users who do not know the ins and outs of how the framework is
designed, with AN being the only add-on that unexpectedly stopped working,
it looks like an AN defect. So, you can say that its Blender's issue but it
shows on AN and makes AN look bad. A request should be made to Blender to
make the filter feature act more appropriately and AN should do as Sorcar
until that is fixed so that its workspace is not broken when filtered.

Karl
----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
Ok, lets take a step back. As a user, what exactly do you expect to happen when you filter Animation Nodes? And why do you want to filter it?

**Comment by kalmdown** [comment]
I want to remove the panel in the 3D Editor...that's it. I have a lot of
add-ons adding panels there and don't need AN's most of the time. But
during that time I am using AN's editor a lot ... Just not adjusting values
in its panel in the 3D Editor.

The expectation that I have when filtering AN out is just that it's panel
in the 3D Editor would be hidden...but that the AN Editor would be
unaffected.

- Karl

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
Sounds reasonable. I do agree that it doesn't make sense to hide the menus and panels when the editor is still there. But I am still not sure what I am supposed to do as a developer. Can you reach to the Blender developers and get clarifications on this?

**Comment by kalmdown** [comment]
Sure. I can try. Assume you have better connections because you have been
coding in the space. This will be my 1st attempt at more than defect
reporting. Any suggestions as to what forum/chatroom/other would be best?

- Karl

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
I think https://devtalk.blender.org/ is the best channel for thins kind of thing.
