### ISSUE TITLE
How to generate an Invoke Subprogram by python script? And Insert Empty Subprogram also by python script?

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1288]
I am trying to use python script to generate an Invoke Subprogram  by using invokeSubprogram = MyNodeTree.nodes.new("an_InvokeSubprogramNode"). But it is empty no Iterations inputs is generated unless you click the My Loop item and then click OK button. How to do this by python script?
Also how to add ChangeSubprogram by python script rather than by Operator?

**Comment by OmarEmaraDev** [comment]
The invoke node have an attribute `subprogramIdentifier` that you can set. It represents the identifier of the network of the target subprogram. So, for instance, you can do the following:

```python
invokeNode.subprogramIdentifier = inputNode.network.identifier
```

Where `invokeNode` is the invoke node and `inputNode` is the input node of the subprogram.

**Comment by derekcbr** [comment]
Thank you for the reply!

**Comment by OmarEmaraDev** [comment]
Did that work? Should we close this?

**Comment by derekcbr** [comment]
Thanks Omar!
The input node is evalFalloff = ng.nodes.new("an_EvaluateFalloffNode").
Bu this script:invokeSubprogram.subprogramIdentifier=evalFalloff.network.identifier
I got the below errors:
TypeError:bpy_struct:item.attr=val:an_InvokeSubprogramNode.subprogramIdentifier doesnot support None from string types
How to fix this?

**Comment by OmarEmaraDev** [comment]
`evalFalloff` is not part of a subprogram. Right?

**Comment by derekcbr** [comment]
What is inputnode of subprogram? Can you put some scripts of adding and changing subprogram?Thanks!

**Comment by OmarEmaraDev** [comment]
`inputNode` can be any node inside a subprogram. When you add a new node, it will not be connected to any networks, and certainly not subprogram networks. Does that make sense?

**Comment by derekcbr** [comment]
Thanks! Can ChangeSubprogram class only be called by operator?

**Comment by OmarEmaraDev** [comment]
Not sure what you are asking. `ChangeSubprogram` is a class that represents a blender operator, yes.

**Comment by derekcbr** [comment]
After creating a new subprogram, and then add a loop, and click OK button. How to do the above steps by python script? Thanks a lot.

**Comment by OmarEmaraDev** [comment]
What have you tried so far? Where are you stuck exactly?

**Comment by OmarEmaraDev** [comment]
Did the issues you were having get resolved?

**Comment by derekcbr** [comment]
Hi, not really. I found other shadernode and compositornode all can be called by python script. This will save a lot of timing . But it is too difficult for me to figure it out how to use python script to call for subprogram.

**Comment by OmarEmaraDev** [comment]
Can you provide a minimal script the shows the difficulties you are having?

**Comment by derekcbr** [comment]
Hi,
bpy.data.node_groups.new("NodeTree","an_AnimationNodeTree")
    bpy.data.node_groups['NodeTree'].name='MyNodeTree'
    ng = bpy.data.node_groups['MyNodeTree']
    
    separateTextObject = ng.nodes.new("an_SeparateTextObjectNode")
    separateTextObject.location=(-420,280)
    separateTextObject.sourceObjectName=text_obj.name
    separateTextObject.outputType='TEXT'
    #update by manual
    
    groupInput = ng.nodes.new("an_GroupInputNode")
    groupInput.location=(-420,0)
    groupInput.subprogramName='fly in'
    #by manual,also link to objMatrixOutput01
    groupInput.outputs[0].text='Object List'
    
    objectIDKey = ng.nodes.new("an_ObjectIDKeyNode")
    objectIDKey.location=(-160,0)
    #by manual
    #objectIDKey.assignIDKey='b'Transforms * Initial Transforms''    
    #objectIDKey.item='Initial Transforms'    

    invokeSubprogram = ng.nodes.new("an_InvokeSubprogramNode")
    invokeSubprogram.location=(-160,280)
    invokeSubprogram.subprogramIdentifier=groupInput.identifier
    #also by manual,to click the New Subprogram

The above fours nodes, quite difficult for me to use python script, has to click the button on the node interface to get it done!
Thanks!

**Comment by OmarEmaraDev** [comment]
Take a look at the following code:

```python
import bpy

nodeTree = bpy.data.node_groups.new("NodeTree", "an_AnimationNodeTree")

groupInput = nodeTree.nodes.new("an_GroupInputNode")
groupInput.location = (0, 0)
groupInput.newGroupInput("Float")

mathNode = nodeTree.nodes.new("an_FloatMathNode")
mathNode.location = (200, 0)

nodeTree.links.new(mathNode.inputs[0], groupInput.outputs[0])

groupOutput = nodeTree.nodes.new("an_GroupOutputNode")
groupOutput.groupInputIdentifier = groupInput.identifier
groupOutput.location = (360, 0)
groupOutput.newGroupOutput("Float")

nodeTree.links.new(groupOutput.inputs[0], mathNode.outputs[0])

invokeNode = nodeTree.nodes.new("an_InvokeSubprogramNode")
invokeNode.subprogramIdentifier = groupInput.network.identifier
invokeNode.location = (0, 160)
```

It is pretty much self explanatory, but let me know if something isn't clear.

**Comment by derekcbr** [comment]
Thanks a lot! It works well! Very helpful!

**Comment by OmarEmaraDev** [comment]
Good to hear. Did this resolve the issues you were having then? Should we close this?

**Comment by derekcbr** [comment]
Yes please!
