### ISSUE TITLE
Python 3.8 Update and A. Nodes Quickfix

### ISSUE THREAD

**Issue by DoMal27** [JacquesLucke/animation_nodes#1289]
**Quickfix**

System Linux - Python 3.8 - Animation Nodes 2.1.4 - Blender 2.81.16

> The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.) [ [Python 3.8 Changes](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals) ]

**Need update the following files:**
`~/animation_nodes/base_types/node_tree.py`
`~/animation_nodes/utils/timing.py`

Find and Replace All: `time.clock()` to `time.perf_counter()`
 
![Peek 2020-01-18 14-20](https://user-images.githubusercontent.com/20363585/72667725-c605cf00-39fd-11ea-8331-09397b3834e7.gif)

Until now is working as expected!

**Comment by OmarEmaraDev** [comment]
We updated that already in d6684ea. Is it not working as expected?

**Comment by DoMal27** [comment]
Very sorry, I didn't see this.
I'm new in GitHub. :P

I cloned the master, compiled and version 2.1.5 is working properly.
I was compiling from here before: [Daily Builds](https://github.com/JacquesLucke/animation_nodes/releases/tag/daily)

Thanks.
