### ISSUE TITLE
New features and abilities

### ISSUE THREAD

**Issue by EAzari** [JacquesLucke/animation_nodes#1290]
Hi all,

I think [PyFlow](https://github.com/wonderworks-software/PyFlow) has some features and abilities that will improve Animation Nodes [Everything Nodes]

Thoughts?

**Comment by OmarEmaraDev** [comment]
What do you propose we urilize PyFlow for?

**Comment by EAzari** [comment]
I think this features from PyFlow are good you have in Everything Nodes:
- Subgraphs
- Watch what is going on
- Drop on wire
- Photoshop-like history
- Wire styles
- Node deprecation flag
- So on

**Comment by OmarEmaraDev** [comment]
I think you are confusing Everything Nodes with Animation Nodes. They are not really related. If you want to discuss Everything Nodes, you may use [devtalk.blender.org](devtalk.blender.org) instead.

As for Animation Nodes. We already have pretty much everything you mentioned. Please be specific on what your suggestions are.

**Comment by EAzari** [comment]
Thanks, I have to investigate Animation Nodes more

I checked your documentations, so I didn't find some features, maybe should investigate the Animation Nodes and see if it has:
- SubGroups:
![SG](https://user-images.githubusercontent.com/39350101/72692111-5e579d00-3b3f-11ea-8416-4e9fe4d47f71.gif)
- Wire styles:
![WS](https://user-images.githubusercontent.com/39350101/72692212-cd34f600-3b3f-11ea-8fce-4f80eee1816f.gif)
- So on?

**Comment by OmarEmaraDev** [comment]
SubGraphs are called SubPrograms in the documentation. Wires style can be achieved using reroute nodes.
