### ISSUE TITLE
get vertex color layer says no such a color layer

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1292]
![BUG](https://user-images.githubusercontent.com/55994236/72977305-3e73e380-3da2-11ea-889a-b25677d22dc6.png)

win10, blender 2.82.6, AN up to date.
I am confused, or is there other ways that I am supposed to input for this node?

**Comment by OmarEmaraDev** [comment]
There is a hidden option in the *Mesh Object Input* node called *Load Vertex Colors*, it needs to be enabled to use Vertex Colors.
