### ISSUE TITLE
Subtract operator in mix falloff node?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1298]
In "mix falloff" node, there are options like add, multiply (find overlapping), max and min.
But there isn't a subtract operator.... Practically speaking I think it make sens to have ability to cancel the overlapping area between falloff? Also it should be doable?
I wonder if is there any workaround for this currently...
I have to turn my head several time to think about this, like invert falloff and mix again and so on? But I end up confusing myself.
If no such an operator this will be a proposal.

**Comment by OmarEmaraDev** [comment]
Yes, sure. We can add such an option to the *Mix Falloff* node.

**Comment by OmarEmaraDev** [comment]
Implemented in 0fcf9b3. Thanks for the suggestion!
