### ISSUE TITLE
Blender 2.83 crashes when using "search"

### ISSUE THREAD

**Issue by gogobd** [JacquesLucke/animation_nodes#1299]
version: 2.83 (sub 1), branch: master, commit date: 2020-01-28 22:17, hash: b499b24c5452, type: Release
build date: 2020-01-29, 00:03:08
platform: Darwin

ctrl-a search crashes blender with a segfault

I was using todays daily build, maybe it's worth checking.

Animation Nodes is awesome.

**Comment by OmarEmaraDev** [comment]
I am not getting any crashes with `commit date: 2020-01-29 15:26, hash: e3f89237fecc`. Can you wait for the next daily build and try again?

If you still get crashes, can you attach the crash report here?

**Comment by OmarEmaraDev** [comment]
Can you report back on this?

**Comment by OmarEmaraDev** [comment]
Feel free to reopen if you still experience the issue.
