### ISSUE TITLE
find close vertices node bit unexpected

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#130]
https://drive.google.com/file/d/0BzzAoBwXO8dsN0FKVmp2eElLMUE/view?usp=sharing
no big deal, but see the blend, 2 things:
-if I shuffle the vert list the max distance seams not to matter ???
-I still get some connections even with 0 connections 

I will further check in simpler setups, maybe without particles

ps: completely unrelated, related to particles wip maybe:
there is also an "is_exist" prop that matters here for particles, as you can see the texture does not change the alive state

**Comment by JacquesLucke** [comment]
ah yes I see that with the connections. I will fix that

For the shuffle thing a simpler example would be much better. I don't really see whats going on here
I just thinking about turning "Scene Changed" in the performance panel off if the update takes very long automatically

Yeah, the particle nodes aren't finished yet. I will try to give you access to as many properties as possible. I'm still quite annoyed that it crashes too often when I try to render (even more with motion blur turned on)

**Comment by og76** [comment]
Particles are buggy
This example is worse as grid particles are very very buggy. For example turn to blender internal and hit f12 the part will mostly dissappear. Without an nodes same. I managed to make it update these particles once by using anodes to randomly update a useless parameter of part. 

However I keep thinking about some order of operation the grid does, like not generating p in grid but moving to grid. Now where in this line falls the edge node? Is it possible to define the verts to use, than move them and only then generate lines based on what was defined first? 

Speculation but it seams a problem of updating. (Big issue if the part phisics is set to none and that makes no cache. Update is chaos ..)

**Comment by JacquesLucke** [comment]
well said, update is chaos... Maybe its better to improve animation baking etc.

Not sure what you mean or what your questions are exactly..
