### ISSUE TITLE
"Splines from Edges" node does not work properly for mesh having many islands.

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1301]
Hi... :)
The _Spline Per Branch_  option of the _Splines from Edges_ node does not work properly for mesh having many islands,
![Screenshot from 2020-02-01 17-47-04](https://user-images.githubusercontent.com/30294746/73591990-41e23a00-451b-11ea-8445-2910d6f12bfb.png)

[SplineFromBranch1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4142531/SplineFromBranch1.blend.zip)

**Comment by OmarEmaraDev** [comment]
The issue happens to islands with no non-bipolar vertices.

**Comment by OmarEmaraDev** [comment]
Fixed in 4bfa14f. Thanks for the report!

**Comment by 3DSinghVFX** [comment]
Thank you :)
