### ISSUE TITLE
How to  add 'loop through strengths' of Evaluate Falloff by python script and automatically generate a Invoke Subprogram and Loop Input nodes?

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1302]
How to  add 'loop through strengths' of Evaluate Falloff by clicking 'W' and automatically generate a Invoke Subprogram and Loop Input nodes? Is it possible to do this by python script?

    evalFalloff = ng.nodes.new("an_EvaluateFalloffNode")
    evalFalloff.falloffType='Transformation Matrix'
    evalFalloff.useList=True
    evalFalloff.location=(540,-180)
    #by W to add
    print('evalFalloff.network.identifier,',evalFalloff.network.identifier)
    print('evalFalloff.identifier,',evalFalloff.identifier)

    invokeSubprogram = ng.nodes.new("an_InvokeSubprogramNode")
    invokeSubprogram.location=(760,-180)
    AN.tree_info.update()
    #invokeSubprogram.subprogramIdentifier=evalFalloff.network.identifier
    invokeSubprogram.subprogramIdentifier=evalFalloff.identifier

    loopInput = ng.nodes.new("an_LoopInputNode")
    loopInput.location=(260,-360)

**Comment by OmarEmaraDev** [comment]
What exactly is the issue you are facing?

**Comment by derekcbr** [comment]
After adding a new EvaluateFalloffNode, and then click 'W' and it will generate a context pie(consisting of Data Input,Viewer and Loop through 'Strengths'), and when clicking the Loop through 'Strengths', it will automatically generate a InvokeSubprogramNode and a LoopInputNode. How to do this by python script? Thanks!

**Comment by OmarEmaraDev** [comment]
Here is the source code for the operator:

https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/operators/node_creators/insert_loop_for_iteration.py

**Comment by derekcbr** [comment]
Hi, 
I tied to use the below from the operator,but it does not work.
    evalFalloff = ng.nodes.new("an_EvaluateFalloffNode")
    evalFalloff.falloffType='Transformation Matrix'
    evalFalloff.useList=True
    evalFalloff.location=(540,-180)
    #by W to add
    print('evalFalloff.network.identifier,',evalFalloff.network.identifier)
    print('evalFalloff.identifier,',evalFalloff.identifier)
    
        

    loopInput = ng.nodes.new("an_LoopInputNode")
    loopInput.location=(260,-360)
    
    sourceNode = AN.tree_info.getNodeByIdentifier(evalFalloff.identifier)
    for key in sourceNode.outputs:
        print(key)
    #socket = sourceNode.outputs[evalFalloff.socketIndex]
    #evalFalloff.insert()



    invokeSubprogram = ng.nodes.new("an_InvokeSubprogramNode")
    invokeSubprogram.location=(760,-180)
    AN.tree_info.update()
    #invokeSubprogram.subprogramIdentifier=evalFalloff.network.identifier
    invokeSubprogram.subprogramIdentifier=loopInput.identifier

I get stuck with the sourceNode parameter which identifier shall I put, as well as the socket's outputs parameter(how to get socketIndex)?
Thanks!

**Comment by OmarEmaraDev** [comment]
See the following example:

```python
import bpy
import animation_nodes as AN

nodeTree = bpy.data.node_groups["NodeTree"]

evalFalloff = nodeTree.nodes.new("an_EvaluateFalloffNode")
evalFalloff.falloffType = "Transformation Matrix"
evalFalloff.useList = True
evalFalloff.location = (0, 140)

loopInput = nodeTree.nodes.new("an_LoopInputNode")
loopInput.location = (0, 0)
loopInput.newIterator("Float List")

invokeNode = nodeTree.nodes.new("an_InvokeSubprogramNode")
AN.tree_info.update()
invokeNode.subprogramIdentifier = loopInput.network.identifier
invokeNode.location = (200, 140)

nodeTree.links.new(invokeNode.inputs[0], evalFalloff.outputs[0])
```

Notice that `invokeSubprogram.subprogramIdentifier` should be the identifier of the **network** of the the loop.

**Comment by derekcbr** [comment]
Thanks!

**Comment by OmarEmaraDev** [comment]
Does that resolve the issues you were having?

**Comment by derekcbr** [comment]
Yes very helpful！
