### ISSUE TITLE
Allow more socket types for input based caching

### ISSUE THREAD

**Issue by ogierm** [JacquesLucke/animation_nodes#1303]
# Problem
Right now only a handful of socket types are marked as comparable, which hinders the caching mechanism for loops.
I'd suggest that instead of comparability, equality should be checked. (Which would require adding that property).

Unrelated, the Vector socket could become comparable (compare the length)

# Why should this be changed
When using caching you can often have your node tree set to `evaluate always` and still have an interactive scene.

# Workaround
Convert the data into something that is comparable (in case of vectors for example into 3 floats), and then convert them back inside the loop. Unfortunately that won't really work for lists

**Comment by OmarEmaraDev** [comment]
Can you provide a practical instance of the problem? As far as I know, this should be related to the storability of types as opposed to their comparability.

**Comment by ogierm** [comment]
The vector socket for example doesn't work with caching.

**Comment by OmarEmaraDev** [comment]
I see, I thought you were talking about the outputs. Let me take a look.

**Comment by OmarEmaraDev** [comment]
Implemented in 5e049b8.

**Comment by ogierm** [comment]
Hmm, that doesn't seem to have solved the problem.

_Example:_
![image](https://user-images.githubusercontent.com/29630575/73664823-58fe6480-46a0-11ea-948e-c391b1b21f08.png)

**Comment by OmarEmaraDev** [comment]
Seems to be working fine here. Did you install the daily build?

**Comment by ogierm** [comment]
Oooops, I forgot to build after pulling. My bad!
