### ISSUE TITLE
Add a trigger for mesh manipulation

### ISSUE THREAD

**Issue by ogierm** [JacquesLucke/animation_nodes#1304]
I'd like my node tree to only update, when I update the geomety of a specific object.
I tried setting `data` as the trigger property, but that didn't really work.

**Comment by OmarEmaraDev** [comment]
While it is possible, I would be very concerned about the implications of this on performance. I will try to test it and get back to you.

**Comment by OmarEmaraDev** [comment]
Oh, and another important thing to note. Mesh data will only be updated when you go to Object mode. So executing the node tree on mesh manipulation seems practically useless. What do you think?

**Comment by ogierm** [comment]
I agree, that wouldn't be too helpful for interactive use cases.

Maybe there is some kind of event or so that is fired whenever any operation like extrude or translate has been done?

**Comment by OmarEmaraDev** [comment]
Blender doesn't report those kind of events unfortunately. And even then, those operators only work in edit mode, so you also can't get anything practical from this execution.

**Comment by OmarEmaraDev** [comment]
In terms of performance impact, for a mesh with 1000 vertices, the trigger preparation time is 3 milliseconds. Which is significant, since this always run, meaning Blender will be slower in general, not just AN.

In conclusion, I don't think this will be implemented. It will slow down everything for no practical value. What do you think?

**Comment by OmarEmaraDev** [comment]
@ogierm Are you satisfied with the reached conclusion?

**Comment by ogierm** [comment]
Ah, forgot to come back, sorry.
I think I saw somewhere that there is a callback for when you move in an out of edit mode. Maybe that could work? Though that sounds rather niche tbf.

I can't say I'm satisfied, but if it's not realistic, then I guess that's fine

**Comment by OmarEmaraDev** [comment]
I will close this for now. But I will keep that in mind if a solution appears.
