### ISSUE TITLE
 Increasing the amount of decimals / significant digits shown in the nodes

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1305]
Is there a way to increase the amount of decimals / significant digits shown in the nodes?  I type in .003 but 0.00 is shown.

[http://i.imgur.com/gfJRM38.png](url)

![gfJRM38](https://user-images.githubusercontent.com/28985314/73639585-ae078f80-463a-11ea-958f-5e95102f6c7f.png)

**Comment by OmarEmaraDev** [comment]
This is just a display thing, the actual value you typed is retained.

![20200203-111844](https://user-images.githubusercontent.com/25300994/73640314-af56ad80-4676-11ea-91a5-b0e32e274c33.png)

**Comment by stillpointx** [comment]
But can we change the node to show it without adding another viewer node?

**Comment by OmarEmaraDev** [comment]
We can show up to 6 digits I think. But the question is if we should. It looks like this:

![20200203-125218](https://user-images.githubusercontent.com/25300994/73647226-bb953780-4683-11ea-9eca-40ad039bd2e9.png)

**Comment by stillpointx** [comment]
If it doesn't break something why not give the user the option? Default could be two decimal places and an option to use more.  I'm using it to animate strange attractors / chaos theory stuff which the smallest change has large effects even 0.0031 effects things drastically over time

**Comment by OmarEmaraDev** [comment]
Implemented in 6d8aba6.

**Comment by stillpointx** [comment]
Thanks! :-)

**Comment by OmarEmaraDev** [comment]
I am sorry, but we had to revert this commit as we don't believe it is a good solution. However, we are exploring alternatives and we will hopefully reach a satisfactory solution.

**Comment by stillpointx** [comment]
Thanks for the update.
