### ISSUE TITLE
Boolean List is not existed anymore in 2.1?What is the substitute node?

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1306]

**Comment by OmarEmaraDev** [comment]
Boolean List still exist. What is the issue you are having?

**Comment by derekcbr** [comment]
How to add a Boolean List? Can not find it by search!Is it a BooleanCreateList?

**Comment by OmarEmaraDev** [comment]
It is called *Create Boolean List* node.

**Comment by derekcbr** [comment]
Thanks! How to make the Invokesubprogram node’s output as Boolean List?

**Comment by OmarEmaraDev** [comment]
See:
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html#generators

**Comment by derekcbr** [comment]
Thanks!
Based on your previous coding:
import bpy
import animation_nodes as AN

nodeTree = bpy.data.node_groups["NodeTree"]

evalFalloff = nodeTree.nodes.new("an_EvaluateFalloffNode")
evalFalloff.falloffType = "Transformation Matrix"
evalFalloff.useList = True
evalFalloff.location = (0, 140)

loopInput = nodeTree.nodes.new("an_LoopInputNode")
loopInput.location = (0, 0)
loopInput.newIterator("Float List")

invokeNode = nodeTree.nodes.new("an_InvokeSubprogramNode")
AN.tree_info.update()
invokeNode.subprogramIdentifier = loopInput.network.identifier
invokeNode.location = (200, 140)

nodeTree.links.new(invokeNode.inputs[0], evalFalloff.outputs[0])

I wants to add loopGeneratorOutput for Boolean List,both below do not work. Please clarify!
1.
    loopGeneratorOutput =loopInput.createGeneratorOutputNode("Boolean")
    loopGeneratorOutput.location=(980,-360)
 2.
    loopGeneratorOutput = ng.nodes.new("an_LoopGeneratorOutputNode")
    loopGeneratorOutput.location=(980,-360)
    loopGeneratorOutput.identifier=loopInput.network.identifier
Thanks

**Comment by OmarEmaraDev** [comment]
Please just look at the code in Animation Nodes. Most of this stuff is intuitive enough.
```python
import bpy
import animation_nodes as AN

nodeTree = bpy.data.node_groups["NodeTree"]

evalFalloff = nodeTree.nodes.new("an_EvaluateFalloffNode")
evalFalloff.falloffType = "Transformation Matrix"
evalFalloff.useList = True
evalFalloff.location = (0, 140)

loopInput = nodeTree.nodes.new("an_LoopInputNode")
loopInput.location = (0, 0)
loopInput.newIterator("Float List")

invokeNode = nodeTree.nodes.new("an_InvokeSubprogramNode")
AN.tree_info.update()
invokeNode.subprogramIdentifier = loopInput.network.identifier
invokeNode.location = (200, 140)

nodeTree.links.new(invokeNode.inputs[0], evalFalloff.outputs[0])

loopGenerator = nodeTree.nodes.new("an_LoopGeneratorOutputNode")
loopGenerator.location = (500, 0)
loopGenerator.loopInputIdentifier = loopInput.identifier
loopGenerator.listDataType = "Boolean List"
```

**Comment by derekcbr** [comment]
Thanks! Also how can invokeNode’s output be updated to Boolean list as well?

**Comment by OmarEmaraDev** [comment]
It will update automatically.

**Comment by derekcbr** [comment]
Thanks!
In my case, if by python script, it will not update automatically.
    def createGeneratorOutputNode(self, dataType):
        node = newNodeAtCursor("an_LoopGeneratorOutputNode")
        node.loopInputIdentifier = self.identifier
        node.listDataType = dataType
        node.outputName = dataType
        invokeTranslation()
        subprogramInterfaceChanged()

If the last two functions were not called, then it will not be updated automatically.

**Comment by OmarEmaraDev** [comment]
Just create the generator before adding the invoke node then.

**Comment by derekcbr** [comment]
Thanks a lot! It works.
