### ISSUE TITLE
Manipulating Meshes bug

### ISSUE THREAD

**Issue by yousifucv** [JacquesLucke/animation_nodes#131]
This is in relation to the "First try to manipulate meshes - Animation Nodes Addon" video on Youtube.
You provide a basic setup for it "http://imgur.com/2hOqwVj" in the comments.
But this actually doesn't work. The Scale Matrix seems to be applied again and again and the model grows infinitely.

**Comment by og76** [comment]
are the source and target objects the same? should not. just guessing here, better provide a blend to see

**Comment by yousifucv** [comment]
Ah. Sorry! You are right. Didn't notice that difference! Thanks!
