### ISSUE TITLE
DLL Error in Blender 2.8+

### ISSUE THREAD

**Issue by AntsoftheSky** [JacquesLucke/animation_nodes#1311]
Not a top notch programmer here, just an artist. Recently tried using AN with 2.8 and 2.81b but have been getting this error (Image Attached). Too much to type and I'm not sure exactly what's wrong.

What's the fix for this? Did I just install this wrong or is it something deeper?

It does work on 2.79 so I'm a bit confused. Thanks.

Here istheimage-- https://i.stack.imgur.com/PjvQj.jpg

**Comment by 3DSinghVFX** [comment]
If you did not install the _vc_redist.x64_ then please install it from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2).

**Comment by OmarEmaraDev** [comment]
See #1240 if you still have issues.
