### ISSUE TITLE
Interporlate from curve node doesn´t work on loops

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#1312]
I have made a loop and I wanted to use the interpolation from curve node in order to modulate scale of objects. But the loop just gets freezed when I plug this node.

https://drive.google.com/open?id=1LoIYKgHPICsCc-B0zdZlVMHK79vlOPLF

**Comment by OmarEmaraDev** [comment]
*Freezed* as in Blender hangs?

**Comment by YorsLosilla** [comment]
Not really @OmarEmaraDev  execution is still playing but the interpolations give unexecpected results almost close to 0 for all values when it should be evenly distributed between the min and max according to input curve.

What it´s sure it´s that this only happens when you plug a custom curve. When you use the manipulators for the standar curves (linear, circular ,etc...) the loops works. I have also tested this other files. It´s seems to be a common issue for 2.15 and above

**Comment by OmarEmaraDev** [comment]
Notice that Blender changed the python API, and we updated the Interpolation From Curve node accordingly. So please try the latest daily build from Blender and see if things work as expected.

**Comment by OmarEmaraDev** [comment]
Can you report back on this?

**Comment by OmarEmaraDev** [comment]
I will close this for now. Feel free to reopen if you still experience the issue.
