### ISSUE TITLE
Object mesh data won't read modifier once disabled in viewport, render / collection

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1318]
Some times I use mesh(es) A(s) to generate a single mesh B, and I don't want mesh A to appear in the viewport. 
So I have to "hide it". Interestingly, even blender itself confuses the term "hide in viewport" (eye icon) and "disable in viewport" (screen icon). Regardlessly, once being disabled, object mesh data node can't read modifier. Currently I am using a workaround to "render in the viewport", in which "eye-icon" is used to hide these original meshes. I don't know if there is a way for node to keep accessing these data even if they are disabled? It will be really helpful.

**Comment by OmarEmaraDev** [comment]
I believe this is a limitation imposed by Blender. Blender won't evaluate modifiers in this case, so we can't access the evaluated data. I will confirm that and get back to you.

**Comment by OmarEmaraDev** [comment]
Yes, seems to be the case. I don't think there is anything we can do here.
