### ISSUE TITLE
Mesh Info vertices come in reversed order on some objects

### ISSUE THREAD

**Issue by CustomPhase** [JacquesLucke/animation_nodes#1321]
Im trying to make triangles (which are all separate objects) that dont face the camera directly smaller, but as you can see, on **some** triangles i get the opposite result.

![image](https://user-images.githubusercontent.com/10864826/74595951-03e02c80-506a-11ea-90cc-20e2cf7c7c31.png)

Heres the node setup im using:

![image](https://user-images.githubusercontent.com/10864826/74595953-15293900-506a-11ea-9b29-c4721a6389e7.png)

I tried using Point List Normal instead, but it gives exactly the same result.
Also the facing on all these objects is correct, no inverted normals or anything like that, i know that cause i cull backfaces in the material.

**Comment by OmarEmaraDev** [comment]
Why aren't you using Polygon Normals from the Mesh Info node?
Cross product is not order invariant, so I would say the result is as expected.

**Comment by CustomPhase** [comment]
> Why aren't you using Polygon Normals from the Mesh Info node?

Oh. Didnt notice that for some reason. Yeah that solved it. 

Also i just understood that it was my own mistake, i should have been using polygon indices. Closing the issue.
