### ISSUE TITLE
Instancing multiple objects easily without the link in vertex color and so on

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1326]
I wish to instance multiple objects in a grid. There are multiple ways to do so.
including instancing a singe type of object in the grid, and then use "copy object data" node to put other objects into the place.
However, although the transform is not linked to the object, the vertex color is linked to the object.
Even if my falloff doesn't touch the other instances, the linked mesh may all appear to have the same vertex color.
There maybe some complicate workaround to solve the problem, but Is there any way to improve the node to help instance multiple objects while retaining ability to manipulate each of them individually?
![copy object data](https://user-images.githubusercontent.com/55994236/74675712-1cdc0100-5182-11ea-935a-62a651787678.png)

**Comment by OmarEmaraDev** [comment]
Can you elaborate? Do you want a deep copy of the meshes?

**Comment by Gerstmann-Bradley** [comment]
> Can you elaborate? Do you want a deep copy of the meshes?

I suppose "deep copy" is the right term in this circumstance, in which each object will be independent to the original, right? and it seems "copy object data" node currently can't achieve this function in this case.

**Comment by OmarEmaraDev** [comment]
I see. So you basically want a Deep Copy option in the Copy Object Data node.

**Comment by Gerstmann-Bradley** [comment]
> I see. So you basically want a Deep Copy option in the Copy Object Data node.

Correct

**Comment by OmarEmaraDev** [comment]
Implemented in e02818c.

However, if the objects will have solid colors, just use the Object Color attribute.
