### ISSUE TITLE
Object Transforms Input Missing "frame" option

### ISSUE THREAD

**Issue by prophet067** [JacquesLucke/animation_nodes#1329]
Unable to locate "frames" option in advanced node settings per the user manual:

https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/object/object_transforms_input.html

The only option present in advanced node settings is: create execution trigger

**Comment by OmarEmaraDev** [comment]
Unfortunately, this option is no longer available in v2.1.

**Comment by Slexis-Works** [comment]
Aw can we know why? I don't see patch notes yet but it seemed so useful

**Comment by OmarEmaraDev** [comment]
@Slexis-Works It was removed on the hope that a better alternative will be available later. I believe the new Actions system might be an alternative here.

**Comment by enzyme69** [comment]
@OmarEmaraDev 

The documentation needs to be updated. I have been getting question on why the "advanced settings" is removed :(
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/object/object_transforms_input.html
