### ISSUE TITLE
Adaptive sampling of curve

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1330]
Hi...
Current curve sampling has two methods _Uniform_ and _Resolution_. The _Resolution_ method respects the curve handles but not the slope of the curve.
![curve2](https://user-images.githubusercontent.com/30294746/75017655-7bbbb600-54b3-11ea-8d54-a4ee8c2d7b35.png)

It would be nice if we have _Adaptive_ method which respects the curve slope,
![Screenshot from 2020-02-21 14-10-56](https://user-images.githubusercontent.com/30294746/75017914-03a1c000-54b4-11ea-918e-eac23aa1daf6.png)

**Comment by OmarEmaraDev** [comment]
Implemented in def0593. Let me know if it works as intended.

**Comment by 3DSinghVFX** [comment]
> Implemented in [def0593](https://github.com/JacquesLucke/animation_nodes/commit/def0593cc1e1b295e03a5aa2b54ec587d33a6dca). Let me know if it works as intended.

Thanks for implementing this node. It works but sometimes gives unexpected results, maybe I'm doing something wrong,
![Screenshot from 2020-09-04 00-10-26](https://user-images.githubusercontent.com/30294746/92154408-61d83400-ee43-11ea-9777-b06be6953e25.png)

**Comment by OmarEmaraDev** [comment]
Reducing the Max Step should solve this. (A value between 0 and 1)

**Comment by harisreedhar** [comment]
Hi please check `Parameters` output which is currently `FloatList` not `DoubleList`

**Comment by JacquesLucke** [comment]
I think the inner workings of the node might need a bit more careful design. Ideally the output points should should be symmetric in the case @3DSinghVFX shows.
Also, can the be part of the Evaluate Spline node?

**Comment by OmarEmaraDev** [comment]
I did try to incorporate it into the Evaluate node, but the evaluation is not parameterized as in the case of Resolution and Uniform parameterization. Not sure if we can do something like uniform conversion, I will take a look.

 For symmetry, a solution might be double sided integration, can you try this @3DSinghVFX?

```diff
diff --git a/animation_nodes/data_structures/splines/bezier_spline.pyx b/animation_nodes/data_structures/splines/bezier_spline.pyx
index 8b092f37..89bb0307 100644
--- a/animation_nodes/data_structures/splines/bezier_spline.pyx
+++ b/animation_nodes/data_structures/splines/bezier_spline.pyx
@@ -324,20 +324,25 @@ cdef class BezierSpline(Spline):

     @cython.cdivision(True)
     def getAdaptiveParameters(self, float stepMultiplier, float maxStep):
+        cdef float startParameter, endParameter, startRadius, endRadius
         cdef FloatList parameters = FloatList()
         cdef int amount = getSegmentAmount(self)
         cdef float step = 1.0 / amount
-        cdef float parameter, radius
         cdef Vector3* w[4]
         cdef Py_ssize_t i
         for i in range(amount):
-            parameter = 0.0
+            startParameter = 0.0
+            endParameter = 1.0
             getSegmentData_Index(self, i, w)
-            while parameter < 1.0:
-                parameters.append_LowLevel(step * (parameter + i))
-                radius = 1.0 / max(evaluateBezierSegment_Curvature(parameter, w), 1e-5)
-                parameter += min(radius * stepMultiplier, maxStep)
-        parameters.append_LowLevel(1)
+            while startParameter < endParameter:
+                parameters.append_LowLevel(step * (startParameter + i))
+                if endParameter != 1:
+                    parameters.append_LowLevel(step * (endParameter + i))
+                startRadius = 1.0 / max(evaluateBezierSegment_Curvature(startParameter, w), 1e-5)
+                endRadius = 1.0 / max(evaluateBezierSegment_Curvature(endParameter, w), 1e-5)
+                startParameter += min(startRadius * stepMultiplier, maxStep)
+                endParameter -= min(endRadius * stepMultiplier, maxStep)
+        parameters.append_LowLevel(1.0)
         return parameters


```
Note: No linear order in the above diff.

**Comment by 3DSinghVFX** [comment]
> I did try to incorporate it into the Evaluate node, but the evaluation is not parameterized as in the case of Resolution and Uniform parameterization. Not sure if we can do something like uniform conversion, I will take a look.
> 
> For symmetry, a solution might be double sided integration, can you try this @3DSinghVFX?
> 
> ```diff
> diff --git a/animation_nodes/data_structures/splines/bezier_spline.pyx b/animation_nodes/data_structures/splines/bezier_spline.pyx
> index 8b092f37..89bb0307 100644
> --- a/animation_nodes/data_structures/splines/bezier_spline.pyx
> +++ b/animation_nodes/data_structures/splines/bezier_spline.pyx
> @@ -324,20 +324,25 @@ cdef class BezierSpline(Spline):
> 
>      @cython.cdivision(True)
>      def getAdaptiveParameters(self, float stepMultiplier, float maxStep):
> +        cdef float startParameter, endParameter, startRadius, endRadius
>          cdef FloatList parameters = FloatList()
>          cdef int amount = getSegmentAmount(self)
>          cdef float step = 1.0 / amount
> -        cdef float parameter, radius
>          cdef Vector3* w[4]
>          cdef Py_ssize_t i
>          for i in range(amount):
> -            parameter = 0.0
> +            startParameter = 0.0
> +            endParameter = 1.0
>              getSegmentData_Index(self, i, w)
> -            while parameter < 1.0:
> -                parameters.append_LowLevel(step * (parameter + i))
> -                radius = 1.0 / max(evaluateBezierSegment_Curvature(parameter, w), 1e-5)
> -                parameter += min(radius * stepMultiplier, maxStep)
> -        parameters.append_LowLevel(1)
> +            while startParameter < endParameter:
> +                parameters.append_LowLevel(step * (startParameter + i))
> +                if endParameter != 1:
> +                    parameters.append_LowLevel(step * (endParameter + i))
> +                startRadius = 1.0 / max(evaluateBezierSegment_Curvature(startParameter, w), 1e-5)
> +                endRadius = 1.0 / max(evaluateBezierSegment_Curvature(endParameter, w), 1e-5)
> +                startParameter += min(startRadius * stepMultiplier, maxStep)
> +                endParameter -= min(endRadius * stepMultiplier, maxStep)
> +        parameters.append_LowLevel(1.0)
>          return parameters
> ```
> 
> Note: No linear order in the above diff.

Omar, It is better now,
![Screenshot from 2020-09-04 19-12-25](https://user-images.githubusercontent.com/30294746/92246029-d31af400-eee2-11ea-8fda-c79bf0fd3f31.png)

But sometimes points bunch together
![Screenshot from 2020-09-04 19-22-06](https://user-images.githubusercontent.com/30294746/92246845-f6926e80-eee3-11ea-8479-9a2398ab445f.png)

and these points are not sorted
![Screenshot from 2020-09-04 19-17-45](https://user-images.githubusercontent.com/30294746/92247344-bc759c80-eee4-11ea-8a7e-32ebb8222ff2.png)

**Comment by JacquesLucke** [comment]
I think it is ok when the set of inputs for the Evaluate Spline node changes when type is set to Adaptive/Curvature. Having a "Detail" input instead of "Amount" is fine.

**Comment by OmarEmaraDev** [comment]
@JacquesLucke Alright.Now that I looked at the masking approach above, I wonder if it is better than the integration approach. The way I see it, integration is less stable but more flexible, though I suspect its flexibility is not really needed. Masking is also sufficiently simple that we may even leave it to the user. What do you think?

**Comment by 3DSinghVFX** [comment]
> Don't worry about the order for now.
> If you would like a per-point-curvature sampling, masking a resolution sampling is probably the best approach.
> 
> ![20200904-163123](https://user-images.githubusercontent.com/25300994/92250362-a90a0780-eecb-11ea-8873-0e3c3cd6e3e0.png)

Yes, this exactly what I want.

**Comment by JacquesLucke** [comment]
First using the resolution and then removing points is fine. I'm not sure whether masking only based on the local curvature is good enough or whether something like decimation works better. 
For decimation you'd have to go over all points and find the one point that adds the least information (is the closest to the straight line between the neighboring points). Then remove that point and search for the next point. This might give better results, but is also harder to implement.

Maybe this kind of decimation could even be a separate node, than no new mode in the Evaluate Spline node would be needed.

**Comment by 3DSinghVFX** [comment]
This paper may help for *Adaptive Sampling of Parametric Curves* http://ariel.chronotext.org/dd/defigueiredo93adaptive.pdf

**Comment by OmarEmaraDev** [comment]
@3DSinghVFX I already tried an implementation of the paper that you linked. You can see my implementation [here](https://github.com/JacquesLucke/animation_nodes/commit/def0593cc1e1b295e03a5aa2b54ec587d33a6dca#diff-09b21829b2695f9b30e048fbcdc574b3L44-L86). However, it didn't give good results at all, and it was recursive. Not sure if we can make it iterative. So I quickly abandoned it in favor of the other approachs.

@JacquesLucke I did try this decimate approach as well. It gave similar results to the masking approach. So I don't think it is particularly advantageous.

**Comment by 3DSinghVFX** [comment]
> @3DSinghVFX I already tried an implementation of the paper that you linked. You can see my implementation [here](https://github.com/JacquesLucke/animation_nodes/commit/def0593cc1e1b295e03a5aa2b54ec587d33a6dca#diff-09b21829b2695f9b30e048fbcdc574b3L44-L86). However, it didn't give good results at all, and it was recursive. Not sure if we can make it iterative. So I quickly abandoned it in favor of the other approachs.
> 

Okay.

**Comment by OmarEmaraDev** [comment]
I think the solutions we provided here are already satisfactory. If Kuldeep would like to propose another implementation, feel free to open a pull request.

**Comment by Gerstmann-Bradley** [comment]
Hi, I wondered why the version including this node has been reverted. Now AN doesn't include this node anywhere.
Would Omar provide me any information about the reason and future plan?

**Comment by OmarEmaraDev** [comment]
We tried four different methods for doing adaptive sampling. Some were better than others but they all suffered from some issues. I would consider this again if a better implementation came along, anybody is welcome to try that. In the mean time, the curvature masking method described in https://github.com/JacquesLucke/animation_nodes/issues/1330#issuecomment-687180527 can be used.

**Comment by Gerstmann-Bradley** [comment]
I see, thanks for the respond.
