### ISSUE TITLE
Removing scene Animation Nodes is pointing to crashes Blender

### ISSUE THREAD

**Issue by kalmdown** [JacquesLucke/animation_nodes#1336]
System Information
Operating system: Mac OSX 10.14.6
Graphics card: Radeon Pro 455 2GB

Blender Version
Broken: (example: 2.80, edbf15d3c044, master, 2018-11-28, as found on the splash screen)
Version 2.83 (2.83 2020-02-21)

Worked: (optional)

Short description of error
Deleting Scene.003 via the Scene controls at top of the window or in Animation Nodes crashes Blender
Exact steps for others to reproduce the error

Load the file "Exp20_Insights_4_Data"
[Exp20_Insights_4_Data.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4242882/Exp20_Insights_4_Data.blend.zip)

a) Try to Delete scene "Scene.003" here.
![image](https://user-images.githubusercontent.com/2244894/75124559-e6f8ba00-5664-11ea-8872-0e981711a209.png)

b) Or here:
![image](https://user-images.githubusercontent.com/2244894/75124562-ecee9b00-5664-11ea-8dfb-0984a8e5b01e.png)

c) Or switch scene in AN Scene field.

Originally reported to Blender Dev but they said...

> Thanks for the report.
> 
> I can confirm for you that it does crash with the message of:
> 
> Memoryblock makebevelcurve: end corrupt
> Memoryblock makebevelcurve: end corrupt
> However, this addon is not maintained by Blender.
> 
> Please report the issue at:
> 
> https://github.com/JacquesLucke/animation_nodes/issues

**Comment by OmarEmaraDev** [comment]
I can't replicate the issue. Can you try to reproduce it with a minimal setup?

**Comment by kalmdown** [comment]
More minimal in what way? - K

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
I mean with as less nodes/data as possible. Also, can you attach the crash log?

**Comment by kalmdown** [comment]
I've tried to minimize it but then it stops crashing...

Here MacOS's crash report.
[AN Scene Deletion Crash.txt](https://github.com/JacquesLucke/animation_nodes/files/4264378/AN.Scene.Deletion.Crash.txt)
