### ISSUE TITLE
Is there a way to put AN instances into specific collections?

### ISSUE THREAD

**Issue by kalmdown** [JacquesLucke/animation_nodes#1341]
I am making a lot of sets of things that then get pushed to Unity. Would be nice if, on creation, they where created in a Collection. Then I wouldn't need to move them after creating them every time I need to regenerate the objects.

**Comment by OmarEmaraDev** [comment]
You can use the Collection Operations node to remove or add objects to a collection as needed.

**Comment by karlisstigis** [comment]
Actually I have the same question. Collection operations allows to "link" objects into other collections, but it's not the same as being in it. The problem arises when you change instance count, more precisely, make the count smaller. Blender does not understand, that the objects have been deleted and somehow still stores them, because they're linked and that can result in thousands of objects.  This does not happen instances are generated inside AN collection, so I think this is the problem.

**Comment by OmarEmaraDev** [comment]
I see. Good point. What are you proposing? Should we remove the objects event if they are used by Blender outside of Animation Nodes?

**Comment by kalmdown** [comment]
I was hoping that there was a nodes to create or put AN instances in the
Collection you want them to end up in - something like a Collection input
on the Object Instance node.

Does AN get special control of the Animation Nodes Object Container or
could AN create objects in other collections easily?

- Karl

----------
Karl Mochel
Interaction, Interface, Information, Experience Design
linkedin.com/in/kalmdown
<https://www.linkedin.com/in/kalmdown?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BpyZvd%2BHjSLSo3xELyIygSw%3D%3D>

**Comment by OmarEmaraDev** [comment]
Animation Nodes merely creates the `Animation Nodes Object Container`, there is nothing special about it. As I said, you may move the objects to other collections (Or remove them from certain collections) using the *Collection Operations* node.

**Comment by Gerstmann-Bradley** [comment]
> I see. Good point. What are you proposing? Should we remove the objects event if they are used by Blender outside of Animation Nodes?

I think I will be satisfied if this is the way to go. As long as the collection operation can follow the change in instances numbers/object identity and so on, I will be happy with that. I don't know if the current proposal will cause other problems or not, but I have to see it to know what I want and how to improve that.

**Comment by OmarEmaraDev** [comment]
Implemented in 33a578c. Let me know if this is satisfactory for everyone.

**Comment by Gerstmann-Bradley** [comment]
> Implemented in [33a578c](https://github.com/JacquesLucke/animation_nodes/commit/33a578c726297ae582ddd61daf790bf65076a0c4). Let me know if this is satisfactory for everyone.

I have tested it earlier, Personally I am pretty happy with that.
The update solves the earlier issue of extra instances. and with this node it can easily hide a specific group of instances in AN by disabling collection in the outliner.

**Comment by OmarEmaraDev** [comment]
Good to hear. I will close this for now, feel free to reopen if needed.

**Comment by RoN43** [comment]
If you use Collection operations node instances just copy to specific collection and stay in main. than you cannt delete instaces from main collection.

**Comment by brothermechanic** [comment]
@OmarEmaraDev , hello, thank you for developing great addon!
tell me, is this a bug
![Screenshot_20200910_200512](https://user-images.githubusercontent.com/3109995/92768846-eec14700-f387-11ea-964b-ecd02b9fde34.jpg)
All instances go to NEW collection but Animation Nodes Object Container already is and still contain instaces
I think all instaces must move (not link) to NEW collection
What do tou think?

**Comment by OmarEmaraDev** [comment]
@brothermechanic This is not really a bug. Objects can be linked to multiple collections. If you don't want them to be linked to the Animation Nodes Object Container, you can disable it from the Advanced Node Settings of the Instancer node.

**Comment by gerroon** [comment]
Thanks for implementing this.

When I untick "linked" it does not remove instances from the AN container and put the defined container in the node. Is this a bug?  See the image please

https://i.imgur.com/kyeQFYc.png

**Comment by Gerstmann-Bradley** [comment]
> Thanks for implementing this.
> 
> When I untick "linked" it does not remove instances from the AN container and put the defined container in the node. Is this a bug? Basically the defined one gets empty. The "linked" option seems to be working on the other hand.
> 
> See the image please
> 
> https://i.imgur.com/kyeQFYc.png

my understanding: 
object will always be instanced in AN container regardlessly.
If you untick, then object will just be produced in AN container as if you haven't used node.
If you tick (as by default), object will be put into a new container, but at same time there will be a linked copy in AN container.
Be aware, that you don't actually double the amount of objects in total/in the scene. It's just the same object presenting in two collections at the same time.
You can disable AN container, and the object will still be visible if you don't disable the target collection; vice versa.
