### ISSUE TITLE
Separate Polygon - Combine Mesh has bug

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#1343]
Not sure exactly what causing this error: 

<img width="1156" alt="Screen Shot 2020-02-29 at 10 53 13 pm" src="https://user-images.githubusercontent.com/3952687/75606947-61827780-5b46-11ea-8991-e5623337fc0f.png">

[AN_separate_polygon_003.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4270237/AN_separate_polygon_003.blend.zip)

**Comment by OmarEmaraDev** [comment]
You need to explicitly pass the edge indices. In this case, you may use the *Edges Of Polygons* node to compute the edges.

**Comment by enzyme69** [comment]
@OmarEmaraDev hmm so this example does not work:
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/mesh/separate_polygons.html

**Comment by enzyme69** [comment]
What's Edges of Polygons node? No such thing I am aware of.

**Comment by OmarEmaraDev** [comment]
This is the documentation for v2.0. Things changed in v2.1, now you always need to input the edge indices.

![20200229-140217](https://user-images.githubusercontent.com/25300994/75607041-c49aec80-5afb-11ea-934e-874ed5ecf7b7.png)

**Comment by enzyme69** [comment]
This is not intuitive.
<img width="1237" alt="Screen Shot 2020-02-29 at 11 00 02 pm" src="https://user-images.githubusercontent.com/3952687/75607044-38aeb200-5b47-11ea-8d06-b2579018a630.png">

**Comment by OmarEmaraDev** [comment]
Why are you using the old Polygon Indices? Use the ones from the Separate Polygons node.

**Comment by 3DSinghVFX** [comment]
Hi :)
This is not a bug. You have to provide edge indices because Combine Mesh does not generate edge indices from the polygon indices. There is Edges From Polygons node which generates edge indices from the polygon indices,
![Screenshot from 2020-02-29 17-29-52](https://user-images.githubusercontent.com/30294746/75607081-6aa91f80-5b19-11ea-9c51-2cda305e0cb6.png)

**Comment by enzyme69** [comment]
<img width="1131" alt="Screen Shot 2020-02-29 at 11 04 38 pm" src="https://user-images.githubusercontent.com/3952687/75607119-ec17a680-5b47-11ea-8e2b-e39fe7f5eea2.png">
Oooh ok I think I got it. Cheers~
[AN_separate_polygon_003.blend 2.zip](https://github.com/JacquesLucke/animation_nodes/files/4270246/AN_separate_polygon_003.blend.2.zip)

**Comment by OmarEmaraDev** [comment]
I added automatic link conversion between the two to make things easier. 33a3e05
