### ISSUE TITLE
animation nodes

### ISSUE THREAD

**Issue by ghJKi876** [JacquesLucke/animation_nodes#1345]
Click on the zip file I have the animation nodes installed in preferences blender 2.83 there's appending symbol to the right side check box on the left I click the check box it says error. I tried to make a copy of the error box but it won't let me

**Comment by OmarEmaraDev** [comment]
Can you screenshot the error?

**Comment by ghJKi876** [comment]
It disappears when I move away from it says trace back then I did not get the rest of it. I just learned how to remove the add on from preferences and try to install it again I get the same thing. If you like I have team viewer so you can join me on my computer so that you can see it yourself and maybe get it insalled for me to.

**Comment by OmarEmaraDev** [comment]
Please try to screenshot it then. Also, did you take a look at #1240?

**Comment by ghJKi876** [comment]
I told you that on the last comment this hopeless to me oh well

**Comment by OmarEmaraDev** [comment]
Why is it hopeless? Which OS/Desktop are you using?

**Comment by OmarEmaraDev** [comment]
I mean, why can't you take a screenshot? Maybe take a look at https://www.take-a-screenshot.org/windows.html

**Comment by ghJKi876** [comment]
I told you before the error disappears when I move the arrow away from its
on there for a half a second then gone. geees

**Comment by OmarEmaraDev** [comment]
Don't move the cursor, just press the key combination, then attach the screenshot here.

**Comment by ghJKi876** [comment]
[image: blender_2.83_alpha_EQDlL2rnPM.png]this is the animation node when I
click that check box I get the error there's that triangle shape symbol on
the right means it doesn't work

**Comment by OmarEmaraDev** [comment]
I can't see the image, please attach it in Github instead.

**Comment by ghJKi876** [comment]
I keep telling you I can not GET A SCREENSHOT OF THE ERROR THE ONE I SENT
IS JUST THE BOX IN THE PREFERENCES THE ANIMATION NODES IS BY ITSELF WITH
THE CHECK BOX WHEN I CHECK THAT BOX THE ERROR SHOWS UP AND DISAPPEARS. SO I
CAN NOT TAKE A SCREENSHOT OF THAT I AM NOT TELLING YOU AGAIN THIS IS
GETTING TO STRESSFUL

**Comment by JacquesLucke** [comment]
Please open the console before activating Animation Nodes via `Window -> Toggle System Console`. Then try to activate the addon again. The error that was in the popup should now be written in the console.

Also, caps lock seems to be enabled on your keyboard, you might want to fix that.

**Comment by ghJKi876** [comment]
I still aint getting it.

**Comment by 3DSinghVFX** [comment]
@ghJKi876 Hi...

Do you have a screen recorder e.g., [OBS](https://obsproject.com/)? If not, please install a screen recorder. Then record a small video of that error and send it as _zip_ file. That will help us to resolve the error.

You can attach the zip file in the _comment_ from the option _Attach files by dragging & dropping, selecting or pasting them_,
![Screenshot from 2020-03-05 11-18-47](https://user-images.githubusercontent.com/30294746/75952022-89b9ff80-5ed3-11ea-9bf4-89fb1155e4d8.png)

**Comment by ghJKi876** [comment]
I have a screen recorder how many times do I have to tell you that error
will not appear on the recorder I told before and before it will not record
the error. If you don't want to come and join me on my computer to show me
how to get the animation nodes installed don't bother with the stupid
answers that are really not answers. By the way am I talking to a real
person if not I need a real person to talk to not a computer generated voice

**Comment by JacquesLucke** [comment]
You are talking to three actual persons here who want to help you for nothing in return.

![image](https://user-images.githubusercontent.com/5881326/75975925-b2dd8e80-5ed9-11ea-9e85-7f6e7a828e57.png)
1. Click on `Toggle System Console`.
2. Try to enable the Animation Nodes.
3. After there was the error popup, go to the previously opened console and copy the content of it here.

It should look something like this:
![image](https://user-images.githubusercontent.com/5881326/75976108-0f40ae00-5eda-11ea-9919-0b024bd8eb7e.png)

**Comment by ghJKi876** [comment]
[image: W1WKc1G2Is.png]

**Comment by JacquesLucke** [comment]
We cannot see the image, something went wrong when you uploaded the image. I only see the text `[image: W1WKc1G2Is.png]`.
Please try to upload the image correctly or copy the text from the console without making a screenshot.

**Comment by ghJKi876** [comment]
will you please come and join me on my computer so that I can watch you how
to get rid of these issues and install the animation nodes for me. I have
team viewer. Other teachers has helped that way

**Comment by OmarEmaraDev** [comment]
You are sending those messages through your email client, that's why the image is not displaying. Upload the image to Github as outlined by @3DSinghVFX above.
