### ISSUE TITLE
Way to use polygon-index to set polygon material?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1346]
I download the Animation node from blender community. The current version is 2.1.7
I saw the tutorial by @3DSinghVFX on youtube, but the node I am having is completely different from the one shown in the tutorial. I can't choose between type, such setting polygon index; I can only see option to set material index.
I wonder if there is a way for me get to set polygon-index for specific material as shown? Thanks in advance.

My node
![My node](https://user-images.githubusercontent.com/55994236/76027714-1af29b80-5eff-11ea-8b37-11e86859a1a3.png)
The node in the tutorial
![Original option](https://user-images.githubusercontent.com/55994236/76028266-3dd17f80-5f00-11ea-9361-1950f1cea0b7.png)

**Comment by OmarEmaraDev** [comment]
I am not entirely sure what you mean, so I will let @3DSinghVFX track this with you, he implemented this node.

**Comment by Gerstmann-Bradley** [comment]
I just think I can come up with a workaround to solve this issue. But I wonder why the most original design of index type has been changed.

**Comment by 3DSinghVFX** [comment]
@Gerstmann-Bradley Hi...
Yes, initial it was there. However, by following the _Set Nodes_ design we removed _Index_ option from the _Set Polygon Material Index_ node.

But you can set per polygon material by making material indices list accordingly, here is an example,
![Screenshot from 2020-03-06 15-01-46](https://user-images.githubusercontent.com/30294746/76071334-14762980-5fbc-11ea-8823-5fe2e5fcd196.png)

Please, let us know whether this solves your issue.

**Comment by Gerstmann-Bradley** [comment]
> @Gerstmann-Bradley Hi...
> Yes, initial it was there. However, by following the _Set Nodes_ design we removed _Index_ option from the _Set Polygon Material Index_ node.
> 
> But you can set per polygon material by making material indices list accordingly, here is an example,
> ![Screenshot from 2020-03-06 15-01-46](https://user-images.githubusercontent.com/30294746/76071334-14762980-5fbc-11ea-8823-5fe2e5fcd196.png)
> 
> Please, let us know whether this solves your issue.

Ok, I come up with idea to do that. Thanks.
