### ISSUE TITLE
Clamping Falloff?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1347]
Referring to the picture, If I set the translation to a negative value, so I assume all polygons should move downwards, but the fact is that some polygons will move upwards. I think it's because the noise falloff is generating negative value.
I try to use "remap falloff", but by default it doesn't change any result. Certainly its function is not to clamp? I tried other method like set remap value to 1-2 or 0.5-1.5; none of these seem to help give a perfectly "clamped" result that sets an upper/lower limit.
What I want is a falloff value from 0-1 (or number you can actually set). Either there is no translation, polygon will stay perfectly at the position, or they will go to 1, or a maximum that I can set. To conclude, may be I am looking for "clamping of the falloff" in general.
![remap noise falloff](https://user-images.githubusercontent.com/55994236/76029604-cf41f100-5f02-11ea-85d5-0e152fe30d78.png)

**Comment by Gerstmann-Bradley** [comment]
Wait, Sorry to add, I think it's not "clamping falloff", it's still a "remap falloff" which can help clamp. If my falloff is -1 to 1, it should be remapped back to 0-1. According to manual, remap falloff assume the falloff range from 0-1 (which isn't true for noise falloff or even wiggle falloff?). This may be the reason it doesn't help in noise falloff and can hardly get a desired effect.

**Comment by OmarEmaraDev** [comment]
I see. We should either extend the Remap Falloff node to other ranges or remap the Noise Falloff to a normalized range.

**Comment by 3DSinghVFX** [comment]
@OmarEmaraDev I think we should extend the Remap Falloff node so that it can be used in any falloff range, and it will be very helpful in the case of Custom Falloff.

**Comment by OmarEmaraDev** [comment]
Implemented in fc68392.
