### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by samehaladli** [JacquesLucke/animation_nodes#1349]
Hello,

Thanks for your efforts making blender more easy for us.

I installed the add-on but i get the error message when i try to enable it.
My OS is Win 8.1
Blender 2.83

**Comment by 3DSinghVFX** [comment]
@samehaladli Hi...
From where you have downloaded the AN build? Can you please share a screenshot of the error?

**Comment by samehaladli** [comment]
Ya sure please check the link:
![AN issue](https://user-images.githubusercontent.com/46692731/76108468-55cdff80-5fe3-11ea-8f82-4cba59f8c3b7.jpg)

**Comment by samehaladli** [comment]
I downloaded the add-on from the creator site: 
https://animation-nodes.com/

**Comment by 3DSinghVFX** [comment]
> I downloaded the add-on from the creator site:
> https://animation-nodes.com/

Okay.

You have to install `vc_redist.x64` from [microsoft's support center](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads#section-2). (for more details see https://github.com/JacquesLucke/animation_nodes/issues/1240)

**Comment by samehaladli** [comment]
@3DSinghVFX I install it but gives me the same error message.

**Comment by 3DSinghVFX** [comment]
Did you try a fresh install of AN after the installation of `vc_redist.x64`?

**Comment by samehaladli** [comment]
Yes i did.

**Comment by 3DSinghVFX** [comment]
> Yes i did.

Okay.

@OmarEmaraDev can you please look at this issue.

**Comment by OmarEmaraDev** [comment]
I don't really know what could be causing this issue. It is probably an issue with the installation of `vc_redist.x64`, perhaps try reinstalling using administrative privileges.

**Comment by OmarEmaraDev** [comment]
@samehaladli Did that work?

**Comment by inertdruid** [comment]
same problem here!

**Comment by 3DSinghVFX** [comment]
@inertdruid Hi...
If Animation Nodes (AN) does not appear in the addon list after installation, probably you have installed the source code of AN. Please remove the AN-files (folder) from the addon folder, download the AN build from https://animation-nodes.com/ and install it.
