### ISSUE TITLE
Is it possible to use functions from float_math.pyx ?

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1352]
I was trying to create a node myself. i have two float list. i want to perform some operation like division on it. Is it possible to use functions from float_math.pyx ? if yes how?

**Comment by OmarEmaraDev** [comment]
`float_math.pyx` is not designed to be used a a general purpose list math functions. Typically, what you should do is create the needed cython function in a `c_utils.pyx` file then call them from python.

**Comment by harisreedhar** [comment]
Thanks

**Comment by OmarEmaraDev** [comment]
I will close this for now. Feel free to reopen if needed.
