### ISSUE TITLE
The Attribute entry of Set Vertex Color is gone

### ISSUE THREAD

**Issue by marcydunk** [JacquesLucke/animation_nodes#1353]
I just found there are two Set Vertex Color nodes in the latest AN (Color->Set Vertex Color; Mesh -> Mesh data->Set Vertex Color), and they are exactly the same with the Attribute entry removed. Without this entry I won't be able to create a vertex color attribute for each instance independently and send data to Shader editor to control the Mix factors. 

I've tried the Material nodes like the Cycles Material Output, but it changes the material data as a whole. Or should I use the Material Instancer to achieve the same thing?

Looking forward to your response.

Thanks

**Comment by Gerstmann-Bradley** [comment]
I think the way it works now is that you need a "vertex color layer" that's manually added in object's mesh. If you are instancing object, then add this vertex color layer in the mother object and "copy full object + deep copy". Or you can use "insert vertex color layer" node if you are generating new mesh...There are many other options you can do I suppose.
In shader, use "vertex color" instead of "attribute".

**Comment by marcydunk** [comment]
> I think the way it works now is that you need a "vertex color layer" that's manually added in object's mesh. If you are instancing object, then add this vertex color layer in the mother object and "copy full object + deep copy". Or you can use "insert vertex color layer" node if you are generating new mesh...There are many other options you can do I suppose.
> In shader, use "vertex color" instead of "attribute".

Thanks dude. I'll give it a try.

**Comment by OmarEmaraDev** [comment]
Did your issue get resolved?

**Comment by marcydunk** [comment]
> Did your issue get resolved?

yes, I took Bradley's advice and got it solved. Thanks Omar.

**Comment by derekcbr** [comment]
> I think the way it works now is that you need a "vertex color layer" that's manually added in object's mesh. If you are instancing object, then add this vertex color layer in the mother object and "copy full object + deep copy". Or you can use "insert vertex color layer" node if you are generating new mesh...There are many other options you can do I suppose.
> In shader, use "vertex color" instead of "attribute".

Hi there,
It worked well by your solution. But it is not animatable. It will crash after 40 frames. Do not know what is wrong?
I use a python script to add the color_layer:
mesh = mysphere.data

    if not mesh.vertex_colors:
        mesh.vertex_colors.new()

    """
    let us assume for sake of brevity that there is now 
    a vertex color map called  'Col'    
    """

    color_layer = mesh.vertex_colors["Col"]
As I do not find a way to do it in Blender. But the animation always got crash!

**Comment by 3DSinghVFX** [comment]
@derekcbr Hi :)
Can you please share the screenshot of the node-tree?

**Comment by derekcbr** [comment]
> @derekcbr Hi :)
> Can you please share the screenshot of the [node-tree?
Please have a look!
![blendercrash001](https://user-images.githubusercontent.com/31892214/78619028-b4bab900-78ae-11ea-9fd9-0d7dd1e646e4.png)

**Comment by 3DSinghVFX** [comment]
It is working on my side: 
![Screenshot from 2020-04-07 11-33-43](https://user-images.githubusercontent.com/30294746/78635366-b17df800-78c3-11ea-8e30-3691bfbda34f.png)

Which version of Animation Nodes and Blender are you using?
You can download the latest build of Animation Nodes (current version is 2.1.7) from https://animation-nodes.com/.

**Comment by derekcbr** [comment]
> It is working on my side:
> ![Screenshot from 2020-04-07 11-33-43](https://user-images.githubusercontent.com/30294746/78635366-b17df800-78c3-11ea-8e30-3691bfbda34f.png)
> 
> Which version of Animation Nodes and Blender are you using?
> You can download the latest build of Animation Nodes (current version is 2.1.7) from https://animation-nodes.com/.

I am using Blender 2.81 and AN 2.1.7. Cheers!

**Comment by 3DSinghVFX** [comment]
@derekcbr Is the AN 2.1.7 working?
