### ISSUE TITLE
When I add a Object Mesh Data node,it appears a Mesh Object Input node?

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1354]
When I add a Object Mesh Data node,it appears a Mesh Object Input node? How to add an Object Mesh Data node?

**Comment by OmarEmaraDev** [comment]
Both names are synonym. It is the same node.

**Comment by derekcbr** [comment]
Mesh Object Input node does not have Vertex Locations,Edge Indices,Polygon Indices shown in user guide. It has Mesh,Vertex Locations and Polygon Centers. Thanks!

**Comment by OmarEmaraDev** [comment]
The documentation describe v2.0. The new version v2.1 changed things a bit as you can see.
