### ISSUE TITLE
Create 2D or 3D curve from Text

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#1357]
Hi,

It would be nice if "separate text object" node curve output could be set to 2D or 3D.
I couldn't find a way to set this setting after object generation. If that would be possible, then it could be as a separate node also. This is actually quite a critical thing for automation of things.

![Annotation 2020-03-11 003125](https://user-images.githubusercontent.com/17803543/76365599-555d9d80-6330-11ea-9c07-4f8b93428ce8.jpg)

**Comment by OmarEmaraDev** [comment]
Implemented in 9be3a04. Thanks for the suggestion!
