### ISSUE TITLE
ReassignLoopParameterNode shows error Target does not exist

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1361]
How to use python script?Beow is code,how to put a value of loopInput for parameterIdentifier?

    loopInput = ng.nodes.new("an_LoopInputNode")
    loopInput.location=(-400,-200)
    loopInput.newIterator("Vector List")
    loopInput.newParameter("Vector List")

    reassignLoopParameter= ng.nodes.new("an_ReassignLoopParameterNode")
    reassignLoopParameter.location=(400,-200)   
    AN.tree_info.update()
    #reassignLoopParameter.parameterIdentifier=loopInput.network.identifier
    reassignLoopParameter.loopInputIdentifier=loopInput.network.identifier

Thanks!

**Comment by 3DSinghVFX** [comment]
> How to use python script?

Here is the details of the _Script Node_: https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/script.html

>Beow is code,how to put a value of loopInput for parameterIdentifier?

Can you please share the screenshot of the node-tree? This may help: https://github.com/JacquesLucke/animation_nodes/issues/1288#issuecomment-578536940

**Comment by derekcbr** [comment]
> Hi...
> 
> > How to use python script?
> 
> Here is the details of the _Script Node_: https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/script.html
> 
> > Beow is code,how to put a value of loopInput for parameterIdentifier?
> 
> Can you please share the screenshot of the node-tree? This may help: [#1288 (comment)](https://github.com/JacquesLucke/animation_nodes/issues/1288#issuecomment-578536940)

Omar has helped to send me the solution for subprogramnode by using python script before and it worked well for me. Now I need the same for ReassignLoopParameterNode.

**Comment by derekcbr** [comment]
![an20200316180526](https://user-images.githubusercontent.com/31892214/76745780-6899be80-67b1-11ea-911d-ac1290fcb349.jpg)
Please have a look at the attahed photo.

**Comment by OmarEmaraDev** [comment]
The `loopInputIdentifier` should be the identifier of the loop input node, not the network. Moreover, `parameterIdentifier` should be the identifier of the the parameter. For instance, to reassigned the first parameter we do:

```python
reassignNode = nodeTree.nodes.new("an_ReassignLoopParameterNode")
reassignNode.loopInputIdentifier = loopInput.identifier
reassignNode.parameterIdentifier = loopInput.getParameterSockets()[0].identifier
AN.tree_info.update()
```

Just read the source code for more info, it is usually very clear.

**Comment by derekcbr** [comment]
Work well!Thanks Omar!
