### ISSUE TITLE
Proposal: F1

### ISSUE THREAD

**Issue by kosirm** [JacquesLucke/animation_nodes#1362]
Hi, first of all, I want to thank you for this amazing addon. For me it was eye-opening and I think it is possible that it will become one of most important Blender addons.

I have a simple proposal which I think it is quite easy to implement: put F1 function on every node, which will link to node description on (excellent) documentation page. Btw, this is already implemented accross most of Blender functionality, so it would be very natural for Blender users.
Please let me know, it this is maybe already implemented is some other way... I'm new to AN.

BR

**Comment by OmarEmaraDev** [comment]
The built-in F1 operator is not extensible as far as I know. So if we want this functionality, we are going to have to implement our own operator. I am not sure if this is something we will do, but I will label this as a proposal for now. I will get back to you later.

**Comment by kosirm** [comment]
Thanks!

**Comment by OmarEmaraDev** [comment]
I took another look at this. It seems we can't define our own F1 help system without conflicting with Blender's. So if we decide to do that, we will have to define another shortcut or context menu entry, which won't be very discoverable. Moreover, I don't want the overhead of maintaining a mapping between the two. So I don't think we will be implementing that. Sorry.
