### ISSUE TITLE
When to use cython ?

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1363]
I have few doubts in coding on AN,

1. What are the best cases to use cython for animation nodes ? 
2. What is a virtuallist ?
3. How yield works to return list ? I saw they are written inside double quotes
4. How to check a socket is empty or not ?

**Comment by OmarEmaraDev** [comment]
1. We use Cython in two cases. (1) When we want to use C/C++ code in Animation Nodes. (2) If writing the code in Cython would result in better performance. This is usually the case for algorithms that have a large input size. Some code is always written in Cython, like Falloffs.
2. A virtual list is a list that allow indexing outside of its bound by repeating or filling itself. For instance, if `a = virtual([0, 1, 2, 3])`, then `a[3] -> 3, a[4] -> 0, a[5] -> 1, ...`.
3. This is called a "Generator Function". Consult the documentation for how this works.
4. I assume you mean if a socket is linked or not. In this case, you can use the `required` input of the `getExecutionCode` function. For example, look at the sort node.

**Comment by harisreedhar** [comment]
Thanks @OmarEmaraDev
