### ISSUE TITLE
Current version of some nodes appear different from examples in manual

### ISSUE THREAD

**Issue by JayMuller** [JacquesLucke/animation_nodes#1364]
I am diligently working through the examples provided in the manual, but have several issues.  The current issue driving me utterly insane is some nodes appear completely different in my instantiation of Animation Nodes (I have the current build).  For example, the Mesh From Object (Vector From Value, example 1) node in the illustration provided has "Edges" and "Faces" options above the "Use Modifiers" option, but mine does not, nor does "w" or anything else I've come across in the documentation or numerous video tutorials explain why.  Similarly, the Grid Mesh node (Vector Wiggle, example 3) doesn't have "Vertices", "Edge Indices", or "Polygon Indices"  out put sockets, nor does "u" give me the option to add any of those sockets.  Any assistance would be greatly appreciated.  I am confident I will become adept with Animation Nodes one way or another, but it will take much longer if I can't even replicate basic examples.  Thank you in advance for any and all consideration,
Jay Muller

**Comment by OmarEmaraDev** [comment]
The documentation describe version v2.0. The version you are using is v2.1, which has some differences as you can see. The documentation will be updated once v2.1 is released. We hope this will be in the coming months.

**Comment by JayMuller** [comment]
Thank you for the prompt reply.  Is there a way to download version 2.0 and use it as a separate add on in the same template, for side by side comparison?  
Thanks again!
Jay

**Comment by OmarEmaraDev** [comment]
Yes. But v2.0 only works with Blender 2.7x, so that would make things harder. You may download that from: https://animation-nodes.com/#download

**Comment by JayMuller** [comment]
Good afternoonI am slowly but surely learning Animation Nodes, and getting better at figuring out discrepancies between the documentation and the latest version.  Having said that, I am trying to work the example given for "Combine Mesh Data", but am unable to find either the "Prepare Polygon T (Transform?)" or "Transform Polygons" nodes.  I have looked closely at the socket settings for every node that may possibly fill those roles, to no avail.  If they have been rendered obsolete, could you provide a similar example using the current version of AN?  If not, could you provide some additional detail regarding the initial selection of nodes within the node tree provided by the example, and how they are connected to make them appear as in the example?  Thank you in advance for any and all consideration,Best,Jay
    On Tuesday, March 17, 2020, 08:15:08 AM EDT, Omar Emara <notifications@github.com> wrote:  
 
 


Yes. But v2.0 only works with Blender 2.7x, so that would make things harder. You may download that from: https://animation-nodes.com/#download

**Comment by OmarEmaraDev** [comment]
@JayMuller I think the node you are looking for is the Offset Polygons node and Separate Polygons node. They are not exactly the same, but they are designed to achieved the same effect.

**Comment by JayMuller** [comment]
Good afternoonI updated to Blender 2.91 yesterday.  I am using Animation Nodes 2.2.1.  When I copy a node network from one project and attempt to paste it in a different project, Blender immediately terminates.  Copying and pasting between different node trees or within the active node tree space works flawlessly.  This crash occurs whether I right click or use ctrlc/ctrlv.  I routinely copied node networks between different blend files using Blender 2.90.1 without ever encountering a crash.  I hope someone finds this information useful.  Have a great day,Jay Muller
    On Tuesday, March 17, 2020, 05:34:21 AM EDT, Omar Emara <notifications@github.com> wrote:  
 
 


The documentation describe version v2.0. The version you are using is v2.1, which has some differences as you can see. The documentation will be updated once v2.1 is released. We hope this will be in the coming months.

**Comment by OmarEmaraDev** [comment]
@JayMuller Any crash report to look at?

**Comment by JayMuller** [comment]
Well, I tried to figure out how to obtain a crash log, I've spent over an hour on it, wading my way through a variety of google search results.  The furthest I can get on the process is "the system cannot find the file path specified" message when attempting to run the .exe file from command prompt, which led me down a path of nested search results (i.e., what does "the system cannot..." mean? "what is SFC", etc) ultimately resulting in accomplishing absolutely nothing. Please advise.  Jay 
    On Saturday, November 28, 2020, 03:51:00 PM EST, Omar Emara <notifications@github.com> wrote:  
 
 


@JayMuller Any crash report to look at?

**Comment by JayMuller** [comment]
For every instance of crashing, I have a corresponding "455" error, as followsLog Name:      ApplicationSource:        ESENTDate:          11/29/2020 10:46:02 AMEvent ID:      455Task Category: Logging/RecoveryLevel:         ErrorKeywords:      ClassicUser:          N/AComputer:      owner-PCDescription:svchost (11580,R,98) TILEREPOSITORYS-1-5-18: Error -1023 (0xfffffc01) occurred while opening logfile C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log.Event Xml:<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">  <System>    <Provider Name="ESENT" />    <EventID Qualifiers="0">455</EventID>    <Level>2</Level>    <Task>3</Task>    <Keywords>0x80000000000000</Keywords>    <TimeCreated SystemTime="2020-11-29T15:46:02.624086600Z" />    <EventRecordID>9451</EventRecordID>    <Channel>Application</Channel>    <Computer>owner-PC</Computer>    <Security />  </System>  <EventData>    <Data>svchost</Data>    <Data>11580,R,98</Data>    <Data>TILEREPOSITORYS-1-5-18: </Data>    <Data>C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log</Data>    <Data>-1023 (0xfffffc01)</Data>  </EventData></Event>
I hope this helps.Jay
    On Saturday, November 28, 2020, 03:51:00 PM EST, Omar Emara <notifications@github.com> wrote:  
 
 


@JayMuller Any crash report to look at?

**Comment by OmarEmaraDev** [comment]
@JayMuller See https://docs.blender.org/manual/en/latest/troubleshooting/crash.html#windows. Also can you provide a test file?

**Comment by JayMuller** [comment]
Let's assume I do not know how to create, or locate, a test file.  I am unable to discern anything useful from the provided link, because there are many details glossed over in the brief explanation provided.  For example, there is mention of the "Blender installation directory".  Exactly what does that look like, and where precisely is it located?  Almost every statement on that link similarly results in more questions for me, rather than a single answer.  Sorry, I'm happy to give as much information as possible, but finding it is no easy task.Jay     On Sunday, November 29, 2020, 11:15:59 AM EST, Omar Emara <notifications@github.com> wrote:  
 
 


@JayMuller See https://docs.blender.org/manual/en/latest/troubleshooting/crash.html#windows. Also can you provide a test file?
