### ISSUE TITLE
object instancer

### ISSUE THREAD

**Issue by SensArice** [JacquesLucke/animation_nodes#1365]
Whenever I repeatedly check "copy full objcect" 
The node will automatically copy a lot of redundant objects.
This is very inconvenient.

**Comment by OmarEmaraDev** [comment]
Can you elaborate? What does *"copy a lot of redundant objects"* mean?

**Comment by SensArice** [comment]
I want to move the copied objects from the object instancer node to a collection with collection operations. 
When I check "copy full object", then uncheck "copy full object" 
There will be a lot of useless objects.
![QQ截图20200320022341](https://user-images.githubusercontent.com/40132479/77101350-217e2880-6a52-11ea-8f54-241232586fe7.png)

**Comment by OmarEmaraDev** [comment]
I believe we fixed this in 33a578c, can you try the latest version from https://animation-nodes.com/?
