### ISSUE TITLE
Error when calling invert falloff node

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1366]
when calling "invert falloff node", no need to connect it to anything, error message will appears.
error is resolved if the "invert falloff" node is deleted from the node tree.
The screenshot shows the console, hope it helps.
![report](https://user-images.githubusercontent.com/55994236/77146418-5f367d80-6a61-11ea-81de-c9039c1ffe6d.png)

**Comment by OmarEmaraDev** [comment]
I think this was already fixed. Can you try the newest build?

**Comment by Gerstmann-Bradley** [comment]
> I think this was already fixed. Can you try the newest build?

ooops, it's fixed. Sorry
