### ISSUE TITLE
How to generate a Target object in MeshObjectOutputNode by python script?

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1367]
How to generate a Target object in MeshObjectOutputNode by python script?

**Comment by OmarEmaraDev** [comment]
I recommend you look at the source code first, usually what you want is clear enough.
https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/sockets/object.py#L55

**Comment by derekcbr** [comment]
Thanks!
