### ISSUE TITLE
Proposal: radial falloff

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1368]
AFAIK radial falloff isn't an available feature in AN.
I have workaround to solve part of this problem, but it only works for radial pattern.
At some point, I still wish to have true radial falloff if possible? Thanks.
![radial falloff](https://user-images.githubusercontent.com/55994236/77161526-48535380-6a80-11ea-80dd-824efae08eb2.png)

**Comment by JacquesLucke** [comment]
Sounds like a good idea. I can see many use cases for this.

**Comment by OmarEmaraDev** [comment]
Implemented in 04e151e. Thanks for the suggestion!
