### ISSUE TITLE
Subprograms don't seem to work

### ISSUE THREAD

**Issue by liquid600pgm** [JacquesLucke/animation_nodes#1369]
For some strange reason, when I add an Invoke Subprogram Node, then create a Loop subprogram, the Loop subprogram does not appear in the Invoke Subprogram Node.

![image](https://user-images.githubusercontent.com/16415678/77192798-7024d480-6add-11ea-92b0-cd3bd565dc6e.png)

The nodes also don't change color, which seems to be visible in the documentation (their color is purple).

I'm running version 2.1.4 compiled from source to make it work with Python 3.8. Blender on Manjaro seems to have a newer, incompatible Python version, hence I couldn't use the prebuilt binaries.

**Comment by OmarEmaraDev** [comment]
Note that we have Animation Nodes in the AUR.
https://aur.archlinux.org/packages/blender-plugin-animation-nodes-git/

Which Blender version are you using? 2.1.4 is an old version, can you update to the latest version?

Can you open Blender from the terminal and tell us the output in the terminal?

**Comment by liquid600pgm** [comment]
Oh, updating Blender and Animation Nodes seems to fix the problem. Sorry for opening this issue, it was pretty stupid of me to not update stuff first.
