### ISSUE TITLE
AN-generated objects appear in all scenes

### ISSUE THREAD

**Issue by liquid600pgm** [JacquesLucke/animation_nodes#1371]
For instance, I have a tree `text_anim` bound to scene `text` which animates some text using the `Separate Text Object` node, and another tree `pop_anim` bound to scene `pop` which creates some objects using the `Object Instancer` node. However, on any update, my instanced objects appear on both scenes, despite being in completely separate scenes. The objects aren't animated, they're just… there. Not moving, not invisible.

**Comment by liquid600pgm** [comment]
After some further investigation, it appears that AN reuses just one container for its objects, which is linked across scenes. This means that any changes I do in the container will be reflected in other scenes, which causes even more problems because I can't even remove the generated objects manually.

**Comment by OmarEmaraDev** [comment]
I see what you mean.

By the way, you should never remove objects manually, you would just be unlinking them without removing them.

**Comment by liquid600pgm** [comment]
@OmarEmaraDev 
> By the way, you should never remove objects manually, you would just be unlinking them without removing them.
I know that removing objects manually is bad, I just wanted a quick solution for the time being, but it appears that won't work.

**Comment by OmarEmaraDev** [comment]
@liquid600pgm The Instancer node have an Advanced Node Option called *Add To Main Container*. You can disable it for now if you want.

**Comment by liquid600pgm** [comment]
@OmarEmaraDev sure, but what about Separate Text Object? It doesn't seem to have this option
