### ISSUE TITLE
Possible bug  found when I was trying to find workarounds for a question: 

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1375]
Possible bug found with Mesh Object Input / Output nodes when I was trying to find workarounds for this question: 

[https://blender.stackexchange.com/questions/170591/using-animation-nodes-to-create-animate-different-3d-polyhedrons-solids-using](https://blender.stackexchange.com/questions/170591/using-animation-nodes-to-create-animate-different-3d-polyhedrons-solids-using)

I was testing the node setup below.
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/mesh/object_mesh_data.html

And **when I increase or decrease the factor field the icosphere just increases in size.**
![vokoscreen-2020-03-23_22-37-54](https://user-images.githubusercontent.com/28985314/77382810-b2f1e100-6d57-11ea-8020-9d4cee14adf3.gif)

I'm using animation nodes 2.1.7 aaf17bf8d14946c2bc4f9cebe4bcc184.zip and Blender 2.82a on Linux 64bit.  I also tested it with animation nodes 2.1.6 the issue still popped up.

See attached gif

**Comment by 3DSinghVFX** [comment]
It is not a bug. Actually, you are using the same Icosphere for the input and output which leads to recursive effect. Please use a different object (create a new object by clicking the + button) in the Mesh Object Output node

**Comment by stillpointx** [comment]
Thanks
