### ISSUE TITLE
Question ; is there a easy way to merge/join objects 

### ISSUE THREAD

**Issue by BennyGovaerts** [JacquesLucke/animation_nodes#1377]
Is there a solution to easy merge/join object like with sverchok if you need this 
![image](https://user-images.githubusercontent.com/49908008/77533161-a88a3100-6e96-11ea-86c2-14d5c9613753.png)
![image](https://user-images.githubusercontent.com/49908008/77533290-e1c2a100-6e96-11ea-8203-9370204abe1e.png)

**Comment by OmarEmaraDev** [comment]
Use the Transform Mesh node with the *Join Mesh* option enabled. Or just use the *Join Mesh*
 node manually.
![20200325-140113](https://user-images.githubusercontent.com/25300994/77534090-b9d83b00-6ea0-11ea-9c19-01adf9bd7ac7.png)

**Comment by BennyGovaerts** [comment]
But then you can not switch to instances if you need this instead off deep copy

**Comment by OmarEmaraDev** [comment]
Not sure I follow.

**Comment by BennyGovaerts** [comment]
Excellent idea but then you need another node setup

**Comment by OmarEmaraDev** [comment]
Another node setup to do what?

**Comment by BennyGovaerts** [comment]
Sometimes you need instances and sometimes you need real geometry - 
![image](https://user-images.githubusercontent.com/49908008/77536126-1a18ae00-6e9c-11ea-82dc-95de1f4ea832.png)

**Comment by BennyGovaerts** [comment]
Thanks , for this solution
