### ISSUE TITLE
Additional way to generate a material list?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1379]
This may be a weird situation, but I imported images as planes. I have about 50 images/materials on 50 planes respectively. I need to copy these materials to another 50 objects (each of them should have a different material). It's possible doing this in AN by loop and "object material output", but I need to firstly create a "material list" that include these 50 materials.
AFAIK, only two ways to generate a material lists, either I create it manually using "create a material list", Or I use material instancer. Both ways don't seem solving the problem easily.

1. Hypothetically, if it it allows me to "get object material"/"object material input", it maybe easier to achieve such a function?
2. Or, is there a way to get all materials on the file into a list, and then use "filter" by name to select required material for me?

**Comment by OmarEmaraDev** [comment]
Implemented in a4fa4e8. Thanks for the feedback!
