### ISSUE TITLE
add child particles to particle nodes

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#138]
child particles are not presented
They can be shown in:
- particle sys info as second output socket
- particle sys info single socket for all + "children" check in filter node
- particle sys info single socket for all + "children"socket in filter node
- separate node at the level of filters (under particle sys info)
with particels input and children output, maybe a check for preview/render

I am tempted about the last, as they are related to the parent partc with respective alive etc
Structurally they appear next to the parents  (bpy.data.particle_systems[0].child_particles), but they don't present all those states independently

There is an extra issue with having creation determined by preview and render separate parameters. so witch to go for? they are default render 100, but display 10, in which case you'll find only 10 x partcnumber as a list  in the above path. 
This is a good place for a warning, as 10 times slower may just crash a loop. Maybe as simple label info  display10 /render100 ! or so. (we don't really have access to render nr but on render time.)

I'd go for last, separate node, with warning.

ps. there are also trailing particles that can be set. I cannot find them for the love of god ..

**Comment by JacquesLucke** [comment]
seems like I don't have access to the position of Child Particles: http://www.blender.org/api/blender_python_api_2_74_5/bpy.types.ChildParticle.html#bpy.types.ChildParticle

**Comment by og76** [comment]
seams so
sorry I did not look deeper into data blocks before asking. 
I'll see if I find scripts to access this For now not. 

(they are usefull for hair mostly, or for simpler data calc as they are interpolated from parents and not part of the sim. But they do use dupli instances...)
