### ISSUE TITLE
AN Version for Blender 2.82 specifically?

### ISSUE THREAD

**Issue by 017Bluefield** [JacquesLucke/animation_nodes#1381]
Tried using the 2.0 release of Animation Nodes for Windows on Blender 2.82, but encountered a version mismatch error below:

![Annotation 2020-03-26 182441](https://user-images.githubusercontent.com/5580888/77712040-dc954d00-6f8f-11ea-876d-2bae48dcfeeb.png)

Is there already a build of AN that can be used in 2,82? If so, which one?

**Comment by 3DSinghVFX** [comment]
You can download the latest build of AN from https://animation-nodes.com/

**Comment by 017Bluefield** [comment]
Thank you.
