### ISSUE TITLE
Proposal: Interpolation in "remap falloff" node.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1383]
I am working with a falloff range from -1 to 1 and feed it into "offset matrices" node, and I wish to interpolate the falloff.
Interpolate falloff seems also assume the falloff range from 0 to 1, while it will disrupt my setup.
I think easiest way to solve it is to add interpolation option within the "remap falloff" node.

**Comment by OmarEmaraDev** [comment]
Implemented in 2a9866d. Thanks for the suggestion!
