### ISSUE TITLE
Trying to convert math nodes to use an expression node gives an error

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1385]
I'm trying to convert some math nodes over to using an expression node (this will give me more flexibility and make it easier to read / change) but I'm getting an error message see below.

![screenshot-March-29-2020-02:42:57](https://user-images.githubusercontent.com/28985314/77843031-0f456e00-7167-11ea-8456-27a064ae6a90.png)

This is what my node setup is.

![screenshot-March-29-2020-02:39:01](https://user-images.githubusercontent.com/28985314/77843045-3d2ab280-7167-11ea-8bca-8fe81cfda672.png)

**Comment by harisreedhar** [comment]
@stillpointx You should use loops. because sin, cos functions don't support list input.
Some example : 
![expression_loop](https://user-images.githubusercontent.com/46858047/77844308-6416d200-71c3-11ea-9620-ac99228dc501.PNG)

**Comment by 3DSinghVFX** [comment]
@stillpointx It does not support any kind of list. However, you can convert them in NumPy array then use them as usual, 
First import `numpy` in the N-panel of the expression node,
![Screenshot from 2020-03-29 14-04-34](https://user-images.githubusercontent.com/30294746/77844747-b4436380-71c6-11ea-879f-93e49b35fc82.png)

![Screenshot from 2020-03-29 14-07-20](https://user-images.githubusercontent.com/30294746/77844748-b86f8100-71c6-11ea-9a98-59c458368bff.png)

**Comment by stillpointx** [comment]
Thanks!! @3DSinghVFX  and @harisreedhar this really helped I've included the image of a sample node setup here in-case someone will have to use large equations and wan't to avoid using several math nodes.

![screenshot-March-29-2020-07:23:45](https://user-images.githubusercontent.com/28985314/77847929-a7a31900-718e-11ea-9f82-bf2f4ad24ad9.png)

**Comment by stillpointx** [comment]
I do get an error with certain functions.
![screenshot-March-29-2020-07:57:34](https://user-images.githubusercontent.com/28985314/77848486-197d6180-7193-11ea-999a-67015619f8b1.png)

**Comment by harisreedhar** [comment]
@stillpointx I think numpy doesn't support ** operator. Try` 1 - (numpy.square(x) + numpy.square(y) + yinc)` or `1 - (numpy.power(x, 2) + numpy.power(y, 2) + yinc)`
To know more about numpy functions check : [Link](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)

**Comment by 3DSinghVFX** [comment]
> @3DSinghVFX I do get an error with certain functions is there a workaround?
> ![screenshot-March-29-2020-07:57:34](https://user-images.githubusercontent.com/28985314/77848486-197d6180-7193-11ea-999a-67015619f8b1.png)

The resaon you are getting an error because you have change the output type `numpy.array(x)` as _Float List_. The `numpy.array(x)` should be _generic_ type (red circle) for lists. However, the output you can set with the _gear_ button (green circle) as you need:
![Screenshot from 2020-03-29 19-50-03](https://user-images.githubusercontent.com/30294746/77851456-e5d42300-71f6-11ea-91db-49d97329a04f.png)

**Comment by stillpointx** [comment]
Thanks!!
