### ISSUE TITLE
Easy way to Join Objects with Materials

### ISSUE THREAD

**Issue by Galfour** [JacquesLucke/animation_nodes#1387]
Is there an easy way to emulate `ctrl+J` from Object Mode?

With Animation Nodes, the easy thing to do is `Object` -> `Mesh Object Input` -> `Mesh`. And after having done so for each object, you can `Join Mesh List`.

However, this looses all material information. In order to keep those, I had to define a lot of boilerplate:
![image](https://user-images.githubusercontent.com/10775078/78155117-f671dc80-7434-11ea-8646-d5a3c60ad63b.png)

Which I then have to carry around when doing simple things. Here is what piling some objects on top of each other (ground, dynamic number of floors, top) looks like:
![image](https://user-images.githubusercontent.com/10775078/78155740-bfe89180-7435-11ea-8f96-b70736c99db3.png)

**Comment by OmarEmaraDev** [comment]
The problem is that polygon indices are not part of the mesh structure currently. I suppose we can do something about that.

**Comment by OmarEmaraDev** [comment]
Implemented in 4d0e672. Thanks for the suggestion!

**Comment by Gerstmann-Bradley** [comment]
Hi Omar, would you be able to provide a simple example to achieve what's proposed in this post?
If I understand correctly, the post was talking about a procedural way to "ctrl+J" in which materials of polygons will be retained.
I am not exactly sure how currently update actually solves this issue.
Assuming there are two objects, and each of them has a single material. Then their material indices will all be 0. Even if they are joined with node, the second object mesh data won't change its indices automatically to 1 or more. Therefore the final product will only read material whose index is 0.
Looking for suggestions.

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley Ctrl+J is an object level operation, not mesh a one. So I am guessing Blender can make an educated decision to increment the material indices based on the material slots of each of the objects. How would we make such a decision here? Moreover, how do we inform the user about the changes so that the user can create the materials slots appropriately?

Currently, the user can increment the indices manually then join.
