### ISSUE TITLE
Support for pickles

### ISSUE THREAD

**Issue by j6k4m8** [JacquesLucke/animation_nodes#1389]
More generally, this is in pursuit of more easily importing external data. I'd love to be able to import numerical data more intelligently than through a hacked-together CSV parser reading from a textfile. Pickles seemed like a good answer here, but I'm very open to other solutions (or maybe I'm missing an obvious node!?).

If folks like the idea, I'd be happy to try scripting it up myself, too.

**Comment by OmarEmaraDev** [comment]
Can you provide some practical examples for this?

**Comment by j6k4m8** [comment]
I could imagine importing a list of XYZ coordinates as a list of lists; right now, to do the equivalent, you need to chain a `split("\n")` → `split(",")` and point it to reading a textfile. The `eval` call that is then required to convert each number to a float takes an enormous amount of time; even over a few megabytes of data, this can take ~10s per frame, which means it's extremely difficult to debug and tweak.

The main need here is for a way to read data from disk without the need for a slow `eval` step, especially since that eval is not exposed for APIs other than str→float conversions (i.e. you can't `eval("[1,2,3]")` with AN, and must instead do `[eval("1"), eval("2"), eval("3")]`.

If you think that this sort of utility is out-of-scope, I'd be hopeful for a "execute-arbitrary-python" node so that a user could roll one his/her-self, instead :)

**Comment by OmarEmaraDev** [comment]
I agree than parsing CSV manually is not ideal and shouldn't be used in most cases. But let me outline couple of points:
- While CSV is a rather popular data format, a pickle isn't, and it is unlikely that external data will exist as a pickle. So I don't think using pickles here would be appropriate. Maybe a dedicated node for parsing CSV or JSON would be a better option. Which brings me to the next point.
- The output of a CSV or a JSON parser is rather unpredictable and won't be readily usable in Animation Nodes. The best we could do is to assume numerical data and return a generic list of lists. This generic list would need further processing before it becomes ready for use in AN.

>  I'd be hopeful for a "execute-arbitrary-python" node.

We already have that, there is the Expression node for simple python expressions and the Script node for arbitrary scripts. Animation Nodes also use numpy, so you can just use `loadtxt` or `genfromtxt` to parse the CSV data (This is what I usually do), for instance:

![20200407-212338](https://user-images.githubusercontent.com/25300994/78710492-b79cc480-7915-11ea-9263-fd92cdaeaed0.png)

```python
Vector3DList.fromNumpyArray(numpy.ravel(numpy.loadtxt(file, delimiter = ",", dtype = "f")))
```

Check the documentation on the expression and script nodes for more information.

**Comment by j6k4m8** [comment]
Aha! Didn't know about numpy under the hood. That's excellent! 

> While CSV is a rather popular data format, a pickle isn't, and it is unlikely that external data will exist as a pickle.
This is a great point. And I think a moot point if .npy is supported anyhow!

> The best we could do is to assume numerical data and return a generic list of lists.

I think this itself is already an enormously powerful tool, especially if you can import as, say, list-of-RGB, list-of-HSV, list-of-XYZVector, etc (which allows for checking that `shape` is 3 in one dimension). Or perhaps just importing a list of 3-tuples, which can be `combine`-node'd back into color/vector/etc... Sounds to me like my idea-pitch needs a bit more fine-tuning before it's ready for your review :) Happy to close this issue and I can open a new one when I have a better proposal for you, and/or also happy to use this space to workshop this idea if you think it has merit!

**Comment by OmarEmaraDev** [comment]
Ok, sure. Feel free to work on a proposal for this that is more streamline. You may create a new issue or use this one, up to you.
