### ISSUE TITLE
Issue with getting right context in script node

### ISSUE THREAD

**Issue by denis130** [JacquesLucke/animation_nodes#1390]
I am trying to apply Set Inverse on all the ChildOf Constraints on the armature, using animation nodes Script Node. But when triggering the script I get error an error that says: Cant get constraint data for child of constraint. That was working in previous versions of animation nodes in blender 2.79, but doesnt work in blender 2.82.

```
import bpy

if inverse: 
    oby = bpy.data.objects['metarig2']
    bpy.context.view_layer.objects.active = oby
    pbones = bpy.data.objects['metarig2'].pose.bones

    for pbone in pbones:

        isConstraint = False
        if len(pbone.constraints)>0:
            for const in pbone.constraints:

                if const.type == "CHILD_OF":
                    context_copy = bpy.context.copy()
                    context_copy["constraint"] = pbone.constraints["Child Of"]
                    bname = pbone.bone.name

                    bpy.data.objects['metarig2'].data.bones.active = bpy.data.objects['metarig2'].data.bones[bname]
                    bpy.ops.constraint.childof_set_inverse(context_copy, constraint="Child Of", owner='BONE')

    bpy.data.objects['metarig2'].select = False
    activ = bpy.data.objects['metarig']
    bpy.context.scene.objects.active = activ
```

**Comment by OmarEmaraDev** [comment]
You should avoid using `bpy.ops` operators in Animation Nodes. Perhaps you should check:
https://blender.stackexchange.com/questions/18562/child-ofs-set-inverse-without-using-bpy-ops

**Comment by denis130** [comment]
Im not sure how the answer in that question for the bones in the armature. Why is it a problem to use `bpy.ops` in animation nodes? I just need to trigger it once and its only applied to  the bone rotations on the constraints.

**Comment by OmarEmaraDev** [comment]
Because of the invalid context you might get. I don't really know how this works, so I think you are better of asking in blender.stackexchange.com

**Comment by Clockmender** [comment]
You can switch the 'context area' using this type of code:

```bpy.context.area.type = "VIEW_3D"``` or
```bpy.context.area.type = "GRAPH_EDITOR"``` etc.

Must be in an enumerator range as here:

https://docs.blender.org/api/current/bpy.types.Area.html?highlight=area.type#bpy.types.Area.type

I use this in my own nodes, it works well and I can switch the context.area.type backwards and forwards in a nodes ```execute()``` function. At one point I want to bake sound to an F-Curve so I have to use "VIEW_3D" to get the object and "GRAPH_EDITOR" to bake to the F-Curve. 

Cheers, Clock.

**Comment by denis130** [comment]
This is a solution that I was given on blender stackexchange and its working good:
```
import bpy

if Inverse: 
    rig = bpy.data.objects['metarig2']
    pbones = rig.pose.bones

    for pbone in pbones:
          for const in pbone.constraints:

                if const.type == "CHILD_OF":
                    context_py = {
                        "constraint" : const,
                        "active_object" : rig
                        }

                    bpy.data.objects['metarig2'].data.bones.active = pbone.bone

                    bpy.ops.constraint.childof_set_inverse(context_py, constraint="Child Of", owner='BONE')
```

**Comment by OmarEmaraDev** [comment]
That is good to hear. I will close this for now, let us know if you need anything else.

**Comment by denis130** [comment]
> That is good to hear. I will close this for now, let us know if you need anything else.

Where can I find more information on how the operators are constructed?

**Comment by OmarEmaraDev** [comment]
As far as I know, Blender does not expose this information to the end use. You would need to check the source code of the poll method of the target operator. See those two answers for more information:
https://blender.stackexchange.com/questions/69114/how-do-i-get-the-correct-context-for-python-operators
https://blender.stackexchange.com/questions/6101/poll-failed-context-incorrect-example-bpy-ops-view3d-background-image-add

**Comment by denis130** [comment]
> As far as I know, Blender does not expose this information to the end use. You would need to check the source code of the poll method of the target operator. See those two answers for more information:
> https://blender.stackexchange.com/questions/69114/how-do-i-get-the-correct-context-for-python-operators
> https://blender.stackexchange.com/questions/6101/poll-failed-context-incorrect-example-bpy-ops-view3d-background-image-add

Thanks!
