### ISSUE TITLE
Animate boolean node

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1392]
It's possible to use "animate float" node to do the boolean.
But boolean only shows true and false according to "non-0" and "0".
Meaning If my end value want to be want to be "true", it seems I need to add at least one node to do this.
In such a case, won't that be good to rather get an animate boolean node to shorten the usage of nodes?
![animate boolean node](https://user-images.githubusercontent.com/55994236/79028804-90393800-7b5f-11ea-86cf-accf19f30c01.png)

**Comment by OmarEmaraDev** [comment]
I don't think it makes much sense to add such node. Perhaps you should use a compare node instead.

**Comment by Gerstmann-Bradley** [comment]
> I don't think it makes much sense to add such node. Perhaps you should use a compare node instead.

But to "animate boolean" I still need a compare node in addition to "animate node" group right? I can imagine there are lots of approaches to the solution, but the issue is that I always need to add an extra node to solve the problem.
If there is a chance to reduce the usage of nodes, won't that be good to do so? Even calling such an extra node may take about 1 second during the work, and an extra node definitely generate more noddles.

**Comment by OmarEmaraDev** [comment]
If I understand correctly, you want a boolean that is false from frame 0 to 29 and true from 29 to the end frame. In which case, you can use a single compare node (Frame > 29). How would an animate node work here?

**Comment by Gerstmann-Bradley** [comment]
> If I understand correctly, you want a boolean that is false from frame 0 to 29 and true from 29 to the end frame. In which case, you can use a single compare node (Frame > 29). How would an animate node work here?

I see, thanks.
