### ISSUE TITLE
Question: Spline Falloff with Radii option

### ISSUE THREAD

**Issue by 8BitsGotBite** [JacquesLucke/animation_nodes#1394]
Would it be possible to use the Radii of a Spline, in the Spline Falloff node or would that be technically impossible?

**Comment by 8BitsGotByte** [comment]
That would be fantastic. Thanks a million :)

**Comment by OmarEmaraDev** [comment]
@8BitsGotBite Feel free to provide feedback in #1394.

**Comment by OmarEmaraDev** [comment]
Implemented in 3920e2f.
