### ISSUE TITLE
Remnant of Spline falloff after trim the spline down to 0

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1395]
If I were to trim the spline down to 0, there still would be a remnant of spline falloff at the beginning vertex due to Either "offset" or "Width", If I keep both value to 0, then no falloff will be generated at all.
I think the expected behavior is if the whole spline no longer exist, the falloff shouldn't exist either. Will you be able to solve the issue?

**Comment by OmarEmaraDev** [comment]
Zero trimming still results in a spline, albeit an infinitesimal one, in other words, a point. In which case, the Spline Falloff node acts as a Point Falloff. So, as far as I can tell, this is the expected behavior.

**Comment by Gerstmann-Bradley** [comment]
> Zero trimming still results in a spline, albeit an infinitesimal one, in other words, a point. In which case, the Spline Falloff node acts as a Point Falloff. So, as far as I can tell, this is the expected behavior.

Technically speaking yes. but practically I don't think this is desired?
If the spline has been used for both curve object output and the falloff, trim the spline to 0 will make the spline non-visible on the bevel, but the falloff effect is still seen as a point falloff. I think such an inconsistency is something that need to be dealt with?

**Comment by OmarEmaraDev** [comment]
Yes, sounds reasonable. So you are proposing we return an empty spline from the Trim Spline node when the start and end are equal?

**Comment by Gerstmann-Bradley** [comment]
yes, it sounds great to me

**Comment by OmarEmaraDev** [comment]
Implemented in a4ee0ea.
