### ISSUE TITLE
Matrix update issue

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#140]
Here is an example file: http://www.pasteall.org/blend/36136
A is B's parent, each time I moved A, I see no update on C, which is unlike the other three modes, even restart the file. Unless having to apply something on A (rotation and/or scale).

**Comment by JacquesLucke** [comment]
looks like the parent inverse matrix is only calculated in the moment when you parent 2 objects.. Not sure if this is really an issue or if it is intended by Blender...

**Comment by LeonCheung** [comment]
Confirmed by mont29 (Bastien Montagne), this is an intended behavior, it’s the matrix that allows keeping current world space of child when parenting it. (world space position/scale/rotation, though you can set any matrix here, from py script, if you want).

So, if we want to make it exactly synced with the parent (as the other three sockets do), we have to apply position/scale/rotation all together to keep it right.

Not sure if this is possible / necessary to implement.

**Comment by JacquesLucke** [comment]
I think here is nothing for me to do.
