### ISSUE TITLE
Interpolation-Curve crash

### ISSUE THREAD

**Issue by eestart** [JacquesLucke/animation_nodes#1400]
Blender Ver 2.82.7
AN Ver.2.1.4
Every time using the "Interpolation-Curve" ,AN just crash
If delete it,everything back to normal.
Is that anyone have the same issue?

**Comment by OmarEmaraDev** [comment]
This was already fixed. Please update your Animation Nodes build.

**Comment by eestart** [comment]
> This was already fixed. Please update your Animation Nodes build.
Oh,I`ll try,thx.
