### ISSUE TITLE
applying quaternion operations to all objects in the collection.

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1401]
I'm trying to test the effects quaternion operations have on multiple objects in a collection. 

I'm having trouble applying quaternion operations to all objects in the collection.

My thoughts where to:
1) loop through objects in the collection 
2) apply quaternion operations to all objects in collection
3) see what happens to objects

**I didn't want to use just nodes because I need to use python code to add different complex mathematical operations to it later.**

My thoughts where to get all the objects in a collection then multiply the objects by the quaternion operations and see what effects it has on the objects.  

I'm using animation nodes 2.1.7 on Blender 2.82a

![screenshot-April-22-2020-12:53:04](https://user-images.githubusercontent.com/28985314/80011047-4aeb0380-8499-11ea-90c8-ee73430b511d.png)

Python code below along with blend file.
[quat_eq01.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4517783/quat_eq01.blend.zip)

```
import math
import sys
import mathutils
import numpy as np
from math import radians

def quat_rot_axis(deg_to_change):
    new_angle_rad = np.deg2rad(deg_to_change)
    w_rot = np.cos(new_angle_rad/2)
    i_rot = np.sin(new_angle_rad/2)*0
    j_rot = np.sin(new_angle_rad/2)*1
    k_rot = np.sin(new_angle_rad/2)*0
    return w_rot,i_rot,j_rot,k_rot

w_rot,i_rot,j_rot,k_rot = quat_rot_axis(deg_to_change)


# ---- Create Quaternion
quat1 = mathutils.Quaternion((w_rot, i_rot, j_rot, k_rot))


# ---- Normalize Quaternions and get individual Quaternion values
quat1_norm = quat1.normalized()
quat1_norm_inv = quat1_norm.conjugated()

print(quat1_norm)
w_quat1 = quat1_norm[0]
i_quat1 = quat1_norm[1]
j_quat1 = quat1_norm[2]
k_quat1 = quat1_norm[3]
print("w_quat1=%s" % w_quat1)
print("i_quat1=%s" % i_quat1)
print("j_quat1=%s" % j_quat1)
print("k_quat1=%s" % k_quat1)

# ---- Calc new Quaternion object location 
#quat1_new = quat1_norm * object 
#quat1_new = quat1_norm * object * quat1_norm_inv)
```

**Comment by OmarEmaraDev** [comment]
I am not entirely sure what you are asking. Wouldn't a loop be sufficient to apply the same setup to multiple objects?

**Comment by stillpointx** [comment]
Yes I'm just having trouble applying / combining the python and quaternion operations to all objects in the collection. 

**I didn't want to use just nodes because I need to use python code to add different complex mathematical operations to it later.**

**Comment by jingle1000** [comment]
I'm also confused as to how to apply operations to all items in a collection. I'm trying to move all objects in a "collection info" node (vector multiplication on each object's position). The position is calculated based on the current frame number times the vector multiplication function. 
I don't have the frame info setup but this is what I have so far:
![image](https://user-images.githubusercontent.com/11929724/80206326-1b9fd800-85fa-11ea-8658-6305f55d4049.png)

**Comment by stillpointx** [comment]
Please don't hijack questions by asking another question.

**Comment by jingle1000** [comment]
@stillpointx Sorry, not trying to hijack. If I am reading your question correctly, we are both trying to figure out **how to apply operations on all objects inside a "collection info" node**. I would like to do vector operations on the position, you would like to do quaternion operations. The overarching issue here is a lack of documentation on how to use that node.

**Comment by OmarEmaraDev** [comment]
Loops can be used to apply the same operation to multiple objects, see the documentation on loops:
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html

However, a lot of the nodes are vectorized, so loops will not be needed. See the documentation on vectorization:
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/getting_started/data.html#vectorized-sockets

**Comment by stillpointx** [comment]
@jingle1000  no worries this video should help https://youtu.be/YJ5ksvlTKUM 

@OmarEmaraDev Thanks!!  Those loop / invoke sub-programs nodes get me ever time.
