### ISSUE TITLE
Strange interface error and chain of problems

### ISSUE THREAD

**Issue by prof-jerz** [JacquesLucke/animation_nodes#1402]
I spent about 5 hours today learning Animation Nodes and loved it. I'm trying to generate random titles for an infinite library of books.  I was moving along very nicely when for some reason every time I left-clicked with the mouse in the 3D viewer, I got the delete confirmation box. 

I reloaded factory settings (which fixed the strange interface problem) and re-activated all my plugins, after which Animation Nodes would no longer work. 

I saw a reference to looking in the 'Problem panel" but I had no idea what that was or how to find it. 

I uninstalled AN and reinstalled it twice. Now, even when I start a new blender file, the AN screen has the red line, and the AN node menu reads "View Select Add Node Subprogram Subprogram Subprogram Subprogram Subprogram Subprogram Subprogram. When I mouse over any of the "Subprogram" menu items, all the options are grayed out with the message "There are no subprograms yet."

There are also 7 grayed out "Remove" items at the rightmost end of the menu.

I followed the instructions -- disable the plugin, then restart Blender, then uninstall the plugin. 

Now the red box is gone, but the contents of my Node Animator trees have disappeared from the file i was working on when all this went wrong.

I have no idea what caused this chain of problems, but thought I'd report it.

I loved what I saw Node Animator doing and shall continue to try to recover what I had achieved before it all fell apart.

**Comment by OmarEmaraDev** [comment]
We can't really fix a problem that we can't reproduce. So the best thing you can do is report it again as it happens. When you see a red border around Animation Nodes, look in the console and attach the its contents here, this should help us identify the problem.
