### ISSUE TITLE
some "warnings" in complie AN on ubuntu16.04

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1404]
![2](https://user-images.githubusercontent.com/64368228/80468147-68284200-8971-11ea-87c0-45bbc3d7cecc.png)
![3](https://user-images.githubusercontent.com/64368228/80468185-75453100-8971-11ea-8a4d-8000c6847c8a.png)
![4](https://user-images.githubusercontent.com/64368228/80468206-7b3b1200-8971-11ea-8afe-9e637ccb11b4.png)
![5](https://user-images.githubusercontent.com/64368228/80468281-90b03c00-8971-11ea-98a1-7c1ac280cc55.png)
![6](https://user-images.githubusercontent.com/64368228/80468299-96a61d00-8971-11ea-9395-117fed8f62cb.png)
![7](https://user-images.githubusercontent.com/64368228/80468329-9efe5800-8971-11ea-8efb-04eada9bdc0b.png)
![8](https://user-images.githubusercontent.com/64368228/80468350-a4f43900-8971-11ea-97de-00b208565a3e.png)
![9](https://user-images.githubusercontent.com/64368228/80468371-aa518380-8971-11ea-9f8f-58ccce530d0c.png)
![10](https://user-images.githubusercontent.com/64368228/80468384-b0476480-8971-11ea-9209-bcab35d77158.png)
![11](https://user-images.githubusercontent.com/64368228/80468404-b6d5dc00-8971-11ea-9566-abd72a951de8.png)
![1](https://user-images.githubusercontent.com/64368228/80468420-bccbbd00-8971-11ea-9978-09c6b62db9ca.png)

**Comment by OmarEmaraDev** [comment]
They are harmless warnings, don't worry about it.

**Comment by kdsin23** [comment]
> They are harmless warnings, don't worry about it.

oh,Thank you!
