### ISSUE TITLE
where to import "ParticleSystem" ?

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1407]
```
def GetParticles(ParticleSystem Psystem):
    cdef Py_ssize_t i
    cdef Py_ssize_t count = len(Psystem.particles)
    cdef ParticleList = list(length = count)
    for i in range(count):
        ParticleList.append(Psystem.particles[i])
    return ParticleList
```

it gave me an error: "'ParticleSystem' is not a type identifier", so i add "from ... data_structures cimport ParticleSystem" to the head of code ,but it doesn't work yet!
i want to know where to import a ParticleSystem data_structure ,or how to identify a type of ParticleSystem. could you help me? thank you!

**Comment by OmarEmaraDev** [comment]
I am guessing you want the Blender `ParticleSystem` type. In which case, you can import it from `bpy.types`.

**Comment by kdsin23** [comment]
> I am guessing you want the Blender `ParticleSystem` type. In which case, you can import it from `bpy.types`.

Thank you for your reply! i tried to add "from bpy.types import ParticleSystem",but it has the same problem  "'ParticleSystem' is not a type identifier",i don't know how to fix it.

**Comment by OmarEmaraDev** [comment]
Are you looking for `ParticleSystems` with an "s" at the end.

**Comment by kdsin23** [comment]
> Are you looking for `ParticleSystems` with an "s" at the end?

yes,I had checked many times,but it doesn't work still,always appearing "'ParticleSystems' is not a type identifier".I was confused about this.
