### ISSUE TITLE
Option for "object controller falloff - sphere" not scaled by object

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1408]
In sphere mode of object controller falloff, scaling of the object will scale the falloff as well.
Sometimes it's desired, but some other time I only use the object to keyframe and knowing where it actually locates. In such a case I scale the object for better viewing, because the scale of my other objects in the scene maybe very large or so, but I want to keep the falloff small. Thus, I don't want the scale of my object to actually effect my falloff. (It's true I can use negative offset to cancel such a scaling, but it seems hard to do numerically correct.)
Currently, to solve the object, I plug "object transform input" node into the location of "point distance falloff" node, and purely use size and width to regulate falloff's width.
I hope this can be done more easily with an option that decides whether to use object's scale to effect the falloff, in "object controller falloff" node.

**I am only talking about the "sphere mode" at this moment.

**Comment by JacquesLucke** [comment]
Seems fine to add an option for that. It could be a hidden input by default.

**Comment by OmarEmaraDev** [comment]
I just realized that you can change the display size of empties from the Empty Data panel. It is called the Empty Display Size property. In this case, I think this option would be redundant. @Gerstmann-Bradley Is this solution satisfactory?

**Comment by Gerstmann-Bradley** [comment]
> I just realized that you can change the display size of empties from the Empty Data panel. It is called the Empty Display Size property. In this case, I think this option would be redundant. @Gerstmann-Bradley Is this solution satisfactory?

Personally I think it's a little different than directly control from viewport (by hitting S). But I also think it may just be something that I need to get used to. So maybe you are right. I am closing this.
