### ISSUE TITLE
The Combine Quaternion node automatically normalizes data how can I avoid this?

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1409]
The Combine Quaternion node is automatically normalizing data is there away to have it not do this? I'm using the operation for Rotation & scaling: **Pout = q * Pin * conj(q)**  and **Pout = q * Pin** but when I put in the **(Pin)** x,y,z = (the vector representing axis of rotation) which is **0,1,2,3** it automatically normalizes it.  I was hoping that the value for **Pin** would be **(w=0, i=1,j=3,k=4)**

Is there a work around?

I'm working from the website below I want to animate different operations which involve quaternions and diffferent axis to rotate around. 
https://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/index.htm

![screenshot-April-29-2020-11:22:33](https://user-images.githubusercontent.com/28985314/80615397-9f4c3100-8a0d-11ea-9e5e-8fec5171d58d.png)

I'm running Blender 2.82a and AN 2.1.7

**Comment by OmarEmaraDev** [comment]
You can just write this `Quaternion((0, 1, 2, 3))` in an expression node.

**Comment by stillpointx** [comment]
Thanks!
