### ISSUE TITLE
Suggestion: "Use Nodes" toggle

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#141]
Sometimes, for some reason, we want to temporarily disable AN, but it seems not that simple (or I just didn't know how?). So I htink it would be very convenient that we could have a "Use Nodes" toggle on the header, which is like the other three node systems. FYI. :)

**Comment by kopias** [comment]
​​
​funny I was going to suggest this yesterday. Didn't had time :)

**Comment by LeonCheung** [comment]
LOL, What's more funny is I was about to do it yesterday as well. :P
Each time, I have to toggle off all five toggles on the Performance panel.

![performance](https://cloud.githubusercontent.com/assets/494788/7722338/b3890c88-ff11-11e4-922a-49f79285c200.jpg)

Yeah, it works for sure. But still not soooo convenient, huh? :)

**Comment by JacquesLucke** [comment]
this can also become part of this: https://github.com/JacquesLucke/animation_nodes/issues/142#issuecomment-103819780
