### ISSUE TITLE
Compiling error on ubuntu18.04!

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1410]
using the conda tool to compile the AN,appering some errors:
![compile error](https://user-images.githubusercontent.com/64368228/80737592-55b33180-8b46-11ea-8aae-f277d5446290.png)

I need some help,thank you!

**Comment by OmarEmaraDev** [comment]
I don't use Conda, so I can't debug this right now. Does this happen while compiling FastNoiseSIMD?

**Comment by kdsin23** [comment]
> I don't use Conda, so I can't debug this right now. Does this happen while compiling FastNoiseSIMD?

yes,it is.i tried to install gcc+ in conda,but failed.

**Comment by OmarEmaraDev** [comment]
Can you replace `gcc` with `${CXX:-gcc}` in the file `animation_nodes/libs/FastNoiseSIMD/source/compile_linux.sh` and try and see it works.

**Comment by kdsin23** [comment]
> Can you replace `gcc` with `${CXX:-gcc}` in the file `animation_nodes/libs/FastNoiseSIMD/source/compile_linux.sh` and try and see it works.

sorry,it still doesn't work! here is an error message below:

```
gcc -pthread -B /home/plug/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I
/home/plug/download/blender/AN_BLUEFOX-AN-bluefox/animation_nodes/libs/FastNoiseSIMD/source -I/home/plug/anaconda3/include/python3.7m -c /home/lvan/download/blender/AN_BLUEFOX-AN-bluefox/animation_nodes/libs/FastNoiseSIMD/wrapper.cpp -o build/temp.linux-x86_64-3.7/home/plug/download/blender/AN_BLUEFOX-AN-bluefox/animation_nodes/libs/FastNoiseSIMD/wrapper.o -g0 -std=c++11
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1
```
