### ISSUE TITLE
In blender 2.82

### ISSUE THREAD

**Issue by medium-9** [JacquesLucke/animation_nodes#1411]
Working with "https://www.youtube.com/watch?time_continue=570&v=8SMFucF-SC8&feature=emb_title" tutorial. Tried appending scene with his rigid body present file. That's when the report was generated. I assume this is something regarding his preset vs your add-on. I'll scour for a legacy edition of your AN add-on to see if I can get it to work again.

**Comment by OmarEmaraDev** [comment]
What "report" are you talking about exactly?
