### ISSUE TITLE
Animation Nodes 2 freezes with Python Script(Multithreading)

### ISSUE THREAD

**Issue by starzar** [JacquesLucke/animation_nodes#1412]
Trying to display **NestedLoops(at least two) Python script output ("Timer") i**n 3dView from AN's(Animation Nodes2.0.4) Subprogram/Script Node.

> **_ATTEMPT 1 - Running Loop in Main Thread_**

AN freezes (0000ms-no updation in the tick loop).

```
#Python Script

#Import 
import time

#Assign 
i= 0
j = 0
timer = ""

#Timer Loop
for i in range(3):
    for j in range(2): 
       # access "Timer" value in AN
        timer = "i : j = {}:{}".format(i,j)
        print(timer)
        sleep(0.5)

```

![AN_crash_cache](https://user-images.githubusercontent.com/38550930/80792530-44a00a00-8bb2-11ea-970a-b299ebc5582b.gif)
`
 **

> **_ATTEMPT 2 -AN not recognising "Global List"values in Multithreaded script_**

**
On creating the Timer in a separate thread , AN didn't recognise the filled global Timer list().
So ,in this new script , on loading a "Queue" in a Worker thread and passing the queue values to the  "Timer" list (initialised "Global" and exists in the Main Thread), AN  still doesn't recognise the  Timer list.The GetListElement and GetListLength Nodes  are shown as empty and "0" respectively ,**_eventhough the list is full._** 

![threaded list not recognised by AN](https://user-images.githubusercontent.com/38550930/81064209-e72ff400-8ef6-11ea-88e5-0d8bffa3aebb.jpg)

![ANThreadingQueue](https://user-images.githubusercontent.com/38550930/80917199-16b9f180-8d7b-11ea-8466-0228f9d39482.gif)

    #################  Mutlithreaded Script using "Queue"  ###################
    #Import 
    import threading 
    from queue import Queue
    from time import sleep

    #Initialise 
    timer = []  #"timer" initialised and passed to Animation Nodes 

    #Spawn Thread
    def Queue_load(queue,lock):
        i= 0
        j = 0
       
        for i in range(3):
            for j in range(2):
                with lock: 
                    t= 'timer -->{}:{} (queue loaded in {} & printed from Main)'
                    t_str = str(t.format(i,j,threading.current_thread().name))
                    

                    #Orignially Timer loaded from this thread but not recognised by AN
                    # timer.append = t_str
                    # sleep(0.5)

                #Queue used as Timer from this thread  was not recognised by AN 
                    #Queue_load
                    queue.put(t_str )
                    queue.task_done()

    #Main Thread      
    if __name__ == "__main__":     
        print("START MAIN") 

    #Start and join thread , queue & lock   
        q = Queue()
        lock = threading.Lock()

        t = threading.Thread(target = Queue_load,args=(q,lock,))

        print('thread count:', threading.active_count())
        print('thread enum:', threading.enumerate())
        print('mainthread:', threading.main_thread())
        print('currentthread:', threading.current_thread())

        t.start()

        t.join()

        q.join()

    #Load Timer with Queue values    
        q_qsize = q.qsize()
        q_int = int(q_qsize)
        print('Queue size = ' + str(q_qsize ))

        timer = list(q.queue)
        print('\n'.join('{}' for _ in range(len(timer))).format(*timer))

        print("END MAIN")

   #################   Blender texteditor(Console Output)   ################### 

    START MAIN
    thread count: 1
    thread enum: [<_MainThread(MainThread, started 1364)>]
    mainthread: <_MainThread(MainThread, started 1364)>
    currentthread: <_MainThread(MainThread, started 1364)>
    Queue size = 6
    timer -->0:0 (queue loaded in Thread-13 & printed from Main)
    timer -->0:1 (queue loaded in Thread-13 & printed from Main)
    timer -->1:0 (queue loaded in Thread-13 & printed from Main)
    timer -->1:1 (queue loaded in Thread-13 & printed from Main)
    timer -->2:0 (queue loaded in Thread-13 & printed from Main)
    timer -->2:1 (queue loaded in Thread-13 & printed from Main)
    END MAIN

**Comment by OmarEmaraDev** [comment]
Animation Nodes is freezing because it is blocked by the execution of your script. Animation Nodes have to wait until the script finish executing before it can resume execution.

**Comment by starzar** [comment]
@OmarEmaraDev Updated question with new Multithreaded Script for unblocking the Main Loop,but AN still not rendering script "Text" .

**Comment by starzar** [comment]
@OmarEmaraDev  - With a new multithreaded script, AN  is still not recognising the "Global list elements " eventhough the list is full.
