### ISSUE TITLE
Possible to keep original modifier when using "copy object data"?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1413]
To instance multiple object using "object instancer node", I can use "copy object data" node.
This node, however, won't copy modifier with it. Rather, all children objects will inherent the modifier from the "object instancer", when "copy full object" has been turned on.

I suppose this proposal will be very hard and even difficult, but what's your opinion?

**Comment by OmarEmaraDev** [comment]
Modifiers are object data, not mesh data, so it wouldn't make sense to copy Modifiers along with the mesh data in the *Copy Object Data* node.

**Comment by Gerstmann-Bradley** [comment]
> Modifiers are object data, not mesh data, so it wouldn't make sense to copy Modifiers along with the mesh data in the _Copy Object Data_ node.

I understand, but I want to know is there an approach to do such kind of function?
I think this is somehow important, because modifier is also procedural that I may not want to apply them.

**Comment by OmarEmaraDev** [comment]
What are you proposing? A *Copy Object Modifiers* node?

**Comment by Gerstmann-Bradley** [comment]
> What are you proposing? A _Copy Object Modifiers_ node?

Oh, that sounds great, is that possible?

**Comment by OmarEmaraDev** [comment]
It should be possible. Just not sure if it will be sufficiently efficient.

**Comment by JacquesLucke** [comment]
I'm not sure I fully understand the problem you are trying to solve here. Can you describe the problem again, and maybe give an example use case?

**Comment by Gerstmann-Bradley** [comment]
> I'm not sure I fully understand the problem you are trying to solve here. Can you describe the problem again, and maybe give an example use case?

Here is an example. I want to copy different object using "object instancer". So I used "copy object data" node.
However, because the initially instanced cube has a "bevel modifier", the "instanced icosphere" must also contain a bevel modifier as shown. In reality, Perhaps I want bevel modifier on cube and subdivision on icosphere, instead of them sharing completely the same modifier.
Also a note. Currently I solve this issue using an alternative way of instancing, but it may still not completely replace the nature of "object instancer" node. I am not sure.
![Example](https://user-images.githubusercontent.com/55994236/89771478-5f95ea80-dace-11ea-85f2-7cdd6338aad7.png)

**Comment by OmarEmaraDev** [comment]
Implemented in 3077c3d. Thanks for the suggestion!
