### ISSUE TITLE
Possible to keep UV Map when transforming the meshes list

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1414]
![uv error](https://user-images.githubusercontent.com/64368228/81029515-d7dd8600-8eb7-11ea-8eb7-3021f11099ad.png)

when transform the mesh list ,why the "UV Map" is None,is it possible to generate the uv?i think if possible,it is good for us to texture.

**Comment by OmarEmaraDev** [comment]
It seems the append method of the mesh structure doesn't support UVs. Thanks for the report!

**Comment by OmarEmaraDev** [comment]
Fixed in 1a73bec.
