### ISSUE TITLE
Why numpy code is so slow?

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1416]
it is said that the numpy is much faster  than python,but why not in this script:
![vecs to cols](https://user-images.githubusercontent.com/64368228/81180631-e2923b00-8fdd-11ea-9865-3d22c0fd4a4b.png)

Obviously,the python code is ten times faster than numpy code,what is wrong?

**Comment by OmarEmaraDev** [comment]
To get a numpy array from a Vector List, you can use the `asNumpyArray` method. To get a Color List from a numpy array, you can use the `fromNumpyArray` method. This should reduce the python overhead significantly.

**Comment by harisreedhar** [comment]
> To get a numpy array from a Vector List, you can use the `asNumpyArray` method. To get a Color List from a numpy array, you can use the `fromNumpyArray` method. This should reduce the python overhead significantly.

Is asNumpyArray method of Vector3DList ?

**Comment by OmarEmaraDev** [comment]
@harisreedhar Yes, all numeric lists in Animation Nodes have an `asNumpyArray` method. Similarly, All numeric list classes have a `fromNumpyArray` class method.

**Comment by harisreedhar** [comment]
> @harisreedhar Yes, all numeric lists in Animation Nodes have an `asNumpyArray` method. Similarly, All numeric list classes have a `fromNumpyArray` class method.

Thanks, Is there any way to know available functions of class?

**Comment by OmarEmaraDev** [comment]
@harisreedhar If you mean in python in general, you can use the `dir` function, which will return a list of the names of all the methods and attributes of an object. For instance:

```python
>>> a = [1, 2, 3]
>>> dir(a)
['sort', 'reverse', 'remove', 'pop', 'insert', 'index', 'extend', 'count', 'copy', 'clear', 'append', '__subclasshook__', '__str__', '__sizeof__', '__setitem__', '__setattr__', '__rmul__', '__reversed__', '__repr__', '__reduce_ex__', '__reduce__', '__new__', '__ne__', '__mul__', '__lt__', '__len__', '__le__', '__iter__', '__init_subclass__', '__init__', '__imul__', '__iadd__', '__hash__', '__gt__', '__getitem__', '__getattribute__', '__ge__', '__format__', '__eq__', '__doc__', '__dir__', '__delitem__', '__delattr__', '__contains__', '__class__', '__add__']
```

**Comment by harisreedhar** [comment]
> @harisreedhar If you mean in python in general, you can use the `dir` function, which will return a list of the names of all the methods and attributes of an object. For instance:
> 
> ```python
> >>> a = [1, 2, 3]
> >>> dir(a)
> ['sort', 'reverse', 'remove', 'pop', 'insert', 'index', 'extend', 'count', 'copy', 'clear', 'append', '__subclasshook__', '__str__', '__sizeof__', '__setitem__', '__setattr__', '__rmul__', '__reversed__', '__repr__', '__reduce_ex__', '__reduce__', '__new__', '__ne__', '__mul__', '__lt__', '__len__', '__le__', '__iter__', '__init_subclass__', '__init__', '__imul__', '__iadd__', '__hash__', '__gt__', '__getitem__', '__getattribute__', '__ge__', '__format__', '__eq__', '__doc__', '__dir__', '__delitem__', '__delattr__', '__contains__', '__class__', '__add__']
> ```

Thank you

**Comment by kdsin23** [comment]
> To get a numpy array from a Vector List, you can use the `asNumpyArray` method. To get a Color List from a numpy array, you can use the `fromNumpyArray` method. This should reduce the python overhead significantly.

Thank you very much!  does the "GenericList " have the `asNumpyArray`method?

**Comment by OmarEmaraDev** [comment]
GenericList is a python lists, not a CList, so no.

**Comment by kdsin23** [comment]
> GenericList is a python lists, not a CList, so no.

much appreciate! another question is that can we write a Numpy array in `.pyx` file like this:

`cdef nd.array array_b = Vector3DList.asNumpyArray(vectors)`

or how can we `cdef` a numpy array in the cython? 
thank you!

**Comment by OmarEmaraDev** [comment]
@kdsin23 Read the Cython documentation on the topic:
https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html
