### ISSUE TITLE
Single input that's not a list won't be recognized by "get list length" node.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1418]
This maybe a dumb request.
I sometimes use get list length node to know if the socket has an input. and its result will feed into switch. So if I input a value into the socket, then finally the result will return A, or if I didn't use that socket, it will return B.
This method works for the list input. but won't work for a "non-list input" as shown.
It's definitely doable to convert it into a list use "create list" series. But personally speaking I think it makes more sense to me if it can recognize a single input and convert it into a list by its own?

![get list length](https://user-images.githubusercontent.com/55994236/81238593-72c98380-8fd0-11ea-9793-a5bdf59dad3d.png)

**Comment by OmarEmaraDev** [comment]
I am not entirely sure what you are asking. Do you want it to return 1 instead of zero for non lists?

**Comment by Gerstmann-Bradley** [comment]
> I am not entirely sure what you are asking. Do you want it to return 1 instead of zero for non lists?

Yes, exactly.

**Comment by Gerstmann-Bradley** [comment]
> I am not entirely sure what you are asking. Do you want it to return 1 instead of zero for non lists?

Oh, wait, I realize it won't be possible.
"get list length" will count 1 even I didn't input anything into the element.
![Issue](https://user-images.githubusercontent.com/55994236/81278810-2f990000-9024-11ea-9a35-4a3cac99cd34.png)

**Comment by OmarEmaraDev** [comment]
What is your use case exactly?
