### ISSUE TITLE
why consol appers this message

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1419]
![ter](https://user-images.githubusercontent.com/64368228/81275695-9cdc7d80-9084-11ea-86c1-33bf8c1b75e0.png)

when add this node to the scene, the consol come out this message, is this broken for this node?

**Comment by OmarEmaraDev** [comment]
Are you sure you don't have a print statement somewhere?

**Comment by harisreedhar** [comment]
> ![ter](https://user-images.githubusercontent.com/64368228/81275695-9cdc7d80-9084-11ea-86c1-33bf8c1b75e0.png)
> 
> when add this node to the scene, the consol come out this message, is this broken for this node?

I think u are using c_utils.pyx from my build, it has a print statement i forgot to delete.

**Comment by kdsin23** [comment]
> Are you sure you don't have a print statement somewhere?

Thank you!

**Comment by kdsin23** [comment]
> > Are you sure you don't have a print statement somewhere?
> 
> Thank you! it has been fixed! it exactly has a print statement,and i deleted it.
