### ISSUE TITLE
Suggestion: Node Tree Manager panel

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#142]
I know, it is recommended to use one nodes at the same time, However, for better organization on more complex scene, it would be a good way to split a giant node tree into several individual ones. Currently, all node trees are all on work at the same time regardless whether or not it is currently shown in the Node editor.

Can we imagine a Node Tree Manager panel, in which we could enable or disable individual node trees? (something like the layer manager addon or outliner)

**Comment by kopias** [comment]
didn't test it that well but i think sverchok handles this pretty well
maybe its worth investigation...

**Comment by JacquesLucke** [comment]
After I finished the curve sockets/nodes I plan to update some stuff in the core execution system. Shouldn't break existing files I hope.
This can be part of it. 
Also maybe I found a way to speed up the node tree drawing in the interface. Sometimes it becomes a bit slow when there are many nodes.
