### ISSUE TITLE
How to use asNumpyArray method in euler list?

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1420]
I'm getting an error "`Cannot create memoryview for this type(NotImplementedError)`" when using asNumpyArray method in euler list. 

![rotaionasNumpyarray](https://user-images.githubusercontent.com/46858047/81421723-8b23d480-916f-11ea-937d-7450f9f6df91.png)

**Comment by OmarEmaraDev** [comment]
An EulerList is special in this case because it doesn't have a primitive buffer type, because each euler element includes a special order value. Due to this we can't use the `asMemoryView` method and consequently the `asNumpyArray` method.

**Comment by harisreedhar** [comment]
Ok 😪
