### ISSUE TITLE
Attribute Input Node not working with custom properties

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1421]
![attribute input](https://user-images.githubusercontent.com/46858047/81492610-d3014380-92b6-11ea-8def-d247f6676845.png)

**Comment by OmarEmaraDev** [comment]
I can't replicate this. Can you share the blend file?

**Comment by harisreedhar** [comment]
I'm using 2.83 build from Bone studio.
[Custom_attribute.zip](https://github.com/JacquesLucke/animation_nodes/files/4605420/Custom_attribute.zip)

**Comment by OmarEmaraDev** [comment]
You are setting a mesh data block custom attribute but reading an object one. Animation Nodes only supports object custom attributes.

**Comment by harisreedhar** [comment]
Thanks
