### ISSUE TITLE
Vertex normals have values higher than 1.

### ISSUE THREAD

**Issue by hitrpr** [JacquesLucke/animation_nodes#1422]
Here the problem. Some veterx normals have vectors with higher than 1 values.
It is strange: when I copy generated object it have proper normal values.
Please check.

![37172913](https://user-images.githubusercontent.com/21099918/81526258-d00e5d80-935f-11ea-8b48-b125d3950ee9.jpg)
[unnormal.zip](https://github.com/JacquesLucke/animation_nodes/files/4607655/unnormal.zip)

**Comment by OmarEmaraDev** [comment]
The node just doesn't guarantee normalized normals I think, you have to normalize them manually.

**Comment by hitrpr** [comment]
Okay, thanks for reply. It works.

**Comment by OmarEmaraDev** [comment]
Because it it is not always needed, so we save time by not performing it.

**Comment by hitrpr** [comment]
Oh, okay. Then all is fine.
