### ISSUE TITLE
Using Python Dictionaries in Subprograms

### ISSUE THREAD

**Issue by starzar** [JacquesLucke/animation_nodes#1423]
For a Text(typewriter)animation , a "typewritertext" node group was created.This group needs to be triggered with appropriate text input and a time delay **_inorder to match the voice narration._**   

![ANdelay](https://user-images.githubusercontent.com/38550930/81771405-7a24eb80-9500-11ea-8f55-4e59cb420035.jpg)

For this purpose, a **_Python "dict" would be a perfect datastructure as it could hold the delay time and the corresponding text input to be displayed ._**

Is using Python Dict's possible in Subprograms?

Code would be something like this -   
```
#initialise
delay = 0.0
text = " "

#delay = bpy.data.node_groups["typewritertext"].nodes["Delay Time"].inputs[1].value
#text = bpy.data.node_groups["typewritertext"].nodes["Data Input"].inputs[0].value 


# Use dictionary struture text_dict = {delaytime : text}
text_dict = {
0.00 : "Start this text at frame 1 " # display this text in 3d view at @delaytime = 0.00
20.00 : "Start this text at frame 20"
50.00 : "Start this text at frame 50"
}

delay = text_dict.items()
text =  text_dict.values()
```

**Comment by OmarEmaraDev** [comment]
Do you mean using an expression or a script node?

**Comment by starzar** [comment]
A Script node (or even a Loop node iterator)  ,which would  iterate the dict (containing the delay_time and text values) and provide delay_time based input to AN.

**Comment by OmarEmaraDev** [comment]
Ok. What is the difficulty of using such nodes in a subprogram?

**Comment by starzar** [comment]
Tried implementing a Python Dict with the Script Node ,but AN didn't recognise the delay_time which was provided as a Dict index. In case of Loop Node,not sure how to implement a Dict with this node.

**Comment by OmarEmaraDev** [comment]
I am sorry, I am still not entirely sure what the problem is.
