### ISSUE TITLE
How to get the return value of objectTransformsOutputNode?

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1425]
bpy.data.node_groups.new("NodeTree","an_AnimationNodeTree")
bpy.data.node_groups['NodeTree'].name='MyNodeTree'
ng = bpy.data.node_groups['MyNodeTree']   
objectTransformsOutput= ng.nodes.new("an_ObjectTransformsOutputNode")
myobjs= objectTransformsOutput01.outputs[0].getValue()

But it shows myobjs is none. How to correct the problem?

**Comment by OmarEmaraDev** [comment]
Outputs don't really have values. What are you trying to do?
