### ISSUE TITLE
Mesh loft render

### ISSUE THREAD

**Issue by benny7770** [JacquesLucke/animation_nodes#1426]
Hi!

Love the update on animation nodes. 
I have lofted a mesh across 7 splines and animated the spline vertexs. However Blenders render engines, both eevee and cycles do not render the change in the mesh from the animated splines on "Object" mode.  However it does render the animated splines properly with all splines selected and in "edit" mode. Is this a bug? or a limitation?

**Comment by OmarEmaraDev** [comment]
Can you share a minimal blend file to replicate the issue?

**Comment by benny7770** [comment]
[example 1.zip](https://github.com/JacquesLucke/animation_nodes/files/4634521/example.1.zip)


Here you go. Thanks for looking at this.

**Comment by OmarEmaraDev** [comment]
I can replicate the issue. Thanks for reporting!
This seems like a leftover issue from #1294.

**Comment by OmarEmaraDev** [comment]
How does one animate a spline in Blender?

**Comment by benny7770** [comment]
By Animating the vertex of a spline with Animall add on . I say spline but I think I mean Bézier curve.

**Comment by OmarEmaraDev** [comment]
Fixed in 0c2378c.
