### ISSUE TITLE
Execution fails v2.1.4 

### ISSUE THREAD

**Issue by desertbeaver** [JacquesLucke/animation_nodes#1428]
Blender v2.81.16
AN v2.1.4

3d viewer nodes fail to execute from Distribute Matrices node and all subsequent nodes. 
"The Animation Nodes add-on is not able to setup the execution units for the node tree....."

**Comment by 3DSinghVFX** [comment]
Please use the latest version v2.1.7 of Animation Nodes, you can download from https://animation-nodes.com/

**Comment by Gerstmann-Bradley** [comment]
Also to add that,
at least the curve interpolation node no longer works for version earlier than blender 2.82.
(Maybe there some other nodes no longer work as well.)
Maybe you want to update your blender as well.
