### ISSUE TITLE
Script: names of inputs and variables do not match

### ISSUE THREAD

**Issue by hitrpr** [JacquesLucke/animation_nodes#1429]
Here you can see, that I named variables starting with lowercases, but inputs starts with uppercases.

![37722034](https://user-images.githubusercontent.com/21099918/82127584-68bc3780-97bd-11ea-8235-20c8f4132806.jpg)

**Comment by OmarEmaraDev** [comment]
This is just how Animation Nodes works. Most programming conventions start variables with lower case letters, and most UIs start with uppercase letters so AN does that automatically.

**Comment by hitrpr** [comment]
Oh, I see. But it still confusing.

**Comment by OmarEmaraDev** [comment]
We will make sure to add that to the documentation.
