### ISSUE TITLE
AttributeError: object has no attribute 'resolution'

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1431]
why the spline object has no attribute 'resolution'? i want to get sample points on the spline,so my code is like this:

```
def evalSpline(self, spline, samples, start, end):
        spline.ensureUniformConverter(self.resolution)
        evalRange = range_DoubleList_StartStop(samples, start, end)
        parameters = FloatList.fromValues(evalRange)
        parameters = spline.toUniformParameters(parameters)

        return spline.samplePoints(parameters, False, 'RESOLUTION')
```
i don't know what is wrong with the code,thank you!

**Comment by OmarEmaraDev** [comment]
I am guessing you are trying to follow the code in the *Evaluate Spline* node. In which case, note that `self` here refers to the evaluate node not the spline itself. `resolution` in this case would be the advanced node setting.

**Comment by kdsin23** [comment]
> I am guessing you are trying to follow the code in the _Evaluate Spline_ node. In which case, note that `self` here refers to the evaluate node not the spline itself. `resolution` in this case would be the advanced node setting.

Thank you! the problem has been fixed!
