### ISSUE TITLE
Undoing a connection doesn't unhide the range selectors.

### ISSUE THREAD

**Issue by Bunpasi** [JacquesLucke/animation_nodes#1433]
When connecting the "Object Transforms Input" to a "Separate Euler" it hides the three range values, but when hitting CTRL + Z, is doesn't unhide them. If I manually disconnect them, it does work.

![Naamloos 2](https://user-images.githubusercontent.com/58082391/82267651-45d08580-996d-11ea-95c8-04b4f26f8765.png)

**Comment by OmarEmaraDev** [comment]
I noticed this as well. I will take a look later.
