### ISSUE TITLE
Object Material Output shuts down blender with object with mulitple materials

### ISSUE THREAD

**Issue by Bunpasi** [JacquesLucke/animation_nodes#1435]
When I use the "Object Material Output", my Blender shuts downs under certain circumstances. This is the minimum amount of steps I could have to reproduce the problem.

- open new project
- add second material to default cube by clicking plus and new
- open animation nodes
- create a new node tree
- add an 'Object Material Output' node
- hit right eye dropper to assign currently selected object

If I disable the 'Always' auto execution this problem doesn't occur. I hope I've described the problem well enough.

**Comment by OmarEmaraDev** [comment]
I can't replicate the issue. Can you try the latest Blender daily build and the latest Animation Nodes?

**Comment by Bunpasi** [comment]
I tried 2.82 and it seems to work fine now. Sorry and thanks.
