### ISSUE TITLE
Object instancer in subprogram

### ISSUE THREAD

**Issue by Bunpasi** [JacquesLucke/animation_nodes#1436]
Is there a reason that you can not use an object instancer in a subprogram? This would be very convenient when you have many trees or recursion. I tried commenting out
`options = {"NOT_IN_SUBPROGRAM"}` in `object_instancer.py`
and that worked fine.

**Comment by kdsin23** [comment]
> Is there a reason that you can not use an object instancer in a subprogram? This would be very convenient when you have many trees or recursion. I tried commenting out
> `options = {"NOT_IN_SUBPROGRAM"}` in `object_instancer.py`
> and that worked fine.

but the performance is not better, i think it will be very slow.

**Comment by OmarEmaraDev** [comment]
It probably didn't work fine. Try using it in a loop or in a group that is invoked many times.
We tried allowing that before but no implementation with a reasonable running time was found. So we probably won't consider that in the future.

**Comment by Bunpasi** [comment]
Thank you for your quick response.

Isn't it possible to just show a warning instead of disallowing it completely? As I was looking for why other people were asking the same question, I realized that this is a powerful feature.

**Comment by OmarEmaraDev** [comment]
The performance penalty will be for the base case, so making the node slow for pretty much all cases except for a few cases is not a good idea. So I don't think this is something we will consider for now.

**Comment by Bunpasi** [comment]
Oh. I get it.
