### ISSUE TITLE
Looping through objects indices while performing an operation / calculation on them

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1437]
I'm having trouble looping through an objects (**the cylinder**) indices while performing
an operation / calculation on them.

I created an animation in Octave and the calculations match up with the calculations in Animation Nodes.  I'm just having problems looping over the indices to produce the same animation.  See attached animated Octave gif of how it should look.  I've also included the blend file and an image of the node

**Please note: I know it looks like a simple rotation but it isn't, it's visualizing / showing different quaternion calculations.**

![video](https://user-images.githubusercontent.com/28985314/82979693-b43cc580-9fb5-11ea-9392-f47a0f384f77.gif)

**The entire node:**
![screenshot-May-27-2020-01:53:25](https://user-images.githubusercontent.com/28985314/82982829-01706580-9fbd-11ea-8043-4b3c4ac9e166.png)

**The section that does the calculations:**
![screenshot-May-27-2020-01:53:08](https://user-images.githubusercontent.com/28985314/82982833-03d2bf80-9fbd-11ea-9d12-0afc8b47ef88.png)

**The section with the vertices I'm trying to loop over:**
![screenshot-May-27-2020-01:52:38](https://user-images.githubusercontent.com/28985314/82982836-0503ec80-9fbd-11ea-9913-2da23cfe729c.png)

[quat_AN_eq01_loop_question.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4686537/quat_AN_eq01_loop_question.blend.zip)

**Comment by OmarEmaraDev** [comment]
Are we talking about polygon indices? What is the difficulty exactly?

**Comment by stillpointx** [comment]
Yes polygon indices. I tried using the Object transforms output node but that does simple rotations I'm trying to get finer control and the indices seems the way to go.  **I'm just having trouble combining the calculations and the looping of all the indices together.**   I'm trying to get the "mathematical morphing" seen in the animation above.
