### ISSUE TITLE
Frequen error with Animation Nodes - Red border

### ISSUE THREAD

**Issue by mioii** [JacquesLucke/animation_nodes#1438]
During the work it happens that i can't do anymore also the simplest action.
For example to manage a cube rotation directly from the transformation output node. Why?

Traceback (most recent call last):
  File "/Users/marco/Library/Application Support/Blender/2.82/scripts/addons/animation_nodes/operators/output_execution_code.py", line 14, in execute
    code = getCurrentExecutionCode(lineNumbers = True)
  File "/Users/marco/Library/Application Support/Blender/2.82/scripts/addons/animation_nodes/operators/output_execution_code.py", line 46, in getCurrentExecutionCode
    codes = unit.getCodes()
AttributeError: 'NoneType' object has no attribute 'getCodes'

location: <unknown location>:-1

**Comment by OmarEmaraDev** [comment]
Are you using the latest build from https://animation-nodes.com/?

**Comment by mioii** [comment]
Is the version 2.1.7

![Schermata 2020-05-27 alle 14 03 26 (2)](https://user-images.githubusercontent.com/66013465/83020594-fa7f3c80-a028-11ea-8fda-19913ce49e5f.png)

**Comment by mioii** [comment]
yesterday evening the same, nothing to do to solve till a pc restart...

**Comment by OmarEmaraDev** [comment]
I can't replicate this in Blender 2.90. Can you open Blender from the terminal and dump the whole terminal output here?

**Comment by mioii** [comment]
I solved the error messages deleting from the library and re-installing the add-on, look like during a re-install was created a duplicate. 

But i still have issues when i do few "undo" commands, after 5/10 input the red border appear.
