### ISSUE TITLE
Error after few "cmd + Z"

### ISSUE THREAD

**Issue by mioii** [JacquesLucke/animation_nodes#1439]
Can't do a "monitor print", don't know why.

Can anyone help please?

![Schermata 2020-05-28 alle 14 37 45 (2)](https://user-images.githubusercontent.com/66013465/83142556-f159a280-a0f0-11ea-9325-d15e5f2028a5.png)

**Comment by OmarEmaraDev** [comment]
Can you attach the terminal output here?
