### ISSUE TITLE
Suggestion: ReadingText from Object

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#144]
Reading text from existing text object(s) is sometimes needed. I wonder if it could worth implementing.

**Comment by kopias** [comment]
something like this?
http://www.pasteall.org/blend/36211

**Comment by LeonCheung** [comment]
LOL, OK, you win.

**Comment by kopias** [comment]
Now make me some nice example :)​

**Comment by LeonCheung** [comment]
Ya, there should be many.  tbc  :)

**Comment by LeonCheung** [comment]
Vote to close this issue. :) Thanks again.
