### ISSUE TITLE
Totally different results for rendering. 

### ISSUE THREAD

**Issue by ranqiz** [JacquesLucke/animation_nodes#1440]
Hi, 

As in topic, I got totally different, buggy results of animation nodes graph when do regular Cycles GPU rendering. Viewport animation aka Playblast shows great result, and then changing NOTHING, not a bit, final render shows something else. Not different, but just corrupted. 

Here's the Playblast version of grass animation:
https://drive.google.com/open?id=1_OAk3UiIKsXjPYvWNiGAzPFODBbAt_uq

As You can see the grass look GREAT! As I wanted. 

But after rendering, I got this...
https://drive.google.com/open?id=16OE5WxeeN-k9j1Udf36cydTSIdm-BYGh

Totally corrupted, not even close to the playblast. Particle hair cache is good. 

What's wrong? I need to re-render this, but need the result from Playblast. 
Anynoe can help here? I'm thinking of exporting ABC sequence, but this is an extra step, and I like to change the grass type, so I need it to be as is on AN Nodes setup. 

Cheers!

**Comment by Gerstmann-Bradley** [comment]
Without the node tree/explanation, it's not possible to know what you have done wrong.
I suppose you disabled something in the render but not in the viewport of your file, but it's just an hypothesis.
However, in the worst case, it's still possible for you to "render viewport animation"; I suppose it will solve your problem.
![thought](https://user-images.githubusercontent.com/55994236/83166785-67eca500-a0dd-11ea-8f04-84b746679d33.png)

**Comment by ranqiz** [comment]
Hi, 

How it will solve the problem? It work's when render via "Viewport Render Animation" option from view menu. Also everything is checked in the AN panel. I need it working for Cycles Render. Also if something will be wrong, it should not work at all, but the grass moves. 
Attaching nodes:
![Tree](https://user-images.githubusercontent.com/36239294/83170219-7e622300-a114-11ea-84b1-12599d15ea1b.jpg)

**Comment by OmarEmaraDev** [comment]
Might be related to #1294. Make sure you have the latest version, if yes, then I will have to investigate in more details later.

**Comment by ranqiz** [comment]
> Might be related to #1294. Make sure you have the latest version, if yes, then I will have to investigate in more details later.

I got the 2.1.7 AN, so the newest. But I have checked:
![image](https://user-images.githubusercontent.com/36239294/83191330-20453800-a134-11ea-9546-79bfcdd017d5.png)

May that be the cause?

**Comment by OmarEmaraDev** [comment]
Shouldn't make any difference.

**Comment by ranqiz** [comment]
Hi, 

And how? Is this a bug? Or is there a workaround? Really need it to the actual project.

**Comment by OmarEmaraDev** [comment]
@ranqiz Can you create a minimal setup that replicates the issue you are talking about? What exactly is the expected output and what is the actual output? What is the purpose of the node tree?

**Comment by ranqiz** [comment]
Pfff sadly on a test file it works just fine... The mesh on which is the particles system, which is the root of animation, is from Megascans. I try to make a plane, with shrinkwrap, just to avoid using Megascans mesh, as base for the particles. This is the only thing which may be the problem.

**Comment by ranqiz** [comment]
Hi, 

Can this topic be re-open, because the problem occurs when there are more objects, and doesn't work at all on rendering. Viewport look good, also I'm not populating particle system on heavy geo, just on plane with shrinkwrap. On simple, light scenarios it's good, but on the heavy ones it's a disaster.

**Comment by OmarEmaraDev** [comment]
Ok. Can you create a minimal setup that replicates the issue you are talking about? What exactly is the expected output and what is the actual output? What is the purpose of the node tree?

**Comment by ranqiz** [comment]
Hi Omar, 

The purpose is to get animated grass. Basically, because I made out of 2-3 tutorials by myself, but mostly from one. Curves are placed and are copying the movement of the particle hair system, which mimics grass behaviour. Then also a collection of grass as geometry is instanced. Both by instancer node. And in the viewport the behavior, apart from overall performance is as in particle system. But after rendering, it's totally diffrent. BUT only on heavier scene. 
Below link to the same scene in 2 variants, the lighter one just works fine, and after exporting to ALEMBIC, also. The heavier not at all. I wasn't testing the heavier one in rendering, but the smaller is working just fine. Also On the heavier file, AN Nodes turn red in some time. So the problem is in the number of objects. Sadly this is very important thing for Me now, I really need to have animated grass. Hope You can help. 

https://drive.google.com/file/d/1khsG_YN2yw1fAzzQB3RwQaBoGWdB75fY/view?usp=sharing

**Comment by ranqiz** [comment]
Yeah this is the cause, I mean, maybe not the number of objects, but a too long time of computing the nodes, but I can confirm after some further testing, that this is the cause. Now is the question, if this is fixable.

**Comment by OmarEmaraDev** [comment]
I can't replicate the issue and your file is too heavy to debug. Can't you simplify it more? Are you aware the minimum time difference is set to 5 seconds?

**Comment by ranqiz** [comment]
Minimal time difference? No, I wasn't aware, is there a possibility to change that time? What it means exactly. Sadly I can't make easier file, because for that what I need the particle count is about for now 5600, but should be 12000. So I can't simplify, because on simpler, and lighter setups it is working fine.

**Comment by OmarEmaraDev** [comment]
In the Auto Execution panel, there will be a value called Minimum Time Difference, set it to zero. I am not sure how you managed to make things work with it set to 5, but try a value of zero and report back. See:
https://docs.animation-nodes.com/documentation/introduction/execution/#minimum-time-difference

**Comment by ranqiz** [comment]
Managing it is a pain, but I really was in need of good grass behaviour, with particles We can't do that, because of spinning problem, when the strand is bending in the other direction too far. But form that what I see, I will be forced to use particle system, and just make it move only slightly, not to exceed the range. Apart from that, I think AN Nodes solution is much, much, much more memory consuming. Yet possible, need to take a look at render time difference between. Thank You for Your answers, it helps Me alot :)
