### ISSUE TITLE
Animation nodes doesn't work in headless mode

### ISSUE THREAD

**Issue by jasowill536** [JacquesLucke/animation_nodes#1441]
Love Animation Nodes!  Looking forward to everything nodes in a future release of Blender.

It appears that Animation Nodes will not work in headless mode.  Example: blender -b -P test_animation_nodes.py with the following sample code, will fail when attempting to update a "Separate Text Objects" node.

`animNodes = bpy.data.node_groups['NodeTree'].nodes
animNodes["MainTextInput"].inputs[0].value = "some text"
animNodes["GlyphBuilder"].updateSeparation()
`
This fails with:
...\animation_nodes\utils\blender_ui.py", line 90, in wrapper
    return output
UnboundLocalError: local variable 'output' referenced before assignment

Just looking at the name "blender_ui.py" seems to indicate that animation nodes was not intended to run in headless mode.  

It would be wonderful if running animation nodes was possible in headless mode.

**Comment by arest** [comment]
I'm facing a similar problem. Headless mode. Trying to update the text value on the fly.
    bpy.data.objects['Text'].data.body="Test 123"
    bpy.data.node_groups['NodeTree'].nodes['Separate Text Object'].updateSeparation()
```
ERR:   File "execution: 'NodeTree'", line 87, in <module>
AttributeError: type object 'object' has no attribute 'location'
Traceback (most recent call last):
  File "/bin/2.82/scripts/addons/animation_nodes/execution/main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 87, in <module>
AttributeError: type object 'object' has no attribute 'location'
```
It works when using the GUI.

**Comment by OmarEmaraDev** [comment]
Animation Nodes does work in headless mode, however, the Separate Text operator is a special case, as it requires manual intervention from the user.

We recently introduced a new workflow to work with texts in #1325 using the Decompose Text node. This workflow should be used if you need things to be dynamic and require no manual intervention.

**Comment by jasowill536** [comment]
Wonderful!  Thanks for taking the time to respond to this.  I will close this.
