### ISSUE TITLE
Mesh Object Output does not show wires, unless Type is BMesh

### ISSUE THREAD

**Issue by wesvdes** [JacquesLucke/animation_nodes#1445]
When you enter edit mode you'll see the wires are still there, they are just not drawn in the viewport.

![Invisible wires](https://user-images.githubusercontent.com/3173161/83942444-abd55d80-a7f3-11ea-9488-628514f74c79.jpg)
[Invisible wires.zip](https://github.com/JacquesLucke/animation_nodes/files/4739841/Invisible.wires.zip)

**Comment by OmarEmaraDev** [comment]
They are actually not visible in any of versions for me. So this is probably a Blender thing. Maybe it should be reported to the Blender developers instead.

![20200606-142016](https://user-images.githubusercontent.com/25300994/83944015-c8c45d80-a800-11ea-9b6e-73559c519c2f.png)

**Comment by wesvdes** [comment]
That's interesting. It could very well be a Blender issue, or perhaps graphics driver related.
May I ask which graphics card and driver version you're using?

For reference, I got my results using the following:
GeForce GTX 770
Driver version 442.19

Tested with:
Blender 2.82.7
Blender 2.83.0
Animation Nodes 2.1.7

**Comment by OmarEmaraDev** [comment]
Mine is probably a driver issue because I am using an unsupported GPU (AMD HD5450). However, your issue might have something to do with drawing cache or something like that, so probably a Blender issue, not a GPU issue. I remember there were similar reports about this issue, but I can't find them right now.

**Comment by wesvdes** [comment]
I found it! Edges have an is_loose property. If it is set to True, the edge will always be drawn, even when not in wireframe view. But this property can't yet be carried over between AN nodes, just like seams, sharp edges, bevel weights, etc.

BMesh.to_mesh() recalculates loose edges automatically. But when building a Mesh manually you can use [Mesh.update(calc_edges_loose=True)](https://docs.blender.org/api/current/bpy.types.Mesh.html?highlight=mesh#bpy.types.Mesh.update) to do this. When doing so, you should call it after the mesh's edges, polygons and loops have been assigned.

![Invisible edges solved](https://user-images.githubusercontent.com/3173161/83950161-cf66cb00-a828-11ea-882b-7da714478444.jpg)

**Comment by OmarEmaraDev** [comment]
Thanks for investigating @wesvdes! I added an optional Advanced Node Setting to the node to calculate loose edges in 6aa7ec4.
