### ISSUE TITLE
Switching Objet Mode in AN

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#1446]
I have a situation where I need to switch between Object and Edit mode for an Armature in a script node, given I should not use ```bpy.ops``` calls, how do I do this please? I have not tried this yet, but remember you saying not to do this...

**Comment by OmarEmaraDev** [comment]
You can't do that as far as I know. You have to use the operators. What are you trying to do?

**Comment by Clockmender** [comment]
Duplicate a bone so there are so many instances of it. so the code goes something like this:

```python
if Armature is not None and process:
    if Armature.type == "ARMATURE" and bone in Armature.pose.bones:
        bone_orig = Armature.pose.bones[bone]

        if bone_orig is not None:
            head = bone_orig.head.copy()
            tail = bone_orig.tail.copy()
            bpy.ops.object.mode_set(mode='EDIT')
            
            for i in range(copies):
                # These next two lines will offset the duplicate bones
                head = head + offset
                tail = tail + offset
                bone_d = Armature.data.edit_bones.new(bone_orig.name+"_"+str(i))
                bone_d.head = head
                bone_d.tail = tail
        
        bpy.ops.object.mode_set(mode='OBJECT')
```

Variables are as defined in the script node...

**Comment by OmarEmaraDev** [comment]
In this case I think your approach is the only feasible one. Just be wary of contexts and out of context references.

**Comment by Clockmender** [comment]
Thank you, I'll close this now.
