### ISSUE TITLE
Is it possible to add a texture image to a "target" Mesh Object Output node in AN?

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1450]
I'm trying to add a texture image to a "target" Mesh Object Output node and have the texture follow and warp with it when I change the compose matrix.  Is this possible?

I'm using Blender 2.83 and AN 2.1.7

Node setup:
![screenshot-June-13-2020-16:29:38](https://user-images.githubusercontent.com/28985314/84578428-26255500-ad93-11ea-910e-2b4d3f1b3ed9.png)

Image texture I'm trying to apply to the cylinder. 
![untexture](https://user-images.githubusercontent.com/28985314/84578352-5f10fa00-ad92-11ea-9fd2-cc66b444f70a.png)

**Comment by OmarEmaraDev** [comment]
I apologies for the delay @stillpointx. Haven't seen this issue till now.
Are you looking to create a UV map for the Cylinder?

**Comment by stillpointx** [comment]
No worries, we live in very interesting times.  

I can apply a image texture to an object (a cylinder)

![screenshot-June-20-2020-17:41:40](https://user-images.githubusercontent.com/28985314/85212146-c2b09f80-b31d-11ea-96e3-0c7fc872eb57.png)

 But the image texture doesn't seem to be connected to the object if I change anything in animation nodes.  

![screenshot-June-20-2020-17:42:13](https://user-images.githubusercontent.com/28985314/85212207-7e71cf00-b31e-11ea-94cc-d4ca6c9196a6.png)

Is there an image texture node in animation nodes that I need to use so when I change something in animation nodes the texture will also follow the geometry?

Thanks

**Comment by OmarEmaraDev** [comment]
In the Mesh Object Input node, there is a hidden input called Load UVs, enabling it should transfer the UV map and the texture should appear as you might expect.

**Comment by stillpointx** [comment]
Thanks that did it...:-D
 For the next person here's what it looks like
![screenshot-June-21-2020-08:11:17](https://user-images.githubusercontent.com/28985314/85224286-23c88980-b397-11ea-87e8-35fea0bb7a5f.png)


![screenshot-June-21-2020-08:12:05](https://user-images.githubusercontent.com/28985314/85224287-26c37a00-b397-11ea-854a-08be3d38a06e.png)
