### ISSUE TITLE
Animation Nodes won't enable in Blender 2.83 Linux Ubuntu 20.04

### ISSUE THREAD

**Issue by rorocabrera** [JacquesLucke/animation_nodes#1452]
Hi, when trying to enable AN I get this:

<a href="https://ibb.co/Pmtw9q9"><img src="https://i.ibb.co/Pmtw9q9/Screenshot-from-2020-06-21-13-48-42.png" alt="Screenshot-from-2020-06-21-13-48-42" border="0"></a>

I have used official https://animation-nodes.com/#download build for linux

and the latest https://blender.community/c/graphicall/tdbbbc/ build with same result

I installed libpython3-dev and restarted

phtyon3 --version command, returns Python 3.8.2

I have deleted /home/.config/blender/2-83/scripts/addons/animation_nodes manually

I Have done a search throughout the system for any other animation_nodes folder but found nothing

A clue to what might be happening is that the first attempt to install it was done with the master zip file https://github.com/JacquesLucke/animation_nodes.git that i downloaded thinking was the correct build. It proceed with the installation in blender but no add-on showed on the list.

Thank you very much

**Comment by OmarEmaraDev** [comment]
The official builds are built for Python 3.7, not 3.8, because 3.7 is the default Python version in Blender. Ubuntu's Blender probably uses the system python, so that's why this isn't working. I am still not sure how to deal with all of those different versions. But for now, either use a portable Blender build from their website, or compile Animation Nodes yourself.

**Comment by rorocabrera** [comment]
Thanks very much, will try any of those.

**Comment by scoot** [comment]
installing python3.7 and libpython3.7 should work.  I just had the same problem and that fixed it for me.

**Comment by kdsin23** [comment]
i was the same issue, i downloaded the AN file from the blender.today is not working on ubuntu16.04, but i compiled myself can work correctly.

**Comment by disarticulate** [comment]
@kdsin23 How did you compile it? I can't see any details about that.

**Comment by Choons** [comment]
If you install Blender through the Ubuntu distro you get a version compiled to work with python 3.8.2. Then if you build Animation Nodes from source in Ubuntu 20.04 & install python3-numpy, you will get version compatible Animation Nodes that works. The Ubuntu build is currently for Blender 2.82 so a bit behind official releases but I'm good with tat to have a Blender working with my system python 3.8 and Animation Nodes as well.

**Comment by scoot** [comment]
@kdsin23 try:

`sudo apt install python3.7 libpython3.7`

**Comment by OmarEmaraDev** [comment]
We now provide official builds for Python 3.8 on Linux. https://animation-nodes.com/#download
