### ISSUE TITLE
Rotation Glitch problem

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1453]
Rotation glitches when using `Evaluate range` and `Mix Euler List` node.

![rotateAlongSpline](https://user-images.githubusercontent.com/46858047/85380959-22e05500-b55b-11ea-916f-ca551df1fe65.gif)

**Comment by OmarEmaraDev** [comment]
Can you share a minimal blend file to reproduce the issue?

**Comment by kdsin23** [comment]
i guess the problem is due to the first point and the last point is not connect when using the "Mix euler list" node, i think you can append the first point to the location list, so the first and the last point to overlap. this way maybe fix the problem.

**Comment by harisreedhar** [comment]
> Can you share a minimal blend file to reproduce the issue?

Here is the project file. please check frame at 73 to 76
[rotationGlitch1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4819645/rotationGlitch1.blend.zip)

**Comment by harisreedhar** [comment]
> i guess the problem is due to the first point and the last point is not connect when using the "Mix euler list" node, i think you can append the first point to the location list, so the first and the last point to overlap. this way maybe fix the problem.

Did you mean to make connected spline?

**Comment by harisreedhar** [comment]
> i guess the problem is due to the first point and the last point is not connect when using the "Mix euler list" node, i think you can append the first point to the location list, so the first and the last point to overlap. this way maybe fix the problem.

Not working :( i think it's some issue with mixeuler or evaluate range.

**Comment by OmarEmaraDev** [comment]
@harisreedhar This is one of the cases where using Eulers is a bad idea. Generally, interpolating euler angles don't work well in practice. Luckily, that's why we have quaternions. So convert your angles to quaternions, mix them, then convert them back to Eulers.

**Comment by harisreedhar** [comment]
> @harisreedhar This is one of the cases where using Eulers is a bad idea. Generally, interpolating euler angles don't work well in practice. Luckily, that's why we have quaternions. So convert your angles to quaternions, mix them, then convert them back to Eulers.

Perfect. Now It works fine thank you.
