### ISSUE TITLE
Is it a boolean bug?

### ISSUE THREAD

**Issue by cxdcxdcxd198** [JacquesLucke/animation_nodes#1454]
Is it a boolean bug?
![bug](https://user-images.githubusercontent.com/51414955/85394660-74033f80-b581-11ea-8434-d08f3446092f.JPG)

**Comment by OmarEmaraDev** [comment]
Not really. Animation Nodes will return false if it can't compare the inputs. In this case, it can't, because falloffs are not comparable.
