### ISSUE TITLE
How "Transform Vector" Node works?

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1455]
![transform vector bug](https://user-images.githubusercontent.com/64368228/85401743-18d74a00-b58d-11ea-9790-47281ad4e25a.png)

i used Transform vector node in a loop, i found a interesting thing: the distance between two lines is not equal, i dont know why,so i tried to used the "fill list" node instead of "float range" node,as a result, they are the same distance betwen two lines, i was very confused about this, i feel this is a bug for this node?

![transform vector bug3](https://user-images.githubusercontent.com/64368228/85402160-c64a5d80-b58d-11ea-81e0-67a0dcfef35b.png)

**Comment by OmarEmaraDev** [comment]
By default, Animation Nodes doesn't copy lists in loops. So each iteration transforms the list that was already transformed in the previous iteration. To fix this, you can force Animation Nodes to copy the list every time from the advanced node settings. Se the documentation:
https://docs.animation-nodes.com/documentation/subprograms/loop/#parameter-sockets

**Comment by kdsin23** [comment]
> By default, Animation Nodes doesn't copy lists in loops. So each iteration transforms the list that was already transformed in the previous iteration. To fix this, you can force Animation Nodes to copy the list every time from the advanced node settings. Se the documentation:
> https://docs.animation-nodes.com/documentation/subprograms/loop/#parameter-sockets

Thank you for your reply!  you makes me learn something new about a loop one more time.
