### ISSUE TITLE
is ObjectInstancerNode  imported to other file?

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1456]
i wanted to use the `getInstances_WithSource()`function,so i imported the module like this:
`from .. object.object_instancer import ObjectInstancerNode`, then i used the function like this: `ObjectInstancerNode.getInstances_WithSource(count, source, scenes)`

but the consoul gave me an error:

![import er](https://user-images.githubusercontent.com/64368228/85593315-82348700-b679-11ea-9fde-a956049a8796.png)

i don't know why, or there are some other reasons, the full python code is here:
[spere_light.py.zip](https://github.com/JacquesLucke/animation_nodes/files/4826649/spere_light.py.zip)

thank you for any help!

**Comment by OmarEmaraDev** [comment]
The `getInstances_WithSource` method is an instance method, not a class method. So there needs to be instance of the `ObjectInstancerNode` class, then you would be able to call that method.

**Comment by kdsin23** [comment]
> The `getInstances_WithSource` method is an instance method, not a class method. So there needs to be instance of the `ObjectInstancerNode` class, then you would be able to call that method.

Thank you for your reply! it can work now
