### ISSUE TITLE
use consistent  node names vs menu names vs category 

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#146]
As per forum by Leon
1. I completely agree that name should be same 
2. Also node name should contain category name
Example
I looked up list. not all nodes there. sum elements by first

**Comment by LeonCheung** [comment]
My two cents: https://docs.google.com/spreadsheets/d/1gjZbjXFlb6Z8mAWpUMFUNCEpDtoOc_iTMAVRtZKrtH4/edit?usp=sharing You can edit or comment there if you like.

**Comment by LeonCheung** [comment]
For most of them, it applies "category_name" + "Item_name" as the full node names. e.g. adding node by selecting "Object" > "Input", the node name will be displayed like Object Input, not strictly, but a recommended rule.

**Comment by JacquesLucke** [comment]
thanks. I will through that list tomorrow :)

**Comment by JacquesLucke** [comment]
do you think I should remove the debug category and put the debug node into the system category?

**Comment by LeonCheung** [comment]
I think so, since it only got two items and takes the menu list space (I really think we could quickly add it by some shortcut, like the Ctrl Shift LMB in Compositor). And I suggest to call System a more generic name, maybe something like "Misc", in order to put in any possible nodes that are relatively hard to classify singly.

**Comment by JacquesLucke** [comment]
I experimented a bit with pie menus. If you have a late version of the curve sockets branch you should be able to hit the 'w' key to open a menu while you have an active node

hmm not sure if 'Misc' is a great name..

**Comment by LeonCheung** [comment]
I see. Sure then. But I dare to say that sooner or later we'll need a Misc category.  lol

**Comment by JacquesLucke** [comment]
haha. Maybe we should leave the loop and group stuff in a 'system' category and put the rest into misc

**Comment by LeonCheung** [comment]
Could be an option.  :)

**Comment by LeonCheung** [comment]
Just noticed the W pie menu, that's more brilliant!

**Comment by og76** [comment]
I think this is going in the right direction 

according to the above, just made some further changes to insert_nodes_menu.py as it is now in the socket branch, 

see it here (replace your insert_nodes_menu.py with this)
https://drive.google.com/file/d/0BzzAoBwXO8dsNk9rTmtBZUVSLVE/view?usp=sharing
or in git 
(kinda confusing me with all those forks and stuff, forks and knifes are for civilized people)

as for the sheet b notes:
-if u make one integer/float, add a check for integer not dropdown. But I'm not so sure about this merge.
+1 to NOT using second submenus, tough I know more is to come to mesh like voronoi functions etc

**Comment by JacquesLucke** [comment]
thanks for the comments in the file. looks quite helpful. 
I will go through that in more detail later (yes, I know I'm saying this relatively often currently... but there is so much stuff)

On thing about the order in the Matrix Menu:
I prefer to have 'Translation', 'Rotation' at the top instead of decompose and compose because this are much more usual nodes. At least in my workflow

**Comment by og76** [comment]
true about matrix usage, but I'm trying to have kinda same arrangement for categories
for vector there is compose/decompose into float, matrix would follow compose decompose into vectors

matrix combine is way more useful, but in this logic it's a more complex operation ... 

ps. it's ok, when you say later is very soon anyway.

**Comment by og76** [comment]
+1 for the w menu!
(now I have to find a way to get my mini debug into it...)

**Comment by og76** [comment]
I played with the pie menu code a bit (see #145 ) and have a question:
**Should the pie menu refer to (a structure of) other "menu files"** for each particular case, like MyNode_menu.py? Ok maybe not the debug, but for loops etc ... or custom nodes.

**Or maybe a way to append** / insert my menu into the main pie

when I started adding stuff to the pie code *I thought it should be in a separate file near my nodes.* In this way I could add my Node Menu stuff like I add today a link in the shift A menu. And when I change my menu I don't have to change the main pie.


In time there will be more to add to the pie menu than debug , math and transforms. And people may just wanna have special menus for their special node (like me :stuck_out_tongue_winking_eye:  )

**Comment by JacquesLucke** [comment]
Well the code structure for pie menus are far from finish, this debug operator was more like a small test.
My main goal was to have some static operators in the pie menu and some that change depending on the selected node. The problem is that I don't know yet how to specify the position of an operator in the menu to make sure that the same operators are always at the same place. 

Yes, having some pie menu code near the node they belong to would be cool and easier.

**Comment by LeonCheung** [comment]
According to what Sabasitan discussed [here](https://vimeo.com/103321600) (around 6:00), pie menu seems quite dynamic. fyi

**Comment by og76** [comment]
**Formatting the pie** (so far)
It always works in the **specific order of the buttons vs specific order of the script** . 
My workaround for **fixed positions** was to put **dummy row or column** to keep the places occupied. 

**The order goes like this:**
![pie_order](https://cloud.githubusercontent.com/assets/11709974/8041872/13aa200e-0e24-11e5-95c1-fd8a81e25400.PNG)
With a code like this ( labels need row or col to get this position, see notes below)
```python
            pie = self.layout.menu_pie()
            
            row=pie.row()
            row.label("POSITION 01")
            row=pie.row()
            row.label("POSITION 02")
            row=pie.row()
            row.label("POSITION 03")
            row=pie.row()
            row.label("POSITION 04")
            
            col=pie.column()
            col.label("position 05")
            col=pie.column()
            col.label("position 06")
            col=pie.column()
            col.label("position 07")
            col=pie.column()
            col.label("position 08")
            
            row=pie.row()
            row.label("pos 09")
            row=pie.row()
            row.label("pos 10")
```
If you have **just row or col**  you **get the empty space**.
![pie_order1](https://cloud.githubusercontent.com/assets/11709974/8042100/81297b92-0e25-11e5-8712-ecd62f157a5e.PNG)
idem the above, but commented out 2
```python
           ...
            row.label("POSITION 01")
            row=pie.row()
            #row.label("POSITION 02")
            row=pie.row()
            row.label("POSITION 03")
            ...
```

*Same goes if you put more than one operator in a position. You will get a menu (like any other ) with row and col that is centered on the position vertically or horizontally (col or row). So if you again wanna keep the fixed position, may wanna use empty row or col. (see bottom pic)*


**Notes:**
- simple pie.label goes positioned near center on top of each other, so you have to use row, col or so
- above 10 it will show these labels on top of others (pos 11 would be like pos 01) but in a very chaotic order (pos 12 is over 10 and 13 over 6 or so ..)
- For these buttons of mine I use only first 4 positions, the rest is the usual row/col formatting
inwitch case the buttons are not big and black, but like any menu:
- labels go on transparent back, buttons Embossed=False have black text on the transparent back etc, \you get the nice big black button only for single pie.operator

**Example with more operators:**
Top is just a row label
Bottom is single operator
LR are menus with more than one row/col ...
if I hide some operators, but wanna keep  the Left/right in the same pos (vertically) I have to replace those lines with empty row/col
![remote pie2](https://cloud.githubusercontent.com/assets/11709974/8042292/f3825f1e-0e26-11e5-8bfa-20778801611c.PNG)

**Comment by og76** [comment]
fwiw, I just realized, from some forum threads, that you can have nested pies. (just to note here ...)

**Comment by JacquesLucke** [comment]
Yeah, I know that you can have nested pies ;)

Thanks for showing me how to create 'empty pie menu directions'. That was helpful.
Maybe you want to create a new github Issue for Pie Menus (Yeahh one more :D) because it has nothing to do with the initial intend for this issue

**Comment by og76** [comment]
moved there the pie discussion. 
Do we still need this one? 
Are we gonna rename some actual nodes according to menu naming rules above?

**Comment by JacquesLucke** [comment]
Not sure, but I think we can leave this one open for now
