### ISSUE TITLE
Clean build for python 3.8.2. Now what?

### ISSUE THREAD

**Issue by Choons** [JacquesLucke/animation_nodes#1461]
I'm a Blender 2.8 noob working in a AMD64 Ubuntu 20.04 environment. I tried the pre-builds from Graficall but they wouldn't work, so I decided to build Animation Nodes myself from the master branch. I had no idea Blender isn't using my system python3 version of 3.8.2, so I set up Cython, python3-dev, gcc/g++, etc. for that version. 

Now I have a beautiful clean build of Animation Nodes for AMD64 + Ubuntu 20.04 + python 3.8.2 that I obviously found out doesn't work in Blender as of now. SO anything I can do about it? More of a Blender question but can I patch it to get current with python3 versions being used in Ubuntu now.. OR... what? (kudos by the way for putting out code that actually WILL build clean on python 3.8.2!) Looking forward to using this great add-on

To be a little more clear-- using Blender 2.83 and my built version of Animation Nodes failed to install into Blender with the alert that there is python version mismatch with Blender 2.83 running on python 3.7.4 I believe is the version while my build is for python 3.8.2 as I said above. I built with the --noversioncheck flag but still not working. Looking at the Blender install, I see it installed its own local version of python 3.7.

**Comment by OmarEmaraDev** [comment]
There are two distinct cases here:
- You are using the Blender package from your Linux distribution, this package is probably using the system Python which is probably 3.8. In this case you can compile Animation Nodes using the system python and everything should work.
- You are using a portable Blender build that uses Python 3.7. In this case, you should download an appropriate build from https://animation-nodes.com/#download. However, Python 3.7 requires the existence of the dynamic libpython3.7.so. The trouble is that Ubuntu Focal removed Python 3.7, so you will probably have to use the deadsnakes PPA.

**Comment by Choons** [comment]
Yes! Perfect answer. I was indeed using a portable version instead of the Ubuntu distro version which is compiled for python 3.8. Reinstalled Blender and added python3-numpy and my Animation Nodes build works! now. Thanks so much, Omar.

**Comment by OmarEmaraDev** [comment]
We now provide official builds for Python 3.8 on Linux. https://animation-nodes.com/#download
