### ISSUE TITLE
how to solve this issue ..Need Help!!

### ISSUE THREAD

**Issue by kareem64** [JacquesLucke/animation_nodes#1463]
I Use Blender 2.9 alpha latest version  on Ubuntu 20.04
I can't Use Animation node
I try  use animation_nodes_v2_1_linux_py38  And animation_nodes_v2_1_linux_py37 

this  screenshot for issue
please help me

![Screenshot from 2020-07-02 09-57-56](https://user-images.githubusercontent.com/46063289/86335253-8d298180-bc4e-11ea-9d55-a9871996ed65.png)

**Comment by OmarEmaraDev** [comment]
You need to have libpython3.7 installed on your system.

**Comment by kareem64** [comment]
I installed libpython3.7 on my system but it notwork !!
![Screenshot from 2020-07-02 09-57-56](https://user-images.githubusercontent.com/46063289/86373384-a1d43c80-bc83-11ea-97e5-5fe95647d0bc.png)

**Comment by kareem64** [comment]
Thank You very much 
I download another version off animation node  and it work now 
Thanks Alot!!!
