### ISSUE TITLE
What determines the order of different viewport input nodes?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1464]
If I have multiple viewport input nodes, there will be different group of them in the N-panel. My question is whether there is a specific rule to arrange them, to make sure which one is on the top, the second and the third, etc.? I have tried naming, but it doesn't seem to work.
If there is no such a function, is that possible to add way to arrange them?
viewport input is very convenient, but if everything has to be in a single viewport input node, it will make node tree looks very horrible. If there are multiple viewport input group but I can't control their order, it also seems difficult to work with at some level.

**Comment by OmarEmaraDev** [comment]
The order is currently arbitrary, but we can introduce a weight to define their order.

**Comment by JacquesLucke** [comment]
I'm fine with a new system for Viewport Input (that maybe also allows inputs in other places?). The current system is a bit limiting indeed. I do do not have a design for this in mind currently. More specific proposals are welcome.

**Comment by Gerstmann-Bradley** [comment]
> I'm fine with a new system for Viewport Input (that maybe also allows inputs in other places?). The current system is a bit limiting indeed. I do do not have a design for this in mind currently. More specific proposals are welcome.

Not sure what specific you are looking for. If I understood your request correctly, I would say maybe "ordering different viewport input according to alphabetic order of their name". like 0 is always superior to 1, A is always superior to B...

**Comment by OmarEmaraDev** [comment]
Implemented in f7e312f. Thanks for the suggestion!

I will look into allowing more flexibility and drawing in other places, but lets track this outside of this issue.
