### ISSUE TITLE
AN .. Auto Execution Not Work

### ISSUE THREAD

**Issue by kareem64** [JacquesLucke/animation_nodes#1465]
I use ubuntu 20.04 and I installed AN v 2.1.3 
but auto execution not work I must click Execute Node Tree  to work .. please help me 
Thank You
This is screenshoot for the issue!
![Screenshot from 2020-07-03 12-14-35](https://user-images.githubusercontent.com/46063289/86461037-b10dc580-bd29-11ea-842a-42ffd0ba70f0.png)
![mypic](https://user-images.githubusercontent.com/46063289/86461361-2c6f7700-bd2a-11ea-9ced-5e08bfd113d5.png)

**Comment by OmarEmaraDev** [comment]
v2.1.3 is an old version of Animation Nodes. Please use the latest version and check if the issue still persists.

**Comment by kareem64** [comment]
I try v2.1.7 put it not installed  

screensoot:
![Screenshot from 2020-07-03 13-53-51](https://user-images.githubusercontent.com/46063289/86466875-bc1a2300-bd34-11ea-859c-ca8181cbf7b1.png)
![Screenshot from 2020-07-03 13-58-41](https://user-images.githubusercontent.com/46063289/86467263-61cd9200-bd35-11ea-9cb1-874213af18fa.png)

**Comment by OmarEmaraDev** [comment]
Well, it needs `libpython3.7`. So you need to install it. Ubuntu 20 doesn't have it, so you will have to get it from other sources like the deaksnakes PPA.

**Comment by kareem64** [comment]
Yes!! I did as you say !! it work now very well ..Thank you very much.
