### ISSUE TITLE
How to turn off "measure execution time" by default.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1466]
This may be a very weird question, but it drives me crazy now.
I once turned measure execution time on to check the performance delay. And then whether I am opening old file, or new file, it always pop up. Switching to default/measure execution will turn the time box off for the moment. But if I close the blender, and reopen blender, default always show this "measure execution time". Since I don't want to see it in a new file, I have to manually turn it off every time, which really drives me crazy now.
Is there any solution? I am totally confused about why the default becomes showing this measure execution time.

**Comment by Gerstmann-Bradley** [comment]
It seems I solved it. after turning "measure execution time" off, goes to "Edit" on the top -> "preference" -> "save preference"; Not sure how this works exactly but it works now.

**Comment by OmarEmaraDev** [comment]
Seems like the execution code option is an add-on preference as opposed to a standard property.
@JacquesLucke Why is this the case?

**Comment by JacquesLucke** [comment]
The reason was probably that this is a global setting and not per node tree. Not sure what you mean by "standard property".

**Comment by OmarEmaraDev** [comment]
Then should we draw those properties in the add-on preferences? We want to avoid what @Gerstmann-Bradley experienced.
