### ISSUE TITLE
How to sort lists in Animation Nodes?

### ISSUE THREAD

**Issue by dwizor** [JacquesLucke/animation_nodes#1470]
Hey, is there a way in animation nodes to sort lists based on e.g. position of vectors or by selection order ID?

I am missing this node in version with extra nodes:
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/list/sort_list.html

**Comment by OmarEmaraDev** [comment]
Key based sorting can be achieved using the indices output of the Sort Numbers node. For instance, to sort a group of vectors according to their x position, we do:

![20200710-164633](https://user-images.githubusercontent.com/25300994/87166941-8e9d1e80-c2cc-11ea-991b-2b2ec56d84f8.png)

**Comment by dwizor** [comment]
Oh that's nice! And what about for example sorting objects list by select order ID? ^^

**Comment by dwizor** [comment]
oh, it looks like adding a sort node after ID key works here too, thanks!

**Comment by OmarEmaraDev** [comment]
For ID Keys, you don't need a sort node. The indices are themselves the keys, so just get the objects at the elements:

![20200710-181101](https://user-images.githubusercontent.com/25300994/87174968-4552cc00-c2d8-11ea-81bc-b052b350f0d3.png)

**Comment by dwizor** [comment]
It's wierd, sometimes it work for me well but sometimes not. Take a look, i sorted object here by X Axis ID key, without sort node its incorrect and cylinder is in middle of list, but when i added sort node its work fine oO
![image](https://user-images.githubusercontent.com/68112419/87177960-c4e29a00-c2dc-11ea-9b8e-4f2370565b4a.png)

**Comment by OmarEmaraDev** [comment]
@dwizor I apologize, I mixed things up, it was the other way around. So yes, your should use the sort method.

**Comment by dwizor** [comment]
Ok, nice! Thanks for fast help :D
