### ISSUE TITLE
How to Calculate the thick of the mesh?

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1471]
is there any way to calculate the thick of the mesh by AN? for example ,the ears of the monkey,I wanted to move points on surface of the mesh along the normal direction, where the thick place moves more, and the thin place moves less, so that the surface points can be moved inside of the mesh.

![scatter](https://user-images.githubusercontent.com/64368228/87219694-0bdd9780-c390-11ea-82d4-849fab46aea9.png)

thank you for any help!

**Comment by OmarEmaraDev** [comment]
Not sure exactly how you want to define depth in this case. But here is an example where the depth is computed by casting a ray along the negative direction of the normals and computing the distance between the start and hit positions.

![20200711-113902](https://user-images.githubusercontent.com/25300994/87221251-d3779280-c36a-11ea-9984-1a90c93c7246.png)

**Comment by kdsin23** [comment]
> Not sure exactly how you want to define depth in this case. But here is an example where the depth is computed by casting a ray along the negative direction of the normals and computing the distance between the start and hit positions.
> 
> ![20200711-113902](https://user-images.githubusercontent.com/25300994/87221251-d3779280-c36a-11ea-9984-1a90c93c7246.png)

Thank your for your example. it is very useful to me, i have achieved my goal, scatter points in a volume of a mesh.
![scatter points](https://user-images.githubusercontent.com/64368228/87239765-73a1ea00-c445-11ea-94e5-6710bde9742c.png)

**Comment by OmarEmaraDev** [comment]
Very nice! I guess this is resolved then.
