### ISSUE TITLE
Closed Shapes option of the Mesh from Spline node crashed the Blender

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1472]
Hi...

Disabling the _Closed Shape_ option (while Cap Ends is enabled) of the _Mesh from Spline_ node crashes the Blender.
![Bug](https://user-images.githubusercontent.com/30294746/87223358-dfc71400-c399-11ea-91a7-bb3921cf9a69.png)

File: [Bug.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4906703/Bug.blend.zip)

**Comment by OmarEmaraDev** [comment]
Can replicate that.

**Comment by OmarEmaraDev** [comment]
Fixed in db6a0c0.
