### ISSUE TITLE
Text object not moving during Render Animation CTRL+F12

### ISSUE THREAD

**Issue by mbernbrich** [JacquesLucke/animation_nodes#1473]
I am using: 
   blender 2.83 
   AN 2.1.7

I have a text object that gets its text derived from the frame count, so during the animation it reads from '0' to '100'.
In addition, this text object moves in Y direction (from bottom to top like a fader on a mixer).
In preview all is working. 
When I press "Render Animation", the text gets updated with every frame change, but the object does not move anymore.
Changing the text AND moving it during animation is not working.
The small image illustrates what happens, when I renter single images (A) vs. an animation (B):
![AN_issue](https://user-images.githubusercontent.com/66380527/87251799-a90efd80-c46e-11ea-892f-81929057888f.png)

Great Addon! I just started to use it and it so cool !!

Thanks,
       Martin :-)

**Comment by Gerstmann-Bradley** [comment]
How did you drive the move of your text?
For curiosity I just did a test, and it works fine with me in both viewport and render. Likely you got mistake in your setup that make the text not moving.
In the worse case, I think you can "render viewport animation" instead.

**Comment by mbernbrich** [comment]
Thanks for the test file - this works indeed (I added a camera) and CTRL+F12 works fine - I see you used the AN for the movement as well (makes perfect sense).
In my case I used the blender key frames to animate the text object (file attached) which I felt was more appropriate to me. I hope that this is not a general constraint...
Here my file:
[UI_Fader_MB1-2-3_3d.zip](https://github.com/JacquesLucke/animation_nodes/files/4909005/UI_Fader_MB1-2-3_3d.zip)

**Comment by Gerstmann-Bradley** [comment]
> Thanks for the test file - this works indeed (I added a camera) and CTRL+F12 works fine - I see you used the AN for the movement as well (makes perfect sense).
> In my case I used the blender key frames to animate the text object (file attached) which I felt was more appropriate to me. I hope that this is not a general constraint...
> Here my file:
> [UI_Fader_MB1-2-3_3d.zip](https://github.com/JacquesLucke/animation_nodes/files/4909005/UI_Fader_MB1-2-3_3d.zip)

I see. Unfortunately I don't know the answer. But in the mean time you can "render viewport animation" instead, I have tested it and it works. hope the problem will be solve by @OmarEmaraDev

**Comment by OmarEmaraDev** [comment]
Seems more like a Blender bug than an Animation Nodes one. I will try to confirm and see what we can do then.

**Comment by mbernbrich** [comment]
Thank you for your note. As I am using the compositor, the viewport render ist half a workaround. But thank you for this hint - I never thought of using viewport rendering before.
Is there a blender forum you can recommend (to post my issue there)?

**Comment by OmarEmaraDev** [comment]
@mbernbrich I already reported it in [T78866](https://developer.blender.org/T78866). I recommend you just move the text using Animation Nodes as a workaround for now. See the following example:
https://docs.animation-nodes.com/documentation/nodes/animation/animate_vector/#examples-of-usage

**Comment by Gerstmann-Bradley** [comment]
> Thank you for your note. As I am using the compositor, the viewport render ist half a workaround. But thank you for this hint - I never thought of using viewport rendering before.
> Is there a blender forum you can recommend (to post my issue there)?

Another solution, which has been proven to work. You can keyframe an empty, and use empty's location to drive the text location. example provided. So that you can render it, and you can keyframe it.
[text test1.zip](https://github.com/JacquesLucke/animation_nodes/files/4909323/text.test1.zip)

**Comment by mbernbrich** [comment]
Alright, this works for me :-)
Thank you very much, indeed for the super quick response on a sunday!
