### ISSUE TITLE
Exporting node tree to python code doesn't work if the node tree has a sub-program node

### ISSUE THREAD

**Issue by MoamenAbdelsattar** [JacquesLucke/animation_nodes#1476]
In the developer's panel, there is a button which exports the node tree to a python code. If the node tree doesn't contain any (Invoke subprogram) nodes the resulted script works well. However, if the node tree has any invoke subprogram node, the resulted script doesn't work and gives an error like: "name '_subprogram_zxltfwbszv806qn' is not defined".
Is there a way to un-pack or un-group all subprograms before exporting to code?

**Comment by OmarEmaraDev** [comment]
To get the execution code of the subprogram, just select one of its nodes and press the button that exports the execution code. You will find a single routine, called `main`, this is the routine we call `_subprogram_zxltfwbszv806qn`.

**Comment by MoamenAbdelsattar** [comment]
Thanks for respond! I forgot to close this issue.
