### ISSUE TITLE
Converting array over to Vector List (X,Y,Z)

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1477]
### 1-The Issue:
I get an error in my loop / script saying **mathutils.Vector sequence 2 expected a number, found numpy.ndarray type.**

I know this is related to the Animation Nodes looking for a Vector List (X,Y,Z values) and I'm giving it an array of values.  How can I convert the array over to a Vector List so animation nodes can use it (if this is the correct way to do it)

### 2-What I'm doing:
I'm converting over a 3D parametric equation from Octave to Blender to animate it using Animation Nodes.

I can create / plot the parametric equation in Octave 

![](https://i.imgur.com/UxfoM7U.png)

Octave code:

    clc
    close all
    clear all
    
    u=linspace(0,4*pi,100);
    v=linspace(0,pi,100);
    [u,v]=meshgrid(u,v);
    x=u.*sin(u).*cos(v);
    y=u.*cos(u).*cos(v);
    z=-u.*sin(v) .-  sin(60/180 * pi)*(sqrt((x).^2 + (y).^2));
    figure(1)
    mesh(x,y,z);
    view([-57,32])
    h=gca; 
    get(h,'FontSize') 
    set(h,'FontSize',14)
    xlabel('X','fontSize',14);
    ylabel('Y','fontSize',14);
    zlabel('Z','fontsize',14);
    title('3D Parametric Equation Lily impeller','fontsize',14)
    fh = figure(1);
    set(fh, 'color', 'white'); 

Octave Image it creates:

![](https://i.stack.imgur.com/RS1ox.jpg)

### 3-What I have: (I've attached the Blend file
[fermat5_python_uv_an.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4941173/fermat5_python_uv_an.blend.zip)
)
But I'm having some issues converting / integrating that with Animation Nodes / Python. What I have so far is below.

Python Script in Animation Nodes Script Node
```
import math
import numpy as np

def surf(u, v):

    x1 = u*np.sin(u)*np.cos(v)
    y1 = u*np.cos(u)*np.cos(v)
    z1 = u*np.sin(v) - np.sin(60/180 *np.pi) *np.sqrt((x1**2 + (y1)**2))
    return x1, y1, z1

ux, vx = np.meshgrid(np.linspace(0, 4*np.pi, 100), np.linspace(0, np.pi, 100))

x1, y1, z1 = surf(ux,vx)

print("x1 size= ", (x1.size))
print("x1 shape= ", (x1.shape))
print("x1 dimension= ", (x1.ndim))
print("x1 dtype= ", (x1.dtype))

position1 = Vector((x1, y1, z1)) #issue is here animation nodes wants vector list.

```

![screenshot-July-18-2020-02:07:08](https://user-images.githubusercontent.com/28985314/87846154-aad82700-c89b-11ea-98e9-0c815968d77a.png)

![screenshot-July-18-2020-02:07:36](https://user-images.githubusercontent.com/28985314/87846159-b297cb80-c89b-11ea-9111-3916ccc86ac2.png)

**Comment by OmarEmaraDev** [comment]
You can concatenate the coordinates into a 2D array using the `column_stack` numpy function. Then you can use the `fromNumpyArray` method of the `Vector3DList` structure to convert to an AN list.
```
Vector3DList.fromNumpyArray(numpy.column_stack((x1, y2, z1)).ravel())
```
Also, make sure to create the arrays of type `float32`.

**Comment by stillpointx** [comment]
1)st way I tried:
```
x1 = np.float32(x1)
y1 = np.float32(y1)
z1 = np.float32(z1)
position1 = Vector3DList.fromNumpyArray(np.column_stack((x1, y1, z1)).ravel())
```

**Error:
Got Wrong Type expected 'Vector'**


2)nd way I tried: 
```
xp1 = np.float32(x1)
y1 = n.float32(y1)
z1 = np.float32(z1)
position1 = Vector((Vector3DList.fromNumpyArray(np.column_stack((x1, y1, z1)).ravel())))
print("position1 dtype=%s " % type(position1))

```
**Error in position1 line:
mathutils.Vector(): sequence index 9999 expected a number, found 'Vector' type.**

**Comment by OmarEmaraDev** [comment]
Where did this error occur `Got Wrong Type expected 'Vector'`? Can you share a minimal reproducible expression?

**Comment by stillpointx** [comment]
Sure.

```
import math
import numpy as np

def surf(u, v):

    x1 = u*np.sin(u)*np.cos(v)
    y1 = u*np.cos(u)*np.cos(v)
    z1 = u*np.sin(v) - np.sin(60/180 *np.pi) *np.sqrt((x1**2 + (y1)**2))
    return x1, y1, z1

ux, vx = np.meshgrid(np.linspace(0, 4*np.pi, 100), np.linspace(0, np.pi, 100))

x1, y1, z1 = surf(ux,vx)

#Change float type from float64 to float32
x1 = np.float32(x1)
y1 = np.float32(y1)
z1 = np.float32(z1)

position1 = Vector3DList.fromNumpyArray(np.column_stack((x1, y1, z1)).ravel())
```

![screenshot-July-18-2020-08:11:49](https://user-images.githubusercontent.com/28985314/87852253-5bf7b500-c8ce-11ea-93c0-e03a507420f3.png)
[fermat5_python_uv_an.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/4941612/fermat5_python_uv_an.blend.zip)

![screenshot-July-18-2020-08:15:38](https://user-images.githubusercontent.com/28985314/87852328-f35d0800-c8ce-11ea-96e7-5dc5f921bc6d.png)

**Comment by OmarEmaraDev** [comment]
The output of your script node has a wrong type. It should be a Vector3D List.

**Comment by stillpointx** [comment]
Maybe I'm missing something.  But that option is shown.

![screenshot-July-18-2020-08:40:46](https://user-images.githubusercontent.com/28985314/87852720-83508100-c8d2-11ea-91bc-66a3f005e0a4.png)

I'm using AN 2.1.7

**Comment by OmarEmaraDev** [comment]
"Vector List" is an alias for "Vector 3D List".

**Comment by stillpointx** [comment]
Thanks!
