### ISSUE TITLE
Cant install Linux Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by rememberyywwhh** [JacquesLucke/animation_nodes#1478]
blender version 2.83.2
Python 3.7.6
combine file https://github.com/JacquesLucke/animation_nodes/tree/master

**Comment by OmarEmaraDev** [comment]
Did you download from https://animation-nodes.com/#download?

**Comment by rememberyywwhh** [comment]
> Did you download from https://animation-nodes.com/#download?
thank for reply 
 i dont know what i did
its work now
