### ISSUE TITLE
Noodles doesn't appear after making a attachment between nodes, but shows the preview while making attachment in animation nodes v2.1 for python3.7 in Windows

### ISSUE THREAD

**Issue by Balaji-Ganesh** [JacquesLucke/animation_nodes#1479]
For detailed explanation:
We made a question in stack exchange, can be accessed via https://blender.stackexchange.com/q/187036/101521

**Comment by OmarEmaraDev** [comment]
Do other node editor experience the same issue?

**Comment by Balaji-Ganesh** [comment]
Yes!! even the Shade editor too.

**Comment by OmarEmaraDev** [comment]
Then this is a Blender bug, you can report it here https://developer.blender.org/
