### ISSUE TITLE
Some thoughts about the new Create List node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#148]
1. Allow to create Integer List. (it is sometimes really convenient when we only want all to be integer);
2. Allow to create Integer List;
3. When setting type to Object, bring back "From Selection" button.

FYI, thanks.

**Comment by LeonCheung** [comment]
Grr.. just noticed I was actually stupid to make two points here instead of three. What I actually mean in Point Two is to bring back "Show Option" toggle.  Sorry for misleading.

**Comment by JacquesLucke** [comment]
"show options" should be called "Hide All Inputs" here, right?

**Comment by LeonCheung** [comment]
Ah, right. It does mean that indeed.
