### ISSUE TITLE
How to get value directly from a socket?

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1480]
For example, From float math node i was trying to access value of first input. 
i tried `self.inputs[0].value` but it not working when list of values is given.

**Comment by OmarEmaraDev** [comment]
What do you mean by "when list of values is given". Generally, the `getValue` method of the socket should be used.

**Comment by harisreedhar** [comment]
Hi, sorry forget about list, see this example. how can i get value of second input which is linked with other node? Output here is 0 which is not the value i want, i was hoping to get value 10.
![floatsocket](https://user-images.githubusercontent.com/46858047/88012834-8351ba80-cb38-11ea-8f79-70ecfaffa246.png)

**Comment by OmarEmaraDev** [comment]
You can't. Values are not stored per socket, they are computed on the fly when evaluating the node tree, and only in the context of its execution.

**Comment by harisreedhar** [comment]
> You can't. Values are not stored per socket, they are computed on the fly when evaluating the node tree, and only in the context of its execution

Ok, thank you
