### ISSUE TITLE
Calculating the edge and polygon indices numerically to build mesh

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1482]
I can calculate the vertices and faces but how does one calculate the **edge and polygon indices** in python numerically to build the mesh?

### Animation Nodes:
![screenshot-July-22-2020-14:11:49](https://user-images.githubusercontent.com/28985314/88212625-8d9db280-cc25-11ea-8c26-73130b3bccd2.png)

### Image it creates:
![screenshot-July-22-2020-14:12:02](https://user-images.githubusercontent.com/28985314/88212691-a73efa00-cc25-11ea-8ceb-fa0992136acf.png)

### Image I'm trying to get:  (It has faces filled in)
![screenshot-July-22-2020-14:19:00](https://user-images.githubusercontent.com/28985314/88213210-6abfce00-cc26-11ea-961a-7ab324fafe61.png)

### Python script used:
```
import bpy
import math

def parametricfunc(val1):

    # mesh arrays
    verts = []
    faces = []

    # mesh variables
    numX = 50
    numY = 50
    
    # fill verts array
    for i in range (0, numX):
        for j in range(0,numY):
            # nomalize range
            u = 8*(i/numX-1/2)
            v = 2*math.pi*(j/(numY-1)-1/2)

            x = 2*math.sqrt(1+u*u)*math.cos(v)*(val1/12)
            y = 2*math.sqrt(1+u*u)*math.sin(v)*(val1/12)
            z = 12*u/(val1/12+0.01)

            vert = (x,y,z)
            verts.append(vert)
            
    # fill faces array
    count = 0
    for i in range (0, numY *(numX-1)):
        if count < numY-1:
            A = i
            B = i+1
            C = (i+numY)+1
            D = (i+numY)
            face = (A,B,C,D)
            faces.append(face)
            count = count + 1
        else:
            count = 0
    
    return x, y, z, verts, A, B, C, D, faces
            
x, y, z, verts, A, B, C, D, faces = parametricfunc(val1)            
        

```

**Comment by OmarEmaraDev** [comment]
You can use Animations Nodes grid mesh generation algorithms. In this case, edges can be generated using the `quadEdges` function.

```
AN.algorithms.mesh_generation.grid.quadEdges(50, 50)
```

Similarly, polygons can be generated using the `quadPolygons` function.

```
AN.algorithms.mesh_generation.grid.quadPolygons(50, 50)
```

Finally, notice that both functions have two default arguments for joining the terminals horizontally and vertically, they default to `False`.

**Comment by stillpointx** [comment]
Thanks!!  that fixed it :-)
```
     edges = AN.algorithms.mesh_generation.grid.quadEdges(50, 50)
     poly = AN.algorithms.mesh_generation.grid.quadPolygons(50, 50)
return x, y, z, verts, A, B, C, D, faces, edges, poly
            
x, y, z, verts, A, B, C, D, faces, edges, poly  = parametricfunc(val1)     
```
