### ISSUE TITLE
i am not able to install animation node 3.7 or 3.8 on Ubuntu 20.04 LTS.

### ISSUE THREAD

**Issue by tsandeep156** [JacquesLucke/animation_nodes#1484]
Memory- DDR2 4GB
Graphic card-GeForce GT 710/PCIe/SSE2
Processor-i
![Screenshot from 2020-07-25 09-25-46](https://user-images.githubusercontent.com/68765637/88448599-118daf80-ce5d-11ea-9ee9-c89d21eeaf60.png)
![Screenshot from 2020-07-25 09-25-46](https://user-images.githubusercontent.com/68765637/88448604-1e120800-ce5d-11ea-9868-503f70fa2317.png)
![Screenshot from 2020-07-25 09-25-46](https://user-images.githubusercontent.com/68765637/88448617-3e41c700-ce5d-11ea-9d78-0b2c0f7ac46d.png)

ntel® Core™2 Quad CPU Q8400 @ 2.66GHz × 4 
I am using blender-2.90.0-d7c4e9649320-linux64.tar.xz
Ubuntu python version support 3.8.2

this is blender PYTHON INTERACTIVE CONSOLE 3.7.7 (default, Jul  9 2020, 12:52:49)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

**Comment by OmarEmaraDev** [comment]
See #1240.

**Comment by somerandomguy592** [comment]
Taken from issue #1240:
Animation Nodes needs the python dynamic library in order to work. Install python3.x or/and libpython3.x from your package manager of choice.

Ubuntu
Ubuntu users may install libpython3.x from the deadsnakes PPA using the following commands. (Making sure to replace x with the target version.)

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update -y && sudo apt upgrade
sudo apt install libpython3.x

**Comment by mrmowgli** [comment]
The readme should mention this. The core issue is that blender is bundled with 3.7 but Ubuntu is bundled with 3.8.  Trying to use the version compiled for 3.8 on the download site also fails, complaining blender uses only 3.7.  Is there any way to have AN use the bundled blender version?  Or alternatively get blender to use the system python?

**Comment by OmarEmaraDev** [comment]
@mrmowgli 

> Is there any way to have AN use the bundled blender version?

Animation Nodes already uses the bundled version. You just need to install the version compiled for your python version, which is typically 3.7 if you download from anywhere other than the Ubuntu package repository. The main problem is, you need the dynamic python library if you are using 3.7 (3.8+ doesn't need that). You can download that as we described in #1240.

> Or alternatively get blender to use the system python?

You can do that but only if the system python version matches that of Blender, so it is practically useless. See https://docs.blender.org/api/current/info_tips_and_tricks.html#bundled-python-extensions
