### ISSUE TITLE
The Material Output node does not work properly.

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1485]
Hi...
The _Material Output_ node does not update the inputs (Color, Roughness, Metallic) of the _Principled BSDF_ node. However, other inputs are working, e.g., Pass Index, Screen Space Reflection, etc.

Thank you.

![Screenshot from 2020-07-25 23-36-51](https://user-images.githubusercontent.com/30294746/88463357-cbbdff00-cecf-11ea-9565-432f25762c69.png)

**Comment by OmarEmaraDev** [comment]
The Material Output node have nothing to do with Cycles shader nodes. This what the Cycles Material Output node is for. The node only edits the material settings, which you can find in the Viewport Display panel.

**Comment by 3DSinghVFX** [comment]
Okay, Thanks for the clarification.

**Comment by 3DSinghVFX** [comment]
However, those settings look different in Cycle and Eevee:
Cycle:
![Cycle](https://user-images.githubusercontent.com/30294746/88465343-e4361580-cedf-11ea-9a8f-e752831fc0c3.png)

Eevee:
![Eevee](https://user-images.githubusercontent.com/30294746/88465351-ee581400-cedf-11ea-8a31-b5f11b44e52a.png)

**Comment by OmarEmaraDev** [comment]
What is the difference exactly?

**Comment by 3DSinghVFX** [comment]
In the Cycles, the Viewport Display panel has all the settings, however, in Eevee, they split into two panels 

Eevee
![Eevee](https://user-images.githubusercontent.com/30294746/88471702-c5f50780-cf29-11ea-8d36-93054ba5279d.png)

Cycles
![Cycle](https://user-images.githubusercontent.com/30294746/88471704-d4dbba00-cf29-11ea-98f9-8df57f52da38.png)

**Comment by OmarEmaraDev** [comment]
They are still part of the same data block, so the difference is only in the drawing.

**Comment by 3DSinghVFX** [comment]
Okay.
