### ISSUE TITLE
Unable to connect matrix nodes to matrix or matrix list input of script node vis a vis matrix output.

### ISSUE THREAD

**Issue by nexus12** [JacquesLucke/animation_nodes#1487]
This is probably not a bug, but I am noob at programming. I want to change an element of a matrix, and fell at the first hurdle.
Also feature request for matrix node where have inputs for each element in matrix

Edit
I got out the  wrong side of bed this morning as the saying goes. I was trying to connect it to the actual script node not the invoked node! Duh!

**Comment by OmarEmaraDev** [comment]
I don't think we will create a node to alter the matrix elements directly, because they explicitly represent transformation matrices. But you can do that using a simple python script.
