### ISSUE TITLE
Can't create deep copies of mesh in animation nodes

### ISSUE THREAD

**Issue by MoamenAbdelsattar** [JacquesLucke/animation_nodes#1489]
I'm trying to do procedural modeling in animation nodes, I want to duplicate a circle along another circle with rotations from 0 to 360 to create a torus. For testing I tried the translations alone, I discovered that the other branch of the loop subprogram (the rotations branch) is affecting the branch of translations.
![Deep copy](https://user-images.githubusercontent.com/68331166/89169950-44335880-d57f-11ea-91eb-f364fea7c82e.PNG)
After I disable rotation in (compose matrix) node in the upper branch, the rotations disappear:
![deep copy 2](https://user-images.githubusercontent.com/68331166/89170068-6c22bc00-d57f-11ea-9f3f-eeaf59aa9cb0.PNG)
I tried to create deep copies of the mesh using copy module in python, but it throws an error and doesn't work:
![deep copy 3](https://user-images.githubusercontent.com/68331166/89170429-e6534080-d57f-11ea-89b4-f855b38ef123.PNG)

**Comment by MoamenAbdelsattar** [comment]
![copy mesh](https://user-images.githubusercontent.com/68331166/89174253-d4749c00-d585-11ea-8815-a74fcf62e49e.PNG)
I finally could copy the mesh using this group, thank you.

**Comment by OmarEmaraDev** [comment]
Animation Nodes avoids copying complex data structures when passed to loops if possible. You don't want to copy a constant parameter for each iteration. However, you may enforce copying by enabling Copy in the Advanced Node Settings of the parameter.

![Edwp68LXsAAmEek](https://user-images.githubusercontent.com/25300994/89176433-cfb1e700-d589-11ea-9021-dcb1ffe52787.png)

https://docs.animation-nodes.com/documentation/subprograms/loop/#parameter-sockets

**Comment by OmarEmaraDev** [comment]
Also, a simple Replicate matrix node should do the job if you are interested in an alternative solution.

![20200803-131041](https://user-images.githubusercontent.com/25300994/89176738-6383b300-d58a-11ea-9b34-38753ba3641d.png)
