### ISSUE TITLE
Can't use direction to rotation node

### ISSUE THREAD

**Issue by somerandomguy592** [JacquesLucke/animation_nodes#1493]
So I used a Mesh Object Input node with all the outputs enabled, did a Combine Vector List on the vertex normals and the polygon normals. Then I fed the output of that into the Direction to Rotation node. The node is reset, but it still doesn't work.
Any idea why?
[animationnodes3.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/5035194/animationnodes3.blend.zip)

**Comment by OmarEmaraDev** [comment]
Seems to be working here. What is the output you are expecting?

![20200806-175221](https://user-images.githubusercontent.com/25300994/89552963-2d099a80-d80d-11ea-9bfc-93472808ac48.png)

**Comment by somerandomguy592** [comment]
Yeah, BTW I'm using AN 2.1 on a Linux Mint 19 machine, with the 'Build does not work at the moment' error message if condition codedeleted(after deleting, figured out that I needed libpython3.7).

**Comment by somerandomguy592** [comment]
I'm also using Blender 2.83 with the Node Arrange addon enabled.

**Comment by somerandomguy592** [comment]
![ANerror2](https://user-images.githubusercontent.com/55585272/89571971-bc9b5300-d7e5-11ea-8856-ce1ed9aa40e6.png)
![ANerror1](https://user-images.githubusercontent.com/55585272/89571973-bd33e980-d7e5-11ea-904d-1e09b68ce39f.png)

**Comment by OmarEmaraDev** [comment]
Can you check the terminal and paste the output here? This is probably an install conflict issue.

**Comment by somerandomguy592** [comment]
Sure..

**Comment by somerandomguy592** [comment]
Traceback (most recent call last):
  File "/home/inlerlu/.config/blender/2.83/scripts/addons/animation_nodes/operators/output_execution_code.py", line 14, in execute
    code = getCurrentExecutionCode(lineNumbers = True)
  File "/home/inlerlu/.config/blender/2.83/scripts/addons/animation_nodes/operators/output_execution_code.py", line 46, in getCurrentExecutionCode
    codes = unit.getCodes()
AttributeError: 'NoneType' object has no attribute 'getCodes'

location: <unknown location>:-1

**Comment by somerandomguy592** [comment]
That's what happened when I clicked 'Profile' in the Developer panel of the Node Tree tab.

**Comment by somerandomguy592** [comment]
![ANerror3](https://user-images.githubusercontent.com/55585272/89574079-cecac080-d7e8-11ea-99b0-1890f0216537.png)

**Comment by OmarEmaraDev** [comment]
Can you try removing Animation Nodes *manually* and installing it again. Some of those unexplained issues stem from conflicts between old installed files and current versions.

**Comment by somerandomguy592** [comment]
Ok, will try, but Vector to Euler works fine for me.

**Comment by somerandomguy592** [comment]
Have now reinstalled AN, Direction to Rotation works fine now.

**Comment by OmarEmaraDev** [comment]
Ok. That's good to hear.
