### ISSUE TITLE
How does one do a simple deform on a mesh or an object.

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1494]
How does one do a simple deform on a mesh or an object.

I'm trying to recreate the simple deform modifier but using animation nodes.

![vokoscreen-2020-08-07_10-17-59](https://user-images.githubusercontent.com/28985314/89655695-7a7f1980-d898-11ea-9fc6-649d198c9c1f.gif)

**Comment by OmarEmaraDev** [comment]
If you are feeling advantageous, check the Blender source code, in particular, the `simpleDeform_bend` function in `MOD_simpledeform.c`. If you can't, I will check it and get back to you when I have the time.

**Comment by stillpointx** [comment]
I didn't think it would be so complex I was just looking to find out the Animation Nodes that would create that animation.  Using just the Compose / Transform Nodes just wasn't working out for me.

**Comment by OmarEmaraDev** [comment]
It is not that complex, just a certain formula that needs to be applied. I will look into it as soon as I have the time.

**Comment by stillpointx** [comment]
Thanks

**Comment by stillpointx** [comment]
How did you choose the center point of the bend?
