### ISSUE TITLE
Cant install animation nodes in blender 2.79, 2.80, 2.81, 2.82, 2.83.4, 2.90 beta, 2.91 alpha in linux 20.04

### ISSUE THREAD

**Issue by shridhar2011** [JacquesLucke/animation_nodes#1496]
![Screenshot from 2020-08-09 08-51-33](https://user-images.githubusercontent.com/56965716/89727932-b8ba3b80-da46-11ea-884e-0849c2cde2f7.png)
Error line 351, 158. in all versions of blender

**Comment by OmarEmaraDev** [comment]
Did you see the section on Ubuntu in #1240?

**Comment by shridhar2011** [comment]
Yes but cant find answers.
Please help.

**Comment by OmarEmaraDev** [comment]
Lets continue this in #1240.
