### ISSUE TITLE
Mesh getting deformed upon using sound spectrum animation (tut #6 - Chris Prenninger)

### ISSUE THREAD

**Issue by Shaileshbg1** [JacquesLucke/animation_nodes#1498]
I am following the tutorial 6 - More fun with audio 
https://www.youtube.com/watch?v=8PkdH_GXpQE&t=476srl

on a Ubuntu 20.04 with the latest version of blender: 2.83.4, with build date: build date: 2020-08-05, 06:00:03 and animation_nodes_v2_2_linux_py37 downloaded from official page. 

But upon playing the animation with just the first line of vertices moving, my mesh gets broken and the grid becomes infinitely long in the y-direction. I have tried with different blender versions of 2.82 and 2.90. I have tried compiling the animation nodes and installing that, I have also tried using Github desktop to get the folders from the latest branch and replacing them in the animation folder...
I have attached a screenshot showing the effects after I check 'auto-execution' and 'frame-change'
![animation_nodes_v2_2_linux_py37_blender_2_83_4](https://user-images.githubusercontent.com/32194415/89866816-d06ffc00-dbcd-11ea-891f-f85d9a3c4f5f.png)

Here is a link to a screen recording showing the process and the blend file to replicate the issue. 
https://drive.google.com/drive/folders/1Z9M6iN2iQH9mMQf5N4acqNoYP8UTPEXQ?usp=sharing

Please help, any suggestions would be greatly appreciated.

**Comment by OmarEmaraDev** [comment]
You are reading the data from the Grid object and writing them to the same Grid object again, hence the growing effect you see. Simply create a new object to assign the mesh to by pressing the Plus button in the Mesh Object Output node.

**Comment by Shaileshbg1** [comment]
Thank you very much. That part is working now so the first line of vertices move as per the sound spectrum. 

But in the second part of the video, he tries to get the wave to move progressively downwards on the mesh. A new subprogram is used to create a vector list that is fed back to this initial grid.  Those changes are not being recognized. In the below screenshot - a subprogram called 'shift' is feeding to the grid, the jump in the mesh is supposed to move forward.
![Screenshot from 2020-08-11 16-14-05](https://user-images.githubusercontent.com/32194415/89889175-daeebd80-dbee-11ea-9f84-7b276a242ca5.png)
I tried creating another object but it does not work. Thank you again for your time.

**Comment by OmarEmaraDev** [comment]
I see. I haven't seen the tutorial you are referencing, so I it is best to ask Chris or the community about this. Perhaps ask in [BSE](https://blender.stackexchange.com/questions/tagged/animation-nodes).

That said, I don't think this node tree is a good idea. Simply evaluate the sound at multiple frames and offset a grid based on those sample. Maybe cache the output for faster revaluation. Like this:

![20200811-135724](https://user-images.githubusercontent.com/25300994/89894612-a7099d00-dbda-11ea-8b51-7701c7a8fcbb.png)

**Comment by Shaileshbg1** [comment]
Thank you Omar for the idea and the node tree. I am new to blender and AN, so I need a bit more help in executing this. 
1) In the subprogram loop input, what is the type of the iterators 'Count' and 'Frame'. When I invoke subprogram with 'Float List' as iterator type, I do not get 'Iterations', ''Count and ''Frame' options.
2) In this way is the 'grid mesh' is defined through AN itself? So I need not add a grid mesh manually in the layout right? 

Sorry if these are trivial questions.
I will post my query on the tutorial defined node tree on BSE. Thank you for your time.

**Comment by OmarEmaraDev** [comment]
1. If no iterators are present, Animation Nodes will automatically add an `Iterations` input that controls how many times the loop will run. So don't add an iterator list and you will get that input. Count and 'Frame are parameters of type Integer, they are not iterators.
2. Yes. The grid is generated by Animation Nodes procedurally. You don't need to create a grid in Blender or read it in Animation Nodes.

**Comment by Shaileshbg1** [comment]
Thank you very much Omar. It's working :) :+1: 
I request your suggestion on one last question. 
I am working on animating/visualization of heart sounds, in which case frequency becomes a big factor. Is there a way in which I can separate out the frequencies and highlight them using shading, lights or vertex movement or any way?
Thank you for your time.

**Comment by OmarEmaraDev** [comment]
Sure, that's what Animation Nodes is for. For details on how you can extra frequencies from the sound, check the documentation on the Node. https://docs.animation-nodes.com/documentation/nodes/sound/sound_spectrum/

I can give you pointers, but you are going to have to be more specific. What exactly is the effect you are trying to achieve?

**Comment by Shaileshbg1** [comment]
Hi Omar, 

Thank you for your reply. I did check the documentation but as I am still working on understanding heart sound frequencies, I still need time to understand what needs to be animated. 

For now, I want to automate this process using bpy. These are the steps which I have followed: 
1) Use the ''background_job.py" template to automate the task and run blender from command line. 
2) Use editor type - 'info' to capture all my animation node definitions into script form. Paste the script contents into 'background_job.py' and run from command line.

The first line of the script is:

bpy.context.area.ui_type = 'an_AnimationNodeTree'

As bpy as a python module is headless and there is no ui associated with bpy, I commented out this line. Upon running it cannot identify node tree: 

`KeyError: 'bpy_prop_collection[key]: key "NodeTree" not found'`

How do I access and run animation nodes from a python script? Thank you for your time.

**Comment by OmarEmaraDev** [comment]
What process are you trying to automate exactly?

**Comment by Shaileshbg1** [comment]
Hi Omar, The process which you explained above of - evaluating the sound at multiple frames and offset a grid-based on those samples". 
![image](https://user-images.githubusercontent.com/32194415/90537145-95a43000-e19a-11ea-96f5-0647509acc97.png)

**Comment by OmarEmaraDev** [comment]
Yes, but Animation Nodes does everything here, what are you trying to automate?

**Comment by Shaileshbg1** [comment]
Hi Omar,

I want this process to be scripted so that it can run on a server listening to sound file input and output a movie for every sound file passed. 
There will be an API call that passes the sound file to this process and another API call that will fetch the output of this process.

I am trying to get the whole animation nodes process as a function of this form:

def animation_function(path_to_sound_file):
    ---- animation nodes -----
    return(animation.mp4)

**Comment by OmarEmaraDev** [comment]
I see. You probably don't need access to Animation Nodes trees anyways. You can construct the sound from a sound sequence in the sequencer. See:
https://docs.animation-nodes.com/documentation/nodes/sound/sound_from_sequence/

Then, in your script, just update the source of the sound sequence strip and its lengths. Also update the scene end frame.

**Comment by Shaileshbg1** [comment]
Hi Omar, thank you for your reply, but could you please explain a bit more on how I can construct such a script. The link only provides definitions so some more detail would be of great use to me. Thank you for your time.

**Comment by OmarEmaraDev** [comment]
Lets assume your base file is composed of a sound you generate from the sound sequence called `AnimationNodesSound`. In order to change the sound file used whose path is `filePath`, you may use the following script. You may execute this script from the CLI followed by the `-a` flag to render the animation.

```python
import bpy
import aud

scene = bpy.data.scenes['Scene']
sequence = scene.sequence_editor.sequences_all["AnimationNodesSound"]
filePath = "path/to/your/sound/file.ogg"

sound = aud.Sound.file(filePath)
soundDuration = sound.length / sound.specs[0]
soundFrameDuration = soundDuration * scene.render.fps

scene.frame_end = soundFrameDuration
sequence.frame_final_duration = soundFrameDuration
sequence.sound.filepath = filePath
```

![20200819-191617](https://user-images.githubusercontent.com/25300994/90668420-605a1980-e250-11ea-9675-2cf80ec97888.png)

**Comment by Shaileshbg1** [comment]
Hi Omar, 

Thank you very much for your help. I was able to pass different sound files and use animation nodes successfully to deform mesh points. Closing the issue as it is resolved. Thank you for your time.
