### ISSUE TITLE
Freature Suggestion: Trim Text Backwards

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#150]
Trim Text: Allow trimming back from the last character. (probably adding an "End" value setting?)

**Comment by JacquesLucke** [comment]
I will break some files which use this node now..

**Comment by LeonCheung** [comment]
Just saw the implementation. thought it is not exactly what I really meant, but that is cool, as well.

Hmm, I think I was discussing something like this:

e.g. Now with a list: ['Trim','Text','Backwards'], in my idea, I want to trim off the last letter while keeping the rest (or keep the last one while deleting the rest). For now, It seems I have to use quite a fiew nodes to achieve that:

![backw](https://cloud.githubusercontent.com/assets/494788/8143319/6ac20746-11d8-11e5-910f-b7390998e4ac.jpg)

Yeah, it works. But I just think this is the duty of Trim Text node. Isn't it?  :)

**Comment by JacquesLucke** [comment]
![text trimming](https://cloud.githubusercontent.com/assets/5881326/8150417/25e6870c-12e9-11e5-831f-5043d161032f.PNG)

**Comment by LeonCheung** [comment]
Cool and quick implement for using negtive Indices! :smile:

**Comment by og76** [comment]
https://github.com/JacquesLucke/animation_nodes/commit/ff2304e8e8f2f1b66b541c34455127f881da27c9
(does this work or should I post the file here?)

Great negatives. I was waiting for it.
but:
add boolean option for negative indexes. default to False //backwards compatibility
-It breaks existing trees (I have lot like this and may need to add clamps to all)
-if it's driven by frames, starting 35, to have typewriter effect I need to add a clamp now

the file has simple Boolean option. should we have a socket instead? (animate everything...)

**Comment by JacquesLucke** [comment]
yes this did work, although I have no idea why :D where did you make this commit?

Yes I can add this boolean option, but I prefer to have it as property and not as socket

**Comment by og76** [comment]
![git1](https://cloud.githubusercontent.com/assets/11709974/8159222/32c9fea2-136d-11e5-9e65-bdc0dc065f7c.PNG)

I say edit in your sock branch, made no fork myself

**Comment by og76** [comment]
and yes, I used prop also, not socket ...

**Comment by JacquesLucke** [comment]
ahh okay, thanks for the screenshot :)

Can this be considered as final implementation of this node?

**Comment by og76** [comment]
Final? Don't you just love working on closed issues? :smile:

**Comment by JacquesLucke** [comment]
:D
