### ISSUE TITLE
Search panel duplicate and uses different shortcut

### ISSUE THREAD

**Issue by j-morgado** [JacquesLucke/animation_nodes#1502]
Animation Nodes v2.2.0 uses a different shortcut from Blender to search for nodes and displays 2 search menus (see image attached). This is slightly confusing and not intuitive. 

Blender uses "S" after pressing "Shift+A" to search for nodes, but Animation Nodes uses "E" after pressing "Shift+A" or alternatively it uses it's own separate shortcut "Ctrl+A".
Also, the add node menu in Animation Nodes shows to "Search" entries and the first one starts an non functional search box.

Not sure if these are limitations caused by Blender itself or an Animation Nodes bug.

![image](https://user-images.githubusercontent.com/17785361/90257404-25518380-de15-11ea-802f-192cc901104c.png)

**Comment by OmarEmaraDev** [comment]
We submitted a patch upstream in [D8576](https://developer.blender.org/D8576).

**Comment by OmarEmaraDev** [comment]
Commited in [e14de692fc99](https://developer.blender.org/rBe14de692fc99b5e66d93c6240ec51410d087cf4d). This fix will be in Blender 2.91. Thanks for the report!
