### ISSUE TITLE
How to get proper text location after split text node?

### ISSUE THREAD

**Issue by dwizor** [JacquesLucke/animation_nodes#1505]
Is there a option to distribute text in the same locations after split text node as it was located before it?

![Reference](https://user-images.githubusercontent.com/68112419/90309891-b34c6d80-deec-11ea-8a5a-c2e1af2d821c.jpg)

**Comment by OmarEmaraDev** [comment]
That's what the Decompose Text node is for.
https://docs.animation-nodes.com/documentation/nodes/text/decompose_text/

**Comment by dwizor** [comment]
Oh I didn't know this node existed because I didn't see it in the list in text section ^^
Also i didn't know Animation Nodes have documentation + manual, i saw only manual before, thanks  ;D

**Comment by OmarEmaraDev** [comment]
Added the node to the menu in e3f3ccb. Thanks for notifying us about it!

The docs is technically the new manual. We will remove the manual at some point.
