### ISSUE TITLE
Something about ”Copy Object Data“ Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#151]
1. Is it possible to support deep copy? I mean to copy modifiers, constraints, vgroups, vcolors, etc.
2. I'm not sure if this is a bug, but it sometimes didn't work with list:

![copy_data](https://cloud.githubusercontent.com/assets/494788/7902040/926c84cc-07da-11e5-93c1-f2ff65275afa.jpg)

[example file](http://www.pasteall.org/blend/36326)

**Comment by JacquesLucke** [comment]
1. unfortunally not, This node does something different.

2. the problem in your file was that there was an error because you tried to copy mesh data onto a text object. This doesn't work

**Comment by LeonCheung** [comment]
Sure. But it does copy material. Is that intended?

**Comment by JacquesLucke** [comment]
In fact I didn't know that it copies materials but yes it is intended then.
I'm only exposing a basic operation into a node here:
https://github.com/JacquesLucke/animation_nodes/blob/master/nodes/object/mn_copy_object_data.py#L26
I don't plan to change that simple line

To just copy the mesh you can use the mesh nodes
![copy mesh](https://cloud.githubusercontent.com/assets/5881326/7904769/92d1aa58-0809-11e5-9df9-0fce66edd84d.JPG)
