### ISSUE TITLE
AN Object Container for Object Instances doesn't allow for more than one instance

### ISSUE THREAD

**Issue by Keidini** [JacquesLucke/animation_nodes#1511]
Trying to create a matrix of cubes, then a matrix of squares. AN only displays the matrix of cubes from memory and then after trying to configure the object instancer to the square, it crashes and I have to start from scratch.

**Comment by OmarEmaraDev** [comment]
Can you provide more information? Maybe a screenshot of the node tree, what you expect, and what you get instead.
