### ISSUE TITLE
No way to delete path

### ISSUE THREAD

**Issue by hitrpr** [JacquesLucke/animation_nodes#1513]
![49725058](https://user-images.githubusercontent.com/21099918/91005533-cbed0f80-e5df-11ea-949e-43231d7a610e.png)
Hello, it seems, there is no way to delete second path, if I don`t need it.
Imagine: I have node with 5 paths, and I want to get rid of one of them.
Should I re-create node from scratch?

**Comment by OmarEmaraDev** [comment]
Good point. I will add a delete option.

**Comment by OmarEmaraDev** [comment]
Implemented in 20a502f. Thanks for the suggestion!

**Comment by hitrpr** [comment]
thank you!
