### ISSUE TITLE
Mesh Object Output Node doesn't work now!

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1514]
![mesh object ouput error](https://user-images.githubusercontent.com/64368228/91030970-7e4dc280-e632-11ea-8172-d5e206f99d31.png)

![not match](https://user-images.githubusercontent.com/64368228/91030992-87d72a80-e632-11ea-8f32-0f7b42eed53a.png)

this error appears in latest version 2.8 AN!

**Comment by OmarEmaraDev** [comment]
This doesn't seem to be latest Animation Nodes. Try reinstalling Animation Nodes and test again.

**Comment by kdsin23** [comment]
> This doesn't seem to be latest Animation Nodes. Try reinstalling Animation Nodes and test again.

Thank you! i tried the latest version, it is working now!
