### ISSUE TITLE
interpolation in start/stop mode of “float range node“”, and change in "map range" node.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1515]
1. having interpolation function in "float range" node can help generate a series of number with specific distribution. Currently the alternative method is to use "map range" node, whose input minimum & maximum equal to output minimum & maximum respectively. In reality, every time if I change input minimum and maximum (start/stop), I have to synchronize the change in map range using "float input" node. Therefore, at least 4 nodes (including two float input nodes) need to be used. If interpolation in start/stop mode is possible, then 1 node can replace these 4 nodes.
![interpolation](https://user-images.githubusercontent.com/55994236/91044403-38b5d900-e5e3-11ea-89c7-c30352634a6d.png)

2. Currently, in map range node, input minimum must be smaller than input maximum.
If I wish to inverse minimum and maximum, I have to mirror the interpolation. This seems to be an extra step, and sometimes it's a limited thinking process that you can't directly reverse it.
I have checked, in shader nodes, input minimum can be lager than input maximum. So I hope this improvement in AN map range node can be also made.
![map range](https://user-images.githubusercontent.com/55994236/91044289-06a47700-e5e3-11ea-92f2-da1843118125.png)

**Comment by OmarEmaraDev** [comment]
Your second point was fixed in eb4ada0. Thanks for the report!

For your first point, I am not sure if that's a good idea. I will get back to you on this later.

**Comment by OmarEmaraDev** [comment]
Ok, so for your first point. I would keep the node as is, I don't want to unnecessarily complicate it. I think using an evaluate or a remap node is an acceptable option in this case. Feel free to reopen if you want to discuss this further.

**Comment by Gerstmann-Bradley** [comment]
> Ok, so for your first point. I would keep the node as is, I don't want to unnecessarily complicate it. I think using an evaluate or a remap node is an acceptable option in this case. Feel free to reopen if you want to discuss this further.

If I were to use the map range node, I must not only use it, but two additional float input nodes for synchronizing start and stop value..
Personally I made a group node, saved it in the startup file as a preset. so that I don't need to build these 4 nodes every time.
However, if 1 node can replace 4 nodes to achieve such a function in native AN, I think it will be much simpler for many people to work with that. In that case, I think it's necessary.

If you still think it's unnecessary, it's ok.
![map range](https://user-images.githubusercontent.com/55994236/91212739-a1ce4700-e6de-11ea-815a-86ed497e4072.png)

**Comment by OmarEmaraDev** [comment]
Implemented in e61048e.

**Comment by 3DSinghVFX** [comment]
> Implemented in [e61048e](https://github.com/JacquesLucke/animation_nodes/commit/e61048e56e38968eafc7309c91cbaaa6aa3cd99e).

Omar, If I input `Start = 0` then interpolation does not work in *Float Range* node,
![screen](https://user-images.githubusercontent.com/30294746/91665457-57502e80-eb13-11ea-88d8-84b0946d5fa4.png)

**Comment by OmarEmaraDev** [comment]
Seems to work here. Can you investigate further?

![20200830-193025](https://user-images.githubusercontent.com/25300994/91665567-d3884900-eaf6-11ea-8c35-aa64a87345dc.png)

**Comment by 3DSinghVFX** [comment]
If I add `Start = 0.000001` then it is fine working.

**Comment by OmarEmaraDev** [comment]
Can you do a clean rebuild?

**Comment by 3DSinghVFX** [comment]
> Can you do a clean rebuild?

I have tried that, still the same problem.

BTW, I'm getting a run time warning `/Documents/blender/blender2.83/2.83/python/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: animation_nodes.data_structures.meshes.mesh_data.Mesh size changed, may indicate binary incompatibility. Expected 64 from C header, got 72 from PyObject
  return f(*args, **kwds)
`

**Comment by OmarEmaraDev** [comment]
This runtime warning probably means that you don't have a clean build. Run `git clean -fdx animation_nodes` then compile again.

**Comment by 3DSinghVFX** [comment]
> This runtime warning probably means that you don't have a clean build. Run `git clean -fdx animation_nodes` then compile again

Omar, Thanks. 
But I have also checked with the AN build from the GitHub, problem is still there.

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley Can you replicate the issue that Kuldeep talks about?

**Comment by Gerstmann-Bradley** [comment]
> @Gerstmann-Bradley Can you replicate the issue that Kuldeep talks about?

Yes, I can.
2.90 beta & 2.91 alpha. AN up to date. WIN-10.
it's fine in linear mode, but in other mode, if the start is 0, nothing will work.

**Comment by OmarEmaraDev** [comment]
By bad, fixed in 549c169.

**Comment by 3DSinghVFX** [comment]
> By bad, fixed in [549c169](https://github.com/JacquesLucke/animation_nodes/commit/549c169601ca7e9f85dab4ff1e443aa3e591de6a).

Now it is working fine, thanks.
