### ISSUE TITLE
Curve Interpolation in Blender 2.83.1

### ISSUE THREAD

**Issue by Frankiscophil** [JacquesLucke/animation_nodes#1520]
Hello there. I have been having issues with both the latest version and version 2.1 of Animation Nodes involving the Curve Interpolation. Whenever I plug it to the scale of the Object Transform Output node through a Map Range Node, it doesn't show up; the meshes that should've been affected just end up vanishing. I am hoping this is fixed soon in due time. Thank you.

**Comment by OmarEmaraDev** [comment]
Can you share your node tree in question?

**Comment by Frankiscophil** [comment]
![image](https://user-images.githubusercontent.com/68121145/91673248-c8b8cd00-eb65-11ea-9851-a520f2fffba9.png)
![image](https://user-images.githubusercontent.com/68121145/91673271-f00f9a00-eb65-11ea-933f-f531d89eae84.png)

Here are the before (Map Range and Vector from Volume not connected) and after (Map Range and Vector from Volume connected). Even after moving around the empty that controls the effect, the particle meshes don't show up.

**Comment by Gerstmann-Bradley** [comment]
> ![image](https://user-images.githubusercontent.com/68121145/91673248-c8b8cd00-eb65-11ea-9851-a520f2fffba9.png)
> ![image](https://user-images.githubusercontent.com/68121145/91673271-f00f9a00-eb65-11ea-933f-f531d89eae84.png)
> 
> Here are the before (Map Range and Vector from Volume not connected) and after (Map Range and Vector from Volume connected). Even after moving around the empty that controls the effect, the particle meshes don't show up.

it's because the value in your map range node is 0, so the scale of objects turns to be 0

**Comment by Frankiscophil** [comment]
Yeah, I realized that the value wasn't connected to Evaluate Falloff, among other issues. Thank you very much for pointing that out! Apologies for assuming fault in the add-on. Thanks again; do have a good day!
