### ISSUE TITLE
Pie Menu content, format and file structure

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#153]
From #146 where there are:
-pie format (see empty position, fixed positions using row/col)
![Image of Pie Order](https://cloud.githubusercontent.com/assets/11709974/8041872/13aa200e-0e24-11e5-95c1-fd8a81e25400.PNG)
-pie file structure idea (insert menu from other files, near various nodes)

**Comment by JacquesLucke** [comment]
Can you maybe comment on the changes? :)

**Comment by og76** [comment]
At first glance:
That is exactly what I was thinking. Define some position, allow to insert on them or keep empty.
And yes, position 9/10 suck, I would not use them either ;)

Issues:
1.
We need a different behavior for **no selection**. Probably as another condition.
- **If deselect, there is still a pie that  accounts for the last active.** behavior unexpected.
( have some nodes. Deselect all (A). W. still ready to insert.. )
Seams like "active node" and selected state are not quite going together

- if empty tree, this is a good place for some very common nodes (simple insert, not insert linked)
or some presets. Like time info, math, obj transforms in/out ...

Conclusion: 
Need "no selection" condition. define Active node also checking if 

    bpy......["MyNode"].select 

as extra condition to say this is the active node? may be that simple ..
+maybe show the active node name in the pie label (as a check, not cause I have an obsession :))

2.
Suggestions are only nodes and socks. I cannot **insert an operator or menu**. Or nested pie?
My be enough to **accept a menu**.
- Then everybody defines that menu and operators in the node. (Script node may like the socket tipe and assign buttons, debug may have show in row and 2 sliders..)
- nodes will look like big black pie buttons, operators and such will look like normal menu buttons.
No confusion here

Conclusion: 
I see it like: check if menu suggestion, then check if node suggestion. Node beats menu. 
This way we keep the node + soc tuples, cause it's smart :)

I know that complicates thing, but I think is useful

3.
- have a insertSimpleNode besides insertLinkedNode, just no links. The difference may be making socket indices optional. (If no sock index, just simple insert.)  hmm
may work for issue 1 ..

**Comment by JacquesLucke** [comment]
Thanks for the feedback.

1. Yes you're right, I will implement this extra check for selection.
Having some basic starter stuff when the node tree is empty is also a good idea.

2. I want this w-menu for very fast usage only (except for the bottom right element, that can contain more than one element). There are many more keys on the keyboard. I have no problem with implementing other menus for other keys. 
Nested pie menus and normal menus always slow down (normal menus even more than pies, because normally you want to reach the point where you don't have to read the menu anymore).

3. Maybe (just maybe) I can make it so that no links will be created when the user holds down shift or so.


What is also important now is to find out which nodes are often used together

**Comment by og76** [comment]
2. I was just thinking of operators as in the pic I showed,  where i had operator instead of nodes.
No sub-menus
but I guess we can keep W for node insertion only
(It would be fast to have Rclick or doubleclick or so. Afaik it kinda sucks to make that in blender ...)

3. Most of the time I use math like: get math node, move between existing nodes (on top of an existing link) it's more direct than inset linked and then link further. 
That is what I was thinking when said simple node insertion. 

Immediate thought, often used: 
- any list out socket should gave get element and get length
- vector/matrix inputs to have separate vector/matrix
- vec/matrix out to have combine vec/  translMatrix, rotMatrix, scaMatrix  Combine matrix

**Comment by LeonCheung** [comment]
So the W pie menu works on active node only? For example, is it possible to select multiple nodes then add a Frame for them from pie?

**Comment by og76** [comment]
![frame join](https://cloud.githubusercontent.com/assets/11709974/8129107/51a3c3e6-110e-11e5-9e4e-c095c1d3cced.png)

**Comment by LeonCheung** [comment]
OK Thanks.
