### ISSUE TITLE
Blender startup performance problems w/ animation nodes

### ISSUE THREAD

**Issue by alinsavix** [JacquesLucke/animation_nodes#1531]
This is more of an FYI rather than a problem with animation nodes itself, but is useful knowledge that might be broadly applicable and potentially worth mentioning in the documentation somewhere.

The problem: After installing animation nodes, blender would sometimes take a *very* long time to start -- on the order of "multiple minutes" (though at first I just thought it was hung, and killed it after a minute or so). This wouldn't always happen, but happened enough to be pretty irritating.

Vital stats:
  OS: Windows 10, May 2020 release (release "2004", because Microsoft naming is beginning to collapse on itself)
  Blender: 2.83.x and 2.90.0 exhibit the problem
  Animation Nodes: 2.1

The problem/solution:

I spent some time looking at Blender using sysinternals' `procmon` tool. It looked like something weird was happening with anim_nodes because Blender would just sit there reading files from the addon for the entire time Blender was 'hung'. It almost seemed like Blender was hung in an infinite loop re-reading addon files, but that answer was ... unsatisfying.

Then I realized that most of the files I was seeing in the trace were `.pyd` files -- basically DLLs.

A little more experimentation led me to the conclusion that Windows Defender's realtime protection functionality was slowing the loading of these files by a massive amount. Turning off realtime protection takes the addon's load time from "multiple minutes" to "basically instant". I've done this repeatedly -- start blender (optionally monitor with procmon), and when it becomes clear it's going to be one of those "multiple minute" startups, turn off realtime protection, and blender finishes loading almost instantly.

I'm assuming that Windows Defender keeps some internal cache that allows Blender to start fast once it's gone through the slow startup once, and at some point that cache expires, requiring another round of slow loading before startup times are reasonable again.

There's a few possible solutions for users... you can't turn off realtime protection and have it stay off (it turns back on automatically), so that's not an answer (and you probably shouldn't, anyhow). So the other solutions are: don't use windows defender (not recommended), or add an exclusion in windows defender for the user's choice of 1-- the blender process, 2-- the blender addon path, or 3-- the `.pyd` file extension. None of these are great choices (because a Blender addon could absolutely contain malware, and `.pyd` files in general could absolutely contain malware (though that's probably pretty uncommon)), but having to wait multiple minutes for Blender to open also isn't a good option, so here we are.

Anyhow, leaving this here so that other people can find it and/or you could mention in the troubleshooting doc if you find it appropriate. Enjoy!

**Comment by OmarEmaraDev** [comment]
Many thanks for investigating this! I added a warning in https://github.com/JacquesLucke/animation_nodes_manual/commit/e28c334b24accea348befe7908d71daf6b12ddf4.

**Comment by alinsavix** [comment]
Man, that's some epic response time y'all got there. Kudos!

(...now, step 2 of my master plan: figure out how to use this durned thing...)
