### ISSUE TITLE
How to instace collections

### ISSUE THREAD

**Issue by dwizor** [JacquesLucke/animation_nodes#1533]
Hello, i have 4 objects in collections that need stick together, i want scatter thier positions to matrices in animation nodes, how to archieve this?
I tried used this setup which I found on the internet but it showing me wrong value(test is collection that i want instance).
![wrong_value](https://user-images.githubusercontent.com/68112419/93302246-f6567500-f7f9-11ea-96a9-c08caaba11e6.png)

**Comment by Gerstmann-Bradley** [comment]
> Hello, i have 4 objects in collections that need stick together, i want scatter thier positions to matrices in animation nodes, how to archieve this?
> I tried used this setup which I found on the internet but it showing me wrong value(test is collection that i want instance).
> ![wrong_value](https://user-images.githubusercontent.com/68112419/93302246-f6567500-f7f9-11ea-96a9-c08caaba11e6.png)

You need to input a collection instead of text. Because you are "selecting" collection.
Please use "collection input" node instead "text input"
![example](https://user-images.githubusercontent.com/55994236/93303535-9ba52500-f7c9-11ea-8c2b-e21be24a7065.png)

**Comment by dwizor** [comment]
Oh, you are right! Such a stupid mistake ;o works perfectly thanks!
