### ISSUE TITLE
[BUG] Nodes don't work properly and objects fly away for no reason

### ISSUE THREAD

**Issue by hilth-augusto** [JacquesLucke/animation_nodes#1536]
This video shows the problem
I had the same issue using the Collection input node. Not sure what I'm doing wrong or if it is a bug.

See the video to understand the problem:
https://twitter.com/i/status/1307043515743064064

**Comment by OmarEmaraDev** [comment]
This not a bug. Do not read and write to the same object. You essentially have an infinite feedback loop. To fix this, add a new object by pressing the plus button in the Object Mesh Output node and use that as the output object. Then hide the source object if needed.

**Comment by hilth-augusto** [comment]
> This not a bug. Do not read and write to the same object. You essentially have an infinite feedback loop. To fix this, add a new object by pressing the plus button in the Object Mesh Output node and use that as the output object. Then hide the source object if needed.

Thanks man... the problem was between the chair and the keyboard... hahaha
Sorry :)
