### ISSUE TITLE
Decompose Text node doesn't work as expected

### ISSUE THREAD

**Issue by noc2art** [JacquesLucke/animation_nodes#1538]
We need to make per-character sequential animations of text objects that should non-destructively be changed by the user. The only way in AN to do that is to use the "Decompose text" node. Yet, it is unable to yield the same result as a regular text object in terms of spacing between characters that are inherent to the font that's being used, thus making it almost impossible to make any use of it.

![image](https://user-images.githubusercontent.com/32395664/93655651-8cbeac80-fa2d-11ea-92ae-f797e53916ea.png)

The text above is the text decomposed and the one below is the regular Blender text object.

**Comment by OmarEmaraDev** [comment]
Can you show us the node tree used here?

**Comment by noc2art** [comment]
Hi Omar;

Thank you for getting back. I'm sharing the blend file (2.90) The text object below is the master object from which the data.body is fed into the decomposed text.

https://drive.google.com/file/d/1r8GZHzpwThjX0y_A2UWBUjzTZhOgt9Cu/view?usp=sharing

Cheers;

AJ

**Comment by OmarEmaraDev** [comment]
The issue is in the text horizontal alignment in your source text object. We only support the default alignment (Left). I recommend you don't copy for a source object in the instancer node to avoid such differences.

**Comment by noc2art** [comment]
Thank you so much Omar for taking the time to help. Much appreciated.

Cheers;

AJ
