### ISSUE TITLE
How to call a function with argument with the invokeFunction ?

### ISSUE THREAD

**Issue by akaflokart** [JacquesLucke/animation_nodes#1540]
Hi,

if i try to call a function with the invokeFunction it works if the function have no argument but with a argument i dont know how to call it.

Example without argument (this works)
```` python
class ExampleNode(bpy.types.Node, AnimationNode):
    ...

    def draw(self, layout):
        self.invokeFunction(row, "refreshCamera")

    def refreshCamera(self):
        # Do the refresh.

    ...

````
Example with argument (this doesnt work)

````python
class ExampleNode(bpy.types.Node, AnimationNode):
    ...

    def draw(self, layout):
        self.invokeFunction(row, "refreshCamera(Argument)") # dont know how to call the "refreshCamera" function with Argument

    def refreshCamera(self, Argument):
        # Do the refresh.

    ...
````
Tips are welcome.

**Comment by OmarEmaraDev** [comment]
It is possible to pass a string argument and parse it in your method. For instance:
```python
class ExampleNode(bpy.types.Node, AnimationNode):
    ...

    def draw(self, layout):
        data = "5" # Some string data.
        self.invokeFunction(row, "refreshCamera", data = data)

    def refreshCamera(self, data):
        parsedData = int(data) # Parse the data and use it.
        # Do the refresh.

    ...
```
Notice that `refreshCamera` is a method of the node class and can access all the data in the class instance. So avoid passing complex data in the invoke function and only pass "pointers" to them.

**Comment by akaflokart** [comment]
Thanks Omar,
i wasn`t clear , the argument is a float list as a input like the following structure.
I can convert it to a string and back to float but the draw method dont accept a argument.


````python
class ExampleNode(bpy.types.Node, AnimationNode):
    ...
   def create(self):
        self.newInput("Float List", "Window Pos Size", "WindowPosSize")

    def draw(self, layout,WindowPosSize): # This dont work obviously
        data = WindowPosSize # Some string data.
        self.invokeFunction(row, "refreshCamera", data = data)

    def refreshCamera(self, data):
        parsedData = int(data) # Parse the data and use it.
        # Do the refresh.

    ...
````
I only want to parse a Input data to the refreshCamera method.

**Comment by OmarEmaraDev** [comment]
You can't use data from inputs in drawing something, at least not before execution happens. What exactly are you trying to do?

**Comment by akaflokart** [comment]
I try to open and close a window with a button.
The window position and size needs four inputs and the object to zoom at.
So the node looks something like the following picture.


![Window](https://user-images.githubusercontent.com/41044719/94289455-0805ee00-ff59-11ea-94b5-6b22e9a9178f.PNG)

The code to open and close a window works as expected but the inputs dont works.
Or do i need a execution method just to return the float list and object and call this method inside the create_delete_func method.

**Comment by OmarEmaraDev** [comment]
Why not create the inputs as node properties so that you can access them readily?

**Comment by akaflokart** [comment]
Can you give me a small example?
If i understand you correct you mean a input field directly on the node like a button.

**Comment by OmarEmaraDev** [comment]
Yes. For instance:

```python
class CopyLocationWithOffsetNode(bpy.types.Node, AnimationNode):
    bl_idname = "ANWindow"
    bl_label = "AN Window"

    windowWidth: FloatProperty(name = "Window Width",
        description = "The width of the window",
        default = 200, soft_min = 0.0)

    def draw(self, layout):
        layout.prop(self, "width")

    def create_delete_func(self):
        # Use self.windowWidth

**Comment by akaflokart** [comment]
Thanks for the input 
your example gives a input field but it changes the node size and not the window size if i change the number in the field.


![window_01](https://user-images.githubusercontent.com/41044719/94344418-84fb9b00-001f-11eb-8171-0996ee60bfe1.PNG)

I need the value from the width input in the def create_delete_func(self) to change the window size # Use self.windowWidth seems not to work it takes all time the default value not the input.
![Window_size](https://user-images.githubusercontent.com/41044719/94344493-11a65900-0020-11eb-912d-9348374f87fa.PNG)

Code
````python
import bpy
from win32 import win32gui
from win32.lib import win32con
from ...base_types import AnimationNode
from bpy.props import *




class CopyLocationWithOffsetNode(bpy.types.Node, AnimationNode):
    bl_idname = "ANWindow"
    bl_label = "AN Window"



    windowWidth: IntProperty(name="Window Width",
                            description="The width of the window",
                            default=200, min=200, max=1980, soft_min=0)





    def draw(self, layout):
        # layout for the window size and position input
        layout.prop(self, "width")

        # layout for the button
        col = layout.column()
        row = col.row(align=True)
        row.scale_y = 1.0
        self.invokeFunction(row, "create_delete_func", text="create_delete_func")#, data = data )


    def create_delete_func(self):

        #global WindowPosSize
        hwnd = win32gui.FindWindow(None, 'Blender Render')
        if hwnd == 0:
            render = bpy.context.scene.render
            bpy.ops.render.view_show('INVOKE_DEFAULT')

            # Change area type
            area = bpy.context.window_manager.windows[-1].screen.areas[0]
            area.type = "VIEW_3D"
            area.spaces[0].overlay.show_overlays = False
            area.spaces[0].show_gizmo = False
            area.spaces[0].region_3d.view_perspective = 'ORTHO'
            area.spaces[0].shading.type = 'MATERIAL'#'RENDERED'

            hwnd = win32gui.FindWindow(None, 'Blender Render')
            win32gui.SetActiveWindow(hwnd)
            win32gui.SetWindowPos(hwnd,win32con.HWND_TOPMOST, 0, 0, 0, 0,win32con.SWP_NOMOVE | win32con.SWP_NOSIZE)

            y = self.windowWidth #Is always the default value
            x = 1000
            px = 20
            py = 20

            a = 38
            b = 9
            win32gui.MoveWindow(hwnd, px-b, py-a, x+(2*b), y+a+b, True)
            bpy.ops.screen.screen_full_area(use_hide_panels=True)

        else:
            win32gui.PostMessage(hwnd,win32con.WM_CLOSE,0,0)

````

**Comment by OmarEmaraDev** [comment]
My bad. I meant `layout.prop(self, "windowWidth")`, not `layout.prop(self, "width")`.

**Comment by akaflokart** [comment]
Thanks Omar,
i have no idea how do you know all the staff.
It works.
