### ISSUE TITLE
Animation node stop execution if a window with 'RENDER' view is active.

### ISSUE THREAD

**Issue by akaflokart** [JacquesLucke/animation_nodes#1541]
Hi,
is this a known issue that animation node stop execution if a window in 'RENDER' mode is active ?
If i switch to 'MATERIAL' or the other everything works fine.

**Comment by OmarEmaraDev** [comment]
This is not an issue, but a decision to deactivate AN during rendering. Maybe we should revisit this decision since a lot changed since then. I will get back to you later.

**Comment by OmarEmaraDev** [comment]
I don't think we will allow that. Essentially, Animation Nodes update the view layer for each execution which means if Always is enabled, the view layer will update as much as possible not giving the render engine any time to do meaningful work. i suggest you find a more suitable execution mechanism. Triggers can be useful in a lot of cases. Consult the documentation for more information.
