### ISSUE TITLE
Proposal：Add Wifi-in and Wifi-out nodes

### ISSUE THREAD

**Issue by cxdcxdcxd198** [JacquesLucke/animation_nodes#1544]
![abc](https://user-images.githubusercontent.com/51414955/94981059-adc0ea80-0561-11eb-95ad-75d001e26dbe.png)
Maybe it could not only simplify the node structure but also easy reusing data.

**Comment by harisreedhar** [comment]
@cxdcxdcxd198 It is kinda possible already:
![wifi_AN2](https://user-images.githubusercontent.com/46858047/94984589-3728ea80-056b-11eb-866b-1265e521864b.png)

**Comment by OmarEmaraDev** [comment]
I don't think we will add similar node. A better solution for such use cases should be studied.

**Comment by cxdcxdcxd198** [comment]
@harisreedhar Finaly noticed that group node could do it !
![002](https://user-images.githubusercontent.com/51414955/95068814-59239800-0738-11eb-95fe-32bea07d3e45.JPG)

**Comment by harisreedhar** [comment]
> @harisreedhar Finally noticed that group node could do it !
> ![002](https://user-images.githubusercontent.com/51414955/95068814-59239800-0738-11eb-95fe-32bea07d3e45.JPG)

Great! I thought sending data between two node trees :)
