### ISSUE TITLE
Node Tree fails to update correctly when Rendering Animation.

### ISSUE THREAD

**Issue by Mehdianim** [JacquesLucke/animation_nodes#1547]
As objects move towards/away from camera I need the outline thickness to remain the same in appearance. Outline thickness is achieved by driving the thickness value of the solidify modifier. I setup a node tree with two subprograms, one per object, to make the thickness adjust at every frame based on each objects distance to camera.

Problem: with more than one object, rendering the animation does not work. rendering 1 Image at a time using F12 works.

When I render animation using Ctrl+F12: (Movie or frame sequence makes no difference here) The node trees update (auto execution on & frame changed checked) but the animation of the objects does not update.

If I delete one of the two subprograms everything works fine but then my outline only works for one object in the scene.
It seems to have an issue with two subprograms in the same tree perhaps ? I also tried separating the two subprograms, each into their own node tree and that made no difference.

I should add that I tried baking the Node Tree to Keyframes so that it wouldn't need to worry about updating while rendering but the bake process doesn't work with my tree.

Please let me know if it is a bug, or if there is a better way to setup the node tree perhaps ?

I reproduced the issue in a very simple test file here:
https://drive.google.com/file/d/1a1rTAMD-e3w-YHKuWZ0ubgkJ2Htj-2Q_/view?usp=sharing

**Comment by OmarEmaraDev** [comment]
Which version of Animation Nodes are you using? I can't replicate the issue.
