### ISSUE TITLE
How to automate adding vertex color group

### ISSUE THREAD

**Issue by dwizor** [JacquesLucke/animation_nodes#1548]
Hello, i have a lot fractured pieces(maybe 1000) of some objects, and i want control thier vertex color by falloff in animation nodes. The only problem is i need add this vertex color group to each objects because they dont have any. Is there any way to automate it?

**Comment by Gerstmann-Bradley** [comment]
May I ask why do you need to control vertex color using falloff?
Would that be possible if you use "object color output" instead? If my guess of what you are trying to do is right.

**Comment by dwizor** [comment]
These pieces are moving in tornado fashion around world center and i want them to show only in place inside empty sphere. In this empty these pieces have to scale up from 0 to 1 and i want vertex color to switch black to white in shader to make pieces emissive while they are scaling up.

**Comment by Gerstmann-Bradley** [comment]
> These pieces are moving in tornado fashion around world center and i want them to show only in place inside empty sphere. In this empty these pieces have to scale up from 0 to 1 and i want vertex color to switch black to white in shader to make pieces emissive while they are scaling up.

You can use "object color output" instead of vertex color output.
In such a case you don't need to add anything, because each object has its object color.

**Comment by dwizor** [comment]
Yeah, it works fine in this case. Just out of curiosity, there are no way one click solution to just add empty vertex color group to each objects? It seems for pretty easy compare to animation nodes power ^^ I am asking because "object color ouput" does not take into account distance between each vertex just from origin, and because of that transition gradients of objects arent possible.

**Comment by Gerstmann-Bradley** [comment]
> Yeah, it works fine in this case. Just out of curiosity, there are no way one click solution to just add empty vertex color group to each objects? It seems for pretty easy compare to animation nodes power ^^ I am asking because "object color ouput" does not take into account distance between each vertex just from origin, and because of that transition gradients of objects arent possible.

there is actually a way to add vertex group using AN. but that method is not recommended in your case.
If you want transition gradient, I think it's also possible use "UV map output" instead object two method previously mentioned. In this case, you also don't need to add UV map.
However, resolution of transition gradient depends on the amount of your vertices. It may unavoidably slow your machine down a lot if you have lots of object each with lots of vertices.

It also reminds me "dynamic painting". It may also be a possible method (I haven't tried but I think it should be possible).
You can copy dynamic painting as "modifier" using "copy attribute add-on".
....
anyway, personally I don't know way to add vertex group to multiple object at once. It's also beyond scope of AN.
Maybe you should ask in blender community or other places.

**Comment by dwizor** [comment]
Hm can you show me any reference how to make it with UV map output technique? 
Dynamic painting sounds good but it dont uses vertex groups? Which i have to add again to all objects.

**Comment by Gerstmann-Bradley** [comment]
> Hm can you show me any reference how to make it with UV map output technique?
> Dynamic painting sounds good but it dont uses vertex groups? Which i have to add again to all objects.

ok forget about dynamic painting then.
A rough example of UV is shown. UV coordinate in this case will go between 0 and 1.
A sideeffect is its UV will be messed up. So your other type of texture shouldn't really use UV.
Regardlessly, there are essentially many types of method and possibilities. I am not going to discuss each of them in extended amount of detail.
![structure](https://user-images.githubusercontent.com/55994236/95082312-dcb59880-06e8-11eb-9f88-8e7bdedccffb.png)

**Comment by dwizor** [comment]
Yeah sure ^^ Anyway thanks for guide me to possible directions, i will take a look for this!

**Comment by harisreedhar** [comment]
This expression adds vertex color `'' if x.data.vertex_colors.get('an_vcolor') else x.data.vertex_colors.new(name = 'an_vcolor')`
![vcolor_expression](https://user-images.githubusercontent.com/46858047/95082732-1f06c600-0739-11eb-8e00-37b01056aad7.png)

**Comment by dwizor** [comment]
Ok, thanks guys for help ^^
