### ISSUE TITLE
List nodes refurbish, modifications, additions

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#155]
There are 2 sections here:
**1. node modification or addition**
[I add some patches with comments. if not ok, I can post the files.] https://github.com/og76/animation_nodes
**2. code or socket issues**
[may wanna take a look there first? however these may be for future refurbish, not immediate...]

**_1.  node modification or addition_**

1.1
[add] - **trim text**  (see #150) -  have "Allow negative Index" bool 
edit: DONE

1.2
[add] **trim list**, same as text but for lists (see patch) 
https://github.com/og76/animation_nodes/commit/0bd33b0744129c842750c7962976d9b64caba702

1.3
[mod] -Negative index, same for **get element** (see patch) 
https://github.com/og76/animation_nodes/commit/c07b69e56854d1a38b20c1fe6cabda93d418a050
For set element, not.

1.4 separate **sum elements** to:
[add] - **join text list** , just that, adding start end functionality, same negative etc
https://github.com/og76/animation_nodes/commit/10b054ca6ca08011b7cf2d987849d55da8be4003
note: create list(string)+join txt looks better than current combine txt (list has management and all)

[add] -**math list elements** with enum: sum, min ,max , avg , 
https://github.com/og76/animation_nodes/commit/8725fcaf20b56c75e1e729dddc96a705cf90a483
note: is there more to add than sum, min, max, avg? 

may *keep original Sum Elements* (hidden) for backwards compatibility
it affects #64 ? 

1.5 
[add] add **sort list elements**, like the expressions we discussed #149, with inputs:
list (list sockets) // attribute (string socket?) // reverese (bool)
testing with script node example ...  I would not do it this brute, I'll test more...
*.to be discussed, this is complicated,*

1.6 
[add] **Filter list**: there is also startswith /endswith ( pattern? not quite so, it seams to be much faster this startswith, out of my reading...) 
-very usefull for string list **Text List Filter**
TO DO ...
-object list  **Object List Filter** (may add others than object)
https://drive.google.com/file/d/0BzzAoBwXO8dsOUw5a0Vjd1pBYWM/view?usp=sharing
script node example ... very brute, but useful
object filter (also with obj type, mesh etc, and has attribute?)
TO DO ...

1.7
[add] add **map lists** . with fallof, guess is better than zip. if it has start/end, we manually limit anyway testing, long discussion, if the case

1.8
[bug] **reverse list accepts text/float etc socket** (not list) and leads to halt in execution.
https://github.com/og76/animation_nodes/commit/285683d535772b869296559bbc2779c231378033
just missing one line in sock generate :hammer: 
*but also changed it to inline exec :dizzy_face:  (you lived to see me doing that..)*

1.9
I'm also working on refactor **combine lists**, to allow more than 2, much based on the create list, with soc management and all 
TO DO soon

add more ideas...

---
**_2. code or socket issues_**

2.1
eventually, may wanna move lists to inline execution. :smile: 

2.2
socket generation is not quite ok. diggin into lists for pieces of code (my experiments) I found that list socket do not adapt well to all cases
have this example (I do this a lot)
falling on an existing link is not working well, falling on a link with debug takes the output as more important than input? hm

I was not able to change the generate sock right (inverting them etc, tried various ways), but so far, seams to me that as a general rule, 
output should be less important than input (not the case today). or 
generic sockets may not be taken into account (for output)? [if out=generic I care about input]
fwiw, convert node works better, but it has always generic input, so maybe it's not of any use

I'll digg more

2.3
add some more here...

**Comment by JacquesLucke** [comment]
thats a lot again :D
I will go over it over the next couple of days/weeks

For now I want to fix the AN key system, test a bit and merge everything into master before we do other changes

**Comment by og76** [comment]
OK. Do not postpone soc and curves for these. Or other.
They are little updates or additions. or ideas...

ps: Note that I am civilized now, I use forks...

**Comment by og76** [comment]
( *hey, no pressure, ok? little updates like trim text. So that u can deal with the hard ones..* )
**Update:**  [og76-lists](https://github.com/og76/animation_nodes)
 1. small changes for nodes above, had little mistakes. :( But now they work. :D
 2. mod **Combine lists** to behave like create list (many sockets, all types etc)

**summary, till now:**
mod
[mn_get_list_element.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_get_list_element.py) -negative index
[mn_reverse_list.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_reverse_list.py) -bug, missing a line in socket gen, also moved to inline execution
[mn_combine_lists.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_combine_lists.py) -heavy copy from create list (commented inside), works for any list type, n inputs, ..

new 
[mn_trim_list.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_trim_list.py) -like text trim but for lists, heavy copy from text trim
[mn_join_text_list.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/text/mn_join_text_list.py) -instead of sum elements(txt), with create list may use instead combine txt
[mn_math_list_elements.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/number/mn_math_list_elements.py) -instead of sum elements(float) /sum/mult/avg/min/max/ with create list is better than multi math
(the two replace sum elements and better, but I left sum elements same)

fwiw, adding the new nodes above to the menu [insert_nodes_menu.py](https://github.com/og76/animation_nodes/blob/og76-lists/insert_nodes_menu.py)

ps
*For those that care to test, the top link is the socket branch copy + these additions/modifications
may install in full
Or just get the zip and add/replace the above nodes: join is in text, list math in float, rest in lists (may replace also insert nodes menu with the above)*

**Comment by og76** [comment]
And some eye candy
![lists1](https://cloud.githubusercontent.com/assets/11709974/8197117/97431ab4-149c-11e5-8341-b8e802851b15.PNG)

**Comment by og76** [comment]
just added get element index node https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_get_list_element_index.py
search a list and return index/indices of all occurrences and occurrences number
+modified the menu respectively

**Comment by og76** [comment]
**summary, till now:**
mod
[mn_get_list_element.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_get_list_element.py) -negative index
[mn_reverse_list.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_reverse_list.py) -bug, missing a line in socket gen, also moved to inline execution
[mn_combine_lists.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_combine_lists.py) -heavy copy from create list (commented inside), works for any list type, n inputs, ..

new 
[ mn_get_list_element_index.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_get_list_element_index.py) -get indices of element in list and nr of occurrences
[mn_trim_list.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/list/mn_trim_list.py) -like text trim but for lists, heavy copy from text trim
[mn_join_text_list.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/text/mn_join_text_list.py) -instead of sum elements(txt), with create list may use instead combine txt
[mn_math_list_elements.py](https://github.com/og76/animation_nodes/blob/og76-lists/nodes/number/mn_math_list_elements.py) -instead of sum elements(float) /sum/mult/avg/min/max/ with create list is better than multi math
(the two replace sum elements and better, but I left sum elements same)

fwiw, adding the new nodes above to the menu [insert_nodes_menu.py](https://github.com/og76/animation_nodes/blob/og76-lists/insert_nodes_menu.py)
