### ISSUE TITLE
Shuffling Nested List Propagating Backwards

### ISSUE THREAD

**Issue by scottdmilner** [JacquesLucke/animation_nodes#1561]
Hello! If I shuffle a list of lists, then the list further back in the NodeTree gets shuffled too, which can lead to undesirable results. Is it possible to add a **Deep Copy** option in the advanced settings of the *Shuffle* node? Thank you!

Example (unwanted behavior on top, desired behavior on bottom):

![an-bug-vid](https://user-images.githubusercontent.com/16693178/96067702-f6c94680-0e5f-11eb-9c65-d15dc22d305f.gif)

**Comment by harisreedhar** [comment]
Try this:

![listCopy](https://user-images.githubusercontent.com/46858047/96076523-26616880-0ecb-11eb-834a-08a2b0e2e646.png)

**Comment by OmarEmaraDev** [comment]
The Shuffle list does Deep Copy as needed indeed. The problem here is that Animation Nodes can not copy a generic list. So for generic lists, copying is your responsibility. as @harisreedhar outlined above.

**Comment by scottdmilner** [comment]
Thanks for the fast response! That makes sense, though it's not very intuitive. At least for me, it took a solid 20 minutes of debugging before I figured out what was going on. 

Could some sort of alert or warning be added to the Shuffle node when its type is switched to *Generic*?

**Comment by OmarEmaraDev** [comment]
What do you want the warning to say?

**Comment by OmarEmaraDev** [comment]
Essentially, if we add a warning, we will have to add it to all nodes that accepts generic lists, which are a lot. So I don't think this is reasonable. I would say your generic lists are your responsibility, copy them explicitly as needed.

**Comment by scottdmilner** [comment]
Oops, this slipped through my inbox earlier. 

Ok, that makes sense. Could you add a line in the [documentation](https://docs.animation-nodes.com/documentation/introduction/data/#generic-data-type) that says something like this?

> Generic lists will not be automatically copied by Animation Nodes when using nodes that make modifications to the list. If you plan on using a Generic list output in multiple places, make sure that you manually copy lists as needed.

**Comment by OmarEmaraDev** [comment]
Done. Thanks for the feedback!

**Comment by scottdmilner** [comment]
Great! Thank you! :-)
