### ISSUE TITLE
"Separate Polygons" doesn't work on blender 2.90

### ISSUE THREAD

**Issue by LupoMarcio** [JacquesLucke/animation_nodes#1562]
There's something wrong in the "separate polygons", I was trying the "vector wiggle" example on the site with a project, at first I thought it was my fault,  I tryed with a simple cube, but it just messes with the vertex order or something.
![blender_wHP05zdIJz](https://user-images.githubusercontent.com/72905040/96079901-36228200-0eb6-11eb-91ee-0fc9f576f30f.png)
AFAIK I think that there's something about edges that need to be processed with the separate polygons node, since the combine mesh is not capable of creating edge indices by itself.
Maybe there's some missing information in the site because is not updated to the new nodes and yes this is blender 2.90, but I wanted to let the developer know.

**Comment by OmarEmaraDev** [comment]
Things changed in the new version. The Combine node will no longer create edges on its own. You have to compute those edges yourself. Try connecting the polygon indices output to the edge indices input, Animation Nodes will insert a node automatically for you.

**Comment by LupoMarcio** [comment]
I tryied that too but it doesn't do that, at least, I don't know if I'm doing it wrong. I did it by hand to make it work, this is only for an object of 51 verts, but when there's more? I would like to automate this.
![immagine](https://user-images.githubusercontent.com/72905040/96112529-0dfd4800-0ee3-11eb-9484-6c54b0ea530e.png)

**Comment by Gerstmann-Bradley** [comment]
> I tryied that too but it doesn't do that, at least, I don't know if I'm doing it wrong. I did it by hand to make it work, this is only for an object of 51 verts, but when there's more? I would like to automate this.
> ![immagine](https://user-images.githubusercontent.com/72905040/96112529-0dfd4800-0ee3-11eb-9484-6c54b0ea530e.png)

I have tested it, what Omar said should work.
Please make sure you keep your animation nodes version up to date.
Also, even if the automated linkage didn't work when you link "polygon indicies" to "edge indicies" of combine mesh node.
You can still use "Edges of Polygons" node instead, whether it's a manual addition or not.
![example](https://user-images.githubusercontent.com/55994236/96113896-d2e32080-0eb2-11eb-835f-8059e5bf7865.png)

**Comment by LupoMarcio** [comment]
I downloaded the latest yesterday, I think is updated..?
I don't know, I restarted blender and it works now.
Thank you very much for the suggestions Omar and Gerstmann-Bradley, it's surely better now.
