### ISSUE TITLE
Undo afer text separation crashes Blender

### ISSUE THREAD

**Issue by hitrpr** [JacquesLucke/animation_nodes#1563]
Create new file, 
create text,
create «separate text»  node and pick text object to it
Press «Update», 
Press Ctrl+Z
Crash.

LTS and newest versions do the same.

**Comment by OmarEmaraDev** [comment]
I can replicate that. Probably a Blender bug. I will try to reproduce and report.

**Comment by OmarEmaraDev** [comment]
Fixed in 5377dd6.
