### ISSUE TITLE
Expression node have problems with brackets

### ISSUE THREAD

**Issue by hitrpr** [JacquesLucke/animation_nodes#1564]
![54310540](https://user-images.githubusercontent.com/21099918/96196801-05475900-0f59-11eb-8cb9-784c33a92c98.png)
![54325840](https://user-images.githubusercontent.com/21099918/96196821-13957500-0f59-11eb-885c-0f0885ee8d14.png)

As you can see, expression returns 0, when I use brackets.
s is vector3 [1,1,1]
i is int, iterator, index of Loop

**Comment by harisreedhar** [comment]
It is showing correct result i think. `Viewer` node only shows result of last iteration. Use `Loop Viewer` to see result of every iteration.

**Comment by hitrpr** [comment]
@harisreedhar nope. sx=s.y=s.z , so they should be equal in the output.
s go to expression at once as parameter, not as iterator.

**Comment by harisreedhar** [comment]
> @harisreedhar nope. sx=s.y=s.z , so they should be equal in the output.
> s go to expression at once as parameter, not as iterator.

Please check precedence of operators in your expression.
![operatoe_precidance](https://user-images.githubusercontent.com/46858047/96328256-7de40d80-105e-11eb-98cf-f5cdcb89a015.png)

* s[0]-(i+1)/5 => 1 - (4 + 1) / 5 = 1 - 5 / 5 = 0
* s[1]-i/5+1/5 => 1 - 4/5 + 1/5 = 1 - 0.8 + 0.2 = 0.4

**Comment by OmarEmaraDev** [comment]
Results seem to be corrected as @harisreedhar pointed out.
