### ISSUE TITLE
How can I find what field type is being used in a node

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1566]
How can I find what field type is being used in a node:

Example:  I know this field type is a generic list but how can I verify what field type is actually being used for other fields?

![image](https://user-images.githubusercontent.com/28985314/96328474-7fd3af80-1011-11eb-9783-067f15d77c86.png)

**Comment by OmarEmaraDev** [comment]
By field, you mean socket?

**Comment by stillpointx** [comment]
Yes I believe so.

**Comment by OmarEmaraDev** [comment]
Socket colors are used to identify their types. We don't display the type anywhere else. Unless you want to use Python.

**Comment by stillpointx** [comment]
Thanks.  Might I suggest adding an option maybe to the Properties section of the node that would show the socket type used.

**Comment by OmarEmaraDev** [comment]
I don't think it is worth it. I think users should just memorize the colors of the sockets. Color-based identification worked rather well for users, so it probably doesn't need more hints.
