### ISSUE TITLE
Exported FBX has no animations. URGENT

### ISSUE THREAD

**Issue by marcusx2** [JacquesLucke/animation_nodes#1567]
[animatedString.zip](https://github.com/JacquesLucke/animation_nodes/files/5395051/animatedString.zip)
I can not, for the life of me, export this .blend file to fbx with the animation. I used the Bake to Keyframes option, it has the keyframes, it has the action. But it's not exported. I mean, the fbx is exported but when you import it, the animation is not there. I'm using blender 2.83.4, downloaded animation nodes _v2.1 for Blender 2.83 LTS_

I was following [this tutorial](https://www.youtube.com/watch?v=Q4H96RYwIls) to make animated strings

I'm not sure if this is a blender bug or animation nodes bug....but since I never had a problem to export an animation before, I'm hoping it's an easy fix on animation nodes' side. Or something stupid that I'm missing.

This is kinda really urgent...I'd appreciate it a lot if someone could help me quick...if not I understand though, everyone's busy...

**Comment by marcusx2** [comment]
It looks like this when I save
![image](https://user-images.githubusercontent.com/5656275/96329858-13fc4180-1027-11eb-87dc-8deb7b1bd57b.png)
But when I import...
![image](https://user-images.githubusercontent.com/5656275/96329869-3aba7800-1027-11eb-97d5-5d3c56091096.png)
The export options...
![image](https://user-images.githubusercontent.com/5656275/96329885-5cb3fa80-1027-11eb-9ae3-d32b9b271b45.png)

**Comment by marcusx2** [comment]
Not an issue with animation nodes. It seems blender can't convert animated curves to animated meshes. Then what is the fucking point of having animated curves if I can't convert them to any usable 3D format??? Fuck!

**Comment by Gerstmann-Bradley** [comment]
Any specific reason to adhere to FBX? Is that acceptable for you to export OBJ sequence instead?

**Comment by marcusx2** [comment]
I need a single 3D format with the animation. But I didn't know about the OBJ sequence. This worked. If I can somehow convert it to a FBX or whatever.
