### ISSUE TITLE
This bug keeps appear when I try to undo 

### ISSUE THREAD

**Issue by Manubt1993** [JacquesLucke/animation_nodes#1569]
I added a collection node , then connect it to an output matrix node and then tried to use an offset but then i pressed ctrl z to undo and it got broken, it doesn't work anymore and the only way to resolve it is to close blender and start again 

![problem](https://user-images.githubusercontent.com/73073635/96374747-4750e480-117d-11eb-8df8-f6960ac3630a.JPG)

**Comment by OmarEmaraDev** [comment]
I can't replicate this. Can you describe the things you did in order? Also, when the error occurs, can you open the console and attach the output here?

**Comment by Manubt1993** [comment]
I'm not sure, but this is what it says in the console 
![console](https://user-images.githubusercontent.com/73073635/96586263-6cfafc80-12e9-11eb-8b28-5ff82c38ca3d.JPG)

**Comment by Manubt1993** [comment]
Ok, i installed blender 2.90.1 and apparently it does not give that error anymore

**Comment by OmarEmaraDev** [comment]
Ok. I guess it was just a bad installation.
