### ISSUE TITLE
Mesh Object Output node sets Material Indices to 0

### ISSUE THREAD

**Issue by Takuyax** [JacquesLucke/animation_nodes#1570]
When using a mesh object output node, all material indices end up being 0.
I'm running Kubuntu 18.04 and the problem could be reproduced in Blender 2.83.5 and 2.90.1.
![Screenshot_20201019_220110](https://user-images.githubusercontent.com/39657731/96508943-9f5e1880-125b-11eb-8744-7779172ee666.png)
Steps to reproduce:
1. Create a mesh object with multiple assigned materials.
2. Create a node tree like in the screenshot to duplicate the mesh object, it's material list and it's material indices.
3. Observe that all faces of the duplicate have material index 0 assigned.

**Comment by OmarEmaraDev** [comment]
You are using an out-dated Animation Nodes version. Material indices are now part of the mesh structure and can be set in the combine node or using the Set Object Material Indices.

**Comment by gerroon** [comment]
@OmarEmaraDev 

Can you please show an example for each method of copying those indices and materials please when you have time? I am using this method for materials but hit an issue that I filed a bug report about it. 

thanks

**Comment by OmarEmaraDev** [comment]
@gerroon In your case, just use the Set Polygon Material Index node: 

![20201026-090616](https://user-images.githubusercontent.com/25300994/97142809-0e5ed400-176a-11eb-8233-d9124a869a9c.png)
