### ISSUE TITLE
Is it possible to call animation nodes from code as functions, not nodes?

### ISSUE THREAD

**Issue by MoamenAbdelsattar** [JacquesLucke/animation_nodes#1572]
I want to call the nodes functions from python scripts, not visually through nodes. The node receive arguments as input, and gives a list as output, making animation nodes act like blender-related python library, is that possible?

**Comment by OmarEmaraDev** [comment]
While we don't support that as an Animation Nodes solution, it is technically possible. As an example, consider the following simple group network:

![20201024-121343](https://user-images.githubusercontent.com/25300994/97079148-efd5cd00-15f1-11eb-8418-148e60087f01.png)

We can get the Animation Nodes generated function code for this group by getting the execution unit of the network and calling `getCodes` on it. Then we can execute that execution code in the current scope using `exec()`. After doing that, we will have a function called `main` that accepts the same number of arguments as the group input node and have the same number of outputs as the group output node.

```python
import bpy
import animation_nodes

network = bpy.data.node_groups['NodeTree'].nodes['Group Input'].network
executionUnit = animation_nodes.execution.units.getExecutionUnitByNetwork(network)
executionCode = executionUnit.getCodes()
exec("".join(executionCode))

print(main(1, 2)) # Will print 3.
```

Now,  lets take a look at the output code and note a number of things:

```python
import bpy, sys, math
import itertools
from time import perf_counter as getCurrentTime
from mathutils import Vector, Matrix, Quaternion, Euler
AN = animation_nodes = sys.modules.get('animation_nodes')
from animation_nodes.data_structures import *
from animation_nodes import algorithms
nodes = bpy.data.node_groups['NodeTree'].nodes
_k7kuqrvmy721zsb = nodes['Group Input']
_929yes0j6yj39pb = nodes['Float Math']
_4h8in6jp57ae8ek = nodes['Group Output']
__socket_False_1_4h8 = None

def main(group_input_0, group_input_1):
    _result_9292 = group_input_0 * group_input_1
    return _result_9292
```

- The execution code will most certainly depend on structures and functions defined by Animation Nodes. So the `animation_nodes` module has to be available. The execution code will include the appropriate import statements, so you don't have to worry about that. In our case, the node tree is sufficiently simple that no Animation Nodes structures or functions are used.
- Node input sockets that are not connected to anything will be referenced in the code as global variables whose values are initialized by calling the `getValue()` method of the target socket. In this case, we don't have any constants, so no global variables are defined. Had we not connected the second socket of the math node, the first line of the function would be  `_result_9292 = group_input_0 * _b_9291` and `_b_9291` would be defined globally as `_b_9291 = _929yes0j6yj39pb.inputs[1].getValue()`.
- The function name will always be `main`, so you should take that into consideration.

**Comment by MoamenAbdelsattar** [comment]
Thanks!
