### ISSUE TITLE
Material copying inside a loop causes hard crashes at high poly counts during render

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/animation_nodes#1573]
Hi

I need to copy materials from some objects to objects created by the instance node. It seems like this idea works when the poly 
counts are lower. When the number of polygons passes some limit it causes hard Blender crash during render.

If you put the repeat list number to low number like 10 (or remove the material input/out nodes form the loop), then you wont get any crash.

You can test this with the attached scene (just load and press f12) . Also please see the attached crash log.

https://bin.privacytools.io/?69ce2d4b3a20a5a2#1PkqYHD4EJdFbjdKMg+7npLEgJmxa5g7xdLzht1W0SY=

It would be nice if someone knows another way to copy materials to instances properly, I was done with my project if I did not hit this bug :( 

Windows 10 x64, Blender 2.90.1, AN 2.2.0

![blender_oSutmZZCGx](https://user-images.githubusercontent.com/8519469/97129362-b04fd380-170c-11eb-8c06-4719e19bb588.jpg)

[an_material_loop_crash_25102020_2112_25.zip](https://github.com/JacquesLucke/animation_nodes/files/5436520/an_material_loop_crash_25102020_2112_25.zip)

**Comment by OmarEmaraDev** [comment]
Can you try enabling the Lock Interface option before rendering and see if that works?

**Comment by gerroon** [comment]
Hi,

Where can I find that option?

**Comment by OmarEmaraDev** [comment]
Top Bar -> Render -> Lock Interface

**Comment by gerroon** [comment]
Hi

Thanks for the reply. Yes that time it does not crash in my actual project, however that seems to  render "Use  Modifiers" (which passes the modified pose mesh data to the instance) useless, which is weird. All the instances  (which gets data from Mesh Onject Input to Mesh Object output) are  rendered without armature deformations (which the original sources have).

I can see the pose mesh data applied to the instances in the loop in the 3d viewport but not in render now.


Is this a separate issue or part of the lock interface?

**Comment by OmarEmaraDev** [comment]
So it is probably as I expected. Unfortunately, this is a Blender limitation. We can't update the scene and draw the interface at the same time, hence why we need to lock the interface. This is a known limitation and we do not consider it a bug.
