### ISSUE TITLE
How to execute the tree without hitting the wrong context  issue?

### ISSUE THREAD

**Issue by kursad-zumolabs** [JacquesLucke/animation_nodes#1577]
Hi

I am trying to run AN inside a headless environment but we are hitting an issue with context.

```
 File "/bin/2.91/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)

RuntimeError: Operator bpy.ops.an.execute_tree.poll() failed, context is incorrect
  In call to configurable 'run' (<function run at 0x7f24c046bef0>)

```

This is the calling line pretty much. We need to update the node tree at will after changing the intended seed value

```
   bpy.data.node_groups["nodeA"].nodes["Viewport Input"].outputs[2].value = random.randint(
        0, 250)

    bpy.ops.an.execute_tree(name="nodeA")
    
    bpy.data.node_groups["nodeA"].autoExecution.enabled = False

```

**Comment by OmarEmaraDev** [comment]
The poll function of the node tree execution is essentially checking for "problems", there are many types of problems that can happen, I am not sure which one is causing this to fail. Can you try printing this before executing the node tree?

```
print(animation_nodes.problems.currentProblems)
```

Also, can you send a minimal file that reproduces the issue?

**Comment by kursad-zumolabs** [comment]
Hi

That did not seem to produce any tangible lead.

```
[<animation_nodes.problems.InvalidSyntax object at 0x7f8821128310>]

```

I was able to resolve it by overriding context. It is still curious that it worked locally but not in the headless.

**Comment by OmarEmaraDev** [comment]
I am pretty sure an InvalidSyntax problem would print its error before it is reported. Are you sure there is nothing in the terminal aside from the error you posted above?
