### ISSUE TITLE
Offset loose parts of mesh

### ISSUE THREAD

**Issue by dwizor** [JacquesLucke/animation_nodes#1578]
Hello, is there in AN option to offset only loose parts of mesh? I'm looking for something that should work similar to offset polygons but on loose parts of the mesh. I made exaggerate example what make no sens but just to illustrate problem:
![loose_parts](https://user-images.githubusercontent.com/68112419/98239666-957d2a80-1f68-11eb-879b-7b5b956cba44.png)
In this case i still want to control whole hexagonals not polygons from which it is made.

**Comment by OmarEmaraDev** [comment]
Would a node that splits the mesh into loose parts be a good solution to this?

**Comment by dwizor** [comment]
Yeah, its definitely is the solution but as i noticed, blender/animation nodes are faster when stuff is just in one mesh. Controlling loose parts would work well, for example, in the case of fractured object in one mesh.

**Comment by dwizor** [comment]
Btw is there already a node which splits the mesh into loose?

**Comment by OmarEmaraDev** [comment]
No, but it has been requested before in #1276. If it will be useful in your use case and others, I might prioritize it and implement this node soon.

I think we should be able to make it efficient, so performance shouldn't be a problem.

**Comment by dwizor** [comment]
Nice, that should by great! Thanks ^^

**Comment by dapa5900** [comment]
+1 for the fractured object in one mesh!
