### ISSUE TITLE
L-Systems Documentation

### ISSUE THREAD

**Issue by gogobd** [JacquesLucke/animation_nodes#1579]
L-Systems could use some more documentatin (couldn't find much on readthedocs); at least this would be noteworthy:

A, B, X, Y, Z: Variables
F: moveForward_Geo
f: moveForward_NoGeo
[: branchStart
]: branchEnd
": scaleStepSize
!: scaleWidth
+: rotateRight
-: rotateLeft
&: pitchUp
^: pitchDown
\: rollClockwise
/: rollCounterClockwise
~: rotateRandom
T: applyTropism
J: storeTurtleState
K: storeTurtleState
M: storeTurtleState

**Comment by OmarEmaraDev** [comment]
We moved the documentation to `docs.animation-nodes.com`. I guess we didn't remove the old one, we should probably do that. Sorry for the inconvenience.

The L-System is documented here:
https://docs.animation-nodes.com/documentation/nodes/text/lsystem/

**Comment by Gerstmann-Bradley** [comment]
> We moved the documentation to `docs.animation-nodes.com`. I guess we didn't remove the old one, we should probably do that. Sorry for the inconvenience.
> 
> The L-System is documented here:
> https://docs.animation-nodes.com/documentation/nodes/text/lsystem/

Just to mention that old manual provides GIF examples which are every educational. But the new documentation does this nowhere. It's ok to delete the old manual, but examples should be retained/updated in the new documentation,

**Comment by gogobd** [comment]
This is perfect! Thanks for the quick response!

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley See the last section in https://github.com/JacquesLucke/animation_nodes_manual/issues/80. I am still not sure on what is the best way to populate the examples. Your suggestions are welcome.
