### ISSUE TITLE
How to execute a subprogram without repeating imports?

### ISSUE THREAD

**Issue by CustomLenny** [JacquesLucke/animation_nodes#1580]
I've spent a lot of time trying to find the answer to these two questions below and haven't had any success. The first probably being more important than the second but both a very similar problem.

1. When executing a subprogram python script in animation nodes that has an import library (and more specifically that import library requires an initialisation call) it imports and inits every loop which results in two problems, first being that it slows everything down, the second being that it never actually finishes initialising enough to get the accurate result of the libraries function. How does one start an external library and initialise it once for the animation nodes subprogram to use the functions in it?

2. In a similar sort of sense, how does one keep a value between calls to a subprogram. That is if I have the line of code: a+=1. How do I have it so that each time the subprogram is called from animation nodes (whether it be from any method of auto execution or not) the value of a will increment by 1? (Following on from that, if this is even possible, how would one completely reset it back to the beginning).

I'd very much appreciate an answer to both questions separately if possible (rather than a merged answer), thank-you in advance.

**Comment by OmarEmaraDev** [comment]
1. I added a Modules option in the script node to get around this issue. It will now only be imported at setup. e99d6ab
2. See my answer here. https://blender.stackexchange.com/a/105178

**Comment by OmarEmaraDev** [comment]
For your first problem, do you call the initialization routine yourself, or is it called upon importing the library?

**Comment by OmarEmaraDev** [comment]
Can you share the code snippet you are talking about?

**Comment by CustomLenny** [comment]
To the first issue, I'm unsure what happened but at some point the code sped up by an incredible amount and I can't even see what I added or removed.

The second part seems very convoluted and probably won't even help with what I want to do in the end. The example also used current frame number to calculate when I specifically want something live.

Ultimately I just want to open a device input (linux) via "open('dev/input/event', 'rb')".
However a way to easily list global values outside of the script so they don't redefine themselves every time would seem convenient regardless of the fact that computers nowadays can more than handle an extra string definition every loop.

**Comment by OmarEmaraDev** [comment]
@CustomLenny You can pass those global values to the loop and then the script invoke node using a generic socket. So you should have two scripts, one to do the one-time initialization, and one that is actually called in the loop. The initialization script should pass the global variables to the script through means of generic sockets.

**Comment by CustomLenny** [comment]
I still cannot understand how to do the one-time initialization, and specifically for 'auto execution' set to 'always'.

**Comment by OmarEmaraDev** [comment]
@CustomLenny If you are asking how to do a one-time initialization across different executions, you can't. Unless you store the initialized data somewhere as I described in the answer I linked before.
