### ISSUE TITLE
Object visibility output crashes whith large amount of objects

### ISSUE THREAD

**Issue by Dihotom** [JacquesLucke/animation_nodes#1582]
I have a collection with 200 objects set to turn visibility. When I hit render it instantly crashes blender. However it can be rendered with command line or "b-renderon!".
Collections with smaller amount of objects don't crash blender.

[crash.zip](https://github.com/JacquesLucke/animation_nodes/files/5510279/crash.zip)

**Comment by OmarEmaraDev** [comment]
Unfortunately, this is a known issue in Blender. The only solution is to enable Lock Interface before rendering.
![](https://i.stack.imgur.com/NL6iX.jpg)
