### ISSUE TITLE
Is There any Way to Access ScriptNode's Name and RNA From Inside of Script Node?

### ISSUE THREAD

**Issue by AmitraksharBiszz** [JacquesLucke/animation_nodes#1584]
I am trynna create a Node in Animation Nodes, Which Can be used to Create Object....(Based on the **Script's RNA and Name**) But I was thinking What if I can do that With Script node instead of making an Actual Registered Node....

**Comment by OmarEmaraDev** [comment]
Not sure I understand what you want to do. Do you want to get the name of the Script Subprogram node that references the script you are writing? Why would you want that?

**Comment by AmitraksharBiszz** [comment]
Yes, You got it Right.... I am Trying to Create Object with script where User Doesn't "HAVE TO" Define a Name of it, Which Can be done by taking the **InvokeSubprogram's Name** [As They would already be Unique].... But Can't seem to Get the InvokeSubProgramsName accessible from within the Script. 

> _Or we could Generate Random Names for Making Objects.... which we wouldn't be able to Stop from getting executed Over and Over again as animation nodes NodeTree is Executed Multiple Times unless we had for eg: taken RNA of the InvokeNode and Object and Saved that Data Somehow, maybe in a DICT_

**That's Why I thought About RNA**

But, if we use InvokeSubprograms's Name and don't use the RNA, if the we change the Name of that Object later, That Would be a Problem too

**Comment by OmarEmaraDev** [comment]
I don't think it is possible to get the name of the invoke node, at least not readily. And we probably won't add an option to allow that. The best thing you can do is use the Object Instancer node to create the objects then fill them with data in the script node, passing the object as an input.

**Comment by AmitraksharBiszz** [comment]
I just Found out, If I untick "Copy from Source" Object Instancer creates Objects... that's Good and All I needed. Thank you....
