### ISSUE TITLE
animation node render crash

### ISSUE THREAD

**Issue by shadowcreeper-hash** [JacquesLucke/animation_nodes#1585]
Why do I crash when I render in blender 2.901
but It works in view mode
There should be no problem with my node
The render crashed at about 170 frames
![Blender_  C__blender_tail blend  2020_11_15 3_54_10](https://user-images.githubusercontent.com/65867725/99197431-70d94c00-27cd-11eb-9f5d-9833fd7ef0a9.png)
[tail.zip](https://github.com/JacquesLucke/animation_nodes/files/5543165/tail.zip)

**Comment by Gerstmann-Bradley** [comment]
Always try to lock interface before rendering. Hope it works
![interface](https://user-images.githubusercontent.com/55994236/99197567-579ab600-2761-11eb-831d-212a56bfa9a5.png)

**Comment by shadowcreeper-hash** [comment]
That's it. Thank you very much
This is the trailing effect video That I made
[tail.zip](https://github.com/JacquesLucke/animation_nodes/files/5543245/tail.zip)

**Comment by shadowcreeper-hash** [comment]
In the next version I want to turn on this lock view automatically when rendering

**Comment by OmarEmaraDev** [comment]
Nice work @shadowcreeper-hash!
I want to find a way to enable it automatically, just haven't found a good way to do that yet.
