### ISSUE TITLE
Why is the coordinate data of the particles different

### ISSUE THREAD

**Issue by shadowcreeper-hash** [JacquesLucke/animation_nodes#1586]
I wanted to create a sphere where the particle disappeared, 
no problem in the view, 
but when I rendered the coordinates where the particle disappeared went to the place of birth

How to solve this problem

![Blender 2020_11_16 17_11_39](https://user-images.githubusercontent.com/65867725/99233915-d14ca580-282e-11eb-8fdb-b6c080fdefca.png)
![Blender 2020_11_16 17_03_36](https://user-images.githubusercontent.com/65867725/99233921-d3aeff80-282e-11eb-85e6-422d02530c29.png)
![Blender 2020_11_16 16_56_22](https://user-images.githubusercontent.com/65867725/99233929-d6115980-282e-11eb-941a-9661e614fd17.png)

**Comment by OmarEmaraDev** [comment]
Can you share that file?

**Comment by shadowcreeper-hash** [comment]
ok

**Comment by shadowcreeper-hash** [comment]
this 
[Uploading partical.zip…]()

**Comment by shadowcreeper-hash** [comment]
> 你能分享那个文件吗？
https://github.com/JacquesLucke/animation_nodes/issues/1586

**Comment by OmarEmaraDev** [comment]
@shadowcreeper-hash Seems like the file wasn't uploaded properly, I can download it. Can you check that?
