### ISSUE TITLE
How to cimport numpy?

### ISSUE THREAD

**Issue by harisreedhar** [JacquesLucke/animation_nodes#1587]
when i try to cimport numpy. it creates compiler error: `fatal error: numpy/arrayobject.h: No such file or directory`.

**Comment by OmarEmaraDev** [comment]
That's because we don't include the numpy headers during compilation. We depend on numpy at runtime, not at compile time, and we don't want to add a compile dependency unless there is a good reason to do so. Why do you want to cimport numpy?

**Comment by harisreedhar** [comment]
i was just learning some numpy functions related to c. how can i add headers to setup file?

**Comment by harisreedhar** [comment]
i found an answer on stackoverflow:
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
import numpy as np

ext  =  [Extension( "cy_test", sources=["cy_test.pyx"] )]

setup(
   name = "testing", 
   cmdclass={'build_ext' : build_ext}, 
   include_dirs = [np.get_include()],   
   ext_modules=ext
   )
```
but it is only good for .pyx single file. i don't understand AN setup file. can you point me where i can add the path in AN.

**Comment by OmarEmaraDev** [comment]
I can't test this right now, but adding the following line:
```python
includeDirs.append(numpy.get_include())
```
After the following line:
https://github.com/JacquesLucke/animation_nodes/blob/master/_setuputils/compilation.py#L21
Should work. Let me know if it does.

**Comment by harisreedhar** [comment]
@OmarEmaraDev Yess it works :100:  . Compiled successfully. thanks a lot.
