### ISSUE TITLE
Object ID key no animation rendered anymore

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1588]
Since Blender 2.83, Object ID key does not render animation  anymore. The below worked well before but now it did not output animation but only the last screenspot in the animation all the time. It did not change for each frame.
![ancollection001](https://user-images.githubusercontent.com/31892214/99514169-69c95e00-29c6-11eb-9781-faa328be5c43.png)

**Comment by OmarEmaraDev** [comment]
What do you mean by "does not render animation"? It works in the viewport but doesn't work during rendering? What value does it return while rendering?

**Comment by OmarEmaraDev** [comment]
Seems to be working fine on 2.92 Alpha with latest AN. Can you share that blend file?
