### ISSUE TITLE
Performance issue: any added animation node increases CPU usage up to 100%

### ISSUE THREAD

**Issue by ProgrammingLife** [JacquesLucke/animation_nodes#1592]
Is there any workaround to solve it?
I can't even mute those nodes for a time while I don't need to play an animation. Only to delete all the animation nodes.

Thanks a lot for such useful plugin!

**Comment by Gerstmann-Bradley** [comment]
what's your runtime shown on the left upper corner (yellow box)?
Have you untick the "always" in the N-panel as shown in the red box?
![example](https://user-images.githubusercontent.com/55994236/99891250-d4340580-2c35-11eb-941c-f289cc37abf6.png)

**Comment by ProgrammingLife** [comment]
@Gerstmann-Bradley Wow, that worked! I've just unchecked "Always" and that worked like a charm!
Thank you!
