### ISSUE TITLE
Keyframe Auto Execution not working

### ISSUE THREAD

**Issue by joulf** [JacquesLucke/animation_nodes#1593]
Trying to keyframe Auto Execution, or any of the Toggles for Execution, seems to be broken.

It is possible to insert keyframes but they dont seem to get "saved", it stays on the wichever value you toggled last.
Strangely I found a workaround that gets it to work properly. Setting the Auto Execution toggle as driver - not driven - for some toggle like Hide in Render on an object makes the keyframes work.
![grafik](https://user-images.githubusercontent.com/50253007/100258941-eb316b00-2f47-11eb-9899-3b4e5dca1a0a.png)

**Comment by OmarEmaraDev** [comment]
This is a Blender limitation as far as I know. So unfortunately, there isn't much we can do here. But thanks for the report!
