### ISSUE TITLE
New build doesn't seem to work with Ubuntu 20.04 and Blender 2.91.0 at the moment

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#1595]
![screenshot-2020-11-25-23-22-41](https://user-images.githubusercontent.com/28985314/100308365-34001880-2f76-11eb-94b0-c87270ed85cc.png)

Traceback (most recent call last):
  File "/home/rt/.config/blender/2.91/scripts/addons/animation_nodes/__init__.py", line 140, in <module>
    try: from . import test_compile
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/snap/blender/51/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/rt/.config/blender/2.91/scripts/addons/animation_nodes/__init__.py", line 158, in <module>
    raise Exception(message)
Exception: 

This build does not work at the moment.
  1. Check if the build you downloaded has been compiled for the OS
     you are using. If not, download another one.
  2. If you are on windows you can try to install a library called
     'vc_redist.x64'. Should be easy to find using your search engine
     of choice.
  3. Try to use an official Blender release downloaded from blender.org.
  4. It is possible that you have a build for the correct platform
     but it still does not work. We experienced this mainly on linux.
     Try to find another build for your platform.
     If it still does not work, you have to compile AN yourself.
  5. Make a bug report on Github and give as much information
     as you can. Specifically the full error message, your OS, version, ...

=====================================
= Blender 2.91.0 System Information =
=====================================

Blender:
=====================================

version: 2.91.0, branch: master, commit date: 2020-11-25 08:34, hash: 0f45cab862b8, type: Release
build date: 2020-11-25, 08:51:08
platform: Linux
binary path: '/snap/blender/51/blender'
build cflags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5  -fuse-ld=gold -std=gnu11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2 -D_GLIBCXX_USE_CXX11_ABI=0
build cxxflags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5  -fuse-ld=gold -std=c++17   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2 -D_GLIBCXX_USE_CXX11_ABI=0
build linkflags:  -Wl,--version-script='/home/sources/buildbot-worker-linux_centos7/linux_291/blender.git/source/creator/blender.map'
build system: CMake

Python:
=====================================

version: 3.7.7 (default, Jul  9 2020, 12:52:49)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
file system encoding: utf-8:surrogateescape
paths:
	'/snap/blender/51/2.91/scripts/startup'
	'/snap/blender/51/2.91/scripts/modules'
	'/snap/blender/51/2.91/python/lib/python37.zip'
	'/snap/blender/51/2.91/python/lib/python3.7'
	'/snap/blender/51/2.91/python/lib/python3.7/lib-dynload'
	'/snap/blender/51/2.91/python/lib/python3.7/site-packages'
	'/snap/blender/51/2.91/scripts/freestyle/modules'
	'/snap/blender/51/2.91/scripts/addons/modules'
	'/home/rt/.config/blender/2.91/scripts/addons/modules'
	'/snap/blender/51/2.91/scripts/addons'
	'/home/rt/.config/blender/2.91/scripts/addons'

Python (External Binary):
=====================================

binary path: '/snap/blender/51/2.91/python/bin/python3.7m'
version: Python 3.7.7

Directories:
=====================================

scripts:
	'/snap/blender/51/2.91/scripts/modules'
	'/snap/blender/51/2.91/scripts'
	'/home/rt/.config/blender/2.91/scripts'
user scripts: '/home/rt/.config/blender/2.91/scripts'
pref scripts: None
datafiles: '/home/rt/.config/blender/2.91/datafiles'
config: '/home/rt/.config/blender/2.91/config'
scripts : '/home/rt/.config/blender/2.91/scripts'
autosave: '/home/rt/.config/blender/2.91/autosave'
tempdir: '/tmp/blender_yiGVLF/'

FFmpeg:
=====================================

avcodec:   '58, 54, 100'
avdevice:  '58,  8, 100'
avformat:  '58, 29, 100'
avutil:    '56, 31, 100'
swscale:   ' 5,  5, 100'

SDL:
=====================================

Version: 2.0.10
Loading method: dynamically loaded by Blender (WITH_SDL_DYNLOAD=ON)

Other Libraries:
=====================================

OpenColorIO:  1,  1,  1
OpenImageIO:  2,  1, 15
OpenShadingLanguage:  1, 10, 10
OpenSubdiv:  0,  0,  0
OpenVDB:  7,  0,  0
Alembic:  1,  7, 12
USD:  0, 20,  5

OpenGL:
=====================================

renderer:	'Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)'
vendor:		'Intel Open Source Technology Center'
version:	'4.5 (Core Profile) Mesa 20.0.8'
extensions:
	GL_3DFX_texture_compression_FXT1
	GL_AMD_conservative_depth
	GL_AMD_draw_buffers_blend
	GL_AMD_multi_draw_indirect
	GL_AMD_query_buffer_object
	GL_AMD_seamless_cubemap_per_texture
	GL_AMD_shader_trinary_minmax
	GL_AMD_texture_texture4
	GL_AMD_vertex_shader_layer
	GL_AMD_vertex_shader_viewport_index
	GL_ANGLE_texture_compression_dxt3
	GL_ANGLE_texture_compression_dxt5
	GL_APPLE_object_purgeable
	GL_ARB_ES2_compatibility
	GL_ARB_ES3_1_compatibility
	GL_ARB_ES3_compatibility
	GL_ARB_arrays_of_arrays
	GL_ARB_base_instance
	GL_ARB_blend_func_extended
	GL_ARB_buffer_storage
	GL_ARB_clear_buffer_object
	GL_ARB_clear_texture
	GL_ARB_clip_control
	GL_ARB_compressed_texture_pixel_storage
	GL_ARB_compute_shader
	GL_ARB_conditional_render_inverted
	GL_ARB_conservative_depth
	GL_ARB_copy_buffer
	GL_ARB_copy_image
	GL_ARB_cull_distance
	GL_ARB_debug_output
	GL_ARB_depth_buffer_float
	GL_ARB_depth_clamp
	GL_ARB_derivative_control
	GL_ARB_direct_state_access
	GL_ARB_draw_buffers
	GL_ARB_draw_buffers_blend
	GL_ARB_draw_elements_base_vertex
	GL_ARB_draw_indirect
	GL_ARB_draw_instanced
	GL_ARB_enhanced_layouts
	GL_ARB_explicit_attrib_location
	GL_ARB_explicit_uniform_location
	GL_ARB_fragment_coord_conventions
	GL_ARB_fragment_layer_viewport
	GL_ARB_fragment_shader
	GL_ARB_framebuffer_no_attachments
	GL_ARB_framebuffer_object
	GL_ARB_framebuffer_sRGB
	GL_ARB_get_program_binary
	GL_ARB_get_texture_sub_image
	GL_ARB_gl_spirv
	GL_ARB_gpu_shader5
	GL_ARB_gpu_shader_fp64
	GL_ARB_half_float_pixel
	GL_ARB_half_float_vertex
	GL_ARB_indirect_parameters
	GL_ARB_instanced_arrays
	GL_ARB_internalformat_query
	GL_ARB_internalformat_query2
	GL_ARB_invalidate_subdata
	GL_ARB_map_buffer_alignment
	GL_ARB_map_buffer_range
	GL_ARB_multi_bind
	GL_ARB_multi_draw_indirect
	GL_ARB_occlusion_query2
	GL_ARB_parallel_shader_compile
	GL_ARB_pipeline_statistics_query
	GL_ARB_pixel_buffer_object
	GL_ARB_point_sprite
	GL_ARB_polygon_offset_clamp
	GL_ARB_program_interface_query
	GL_ARB_provoking_vertex
	GL_ARB_query_buffer_object
	GL_ARB_robust_buffer_access_behavior
	GL_ARB_robustness
	GL_ARB_sample_shading
	GL_ARB_sampler_objects
	GL_ARB_seamless_cube_map
	GL_ARB_seamless_cubemap_per_texture
	GL_ARB_separate_shader_objects
	GL_ARB_shader_atomic_counter_ops
	GL_ARB_shader_atomic_counters
	GL_ARB_shader_bit_encoding
	GL_ARB_shader_clock
	GL_ARB_shader_draw_parameters
	GL_ARB_shader_group_vote
	GL_ARB_shader_image_load_store
	GL_ARB_shader_image_size
	GL_ARB_shader_objects
	GL_ARB_shader_precision
	GL_ARB_shader_storage_buffer_object
	GL_ARB_shader_subroutine
	GL_ARB_shader_texture_image_samples
	GL_ARB_shader_texture_lod
	GL_ARB_shader_viewport_layer_array
	GL_ARB_shading_language_420pack
	GL_ARB_shading_language_include
	GL_ARB_shading_language_packing
	GL_ARB_spirv_extensions
	GL_ARB_stencil_texturing
	GL_ARB_sync
	GL_ARB_tessellation_shader
	GL_ARB_texture_barrier
	GL_ARB_texture_buffer_object
	GL_ARB_texture_buffer_object_rgb32
	GL_ARB_texture_buffer_range
	GL_ARB_texture_compression_bptc
	GL_ARB_texture_compression_rgtc
	GL_ARB_texture_cube_map_array
	GL_ARB_texture_filter_anisotropic
	GL_ARB_texture_float
	GL_ARB_texture_gather
	GL_ARB_texture_mirror_clamp_to_edge
	GL_ARB_texture_multisample
	GL_ARB_texture_non_power_of_two
	GL_ARB_texture_query_levels
	GL_ARB_texture_query_lod
	GL_ARB_texture_rectangle
	GL_ARB_texture_rg
	GL_ARB_texture_rgb10_a2ui
	GL_ARB_texture_stencil8
	GL_ARB_texture_storage
	GL_ARB_texture_storage_multisample
	GL_ARB_texture_swizzle
	GL_ARB_texture_view
	GL_ARB_timer_query
	GL_ARB_transform_feedback2
	GL_ARB_transform_feedback3
	GL_ARB_transform_feedback_instanced
	GL_ARB_transform_feedback_overflow_query
	GL_ARB_uniform_buffer_object
	GL_ARB_vertex_array_bgra
	GL_ARB_vertex_array_object
	GL_ARB_vertex_attrib_64bit
	GL_ARB_vertex_attrib_binding
	GL_ARB_vertex_buffer_object
	GL_ARB_vertex_shader
	GL_ARB_vertex_type_10f_11f_11f_rev
	GL_ARB_vertex_type_2_10_10_10_rev
	GL_ARB_viewport_array
	GL_ATI_blend_equation_separate
	GL_ATI_texture_float
	GL_EXT_EGL_image_storage
	GL_EXT_EGL_sync
	GL_EXT_abgr
	GL_EXT_blend_equation_separate
	GL_EXT_demote_to_helper_invocation
	GL_EXT_draw_buffers2
	GL_EXT_draw_instanced
	GL_EXT_framebuffer_blit
	GL_EXT_framebuffer_multisample
	GL_EXT_framebuffer_multisample_blit_scaled
	GL_EXT_framebuffer_object
	GL_EXT_framebuffer_sRGB
	GL_EXT_packed_depth_stencil
	GL_EXT_packed_float
	GL_EXT_pixel_buffer_object
	GL_EXT_polygon_offset_clamp
	GL_EXT_provoking_vertex
	GL_EXT_shader_framebuffer_fetch_non_coherent
	GL_EXT_shader_integer_mix
	GL_EXT_shader_samples_identical
	GL_EXT_texture_array
	GL_EXT_texture_compression_dxt1
	GL_EXT_texture_compression_rgtc
	GL_EXT_texture_compression_s3tc
	GL_EXT_texture_filter_anisotropic
	GL_EXT_texture_integer
	GL_EXT_texture_sRGB
	GL_EXT_texture_sRGB_R8
	GL_EXT_texture_sRGB_decode
	GL_EXT_texture_shadow_lod
	GL_EXT_texture_shared_exponent
	GL_EXT_texture_snorm
	GL_EXT_texture_swizzle
	GL_EXT_timer_query
	GL_EXT_transform_feedback
	GL_EXT_vertex_array_bgra
	GL_EXT_vertex_attrib_64bit
	GL_IBM_multimode_draw_arrays
	GL_INTEL_performance_query
	GL_KHR_blend_equation_advanced
	GL_KHR_context_flush_control
	GL_KHR_debug
	GL_KHR_no_error
	GL_KHR_parallel_shader_compile
	GL_KHR_robust_buffer_access_behavior
	GL_KHR_robustness
	GL_MESA_framebuffer_flip_y
	GL_MESA_pack_invert
	GL_MESA_shader_integer_functions
	GL_MESA_texture_signed_rgba
	GL_NV_compute_shader_derivatives
	GL_NV_conditional_render
	GL_NV_depth_clamp
	GL_NV_packed_depth_stencil
	GL_NV_texture_barrier
	GL_OES_EGL_image
	GL_S3_s3tc

Implementation Dependent OpenGL Limits:
=====================================

Maximum DrawElements Vertices:	3000
Maximum DrawElements Indices:	3000

GLSL:
Maximum Varying Floats:	128
Maximum Vertex Attributes:	16
Maximum Vertex Uniform Components:	16384
Maximum Fragment Uniform Components:	16384
Maximum Vertex Image Units:	32
Maximum Fragment Image Units:	32
Maximum Pipeline Image Units:	192

Cycles:
=====================================

CPU device capabilities: SSE2 SSE3 SSE41 AVX AVX2

OpenCL device capabilities:
No OpenCL platforms found

Enabled add-ons:
=====================================

io_anim_bvh (version: (1, 0, 0), path: /snap/blender/51/2.91/scripts/addons/io_anim_bvh/__init__.py)
io_curve_svg (version: (), path: /snap/blender/51/2.91/scripts/addons/io_curve_svg/__init__.py)
io_mesh_ply (version: (), path: /snap/blender/51/2.91/scripts/addons/io_mesh_ply/__init__.py)
io_mesh_stl (version: (1, 1, 3), path: /snap/blender/51/2.91/scripts/addons/io_mesh_stl/__init__.py)
io_mesh_uv_layout (version: (1, 1, 1), path: /snap/blender/51/2.91/scripts/addons/io_mesh_uv_layout/__init__.py)
io_scene_fbx (version: (4, 21, 3), path: /snap/blender/51/2.91/scripts/addons/io_scene_fbx/__init__.py)
io_scene_gltf2 (version: (1, 4, 40), path: /snap/blender/51/2.91/scripts/addons/io_scene_gltf2/__init__.py)
io_scene_obj (version: (3, 8, 0), path: /snap/blender/51/2.91/scripts/addons/io_scene_obj/__init__.py)
io_scene_x3d (version: (2, 2, 5), path: /snap/blender/51/2.91/scripts/addons/io_scene_x3d/__init__.py)
cycles (version: (), path: /snap/blender/51/2.91/scripts/addons/cycles/__init__.py)
object_boolean_tools (version: (0, 4, 1), path: /snap/blender/51/2.91/scripts/addons/object_boolean_tools.py)
mesh_looptools (version: (4, 7, 3), path: /snap/blender/51/2.91/scripts/addons/mesh_looptools.py)
space_view3d_3d_navigation (version: (1, 2, 5), path: /snap/blender/51/2.91/scripts/addons/space_view3d_3d_navigation.py)
materials_library_vx (version: (0, 6, 0), path: /snap/blender/51/2.91/scripts/addons/materials_library_vx/__init__.py)
node_wrangler (version: (3, 37), path: /snap/blender/51/2.91/scripts/addons/node_wrangler.py)
measureit (version: (1, 8, 1), path: /snap/blender/51/2.91/scripts/addons/measureit/__init__.py)
precision_drawing_tools (version: (1, 4, 0), path: /snap/blender/51/2.91/scripts/addons/precision_drawing_tools/__init__.py)
add_curve_extra_objects (version: (0, 1, 4), path: /snap/blender/51/2.91/scripts/addons/add_curve_extra_objects/__init__.py)
curve_tools (version: (0, 4, 4), path: /snap/blender/51/2.91/scripts/addons/curve_tools/__init__.py)
add_mesh_BoltFactory (version: (0, 4, 0), path: /snap/blender/51/2.91/scripts/addons/add_mesh_BoltFactory/__init__.py)
add_mesh_extra_objects (version: (0, 3, 7), path: /snap/blender/51/2.91/scripts/addons/add_mesh_extra_objects/__init__.py)
add_mesh_geodesic_domes (version: (0, 3, 6), path: /snap/blender/51/2.91/scripts/addons/add_mesh_geodesic_domes/__init__.py)
mesh_tools (version: (0, 3, 6), path: /snap/blender/51/2.91/scripts/addons/mesh_tools/__init__.py)
mesh_tiny_cad (version: (1, 3, 2), path: /snap/blender/51/2.91/scripts/addons/mesh_tiny_cad/__init__.py)
space_view3d_align_tools (version: (0, 3, 4), path: /snap/blender/51/2.91/scripts/addons/space_view3d_align_tools.py)
object_carver (version: (1, 2, 0), path: /snap/blender/51/2.91/scripts/addons/object_carver/__init__.py)
space_view3d_math_vis (version: (0, 2, 1), path: /snap/blender/51/2.91/scripts/addons/space_view3d_math_vis/__init__.py)
object_print3d_utils (version: (), path: /snap/blender/51/2.91/scripts/addons/object_print3d_utils/__init__.py)
slcad_transform (version: (0, 0, 9), path: /home/rt/.config/blender/2.91/scripts/addons/slcad_transform/__init__.py)
shortcut_VUr-master (version: (0, 9, 2, 0), path: /home/rt/.config/blender/2.91/scripts/addons/shortcut_VUr-master/__init__.py)

**Comment by OmarEmaraDev** [comment]
See section about "libpython3.x : Can't Open Shared Object File" in #1240.

**Comment by stillpointx** [comment]
That's a dangerous fix **Ubuntu PPA's are notorious for breaking other things** especially if you use python in other programs.  Is there another workaround?

**Comment by OmarEmaraDev** [comment]
The solution is to install the dynamic python library. How you do that is up to you. Alternatively, use a Blender version that uses the same python version your system have or simply use the system python.

Note that this library is only needed for 3.7. Python 3.8+ will work without it.

**Comment by stillpointx** [comment]
Thanks.
I'll look into it if I find an easier way I'll post it.

**Comment by stillpointx** [comment]
Thanks.
I'll look into it if I find an easier way I'll post it.

**Comment by stillpointx** [comment]
Just a quick update looks like Blender is saying it's a snap issue...along with not supporting third-party dependencies due to being read-only.
 
Discussion link: https://developer.blender.org/T83085

"Robert Guetzkow (rjg) added a subscriber: Robert Guetzkow (rjg).Edited · Fri, Nov 27, 9:44 AM
As advised in the Sverchok ticket, I would also suggest to use the non-snap official build of Blender that can be downloaded from https://www.blender.org/ . Installing third-party dependencies / modifying the installation with snap is not supported due to being read-only as far as I know.

Robert Guetzkow (rjg) closed this task as Invalid.Fri, Nov 27, 9:59 AM
I'm closing this ticket since this is an issue with how snap works by design and/or the dependencies the third-party add-ons require."

**Comment by OmarEmaraDev** [comment]
It is not really a snap issue for Animation Nodes. Even if you use an official build, you will get the same problem. The dynamic python library is not shipped with Blender or the python snap dependency.

**Comment by stillpointx** [comment]
Looks like the same thing happens with flatpak to

```
rt@sys76:~$ flatpak install blender
Looking for matches…
Found similar ref(s) for ‘blender’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Similar refs found for ‘blender’ in remote ‘flathub’ (system):

   1) runtime/org.blender.Blender.Codecs/x86_64/stable
   2) app/org.blender.Blender/x86_64/stable

Which do you want to use (0 to abort)? [0-2]: 2

org.blender.Blender permissions:
    ipc                  network      pulseaudio      x11     dri
    file access [1]

    [1] host


        ID                           Branch          Op         Remote          Download
 1. [✓] org.blender.Blender          stable          i          flathub         203.6 MB / 210.8 MB

Installation complete.

rt@sys76:~$ flatpak run org.blender.Blender
/run/user/1000/gvfs/ non-existent directory
found bundled python: /app/blender/2.91/python
addon_utils.disable: animation_nodes not disabled
Modules Installed (animation_nodes) from '/home/rt/Documents/My Documents/blender/addons/animation_nodes_v2_2_linux_py37.zip' into '/home/rt/.var/app/org.blender.Blender/config/blender/2.91/scripts/addons'
Traceback (most recent call last):
  File "/home/rt/.var/app/org.blender.Blender/config/blender/2.91/scripts/addons/animation_nodes/__init__.py", line 140, in <module>
    try: from . import test_compile
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/app/blender/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/rt/.var/app/org.blender.Blender/config/blender/2.91/scripts/addons/animation_nodes/__init__.py", line 158, in <module>
    raise Exception(message)
Exception: 

This build does not work at the moment.
  1. Check if the build you downloaded has been compiled for the OS
     you are using. If not, download another one.
  2. If you are on windows you can try to install a library called
     'vc_redist.x64'. Should be easy to find using your search engine
     of choice.
  3. Try to use an official Blender release downloaded from blender.org.
  4. It is possible that you have a build for the correct platform
     but it still does not work. We experienced this mainly on linux.
     Try to find another build for your platform.
     If it still does not work, you have to compile AN yourself.
  5. Make a bug report on Github and give as much information
     as you can. Specifically the full error message, your OS, version, ...

```

**Comment by stillpointx** [comment]
Just another update it seems everyone is just  saying everyone else should include it... sigh...
https://github.com/flathub/org.blender.Blender/issues/65#issuecomment-734892478

**Comment by ramification** [comment]
I've figured out the problem : you have to be sure that you have the full library installed, not just the "minimal" one, which is the default option when installing python from the meta-package "python3.7".

![image](https://user-images.githubusercontent.com/2134642/104852381-18244d80-58fb-11eb-9ca7-3b27637cb84c.png)

**Comment by stillpointx** [comment]
@ramification Issue still occurs because Blender is bundled with it's own version of Python and the new version of Blender 2.91.0 - Python, Ubuntu 20.04 Python, and Animation Nodes doesn't play nice together.

https://docs.blender.org/api/current/info_overview.html

Python in Blender

Blender has an embedded Python interpreter which is loaded when Blender is started and stays active while Blender is running. This interpreter runs scripts to draw the user interface and is used for some of Blender’s internal tools as well.

**Comment by ramification** [comment]
yes but no, I was talking about the packages from the deadsnake PPA ! (I'm on Linux Mint so I'm aware of this problem !)
