### ISSUE TITLE
How do you install an extension ? 

### ISSUE THREAD

**Issue by chromafunk** [JacquesLucke/animation_nodes#1596]
I am trying to make blue fox extension work : https://github.com/harisreedhar/an_bluefox_extension/releases/tag/master-cd-build

But I can't find any clear instructions on how to install extensions. Could you please guide on how to do this ? Thanks

**Comment by OmarEmaraDev** [comment]
It is just a normal add-on. The only special thing about it is that Animation Nodes has to be installed before you install it.

**Comment by chromafunk** [comment]
Thanks :) confirmed to work with AN + an_blue_fox_extension on 2.90.1 / Python3.7

**Comment by chromafunk** [comment]
Thanks, it does work now, but just partially. When you create a new spline tracer, the target splines generated when you move the object won't reset when you go back to frame 1. The target object remains generated and the only way to create a new one is to destroy the entire node setup and re-creating it, making it way too tedious to work with. I'm on blender 2.9.1 with python 3.7.

**Comment by OmarEmaraDev** [comment]
That's good to hear. But this looks like an issue in that particular node. You should report it to the extension developer instead.

**Comment by harisreedhar** [comment]
> Thanks, it does work now, but just partially. When you create a new spline tracer, the target splines generated when you move the object won't reset when you go back to frame 1. The target object remains generated and the only way to create a new one is to destroy the entire node setup and re-creating it, making it way too tedious to work with. I'm on blender 2.9.1 with python 3.7.

Hi, This is official animation nodes repository, please continue queries on [extension repository](https://github.com/harisreedhar/an_bluefox_extension/issues/1)
