### ISSUE TITLE
Proposal: Overlay mode for Mix Falloffs node

### ISSUE THREAD

**Issue by dapa5900** [JacquesLucke/animation_nodes#1597]
Hi. Is it possible for you to add an Overlay mode to the Mix Falloffs node? Basically a mode that only mixes the falloff values within the falloff range from 0 to 1. This mode is quite essential for motion graphics work in order to break the uniformity of the transition area with some randomness for example. Thanks a lot for your great work! 

Please check this video how you can do this in Cinema4D with fields at 10:00min for reference: https://youtu.be/-0PiG0rnpLk

**Comment by OmarEmaraDev** [comment]
> Basically a mode that only mixes the falloff values within the falloff range from 0 to 1.

Can you elaborate on that?

**Comment by dapa5900** [comment]
![overlayMode](https://user-images.githubusercontent.com/75205162/100599034-ca7a6400-32ff-11eb-82d5-ed88dbe67307.gif)


Hi. Thanks for your reply.

Did you watch the video I mentioned? It actually displays quite well what I mean.

I quickly made a small GIF how it works in Cinema4D with a clones (= "Instances" in AN) setup. This setup would basically be the same like in AN using a distribute matrices in grid mode and then offsetting it in Z while restricting the offset of the instances with an object controller falloff in Directional mode for example. If you would mix this Falloff in AN with a Random Falloff Node for example you can use the different available modes for mixing. As you can see, in Cinema4D I toggle between the different modes that are also available in AN. The Overlay mode is unfortunately not available in AN but what it does is it's only affecting the area within the falloff distance basically. So from what I understood is that a falloff spits out values from 0 to 1; 0 not affecting the instances at all and 1 fully affecting the instances. The Overlay Mode therefore would only affect the instances that have a value between 0 and 1, having the biggest effect at 0.5 and then decreasing the effect to zero towards the values 0 and 1 equally. 

You can basically recreate this behavior in AN using a remap falloff node (see blend-file her: https://p7s1-my.sharepoint.com/:u:/g/personal/par0001d_belgium_fhm_de/ETNAbu6Tjr9FheKQFSo7mHMBeADlLp6sHr82hS3ZkUPK4A?e=LyEnu0; there you can also see that the random falloff should only affect the grey instances or 0 to 1 area) approach but of course this setup is more complicated and therefore I think it would be really helpful to add this mode to the mix falloffs node.

**Comment by OmarEmaraDev** [comment]
I see. We can implement that. Thanks for the demonstration.

**Comment by dapa5900** [comment]
Hi. Man, that's awesome! Thanks a lot for your great work on this!

I don't want to seem greedy ;-) but do you think it's ok, if I propose a couple of other things? Coming from Cinema4D I recently managed to wrap my head around AN and was able to rebuild some functionality that I really need for doing motion graphics work. So basically usually this is stuff, that can already be done in AN but similar to this topic here it's currently quite complex to setup some of this compared to Cinema4D. So maybe there's a way to simplify a couple of things in AN, which I think would make it way more accessible and interesting for designers (especially those coming from Cinema4D to Blender which is usually heavy MoGraph work). I'd be really happy to propose and demonstrate these things again, if this helps...?

Thanks a lot again!

**Comment by OmarEmaraDev** [comment]
@dapa5900 Definitely, feel free to propose what you need. We certainly want to make AN more accessible and interesting for designers.

**Comment by dapa5900** [comment]
@OmarEmaraDev Great, will do that soon. Thanks again!

**Comment by OmarEmaraDev** [comment]
Implemented in 8a2288c. Thanks for the suggestion!

**Comment by dapa5900** [comment]
Hi @OmarEmaraDev ,

as mentioned yesterday in the other thread here's my suggestion for improving the default behavior of the overlay mode.

In the example below I offset the instances location by 5 units in z-Direction and restricted this with a directional falloff that is mixed with a random falloff in overlay mode. The random falloff generates by default values between 0 and 1 which currently results in a mix behavior that instances gets offset higher than the maximum offset set by the offset matrices node.

Current Default

![currentDefault](https://user-images.githubusercontent.com/75205162/100994790-3dc9e300-3557-11eb-8770-9e9478334b4b.png)

Instead I would rather suggest that the maximum offset within the overlay section should by default never exceed the maximum offset set in the offset matrices node. When I set the max value in the random falloff node to 0.5 I get the desired behavior.

Suggested Default

![suggestedDefault](https://user-images.githubusercontent.com/75205162/100994787-3c98b600-3557-11eb-9f76-0b77675c5ba6.png)

To put it simple, from what I can see how the mode works now I would suggest to **remap/divide the result of the overlayed falloff** that gets piped into the mix node **by 2**.

What do you think?

**Comment by OmarEmaraDev** [comment]
@dapa5900 Sounds reasonable. Implemented in e3edcd9.
