### ISSUE TITLE
Modifier option from Bmesh from object isn't functioning normally

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1599]
This is very tricky to describe, I will try as best as I can.
1. If modifier is "on" in the original mesh, the target mesh will always be modified in both viewport and final render.
It means this Modifier Options is meaningless.
2. If modifier is "off" in the original mesh and Modifier option in the node is on.
The target mesh will be modified in the viewport, but not in the render.
Thus, there is an inconsistency between render and viewport, and viewport is likely getting wrong result.
3. If modifier is "off" in the original mesh and Modifier option in the node is off.
The target mesh is not modified.

latest AN & blender 2.91. WIN 10.
*******************
There is also an additional thing I want to ask.
In the past it was discussed that "object mesh data" node can't read modifier if the original mesh is disabled.
But here I have found that Bmesh method can read modifier without problem.
Can we therefore have "bmesh mode" for "transform mesh"? Or Bmesh version of "transform mesh" node (thus transform Bmesh)?
Otherwise it always takes two nodes to make it into mesh again for transform.
![bmesh](https://user-images.githubusercontent.com/55994236/100949551-855d5a00-34d8-11eb-965d-7b0573b4344e.png)

**Comment by OmarEmaraDev** [comment]
I can replicate some issue with the node. Not sure if it is the one you are describing. I will investigate.

**Comment by Gerstmann-Bradley** [comment]
Any update? This isn't an urgent issue, so feel free to take your time.

**Comment by OmarEmaraDev** [comment]
Still haven't categorized this, sorry for the delay. I should be available again in couple of days.

**Comment by Gerstmann-Bradley** [comment]
I see. I will retract my second proposal. Or you can still implement it if you wish. After all I think it's not useless.

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley So, we deprecated the Deform input of the Bmesh `from_object` method in [D10086](https://developer.blender.org/D10086). Which we also had to remove in Animation Nodes in d978d82. Moreover, perhaps more alarming to you, we change the internals of the method as well in [D10053](https://developer.blender.org/D10053), so now it will no longer be possible to compute modifiers if the object is disabled, at least during rendering.

**Comment by Gerstmann-Bradley** [comment]
> @Gerstmann-Bradley So, we deprecated the Deform input of the Bmesh `from_object` method in [D10086](https://developer.blender.org/D10086). Which we also had to remove in Animation Nodes in [d978d82](https://github.com/JacquesLucke/animation_nodes/commit/d978d82d941a502cd3a09a82d374acc02263e62c). Moreover, perhaps more alarming to you, we change the internals of the method as well in [D10053](https://developer.blender.org/D10053), so now it will no longer be possible to compute modifiers if the object is disabled, at least during rendering.

Sounds unfortunate, but I get the point, Thanks for letting me know.

**Comment by Gerstmann-Bradley** [comment]
Hi, Omar. Back to the days we are talking about modifier issue in object mesh data node. We have made conclusion that if we are using object mesh data to load modifier, we can not disable from collection, viewport and render.
In Geometry Nodes, however, we can disable the collection but the instanced object will retain its modifier.

In the shown example, red is plane or plane instancing subdivded cube. White is object instanced by AN.
Interestingly, If the geometry node is instance that object, even if I disable the GN modifier in the viewport and render, AN can also start to read modifier data.
Would you be able to investigate their secretes and try to implement that? Thanks.

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley I am not following exactly, can you elaborate?

**Comment by Gerstmann-Bradley** [comment]
> @Gerstmann-Bradley I am not following exactly, can you elaborate?

Basically Geometry Nodes can read modifier data from the object, which is in a disabled collection.
Animation Nodes can not do so, unless this object is being used by geometry nodes somehow.

Previously it was said to be a blender limitation and AN couldn't do anything to solve this.
But it now seems doable in blender geometry nodes, while AN can't.

**Comment by OmarEmaraDev** [comment]
Well, we can only access the modified object if Blender evaluates it somehow. When instancing using GN, the object is evaluated and so it can be accessed. This is nothing special about GN, you could replicate that in multiple other way. The point is that if it is disabled in the viewlayer and Blender doesn't need its data somehow, it will not be evaluated.

**Comment by Gerstmann-Bradley** [comment]
hmmm, so AN can't intentionally ask blender to evaluate an object by any means?

**Comment by OmarEmaraDev** [comment]
Not as far as I know. Blender evaluates things before AN executes anyways, so we can't ask Blender to reevaluate something mid-execution. Well, we can, but we probably shouldn't. :)

**Comment by Gerstmann-Bradley** [comment]
ok, that's unfortunate,
