### ISSUE TITLE
Bug: Particles Info node doesn´t work with keyed particles

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#160]
As far as I´ve been testing it doesn´t work. Here is the file:

It´s just a test  where positions of object instance should be driven by a keyed particle system:

http://www.pasteall.org/blend/37079

If you have any doubts don´t hesitate to drop me a line.

Thanks in advance.

**Comment by JacquesLucke** [comment]
thanks for the info. I found out why it doesn't work. I have to explore this more in the future. Currently it does look like a lot of performance is needed to calculate the correct position for each particle based on the keys. Maybe there is a nicer way to do this....

**Comment by YorsLosilla** [comment]
Well. After thinking on this for a while. This shouldn´t be a priority at all. This type of transitions could be done easily inside animation nodes in more nicer way than with the built in keyed particles which are animated only  with linear transitions.

**Comment by YorsLosilla** [comment]
Well after making some test I have found a severe limitation linked to this bug. If you want to trace particles with the closes vertex node on keyed particles. You need blender built in particle system.

If you animate objects from the positions of one particle system to the positions of another particles system you can trace the lines, which should be traced from the particle system.

**Comment by JacquesLucke** [comment]
I didn't really found out how to access that data. I will close this issue for now
