### ISSUE TITLE
Proposal: Instantiate collections

### ISSUE THREAD

**Issue by bonalex01dev** [JacquesLucke/animation_nodes#1600]
Hi, it would be very usefull to be able to create a number of collection instances. Especially now that the new proxy mechanism relying on collections is gettting up to speed.
My use case is to create one collection instance per particle.

**Comment by Gerstmann-Bradley** [comment]
Is this what you are looking for? Instance collection as a whole?
![1](https://user-images.githubusercontent.com/55994236/101166904-06b30a80-3607-11eb-8645-9575176507a9.png)
![2](https://user-images.githubusercontent.com/55994236/101166914-0b77be80-3607-11eb-8346-a3544819abce.png)

**Comment by bonalex01dev** [comment]
Yes that's what I meant.
I'll retry this

Le ven. 4 déc. 2020 à 14:02, Gerstmann-Bradley <notifications@github.com> a
écrit :

**Comment by bonalex01dev** [comment]
I was trying with linked collections. It works only if I check "copy full object" and "Deep Copy" otherwise, nothing happens.
Maybe this could be documented in the documentation of AN. 
Also The node works only with an instanced collection as source. That's good to me, because only then a collection becomes an object . But again, it could be hinted in the documentation.
Anyway thanks for good and fast help

**Comment by OmarEmaraDev** [comment]
I suppose we can add a special option for collections in the node to make it easier. I will consider the options we have and let you know.
