### ISSUE TITLE
keyframed animation node values don't interpolate or show up in the dope sheet

### ISSUE THREAD

**Issue by bitbutter** [JacquesLucke/animation_nodes#1602]
**System Information**
Operating system: Windows-10-10.0.18362-SP0 64 Bits
Graphics card: GeForce RTX 2060/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 442.23

**Blender Version**
Broken: version: 2.91.0, branch: master, commit date: 2020-11-25 08:34, hash: `rB0f45cab862b8`

if i use the I key to set a keyframes for the B value of the math node at different times, the value doesn't interpolate as expected (stays at the last entered value). and the keyframes don't show up in the dope sheet.

![image](https://user-images.githubusercontent.com/52042/101363386-a25fa780-38a1-11eb-8e37-7a99f54e912b.png)

**Comment by OmarEmaraDev** [comment]
Unfortunately, this is a Blender limitation. Keyframes in node-trees are not supported.

**Comment by Gerstmann-Bradley** [comment]
> **System Information**
> Operating system: Windows-10-10.0.18362-SP0 64 Bits
> Graphics card: GeForce RTX 2060/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 442.23
> 
> **Blender Version**
> Broken: version: 2.91.0, branch: master, commit date: 2020-11-25 08:34, hash: `rB0f45cab862b8`
> 
> if i use the I key to set a keyframes for the B value of the math node at different times, the value doesn't interpolate as expected (stays at the last entered value). and the keyframes don't show up in the dope sheet.
> 

There is a workaround for the keyframe part. If interested, you can go to 5:06 at https://youtu.be/JeQAnRJiP0k

**Comment by bitbutter** [comment]
thanks @Gerstmann-Bradley i'll try that
