### ISSUE TITLE
Proposal: Along Spline Falloff

### ISSUE THREAD

**Issue by dapa5900** [JacquesLucke/animation_nodes#1605]
Hi,

now that we have the Spline Distribution available, can you please add an Along Spline Falloff to create tapered distributions of instances along the spline?

Please find here a blend-file how I tried to achieve this effect with a custom falloff:

https://p7s1-my.sharepoint.com/:f:/g/personal/par0001d_belgium_fhm_de/EjSXLuyXM6dPuEYPo2GLZcwBEnP9YvoZonBhZQvDSyVBfQ?e=ilZykQ

I managed to dynamically get the start and end position of the spline on the X-Axis but of course this should always work, no matter how the spline is placed in the 3D-space. By default the falloff should generate a range from 0-1 from start to the end of the spline I think.

Maybe you could implement this as separate node or maybe better as an extra option in the Spline Falloff Node?

I opened this ticket in parallel to the offset along spline proposal (https://github.com/JacquesLucke/animation_nodes/issues/1604) because it's probably a good idea to develop both of them in parallel. (Mainly to ensure that the falloff works correctly when the instances get offset; like for example that the taper-shape shouldn't be offset together with the instances but stay the same.)

Thank you!

**Comment by OmarEmaraDev** [comment]
I feel like what you are actually want is a fade falloff. See the following example.

![20201211-232445](https://user-images.githubusercontent.com/25300994/101956132-c277c980-3c07-11eb-8e0a-c34e216a4e1c.png)

Do you think this solution is satisfactory?

**Comment by dapa5900** [comment]
@OmarEmaraDev

Thanks for this. I will try this myself on Monday but I think it looks good. I thought I tried the fade falloff before a while ago but for some reason couldn't get it to work like this... Maybe because I didn't had the spline distribution method back then.

Do you thing it would still make sense the add both a "radius" (current behaviour) and an "along" option (which does exactly what you showed here) to the current spline falloff node, just because this would then be more obvious since its directly spline related? Or would this be too redundant?

Also, is there a diffence between using a get list length node like in your setup to just plugging the matrix output directly in the amount input and get the get length node automatically?

Thanks!

**Comment by OmarEmaraDev** [comment]
I think that's reasonable, we could add that option. I am mostly concerned about the performance though, since an implementation will probably need to do spline projection, which is probably the slowest operation to do on a spline. Will see if I can do something about that.

**Comment by dapa5900** [comment]
Thanks. I think performance should be prioritised so if this approach would be too heavy I think it's better to just stick to the current way if achieving this.

**Comment by OmarEmaraDev** [comment]
Implemented in 4e8f238. Thanks for the suggestion!

This uses an approximation with the resolution option in the Advanced Node Settings controlling the accuracy. We will enable an accurate solution once we have a faster spline projection method.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

Works perfectly. Thanks a lot!
