### ISSUE TITLE
Proposal: a "Splines from text object" node or an update for "Separate text object" node

### ISSUE THREAD

**Issue by VladFromRomania** [JacquesLucke/animation_nodes#1607]
At the moment, only procedural way to convert text to curves is to use the `Separate text object` node. Problem with that approach:
It is not really procedural and does not work well with `Decompose text `node.
 Why did I came to the conclusion that such a node would be useful?
 I am working on a project where I do some text manipulation (`Decompose text node`) and I want to add some effects on top (some lights that are following the contour of the text (the non extruded text is converted to a curve, that I then use for animation). Allthough I have found a non procedural workaround, I have come to realise how useful would be a node that I can just plug into the output of the the `Text Object Output`or the `Matrix Object Output` to generate the spline in realtime, even if I change the text.

**Comment by OmarEmaraDev** [comment]
The problem is that Blender doesn't provide access to such information. So we can't add a procedural way to handle that. Your only option for now is to use the Separate Text Object node? Why is missing from this node that you want?

**Comment by VladFromRomania** [comment]
@OmarEmaraDev Thank you for answering so fast. 

> Your only option for now is to use the Separate Text Object node? Why is missing from this node that you want?

- It would be useful to have an text object socket for `Separate Text Object` node, so that I can feed the output of the `Text Object Output `int it, insted of color picking. I think that would also allow me to loop through the characters that I get if I use the `Decompose Text` so that I could get a list of splines out of it.

- Also, would it be posible to have like a boolean input for the update buton  of the `Separate Text Object,` so that it would not be necesary to manualy click on it?

**Comment by OmarEmaraDev** [comment]
I will try to think of a way to accommodate what you need. Might take me sometime as I am rather busy right now.

**Comment by VladFromRomania** [comment]
> I will try to think of a way to accommodate what you need. Might take me sometime as I am rather busy right now.

Thank you very much!

**Comment by OmarEmaraDev** [comment]
@VladFromRomania We submitted a patch to add the functionality in Blender in [D10060](https://developer.blender.org/D10060). Once this lands, adding support in Animation Nodes should be easy.

**Comment by VladFromRomania** [comment]
👍 @OmarEmaraDev

**Comment by OmarEmaraDev** [comment]
Implemented in Blender in [D10354](https://developer.blender.org/D10354) and incorporated in Animation Nodes in 7328e0b. We also took the opportunity to implement modifier evaluation for splines, which is now allowed in Animation Nodes.

Thanks for the suggestion!

**Comment by VladFromRomania** [comment]
thank you for taking this request into consideration!
