### ISSUE TITLE
Bevel Object in the curve object output broke in 2.91

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1608]
People asked me about this issue, and I found it's replicable.
I think it's related to the improvement of curve bevel since 2.91, and problem more likely stems in AN in this case?
Although I haven't tried 2.92 and above, at least now 2.91 is still the most updated stable version that users use.
*************
Also, would you add the "fill cap" option for curve object output node? Since 2.91 updated it, and I think it's very important.
Profile beveling will also be great, but I think it's too complicate to implement at this moment?
Either way, I will just let you decide. Thanks.
![image](https://user-images.githubusercontent.com/55994236/102009279-5fb82800-3d04-11eb-926c-03c0212360ff.png)

**Comment by OmarEmaraDev** [comment]
Fill caps and bevel mode were implemented in d84fae9. Thanks for the report!
