### ISSUE TITLE
The animation Nodes addon is not able to setup the execution units for the node tree

### ISSUE THREAD

**Issue by Manubt1993** [JacquesLucke/animation_nodes#1609]
I installed animation nodes on blender 2.92, worked on a node tree but when i delete a node and then press Ctrl Z to undo the delete, this happens 
![issue 2](https://user-images.githubusercontent.com/73073635/102027974-68fece80-3db0-11eb-8292-7d4c6e9d5d15.JPG)
![issue](https://user-images.githubusercontent.com/73073635/102027957-47054c00-3db0-11eb-9f7b-90edcef7c63f.jpg)
And it doesn't work anymore

**Comment by OmarEmaraDev** [comment]
Is it reproducible? Does it happen every time you do the same action?

**Comment by Manubt1993** [comment]
Yes, every time i click Ctrl Z to undo a deleted not this happens

**Comment by OmarEmaraDev** [comment]
I can't replicate this issue unfortunately. Can you share that file perhaps? Or maybe another simpler file where the problem happens.

**Comment by Manubt1993** [comment]
Ok, here is the file 

[error file.zip](https://github.com/JacquesLucke/animation_nodes/files/5699034/error.file.zip)


When i connect these two nodes and then press Ctrl + z to undo, i get the error
![11](https://user-images.githubusercontent.com/73073635/102279916-dfc4d480-3f34-11eb-953c-165ee6c72501.JPG)

**Comment by OmarEmaraDev** [comment]
I still can't replicate the issue unfortunately.
