### ISSUE TITLE
'Object mesh info' - lacks of caching button

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#161]
Caching option for 'Object mesh info' node is hidden, so user is unable to enable it. For my node setup I just set caching to be always true, because I'm not sure how to fix it. With caching enabled I get decent performance.
![image](https://cloud.githubusercontent.com/assets/13521338/8906410/c2452c88-346e-11e5-9de5-fd98a7c1cf32.png)

**Comment by JoseConseco** [comment]
I just realized what draw_buttons_ext() method does, and now I see this checkbox in properties panel on right. It may be hard to find for new uses, but I close it for now.

**Comment by JoseConseco** [comment]
On second thought global button (in preferences or debug panel) 'reload cache' would be awesome. No need to dig into nodes properties to enable/disable cache!

**Comment by JacquesLucke** [comment]
The problem (and reason why it is turned off by default) is that you cannot always use it without unwanted behavior. 
For example when you transform individual polygons the cache data will be changed as well...

I know that there should be a better and more general solutions for caching data but this isn't my priority atm

I'm currently on vacation, and when I'm back I will continue working on the nodes :)
