### ISSUE TITLE
Red Bar error for wiggle action node

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1610]
Win10, Latest AN up to 12.17.2020.
I am not familiar with action series of node, but I suppose this is a bug.
To replicate issue:
1. build node tree as shown, click "Add" in wiggle action node.
2. Change any parameter in node tree will immediately cause red bar error.

To resolve:
Delete the path. & Retry.

![error node](https://user-images.githubusercontent.com/55994236/102552426-3514f900-408f-11eb-99aa-8c4c7b58b304.png)
![error message](https://user-images.githubusercontent.com/55994236/102552435-38a88000-408f-11eb-9647-89ce35e47484.png)

**Comment by Gerstmann-Bradley** [comment]
I find a replicate #1459

**Comment by OmarEmaraDev** [comment]
Fixed in d36e2b1. Thanks for the report @Gerstmann-Bradley!
