### ISSUE TITLE
'GPencilStroke' object has no attribute 'draw_cyclic'

### ISSUE THREAD

**Issue by Censorazor** [JacquesLucke/animation_nodes#1611]
I'm using Blender v2.91 with AN v2.1.8, so that is probably playing a role. Toggling cyclic on and off for a specific stroke and cheching the Python Console seems to indicate that the name for this attribute has been changed. The prolem occurs the moment I select a grease pencil object for the "GP Object Input" node so GP is unuseable for this blender version like this. Anyway I know I'm an idiot for using incompatible versions, just thought I'd share so it's taken into consideration for the upcoming update.

**Comment by OmarEmaraDev** [comment]
This was updated in #1594 already. So updating AN should solve the issue. But thanks for the report!
