### ISSUE TITLE
Dismantling of the old Docs before finishing the new one was a bad move! 

### ISSUE THREAD

**Issue by noc2art** [JacquesLucke/animation_nodes#1612]
I'm sorry but I need to vent my thoughts on the so-called renewed AN documentation. I am aware that it is still a work-in-progress and that your aim is to expand it even further, which is great. Nevertheless, I find the decision of taking down the old one down completely as you build the new one somewhat reckless! The old docs had lengthy explanations of each node, numerous example pictures and example gifs all over the place, under each section that I personally referred to all the time. They were probably months worth of meticulous work by Jacques Lucke. Now, they're no where to be found on the net. Now, I know that you intend on turning all those gifs into playable videos in the new version, but why on earth did you not even bother keep the old one on the side and give a link to it, at least until the new one was all done??? As of now, you literally have the community stuck with a half-finished documentation and no one knows how long it'll take until it's completely ready. My 2 cents...

AJ

**Comment by OmarEmaraDev** [comment]
See https://github.com/JacquesLucke/animation_nodes_manual/issues/80, lets continue this discussion there. You can still access the old documentation including the examples here: https://github.com/JacquesLucke/animation_nodes_manual/tree/v2.0/docs/user_guide/nodes
