### ISSUE TITLE
Setting spline object material

### ISSUE THREAD

**Issue by grant-h** [JacquesLucke/animation_nodes#1613]
I'm unable to find a way to set the material of individual points on a spline, within an object with multiple splines.
This is being used for an audio visualizer, hence some splines would look best with different material indexes.

Also, when inputting a base spline object as input (Splines from Object), the material index is set to the default of zero and not preserved on Curve Object Output node. This seems like a bug to me or a lack of understanding on my part.

Blender 2.91, Animation Nodes 2.1.8

**Comment by OmarEmaraDev** [comment]
As far as I know, spline points can't have different material indices, splines as a whole can have material indices. Is this what you want?

**Comment by grant-h** [comment]
Yes, that describes it better. Multiples curves per object, each with a different material index.

**Comment by OmarEmaraDev** [comment]
We currently don't support that, but we can add support.

**Comment by OmarEmaraDev** [comment]
Implemented in 58feb87. Thanks for the suggestion!
