### ISSUE TITLE
the Spline mode in Distribute Matrix Node has some bugs

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1614]
![spline mode error](https://user-images.githubusercontent.com/64368228/103503871-b1ca1480-4e90-11eb-9702-15dbbad67025.png)

in vertices mode, you can see in the screenshot above there are 100 points, but only four matrices, others matrices doesn't work correctly.

![spline axis error](https://user-images.githubusercontent.com/64368228/103503985-09688000-4e91-11eb-87a2-0f63a7805aef.png)

i noticed that the bule Z axises bias every step martix, is it designed like this ? or is it a glitches?

**Comment by OmarEmaraDev** [comment]
Can you share this particular file?

**Comment by kdsin23** [comment]
> The second problem is expected as far as I can tell. I will look into the first problem. Can you share this particular file?

OK,here is the file
[matrix error.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/5764829/matrix.error.blend.zip)

**Comment by OmarEmaraDev** [comment]
Seems to be working fine here.

![20210104-153559](https://user-images.githubusercontent.com/25300994/103540177-01fda280-4ea2-11eb-9857-eb30103e43cb.png)

**Comment by kdsin23** [comment]
> Seems to be working fine here.
> 
> ![20210104-153559](https://user-images.githubusercontent.com/25300994/103540177-01fda280-4ea2-11eb-9857-eb30103e43cb.png)

Thank you! i feel so weird!  why not working for me ,do you think what is the reason? but i have another way to work around this issue for me, using RESOLUTION mode
![matrix err0r](https://user-images.githubusercontent.com/64368228/103602003-f2379a00-4f45-11eb-91fe-ea25fb9806e3.png)

**Comment by OmarEmaraDev** [comment]
@kdsin23 Actually, that's exactly how the vertices mode is computed. Can you maybe check the scale of the output matrices? Maybe they have a zero scale.

**Comment by OmarEmaraDev** [comment]
Fixed in 0cc12b0. Thanks again!

**Comment by kdsin23** [comment]
> @kdsin23 Actually, that's exactly how the vertices mode is computed. Can you maybe check the scale of the output matrices? Maybe they have a zero scale.

i change the source code , add the 

> spline.ensureNormals() to the execute_SplineVertices, and recompiled , now it works correctly!
