### ISSUE TITLE
Add Z Height to Spiral in Distribute Matrix Node

### ISSUE THREAD

**Issue by kdsin23** [JacquesLucke/animation_nodes#1616]
![height](https://user-images.githubusercontent.com/64368228/103625734-596d4280-4f76-11eb-8f8e-6962591f68b1.gif)

i think it is handy to generate a hellix, if we can put Z to the node.

**Comment by Gerstmann-Bradley** [comment]
Perhaps I wish to add an option to "offset" for height as well. Like the Grid mode.

**Comment by OmarEmaraDev** [comment]
Do you have a pull request ready for this?

**Comment by kdsin23** [comment]
> Do you have a pull request ready for this?

not yet, i want to improve some functions accroding to Gerstmann-Bradley's advices, do you think where still to be improved, please let me know if possible, Thank you!

![helix](https://user-images.githubusercontent.com/64368228/103719897-0e4e4080-5005-11eb-9e64-909986b96e8c.gif)

**Comment by kdsin23** [comment]
> Perhaps I wish to add an option to "offset" for height as well. Like the Grid mode.
> Another thing is I wish to possibly interpolate this height value as shown, so that it will make helix more interesting. Usage including making tornado sorts of thing possibly.
> ![Spiral](https://user-images.githubusercontent.com/55994236/103630397-dfbb6180-4f41-11eb-87a8-b3a2748111c9.png)

Thank you for your suggestions, i will try later!

**Comment by Gerstmann-Bradley** [comment]
> > Do you have a pull request ready for this?
> 
> not yet, i want to improve some functions accroding to Gerstmann-Bradley's advices, do you think where still to be improved, please let me know if possible, Thank you!
> 
> ![helix](https://user-images.githubusercontent.com/64368228/103719897-0e4e4080-5005-11eb-9e64-909986b96e8c.gif)

Looks good to me! Thanks for improving it!

**Comment by Gerstmann-Bradley** [comment]
@OmarEmaraDev Hi Omar, I have one question. Is it possible to add kind of alias to call specific mode within a node?
For example, If I hit ctrl+A and search for spiral/circle, it will provide "distribute matrices - spiral mode"/"circle mode", etc.

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley Yes, implemented in 9a40fb6.

**Comment by OmarEmaraDev** [comment]
@kdsin23 I wouldn't add the XY, YZ, XZ options. They can be achieved with more control using a rotate node after generation. You can just create the pull request and we can discuss it further there.

**Comment by OmarEmaraDev** [comment]
Implemented in b1d739c.
