### ISSUE TITLE
GP Object Input' does not work

### ISSUE THREAD

**Issue by o-kurage** [JacquesLucke/animation_nodes#1619]
When I try to use the GP Object Input node, I get the following error.

> 'GP Object Input' does not work (undocumented operator)
> bpy.ops.an.move_view_to_node (nodeIdentifier = "_ b4y3hnq39to0gyj")

The procedure is as follows.

1. Added GP Object Input node
2. Enter the object name
3. Error occurred(Or even if you enter the layer name)

I also confirmed it in the .blend file released below.

[https://drive.google.com/drive/folders/12shiQFgwJPjaJchOn8zxGWuw7FiGi7I4
](https://drive.google.com/drive/folders/12shiQFgwJPjaJchOn8zxGWuw7FiGi7I4
)

I'm sorry for not studying, but if you have any idea, I would appreciate it if you could give me your opinion.

**Environmental information**
Mac OS X: High Sierra 10.13.6
Blender: 2.91 beta
AnimationNodes: 2.2.1
(Animation_nodes_v2_2_macOS_py37.zip)

**Comment by 3DSinghVFX** [comment]
Hi.
Actually, I have provided those example files but they are working fine on my side. Can you please provide the full log of the error?
If you are using Blender 2.91 then please use the Latest Build of [Animation Nodes](https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build).

**Comment by o-kurage** [comment]
Thank you for your reply and confirmation.

Is this the full log?
(Node Tree> Developer> Execution Code> Monitor Execution> Write> Save as)

[Execution Code.txt](https://github.com/JacquesLucke/animation_nodes/files/5790054/Execution.Code.txt)

**Comment by OmarEmaraDev** [comment]
@o-kurage The error probably means that those files were created in a version not compatible with your installed version. You can probably correct this by deleting the node in question and re-adding it again.

I can open the files Kuldeep provided using master, so I am guessing your version is the one out of sync. Can you try downloading and installing the latest version?

**Comment by o-kurage** [comment]
@OmarEmaraDev Thank you for your reply and confirmation.
We always refer to your answers on blender.stackexchange.com.

I tried downloading and installing the latest version from link above [Animation Nodes](https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build).
I installed [animation_nodes_v2_2_macOS_py37.zip](https://github.com/JacquesLucke/animation_nodes/releases/download/master-cd-build/animation_nodes_v2_2_macOS_py37.zip).
But no change was seen and the error was not resolved.

**Comment by OmarEmaraDev** [comment]
@o-kurage Does recreating the node tree from scratch without opening the file cause the same error to happen?

**Comment by o-kurage** [comment]
How do I "recreating the node tree from scratch without opening the file"?
When I open the project file, select the node and do "Reset Node", the error disappears, but the input also disappears.
I may have made a mistake, but I can't identify it.
Excuse me, could you please tell me the procedure?

**Comment by OmarEmaraDev** [comment]
@o-kurage I meant don't open any files, start a new Blender file, create the node tree yourself, add the GP input node yourself. Will the error happen then?

**Comment by o-kurage** [comment]
Noted with thanks.
Yes, I tried it but I still get an error.

The process of error is below.
1. New File>General
2. 3D Viewport>Add>Grease Pencil>Stroke
3. Animation Nodes>Add>Grease Pencil>Object Input>Value:Stroke
4. Error

**Comment by OmarEmaraDev** [comment]
hmmm, I am not sure to be honest. Can anybody else try to reproduce this?

**Comment by o-kurage** [comment]
Unfortunately, I searched for it but couldn't find an article about a similar error.

It may not be related, but in my environment, Matrix in "3D viewer" node is not displayed either.
The vector is displayed.
When I asked a question before, I received the answer "Because the specifications of Mac are different from Windows".

**Comment by OmarEmaraDev** [comment]
@o-kurage I was actually calling for other developers/users to try to reproduce, sorry for the confusion. We will try to reproduce it ourselves and let you know.

**Comment by o-kurage** [comment]
@OmarEmaraDev Thank you for all your consideration. 
I'm sorry for the trouble.

**Comment by harisreedhar** [comment]
In my testing with latest AN on linux mint i had no issues.

**Comment by Gerstmann-Bradley** [comment]
I wish to help, but I am on Windows. I personally can't reproduce the issue in 2.91 & latest AN.

**Comment by o-kurage** [comment]
Thank you, everyone.
I'm probably always watching your tutorial videos on Youtube.

**Comment by o-kurage** [comment]
solved.
I'm sorry, it was my mistake.
When I reinstalled it earlier, I confirmed that the error disappeared.
It seems that I made a mistake in the installation method.
I apologize for the trouble.
Thank you for your answers.

**Comment by OmarEmaraDev** [comment]
That's good to hear.
