### ISSUE TITLE
Ability to customize sockets like in cycles mateiral.

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#162]
Basically I would like to see this in Animation Nodes:
![image](https://cloud.githubusercontent.com/assets/13521338/8907135/4c2c3540-3474-11e5-815d-0dfe7739e611.png)

Because currently it is bit hard to manage sockets, especially when you have 10 outputs/inputs, and then you want to reorder them.

**Comment by JacquesLucke** [comment]
Ok, I will see if this is easy to implement.. Thanks for showing me the image. It shows definitly a better way for reordering sockets

**Comment by JoseConseco** [comment]
I just noticed today, that combine socket already has feature that I requested above.
![image](https://cloud.githubusercontent.com/assets/13521338/9026063/f8bac852-3920-11e5-8f53-981a12edf2cb.png)
It would be awesome, if it worked on groups, loops. And then maybe min, max, default value could be editable in 'socket settings' panel on right...

**Comment by JacquesLucke** [comment]
This is only in my working branch currently but works quite well. Thanks for the request
![manage sockets](https://cloud.githubusercontent.com/assets/5881326/9068503/18ecf48c-3ae4-11e5-818d-f4c7d39ebbab.PNG)
