### ISSUE TITLE
How much is AN possible to support light?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1621]
My basic question is simple: **If I instance a light source using animation nodes, I want to control light power differently, like using a "random number" node**.
I have tried object attribute output, the attribute is not found.
I have to use "Ctrl+Shift+Alt" to copy bpy. data path to control its power.
This method is great, but as I am instancing these light sources, it's difficult for me to reach each individual light. I am yet playing the expression statement to see if this can be more procedural, but after all I am not a coder and I have to think a lot to get the statement right 

I wonder if this is something that can be done more easily?
Or any suggestion to get light's bpy. path procedurally will be great as well.

It will be easier to use emission shader and render in cycle, but I am using eevee so there are lots of problems related to emission shader in animation.

**Comment by OmarEmaraDev** [comment]
The light energy is an attribute of the light data block, not the object. To get the light data block from an object, you use the `data` attribute. It follows that in order to access the the energy of the light of an object, you use the `data.energy` attribute.

**Comment by Gerstmann-Bradley** [comment]
> The light energy is an attribute of the light data block, not the object. To get the light data block from an object, you use the `data` attribute. It follows that in order to access the the energy of the light of an object, you use the `data.energy` attribute.

I see, it works great. Thanks!
