### ISSUE TITLE
profile report of object instancer

### ISSUE THREAD

**Issue by drewp** [JacquesLucke/animation_nodes#1623]
![image](https://user-images.githubusercontent.com/104003/104087490-f51bde80-5214-11eb-8723-d3b963f0a89a.png)

I accidentally ran an instancer with 150k objects, and while I was waiting for it to run, I launched py-spy and noticed these lines apparently taking all the time. A quarter of the time in 'newObject.hide_select = False'? Maybe there's a way to set these in batch; fix blender to handle them without triggering as much work; or not call them at all.

**Comment by OmarEmaraDev** [comment]
Thanks for the report! I will see if we can do something about that.

**Comment by OmarEmaraDev** [comment]
That code seems redundant in most cases. Removing it yielded up to 4x performance improvement. Fixed in 6f5a6eb.

Many thanks again @drewp!
