### ISSUE TITLE
MIDI implementation difficulties

### ISSUE THREAD

**Issue by OmarEmaraDev** [JacquesLucke/animation_nodes#1625]
Hi @Clockmender @Patochun,

I am testing some recorded MIDI files and I am noticing some weird behaviors, I was hoping one of you could provide some insights. The following is a subset of the channel events of one of the files:

```
NoteOnEvent(deltaTime=2, channel=0, note=38, velocity=47)
NoteOnEvent(deltaTime=205, channel=0, note=38, velocity=53)
NoteOffEvent(deltaTime=1, channel=0, note=38, velocity=0)
NoteOffEvent(deltaTime=167, channel=0, note=38, velocity=0)
NoteOnEvent(deltaTime=3, channel=0, note=38, velocity=49)
NoteOffEvent(deltaTime=10, channel=0, note=38, velocity=0)
```

The problem here is that there are two `NoteOnEvent` on the same channel and note number, followed by two `NoteOffEvent` on the same channel and note number. Is that allowed by the MIDI specification? Or is that a corrupt file? I was under the impression that each Note On will always be followed by a Note Off on the same channel and note number.

**Comment by OmarEmaraDev** [comment]
I eventually opted for ignoring subsequent Note On Events and their respective Note Off Events. So for the track above, the effective events will be as follows:

```diff
  NoteOnEvent(deltaTime=2, channel=0, note=38, velocity=47)
- NoteOnEvent(deltaTime=205, channel=0, note=38, velocity=53)
- NoteOffEvent(deltaTime=1, channel=0, note=38, velocity=0)
  NoteOffEvent(deltaTime=167, channel=0, note=38, velocity=0)
  NoteOnEvent(deltaTime=3, channel=0, note=38, velocity=49)
  NoteOffEvent(deltaTime=10, channel=0, note=38, velocity=0)
```

**Comment by Clockmender** [comment]
Hi Omar,

it is definitely a corruption of the file, it is impossible to have a note-on NOT followed by a note-off from any MIDI device, so you are right to take these out!

sorry for delay in getting back to you. Hope you are staying COVID free!

Cheers Clock.

**Comment by OmarEmaraDev** [comment]
I see. Thanks for getting back to me @Clockmender!

**Comment by Patochun** [comment]
I don’t know exactly if this is allowed or not. But when you process the midifile step by step, any event on one note (same channel) replace the previous state of note.

 

Cheer.

 

De : Omar Emara <notifications@github.com> 
Envoyé : mercredi 13 janvier 2021 15:22
À : JacquesLucke/animation_nodes <animation_nodes@noreply.github.com>
Cc : Patrick Mauger <ptkmgr@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [JacquesLucke/animation_nodes] MIDI implementation difficulties (#1625)

 

Closed #1625 <https://github.com/JacquesLucke/animation_nodes/issues/1625> .

**Comment by OmarEmaraDev** [comment]
@Patochun If the second Note On overwrote the first Note On, the first Note Off will also "close" the second Note One, and we will end up with an extra Note Off. Moreover, by doing this, we generate the shortest note possible. Upon inspection of such events in MIDI files, we will notice that the window of overlap between those double notes is very small (Look at the delta times above). So my decision to choose the longest note possible is probably closer to reality.

**Comment by OmarEmaraDev** [comment]
I just committed MIDI nodes to master, finally. Many thanks to both of you @Clockmender @Patochun!
Of course, if you have any feedback, let me know.

**Comment by Patochun** [comment]
It's a great day. Congrat @OmarEmaraDev. I will check it soon with a new video.
