### ISSUE TITLE
Vertices Amount not equal warning in vertices mode of mesh object output

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1628]
![BUG](https://user-images.githubusercontent.com/55994236/104500887-fbabac80-55ac-11eb-9896-ef8ec0a8f3a7.png)
Mesh object output node creates nothing. Is this a bug?

**Comment by OmarEmaraDev** [comment]
Probably not a bug. To clarify, the Vertices mode doesn't create vertices, it assumes vertices already exist in the chosen mesh and sets their locations using the input vector. In your case, the mesh is empty, so you need to create a mesh with the same numvber of input vertices.

**Comment by Gerstmann-Bradley** [comment]
> Probably not a bug. To clarify, the Vertices mode doesn't create vertices, it assumes vertices already exist in the chosen mesh and sets their locations using the input vector. In your case, the mesh is empty, so you need to create a mesh with the same numvber of input vertices.

I see. Thanks

**Comment by Gerstmann-Bradley** [comment]
No, wait, would you tell me how to use this mode?
In my idea:
If I were to change the vertices locations, I need to use "mesh object input" to read original locations.
If I output to mesh object output, according to what you explained, I need to use the original object, who feeds the input to "mesh object input".
This will cause a loop, and thus the vertices will be offset each time I execute the node tree.

But in whichever case I can't generate a new object to prevent this loop?

**Comment by Gerstmann-Bradley** [comment]
If we change the vertices data like shown, the mesh will also never come back to its original appearance, because we don't store its original mesh information anywhere.

At the end, I feel like there is no practical use case for this vertices mode. I think "mesh mode" / "Bmesh mode" kind of ideology is much more practical to use.
![mesh object output](https://user-images.githubusercontent.com/55994236/104506054-d621a180-55b2-11eb-8289-1363409630ac.png)

**Comment by OmarEmaraDev** [comment]
You needn't use the original vertices locations, or you can them in a deterministic manner. The main use case for this mode of operation is to improve performance when you know only the vertices locations are changing.

Here is an example where I don't use the original vertices locations, the grid structure is constant, so to improve performance I only set the vertices locations:

![20210113-222825](https://user-images.githubusercontent.com/25300994/104506469-1d795380-55ee-11eb-8084-8b1fdcc6fac6.png)

Here is an example where I do use the original locations, but my node tree is a function of x and y and the result is set to z. x and y are independent of z, so it is okay:


https://user-images.githubusercontent.com/25300994/104507378-5239da80-55ef-11eb-90d1-96e2ed7ca127.mp4

But you really shouldn't use the original locations with this mode just for safety.

**Comment by Gerstmann-Bradley** [comment]
Thanks for the example! I assume you will put them in the manual to avoid misconception.

I still don't think this is practical despite good performance, But I will stop here.
