### ISSUE TITLE
Midi track index can be negative

### ISSUE THREAD

**Issue by Patochun** [JacquesLucke/animation_nodes#1634]
![image](https://user-images.githubusercontent.com/38781639/104626804-98964480-5696-11eb-9b61-45a98a6df11e.png)

**Comment by Patochun** [comment]
Apparently for my midifile track index -6 equal index 1

**Comment by OmarEmaraDev** [comment]
The Get List Element node is not really related to MIDI nodes, it is a generic AN node. When Wrap is enabled, negative indices count from the end of the list. So -1 means the last track, -2 means the second to last track, and so on. If the index is our of range an empty Track is returned.

**Comment by Patochun** [comment]
Ok I understand my mistake
