### ISSUE TITLE
MIDI Track Info node - Values seem to be mixed

### ISSUE THREAD

**Issue by Patochun** [JacquesLucke/animation_nodes#1635]
![image](https://user-images.githubusercontent.com/38781639/104627428-4b66a280-5697-11eb-81c6-213fd54446a0.png)

**Comment by Patochun** [comment]
Name content is Notes
Index content is Name
Notes content is Index

**Comment by OmarEmaraDev** [comment]
That's weird. Seems to be working fine here.

![20210114-194829](https://user-images.githubusercontent.com/25300994/104628455-eadc6300-56a0-11eb-8aac-b08a2fe5dd10.png)

**Comment by OmarEmaraDev** [comment]
Can you investigate this?

**Comment by Patochun** [comment]
Yes I will do. It's Weird.

**Comment by Patochun** [comment]
![image](https://user-images.githubusercontent.com/38781639/104632486-0b56ee00-569e-11eb-824d-f2d3d59ea16f.png)

**Comment by Patochun** [comment]
![image](https://user-images.githubusercontent.com/38781639/104632526-1c076400-569e-11eb-8791-29b156171de7.png)

**Comment by Patochun** [comment]
The remix occurs when I connect one track. Where am I wrong?

**Comment by OmarEmaraDev** [comment]
My bad. It was a wrong copy expression. Will fox that. By the way, in the Advanced Node Setting of the Get List Element node, uncheck Copy Element. This should improve performance a bit since a copy is not needed.

**Comment by OmarEmaraDev** [comment]
Fixed in ee07101. Thanks for the report!
