### ISSUE TITLE
Proposal: vectorize "delay time" & "animate" nodes

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1638]
The attached is an example of what I mean. **I mostly want vectorization in "delay" in delay time, & "time" input in animate node**.
(Indeed, more vectorizations will be welcome but I don't think they will be too useful; so if these are too heavy to implement then I won't ask for it.)
(Delay in delay time is also tricky, because technically we can use math node instead.)

I usually use this method to create a sequential event, examples include "flip book pages", etc.
Here I am not talking about "delay action" because we can't decompose action,
while numerical control in "animate float", "animate vector", etc. are very helpful as they can do math in animation nodes for certain purposes. 

Other insights will be welcome.
![Example](https://user-images.githubusercontent.com/55994236/104715599-c316ea80-56f4-11eb-882e-5f0ca1549680.png)

**Comment by OmarEmaraDev** [comment]
Animate nodes are Mix Nodes with some extra sugar, so it shouldn't be too hard to implement. Since it is not too important, this could be a good first contribution for a developer.
