### ISSUE TITLE
Color Mix node factor ranges only from 0.9 to 1.0

### ISSUE THREAD

**Issue by Spiderguy-F** [JacquesLucke/animation_nodes#164]
If I use a color mix node, a factor lower than 0.9 gets treated as 0.

**Comment by og76** [comment]
![color mix](https://cloud.githubusercontent.com/assets/11709974/8993930/c8eb1cce-3710-11e5-8212-36a41f2e80a4.PNG)
works here 
(only the alpha has to be set with combine rgba, in the color selector it does not appear)

**Comment by Spiderguy-F** [comment]
I used it for set vertex color, I think not seeing a difference had to do with my Cycles material. Thanks for double checking, I couldn't reproduce the issue, so case closed.
