### ISSUE TITLE
Get socket maxValue from an input

### ISSUE THREAD

**Issue by LaurineCapdeville** [JacquesLucke/animation_nodes#1640]
We are trying to create a dynamic maximum value for one of our nodes. We would like the input integer to be constraint between 0 and the number of elements in the second input.
Here is the code of the node we want to create (we know that  maxValue = input.num_qubits in the second input is not possible, so we would like to find out how to do it, probably in the execute function?)

```python 
import bpy
from qiskit import *
from animation_nodes.base_types import AnimationNode

class QuantumGateHNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_QuantumGateHNode"
    bl_label = "Quantum GateH"

    def create(self):
        self.newInput("Quantum Circuit", "Input Circuit", "input")
        self.newInput("Integer", "Qubit Index", "qubit_index", value = 0,  minValue = 0, maxValue = input.num_qubits)
        self.newOutput("Quantum Circuit", "Output Circuit", "output")

    def execute(self, input, qubit_index):
        try:
            input.h(qubit_index)
            return input
        except:
            return
```
Thank you in advance!

**Comment by OmarEmaraDev** [comment]
You are right in that the input can only be accessed in the execution function, so it is not possible to control something in the `create` function with something in the execution function. But even if it is possible, I would advice against it for a number of reasons which I can list if you want.

Moreover, notice that setting `maxValue` only controls the UI, it doesn't guarantee that maximum if the user supplied the input through a link to another node. So you still have to make sure of that in the execution function.

Your best option is to warn the user about such inputs. For instance:

```python
import bpy
from qiskit import *
from animation_nodes.base_types import AnimationNode

class QuantumGateHNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_QuantumGateHNode"
    bl_label = "Quantum GateH"
    errorHandlingType = "EXCEPTION"

    def create(self):
        self.newInput("Quantum Circuit", "Input Circuit", "input")
        self.newInput("Integer", "Qubit Index", "qubit_index", value = 0,  minValue = 0, maxValue = input.num_qubits)
        self.newOutput("Quantum Circuit", "Output Circuit", "output")

    def execute(self, input, qubit_index):
        if qubit_index > input.num_qubits:
            self.raiseErrorMessage("Qubit Index can't be larger than the number of qubits in the input.")
        try:
            input.h(qubit_index)
            return input
        except:
            self.raiseErrorMessage("Failed to do quantum magic.")
```

**Comment by LaurineCapdeville** [comment]
> You are right in that the input can only be accessed in the execution function, so it is not possible to control something in the `create` function with something in the execution function. But even if it is possible, I would advice against it for a number of reasons which I can list if you want.
> 
> Moreover, notice that setting `maxValue` only controls the UI, it doesn't guarantee that maximum if the user supplied the input through a link to another node. So you still have to make sure of that in the execution function.
> 
> Your best option is to warn the user about such inputs. For instance:
> 
> ```python
> import bpy
> from qiskit import *
> from animation_nodes.base_types import AnimationNode
> 
> class QuantumGateHNode(bpy.types.Node, AnimationNode):
>     bl_idname = "an_QuantumGateHNode"
>     bl_label = "Quantum GateH"
>     errorHandlingType = "EXCEPTION"
> 
>     def create(self):
>         self.newInput("Quantum Circuit", "Input Circuit", "input")
>         self.newInput("Integer", "Qubit Index", "qubit_index", value = 0,  minValue = 0, maxValue = input.num_qubits)
>         self.newOutput("Quantum Circuit", "Output Circuit", "output")
> 
>     def execute(self, input, qubit_index):
>         if qubit_index > input.num_qubits:
>             self.raiseErrorMessage("Qubit Index can't be larger than the number of qubits in the input.")
>         try:
>             input.h(qubit_index)
>             return input
>         except:
>             self.raiseErrorMessage("Failed to do quantum magic.")
> ```

Thank you very much!

**Comment by OmarEmaraDev** [comment]
Closing this for now. Feel free to reopen or open a new issue if you want anything else.
