### ISSUE TITLE
Cannot render with animation nodes with spline node

### ISSUE THREAD

**Issue by seemon2** [JacquesLucke/animation_nodes#1647]
Hi there,
I managed to get this "tracer effect" working with Kuldeep Singh tutorial ..  on tracer effects using spline function.
I am using Blender 2.91 and with AN+EN v2.2 with link provided by Bradley ..
 https://github.com/3DSinghVFX/animation_nodes/releases

It my attempt put his tracer on a 3d model (lady dancing), I am able to see this tracers (I setup in gold color) on 3D view but I just can't render (output F12) this gold colored tracers.
Is there special output node or other nodes need to be setup to get this "tracers" to get rendered.?

![image](https://user-images.githubusercontent.com/20814653/105118907-6320a980-5b23-11eb-9867-6629d9796d75.png)

**Comment by OmarEmaraDev** [comment]
Can you share a minimal file that reproduce the problem?

**Comment by seemon2** [comment]
Hi,

Here's the simple version using just suzanne ...
If you click play, you can see the spline on 3D view .. but when press F12
to render .. the spline (gold color) will not appear.
The nodes setup is in "AN" workspace ..

This is really the original file shared by Kuldip Singh .. with minor tweet
in "gold" for the spline and added some lightings.

**Comment by 3DSinghVFX** [comment]
@seemon2 Hi. It did not appear in render because it has zero Bevel Width, so have to add Bevel Width to the spline.

**Comment by seemon2** [comment]
hi .. I am a NOOBS on animation node.

Any help how to add Bevel Width to the spline??
I found there's node for Bevel Edge node but it only accept "mesh" .. but I
think the spline is curve?
Your advise please.

**Comment by seemon2** [comment]
Hi Kuldeep,
I think I found the answer ..
[image: image.png]


see effect on final output .. hmm wonder how to change each spline with
different colors? created from different vertices .. which I saw in your
final demo.

[image: image.png]

**Comment by OmarEmaraDev** [comment]
I guess this is resolved. Feel free to reopen if needed.
