### ISSUE TITLE
Mac version still old?

### ISSUE THREAD

**Issue by luckychris** [JacquesLucke/animation_nodes#1648]
I had a problem with the latest release download on a Mac. 

The problem description is here: https://blender.stackexchange.com/questions/208769/animation-nodes-error?noredirect=1#comment352457_208769

As georgius wrote, the fix was already made. Was it also made for mac? Because when i changed the python file as he linked in the answer, my error was gone.

**Comment by OmarEmaraDev** [comment]
Fixed in 7027125. Thanks for the report!
