### ISSUE TITLE
Working with multiple scenes - Mesh does carry over but modifiers are ignored even with the setting active

### ISSUE THREAD

**Issue by 8BitsGotBite** [JacquesLucke/animation_nodes#1653]
I have a blend file with multiple scenes inside. In scene #1 I manipulate an object and apply modifiers to it. Then I want to grab the mesh component with animation nodes for scene #2, manipulate it further and eventually output it into a new object. The basic mesh carries over fine but modifiers are ignored even when the setting is active in the "Mesh Object Input" node. The hidden "Scene" option doesn't seem to do anything either.
[an.debug.multipleScenes.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/5887818/an.debug.multipleScenes.blend.zip)

**Comment by OmarEmaraDev** [comment]
Unfortunately, this is a Blender limitations. The *Use Modifiers* option only accounts for **evaluated** modifiers. Blender doesn't evaluate the modifiers on objects that are not part of the active scene or not enabled in the current view layer. So there is currently no way to do that in Blender. Though Geometry Nodes (GN) might open up some possibilities in that regard, and we might work on integrating AN with GN soon.

**Comment by 8BitsGotBite** [comment]
Thanks for clearing that up for me so fast. Have to work around this limitation then and keeping my fingers crossed for that AN/GN integration. Sounds like a dream coming true ^^.
