### ISSUE TITLE
Proposal: be able to set plane for "distribute circle"

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1658]
The circle is generated in XY plane. it perhaps will be more convenient if we can set it to other like XZ/YZ plane.
This maybe a minor thing since you can accomplish with two additional nodes, but as the time goes I think it would be more convenient to set it at the first place without additional nodes.
What do you think?

**Comment by OmarEmaraDev** [comment]
I think that's fine. I will leave this as a good first contribution.
