### ISSUE TITLE
add adaptive polygons node (mesh deform on quads)

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#166]
adaptive poly is the name of addon and sverchok node, but something with quads is better, cause it's working well only with quads.

have a mesh to instance and a quad based mesh for using polys. the mesh will not only be instanced for each poly but also deformed accordingly so that it results in a connected surface

examples in the forum from this post on
http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2909445&viewfull=1#post2909445

my script node blend here (just deforming 1 mesh for 1 quad, the rest is loops and all)
[animation fun 88d test poly deformation.blend](https://drive.google.com/file/d/0BzzAoBwXO8dsZGhkSGNDeDdUX28/view?usp=sharing)
the file has 2 layers,
layer 1 , just play to see 1 quad..
layer 2, have to enable the red boolean node, kinda slow .. too see that in the pic below (play frames..)

ps. missing the extra z deformation from verts normals, but there is way more to work on it than that

![quad deform](https://cloud.githubusercontent.com/assets/11709974/8918696/53cf5ba8-34c2-11e5-91a3-5bbedc22a48b.PNG)

**Comment by og76** [comment]
I've started putting this into a node and bumped into **big issues** regarding object data
I used the bound_box prop like in the script and I barely made it work with

        try:
            obb = eval(object.bound_box)
        except:
            obb = None

is there another way than eval? I saw this in obj attributr and expression nodes
should I make a special def for this instead of using in execution?

I'm still trying to use the code from mesh info, but I still have to digg ..

**Comment by JacquesLucke** [comment]
what exactly should this do in your opinion: eval(object.bound_box)?

**Comment by og76** [comment]
I needed : 

    obb = object.bound_box

but it's not working and freeze the whole tree. I managed to make it work then using

    try:
        obb = eval(object.bound_box)
    except:
        obb = None

then I use it to determine some  stuff relative to bbox:

    minX = obb[0][0]
    maxX = obb[6][0]
etc

It happens just like with object.data ...

**Comment by og76** [comment]
I've opened the node again and got it back to plain
obb = object.bound_box
and it seams to just work! ha?

why was it then not workin in the beginning? I was working while still having a script node with similar code. but really?

**Comment by og76** [comment]
I got back to these files ( the node version) only to discover they just don't work, with or without eval 
At a certain point (above) it did work somehow...
The script node version always works.

there is a strange halt in the whole tree (like sometimes happens if u connect a loop in a wrong way) with no warning or error when I connect the node. The moment the node is disconnected, no halt..

I'll have to dig more into how mesh data should be handled, by imitating mesh info node or others...

**Comment by og76** [comment]
**First Working Version**
[ mn_adaptive_quad.py](https://drive.google.com/file/d/0BzzAoBwXO8dsV3ZjZ0R0YUZMaTQ/view?usp=sharing)

http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2922768&viewfull=1#post2922768
![adaptive quad 1](https://cloud.githubusercontent.com/assets/11709974/9347539/a3136f38-4633-11e5-8486-c85a50388d8b.PNG)

questions:
-is the design/place in the nodes setup right? in the AN spirit?
-naming. Ideas?
-how can this be optimized in itself, but also in simpler tree setup

issues:
-I still don't get in full what I was doing wrong before. And now it's workin
-I should clean the code. Just had thrown it all in execute ... maybe some should go in def
-I should see about inline exe

**Comment by JacquesLucke** [comment]
Just some comments, I didn't check it intensively yet because I'm working on the refactor.

- variable names should start lower case. eg 'DeformedLocations' -> 'deformedLocations' 
Capitalized Words are used  for class names
-  should len(QV) > 2 be > 3?
- some variable names are too short in my opinion (I don't know what they do) but sometimes that is ok
- there should be spaces around operators
- you don't need to use inline execution for this node, it wouldn't benefit much from that.
- please check were division by zero exceptions can be raised

Otherwise it looks quite well already! And the results are stunning! :)

**Comment by og76** [comment]
- Quads are the *recommended*, not limit (and I don't wanna make it an option). Tris are acceptable, see the spheres. You can even model to work with tris only...The 56.. poly are less ok as they leave a gap.
*But I don't like the way I escape 1 2 verts with default -1>1 square ...*
- variables like rx, q0, qdef, ndef etc? r =ratio, q0 are quad vert.co, n0 are normals for q.. there was lot of math there so I felt like having it short
- yes, x - y ..., 
- I'll check /0

**questions:**
-should some parts be in **def** instead of **execution**? **Is that more efficient?** Or a class of sorts?
 I keep thinking that I do heavy repetitive task here and inside a loop (u need many instances to look great)
Original script and sverchok (very alike) do that for those interpolation calc. And then in exe they just do that vor v in VL.
```
def lerp(a,b,t):
    return a + (b-a)*t
    
def lerp2(v1, v2, v3, v4, v):
    v12 = v1 + (v2-v1)*v.x
    v43 = v4 + (v3-v4)*v.x
    return v12 + (v43-v12)*v.y
    
def lerp3(v1, v2, v3, v4, v):
    loc = lerp2(v1.co, v2.co, v3.co, v4.co, v)
    nor = lerp2(v1.normal, v2.normal, v3.normal, v4.normal, v)
    nor.normalize()
    return loc + nor*v.z

and then in exe
...
                for v in me1.vertices:
                    new_verts.append(lerp3(vs[0], vs[1], vs[2], vs[last], v.co))
```

(truth is they do have a lot dedicated to mesh creation, that I leave to normal AN ways)

- should I keep names of sokets like this?  or use more suggestive *brush vertices, canvas poly*, like JoseConseco suggested in his setups? or others?
- is the tree logic ok? initially I had it for 1 vertex, but ended with 2 loops needed, to create the vector list outside the node. That was too much. And not intuitive.
- is the *mesh creation/append* inside the same loop less efficient than having another loop for it?
Is there a more efficient way than appending meshes?

I will explore having obj instancer and deform the meshes , but that is less efficient than 1 obj and connected (remove doubles) mesh

ps. I'm already thinking about an even insaner node, but that is separate..

**Comment by JacquesLucke** [comment]
putting stuff into extra functions won't result in a speedup but in much better readability. In fact it will slow down the execution but in most cases this is negligible. Only when you call a specific function a lot of time (>1000) in a short time you should care about this. Everywhere else comes readability first.

Cannot say how repetetiv your code is atm. I'm currently rewriting the whole execution code + new group implementation... so I cannot go more deeply into this algorithm now.

The socket names are good so far in my opinion. A better documentation system would be nice again to explain users how it works......
btw: is the matrix input needed when I will implement that the mesh info node outputs data in world space?

hm no, i think there is currently no more effecient way to join meshes..

**Comment by og76** [comment]
hm,
- >1000 will be very slow, but I guess cause of heavy mesh data not a vector list ...
- I do same thing for all verts. But the question should be: **Is there a way to optimize considering that I will use this inside a loop?** Can it make a difference for the tree that contains it?
- mesh info node data in world space option? like the splines? ok
then **probably not needing that matrix**.  Maybe it will remain hidden? u can use that for other inputs, the alternative being to have another loop to alter the resulted vector list. Did that for some animated purpose...

- meshes (and instancer) are a subject in itself  ... maybe we should also have nodes to just deform a mesh vert without recreating all ... for some deforms is more efficient than recreating data
*Different topic ..*

**Comment by og76** [comment]
this is now modified for the refactor now, with respective 2 more sockets to get the verts normals

as per pull request #233 

for now I guess this is it, but I hope for some other future approach on the mesh data
(well, if I had a clear vision on this I'd say...)

![acref1](https://cloud.githubusercontent.com/assets/11709974/10318865/0d1db1de-6c74-11e5-8a37-2f3620d70981.png)

**Comment by JacquesLucke** [comment]
Not sure if we should wait with this node until we have a clear vision..
I will need some more time for that decision..

**Comment by og76** [comment]
ok.

fwiw, I don't think is worth the wait, unless it's a quick solution. 
Any further change will only simplify this, while the mesh is about much more.

and it would be cool to have it for the conference ;)
