### ISSUE TITLE
Expression node disconnects output to Animate Float input when saving and opening on different OSes

### ISSUE THREAD

**Issue by imacj** [JacquesLucke/animation_nodes#1661]
Hi,

I primarily run Blender on my Macbook Pro running 10.15 Catalina and Blender 2.91.2 and have recently been using a new Windows 10 machine running Blender 2.91.2 for some of my Blender work.

I have the latest Animation build installed on both computers, 2.2.2.

Here is my basic node setup for the test scene, an expression node with the output connected to the inputs of almost all of the Animate Float node, as shown below.
![basic node setup](https://user-images.githubusercontent.com/79052050/107881385-2346ab00-6eb2-11eb-8ad1-84ebf952f595.png)

However, opening this same file on a Mac device shows that the expression node disconnected everything expect the time and duration inputs.
![open on a mac](https://user-images.githubusercontent.com/79052050/107881513-b7b10d80-6eb2-11eb-825f-7c5e4896d1f8.png)

I've also noticed this problem works in reverse, if I have this node setup all connected up, save and open on my Mac it will cause the same issue.

I am unaware if this problem also occurs within Linux.

I have also attached the test file that I used. All of the nodes are connected and this was saved using a Windows computer.
[bug_problem.zip](https://github.com/JacquesLucke/animation_nodes/files/5978005/bug_problem.zip)

Same file but saved with a Mac:
[bug_mac.zip](https://github.com/JacquesLucke/animation_nodes/files/5978011/bug_mac.zip)

Thank you,
iMac

**Comment by OmarEmaraDev** [comment]
This is actually a problem across versions. The Mac screenshot uses a more modern AN version, in that version we changed some things in the Animate node that was backward incompatible. If you open the terminal, Animation Nodes will tell you about such changes to do the node tree so that you can correct them.
