### ISSUE TITLE
cannot install animation nodes + extra nodes

### ISSUE THREAD

**Issue by luckychris** [JacquesLucke/animation_nodes#1663]
I have no problem installing animation nodes. It just happens if i try to install animation nodes + extra nodes from here https://blender.community/c/graphicall/phbbbc/.

The error is: unsafe use of relative rpath libz.1.dylib in .....

I am using a Macbook Pro with MacOS Big Sur.
Blender 2.93 alpha (from yesterday)

**Comment by OmarEmaraDev** [comment]
Extra nodes is not an AN extension, it is an AN fork. You can't install both at the same time.

**Comment by luckychris** [comment]
i did not install it both. I just wanted to mention, that AN alone works. Hoped that might help you find the problem.

**Comment by OmarEmaraDev** [comment]
Ah I see. I though you meant you installed both at the same time. You should report this in https://github.com/3DSinghVFX/animation_nodes instead.

**Comment by luckychris** [comment]
oh sorry, i will
