### ISSUE TITLE
Animation Nodes cannot be installed on Blender 2.92, 2.93 none

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#1666]
<img width="658" alt="Screen Shot 2021-02-17 at 2 58 31 pm" src="https://user-images.githubusercontent.com/3952687/108154238-ad03ac00-7130-11eb-8fef-394f441be71f.png">

I am on Mac, I cannot seem to be able to install Animation Nodes 2.92 and up. 

Latest one complaint that I need to use 2.93, but 2.93 is weird right now I cannot install AN, SV, maybe Python difference....

**Comment by OmarEmaraDev** [comment]
I believe the MacOS issues were already solved and new builds should work, see T85624.

**Comment by gameLvr85** [comment]
I am getting the same error on windows, cannot install on blender v29.1.2/2.92. Asking for v2.93.

**Comment by OmarEmaraDev** [comment]
@gameLvr85 We no longer make daily builds for Python 3.7 and Blender 2.91/2.92. Either use non-daily builds of AN or use daily 2.93 Blender builds.

**Comment by OmarEmaraDev** [comment]
We added back Python 3.7 builds for Blender 2.91/2.92 in the website. But those builds will no longer be updated.

**Comment by enzyme69** [comment]
<img width="1353" alt="Screen Shot 2021-02-21 at 2 56 09 pm" src="https://user-images.githubusercontent.com/3952687/108615145-29f69480-7455-11eb-9a91-2a90908c63e9.png">

Ok this works.... 2.92 then.
