### ISSUE TITLE
Convert a text to a vector, a list of integers?

### ISSUE THREAD

**Issue by procedural** [JacquesLucke/animation_nodes#1667]
Anyone knows how to convert a text with 3 floats to a vector? Can't figure out the syntax, for some reason, I get "Conversion Failed".

![](https://user-images.githubusercontent.com/28234322/108401300-42846600-722d-11eb-8008-98b8d86266c9.png)

**Comment by procedural** [comment]
Also, a list of integers?...

![](https://user-images.githubusercontent.com/28234322/108402350-6c8a5800-722e-11eb-8913-e541595f9934.png)

**Comment by procedural** [comment]
AN 2.1, Blender 2.83.12 LTS

**Comment by OmarEmaraDev** [comment]
The convert node doesn't know how to do that. You have to parse the string yourself. One way to do that is as follows:

![20210218-202358](https://user-images.githubusercontent.com/25300994/108402839-b66f4000-7226-11eb-88b3-0ab17efd2e9a.png)

**Comment by procedural** [comment]
> The convert node doesn't know how to do that.

I see, thanks!

Will it be added in future, or I can close this issue?

**Comment by procedural** [comment]
Also, would be cool if on unsupported conversion types it'd said "Unsupported Type" instead of "Conversion Failed", or not list them at all...

**Comment by OmarEmaraDev** [comment]
It will not be added, such conversion is too specific to implement as a general conversion rule.

**Comment by procedural** [comment]
> It will not be added, such conversion is too specific to implement as a general conversion rule.

Isn't a text with numbers to a list of AN numbers is a common conversion case, though?

**Comment by OmarEmaraDev** [comment]
I wouldn't consider it so. How about using other delimiters like `(1, 2, 3)`, `(1 2 3)`, or `1 2 3`? There are many ways to represent a list of numbers in text, Animation Nodes doesn't know about any of them, so we will need to check if the text satisfy any of them, then parse it accordingly. Hence why I said it is too specific. Moreover, the Convert node does conversion, not parsing, so something like this wouldn't fit anyways.

**Comment by procedural** [comment]
I see, thanks! Closing then.
