### ISSUE TITLE
Crashes when rendering animation! UI bug??

### ISSUE THREAD

**Issue by sjonsjine** [JacquesLucke/animation_nodes#1668]
Hi, whenever I start with Animation Nodes again, I've seem to have forgotten how often it crashes when rendering an animation. Sometimes after 5, sometimes after 25 frames. Today I found a workaround https://www.youtube.com/watch?v=JfuQPWzVN9k&t=4s but my question is, can this be solved? This bug is here already for years! Using latest AN version and Blender 2.912

Thanks! Really thanks a lot!! 

Freddy Peters

**Comment by OmarEmaraDev** [comment]
You can solve it by locking the interface. Other than that, I am afraid we can't do anything about it.

**Comment by OmarEmaraDev** [comment]
See #1585.
