### ISSUE TITLE
Text (trim) animation do not update while rendering

### ISSUE THREAD

**Issue by Dihotom** [JacquesLucke/animation_nodes#1669]
Text animation do not update while rendering both cycles and eevee in blender 2.92, but works fine in 2.83-2.91 and 2.93. here is example 
[text_render.zip](https://github.com/JacquesLucke/animation_nodes/files/6035610/text_render.zip)

**Comment by OmarEmaraDev** [comment]
If it works fine in the latest version (2.93), then there probably isn't much we can do. 2.92 is already in a very late BCon phase.
