### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by aungphyop2017** [JacquesLucke/animation_nodes#1670]
Hi there,

I could not install the animation_nodes properly even though I have installed vc_redist.x64 on my computer. Report: Error describes **"there are multiple versions of add on installed"**.  But I could not file any duplicated versions in the file path. Let me know how I can solve this issue.

![Animation_nodes_installation_error](https://user-images.githubusercontent.com/79825572/109471256-e9bf9380-7a9e-11eb-819b-580ff29a13be.png)

https://drive.google.com/file/d/1e8WnoXMk7RVmK0OMauQBETyLI3m5UibF/view?usp=sharing

**Comment by OmarEmaraDev** [comment]
I can't access that drive link.
Are there any addons with a name containing `animation` and `nodes` at the same time? Even if it doesn't exactly match `animation_nodes`.

**Comment by aungphyop2017** [comment]
Dear Omar Emara,

I have only addons below. How shall I do? Can I change the name of zipped
file? Thanks for your kind support!
[image: image.png]

[image: image.png]

**Comment by OmarEmaraDev** [comment]
I can't see those images. You have to add the images in Github, not email.

**Comment by aungphyop2017** [comment]
Ok, I will check.

**Comment by aungphyop2017** [comment]
![Uploading Animation_nodes_installation_error.png…]()

Please check it.

**Comment by aungphyop2017** [comment]
![Uploading ani_nodes_error_2.jpg…]()

**Comment by aungphyop2017** [comment]
![ani_nodes_error](https://user-images.githubusercontent.com/79825572/109795068-e7973980-7c44-11eb-8a06-4ca3d05a60ec.jpg)

**Comment by OmarEmaraDev** [comment]
I meant inside the addon directory where Animation Nodes is installed. Are there any files/folders with a similar name?

**Comment by aungphyop2017** [comment]
No, it doesn't.

**Comment by OmarEmaraDev** [comment]
There are multiple locations where an add-on can be stored. Can you check all of them?
https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html

**Comment by aungphyop2017** [comment]
Thanks, I'll check them out.

**Comment by he9800** [comment]
Hi all
I tried to install the Animation Node but got error 
I tried many times
I use Blender 2.92

**Comment by OmarEmaraDev** [comment]
@he9800 What is the error exactly?

**Comment by he9800** [comment]
I tried to install it but gave me error ..,,

**Comment by he9800** [comment]
I tried to install Animation Node but gave me error

**Comment by OmarEmaraDev** [comment]
@he9800 I get that, but what is that error? Can you provide a screenshot or a paste of the error message?

**Comment by he9800** [comment]
Oki when i’ll open my pc ‘ll provide it to you

**Comment by OmarEmaraDev** [comment]
@he9800 Lets continue this in #1700.
