### ISSUE TITLE
Proposal: Vectorize "transform" series of nodes

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1671]
**Not an urgent proposal**. But I think it will very useful to have these at some point.
Also it seems if people don't propose, certain development will never be made...

**In terms of priority, I mostly recommend "Vector" & "Spline"**;
and "matrix" will be the least to consider since we have "offset matrices".
(To rotate vectors, we can only use transform, or do a double conversion and then borrow the vectorization from "offset matrix". Thus having vectorization of "Transform Vector" will be the most helpful imo).
The other members in the series can wait. 
Glad we have loop function to help doing all these vectorizations for the time being.

![image](https://user-images.githubusercontent.com/55994236/109573320-d9b6ac80-7abc-11eb-99a2-912c2325cc86.png)

**Comment by OmarEmaraDev** [comment]
Other transform nodes still need to be fully vectorized.
