### ISSUE TITLE
Animation Nodes Crashed Somehow

### ISSUE THREAD

**Issue by L33t-HAXXOR** [JacquesLucke/animation_nodes#1673]
I tried adding a Vector List Math to a noodle going from a Construct Interpolation to a Map Range

The node will appear to work but my animation is no longer triggering
I've tried re-instancing the one object in the scene, reconnecting nodes and reverting to a previous save but nothing has worked.

The Developer panel instructions won't print to the console but give traceback errors. Screenshots attached below.

The "Retry" button is unresponsive.

Thank you for your time

Last successful execution using:
Blender: v2.91.2
Animation Nodes: v.2.2.2

macOS Catalina 10.15.7
<img width="698" alt="System Info" src="https://user-images.githubusercontent.com/31870368/110406503-f10b1200-8047-11eb-872f-7741a7b119be.png">

Print Button and Write Button give these errors:
![Captura de Pantalla 2021-03-08 a la(s) 19 20 57](https://user-images.githubusercontent.com/31870368/110404208-13029580-8044-11eb-8385-4a4547c8fff3.png)
![Captura de Pantalla 2021-03-08 a la(s) 19 21 06](https://user-images.githubusercontent.com/31870368/110404213-1433c280-8044-11eb-95ae-0f3d2e7b603b.png)

[Blend File.zip](https://github.com/JacquesLucke/animation_nodes/files/6105158/Blend.File.zip)

**Comment by OmarEmaraDev** [comment]
I can't reproduce this issue. Reloading the blend file doesn't work you say?

**Comment by L33t-HAXXOR** [comment]
That is correct
Also I was using the Mac build found here:
https://github.com/3DSinghVFX/animation_nodes/releases

**Comment by OmarEmaraDev** [comment]
Can you try the mac build first here first?
https://animation-nodes.com/

**Comment by L33t-HAXXOR** [comment]
That build is what I ended up using and does not give the same issue
Is the wrong place to post that issue above?

**Comment by OmarEmaraDev** [comment]
You should report this there instead.
https://github.com/3DSinghVFX/animation_nodes/

**Comment by L33t-HAXXOR** [comment]
I see! Thank you!
