### ISSUE TITLE
Create Object List From Selection

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#1674]
Create Object List nodes "From Selection" feature does not work as expected.
Previously it took into account the order in which the objects were selected, but now it's not the case.
It seems it does it randomly or by name, I don't know, but it's not in order of selection.

**Comment by OmarEmaraDev** [comment]
Unfortunately, we had to remove the ordered selection functionality in 0f1764e. This was done due to performance concerns, see #1656.
