### ISSUE TITLE
crash when inputting float list to marching squares threshold.

### ISSUE THREAD

**Issue by Yappu** [JacquesLucke/animation_nodes#1675]
This is using AN + EN version, if this is not the right place to bug report please let me know.

Crashing on both 2.92 with python 3.7, and daily build 2.93 alpha with python 3.9, with their respective versions of AN+EN
When inputting the float list and adding a new input blender crashes instantly, or in some seconds later when trying to reproduce.

Blender crash file here
[blender.crash.txt](https://github.com/JacquesLucke/animation_nodes/files/6123567/blender.crash.txt)

**Comment by OmarEmaraDev** [comment]
You should report this here instead:
https://github.com/3DSinghVFX/animation_nodes
