### ISSUE TITLE
Trim spline faloff request

### ISSUE THREAD

**Issue by genesis2303** [JacquesLucke/animation_nodes#1677]
I've been trying to replicate in blender this type of effect:
https://www.youtube.com/watch?v=_ilAMwcqdbM
Turned out that It can't be done with offset of growing splines. Is there any way you could add this feature? For now, I can't find any workaround if it even exists. Tried offset key frames with commotion addon, but it doesn't capture this type of key frames either
https://thumbs.gfycat.com/GenuineJampackedGraywolf-mobile.mp4

**Comment by OmarEmaraDev** [comment]
You can just use a standard Delay Falloff setup as follows.


https://user-images.githubusercontent.com/25300994/111029760-106abc00-8407-11eb-8917-368aa821ab1e.mp4

**Comment by genesis2303** [comment]
OMG so it is possible! Sorry for posting it's here I just was struggling with this since a few days, had no idea how to use this evaluate faloff tried many combinations and nothing seemed to work. Damn so with this faloff I can cascade for example text character spacing? This is just awesome! So is there anything I can't faloff? Thak you!!!

**Comment by dapa5900** [comment]
@OmarEmaraDev

Is it possible to set/randomize each of the replicated spline instances to a different individual thickness somehow? Not per point but for each S shape in your case as a whole segment? Thanks!

**Comment by OmarEmaraDev** [comment]
@dapa5900 You can just use a loop in this case. Maybe we can add an option to change how vectorization is applied in such case. I will think about it.

![20210314-111113](https://user-images.githubusercontent.com/25300994/111063076-76158180-84b5-11eb-909e-4938005aaffb.png)

**Comment by dapa5900** [comment]
@OmarEmaraDev thanks, that's awesome. Yeah, I don't know if that's technically possible but maybe you could add the option to the set spline radius node (and offset spline node) to either affect the points individually or the whole connected segment / branch...?

**Comment by OmarEmaraDev** [comment]
@dapa5900 This sounds reasonable. If you have the time, can you create a new issue with the list of nodes that could utilize such an option?

**Comment by dapa5900** [comment]
@OmarEmaraDev sure I will do this tomorrow. BTW while playing around with the spline nodes I also encountered some issues where I do not know if these are a bug or a feature 😉 what's the best place to ask about or report these?

**Comment by OmarEmaraDev** [comment]
@dapa5900 We just enabled discussions for this repository. You should see it at the top next to Pull Request and Issues. You can open a thread in the Q/A section I guess, lets try it out.

**Comment by OmarEmaraDev** [comment]
We will continue the discussion in the other threads.
