### ISSUE TITLE
Is that possible to "copy setting" when creating a new node tree?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1678]
It's like when we create a new scene, there are options like "New" and "Copy Setting".
(I don't think "Link" is possible in AN, so probably not really matter in this case;
And Full Copy is absolutely pointless imo in AN node tree.)
I am more concerned with copy current node tree settings like "execution method", target scene, etc.
instead of wiping everything out and set things back into default.

What's your opinion?

**Comment by OmarEmaraDev** [comment]
Added in 07372fa. Thanks for the suggestion!
