### ISSUE TITLE
Proposal: Add Set Radius per Segment to appropriate nodes

### ISSUE THREAD

**Issue by dapa5900** [JacquesLucke/animation_nodes#1679]
Hi @OmarEmaraDev,

Following our discussion on #1677 it would be great if you could add the option to set the radius per connected segment / branch for appropriate nodes to achieve the following effect and thus remove the necessity to create an extra loop setup for this.

![splineRadiusPerSegment](https://user-images.githubusercontent.com/75205162/111121742-580b5800-856d-11eb-8881-86443f6e03eb.png)

Nodes that could benefit from this option would be - to my knowledge - the following: 

Set Spline radius
Offset Spline
Spline From Edges
Spline From Points
Mesh from Spline (Size)

Also, after testing your setup above I realized that tapering the beveled strokes afterwards on the Curve Object Output node with a taper object results in overriding the random radii and resetting all the the radii. Please see here for reference:

https://p7s1-my.sharepoint.com/:f:/g/personal/par0001d_belgium_fhm_de/En5lJlSR5GRDp45M0QQ-bwcB3R6ETOQfZzpstLuzvClvOA?e=7Gcaz6

I think It would be great if the output node together with a taper object could as well knowledge the input radii.

**Comment by OmarEmaraDev** [comment]
For tapering, this seems to be a Blender limitations. I guess we can patch Blender to take the radius into consideration.

**Comment by OmarEmaraDev** [comment]
@dapa5900 We submitted a patch for tapering in [D10779](https://developer.blender.org/D10779). Once this lands in Blender, we will add support for it in Animation Nodes.

**Comment by OmarEmaraDev** [comment]
Implemented in 08dcee4.

I don't think the same concepts apply to the nodes you listed above. There are good reasons why those nodes are implemented like this. As for the Offset node, falloffs are evaluated per point, they can't be evaluated at a "spline", because the evaluation point is not really defined.

**Comment by dapa5900** [comment]
> Implemented in [08dcee4](https://github.com/JacquesLucke/animation_nodes/commit/08dcee43ceb5a1514b8843d4be913a5eaa8d9748).
> 
> I don't think the same concepts apply to the nodes you listed above. There are good reasons why those nodes are implemented like this. As for the Offset node, falloffs are evaluated per point, they can't be evaluated at a "spline", because the evaluation point is not really defined.

Thanks!

**Comment by OmarEmaraDev** [comment]
@dapa5900 The taper mode option was merge today in Blender and should be available in tomorrow's daily build. And the option was added to the Curve Object Output in Animation Nodes in f04abfb.

**Comment by dapa5900** [comment]
@OmarEmaraDev 

Mega! Thanks for that.

Quick question are you actually directly involved in the development of Blender itself as well?

**Comment by OmarEmaraDev** [comment]
@dapa5900 Yes. I mostly work on Cycles, but I also work on other areas as well.

**Comment by dapa5900** [comment]
> @dapa5900 Yes. I mostly work on Cycles, but I also work on other areas as well.

@OmarEmaraDev

Cool. What would you recommend is the best place to propose ideas for blender in general (ideas that potentially also reach you directly... 😉)?

**Comment by OmarEmaraDev** [comment]
@dapa5900 For proposing a general idea, there is https://blender.community/c/rightclickselect/. For feedback on certain ongoing developments, there is usually a thread at https://devtalk.blender.org/c/other-topics/user-feedback/. You may also engage in discussions on https://developer.blender.org/, but don't propose ideas there, the developer portal is for bug reporting and development only.

I am always interested in patching Blender to make Animation Nodes better though, so while I can't promise anything, poking us here might be an option as well. 🙂

**Comment by Gerstmann-Bradley** [comment]
@OmarEmaraDev In case you didn't receive the message, there is a red bar error in taper mode that presents in the newest AN and 2.93 alpha up to date. Would be able to investigate that?

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley Fixed in 61f2365e. Thanks!
