### ISSUE TITLE
Why Convert doesn't work here?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#168]
![convert](https://cloud.githubusercontent.com/assets/494788/8923842/c95e30d6-3528-11e5-904b-567132c06e66.jpg)

**Comment by JacquesLucke** [comment]
You are creating a string in the expression node. To create a vector object you have to write "mathutils.Vector((0,0,0))". But this is not possible atm! Because you don't have access to the mathutils module in the script node. This problem is related to #100

**Comment by LeonCheung** [comment]
I see! Thanks for the nice info.  :)

**Comment by og76** [comment]
hey, it does work! like this: 

    (1.5 ,2.4 ,3.3)
or if u use input that is a vector, like obj location
(the convert will do the vector job for u)

![vector expression](https://cloud.githubusercontent.com/assets/11709974/9023581/50b5238a-38aa-11e5-888c-a1c55c2b8226.PNG)

**Comment by LeonCheung** [comment]
Oops, that's a sorta easter egg?!
