### ISSUE TITLE
Animate *Value* node "Start" and "End" inputs lost 

### ISSUE THREAD

**Issue by Eric-M314** [JacquesLucke/animation_nodes#1682]
If I save a file using Animate Matrix (vector, float etc.) nodes in AN v2.1 for Blender 2.83 LTS all the connections to the "start" and "end" sockets are lost when using AN v2.2 for Blender 2.92.

I tried going from Blender 2.91 to Blender 2.92 and I also tried just using blender 2.92 with both versions of AN (downloaded yesterday and today).

If I try appending the node trees I get errors in the console like this:
>Traceback (most recent call last):
  File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'test'", line 6, in <module>
NameError: name 'startTime' is not defined

And if I try to run it anyway:
>WARNING: link removed
    Tree: 'test'
    From Socket: 'Compose Matrix' -> 'matrix'
    To Socket: 'Animate Data.002' -> 'start'

My current project as a lot of these kind of connections...

Simple blender 2.91 file using AN 2.1.8 (older and not LTS I don't think):
[Blender Animation Nodes Bug Report.001.zip](https://github.com/JacquesLucke/animation_nodes/files/6166800/Blender.Animation.Nodes.Bug.Report.001.zip)

**Comment by OmarEmaraDev** [comment]
Seems those are just backward compatibility breaks. In the terminal, Animation Nodes told you about what happened so that you can correct it and relink.

**Comment by Eric-M314** [comment]
True.  Release notes stating compatibility breakages on the download page would've been nice.

Do you know if it'd be possible to fix these broken node links using python and the information from the terminal?

**Comment by OmarEmaraDev** [comment]
We usually write that in the release notes during the release process.

Yes it is possible. In the example above, this should be something like this:
```
node_tree.links.new(nodes["Animate Data.002"].inputsByIdentifier["startValue"], nodes["Compose Matrix"].outputsByIdentifier["matrix"])
```

**Comment by OmarEmaraDev** [comment]
`start` was renamed to `startValue` so this is what you need to update. The same goes for `end` -> `endValue`.

**Comment by Eric-M314** [comment]
Thank you!
