### ISSUE TITLE
Perforamnce of Object attribute

### ISSUE THREAD

**Issue by mifth** [JacquesLucke/animation_nodes#1686]
Hi,
I found a strange issue with performance. The same attribute. But 50ms vs 70ms!
![image](https://user-images.githubusercontent.com/2251298/112282061-ca7be680-8c97-11eb-8b01-628029135b74.png)
![image](https://user-images.githubusercontent.com/2251298/112282095-d36cb800-8c97-11eb-9aa9-8d780e6c9246.png)

**Comment by OmarEmaraDev** [comment]
The Object Attribute Input node evaluates the object on the active depsgraph, so the extra 20ms is Blender evaluating the object.

**Comment by mifth** [comment]
Thanks for answering. Could we add acheckbox just to take from an objecct?
Something like 'Depsgraph' checkbox.

**Comment by mifth** [comment]
I'm a new user. And I even could not realize such an issue. I guess lots of people too.

**Comment by OmarEmaraDev** [comment]
I am not sure if that's a good idea. All input nodes in Animation Nodes gets their data from evaluated IDs. Users expect the output data to be of an evaluated ID, taking data from original ID would confuse users more I would say. What do you think?

**Comment by mifth** [comment]
That's a problem. I've been working on a realtime tool. I use AN as an engine.
I would like to have an option to get data from an object or depsgraph.
Right now I have to use expression nodes and some visual nodes become useless then. And a lot of people even fon't know about such an issue. (

Could I ask to have such an option, please?

**Comment by OmarEmaraDev** [comment]
What is the application for that? In which cases do you need to access the original data and not the evaluated data?

And if you are writing your own tool, why not just write custom nodes as well?

**Comment by mifth** [comment]
I'm working on a modeling tool. I create cylinders an spheres and update them in realtime.

Why should I write my custom node if AN already have them? I think it's good to have nice performance in realtime. )

**Comment by OmarEmaraDev** [comment]
Added an option in Advanced node Settings in f6d093f. Thanks for the suggestion!

**Comment by mifth** [comment]
Thank you! )
