### ISSUE TITLE
Object Visibility Output  node Crash Blender with many objects

### ISSUE THREAD

**Issue by brothermechanic** [JacquesLucke/animation_nodes#1687]
Hello
Can you give me an advice how to animate collection hide in blender?
I released it with aN node Object Visibility Output node, but this node crashed blender
Please see scereencast - blender crashed when it's rendering
https://user-images.githubusercontent.com/3109995/112459687-037a9080-8d56-11eb-9a6f-6324f2935b85.mp4
(if i disable animation node tree blender don't crash)
(as you can see in my complex scene blender crashed everytime)
This is demo scene
https://mega.nz/file/21Ji1BhR#5Z3rxJBoB9_vGj8EKUcwbsBEbGLX_sPf-Hhhq1KjgNU
![Screenshot_20210325_134007](https://user-images.githubusercontent.com/3109995/112460113-77b53400-8d56-11eb-91de-740750e34098.jpg)
Hope you can get an advice to me or may be fix this is issue

**Comment by OmarEmaraDev** [comment]
Did you try locking the interface?

**Comment by brothermechanic** [comment]
> Did you try locking the interface?
awesome! 
Thank you very much!
