### ISSUE TITLE
Indices of Selected

### ISSUE THREAD

**Issue by mifth** [JacquesLucke/animation_nodes#1688]
Hi,
I would like to request a feature if I may. It would be great to get selected indices through 'Mesh Object Input' or 'MeshInfo' nodes.

![image](https://user-images.githubusercontent.com/2251298/112488052-48221e00-8d8e-11eb-9585-e7db97810dbd.png)

- Selected Vertex Indices (int list)
- Selected Edges (edges list or int list)
- Selected Polygons Indices (int list)

But for performance it would be good to load the data with checkboxes.

Thank you.

**Comment by OmarEmaraDev** [comment]
The Get List Element node can be used in this case. If you are concerned about the performance, we don't read data individually, we read buffers, so that's not possible, or at least will not give you the performance boost you are looking for.

**Comment by mifth** [comment]
Hi,
I mean selected data from edit mode. Get List Element will not help in such a case.
![image](https://user-images.githubusercontent.com/2251298/112518883-e15f2d80-8daa-11eb-9c21-9f89396d5378.png)
![image](https://user-images.githubusercontent.com/2251298/112519249-3a2ec600-8dab-11eb-81ae-228dd3b20308.png)

What do you think about this?

**Comment by OmarEmaraDev** [comment]
Ah I see. I will think about it.

**Comment by 3DSinghVFX** [comment]
@OmarEmaraDev Hi. I have added that as a selection mask in *Mesh Object Input* node: https://github.com/3DSinghVFX/animation_nodes/blob/2dbf1a7e5041042faf31b0d064ee05d37d50dedb/animation_nodes/nodes/mesh/mesh_object_input.py#L34-L36

**Comment by OmarEmaraDev** [comment]
@3DSinghVFX What happens if a constructive modifier is applied when Use Modifiers is enabled?

**Comment by 3DSinghVFX** [comment]
> @3DSinghVFX What happens if a constructive modifier is applied when Use Modifiers is enabled?

@OmarEmaraDev Sorry for the late reply. It works for Use Modifiers as well, the selection update according to modifier:
![Screenshot from 2021-04-26 10-27-57](https://user-images.githubusercontent.com/30294746/116031022-7e4b0a00-a67a-11eb-8a5f-899812faf1bb.png)

![Screenshot from 2021-04-26 10-30-03](https://user-images.githubusercontent.com/30294746/116031062-8d31bc80-a67a-11eb-943f-da9da26c2840.png)

**Comment by OmarEmaraDev** [comment]
Ever used that feature in a practical application before?

**Comment by 3DSinghVFX** [comment]
> Ever used that feature in a practical application before?

Yes. I used for Shortest Path node and in some other projects where I need to separate some part of the mesh.

**Comment by OmarEmaraDev** [comment]
In those cases, why not use something that is less "volatile" like a vertex group?

**Comment by 3DSinghVFX** [comment]
> In those cases, why not use something that is less "volatile" like a vertex group?

@OmarEmaraDev That is also possible. I found this is simpler than the vertex group in these cases.

**Comment by OmarEmaraDev** [comment]
I don't think we should have those outputs in this node. I am open to a new node that extracts those information from an object though.

**Comment by 3DSinghVFX** [comment]
> I don't think we should have those outputs in this node. I am open to a new node that extracts those information from an object though.

Okay.
