### ISSUE TITLE
Performance Issue with unconnected nodes

### ISSUE THREAD

**Issue by mifth** [JacquesLucke/animation_nodes#1689]
Hi,
I've found another performance issue. I just created 10-20 unconnected Object Instancer nodes and found bad performance. I suppose if a node has no input/output then it will not be parsed. Apologies for so many reports but I would like to get good realtime performance. )
Here is my blend file:

[tmp1.zip](https://github.com/JacquesLucke/animation_nodes/files/6207988/tmp1.zip)

![image](https://user-images.githubusercontent.com/2251298/112547103-5d696d80-8dcb-11eb-98b3-012a4a31f6ef.png)
![image](https://user-images.githubusercontent.com/2251298/112547143-6b1ef300-8dcb-11eb-976c-63bde4fdc2a5.png)

**Comment by OmarEmaraDev** [comment]
The node does have inputs and it actually does something. It checks if the amount of instanced objects matches that of the required input, and adds or deletes the difference, this takes time and have an actual effect.

**Comment by mifth** [comment]
But Instances = 0. I assume there should be no calculations then, right? Also, Object Cylinder.001 does not exist. I assume there should be no calculations.

Also, even if I remove Object name there still fps drop to 0.11
![image](https://user-images.githubusercontent.com/2251298/112610810-28423700-8e2e-11eb-8272-5bfca6f98340.png)

**Comment by OmarEmaraDev** [comment]
I don't think there is anything we can do here. Two microseconds per node is hardly a problem as far as I am concerned anyway.

**Comment by mifth** [comment]
Maybe something like this:
If instances == 0 or obj.name not in bpy.data.objects then dont initialize a node(pass it).

What do you think about it?

I always think about perfornance. I suppose everything should be with light speed. Especially, for big projects.

**Comment by OmarEmaraDev** [comment]
`instances` is an input, not a property, so its value can come from somewhere else, so a simple check like this wound't work. I guess we could check if it is linked or not, but then again, it is probably not worth it, a zero count or an empty object is not the base case anyways.

**Comment by mifth** [comment]
If it saves performance it would be worth.

**Comment by OmarEmaraDev** [comment]
If we employ that logic, then adding more checks to save performance in a special case would slow down the base case and then we wouldn't have saved performance after all.
