### ISSUE TITLE
Ctrl + x from node wrangler proposal

### ISSUE THREAD

**Issue by genesis2303** [JacquesLucke/animation_nodes#1694]
During the process of trying things out I often take some node and delete it to replace it with another, is it possible to bring to AN this functionality from node wrangler? In node wrangler connection stays intact after deleting in between node with this method. If we can drag node to connection and AN knows where to connect it, why can't we remove it similar way?

**Comment by OmarEmaraDev** [comment]
I am not sure how this works yet. Perhaps we just need to assign `internal_links`. We will look into it.

**Comment by OmarEmaraDev** [comment]
Blender doesn't allow that at the moment. So we will have to patch Blender.

**Comment by genesis2303** [comment]
Ok then this is more loose suggestion for future anyway, for now I'm just really waiting for loopable vector noise, since we can now do instancing with GN we could go crazy lvl of geometry even on my old rig, this is The feature, time difference between 120 frames loop and 10-20 seconds renders without it is pretty significant. Thank you for all your efforts to make AN better ;)

Also is there a way to dynamically change color when instancing with GN?
https://i.imgur.com/yAgof9p.png

**Comment by OmarEmaraDev** [comment]
@genesis2303 Haven't really looked into GN yet. Maybe @3DSinghVFX can help you here.

**Comment by 3DSinghVFX** [comment]
> Also is there a way to dynamically change color when instancing with GN?
> https://i.imgur.com/yAgof9p.png

@genesis2303 Hi. Are you using the target object's vertices for instancing in GN?

**Comment by genesis2303** [comment]
> > Also is there a way to dynamically change color when instancing with GN?
> > https://i.imgur.com/yAgof9p.png
> 
> @genesis2303 Hi. Are you using the target object's vertices for instancing in GN?

Here is full setup, with GN instancing I could throw few of this kind icospheres at my potato xeon 1230 (sth like 3rd generation i7) and R9 390 and viewport works like a charm GN instancing it's like a miracle, with this kind of performance people could do CG on laptops, but I'm not sure how much we can really control with mixing AN-GN system.

https://i.imgur.com/MJ1N8Ze.png

**Comment by OmarEmaraDev** [comment]
Implemented in [D13386](https://developer.blender.org/D13386). Thanks for the suggestion!

**Comment by Durman** [comment]
I have a question, is it possible now muting custom nodes? I mean is it possible to draw internal links between input and output sockets when the nodes is muted?

**Comment by OmarEmaraDev** [comment]
@Durman Yes, that's what this patch does. Muting custom nodes will now draw the internals links and the internal links will be available through the API in `Node.internal_links`. Though we haven't added support for muting in Animation Nodes yet.

![20211201-144116](https://user-images.githubusercontent.com/25300994/144236516-a8f70d3a-b577-4ed6-a0b5-d989ce9d5aed.png)

**Comment by Durman** [comment]
Cool, it really works though not in exact way which would be expected in Sv.
![2021-12-01_21-29-33](https://user-images.githubusercontent.com/28003269/144285238-356b800f-20db-402b-898e-597b4ad87bff.png)
I really appreciate you contribution into Custom nodes on Blender side. It's a pitty that Blender devs don't have enough time to implement new UI features for Custom nodes too though even if the amount of necessary contribution does not seem big.
Bytheway do you think it would be difficult to bring wide sockets into Custom nodes?
![2021-12-01_22-00-23](https://user-images.githubusercontent.com/28003269/144288331-7a603046-b8e4-4d17-9dab-5ec26e64a0f9.png)

**Comment by OmarEmaraDev** [comment]
@Durman Yes, it only takes the socket type as part of its heuristic. Ideally, nodes should be able to override their own internal links. Jacques hinted in [f5dde382](https://developer.blender.org/rBf5dde382af8078a2e5265e7d6710df7cb1b320a0) that we should do that in the future. So this situation should get better.

Getting wide sockets shouldn't be difficult, however, note that in Blender, this allows multiple inputs, so it is not just a UI thing. If this is what you want, then I can create a patch for 3.1 tomorrow.

**Comment by Durman** [comment]
Multiple input for one input socket is not a problem now. There is [link limit attribute](https://docs.blender.org/api/3.0/bpy.types.NodeSocket.html#bpy.types.NodeSocket.link_limit) which determines possible number of connected links. The problem with this is that connected links to such sockets are unordered. So we have to use repeating last socket approach (like in Group input and Group output nodes) which compare to wide sockets is less compact and much uglier solution. I would really appreciate to get wide sockets in Custom nodes.)) I wish I could to subscribe to your activity on developer blender site but it looks there is no such a thing there.

**Comment by OmarEmaraDev** [comment]
@Durman I created a patch in [D13449](https://developer.blender.org/D13449).

**Comment by Durman** [comment]
So easy? I wish I could know C++ and Blender internals so well. Thanks! Do you think adding socket description in Custom nodes would be same easy? 😊

**Comment by OmarEmaraDev** [comment]
@Durman I am not sure, I didn't realize sockets can have a description. I am look into it after that patch is in.

**Comment by Durman** [comment]
It works only in Geometry nodes now and not for all sockets as far as I know. To see the tip the cursor should be rest on a socket.
![image](https://user-images.githubusercontent.com/28003269/144649158-64f5032c-6c2c-45f4-8f8f-8a85942d016e.png)
