### ISSUE TITLE
local axis-global pivot mode in "offset matrices" rotation?

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1695]
Not sure if this should be a proposal.
Basically I'm looking forward to an easy way for vector Rotate based on the origin & arbitrary axis.
There is "transform vector" node that can rotate vector based on origin, but we can't set an axis for rotation. (Figure.1)
There is also "offset matrix" node that can rotate vector based on global/local axis, but it doesn't contain "local axis - global pivot" mode in rotation method. (Figure.2)

![image](https://user-images.githubusercontent.com/55994236/113410967-a056b280-9382-11eb-8f09-a130017924f5.png)
![image](https://user-images.githubusercontent.com/55994236/113411678-72726d80-9384-11eb-96d4-25851ae2f416.png)

**Comment by OmarEmaraDev** [comment]
You want to rotate a vector around a custom axis with a custom pivot?

**Comment by Gerstmann-Bradley** [comment]
> You want to rotate a vector around a custom axis with a custom pivot?

it will be local axis of the vector (Figure.1), and global pivot (the world origin at [0,0,0]). The desired path is shown in Figure.2.
I just came up with a workaround. If this is difficult to implement I may close this issue.
![image](https://user-images.githubusercontent.com/55994236/113412703-faf20d80-9386-11eb-8d19-a8df51a26d7a.png)
![image](https://user-images.githubusercontent.com/55994236/113412654-d138e680-9386-11eb-848b-ff8fcd1f7418.png)
