### ISSUE TITLE
Selection order is broken?

### ISSUE THREAD

**Issue by dwizor** [JacquesLucke/animation_nodes#1698]
Hello, 
How exactly should selection order work? 
-First i am clicking sort objects>record selection order,
-selecting object in order as in need,
-ESC,
-Sort Objects>OK
-my objects have random indexes and not the order i chose.
It's a bug or am I doing something wrong here?

**Comment by OmarEmaraDev** [comment]
Doesn't seems to be working here as well. I will take a look.

**Comment by OmarEmaraDev** [comment]
Fixed in fe55491. Thanks for the report!
