### ISSUE TITLE
custom node update calls

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#170]
Currently blender calls the update function in each node (if it has one) when something changes in the tree. 
I want to add a layer of abstraction here which allows me to decide myself when to update which nodes.

**Comment by JoseConseco** [comment]
That sounds awesome. Will it work for condition node? Because the way condition nodes work now is:
calculate_input1()
calculate_input2()  #both inputs gets calculated even though we use just input 1 in this loop
if (x=1) then return input1;

and I wish it worked bit more
if (x=1) calculate_input1() 
else:  calculate_input2()   #only one input gets calculated. 

I hope your 'layer of abstraction' will fix this.

**Comment by JacquesLucke** [comment]
At least you will be able to write a minimal script node that executes either one or another group
To do what you describe with nodes is quite difficult from the design point of view.

**Comment by og76** [comment]
even if u enclose it in a group? 
a group could have a boolean to say if to execute or not ..

a hackish way would be to have everything in a frame executing or not.
frames appear with parent/child in blender so it is easy to get a node that halts the frame it contains

Like get my parent (frame) -> get all children (nodes in frame - my brothers!...) ->halt or not

**Comment by JacquesLucke** [comment]
the problem only appears when other nodes depend on the nodes inside the frame or group

**Comment by JoseConseco** [comment]
How about  loops and groups had boolean input 'Execute' ?
By default it would be hidden, and set to true.
It cloud work with new caching. Imagine you have mainLoop and conditionLoop (with active 'Execute' input).

do  MainLoop (for index in X)
            if (index == 1) return 1:     #condition node with output connected to 'Execute' input of  conditionLoop ()
                do conditionLoop ()
               
This way    conditionLoop () would be executed only once, for index==1,  and then on next iteration on MainLoop,   the conditionLoop () would output cached data, from first iteration. It would be usefull for initializing data, but it would be more flexible than that. It would allow switching code execution.
[ if X==1: return (True) ]o-------o[ (Execute) Loop1 ]
[ if X==1: return (True) ]o-------o[ (Execute) Loop2 ]
etc.

**Comment by JoseConseco** [comment]
On second thought it is not so good idea, with execute input. I will think about  it some more. Maybe there is solution in other software, houdini or Cinema

**Comment by JacquesLucke** [comment]
I think the most obvious solution is to have two groups with identical in and outputs. so that a caller node can decide which one it should execute in a specific context.
