### ISSUE TITLE
how can i install animation nodes in blender 3.0

### ISSUE THREAD

**Issue by 225ag** [JacquesLucke/animation_nodes#1700]

**Comment by OmarEmaraDev** [comment]
Are daily builds not working with 3.0?

**Comment by 225ag** [comment]
i dont know how to build them

but i would like to know

A sexta, 16/04/2021, 10:50, Omar Emara ***@***.***> escreveu:

**Comment by OmarEmaraDev** [comment]
Build as in compile? There isn't really a difference between building for 3.0 and for other versions. Which platform are you on?

**Comment by 225ag** [comment]
im on linux
im using animation nodes since 2.83 but i cant work with 2.93 but i work
just fine with 2.92.0
could you tell me what to do to fix this problem

im using the version with pyton 3.7
animation_nodes_v2_2_linux_py37.zip

Omar Emara ***@***.***> escreveu no dia sábado, 17/04/2021
à(s) 10:52:

**Comment by OmarEmaraDev** [comment]
2.93 raised the required python version, this is probably the problem. You probably need the 3.9 version.

**Comment by 225ag** [comment]
and where can i find the animation_node 3.9 file

Omar Emara ***@***.***> escreveu no dia sábado, 17/04/2021
à(s) 15:14:

**Comment by OmarEmaraDev** [comment]
https://animation-nodes.com/#download

**Comment by 225ag** [comment]
i try to install it and i doesnt work i dont have the animation node editor
in 2.93
am i doing anything wrong


Omar Emara ***@***.***> escreveu no dia sábado, 17/04/2021
à(s) 15:24:

**Comment by OmarEmaraDev** [comment]
Do you get any errors? Can you open Blender from a terminal and show us the terminal output after enabling Animation Nodes?

**Comment by 225ag** [comment]
i get tthis after installing the addon but after when i try to open the
editor i cant there is none to open

Omar Emara ***@***.***> escreveu no dia sábado, 17/04/2021
à(s) 16:03:

**Comment by OmarEmaraDev** [comment]
We can't see anything. Can you attach that on Github instead of through email?

**Comment by 225ag** [comment]
how can i do that i have only send you a print screen

Omar Emara ***@***.***> escreveu no dia sábado, 17/04/2021
à(s) 17:08:

**Comment by 225ag** [comment]
this is what happen when i try to open blender in terminal
x-special/nautilus-clipboard
copy
file:///home/ag/Pictures/Screenshot%20from%202021-04-17%2017-20-12.png

**Comment by OmarEmaraDev** [comment]
I still can't see the image. Just copy the text output here. Or use the "Attach files" button at the bottom of the the text field to upload the image.

**Comment by 225ag** [comment]
Omar Emara ***@***.***> escreveu no dia sábado, 17/04/2021
à(s) 17:24:

**Comment by 225ag** [comment]
so ,as you can see i think i installed the addon properly
but when i try to open the animation nodes editor i can't because there is
none
or am i doing something wrong

Alexandre GranAda ***@***.***> escreveu no dia sábado,
17/04/2021 à(s) 18:16:

**Comment by 225ag** [comment]
i've tried on blender 3.0 just now and i got to this screen
can this help you

Alexandre GranAda ***@***.***> escreveu no dia sábado,
17/04/2021 à(s) 18:22:

**Comment by OmarEmaraDev** [comment]
@225ag I still can't see any images. Please use the Github interface instead of email. Email will not attach images.

**Comment by 225ag** [comment]
i'm sorry but i can't open the github where i wrote about this issue
could you please send me a link or other thing for i to know where to send
you the screens i have

Omar Emara ***@***.***> escreveu no dia sábado, 17/04/2021
à(s) 20:20:

**Comment by 225ag** [comment]
ok i find it
this are the screens one of blender 2.93.0
tthe other from blender 3.0

![Screenshot from 2021-04-17 18-15-25](https://user-images.githubusercontent.com/82114777/115149180-d4a4c100-a05a-11eb-93b7-af9a1766b42b.png)
![Screenshot from 2021-04-17 18-33-23](https://user-images.githubusercontent.com/82114777/115149186-dec6bf80-a05a-11eb-8a7e-96621d0ff72c.png)

**Comment by OmarEmaraDev** [comment]
@225ag This doesn't seem to be official Animation Nodes. I am guessing this is Extra Nodes? I would say try official Animation Nodes first to see if those problems are there.

**Comment by 225ag** [comment]
so where can i find animation nodes

A domingo, 18/04/2021, 21:52, Omar Emara ***@***.***>
escreveu:

**Comment by OmarEmaraDev** [comment]
First, make sure to remove any old versions, possibly by deleting the `animation_nodes` directories in your Blender installation. Then install AN from here:

https://animation-nodes.com/#download

**Comment by 225ag** [comment]
ok i downloded your file and in 2.93 this happen
![Screenshot from 2021-04-19 17-08-45](https://user-images.githubusercontent.com/82114777/115268729-7c40f280-a132-11eb-9630-aa71294dad36.png)
![Screenshot from 2021-04-19 17-08-32](https://user-images.githubusercontent.com/82114777/115268808-8fec5900-a132-11eb-9b87-ff3d8cf88142.png)
 and in blender 3.0 this happen
![Screenshot from 2021-04-19 17-06-56](https://user-images.githubusercontent.com/82114777/115268892-a8f50a00-a132-11eb-9c88-a806c566a85e.png)
![Screenshot from 2021-04-19 17-06-37](https://user-images.githubusercontent.com/82114777/115268924-b0b4ae80-a132-11eb-90a0-5f4aa383a293.png)

could you help me solving this
and thank you for all the troubled im making to you

**Comment by OmarEmaraDev** [comment]
What does executing this return?

```
ls /home/ag/.config/blender/2.93/scripts/addons | grep animation | grep nodes
```

**Comment by he9800** [comment]
Is blender 3 come out .. it isn't showing in the blender website just blender 2.92

**Comment by OmarEmaraDev** [comment]
@he9800 It isn't out. But you can download an experimental build from here: https://builder.blender.org/download/

**Comment by Mehdianim** [comment]
I am trying it on Blender 3.0. It installs alright but when I click the checkbox to activate it I get this error message:
![image](https://user-images.githubusercontent.com/45181118/154871721-4e637fb4-1279-4b1e-8d75-f068c963c0e4.png)
I am not sure how to compile manually. Is there a build available for Windows 10 ?

**Comment by OmarEmaraDev** [comment]
@Mehdianim Check the py39 builds here https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build.
