### ISSUE TITLE
Moving a Particle System Emitter

### ISSUE THREAD

**Issue by Majoran99** [JacquesLucke/animation_nodes#1702]
Having a plane throwing out particles and moving it via AN does only move the plane, but not the particles. (Different than when  keyframing the plane)

**Comment by Majoran99** [comment]
when keyframing a motion on x axis:
![w1](https://user-images.githubusercontent.com/82707686/115111329-2d535b80-9f80-11eb-8bb1-524b12fff5b8.jpg)

whereas when moving with AN on x axis:
![w2](https://user-images.githubusercontent.com/82707686/115111337-36442d00-9f80-11eb-9b14-83d7f7fc5ddb.jpg)

would be nice if it was that simple with AN as well to move an emitter.

**Comment by OmarEmaraDev** [comment]
I suspect this is a limitation in Blender that we can't really do anything about. When using ketframes, Blender knows exactly where the object will move and can plan ahead. When Animation Nodes is the one moving the object, it is as if you moved the object yourself, and Blender just resets the simulation.

**Comment by Majoran99** [comment]
thanks for the quick answer.
fun fact (I just discovered)- when I move an empty with AN and apply a driver on the plane following the empty`s x axis movement, it works. So, no keyframes, the initial movement comes from AN.
![Image2](https://user-images.githubusercontent.com/82707686/115115828-d016d480-9f96-11eb-95cb-0d5e1114a33e.jpg)

**Comment by OmarEmaraDev** [comment]
@Majoran99 I see. In this case, I will look into the Blender source and see if we can patch it to allow that somehow.

**Comment by OmarEmaraDev** [comment]
I tried to look into this but couldn't reach anything useful. So I would just consider this as a limitation of Blender.

**Comment by 3DSinghVFX** [comment]
@Majoran99 A workaround for this is: first control a different object (an empty) with AN then use that object for drivers of the *Plane* (Emitter).
