### ISSUE TITLE
rounding + compare bug

### ISSUE THREAD

**Issue by Majoran99** [JacquesLucke/animation_nodes#1703]
doing a comparison after rounding seems not to work properly.
![174782715_10226986442514043_693030702223420479_n](https://user-images.githubusercontent.com/82707686/115111241-9ededa00-9f7f-11eb-86f3-686596dd186e.jpg)

**Comment by OmarEmaraDev** [comment]
Comparing floats may not work as you expect it to. Blender may represent that same number differently. Your best option is to compare if it is close enough. `abs(a - b) < e` where e is a small number.
