### ISSUE TITLE
Bake to Keyframes execution times increase

### ISSUE THREAD

**Issue by imacj** [JacquesLucke/animation_nodes#1704]
Hi,

I have a simple setup to simulate larger execution times. It takes about 3-5 ms to calculate each frame with Animation Nodes alone, no baking. When I go to bake to keyframes, the times start around 30 ms, which is fine, but then gradually creep up to 90 ms. Why do the execution times increase when frames advance? I've seen this happen with my larger Animation Nodes projects and sometimes baking can take up to an hour with 6000 frames (or even longer!). 

I am currently using Animation Nodes 2.2.2, running on Blender version 2.91.2 and Mac OS 10.15.7. I have also tested this on a Windows machine running the same build and also run into the same issues.

Here is a demonstration of what happens when baking to keyframes: 

[https://gyazo.com/a9a1653d7e72d2161db6cc85ad1b48c4](https://gyazo.com/a9a1653d7e72d2161db6cc85ad1b48c4)

Here is the demo blend file:

[SimulatedLongExecTimes.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/6343963/SimulatedLongExecTimes.blend.zip)

**Comment by OmarEmaraDev** [comment]
I can replicate that. I will investigate.

**Comment by OmarEmaraDev** [comment]
Profiling the execution tells me most of the time is spent in Blender's `keyframe_insert`. So this is just Blender being slow at inserting kyaframes, there isn't much we can do here as far as i can tell.

**Comment by imacj** [comment]
I see. Would it be possible to have `Bake to Keyframes` only insert keyframes if the keyframed value changes? I just think that inserting blank keyframes isn't as productive and adding to the internal keyframe list is slowing it down.

**Comment by OmarEmaraDev** [comment]
@imacj That is maybe possible, just not sure if is worth it. Most of the examples I can think of will not be sparse in nature.

**Comment by imacj** [comment]
I can understand that most AN animations have values constantly changing. However, all of my MIDI animations usually have gaps until they play the next note. Keyframing 120+ objects is very data-heavy, so having that optimization when I go to bake is very helpful. 

One of my node trees usually takes 140+ ms to execute (because of all of the MIDI data). I don't think it fully optimized either, maybe you could have a look at it?

**Comment by OmarEmaraDev** [comment]
Have you tried using the *Set Keyframes* node? It gives more fine control over that, so you can insert the key frames exactly where/when you want them.

Feel free to send over the unoptimized file and I will have a look.

**Comment by imacj** [comment]
I was looking into that today, I will have more of a look tonight.

Is there a way I can DM/email you?

**Comment by OmarEmaraDev** [comment]
@imacj You can find my email on my Github profile page.

**Comment by imacj** [comment]
Okay, sent you an email!
