### ISSUE TITLE
Can not output videos for no reasons?

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1711]
I used AN to output videos before normally. But now it can play animation only in rendering mode, can not output video anymore.
![an001](https://user-images.githubusercontent.com/31892214/116839237-25441e80-ac04-11eb-898e-8db78ac75e67.png)

**Comment by OmarEmaraDev** [comment]
Can't why? Does Animation Nodes crash? Does it stay the same over all frames?

**Comment by derekcbr** [comment]
> Can't why? Does Animation Nodes crash? Does it stay the same over all frames?

No crash! Correct, it stays the same over all the frames.

**Comment by OmarEmaraDev** [comment]
Can you share a file that replicate that issue? Can you replicate it on the latest version of Blender and Animation Nodes?

**Comment by derekcbr** [comment]
> Can you share a file that replicate that issue? Can you replicate it on the latest version of Blender and Animation Nodes?

Ok, how to send the Blender file?

**Comment by OmarEmaraDev** [comment]
You can zip it and upload it here by dragging and dropping in the text box or pressing the bottom bar in the text box.

**Comment by derekcbr** [comment]
[an001.zip](https://github.com/JacquesLucke/animation_nodes/files/6417383/an001.zip)

**Comment by OmarEmaraDev** [comment]
I can replicate that unfortunately. Did you try with the latest builds from Blender and Animation Nodes?

**Comment by derekcbr** [comment]
> I can replicate that unfortunately. Did you try with the latest builds from Blender and Animation Nodes?

Yes, Blender 2.92+animation_nodes_v2_2_windows_py37 for 2.92
