### ISSUE TITLE
Animation nodes for Mac ARM M1 processor.

### ISSUE THREAD

**Issue by Gussisaurio** [JacquesLucke/animation_nodes#1722]
Hi there.
I am trying to run animation nodes with the experimental compiles for Blender 2.93 Beta ARM and Blender 3.0 alpha ARM.

When I activate the Add on I get the following error:

_Traceback (most recent call last):
  File "/Applications/Blender 2.93 ARM.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/Edgar/Library/Application Support/Blender/2.93/scripts/addons/animation_nodes/__init__.py", line 158, in <module>
    raise Exception(message)
Exception: 

This build does not work at the moment.
  1. Check if the build you downloaded has been compiled for the OS
     you are using. If not, download another one.
  2. If you are on windows you can try to install a library called
     'vc_redist.x64'. Should be easy to find using your search engine
     of choice.
  3. Try to use an official Blender release downloaded from blender.org.
  4. It is possible that you have a build for the correct platform
     but it still does not work. We experienced this mainly on linux.
     Try to find another build for your platform.
     If it still does not work, you have to compile AN yourself.
  5. Make a bug report on Github and give as much information
     as you can. Specifically the full error message, your OS, version, ...__

So I am following instruction number 5. I am running Blender on a MacBook Pro with Big Sur 11.3.1.
Do I have to wait for Blender 2.93 to be officially released or it is unrelated to Blender itself, but related to the new ARM M1 processor?

Blender 2.92 Intel with Animation Nodes 2.2.2 runs just fine on the same Mac.

Thank very much in advance.

**Comment by OmarEmaraDev** [comment]
We don't compile Animation Nodes for ARM at the moment. We also depend on a library that doesn't have ARM neon support. We plan on replacing that dependency though.

So Animation Nodes doesn't work with ARM at the moment. But it will probably support it in the future.

**Comment by Gussisaurio** [comment]
OK. Thank you very much, Omar.
