### ISSUE TITLE
new names given by object instancer

### ISSUE THREAD

**Issue by Majoran99** [JacquesLucke/animation_nodes#1723]
I have incoming data that sometimes should trigger to create a new object, which will then do something for a while (e.g. following a spline until its end) and should then be terminated. And it might happen that before 1 object is killed, the next object already comes up.
The problem with the object instancer is: for every instance it gives names like MyObject.001, MyObject.002 and so on. Say it first created MyObject.001, which then does something, meanwhile it also creates MyObject.002. Now Object.001 should be killed - but if I turn back the Instancer from 2 to 1, the one remaining object gets again the name "MyObject.001". So I lose MyObject.002.
I have seen here (https://github.com/JacquesLucke/animation_nodes/issues/1286#issuecomment-580361537) that renaming an object from the instancer is possible, but in this case this seems to be pretty tricky. Whereas it would be super nice if the instancer simply would always go on numbering the new output objects. 
So my wish is: If I turn the instancer to 2 instances, it creates MyObject.001 and MyObject.002. If I turn it then back to 1 Instance, the last object created (MyObject.002) will remain. If I turn it again to 2 instances, it will give MyObject.002 and the new MyObject.003. And so on...
I am hoping this makes sense. If there is already an easy way to realise this, let me please know.

(This issue would be useful for example for visualising incoming MIDI data like in this visualisation: 
https://archive.org/details/AutoAudioVis5/egoshootVis.mp4 )

**Comment by OmarEmaraDev** [comment]
This seems like an XY problem. Why is it an issue that the extra instances are removed from the end? Ideally your node tree to should be fully descriptive of the objects. Can you share a minimal example that demonstrates this issue?

**Comment by Majoran99** [comment]
Here I use the name-numbering of the instancer to identify each instance individually. But when reducing the number instances, the identification gets lost.
![grafik](https://user-images.githubusercontent.com/82707686/119121902-3ecfcd80-ba2e-11eb-8bbe-1419ff52f82b.png)

**Comment by OmarEmaraDev** [comment]
The question still stands, why does it matter? You just need to identify the object using its index in the output list.

**Comment by Majoran99** [comment]
yes.. but when its position in the index changes due to removing instances, it is getting complicated, I was wondering if it wouldn't be worth a thought implementing the option that a once an object is named in the instancer it could remain with its name although the list length might change.

**Comment by OmarEmaraDev** [comment]
I am sorry, I am still not following what you are saying exactly. I think you should provide a practical example that shows that limitation.

**Comment by Majoran99** [comment]
I try...:
The practical example would be incoming MIDI data. A MIDI pitch (a key on a MIDI keyboard) is by default at 0 but sometimes goes to 1 (key is pressed, note sounds). Everytime a specific key (pitch 60, e.g.) is pressed, an object should be generated and do a movement.
(examples:
https://archive.org/details/AutoAudioVis5/egoshootVis.mp4
or
https://user-images.githubusercontent.com/79052050/111075825-24262900-84c0-11eb-85a8-7b8d0eba140d.mp4 )

To break it down to the core:
I have a counter counting every hit of 1. So the note events sum up to 1 2 3 4 ... Thus creating a unique number for each sounding event. Giving a lifetime for each event-object of 50 frames, a delayed counter subtracts 50 frames later. Results in an incoming stream of 1 2 3 2 3 2 1 2 ...
This would be the input for the instancer. 

Here I have an example (to make it easier, instead of MIDI data I have an empty simply going 0 - 1 - 2 - 1 -0.
(exactly: until frame 9 is at 0, from 10-49 at 1, from 50 to 79 at 2, from 80 to 130 at 1, from 131-end at 0.)

This would mean: first there is 0 objects. Then object 1. Then additionally object 2. Then object 1 dies, object 2 should remain. Then object 2 also dies.
During its lifetime, each object moves upwards. (More complex/ interesting would be each objects follows a spline.)

Now the problem comes:
Here it works with the creation of object 1, it starts to move upwards. Then object 2 comes in addition, works also fine, moves upwards from the world origin. But then, when object 1 is killed, object 2 gets the name of object 1, and so it makes a jump to the last position of object 1 instead of following its own movement any more.
It would be super if the instancer would keep the identity of a once created object.
![Image2](https://user-images.githubusercontent.com/82707686/119177159-34342900-ba6c-11eb-8edb-3da35cc5eacb.jpg)

There might be other solutions for that problem, but as far as I see no elegant, whereas having that option in the instancer might provide generally interesting options to work with objects living for a given lifespan.

**Comment by OmarEmaraDev** [comment]
Well, the main problem is that your animation is not described parametrically. Animation Nodes wasn't designed to work with non parametric animations. Parametric means the object locations can be described as a function of time, with possibly some other parameters.

Say it takes each object `d` seconds to do their animation after they start, and say they start at time `s`. Then to implement this, at time `t`, you find all events where `s < t < s + d`. Instance a number of objects to match the number of events you filtered. For each event, subtract the start time `s` from the current time `t`. The value you get out of the subtraction is the time of the animation, which you can use to evaluate an F-Curve, evaluate an action, evaluate a curve, use in an Animate node, or whatever. Your animation is now parametric and your issue with the instance node would be solved.

**Comment by Majoran99** [comment]
Thank you for your answer, yes, that is possible.
Just thought it might be worth considering to facilitate this by implementing a drop-down-menu in the object instancer where one can choose between the current mode of naming the objects (how to call? "additive-subtractive"?) and a "progressive" naming.
This would allow much easier for having individual objects with a given lifespan, hence one can create fireworks with them and many other great stuff ...

**Comment by OmarEmaraDev** [comment]
I don't think we will be adding such a guarantee. Sorry.
Let me know if you need help in constructing something though.
