### ISSUE TITLE
issue installing AN

### ISSUE THREAD

**Issue by chishou69100** [JacquesLucke/animation_nodes#1724]
Hi ! 
I am totally new in the blender and i have trouble to install the animation node. I installed python 3.9.5 and VC_redist.x64. i can't understand why it's not working. 
![image](https://user-images.githubusercontent.com/79552766/119058216-38116e00-b9ce-11eb-98f7-84d99747f7ee.png)

Thanks in advance.

**Comment by OmarEmaraDev** [comment]
Can you try manually erasing the `animation_nodes` folder from the `addons` directory then installing Animation Nodes again?

**Comment by chishou69100** [comment]
It worked thank you.
