### ISSUE TITLE
Get Custom Attribute doesn't seem working

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1725]
@3DSinghVFX 
Would you be able to confirm and check that?
There isn't any other modifier or setup attached.

![image](https://user-images.githubusercontent.com/55994236/119139282-d3c3ce00-ba10-11eb-9aea-71cb468462f4.png)

**Comment by OmarEmaraDev** [comment]
Do you have the hidden Load Custom Attributes input enabled?

**Comment by Gerstmann-Bradley** [comment]
> Do you have the hidden Load Custom Attributes input enabled?

Ok, I didn't notice that. Thanks for mentioning!

**Comment by asustnt3** [comment]
> Do you have the hidden Load Custom Attributes input enabled?

I get this problem, but i don't know how to have it enable...   
Can i have a bit of detail?

**Comment by asustnt3** [comment]
![image](https://user-images.githubusercontent.com/19390719/121296961-1c8de900-c924-11eb-8501-480e3648b0dd.png)
