### ISSUE TITLE
Proposal: Get Minimum and Maximum / Statistics of a float list.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1729]
This is a node I created for myself for a long time. I think it will be nice we have that within native AN.
Many times I have a list of values and I want to do evaluation with some statistics, such as the shortest/longest spline length.
To make this node by user is theoretically simple. But it also takes a lot of nodes. I think it would better be implemented in the first place. I also think to keep "indices" are important in case there are some specific use case.
What do you think?
(FYI, AFAIK there was similarly kind of proposed idea in geometry Nodes. I think the dev intends to name it as "Attribute Statistic" Node.)
![image](https://user-images.githubusercontent.com/55994236/119243373-0aded000-bb34-11eb-9bdb-c96ea0d01008.png)

**Comment by OmarEmaraDev** [comment]
This functionality seems to be better suited for the Number List Math node. Maybe we can just add the index to that node?

**Comment by Gerstmann-Bradley** [comment]
> This functionality seems to be better suited for the Number List Math node. Maybe we can just add the index to that node?

I see, I've never known that node. Yes, I think add index to that will be helpful.
Also would you add alias directing user to use its minimum/maximum function?

**Comment by Gerstmann-Bradley** [comment]
I also think many times when we know maximum then we want to know minimum. Instead of calling nodes for two times, would that be better to put them into the same class? We may use "Range" to describe it? What do you think?

**Comment by OmarEmaraDev** [comment]
I think two nodes here is acceptable.

Index and aliases added in a6e9b62 as you suggested.
