### ISSUE TITLE
Mesh Object Output > origin not in the center of the object

### ISSUE THREAD

**Issue by trinityss** [JacquesLucke/animation_nodes#1730]
Hi,

I'm following this tutorial (but also want to animate the object): https://www.youtube.com/watch?v=cyR_meI7YjQ&t=3s
I however bump into an issue...

I can't roll the cylinder because the origin isn't placed in the center of the object > 
https://drive.google.com/file/d/1KAQA5N_VjUOwSQmYRIciZcpj-5-MZ10c/view?usp=sharing

![image](https://user-images.githubusercontent.com/61430022/119315733-73ce6100-bc76-11eb-95db-30dc9340215e.png)

Is there a way to change the location of the origin, ,aybe with an AN?
The origin can't be moved with the move tool like is possible with other objects.

Thx!

**Comment by Gerstmann-Bradley** [comment]
I guess there are two ways to solve your problem: 
1. in your most original mesh, make sure it's centered properly according to the world origin. (Figure.1)
2. you just want "transform mesh" node to center your created mesh.

![image](https://user-images.githubusercontent.com/55994236/119317326-f68af800-bc45-11eb-829d-923fe50be8d4.png)

**Comment by trinityss** [comment]
Hi Bradley,

Thanks for your quick reply!  The origin of my original mesh is centered >

![image](https://user-images.githubusercontent.com/61430022/119322238-be071080-bc7d-11eb-8910-f37a800a14dd.png)

I had a look to the transform mesh node but there doesn't seem to be a way to influence the location of the origin, or am I missing something?

![image](https://user-images.githubusercontent.com/61430022/119322661-22c26b00-bc7e-11eb-81cf-814811cfd42a.png)

Thx!

**Comment by Gerstmann-Bradley** [comment]
> Hi Bradley,
> 
> Thanks for your quick reply! The origin of my original mesh is centered >
> Thx!

I meant to locate it at "world origin" Your object is always created based on the "world origin". (Figure.1)
So even if you successfully rotate your target object, it may not rotate in the way you want.
Also a reminder. you have turned your tool "Affect Origin" on, you won't be able to rotate your object in the viewport. (Figure.2)
![image](https://user-images.githubusercontent.com/55994236/119323331-93e92a80-bc4c-11eb-95a8-7791c20a57ee.png)
![image](https://user-images.githubusercontent.com/55994236/119323610-e62a4b80-bc4c-11eb-9d5a-7e79f5783ea9.png)

**Comment by trinityss** [comment]
Aha, sorry about that! Putting the original cylinder at the world origin does indeed result in a correct rotation!

Thanks for your help!

Kr,
