### ISSUE TITLE
"Object Attribute Output" node is not compatible with geometry nodes

### ISSUE THREAD

**Issue by hooyuser** [JacquesLucke/animation_nodes#1731]
**Info**
Blender version: 3.0.0 Alpha, branch: master, commit date: 2021-05-15 23:00, hash: 9dabb342ba5e, type: Release
Blender build date: 2021-05-15, 23:10:04
Platform: 'Windows-10-10.0.18362-SP0'
Animation nodes version: 2.2.2

**Bug Description**
I want to change an input value of my geometry nodes modifier with the "Object Attribute Output" node.  I found that the "Object Attribute Output" node could change the value shown in the modifier UI. However, my geometry nodes modifier didn't respond to this change. 

For example, the input value "Rot Z" can be modified correctly, but the cube doesn't rotate at all.

![bug_1](https://user-images.githubusercontent.com/10691820/119336752-94bba400-bcc0-11eb-8a7c-6717443ca8fb.png)

Here is the blend file of this example: [an.zip](https://github.com/JacquesLucke/animation_nodes/files/6531774/an.zip)

**Comment by OmarEmaraDev** [comment]
Seems to be a limitation of Geometry Nodes, setting values through python doesn't evaluate the GN node tree. Not exactly related to Animation Nodes. I would report this bug to Blender instead.

**Comment by hooyuser** [comment]
> Seems to be a limitation of Geometry Nodes, setting values through python doesn't evaluate the GN node tree. Not exactly related to Animation Nodes. I would report this bug to Blender instead.

That's probably the case. Thanks for your help!
