### ISSUE TITLE
Mix series of Node showing Red Bar Error once in Vectorized Form.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1733]
A weird case I see pretty often. It presents in nearly every Mix Node. (Mix Vector, Mix Euler, Mix Color...)
Is this expected behavior?

Win 10.
Nearly Latest AN.
![image](https://user-images.githubusercontent.com/55994236/119405560-700b0080-bcaf-11eb-93fb-9290a49ba95a.png)

**Comment by OmarEmaraDev** [comment]
Fixed in 75175ce. Thanks for the report!
