### ISSUE TITLE
shape key input & output don't store selected object

### ISSUE THREAD

**Issue by Majoran99** [JacquesLucke/animation_nodes#1736]
With shape key input & output nodes, selecting an object isn't stored, when closing and reopening the blend file, the selections are gone.

**Comment by OmarEmaraDev** [comment]
By selection you mean the Object input property in the node?

**Comment by Majoran99** [comment]
yes

**Comment by OmarEmaraDev** [comment]
Can replicate that.

**Comment by OmarEmaraDev** [comment]
Fixed in 1bbcdce. Thanks for the report!
