### ISSUE TITLE
Particle system - how define when splines appear and disappear 

### ISSUE THREAD

**Issue by krillin666** [JacquesLucke/animation_nodes#1738]
Hi,

I've creating 5 different particle systems and defined what frame each starts and ends.
The trouble I have encountered is how to define the frame where the particle link can start and end, right now all links are starting at around frame 50. 

What I am trying to obtain can be something like this:
- First particle system link - start at frame 50, stop at frame 100, continue at frame 120, end frame 150
- Second particle system link - start frame 80, stop at frame 120, continue at frame 160, end frame 200
- ...

Is this possible to do with the nodes and how can I do it?
Apart from this, can I also determine how fast the particle links (splines) are moving?
 
![Blender_question](https://user-images.githubusercontent.com/60305303/120889885-3fa05c00-c5f7-11eb-87d5-04b701afd0d8.png)

**Comment by OmarEmaraDev** [comment]
It depends on what you want to animate exactly. One thing you can do is slice the output splines list using parameters from an animate node.

**Comment by krillin666** [comment]
What I am trying to animate are the particle links, hope the video helps.
I want to be able to chose in what frame these links start to appear.

Sorry for the FPS, not the best pc.

https://user-images.githubusercontent.com/60305303/120892781-d117ca00-c607-11eb-97e3-adcd984e3936.mp4

**Comment by OmarEmaraDev** [comment]
Try animating the Max Distance parameter using an Animate Node. The start value should be one that gives no connections and the end value is the value you are after.
