### ISSUE TITLE
Node-Tabber Compatibility

### ISSUE THREAD

**Issue by L33t-HAXXOR** [JacquesLucke/animation_nodes#1740]
Are there any plans to make this compatible with [Node Tabber by jigglymoon69](https://github.com/jiggymoon69/node_tabber)?

I love Blender's one key shortcuts and it would be super dope to have that in AN.

As of now, the tab key brings up a blank search menu in AN.
And Node Tabber generally overrides the AN keys.
For instance, if I set the AN quick search to tab without changing the NT shortcut, NT will pull up a blank menu.
If I change the NT shortcut to Ctrl + A (the AN quick search menu) without changing AN, it'll pull up that aforementioned blank menu.

https://user-images.githubusercontent.com/31870368/120933725-06ccb980-c6c1-11eb-9a7e-db6f760e0467.mov

I'm just a simple man who would like Tab to search his nodes in whatever editor.
Would this be possible?

Thanks for reading!
-L33t

**Comment by OmarEmaraDev** [comment]
Not sure how this works at the moment. Animation Nodes uses special search functionality, so that might be problematic. I will take a look later.

**Comment by L33t-HAXXOR** [comment]
Thank you!

**Comment by OmarEmaraDev** [comment]
Have you tried changing the shortcut of this key map item to Tab? Note there is a different key map item for normal search, this one is specific to Animation Nodes.

![20210709-083839](https://user-images.githubusercontent.com/25300994/125034644-1c068080-e091-11eb-9480-dc222b8a175a.png)

**Comment by L33t-HAXXOR** [comment]
Yes I believe I have
That makes that blank menu pop up
