### ISSUE TITLE
Red Bar Error when Inputing Spline list into Spline Falloff

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1743]
![image](https://user-images.githubusercontent.com/55994236/121906566-3b5ff700-ccf9-11eb-8ea3-8b363bfe4a74.png)
![image](https://user-images.githubusercontent.com/55994236/121906680-57639880-ccf9-11eb-8241-8a49b80b4aef.png)

**Comment by OmarEmaraDev** [comment]
Fixed in b187339. Thanks for the report!
