### ISSUE TITLE
AN-Generated Mesh's keyframe data isn't preserved in render.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1746]
Animation is observable in the viewport but not render. Is this related to #1652?
![image](https://user-images.githubusercontent.com/55994236/122835292-143b9380-d2be-11eb-9598-e543c205b2fc.png)
[Generated Mesh.zip](https://github.com/JacquesLucke/animation_nodes/files/6689798/Generated.Mesh.zip)

**Comment by OmarEmaraDev** [comment]
Yes. Seems to be identical to #1652.
