### ISSUE TITLE
v2.2 for Blender 2.93 LTS Release

### ISSUE THREAD

**Issue by OmarEmaraDev** [JacquesLucke/animation_nodes#1747]
We need to release a new version v2.2 for Blender 2.93 LTS. Note that this version uses Python 3.9, which will be our only supported version. This issue outlines the work needed to do the release.

# Documentation

- [x] v.2.2.0
  - [x] Release notes.
  - [x] Node Reference.
- [x] v.2.2.1
  - [x] Release notes.
  - [x] Node Reference.
- [x] v.2.2.2
  - [x] Release notes.
  - [x] Node Reference.

Developers who contributed code to the release are welcome to contribute their respective changes, possibly more. Use the CHANGELOG file to identify the changes and propagate those changes to the documentation.

# Stoppers

- #1756.
- #1726.

# Publish

- [x] Tag release.
- [x] Bump version.
- [x] Update workflow.
- [x] Update website.
- [x] MacOS Arm Builds.

**Comment by OmarEmaraDev** [comment]
As far as I remember, the main contributors to this release are @3DSinghVFX, @harisreedhar, and @kdsin23. Let me know if you can help with the preparations for the release.

**Comment by 3DSinghVFX** [comment]
@OmarEmaraDev I'll help with the release. Can you please let me know the tentative date of the release?

**Comment by OmarEmaraDev** [comment]
@3DSinghVFX Work will be done in the master branch. The only reason I put the subversions above is to organize things and track progress. There is no specific release date, we will release once we are ready, so no hurry. I believe you have commit access, so you can commit directly, open a pull request when it doubt. Other developers can open pull requests.

**Comment by harisreedhar** [comment]
@OmarEmaraDev Sure i can help with the release.

**Comment by 3DSinghVFX** [comment]
> @3DSinghVFX Work will be done in the master branch. The only reason I put the subversions above is to organize things and track progress. There is no specific release date, we will release once we are ready, so no hurry. I believe you have commit access, so you can commit directly, open a pull request when it doubt. Other developers can open pull requests.

@OmarEmaraDev  Okay, thanks for the information.

**Comment by marcan** [comment]
Any chances of getting an arm64 (Apple Silicon) macOS build too? I'd be happy to help with the build if needed, since I have the hardware.

**Comment by OmarEmaraDev** [comment]
Hi @marcan, can you create an ARM build from the `v2.2-for-blender-v2.93` branch?

**Comment by marcan** [comment]
I made a build and it seems to run fine, but the test suite has a bunch of failures, all of this form:

```
..........................EEEEE........................................EE
======================================================================
ERROR: algorithms.lists (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: algorithms.lists
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/marcan/software/an2/animation_nodes/animation_nodes/algorithms/lists/__init__.py", line 1, in <module>
    from . shuffle import shuffle, getShuffleFunction
  File "animation_nodes/algorithms/lists/shuffle.pyx", line 8, in init animation_nodes.algorithms.lists.shuffle
    from ... sockets.info import getSocketClass
ImportError: attempted relative import beyond top-level package```

Is this expected?

**Comment by marcan** [comment]
Nevermind, it seems I had something left over from an old install...

**Comment by marcan** [comment]
Here you go! https://mrcn.st/t/animation_nodes_v2_2_macOS_py39.zip

**Comment by OmarEmaraDev** [comment]
Thanks @marcan!
