### ISSUE TITLE
Particle system - how to use Mantaflow fluid simulation particles in AN

### ISSUE THREAD

**Issue by mathiaskula** [JacquesLucke/animation_nodes#1748]
Hi!
I've run a FLIP liquid simulation with Mantflow and would like to use the particles from the simulation with AN - is this possible?
![AN_particle_systems_emitter_vs_fluid_sim](https://user-images.githubusercontent.com/78308826/124127537-2070df00-da7c-11eb-8e96-6141fc9e5e22.jpg)
The attached image shows a plane with a default emitter vs a fluid sim - the setup works just fine for the emitter plane but not for the liquid particle system. I've tried to change 'particles_data.py' (under nodes/particles) on line 65
(yield "    if system.settings.type != 'EMITTER': continue") to also look for FLIP or APIC (with restart of Blender to reload AN), but I still cannot get particle locations, as shown by the list length of 0 in the image.
Any thoughts?

Best regards,
Mathias

**Comment by OmarEmaraDev** [comment]
Not sure why it didn't work for you. But I just added support in 73804bb. Wait a couple of minutes and download a new build and it should work.

**Comment by mathiaskula** [comment]
Thanks! It seems to work now... I must have made some mistake. //Mathias

Den tors 1 juli 2021 kl 15:24 skrev Omar Emara ***@***.***>:
