### ISSUE TITLE
lastest doesn't work in 2.93

### ISSUE THREAD

**Issue by Azagwen** [JacquesLucke/animation_nodes#1751]
I had the addon installed previously, but the editor wasn't showing up, so I thought I might need the latest build, so I un-installed it and re-added it (latest 2.2.2 for py3.9), but I couldn't even activate it, it gave me this

![image](https://user-images.githubusercontent.com/30528331/124288833-ec67ed80-db51-11eb-9847-46cff60a0861.png)

Is there anything I could try to make it work again ?

**Comment by OmarEmaraDev** [comment]
Can you attach whatever was printed in the terminal?

**Comment by Azagwen** [comment]
> Can you attach whatever was printed in the terminal?

from the "Blender info Log" window

```
Python: Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_valvesource\GUI.py", line 84, in draw
    row.label(text=GetCustomPropName(scene.vs,"export_format",":"))
  File "C:\Users\Utilisateur\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_valvesource\utils.py", line 306, in GetCustomPropName
    return "".join([pgettext(typing.get_type_hints(type(data))[prop][1]['name']), suffix])
TypeError: '_PropertyDeferred' object is not subscriptable

location: <unknown location>:-1


```

**Comment by Azagwen** [comment]
> Can you attach whatever was printed in the terminal?

I closed Blender after it happened, and now I'm unable to reproduce it 😢

**Comment by OmarEmaraDev** [comment]
So Animation Nodes is working correctly right now?

**Comment by BigPhattyVW** [comment]
I just had this error too, and even looked at the terminal window to copy. But I forgot to...

However, I restarted Blender and tried to enable animation nodes again and everything went fine!

Just created this account to fill y'all in.

**Comment by Pyrax** [comment]
I can second that - good old restart of Blender fixed it for me as well.

Can't reproduce it afterwards either. 
My approximate steps when the issue was happening:
- I was working with the Sequencer 
- Then tried to install Animation Nodes but chose the wrong Python version for the plugin first (3.7), removed it and then installed for 3.9.
- Exception occured when trying to activate the plugin
- After restart, activating the plugin worked
