### ISSUE TITLE
AN - Blender 2.93.0 - Mac M1 Build - Not able to activate the Add-On

### ISSUE THREAD

**Issue by neuro-81** [JacquesLucke/animation_nodes#1755]
I am not able to get AN to Add-On in the M1 Version of Blender 2.93.0 
BigSur 11.4
AN Version: animation_nodes_v2_2_macOS_py39

I get the following error: 

<img width="743" alt="Blender_AN_Error" src="https://user-images.githubusercontent.com/68710774/124888207-81784580-df9b-11eb-904f-fd75407cc38e.png">

**Comment by OmarEmaraDev** [comment]
That build is an x86 build for older MacOS. But M1 builds for MacOS11 will be release soon starting from the next release, until then, I think you can run this build through Rosetta.

**Comment by neuro-81** [comment]
Thanks, I don't have the option to open Blender in Rosetta from the "Get Info" tab. 
How would I go about running the add on using Rosetta? 

Any ETA on next release date? 

Thank you! 
-ML

**Comment by neuro-81** [comment]
Okay - I'm good to go until your Apple Silicon Release. I had to download the Intel Version of Blender.
