### ISSUE TITLE
Crash when calling hide_render/viewport inside a loop

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/animation_nodes#1757]
Hi

I am getting repeated crashes when I use a script node inside a loop that disables all the objects in a collection. I am attaching a sample scene that can repeat the crash.

I am using Windows 10, AN 2.2.2 and Blender 2.93 release (the issue is there with 3.0 as well)

![blender_6Y0PpfvJ2i](https://user-images.githubusercontent.com/8519469/126543848-73828795-a3d3-4dab-b0f9-f1376deba089.jpg)

[an_script_test.zip](https://github.com/JacquesLucke/animation_nodes/files/6858168/an_script_test.zip)

**Comment by OmarEmaraDev** [comment]
I can replicate that. I will investigate.

**Comment by gerroon** [comment]
The interesting thing is that it does not crash if you just enable disable single objects fed by the AN loop. This crash happens only when there is a loop that processes a whole collection inside the loop.

**Comment by OmarEmaraDev** [comment]
Unfortunately, this turned out to be a limitation in Blender documented in the [Gotchas](https://docs.blender.org/api/current/info_gotcha.html#unfortunate-corner-cases) section. In particular, to quote:

> `Object.hide_viewport`, `Object.hide_select` and `Object.hide_render`: Setting any of those Booleans will trigger a rebuild of Collection caches, thus breaking any current iteration over Collection.all_objects.

So you can't iterate over the objects and adjust those properties at the same time.

**Comment by gerroon** [comment]
@OmarEmaraDev 

Thanks for the finding, it makes sense. I am glad it is not Animation Nodes.
