### ISSUE TITLE
BUG: Decompose Text Node "can't load (second) font"

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1766]
You can select and load the first font (let's say font-A),
but if you change your font, any following font (font B, C, D, E, F, G) won't be able to be loaded. The bug exist across "Decompose Text Node", meaning if you create a new the same node, it will have the same error to font B, C, D...
The problem doesn't present in text object output, not only you don't have warning, but also it works correctly in the viewport.
This seems a new bug, not sure why it happens.
![image](https://user-images.githubusercontent.com/55994236/127688929-d20538be-4cdb-4bb5-8316-95868f3f63b0.png)

**Comment by OmarEmaraDev** [comment]
Seems to be working fine here. Did this start happening after updating Blender or something?

**Comment by Gerstmann-Bradley** [comment]
I am using 2.93.0 and latest AN. I will update 2.93.1 and 3.0 to see how it goes.

**Comment by Gerstmann-Bradley** [comment]
Occurring to me in both Blender Version as well.

**Comment by OmarEmaraDev** [comment]
Can you open the Blender console and try the following multiple times with different fonts (Replace `<path>` with the path to the font):

```
import blf
print(blf.load("<path>"))
```

Does any of the commands print -1? And are the fonts packed into the blend file?

**Comment by Gerstmann-Bradley** [comment]
> Can you open the Blender console and try the following multiple times with different fonts (Replace `<path>` with the path to the font):
> 
> ```
> import blf
> print(blf.load("<path>"))
> ```
> 
> Does any of the commands print -1? And are the fonts packed into the blend file?

![image](https://user-images.githubusercontent.com/55994236/127702909-7bb42021-0060-4205-b916-6b89ba2351e5.png)
![image](https://user-images.githubusercontent.com/55994236/127703053-f3c1ed54-34ac-466d-a0e7-b0324c5a43db.png)

I think this is irrelevant to AN. If I just play the console, I can succeed the first time, but second time it will always return -1.

**Comment by OmarEmaraDev** [comment]
Can you check the console? Blender should print an error once you get a -1.

**Comment by Gerstmann-Bradley** [comment]
> Can you check the console? Blender should print an error once you get a -1.

would you tell me how to do that exactly? wasn't I already showing the console? Or you mean see the error using command?

**Comment by OmarEmaraDev** [comment]
I mean the terminal/console you open from Window -> Toggle System Console.

**Comment by Gerstmann-Bradley** [comment]
It says "Too many fonts!!!".
![image](https://user-images.githubusercontent.com/55994236/127708016-65ec5306-0fbb-49ba-8770-57b121facf05.png)
![image](https://user-images.githubusercontent.com/55994236/127707996-22705370-166b-4789-ba6a-b70897b04dc8.png)

**Comment by OmarEmaraDev** [comment]
It seems Blender only allow up to `BLF_MAX_FONT = 16` fonts to be used, so you will have to reduce the number of fonts you use.

**Comment by Gerstmann-Bradley** [comment]
i'm only importing the second font in all cases. So i'm not sure where other fonts come and how to solve this issue.

**Comment by OmarEmaraDev** [comment]
Maybe another add-on is loading those fonts? Try disabling all add-ons temporarily, restart Blender, see if the problem is fixed. If it is, then one of the add-ons is probably the culprit.

**Comment by Gerstmann-Bradley** [comment]
The issue occurs in factory setting. I am still not sure what's the reason. But this is just a random issue I found in free time. Hope it will be fixed by itself some day...
