### ISSUE TITLE
Invalid Network when sending a custom property to another object while in a loop

### ISSUE THREAD

**Issue by tacopancakes** [JacquesLucke/animation_nodes#1767]
I am trying to setup a multi MVC pattern of multiple instanced Controller objects with grouped receiver objects, so the Controller object holds custom properties and sends a trigger of sorts at some point in time to its grouped receivers. In these screen shots I just show one for each

I do this game design via code all the time via arrays and loops. But am trying to figure out how to get it done in Animation Nodes.

In the screen shots I have added one one object to each loop to eliminate possible mistakes. If I set the receivers custom property directly all is fine. But if I set it via an outside object WHILE in a loop for each I get Invalid Network. 

The screenshots show that the idea works if I individually select one controller and receiver. 

![working loop 01](https://user-images.githubusercontent.com/83318886/127704105-d4e071a6-7458-408b-8350-0f378d79a7a9.JPG)

Here I simply link the outVal of Controller to the inVal of reciver

![invalid network 01](https://user-images.githubusercontent.com/83318886/127704115-7150deea-47ae-4811-9e1a-d5895c256dbb.JPG)

Individual selection works outside of a loop
 
![non loop 02](https://user-images.githubusercontent.com/83318886/127704118-e88687d6-a875-4611-9eb5-85828ced0495.JPG)

**Comment by OmarEmaraDev** [comment]
I don't fully understand what you are trying to do, but the reason why your network becomes invalid is the fact that the network now have two Loop Input nodes. If you are trying to nest them, then you need to invoke the inner loop in the outer one, not include the loop definition in the other loop.

**Comment by tacopancakes** [comment]
Do the loops not happen at the same time? Its not obvious that the tree has an order for various loops, nor do I see a way to invoke a subprogram outside of the root, they dont have a switch or trigger input.

I am simply trying to feed data from one object to another. Not a complex concept. Now in code yes I would have the for loop happen in the Controller but ownership is not a concept here aside from parenting, or I missed something.

**Comment by OmarEmaraDev** [comment]
In this case, you don't need two loops. Use one loop with two iterators, one iterator for the controller objects and another iterator for the receiver objects.

**Comment by tacopancakes** [comment]
Ehhh~ I guess. I had not considered the loop to be coupled with multiple iterators instead of invoking another loop later down the chain. I still find the invocation and order a bit misleading or so. Anyway your suggestion looks to work so ill consider this solved but the original issue remains as a design limitation i view.
Thank you
