### ISSUE TITLE
Get Spline Length ignores unit scale

### ISSUE THREAD

**Issue by eTaernis** [JacquesLucke/animation_nodes#1775]
The result of the Get Spline Length node does not take into account the unit scale.
Could this be fixed please?

**Comment by OmarEmaraDev** [comment]
What do you mean by "unit scale"?

**Comment by eTaernis** [comment]
Scene Properties - > Units -> Unit Scale
the global multiplier for all object dimensions. Can be used e.g. to match all dimensions to the measurements of a reference object. 

Unfortunately, the unit scale can't be applied afaik. So if the unit scale is not 1, I would have to multiply the result of the Get Spline Length node with the unit scale to get the actual length.

**Comment by OmarEmaraDev** [comment]
I see. But I don't think the node should take this into account. We are basically adding a dependency on a scene for an operation that doesn't really need it. I think this should be left to the user.
