### ISSUE TITLE
[bug] [help wanted] [AN 2.2.2] Fatal error when adding the nodes "Create NlaStrip List" and "Combine NlaStrip List" in a NodeTree

### ISSUE THREAD

**Issue by Telumire** [JacquesLucke/animation_nodes#1779]
Hello,

I was trying to get NLA data (is that even possible ?) but the available nodes that seems related to that ("Create NlaStrip List", "Combine NlaStrip List") are generating a fatal error (red rectangle in the Animation Nodes editor) once added in the node tree.

I'm using blender 3.0 .0 alpha and the latest version of the addon (2.2.2). This bug is also occuring in blender 2.93.3.

Does Animation Nodes actually support NLA ? I was hoping to use the Pose Library with AN to trigger specific pose/animations procedurally, but I did not found information on that anywhere, including the doc .. I'm new to AN so please let me know if that's a bad idea !

Thanks for having read this text, have a great day/night 😃

**Comment by OmarEmaraDev** [comment]
We don't really have support for NLA. Those nodes were left over from an old version which I removed now. Feel free to make a detailed proposal of what you would like to see in the Discussion -> Ideas tab and we will discuss a possible implementation.
