### ISSUE TITLE
L-System -> Mesh Object Output not working

### ISSUE THREAD

**Issue by FAUSheppy** [JacquesLucke/animation_nodes#1781]
I tried this very simple L-System node setup:

![image](https://user-images.githubusercontent.com/14907292/131277122-0169c09d-42bc-4c09-89ba-d94172d02fd4.png)

But there is no output. I read through https://github.com/JacquesLucke/animation_nodes/issues/1115 and tried the alternative example from there.

I run 2.93.3 on linux and tried both animation nodes v2.2 & v2.3. I also tried on the same blender version on a Windows 10 machine yesterday with the same problem.

**Comment by OmarEmaraDev** [comment]
Generations is set to 0, so the L-system isn't grown, try increasing that. Also, in the Mesh Object Output node, you can enable Calculate Loose Edges to show the edges in object mode.
