### ISSUE TITLE
ARM version 2,2,2

### ISSUE THREAD

**Issue by Laurenthenrydavid** [JacquesLucke/animation_nodes#1782]
Hi there,
(excuse my English, I'm French) I 've tried to achieve a tutorial with a part including Animation Nodes :
https://youtu.be/NGV5GDMz6oA?t=1197
but I had a problem when I connected the Locations of the "Object Transforms Input" node to the Location of "Evaluate Falloff" node : it add automatically a "Get List Element" Node that is not appearing in the tutorial and I don't know what to do with it !!! I cannot "mute" it
I'v tried to delete it but it appears again when I do the connection again. Is it a bug or it has to be there ?
I use the same version of Animation Nodes as the author of the tutorial but mine is for MacOs ARM. My version of Blender is 2.93.1 ARM
Thank you for your response !

**Comment by OmarEmaraDev** [comment]
Did you enable the *Use List* option that is beside the evaluation type?

**Comment by Laurenthenrydavid** [comment]
I'm afraid I don't understand your question ?
![Animation node](https://user-images.githubusercontent.com/89923693/131707834-8971cbc6-ed1a-45a9-a41f-4c3718de3739.jpg)

**Comment by Gerstmann-Bradley** [comment]
> I'm afraid I don't understand your question ?
> ![Animation node](https://user-images.githubusercontent.com/89923693/131707834-8971cbc6-ed1a-45a9-a41f-4c3718de3739.jpg)

![image](https://user-images.githubusercontent.com/55994236/131708379-a2a3430e-dd85-4b93-a30f-006fc3f9da53.png)
He means to hit this buttom

**Comment by Gerstmann-Bradley** [comment]
> I'm afraid I don't understand your question ?

![image](https://user-images.githubusercontent.com/55994236/131708519-d05d289d-2bd6-4744-971b-c320508126c5.png)
He means to hit this button

**Comment by Laurenthenrydavid** [comment]
Thank you very much !!!
Now it works perfectly !!!
It's my fault ! I didn't see when he check that box in the tutorial !
