### ISSUE TITLE
Error when installing AN for Blender 3.0 on Mac

### ISSUE THREAD

**Issue by luckychris** [JacquesLucke/animation_nodes#1787]
i got this error here:

![image](https://user-images.githubusercontent.com/232549/132990737-872cb6b2-07ec-446e-80f1-1b881307a8ef.png)

I downloaded AN from here: https://animation-nodes.com/#download

Question: should it run for Blender 3.0 or should i get another version?

**Comment by OmarEmaraDev** [comment]
I feel like this was wrong installation. Can you try removing the add-on explicitly and reinstalling it?

**Comment by luckychris** [comment]
i tried and got this:

![image](https://user-images.githubusercontent.com/232549/133240402-2cf146e2-38e7-4468-9bd1-2c1630397ea6.png)

**Comment by OmarEmaraDev** [comment]
Can you open Blender from the command line and paste the output here?

**Comment by luckychris** [comment]
yes i can:

MacOS % ./Blender
Read prefs: /Users/c/Library/Application Support/Blender/3.0/config/userpref.blend
DEBUG:BlenderGIS-225.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-225.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-225.core.checkdeps:Pillow available
DEBUG:BlenderGIS-225.core.checkdeps:ImageIO Freeimage plugin available
cmolcore imported with success! v1.12
sv: import settings
sv: PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
INFO:sverchok.dependencies:sv: PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
sv: Circlify package is not available. Circlify node will not be available
INFO:sverchok.dependencies:sv: Circlify package is not available. Circlify node will not be available
sv: FreeCAD package is not available, Solids nodes will not be available
INFO:sverchok.dependencies:sv: FreeCAD package is not available, Solids nodes will not be available
sv: Numba package is not available, njit compiled functions will not be available
INFO:sverchok.dependencies:sv: Numba package is not available, njit compiled functions will not be available
sv: Dependencies available: pip, scipy, geomdl, scikit-image, Cython.
INFO:sverchok.dependencies:sv: Dependencies available: pip, scipy, geomdl, scikit-image, Cython.
sv: import all modules
sv: enable internal debug logging.
INFO:logging:log level, 20
 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/ 
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.

sv: version: 1.0.0
INFO:sverchok_extra.dependencies 33:Pygalmesh package is not available. Corresponding nodes will not be available
INFO:sverchok-extra-master 93:Registered 14 nodes
INFO:sverchok-extra-master 110:Node `SvExGalGenerateMeshNode' is not available (probably due to missing dependencies).
INFO:sverchok-extra-master 110:Node `SvSolidWaffleNode' is not available (probably due to missing dependencies).

   _____                     __          __         ______     __            
  / ___/   _____  __________/ /_  ____  / /__      / ____/  __/ /__________ _
  \__ \ | / / _ \/ ___/ ___/ __ \/ __ \/ //_/_____/ __/ | |/_/ __/ ___/ __ `/
 ___/ / |/ /  __/ /  / /__/ / / / /_/ / ,< /_____/ /____>  </ /_/ /  / /_/ / 
/____/|___/\___/_/   \___/_/ /_/\____/_/|_|     /_____/_/|_|\__/_/   \__,_/
initialized.
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Characters definition loaded from characters_config.json in 0.00023508071899414062 secs
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Skeleton knowledge data loaded from retarget_knowledge.json in 0.00026226043701171875 secs
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_i_01.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from deglutition01.json in 6.127357482910156e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from evil02.json in 6.29425048828125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from flirty01.json in 0.00010228157043457031 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from breathing_in.json in 5.4836273193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_u_01.json in 5.1975250244140625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from annoyed01.json in 5.793571472167969e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_t_01.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_a_01.json in 4.982948303222656e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from crying02.json in 5.2928924560546875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from sad01.json in 4.982948303222656e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from furious01.json in 5.7220458984375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from peaceful01.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from angry01.json in 0.00010323524475097656 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_c_01.json in 9.584426879882812e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from confused02.json in 6.222724914550781e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from pain01.json in 5.412101745605469e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from sleep01.json in 7.987022399902344e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from tired01.json in 9.822845458984375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from irritated01.json in 0.00012493133544921875 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from bored01.json in 0.0001227855682373047 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from disgusted.json in 0.00010991096496582031 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_o_02.json in 5.1021575927734375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from surprise02.json in 5.364418029785156e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from kiss01.json in 0.00013184547424316406 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from surprise03.json in 0.00010704994201660156 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_k_01.json in 0.0001690387725830078 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from very_sad01.json in 0.00011396408081054688 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from drained01.json in 0.00011992454528808594 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from posing01.json in 0.0001690387725830078 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_b_01.json in 9.202957153320312e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_w_01.json in 0.00011420249938964844 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_r_02.json in 5.412101745605469e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from serene01.json in 7.224082946777344e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from excited01.json in 6.008148193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_b_02.json in 5.91278076171875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from shocked01.json in 6.008148193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_g_01.json in 6.008148193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_r_01.json in 5.602836608886719e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from grin01.json in 5.1021575927734375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_n_01.json in 5.602836608886719e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from offended01.json in 5.1975250244140625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from attentive01.json in 5.4836273193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from happy01.json in 6.079673767089844e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from sarcastic01.json in 5.984306335449219e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from eyes_rot_right.json in 5.459785461425781e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_z_01.json in 9.489059448242188e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from surprise01.json in 7.987022399902344e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_o_01.json in 7.82012939453125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from eyes_rot_down.json in 5.793571472167969e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_c_02.json in 9.512901306152344e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from confused01.json in 7.772445678710938e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_f_01.json in 7.486343383789062e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_s_01.json in 8.797645568847656e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from embarrassed01.json in 7.796287536621094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from furious02.json in 7.390975952148438e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from sad02.json in 6.222724914550781e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_m_01.json in 5.91278076171875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from curious01.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_a_02.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_q_01.json in 5.793571472167969e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from crying01.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from anxious01.json in 6.508827209472656e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from shy01.json in 6.008148193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_d_01.json in 5.7697296142578125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from eyes_rot_up.json in 5.793571472167969e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from lazy01.json in 5.3882598876953125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from breathing_out.json in 5.7697296142578125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_p_01.json in 5.7220458984375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_e_01.json in 5.2928924560546875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_i_02.json in 5.3882598876953125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from deglutition02.json in 5.6743621826171875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from scared01.json in 6.103515625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from evil01.json in 6.103515625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from wink01.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_l_01.json in 5.3882598876953125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from furious03.json in 6.413459777832031e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from eyes_rot_left.json in 5.412101745605469e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_i_01.json in 5.793571472167969e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from deglutition01.json in 6.985664367675781e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from evil02.json in 9.799003601074219e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from flirty01.json in 0.00011897087097167969 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from breathing_in.json in 0.00011515617370605469 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_u_01.json in 5.316734313964844e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from annoyed01.json in 9.799003601074219e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_t_01.json in 7.104873657226562e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_a_01.json in 6.198883056640625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from crying02.json in 6.604194641113281e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from sad01.json in 6.198883056640625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from furious01.json in 6.29425048828125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from peaceful01.json in 5.698204040527344e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from angry01.json in 6.318092346191406e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_c_01.json in 6.198883056640625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from confused02.json in 6.127357482910156e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from pain01.json in 6.604194641113281e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from sleep01.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from tired01.json in 5.817413330078125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from irritated01.json in 6.198883056640625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from bored01.json in 6.008148193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from disgusted.json in 5.91278076171875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_o_02.json in 5.6743621826171875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from surprise02.json in 6.008148193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from kiss01.json in 5.793571472167969e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from surprise03.json in 6.198883056640625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_k_01.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from very_sad01.json in 6.198883056640625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from drained01.json in 5.817413330078125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from posing01.json in 5.7697296142578125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_b_01.json in 5.817413330078125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_w_01.json in 5.817413330078125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_r_02.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from serene01.json in 6.127357482910156e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from excited01.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_b_02.json in 5.91278076171875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from shocked01.json in 5.793571472167969e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_g_01.json in 5.984306335449219e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_r_01.json in 5.817413330078125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from grin01.json in 5.817413330078125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_n_01.json in 5.4836273193359375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from offended01.json in 6.031990051269531e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from attentive01.json in 5.412101745605469e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from happy01.json in 6.127357482910156e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from sarcastic01.json in 5.6743621826171875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from eyes_rot_right.json in 5.316734313964844e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_z_01.json in 5.412101745605469e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from surprise01.json in 6.389617919921875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_o_01.json in 5.888938903808594e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from eyes_rot_down.json in 5.698204040527344e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_c_02.json in 5.793571472167969e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from confused01.json in 6.198883056640625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_f_01.json in 5.2928924560546875e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_s_01.json in 9.822845458984375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from embarrassed01.json in 0.00011110305786132812 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from furious02.json in 5.1021575927734375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from sad02.json in 5.7220458984375e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_m_01.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from curious01.json in 5.602836608886719e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_a_02.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_q_01.json in 4.8160552978515625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from crying01.json in 5.984306335449219e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from anxious01.json in 5.1975250244140625e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from shy01.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_d_01.json in 5.364418029785156e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from eyes_rot_up.json in 5.3882598876953125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from lazy01.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from breathing_out.json in 5.3882598876953125e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_p_01.json in 5.412101745605469e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_e_01.json in 5.412101745605469e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_i_02.json in 4.982948303222656e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from deglutition02.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from scared01.json in 5.316734313964844e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from evil01.json in 5.602836608886719e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from wink01.json in 5.507469177246094e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from phoneme_l_01.json in 0.00010180473327636719 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from furious03.json in 0.0001327991485595703 secs
INFO:MB-Lab-1_7_8_5.file_ops:Character data loaded from eyes_rot_left.json in 4.887580871582031e-05 secs
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
INFO:MB-Lab-1_7_8_5.file_ops:Looking for the retarget data in the folder data...
mb_lab updater verbose is enabled
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_install_popup'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_install_popup'>
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_check_now'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_check_now'>
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_update_now'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_update_now'>
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_update_target'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_update_target'>
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_install_manually'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_install_manually'>
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_updated_successful'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_updated_successful'>
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_restore_backup'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_restore_backup'>
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_ignore'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_ignore'>
cls BA: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_end_background'>
cls: <class 'MB-Lab-1_7_8_5.addon_updater_ops.addon_updater_end_background'>
mb_lab Updater: Read in json settings from file
INFO:MB-Lab-1_7_8_5.algorithms:Looking for a humanoid object ...
INFO:MB-Lab-1_7_8_5.algorithms:No lab humanoids in the scene
------------------Load-----------------
Saved session recovery to '/var/folders/xf/2w8_n8pd54s_g1kntlccqjqr0000gn/T/quit.blend'
cleaning Sverchok cache
cleaning Sverchok cache
Exception in module unregister(): '/Users/c/Library/Application Support/Blender/3.0/scripts/addons/flip_fluids_addon/__init__.py'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 439, in disable
    mod.unregister()
  File "/Users/c/Library/Application Support/Blender/3.0/scripts/addons/flip_fluids_addon/__init__.py", line 184, in unregister
    bpy.app.handlers.depsgraph_update_post.remove(scene_update_post)
ValueError: list.remove(x): x not in list

Blender quit

**Comment by OmarEmaraDev** [comment]
This doesn't seem to include any AN related logging. I am interested in the output when you enable AN and it fails.

**Comment by luckychris** [comment]
I am sorry Omar. You are right. I started now Blender from the command line for Blender 3.0 and for Blender 2.93. Both installations worked now. I have no idea why. Sorry for bothering you.
