### ISSUE TITLE
FloatList to TextList?

### ISSUE THREAD

**Issue by starzar** [JacquesLucke/animation_nodes#1788]
Is there a way to convert a round a FloatList to 'n' decimal places and display all list values in 3dViewport?

Currently single value conversion is only allowed with **Float to Text** and TextObjectOutput accepts only single values.

I would like to display **_'all values'_** of the Floatlist as separate text objects  in 3dViewport. 

**ATTEMPT 1_FloattoText** 
'**![bandicam 2021-09-15 10-12-06-108](https://user-images.githubusercontent.com/38550930/133372244-7dcf746b-ce07-4184-9b5f-61f3fe349328.jpg)** 

**ATTEMPT 2_ TextObjectOutput** 
![AnFloatlist_2](https://user-images.githubusercontent.com/38550930/133375643-bafcc429-051a-4458-acb4-ee54b1d190a9.jpg)

**Comment by OmarEmaraDev** [comment]
Implemented in 7162885. Thanks for the suggestion!

**Comment by starzar** [comment]
@OmarEmaraDev  Thanks...Is there a way to display the entire list as separate text objects (TextObjectOutput accepts only single values)?

**Comment by OmarEmaraDev** [comment]
I am pretty sure the Text Object Output node accepts lists. Just try plugging it in and it should work.

**Comment by starzar** [comment]
Plz refer above node setup -  **_ATTEMPT 2_ TextObjectOutput**

TextObjectOutput outputs only a single list element.

**Comment by OmarEmaraDev** [comment]
@starzar You need to use the object instance node to create the objects first. See:
https://docs.animation-nodes.com/tutorials/decompose_text/
