### ISSUE TITLE
Custom Attribute does not load for object has modifiers

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1792]
Hi.
I have noticed that *Custom Attributes* only load in the Input Mesh Object node if the object modifiers are disabled in the panel:
![Screenshot from 2021-09-28 19-45-59](https://user-images.githubusercontent.com/30294746/135105969-f0a72cc9-09a0-4196-b16c-a19e588aa4af.png)

Otherwise, it shows error when they are enabled in the panel:
![Screenshot from 2021-09-28 19-46-14](https://user-images.githubusercontent.com/30294746/135106039-5580eeae-9f45-4d71-8daf-c0d17f9d9dbe.png)
![Screenshot from 2021-09-28 19-46-46](https://user-images.githubusercontent.com/30294746/135106079-14e96fc4-bb8e-4424-b972-8c5fb0c81b85.png)

**Comment by OmarEmaraDev** [comment]
I can replicate, I will look into it later.

**Comment by OmarEmaraDev** [comment]
Fixed in cf8def5. Thanks for the report!
