### ISSUE TITLE
Bevel Object Option Not Working

### ISSUE THREAD

**Issue by SkelatorIndy** [JacquesLucke/animation_nodes#1793]
I was following a tutorial using Animation Nodes and it shows adding an object into the **Bevel Object** option in the **Curve Object Output** node. In the comments the creator said they made an issue on the GitHub page regarding this, which I found to be issue #1608. 
Looking at the issue, it says it is closed, however the only comment on the issue is a link to a commit regarding adding the **Bevel Mode** and **Fill Caps** option. Looking at the commit I don't see anything about fixing the bevel object issue, only the new options, and now the issue is present in my project.
I'm using Animation Nodes v2.3.0 (Although I have tested using AN v2.2.2 as well and it still did not work) and Blender v2.93.4. 
I realize this is technically a duplicate issue, however seeing as the previous one was closed without solving the issue I thought I'd make another one. 

For reference, the tutorial I am following is here:
[https://www.youtube.com/watch?v=dv9ln7brjek]
and the timestamp of what is supposed to happen is at 6:55

You can see that immediately after adding the target, it changes how the model looks completely. Mine does not change at all. I'm positive my settings are identical to the tutorials, as I have gone over them multiple times.

**Comment by OmarEmaraDev** [comment]
Can you share a minimal file that reproduces the problem?

**Comment by SkelatorIndy** [comment]
Sure. Give me just a bit to set up a new blender file with just the stuff I have so far, since the one I'm working on contains a bunch of other models too.

**Comment by Gerstmann-Bradley** [comment]
I can replicate it. Omar, it's just the bevel object is again broken somehow.
I am not using the newest AN though, I will download it and try again.
[BUG REPORT.zip](https://github.com/JacquesLucke/animation_nodes/files/7272234/BUG.REPORT.zip)

**Comment by Gerstmann-Bradley** [comment]
yeah, seems still broken in the newest AN.

**Comment by OmarEmaraDev** [comment]
You need to set the bevel mode to `OBJECT`, it is set to `ROUND` by default.

![20211002-232104](https://user-images.githubusercontent.com/25300994/135732081-3f14bfdf-2188-4ebe-916b-d4e96a2f970a.png)

**Comment by Gerstmann-Bradley** [comment]
oh, I see. thanks.

**Comment by SkelatorIndy** [comment]
Ah, it's working now. Thanks for the quick response!
