### ISSUE TITLE
UI related Question: Colored wires in Animation Nodes 

### ISSUE THREAD

**Issue by meikasahara** [JacquesLucke/animation_nodes#1798]
Could Animation Nodes also use the newly introduced colored wires based on data type that are now default in geometry nodes and the shader editor?

**Comment by OmarEmaraDev** [comment]
The newly introduced colored wires unfortunately don't support custom socket colors, it just uses whatever colors in `std_node_socket_colors`. So this is a limitation in Blender, not Animation Nodes. I will look into adding support though, I will get back to you.

**Comment by OmarEmaraDev** [comment]
Seems to be working. Not sure if they will accept such a patch though. We can try to submit it regardless.

![20211029-233131](https://user-images.githubusercontent.com/25300994/139504027-5cb61ce3-728c-4360-914a-fc199ff7510b.png)

**Comment by meikasahara** [comment]
Seems the patch is about to land! I will therefore close this issue! Thanks!

**Comment by meikasahara** [comment]
Reopening since the issue has resurfaced. It has also been reported to Blender:
https://developer.blender.org/T93184
