### ISSUE TITLE
Suspected Millisecond Bug

### ISSUE THREAD

**Issue by adamliuio** [JacquesLucke/animation_nodes#1799]
https://user-images.githubusercontent.com/9758779/139517316-f16198bf-fd90-4b38-aee1-e5764ff49f00.mov

I'm using the "v2.2 for Blender 2.93 LTS (AMD64)" version, and whenever a node is created, there's a millisecond indicator showing up in the upper left corner and keeps bouncing very fast, which doesn't help at all and spikes the cpu usage quite a bit.

Is this a bug or a setting that can be adjusted somewhere? Would love to know.

Besides this, good work for developing this guys, really appreciate it!

**Comment by OmarEmaraDev** [comment]
In version 2.2, Animation Nodes by default executes as many times as possible indefinitely, which is not good as you might have noted. The Auto Execution panel includes the options to disable this and enable better modes of execution. Read the documentation on Execution for more information. https://docs.animation-nodes.com/documentation/introduction/execution/
