### ISSUE TITLE
Can't enable Animation Nodes (Mac)

### ISSUE THREAD

**Issue by mrberns** [JacquesLucke/animation_nodes#1803]
The error message is below, I'm having this issue on my M1 Mac mini (Monterey 21.0.1) with AN+EN 2.30 Mac OS.

(This one: https://blender.community/c/graphicall/phbbbc/)

I've attempted the suggested troubleshooting steps such as completely removing prior versions, and also tried different builds of Blender including 2.93 and 3.0 Beta.

The AN only version 2.2 seems to install fine, but I need to use some of the extra nodes :)

Is this perhaps to do with the fact I'm using ARM?

![image](https://user-images.githubusercontent.com/51438665/141837033-04792ffc-8ee5-4f03-838a-e4215e9e2887.png)

Here are my specs:

![image](https://user-images.githubusercontent.com/51438665/141837241-b74b7731-9254-4fd1-9f45-e7b08902eb42.png)

Thanks!

**Comment by OmarEmaraDev** [comment]
As far as I know, Extra Nodes don't build ARM builds for the M1 Mac, so yes, that's the issue.
The reason why we don't have ARM builds available is that our build bots don't support them yet.
For the 2.2 release, however, the people from Asahi Linux were kind enough to provided us with a build.
So you will have to build it yourself or wait until we are able to use M1 Mac runners.

**Comment by mrberns** [comment]
Thank you for clarifying that
