### ISSUE TITLE
Cant find the right installer for 2.79

### ISSUE THREAD

**Issue by Justiniscoding** [JacquesLucke/animation_nodes#1806]
I am using blender 2.79.7 and I cannot find the right installer for animation nodes. I can not upgrade my blender version due to my OS. If I use the [animation_nodes_v2_1_macOS_py36.zip](https://github.com/JacquesLucke/animation_nodes/releases/download/v2.1_testbuilds_2/animation_nodes_v2_1_macOS_py36.zip) installer it tells me there is a python version mismatch and that my blender build uses version 3.7 and animation nodes was compiled for 3.6. I think I need to download a different installer, one for python version 3.7 except I can't find the right installer on the [releases page](https://github.com/JacquesLucke/animation_nodes/releases). How could I compile it myself or find a version that would work for me? (on macOS 10.11.6)

**Comment by OmarEmaraDev** [comment]
I don't think we have a version for 2.7x Python 3.7. So you will have to compile yourself.

For compiling, make sure Cython is installed, checkout the source code at the [`v2.0` tag](https://github.com/JacquesLucke/animation_nodes/tree/v2.0), then execute in the source directory:

```
python setup.py build --export --noversioncheck
```

**Comment by Justiniscoding** [comment]
I have python version 3.7 installed and when I run that command I get the following error:
```
Unknown arguments: {'build'}
Allowed arguments: {'--noversioncheck', '--all', '--nocopy', '--export'}
```
After that, I tried running this command: `python setup.py --export --noversioncheck` and it succeeded after a few minutes
