### ISSUE TITLE
BUG: No Linkage is Formed when the node being put in between

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1809]
![image](https://user-images.githubusercontent.com/55994236/144893451-6113e35d-0292-41f8-a59f-47ec6c3a89f5.png)
FYI

**Comment by OmarEmaraDev** [comment]
This was fixed already in https://developer.blender.org/rBab2a7aa0da81678b19e3362b93f89e8302da65d8. Didn't go into the 3.0 release unfortunately.
