### ISSUE TITLE
All Action conversions fail with NameError

### ISSUE THREAD

**Issue by Th3Gavst3r** [JacquesLucke/animation_nodes#1810]
## Description
When attempting to convert an Action socket, the Node Tree will error with the message `NameError: name 'Action' is not defined`

## To reproduce
1. Create an Empty and add an Action to it
1. Create an `Action from Object` node in the Animation Nodes editor
1. Attach the `Action` output socket to a `Convert` node
1. Change the conversion type to `Action`
1. `NameError` occurs

![image](https://user-images.githubusercontent.com/9059018/145332410-216b1fab-b5eb-42cf-a590-9f7b19942191.png)

I tried to work around this using a `Script` node and some custom class conversion with Python, but `Script` nodes seem to silently fail to output a valid `Action` even when the NodeTree displays no errors and the provided output variable is a valid instance of `data_structures.Action`.

![2021-12-08_23-56-03_%pn](https://user-images.githubusercontent.com/9059018/145336938-0649fbfe-e462-4e10-bd03-ae60def35ea2.gif)

## Potential fix
Changing [`ActionSocket.correctValue()`](https://github.com/JacquesLucke/animation_nodes/blob/4efcf03272c14ac0078bb3d4564a27fe25b1eef3/animation_nodes/sockets/action.py#L22) to use `data_structures.Action` fixes both of the explicit and silent errors listed above, but a small caveat is that the `Convert` node still cannot automatically convert `bpy.types.Action` to a format animation_nodes understands. 

With fix:
![2021-12-08_23-54-41_%pn](https://user-images.githubusercontent.com/9059018/145336820-2d64aa4d-d99d-4eb8-84f0-99267226c857.gif)

## Example file
Here is a [minimal blend file](https://dl.dropboxusercontent.com/s/jybn9grb8z9d88q/action%20selector%20script%20minimal.blend) which reproduces this bug. Three scenarios are included:
1. Converting an `Action` socket from an `Action from Object` node (fixed with above solution)
2. Converting a `bpy.types.Action` generic attribute from an `Object Attribute Input` node (conversion fails with above solution)
3. Converting an action using custom python scripting (fixed with above solution)

![image](https://user-images.githubusercontent.com/9059018/145333541-baa949e1-292c-4d0a-8031-cc69da69f8fc.png)

**Comment by OmarEmaraDev** [comment]
Thanks for the detailed report! Your solution seems correct. Do you want to create a pull request for that or would you like me commit?

For the failed conversion, Animation Nodes doesn't really try to correct complex types that are not part of Animation Nodes. So conversion of BPY Action to AN Action, while possible, is expected to fail. But I guess we could look into more elaborate conversions at some point.

**Comment by Th3Gavst3r** [comment]
Sure I just opened up #1812, just wanted to double check what direction you wanted to take before putting up a solution
