### ISSUE TITLE
number wiggle result values outside the interval...

### ISSUE THREAD

**Issue by luckychris** [JacquesLucke/animation_nodes#1817]
Docu says:
Amplitude - It is the maximum possible value for the absolute of the output number.
https://docs.animation-nodes.com/documentation/nodes/number/number_wiggle/

i have this node setup to check the results of number wiggle:
![image](https://user-images.githubusercontent.com/232549/145990942-c81cea43-ec91-4abf-8861-2e6f9fab8c95.png)

So the resulting max and min of node wiggle is outside [-3,3]

is this a bug, or what am i doing wrong?

**Comment by OmarEmaraDev** [comment]
Looks like the documentation is wrong here, especially when you have a high number of octaves. Not sure if this is something we can guarantee.

**Comment by luckychris** [comment]
ok thank you for your very fast answer. So i am not too dumb... ;)
