### ISSUE TITLE
Tempo Track of Midi Nodes of Animation Nodes are not properly taken into account.

### ISSUE THREAD

**Issue by KonSwart** [JacquesLucke/animation_nodes#1821]
Hi!

When I saw that Animation Nodes was extended with midi capabilities, I was very excited!

FINALLY I could use midi in Bender!

I used it in the following video.

https://youtu.be/VHCbmKka58w

However, when I tried to use it in a Blender version of this: 

https://youtu.be/GaDvGbixwz0?t=147

It messed up the timing completely. The end notes were all over the place! They were shifted far to the back!

The midi file at this position has a lot of tempo change events in the tempo track.

The midi file reader does nót take that properly into account.

This is a HUGE ISSUE for me!

In the Mozart animation, this was not a problem, because that file contained just one tempo event in the tempo track.

Has any work been done yet to remedy this problem?

**Comment by OmarEmaraDev** [comment]
Can you share the problematic MIDI file?

**Comment by KonSwart** [comment]
Here it is.

 

The problem starts with measure 34.03, all through the end.

**Comment by KonSwart** [comment]
This problem has prevented me from making YouTube tutorials, showing how one can make midi animations like the Alla Turca with Animation Nodes.

 

I know that there are many people interested in such tutorials, because I have received requests and questions about how to make such videos.

 

The video of the problematic file has been made, not by Animation Nodes, but in Unity.

 

I have made the Alla Turca video in Blender.

 

I hope you can resolve this problem.

**Comment by OmarEmaraDev** [comment]
I can't see that file anywhere. You need to upload it to Github not through email.

**Comment by KonSwart** [comment]
I try again.

I tried it through GitHub, but the 'Attach files by dragging & dropping selecting or pasting them' failed.

So, how do I do that?

**Comment by KonSwart** [comment]
I am completely new to GitHub.

**Comment by KonSwart** [comment]
Next attempt.

 

How do I upload from GitHub?

**Comment by KonSwart** [comment]
I try again through e-mail, and compress the file.

Maybe THAT will work!

How do I upload through GitHub? 

The box: 'Attach file by dragging & dropping selecting or pasting them' does not work!

It says: We don't support that file type.

I tried it with midi, and compressed to a rar format.

**Comment by KonSwart** [comment]
I tried again, through e-mail, but now compressed with a rar format.

Did it arrive now?

**Comment by KonSwart** [comment]
I have changed the extension of .mid to .jpg, and tried again.

If it arrives, try to change it back to .mid


![No01BWV846Prelude - Copy](https://user-images.githubusercontent.com/24935129/149819623-70406ec8-609b-425d-b23e-fcfc870a769d.jpg)

**Comment by KonSwart** [comment]
I have tested it, by downloading it from the link, and then changing the extension to .mid

With me it was working, because I could open the midi file in Sonar, and the problematic tempo changes were there.

Here it is, again.


![No01BWV846Prelude - Copy](https://user-images.githubusercontent.com/24935129/149820069-2f5a9ec2-fbc0-4b25-bc07-d32899eada67.jpg)

**Comment by OmarEmaraDev** [comment]
Okay. I got the file. I can see there is a delay at the very end indeed. I am not immediately sure what is causing that. It might take sometime to investigate that.

**Comment by KonSwart** [comment]
Great that you look at it!

The problem is in the tempo track. The changes in the tempo track are not taken into account in the timing of the midi events.

Usually that is no problem, because most musicians use realtime recordings, so that there is just one tempo command in the entire file. But I work in steptime. Therefore I edit the tempo, after I have made the midi file.

If you could solve THIS, I would be VERY GRATEFUL to you!

**Comment by KonSwart** [comment]
Please, let me know if, and when you have solved it.

Also, please let me know when you cannot do it!

**Comment by OmarEmaraDev** [comment]
Fixed in 836773b. Thanks for the report!

**Comment by KonSwart** [comment]
Wow! That was fast!

 

Thank you very much!

 

I shall test it tomorrow!
