### ISSUE TITLE
Python mismatch

### ISSUE THREAD

**Issue by AwesomeGuy74623** [JacquesLucke/animation_nodes#1828]
It says that there is a Python mismatch even though I reinstalled the addon and got the correct version or Python and Blender. So how do I get a custom build or fix it?

- OS: Windows
- Blender 3.0.1

**Comment by OmarEmaraDev** [comment]
What does the error message say about the version mismatch?
Which version of Animation Nodes did you download?

**Comment by mike2003** [comment]
I'm in the same situation. what to do with this error? It doesn't work with 3?
![a8wkE6D](https://user-images.githubusercontent.com/11754198/155888528-6826355f-3867-48b7-a0ed-4fa1baed7648.jpg)

**Comment by OmarEmaraDev** [comment]
@mike2003  I am guessing you are downloading a daily build, not the LTS release. In this case, download the py39 versions from here https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build.

**Comment by ilionic** [comment]
Would be possible to publish new version compiled for python 3.10 ( the one Blender 3.1 expecting ) for ARM mac? Thanks

**Comment by OmarEmaraDev** [comment]
@ilionic We don't have access to an Arm Mac at the moment, so we won't publish official builds unless Github supports M1 runners,

**Comment by ilionic** [comment]
@OmarEmaraDev thanks for speedy reply. I will try to compile it from source myself then.
