### ISSUE TITLE
Can someone compile a py310 build for windows? 

### ISSUE THREAD

**Issue by TheJeran** [JacquesLucke/animation_nodes#1829]
I would like to use AN for Blender 3.1 but of course Blender 3.1 uses python 3.10. I'm not smart enough to compile it myself. I saw someone had compiled a version for MacOS in another issue and was wondering if someone would be so kind to do the same for Windows.

**Comment by OmarEmaraDev** [comment]
The builds we have in the website are already Python 10, do they not work for you?
https://animation-nodes.com/#download

**Comment by TheJeran** [comment]
Agh, my dumbass was downloading the v2.2 And didn't realize the "latest' Was different from the 2.2 here on github. Thanks
