### ISSUE TITLE
Proposal: Get Sequence from Scene By Name

### ISSUE THREAD

**Issue by jackhumbert** [JacquesLucke/animation_nodes#1830]
I have a workflow for making videos where I edit Scenes/clips together in a separate Scene (like `_Editing`), and I made a quick node to grab a Sequence from that Scene, to get info like the start & ending of the clip, and use that timing information in my Scene's animations:

```py
import bpy
from ... base_types import AnimationNode

class GetSequenceFromSceneNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_GetSequenceFromSceneNode"
    bl_label = "Get Sequence From Scene"

    def create(self):
        self.newInput("Scene", "Scene", "scene")
        self.newInput("Text", "Name", "name")
        self.newOutput("Sequence", "Sequence", "sequence")

    def getExecutionCode(self, required):
        yield "editor = scene.sequence_editor if scene else None"
        yield "sequences = list(getattr(editor, 'sequences', []))"
        yield "sequence = [x for x in sequences if x.name == name][0]"
```

Would this sort of node be acceptable to add, or maybe there could be a Scene selection on the `Sequence Info` node? I was also wondering if there is a better way to access an element of that `sequences` list by name other than by using a string. I wasn't sure how I could repopulate the Sequence selection from a variable.

Thanks for making this great addon!

**Comment by OmarEmaraDev** [comment]
We already have a general Blend Data By Name node that does something similar, so adding this node would be good and inline with what we have already. Feel free to open a pull request.

We should probably use `sequences_all` to include sequences in meta strips as well. Both `sequences_all` and `sequences` are `bpy_prop_collection`, which behaves like a dictionary and can be subscribed using the name of the sequence `sequences_all[name]`. But for robustness, as no sequence with the given name may exist, we should use the [`get`](https://docs.blender.org/api/current/bpy.types.bpy_prop_collection.html#bpy.types.bpy_prop_collection.get) method, which is also similar to its dictionary counterpart.
