### ISSUE TITLE
Can't enable add-on

### ISSUE THREAD

**Issue by uraniumcrystalsmaster** [JacquesLucke/animation_nodes#1831]
I upgraded blender to 3.1, and downloaded animation nodes for python 3.10. It used to work before.
This is the error message I get:

Traceback (most recent call last):
  File "D:\SteamLibrary 2.0\steamapps\common\Blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\urani\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\__init__.py", line 166, in <module>
    auto_load.init()
  File "C:\Users\urani\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\urani\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\urani\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "D:\SteamLibrary 2.0\steamapps\common\Blender\3.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\urani\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\nodes\numpy\from_numpy.py", line 4, in <module>
    from .. rotation.c_utils import flatDoubleListToEulerList
ImportError: cannot import name 'flatDoubleListToEulerList' from 'animation_nodes.nodes.rotation.c_utils' (C:\Users\urani\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\nodes\rotation\c_utils.cp310-win_amd64.pyd)

**Comment by OmarEmaraDev** [comment]
This likely because you intermixed a new version with an old version. Delete the `C:\Users\urani\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\animation_nodes\` manually and install again.

**Comment by satabol** [comment]
I have this problem too. But in console I see:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Unable to initialise audio

I got that error after installing sverchok addon. It install new version numpy. I think animation nodes has to be rebuild with new version numpy or do not update numpy with sverchok addon (simple revert - get clean blender installation)

**Comment by OmarEmaraDev** [comment]
@satabol But is this runtime error from Animation Nodes? If Sverchok installed a new version and the error messages indicates the current version is lower, shouldn't that mean that Sverchok is the one that is not happy?

The error in the first message indicates the existence of old code, so AN just needs to be removed and reinstalled cleanly.

**Comment by satabol** [comment]
> @satabol But is this runtime error from Animation Nodes? If Sverchok installed a new version and the error messages indicates the current version is lower, shouldn't that mean that Sverchok is the one that is not happy?
I check console and got very strange situation. I can't run AN files saved before today and I can run only newer files of today. It is very embarrassing. WTF?! It is happens and with only AN installed on blender (I clean blender userprofile too).

**Comment by OmarEmaraDev** [comment]
Does the Retry button work in those cases?

**Comment by satabol** [comment]
Yes I did. In console no new error.
But I see 2 strange append:
![image](https://user-images.githubusercontent.com/14288520/158900248-35c34ec5-785d-4c93-9f2b-372532564df8.png)
like node tree look deleted node.

**Comment by satabol** [comment]
![image](https://user-images.githubusercontent.com/14288520/158900576-7f25bbda-d996-4670-bc8f-ba8704e0ff2d.png)

**Comment by satabol** [comment]
Yes I did. But no result. I have a new information and this is not theme for this situation on the top. I will create a new Issue with some pictures and solutions.

**Comment by uraniumcrystalsmaster** [comment]
I wasn't sure if it would delete my node configurations by deleting the addon. Thank you for your help!
