### ISSUE TITLE
Exception in console on open files. AN do not animate anything.

### ISSUE THREAD

**Issue by satabol** [JacquesLucke/animation_nodes#1835]
I have no exactly steps for reproduction. It is happens with my yesterday files. Yesterday I have install new blender 3.1 and last AN. All work well. I newly in AN so I did some experiments and save some files. Today I install sverchok and update its numba module. Numba for sverchok need old version numpy and sverchok reinstall numpy. Ok. Sverchok work well. But today I found that AN stop working. It did not start at blender start. So I delete my Blender installation and clean user profile of Blender (C:\Users\user\AppData\Roaming\Blender Foundation) and Blender installation folder. After a clean install of Blender I install AN. No errors on start in console. Good. 

I. On open my yesterday files I got error in console:
After many tries I found in some files empty node "Invoke subprogram". If I delete it node AND "save as" new file AND restart Blender AND open newly created blend file I got AN is working!!!
I have two files with this error and in both of them was empty "Invoke subprogram" node.

![image](https://user-images.githubusercontent.com/14288520/158906358-8cf3733a-3910-461c-8c3b-08f02bb0a80f.png)

II. If I get runtime error on open files like in pos.I then AN will not work with any other files (with new or open saved files) until restart Blender (if I try open good files too)

III. If I get error on open file and file has no empty node “invoke subprogram” then I “save as” a new file, close blender, open blender and open last file. AN work well now.

This is file with my error.
[Empty_InvokeSubprogram_node.runtime_error_at_start.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/8293405/Empty_InvokeSubprogram_node.runtime_error_at_start.blend.zip)

**Comment by OmarEmaraDev** [comment]
Fixed in 1153368. Thanks for the report!

**Comment by satabol** [comment]
@OmarEmaraDev Thank you. All old files open without errors and works. Awesome!
