### ISSUE TITLE
Animation node 2.3 for Mac m1 (and pro, max, ultra) blender 3.1

### ISSUE THREAD

**Issue by jlrichter** [JacquesLucke/animation_nodes#1836]
Hi,

I have recompliled the animation nodes plug-in for my Macbook pro 16 m1max for blender 3.1 with Python 3.10.3

I don't know how to upload the file, so I share it from my drobox :

[Build](https://www.dropbox.com/s/8achg2tvy8njs9t/animation_nodes_v2_3_macOS_py310.zip?dl=0)

It takes a few seconds to activate in blender (I was a bit worried) wut it is working so far

**Comment by megrimm** [comment]
I keep getting:

`macOS cannot verify the developer of “vector.cpython-310-darwin.so”. Are you sure you want to open it?`

and 

`“conversion.cpython-310-darwin.so” cannot be opened because the developer cannot be verified.`

for each *.so I have to go into system preferences and "Allow Anyway". Any way to Allow All?

**Comment by megrimm** [comment]
this worked for me:

`xattr -d -r com.apple.quarantine ~/Documents/Blender/addons/animation_nodes`

solution from here:
https://superuser.com/questions/1618945/file-developer-cannot-be-verified-error

**Comment by MrTheRich** [comment]
> Hi,
> 
> I have recompliled the animation nodes plug-in for my Macbook pro 16 m1max for blender 3.1 with Python 3.10.3
> 
> I don't know how to upload the file, so I share it from my drobox :
> 
> [Build](https://www.dropbox.com/s/8achg2tvy8njs9t/animation_nodes_v2_3_macOS_py310.zip?dl=0)
> 
> It takes a few seconds to activate in blender (I was a bit worried) wut it is working so far

Could you give an explanation what is needed to make the addon compatible with blender 3.x? I want to compile this for windows too, but can't find a guide on what is neccesary.

**Comment by MrTheRich** [comment]
Nvm I got it to work.
For people who wonder in the future: 
Make sure you have the right python version or use `--noversioncheck`.
Make sure you have Visual Studio compiler installed
Install Cython voor python.
modify the `config.conf` to the correct blender (version) addon directory and your windows username
run `python setup.py build --copy` from the correct directory in the commandline if you want to directly install it.
run `python setup.py build --export` if you want an installable zipfile.

If the compile fails at FastNoiseSIMD, manually compile that lib using the Native Visual Studio cmd by running `animation_nodes\libs\FastNoiseSIMD\source\compile_windows.bat`

**Comment by wyhinton** [comment]
So is the current state of things that Animation Nodes does not work on m1 mac out of the box? If so this should be noted in the docs.

**Comment by OmarEmaraDev** [comment]
@wyhinton It should work, we just don't provide official daily builds for it, because we don't have the hardware.
