### ISSUE TITLE
Couldn't find animation_nodes folder from addons

### ISSUE THREAD

**Issue by mousery** [JacquesLucke/animation_nodes#1837]
Well I installed the animation node addon in Blender 3.0.1. Then I tried to activate it in the Preference, but then it said I installed multiple versions. So I went to the addons folder to manually delete the animation_nodes folder. But I couldn't find the folder. Did this only happen to me?

**Comment by OmarEmaraDev** [comment]
There are three directories where it could be stored. You will need to check all of them. See https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html. Also, the add-on information in Blender should point you to the directory.

**Comment by mousery** [comment]
I solved the problem. Thanks for the quick reply
