### ISSUE TITLE
Proposal: Instance Object in Scene-Specific Collection

### ISSUE THREAD

**Issue by jekor** [JacquesLucke/animation_nodes#1841]
When working on a multi-scene file with a node tree for each scene, instanced objects appear in all scenes, presumably because the `Animation Nodes Object Container` collection is shared between the scenes. I can disable the `Add to Main Container` setting on the Object Instancer node, but doing so pollutes the root collection. I also see no way to move an object to another collection with the available nodes, only to link it.

The most convenient solution would seem to be:

1. a setting for the Object Instancer to add to a scene-specific container (instead of the main container)
2. a collection input for the Object Instancer (optional)

The first option would remove the need to manually create and name an animation nodes container for each scene and remove the need for a Scene Input node for every Object Instancer node. I image this could be implemented as a select such as `Add to: Main Container | Scene Container` (instead of the boolean toggle currently).

Note: My use case is for a project that involves one scene rendered with Bloom enabled and another without, which are then composited together. However, I'm new to blender and don't know if this is the best workflow to achieve this.

![1648397143](https://user-images.githubusercontent.com/136132/160290293-19c18e56-b7a2-48e1-acb4-655f5e0dd72e.png)

**Comment by OmarEmaraDev** [comment]
> I also see no way to move an object to another collection with the available nodes, only to link it.

Isn't moving an object the same as linking it? Can't you just unlink from the existing collection and link to your preferred collection?

**Comment by jekor** [comment]
I didn't see a way to unlink it from the scene (root) collection, but it does work to unlink it from the `Animation Nodes Object Container` (pictured). However, it still means that:

- I have to manually create a unique collection.
- I have to add 2 additional nodes each time I instance an object.
- There is an empty unnecessary Animation Nodes Object Container.

I still think being able to instance an object in one of 3 places (instead of the current 2) is the most intuitive for someone managing different animations in different scenes (i.e. in the main container, in a scene-specific container, or in no container/the root scene container). But I may be alone in this and would be happy to just build the abstraction myself but would need the following to make it work:

- Allow instancing objects within groups (perhaps hidden behind an advanced option with a big warning that you might kill performance).
- Make the 3 boolean options for the Object Instancer inputs on the node (`Copy from Source`, `Copy Full Object`, `Deep Copy`).
- Add a "Create Collection" node that accepts a name (and optionally a scene/list of scenes?)

![1648614333](https://user-images.githubusercontent.com/136132/160751227-61271d2d-19cd-4d40-9edc-7c4e6d89d2fc.png)

**Comment by OmarEmaraDev** [comment]
There is a technical reason why we don't want to make the instancer node more flexible, and it is not something to easily work around unfortunately. To make the instancer node reasonably fast, we designed it such that it only adds object at the first execution and it has no effect on latter executions if the source didn't change. This means that if we add options like you are suggesting, changing them will not have an effect, because they are too expensive to track. So I am tempted to say this is not something that we will consider.

**Comment by jekor** [comment]
OK. Given that the `Add to Main Container` option exists and the collection that the instance appears in changes immediately upon changing the checkbox, it seems that at least that part of it is being tracked and could be extended to a third option (using a scene-specific container) without affecting performance?

**Comment by OmarEmaraDev** [comment]
@jekor If I understood correctly from your second point, you want the collection specified as an input of the node. The reason why the Add to Main Container works is because it is an option that essentially just resets the whole node state. We could just add a similar option in the advanced node settings to choose a custom collection, maybe that's what you meant already? Would that be a satisfactory solution?

**Comment by jekor** [comment]
Yes, we can disregard my second point about inputs, instancing in groups, etc. The option alone would be sufficient. Here's the relevant part of the dialog (top) and what I'm proposing (bottom).

![1648781224](https://user-images.githubusercontent.com/136132/161185373-448fc950-a1b6-41cd-b6f0-8cb45f81e0a1.png)

**Comment by OmarEmaraDev** [comment]
Implemented in a0e2ee3. Thanks for the suggestion!
I also generalized the tracking logic to work for collections, so collections can now be specified as inputs.
