### ISSUE TITLE
Assign script, with 'script node'

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#185]
Hi right now if I want to append node tree, that is using some script nodes, I have to append each script too. This is bit complicated.  It would be great, if scripts were saved inside 'script node', so after appending node tree, all scripts would be imported automatically.

**Comment by JoseConseco** [comment]
Maybe 'scrip node' could have string property, that would hold script code?

**Comment by JacquesLucke** [comment]
Yes something like that is the way to go.

I also have to find a way to use a created script node more than once in the node tree more easily
