### ISSUE TITLE
Unable to create Sound List 

### ISSUE THREAD

**Issue by nasrullah378** [JacquesLucke/animation_nodes#1855]
In older version I used to create a SOUND LIST, Now I am unable to create multiple dialogue sounds list to use for lip synce with shape keys.

**Comment by OmarEmaraDev** [comment]
Doesn't seem like this was supported before, not sure why, but I guess it can be added.

**Comment by nasrullah378** [comment]
> 

Thanks please. I got the solution. I added nod "SOUND FROM SEQUENCE" that worked for me.
