### ISSUE TITLE
Constraints stop working with object visibility node attached to subprogram loop

### ISSUE THREAD

**Issue by wavestorm** [JacquesLucke/animation_nodes#1858]
When changing the visibility of objects in a collection using the Object Visibility Node and a Subprogram/Loop Input node, all constraints on the objects stop working when the Interface Lock option is checked during a render. This issue does not occur when the Lock Interface option is not checked, or when using an object visibility node outside of a Subprogram Loop.

Using AN version 2.3.0 with Blender 3.1.2

![Blender_AN_Constraint_Bug](https://user-images.githubusercontent.com/18644561/167486128-80593090-bbfd-4f92-9e40-820b667e0404.png)
.

**Comment by OmarEmaraDev** [comment]
Does that happen even when the visibility is enabled?

**Comment by OmarEmaraDev** [comment]
Seems to be a limitation in Blender. But I implemented a workaround in 7a74e31. Thanks for the report!

**Comment by wavestorm** [comment]
Great, thanks for looking into it.
