### ISSUE TITLE
Particles' position does not update for the unborn and dead particles at the start frame

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1859]
Particles' position does not update at the Start frame even if change particle settings or press the "Jump to Start Frame" button. 
![screen](https://user-images.githubusercontent.com/30294746/168029541-e4d98683-a510-4f51-bec5-6381fd44ffb0.png)

**Comment by OmarEmaraDev** [comment]
It seems Blender no longer resets the particles internally, so there is probably nothing we can do.
