### ISSUE TITLE
Viewer Node Is Created in a Weird Place.

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1862]
I have no idea what's going on.
https://user-images.githubusercontent.com/55994236/173417938-aeda1381-853c-42b1-8108-e613a7be3fb8.mp4

**Comment by OmarEmaraDev** [comment]
I can't replicate that myself. Does this happen in a particular version of Blender or in all versions?
Do it also happen with factory settings? Perhaps it is a UI scaling thing?

**Comment by Gerstmann-Bradley** [comment]
I think it's just latest AN 2.3 python 310 for windows.
I didn't check other AN/Blender version.
This is purely an accidental finding.
Now I can't even replicate it in the bug report file, while I didn't change anything in file, blender or AN.
(In fact even in the recording there's an instance that the bug didn't occur)
I will close for now until I encounter this again or so.
