### ISSUE TITLE
Using multiple script subprograms causes Errors

### ISSUE THREAD

**Issue by Spiderguy-F** [JacquesLucke/animation_nodes#1864]
When adding script subprogram nodes (ca. 3-5), the tree often gets it's red error frame. Usually deleting the new script node solves this, but when it has happened once, I can't add any more script nodes. 

  File "execution: 'NodeTree'", line 3, in <module>
NameError: name '_subprogram_jt3dtw48882bgu0' is not defined

Apparently when I quit Blender, load a afile with a working node tree, I can rescue my file by reloading it afterwards, but at this point I still can't add any more script nodes.

**Comment by OmarEmaraDev** [comment]
Can reproduce, looking into it.

**Comment by OmarEmaraDev** [comment]
Fixed in 7f310f20. Thanks for the report!
