### ISSUE TITLE
Last version to work on 2.79?

### ISSUE THREAD

**Issue by DNDEBUG** [JacquesLucke/animation_nodes#1866]
Hello there, i want to know what is the last version that works on 2.79
i couldn't find this info anywhere so i had to ask

**Comment by OmarEmaraDev** [comment]
That would v2.0 as the latest official build: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0
And experimental v2.1 as the latest experimental: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_testbuilds_2

**Comment by DNDEBUG** [comment]
Blender is crashing when i try to enable it
i'm using this version here
https://download.blender.org/release/Blender2.79/latest/
blender-2.79-e045fe53f1b0-linux-glibc217-x86_64

**Comment by OmarEmaraDev** [comment]
Crashes or shows and error?
Can you attach the crash log created by Blender? https://docs.blender.org/manual/en/latest/troubleshooting/crash.html

**Comment by DNDEBUG** [comment]
Crashes, no crash log
and running with debug option gives nothing extra

**Comment by DNDEBUG** [comment]
:/ i have no idea how to start
--debug-all doesn't help either

**Comment by OmarEmaraDev** [comment]
Why do you need 2.79 anyways? Maybe what you need can be achieved someway different?

**Comment by DNDEBUG** [comment]
>Why do you need 2.79 anyways?
because i am tired of what blender has become :sob:, basically bloatware
i want to go back to the old comfy time
i wish there was a 2.79 fork

**Comment by FinnT730** [comment]
bloatware?
What is in Blender that is bloatware now?
It still has all the things from 2.7, but extra stuff, and is generally faster.
I do not need a expensive houdini license now to create stuff from nodes with Geo nodes.

**Comment by DNDEBUG** [comment]
> bloatware? What is in Blender that is bloatware now? It still has all the things from 2.7, but extra stuff, and is generally faster. I do not need a expensive houdini license now to create stuff from nodes with Geo nodes.

https://en.wikipedia.org/wiki/Software_bloat
https://en.wikipedia.org/wiki/Feature_creep

Blender only gets More features and bug fixes
it never gets improvements for older tools like maya for example
Blender depends on 3rd-party developers to create add-ons to improve blender

Corporations decide what new features blender will get, [the fund page](https://fund.blender.org/) is just corporations and nft trash
see the last features blender got, not much interesting for users
modeling? trash, Texturing? trash, and much more
but it does get lots of good features for movie companies

Godot for example, they get money but they decide what to do with it

Blender Has become Bloatware and feature creep
and no, it is not faster than 2.79

**Comment by FinnT730** [comment]
Blender has gotten way more improvements then most people think.
One of which, CyclesX, something that rendered my scenes just 10x faster.
The sculpt tools, even with a 2.6 million poly model, I can still just use the Cloth brush just fine and fast. No slow down / lag or whatever (in the alpha / beta versions, yes this was a issue, not anymore)
And oh yea, before I forget, the compositor got fast enough to be able to be used in the viewport, in real time.

If blender was really bad at performance, you could not do stuff like Geo nodes in real time (as shown in the "Build anything" section on the release nodes) [link](https://www.blender.org/download/releases/3-1/)
Sure, this can be done by addons in 2.79, but that means I am now relying on addons to do the work for me. Now blender can do most of the work for me, natively. and IIRC, form what I have seen, this does not run on Python either (like most things in Blender) but on the C++ layer of Blender

**Comment by DNDEBUG** [comment]
These are great really, but not for everyone
CyclesX is faster, Sculpting can manage millions of polygons, compositing is faster
really great, but these aren't essential, If i'm making a cartoon style model i'm probably just going to use Eevee or pure OpenGL rendering
Sculpting can manage milions of polygons, thats great for people who work with sculpting
Compositing is faster now, thats great
Geometry nodes are incredible
but these are very niche tools

Blender gets more features and bug fixes, but the older code never gets improved
Why can't the knife tool be improved?
Material nodes are great, but managing materials is really clunky
Subdivision is one of the most used modifiers, but it only has 2 options, "Catmull-Clark" or "Simple", would be great to have something like curves for example
Texturing is horrible, i got really happy when blender got UDIM, but it is a really irrelevant feature that is going to see little use for normal users

I Want usability improvements, not new features that are only relevant for the movie company or the game company
the problem is they pay the bills and the normal user don't
