### ISSUE TITLE
Boid Particle Info Node for several animations

### ISSUE THREAD

**Issue by BlendCreator** [JacquesLucke/animation_nodes#1867]
There is a Blender feature that allows particles to fight each other. 
The only problem is that at most you can only choose an animated character as the object, which means that the character appears as if he's walking when he's actually punching or taking damage. 
My idea would be a "_Boid Info Node_" that shows information like speed and health as a number, and two inputs that show the node editor if the character is attacking ,being attacked or if it´s flying.
So when a character attacks you can assign a specific animation to the character.

So that would be a way to create a battle simulation in Blender.

Thanks in advance,
Blend Creator

**Comment by OmarEmaraDev** [comment]
Sorry for the delayed response, I missed this topic.
Unfortunately, Blender doesn't provide this information, so Animation Nodes can't access it and make it available through a node.
So this is unfeasible.

**Comment by BlendCreator** [comment]
If that helps: There was a property up to version 2.79, with which you could set the health to be displayed as numbers in the boids. Thank you for the effort.
BlendCreator
