### ISSUE TITLE
Issue on Install

### ISSUE THREAD

**Issue by bdnet** [JacquesLucke/animation_nodes#1873]
I downloaded the latest .zip and i checked the box on blender to apply the Animation Nodes add on. This is what I get when I click the check box:
<img width="1505" alt="Screen Shot 2022-08-04 at 4 30 55 PM" src="https://user-images.githubusercontent.com/110635617/182947256-3d6c079c-820c-4dba-a53f-f4abd8fc2ba9.png">

**Comment by OmarEmaraDev** [comment]
Is that on an ARM Mac? Which platform are you on and which version did you download?

**Comment by bdnet** [comment]
Im on a 2021 Macbook Pro with a M1 Pro. I downloaded the "latest" on the original website

**Comment by OmarEmaraDev** [comment]
The latest on the website is an AMD64 build, not an Arm one, so your only option is download v2.2 for Blender 2.93 LTS (ARM) for now.

**Comment by OmarEmaraDev** [comment]
Also see #1836.

**Comment by bdnet** [comment]
Got it to work, thanks
