### ISSUE TITLE
i just compiled AN for blender 3.4 and python 3.10

### ISSUE THREAD

**Issue by luckychris** [JacquesLucke/animation_nodes#1874]
unfortunately after compiling and using AN, lots of nodes are working, but if i e.g. add "Text file reader" i got this error message:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/232549/185412798-96be8332-4b07-4c5d-aa4c-288a0dde9875.png">

do you have any advice for me?

System: MacOS 

<img width="239" alt="image" src="https://user-images.githubusercontent.com/232549/185412903-74082cc5-b9df-4c1e-824a-f2ae3574fac8.png">

I compiled it with the newest AN code from some days ago.

**Comment by OmarEmaraDev** [comment]
I can reproduce that. Will look into it.

**Comment by luckychris** [comment]
great, thank you!!!

**Comment by OmarEmaraDev** [comment]
Fixed in d418e9f. Thanks for the report!

**Comment by luckychris** [comment]
i downloaded branch master a few minutes ago, compiled again, and i got the same error 

<img width="805" alt="image" src="https://user-images.githubusercontent.com/232549/185762107-a1af5ae7-4eb3-4ee0-9f98-b3e0ddb61259.png">

but i checked whether your update was in - and it was...so i am pretty confused now...

**Comment by luckychris** [comment]
ok, forget it, after closing and reopening Blender, it worked like a charm!

I have to say thank you very much for the quick fix!!!!
