### ISSUE TITLE
i cant find user preferences

### ISSUE THREAD

**Issue by bananappleful** [JacquesLucke/animation_nodes#1875]

**Comment by OmarEmaraDev** [comment]
Edit > User Preferences > Addons > Animation Nodes. Or do you mean something else?

**Comment by bananappleful** [comment]
now i cant find edit

**Comment by OmarEmaraDev** [comment]
![20220905-174701](https://user-images.githubusercontent.com/25300994/188484219-434d9490-3f91-47c4-9bae-787412335eb0.png)

**Comment by bananappleful** [comment]
this helped me a lot but quick question,must i install animation nodes to find the addon because i cant find the addon but i installed it and unzipped it but instead of it becoming a file its a folder with all the assets

**Comment by OmarEmaraDev** [comment]
Yes. You should just install the zip file directly, do not unzip it.

**Comment by bananappleful** [comment]
oh

**Comment by bananappleful** [comment]
ill close this issue if it works

**Comment by OmarEmaraDev** [comment]
Can you check that an `animation_nodes` folder was created in one of the add-on paths?
https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html

**Comment by bananappleful** [comment]
whats an add-on path?

**Comment by OmarEmaraDev** [comment]
Those paths:
https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html#windows

**Comment by bananappleful** [comment]
i cant find an animation nodes path

**Comment by OmarEmaraDev** [comment]
Does unzipping the animation nodes zip file and putting it in one of the above paths make Animation Nodes appear in the add-ons list?

**Comment by bananappleful** [comment]
i cant find the file

**Comment by OmarEmaraDev** [comment]
Which file? The add-ons directly? Did you check the link above for the directory structure on Windows?

**Comment by bananappleful** [comment]
i cant find an animation nodes file

**Comment by bananappleful** [comment]
i did check

**Comment by OmarEmaraDev** [comment]
You download the zip file from [here](https://animation-nodes.com/#download) and extract it. It should give you an `animation_nodes` folder, which you can then put in the right place.

**Comment by bananappleful** [comment]
i got the wrong folder,and my free winzip expired
