### ISSUE TITLE
Drag link to add new node functionality

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1876]
Hi @OmarEmaraDev 

Is it possible to add a drag-link to add new node functionality in Animation Nodes? It is available in Geometry Nodes that make the workflow faster.
![Screenshot from 2022-09-07 12-53-01](https://user-images.githubusercontent.com/30294746/188815033-c374f156-8c4a-4c54-acef-03e7eb12e9be.png)

**Comment by Durman** [comment]
Unfortunately Blender developers does not care too much about adding new features into custom node tree.

**Comment by OmarEmaraDev** [comment]
It seems like this operator doesn't work for dynamic sockets and thus doesn't work with custom nodes.
So it will need some work to be usable for custom node.
