### ISSUE TITLE
Need an update for latest Blender Versions

### ISSUE THREAD

**Issue by cyanogenmoded** [JacquesLucke/animation_nodes#1877]

**Comment by OmarEmaraDev** [comment]
Is something not working with the latest version? Or are you asking for a new release?

**Comment by Blueria** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/7038130/191272479-7cd6d225-e252-47cc-afb9-18d26a23e0ab.png">

**Comment by OmarEmaraDev** [comment]
@Blueria The "Latest" builds from [here](https://animation-nodes.com/#download) are build with 3.10. Did you try those?

**Comment by sgozque77** [comment]
![errorblender png](https://user-images.githubusercontent.com/114153976/191734818-03fb4894-b3f3-4985-b847-3a2b80636bc8.jpg)

**Comment by sgozque77** [comment]
> @Blueria The "Latest" builds from [here](https://animation-nodes.com/#download) are build with 3.10. Did you try those?

Hello. I tried with the "Latest" version and is still not working. I am using Blender 3.2.2.
I got this error message. thank you!

![errorblender png](https://user-images.githubusercontent.com/114153976/191736168-d4aaf303-e95a-486b-93d6-7282a0f11ada.jpg)

**Comment by OmarEmaraDev** [comment]
@sgozque77 That seems like a bad installation of Animation Nodes.
Can you manually delete the `C:\Users\snt\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\animation_nodes` folder and reinstall?
