### ISSUE TITLE
Append an Animation Node Tree structure without dependencies or scene

### ISSUE THREAD

**Issue by Mehdianim** [JacquesLucke/animation_nodes#1881]
I need to be able to run multiple node trees in the same scene. Essentially 1 per animated Character.
I run into the common issue of conflicting trees when I try to append the same node tree multiple times because they come with a lot of baggage (original scene, object data etc...) Even if I update the subprogram names etc... the conflict does'nt seem to resolve.
Would be nice to be able to just append the structure so I don't have to build each tree from scratch for every character each time.
If there already exists a way to do this I'd love to learn ! 
Here's the Tree I'm trying to work with.
![image](https://user-images.githubusercontent.com/45181118/192546696-852e8446-81cf-49af-8e2f-266920ef29ee.png)

**Comment by OmarEmaraDev** [comment]
The problem is that node tree reference a specific scene and Blender automatically appends any data references by the ID you are appending. Not sure if this is something we can control.
