### ISSUE TITLE
Can't Install In Blender 3.3

### ISSUE THREAD

**Issue by cwrightlibrary** [JacquesLucke/animation_nodes#1886]
Not sure what to do, tried different versions but none worked. I downloaded the "v2.2 for Blender 2.93 LTS (ARM)" on my M1 2020 MacBook Pro.

![Screenshot 2022-10-25 at 7 06 19 PM](https://user-images.githubusercontent.com/108359193/197898539-1f12ddeb-22cb-402c-8db3-c8c3ef49106d.png)

**Comment by OmarEmaraDev** [comment]
The ARM build we provide is not compatible with 3.3. We can't provide a build suitable for 3.3 ourselves because we don't have the hardware. So you will have to compile it yourself or use a build from other MacOS users.
See #1836.

**Comment by pkej** [comment]
See  #1887  for a zip file of a compile I did yesterday.

**Comment by cwrightlibrary** [comment]
> See #1887 for a zip file of a compile I did yesterday.

Sweet looks like it works! Thanks!
