### ISSUE TITLE
Animation Nodes with python3.10 Mac giving me the following error when installing in Blender 3.3

### ISSUE THREAD

**Issue by Apzzpa** [JacquesLucke/animation_nodes#1887]
<img width="734" alt="Screenshot 2022-10-29 at 20 53 35" src="https://user-images.githubusercontent.com/116977259/198850283-8fcc6051-0dd2-4db5-9e58-52e1887d4478.png">

**Comment by Apzzpa** [comment]
I have no idea about Python or coding, or how to compile an addon myself so I thought I would raise it here. If anyone can help me I would really appreciate it. Thanks

**Comment by OmarEmaraDev** [comment]
Could this be the same as #1886?

**Comment by Apzzpa** [comment]
Hi yes, it is. Thank you

**Comment by pkej** [comment]
[animation_nodes_v2_3_macOS_py310.zip](https://github.com/JacquesLucke/animation_nodes/files/9897406/animation_nodes_v2_3_macOS_py310.zip)

Just compiled it. Works in Blender 3.3 M1 Mac, macOS 13.0 Ventura, Python 3.10.8.

**Comment by pkej** [comment]
I've installed it on 3.2, 3.3 and 3.4. I recommend running it on 3.2. In a test with 2500 instances of a bevelled box on a isosphere and an effector, there was a sudden drop when adding "mix vectors"-node.

The same file was unwieldy when reloading in 3.3 and 3.4, but it worked better in 3.2.

**Comment by Apzzpa** [comment]
Hey Paul, thanks so much for your help and advice. Really appreciate it

**Comment by Aliprandini** [comment]
Couldn't install with all that advice on Mac Intel. Blender 3.3, ventura 13. The same error is appear.

**Comment by pkej** [comment]
Get version info from the packages:

```shell
python --version
/Applications/Blender.app/Contents/MacOS/Blender --version
```
Then start Blender from command line like this:
```shell
/Applications/Blender.app/Contents/MacOS/Blender 
```

Look for:
```pre
Registered Animation Nodes
```

In the output. If not. Remove Animation Nodes. Restart Blender. Double check that you have installed the right version of animation nodes. Compare to the python version string. Install animation_nodes and wait for a while, before clicking the checkbox for activating. After activating wait even longer to make sure it registeres everything. Restart blender once more, and check the output one more time.

The important stuff is that python is at 3.10.x (mine is 3.10.8).

**Comment by Aliprandini** [comment]
As Blender 3.4 has new benefits I try it with AN2.3 compiled above with the same result:
![3423](https://user-images.githubusercontent.com/73755453/200588203-80dbcf3e-8c28-461b-b13e-33340124c8a0.png)

**Comment by pkej** [comment]
I've built it on Apple Silicone, I guess that might be the problem? I have the same error in 3.5 alpha, so I have to rumble through my head and build it one more time, I can't remember how I did it the last time. I'll get back to you.

**Comment by pkej** [comment]
This is the latest build for 3.5-alpha (hash: 485c5abedc3a), Apple Silicon, macOS 13.0, Python3.10.8. 

I tested with this file: https://bradley-animations.gumroad.com/l/sAsRo?layout=profile

[animation_nodes_v2_3_macOS_py310.zip](https://github.com/JacquesLucke/animation_nodes/files/10251739/animation_nodes_v2_3_macOS_py310.zip)

**Comment by pkej** [comment]
> Couldn't install with all that advice on Mac Intel. Blender 3.3, ventura 13. The same error is appear.

I guess cython being C-bindings I need to compile on an Intel Mac. I can't promise when, I'm off to a party, so I might forget this... Try to @pkej in a comment on this issue to remind me :)

**Comment by pkej** [comment]
You could build Animation Nodes yourself. I don't know if my older Intel Mac can run the latest versions of macOS and Apple tend to change some of their bindings now and again.

This video shows you how to install cython and build AN. Just use python3.10 and pip3.10 where the video says Python, pip, python3.7 or pip3.7.

https://youtu.be/pNDArhsuRfo

**Comment by pkej** [comment]
I just tried to install the command line tools for Xcode on the Intel Mac, and it stopped downloading after about 15%, and nothing for an hour. Therefore I can't compile for Intel Macs. I'm sorry.

**Comment by pkej** [comment]
Tested it on the Intel Mac (where I'm not able to install Python 3.10.8 in the OS for some reason) and the blend file linked above works. Test it on your mac on blender 3.4 and let us know if it works and can be distributed, @Aliprandini

**Comment by pkej** [comment]
@OmarEmaraDev I forked this repo and added "architecture x64" or similar to the yaml for build. However, I haven't been able to setup a matrix, so I can't get it to build both versions in one buld script. I think you could create a separate file just for macos_latest and architecture x64 and it will build the artifact separately.

**Comment by OmarEmaraDev** [comment]
The daily build available in https://animation-nodes.com/#download is for Intel x86 MacOS. So you don't need to comple one yourself. A daily build for ARM MacOS doesn't exist however, so you will need to compile it yourself.

@pkej Can you elaborate on that? What is the difference between x64 and x86-64 in this case?

**Comment by pkej** [comment]
I don't honestly know, I tried x86_64 and it failed, so I googled around and found that x64 should work. And my preliminary test shows it works.

Anyway, as long as I don't know how to a) add a matrix for architecture, b) just add it to macOS, and c) have it execute the matrix, I can't automate it properly to produce the ARM64 version.

OK, got you, about the download page, then I hope the guys in this thread who tried the ARM64 on intel reads your comment and downloads from the download page.

I will try to have autobuild of ARM64 so I can just rebase from you to trigger new builds. I learned some GitHub actions from all of this, and I will get to the bottom of how to compile for different architectures.

**Comment by OmarEmaraDev** [comment]
@pkej The reason why we don't have auto builds for ARM64 is that Github doesn't provide ARM64 runners in their free tier. So we are just waiting for them to add those machines to the free Github hosted runners.

**Comment by pkej** [comment]
aha! understand. Just ping me when you need me to build a new version until that happens.

**Comment by OmarEmaraDev** [comment]
@pkej Alright. Thank you!
