### ISSUE TITLE
Compile issue with python 3.10.6  'FastNoiseSIMD_windows.lib' Windows 10

### ISSUE THREAD

**Issue by rofoto** [JacquesLucke/animation_nodes#1888]
I am trying to compile against python 3.10.6 in windows 10 to install AN on blender 3.4 beta and am getting the following error. Any help would be appreciated.

`66/134:
running build_ext
building 'animation_nodes.libs.FastNoiseSIMD.wrapper' extension
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IZ:\00_SOURCES\animation_nodes\animation_nodes\libs\FastNoiseSIMD\source -IC:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python310\include -IC:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python310\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\cppwinrt /EHsc /TpZ:\00_SOURCES\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cpp /Fobuild\temp.win-amd64-3.10\Release\00_SOURCES\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.obj
wrapper.cpp
Z:\00_SOURCES\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cpp(6222): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:Z:\00_SOURCES\animation_nodes\animation_nodes\libs\FastNoiseSIMD\source /LIBPATH:C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python310\libs /LIBPATH:C:\Users\MYUSERNAME\AppData\Local\Programs\Python\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\ATLMFC\lib\x64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.20348.0\\um\x64 FastNoiseSIMD_windows.lib /EXPORT:PyInit_wrapper build\temp.win-amd64-3.10\Release\00_SOURCES\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.obj /OUT:Z:\00_SOURCES\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\00_SOURCES\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cp310-win_amd64.lib /NODEFAULTLIB:LIBCMT
LINK : fatal error LNK1181: cannot open input file 'FastNoiseSIMD_windows.lib'
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181`

**Comment by OmarEmaraDev** [comment]
Can you attach the full log?

**Comment by rofoto** [comment]
Sure here it is. 

[AN_COMPILE_LOG.txt](https://github.com/JacquesLucke/animation_nodes/files/9957341/AN_COMPILE_LOG.txt)

**Comment by OmarEmaraDev** [comment]
The real problem is due to this error:
```
'cl' is not recognized as an internal or external command,
```
The Microsoft visual studio compiler is not found, which needs to be accessible in your execution environment. Try to execute the command from the `x64 Native Tools Command Prompt` program.

**Comment by rofoto** [comment]
> The real problem is due to this error:
> 
> ```
> 'cl' is not recognized as an internal or external command,
> ```
> 
> The Microsoft visual studio compiler is not found, which needs to be accessible in your execution environment. Try to execute the command from the `x64 Native Tools Command Prompt` program.

That worked, thanks so much, not sure why VS doesn't add the build utils to PATH by default but thanks for your help.
