### ISSUE TITLE
animation nodes error: 

### ISSUE THREAD

**Issue by luckychris** [JacquesLucke/animation_nodes#1891]
i have made this simple node tree here:

<img width="986" alt="image" src="https://user-images.githubusercontent.com/232549/206855043-a48bcdc7-dfcb-4654-9b0c-15ddae02d515.png">

and i got this error:

Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/3.5/scripts/addons/animation_nodes/execution/main_execution_unit.py", line 38, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 12, in <module>
  File "/Users/chris/Library/Application Support/Blender/3.5/scripts/addons/animation_nodes/extend_bpy_types.py", line 77, in getPolygonMaterialIndices
    self.mesh.polygons.foreach_get("material_index", indices.asMemoryView())
TypeError: couldn't access the py sequence

The cube is just a simple subdivided cube like this:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/232549/206855092-0da9816a-9d4c-4e6e-8b71-3670d611f6ab.png">

MacOS, 
<img width="263" alt="image" src="https://user-images.githubusercontent.com/232549/206855103-43bb015d-105d-4638-adc0-fe1585550fcb.png">

Blender: 
<img width="223" alt="image" src="https://user-images.githubusercontent.com/232549/206855119-642c2cd0-a7ab-490e-a20f-000c58e60d54.png">

animation nodes:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/232549/206855147-a084b7fe-cdb6-44f0-a1c4-86abbcf65f81.png">

Did i make an obvious dumb mistake here?

the same blend file works in 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/232549/206855256-b6d1519d-574f-40ac-b38e-1776835e4045.png">

result: (which i expected):

<img width="729" alt="image" src="https://user-images.githubusercontent.com/232549/206855270-6a29c11b-f40d-4207-ab07-b1d68a671778.png">

and this is animation nodes version:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/232549/206855297-9af9b191-2433-4602-ba2b-59dc9cfd53f4.png">

**Comment by OmarEmaraDev** [comment]
Probably related to https://developer.blender.org/rBf1c0249f34c417.
