### ISSUE TITLE
AN not compiling for Blender 3.3.2 Windows 10

### ISSUE THREAD

**Issue by InfoTheGamer** [JacquesLucke/animation_nodes#1892]
I am not well versed in VS and compiling code, and I consistently get this error when trying to compile the SC.

`error: Unable to find vcvarsall.bat`

Honestly, if it's a lot easier, I would appreciate it if someone could compile the newest Windows 10 version of AN for Blender 3.3.2 since I have no clue what I'm doing.

**Comment by OmarEmaraDev** [comment]
You can just download the "Latest" option from here: https://animation-nodes.com/#download

**Comment by InfoTheGamer** [comment]
Works as intended. Thanks for pointing that out.
