### ISSUE TITLE
Animation Nodes can't process after error

### ISSUE THREAD

**Issue by FredRus** [JacquesLucke/animation_nodes#1893]
I have been trying out Animation Nodes 2.30 in Blender version 3.4 but realized it's a little buggy. I'm not a pro at it, but I could tell through its weird reactions: The viewer just shows none even if I clearly put in a simple float input, mesh cannot be viewed from the 3D view and some more. Can suggestion be offered on what I should do?

**Comment by OmarEmaraDev** [comment]
Is a red border displayed in the node editor? Can you open the system console and let us know if you find any errors?

**Comment by FredRus** [comment]
During the time I was running this file, yes there was a red border. I fixed the problem and hit retry and it did without errors, but I still could see anything in the viewport or the 3D viewer. The mesh object output also works and doesn't sometimes image file I've sent, 
![AN_Problems](https://user-images.githubusercontent.com/120553860/208587254-c0acccf1-c8c5-45f5-b26a-fed511bd0a5c.png)
I have tried all possible combinations of the mesh object output node, but the viewport and spreadsheet are empty.

**Comment by OmarEmaraDev** [comment]
You need to press the dot in the Mesh socket in the Mesh Object Output node.

**Comment by FredRus** [comment]
It works! Thank you, but I wish it was enabled by default. It's hard or someone to tell.

**Comment by FredRus** [comment]
The behavior I encountered has happened again. I deleted a loop node while an invoke subprogram node for it was there. I removed it and hit retry but the viewport was unresponsive.


![Red_ANpng](https://user-images.githubusercontent.com/120553860/208667405-913b423a-0ef2-4e43-87e8-b8f18e5f433b.png)
