### ISSUE TITLE
Animation node rename install error 

### ISSUE THREAD

**Issue by ChiragSharma6283** [JacquesLucke/animation_nodes#1897]
I installed animation node add on below is the error it shows 
![IMG_20230101_181608](https://user-images.githubusercontent.com/111210668/210171021-e458694b-945f-4c5d-88fc-18546c1ca938.jpg)

**Comment by OmarEmaraDev** [comment]
Just do what the error says, your directory is called `animation_nodes-2`, while it should just be `animation_nodes`.

**Comment by ChiragSharma6283** [comment]
just did that now deleted all downloads of the node and I am using Mac so compressed it now it is showing this error
<img width="688" alt="Screenshot 2023-01-01 at 9 44 55 PM" src="https://user-images.githubusercontent.com/111210668/210177591-b41d835b-b82b-43eb-b9be-8ab20204d6b2.png">

**Comment by OmarEmaraDev** [comment]
Are you on ARM Mac or x86 one? Which version did you download exactly?

**Comment by ChiragSharma6283** [comment]
I have tried all of them there are three version I tried them now I am trying to install on blender ver 2.93

**Comment by ChiragSharma6283** [comment]
success ! it got installed on ver 2.93 ! just another question I mean I tried to use it with 3.4 I mean this could be useful there too so how do I get this one there or I am doing something wrong

**Comment by OmarEmaraDev** [comment]
Are you on an ARM Mac or an x86 one?

**Comment by ChiragSharma6283** [comment]
ARM Mac/ M1!

**Comment by OmarEmaraDev** [comment]
See #1887.
