### ISSUE TITLE
How to use convert time_info into python to add animation?

### ISSUE THREAD

**Issue by derekcbr** [JacquesLucke/animation_nodes#1899]
![c02ff59646e973862cd99cad1ad1f92](https://user-images.githubusercontent.com/31892214/211130462-6f5cb56c-9c4f-41da-bd91-663463f2453c.png)
I tried to convert above animationnodes into python code. But I am not sure how to add animation?
I noticed that in mesh_object_output.py:
def ensureThatMeshHasAnimationData(self, mesh):
        if not isAnimated(mesh):
            mesh['an_helper_property'] = 0
            mesh.keyframe_insert(data_path = '["an_helper_property"]')

TimeInfo Frame links Wiggle Falloff Evolution.
if "frame" in required:      yield "    frame = scene.frame_current_final"

How to combine those?

**Comment by OmarEmaraDev** [comment]
The Time Info node just returns the value of `self.nodeTree.scene.frame_current_final`, so you can use that. Or are you talking about something different?

**Comment by derekcbr** [comment]
> nodeTree.scene.frame_current_final

Hi Omar:
According to your previous posts, I changed cython coding to generate below:
myfalloff = my_wiggle_falloff.WiggleFalloffNode.execute(my_wiggle_falloff.WiggleFalloffNode, 0, 100.0, 1.0, 0.5, 0.5, 2, 0.3)
myoffset = (0, 0, 1)
myoffsetvectornodecls = my_offset_vector.OffsetVectorNode()
myvectors = myoffsetvectornodecls.execute_List(vertexLocations, myfalloff, myoffset)

I just have no idea how to link self.nodeTree.scene.frame_current_final with evolution in myfalloff.
I tried to add animation but failed:
frame = scene.frame_current_final
context.scene.frame_set(frame)
Thank you for the help!

**Comment by derekcbr** [comment]
> context.scene.frame_set(i)
> frame = scene.frame_current_final

Thanks Omar for the reply. No real use indeed just for testing Cython.
for i in range(50):
        scene.frame_set(i)
        frame = scene.frame_current_final
        myfalloff = my_wiggle_falloff.WiggleFalloffNode.execute(my_wiggle_falloff.WiggleFalloffNode, 0, i, 1.0, 0.5, 0.5, 2, 0.3)
        myoffset = (0, 0, 1)
        myoffsetvectornodecls = my_offset_vector.OffsetVectorNode()
        myvectors = myoffsetvectornodecls.execute_List(vertexLocations, myfalloff, myoffset)
        
        try:
            meshData = Mesh(myvectors, edgeIndices, polygonIndices, skipValidation = skipValidation)
            if len(materialIndices) == len(polygonIndices) and materialIndices.getMinValue() >= 0:
                meshData.insertBuiltInAttribute(Attribute("Material Indices", AttributeType.MATERIAL_INDEX, AttributeDomain.FACE, AttributeDataType.INT, materialIndices))
            else:
                print("Invalid material indices.")
            
        except Exception as e:
            print(str(e))
        
        print(meshData)
        outmesh = bpy.data.meshes.new(name="Target")
        myobj = bpy.data.objects.new("Target", outmesh)
        bpy.context.collection.objects.link(myobj)
       
        meshDataType = "MESH_DATA"
        if meshDataType == "MESH_DATA":
            setMesh(outmesh, meshData, myobj)
        elif meshDataType == "BMESH":
            setBMesh(outmesh, bm)
        elif meshDataType == "VERTICES":
            setVertices(outmesh, meshData.vertices)
But I failed to generate animation but got 50 Target Objects instead. 
In mesh_object_output.py.py, I noticed that animation is built by below, but no idea how to proceed?
if not isAnimated(mesh):
mesh['an_helper_property'] = 0
mesh.keyframe_insert(data_path = '["an_helper_property"]')

**Comment by OmarEmaraDev** [comment]
To clarify, do you actually want an animated mesh? In that case, this will not work, and the creation of multiple meshes is expected. Animation Nodes is able to animate meshes because it executes on frame changes and adjusts the mesh directly instead of creating a new one.

**Comment by derekcbr** [comment]
> To clarify, do you actually want an animated mesh? In that case, this will not work, and the creation of multiple meshes is expected. Animation Nodes is able to animate meshes because it executes on frame changes and adjusts the mesh directly instead of creating a new one.

Got it! Thanks!
