### ISSUE TITLE
I wish there was a way of organizing parts of node tree into library of presets.

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#190]
It would be great, it there was easy way to save, share nodegroups, so that user could build setups of most repetitive task into library of presets...
In cycles node groups do that, you can share it, and user do not have to know what is inside this node group. And then you can add this new group into blender startup file, so it is easily available in new project.
We can copy/paste nodes, but it't doesn't give us easy way of organizing snippets on node tree.

**Comment by og76** [comment]
I was just talkin bout something like this in #189 , but it's not the only way...

truth is, today **you can just create a group and put it in a separate node tree** (named suggestively) and then you can get it like any B group. (+Do consider that if u have a script node in it, u have to also import the respective text file...)

I'm not saying that there should not be another way...


the node trees in py like AN, sverchok etc are already in the group trees area, so all the trees here are visible and sharable. It's just not obvious. And the tendency is to have it all in one tree

example [AN grouping and sharing.blend](https://drive.google.com/file/d/0BzzAoBwXO8dsTUloWjdTeWo5MzQ/view?usp=sharing)
see the trees..
then go to another file and append from the file/node trees/respective group ...

**Comment by JoseConseco** [comment]
OK. Is see how it works.
About scripts I already requested here https://github.com/JacquesLucke/animation_nodes/issues/185
ability to save scripts inside 'script node'
One problem I have is that Sverchok, AN, and cycles material groups are all placed in 'nodeTree' folder. It is hard to manage and find what you are looking for. Anyway I agree with what you said in #189.
