### ISSUE TITLE
Geometry Node does not evaluate for AN-instanced objects

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1900]
Hi.
Here is a setup in which a cube object is instanced with AN that has Geometry Node Modifier (has offset parameter). When I try to control the parameter (Geometry Nodes Modifier) of the instanced objects, it does not update ([video](https://blenderartists.org/t/geometry-nodes-development-discussion/1382153/273?u=3d_singh)).
[AN_Issue.zip](https://github.com/JacquesLucke/animation_nodes/files/10472360/AN_Issue.zip)

![AN_Issue](https://user-images.githubusercontent.com/30294746/213871934-db836631-3abd-47ea-a19b-cf2c42f57ef3.png)

**Comment by OmarEmaraDev** [comment]
Seems to be a known issue for Blender, not really specific to Animation Nodes. https://developer.blender.org/T87006

**Comment by Durman** [comment]
In Sverchok we use `obj.data.update()` to solve the problem (only works with mesh as far as I concern).

https://github.com/nortikin/sverchok/blob/978928866e68dfeda497446aaa4ce25153c5a7d1/nodes/viz/geo_nodes_viewer.py#L254
