### ISSUE TITLE
Animation nodes for blender 3.3.1

### ISSUE THREAD

**Issue by IllianDeCube09** [JacquesLucke/animation_nodes#1901]
I followed the third option as I have no idea how to do the first two
Looks like addon development is frozen for some reason

![изображение](https://user-images.githubusercontent.com/68920871/216155212-e738a3c9-9fab-4a86-a071-8689b65858c5.png)

**Comment by OmarEmaraDev** [comment]
Did you download the "Latest" version from here? https://animation-nodes.com/#download

**Comment by IllianDeCube09** [comment]
Yeah, it worked, thanks.
But why don't you add this release to github repository?

**Comment by OmarEmaraDev** [comment]
It is, just as a pre-release https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build.

**Comment by thecircleoflifefree** [comment]
Any roadmap for official release on 3.6?

**Comment by OmarEmaraDev** [comment]
That's unlikely as development on AN is stalled for now.
