### ISSUE TITLE
Animation node values not updated on render animation

### ISSUE THREAD

**Issue by ulmemxpoc** [JacquesLucke/animation_nodes#1902]
From https://blender.stackexchange.com/q/285322/50044#comment490755_285322.

> # Issue
> 
> Render with <kbd>ctrl</kbd>+<kbd>F12</kbd> always shows the value in timeline at the time of render (`10.0`), but want current frame number. How can I fix number shown in animation render (important: must not be static render) to be frame number?
> 
> Seeking in timeline with `Sequencer and Preview` works fine.
> 
> All frames of render are:
> 
> [![render][1]][1]
> 
> but want `1.0` for frame #1, `2.0` for frame #2, and so on.
> 
> # Attempted solve
> 
> - Nodes: `Overview` --> `Bake to Keyframes`
> - Use older animation nodes: [Python version mismatch](https://blender.stackexchange.com/q/264417/50044)
> 
> 
> # Setup
> 
> ## VSE
> 
> - Add text strip
> 
> [![vse][2]][2]
> 
> 
> ## Animation nodes
> 
> - Add nodes and connect: `Time Info:Frame` --> `Data:Convert to Text:Text` --> `Text:Text Sequence Output`
> 
> [![nodes][3]][3]
> 
> 
> # Environment
> 
> - Blender: latest ([3.4.1 for Linux](https://www.blender.org/download/release/Blender3.4/blender-3.4.1-linux-x64.tar.xz/))
> - Animation nodes: latest ([`animation_nodes_v2_3_linux_py310.zip`](https://github.com/JacquesLucke/animation_nodes/releases/download/master-cd-build/animation_nodes_v2_3_linux_py310.zip))
> 
> 
> # References
> 
> Based on https://blender.stackexchange.com/a/73975
> 
> 
>   [1]: https://i.stack.imgur.com/ZI6NZ.jpg
>   [2]: https://i.stack.imgur.com/FQuVH.png
>   [3]: https://i.stack.imgur.com/kariu.png

**Comment by OmarEmaraDev** [comment]
Due to [T46343](https://developer.blender.org/T46343), where the necessary handlers don't execute, so we probably need to check for render-pre handlers as well.
