### ISSUE TITLE
Strange Behavior of Distribute Matrices (or Bug in Transform Vector?)

### ISSUE THREAD

**Issue by aiayou** [JacquesLucke/animation_nodes#1906]
"Distribute Matrices" node's "Matrices" output and "Vectors" output have different positions in my node tree.
Everything was working as intended, but suddenly "Distribute Matrices" node started to output wrong vectors.
<img width="630" alt="Screenshot 2023-02-19 144232" src="https://user-images.githubusercontent.com/62569151/219930156-2a40c5ca-1f0d-47a6-ad46-6fdb5c0fb03a.png">
Here you can see that "Vectors" output of "Transform Vector" node is identical to the "Vectors" that "Distribute Matrices" output, which shouldn't be the case.
I plugged "Matrices" and "Vectors" into 3D Viewers and this is how it looks like: 
<img width="500" alt="Screenshot 2023-02-19 144250" src="https://user-images.githubusercontent.com/62569151/219930987-6016ff8a-69e3-4496-a52b-7f02b4cb63df.png">
It seems to me that somehow "Transform Vector" node modifies vectors list before itself. Not sure if it's a bug, or I'm missing something.

Here's zipped blend file.
[Kana Loop Background.zip](https://github.com/JacquesLucke/animation_nodes/files/10776192/Kana.Loop.Background.zip)

**Comment by 3DSinghVFX** [comment]
Hi. 
Thanks for reporting this issue; it is a bug. I have added the patch for this: https://github.com/JacquesLucke/animation_nodes/pull/1907
