### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by HiIamKiki** [JacquesLucke/animation_nodes#1909]
![image](https://user-images.githubusercontent.com/72176255/222031718-32ccf809-1e86-47a7-85b1-ea5f31a57b60.png)

**Comment by HiIamKiki** [comment]
FYI - I am using the latest version here: https://animation-nodes.com/#download
My blender version is 3.4

**Comment by 3DSinghVFX** [comment]
Hi.
Please try the Latest Version of Animation Nodes from the [Release Page](https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build).
