### ISSUE TITLE
Multiscene support?

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#191]
Currently many nodes use the current scene to get data like the current frame. There may be some unwanted behaviors if the user switches to another scene.
To avoid these problems many nodes whould need a scene input socket (which can be hidden by default).
The main question is if it is worth the effort or if we should stick to the current one-scene-only approach.

I have to investigate scenes a bit more to decide that, because I never really used more than one while working on a blender project.

**Comment by og76** [comment]
I use multiple scenes sometimes
even for same shot, to render some layers Cycles and some BI

however, in a more serious setup, some scenes are made out of various appended/linked data from other blends. 
or in vse you may just have 2-3 scenes

ps:
layers hidden are also not updating . or not always.. Related?

**Comment by JacquesLucke** [comment]
No that shouldn't have anything todo this layers.

So should I create a scene input for the Time Info node for example?

**Comment by og76** [comment]
**time is a dangerous part**. As long as things are not updated but for current scene (as of today B), this may be useless, or misleading. 
On render some things happen so if u relay on having different time on render layers, there will be a surprise. *If the whole setup works great but fails on render, that is the worst fault.*

**We do need scene access for various other things**, for example objects in scenes that are not current (today you cannot access that but by hard bpy... expression)

ok. What is the case where I need different times?
how will it work? will it update respective scene to that frame? don't think is possible ... unless B allows

ps:
**I do use different scenes, but usually synchronized. **
for example, same objects etc, but different camera, that goes closer for a zoom. then u combine the zoom over original in compositor for magnifier effect ...
