### ISSUE TITLE
Not opening for Mac

### ISSUE THREAD

**Issue by Trtle-T** [JacquesLucke/animation_nodes#1911]
I've tried installing the Add-on multiple times, and I get this error each time.
<img width="647" alt="Screen Shot 2023-03-26 at 4 54 32 PM" src="https://user-images.githubusercontent.com/128990265/227804316-90d6af25-27e4-4585-a46e-d325d5c7d3ae.png">
I'm using MacOS and Blender 3.2.2
When I go to install it and it prompts me to choose a file, I import the .zip file. I don't know if that's the wrong way to do it, but I don't really know what else to do.
The .zip name is "animation_nodes_v2_3_macOS_py310.zip" I downloaded it from the "latest" button on the website.

**Comment by OmarEmaraDev** [comment]
Perhaps you are using an ARM Mac? In that case, see #1887.

**Comment by Trtle-T** [comment]
Yes, I am using an ARM Mac, but when I tried downloading and installing each of the files under the post, but none of them seemed to work. One of them mentioned that it would take "forever" to load, but I didn't know which part of the loading process (installing the add-on into Blender, displaying the add-on, or getting the add-on to work)
I've also recently updated to Blender 3.5, but I don't know if that changes anything.

**Comment by OmarEmaraDev** [comment]
So you tried this one? https://github.com/JacquesLucke/animation_nodes/issues/1887#issuecomment-1356246203
What is the error in that case?

**Comment by Trtle-T** [comment]
When I drag and drop the file into the install menu, nothing happens and no new add-ons appear. There is no error screen.

**Comment by OmarEmaraDev** [comment]
Maybe try unzipping the file and putting the directory in the add-on directory manually?

**Comment by Trtle-T** [comment]
It seems that I was doing it wrong this whole time, I was unzipping the file and adding the folder, and when I added the zipped file, it installed correctly. Thank you for your help!
