### ISSUE TITLE
Viewer does not show box with information

### ISSUE THREAD

**Issue by kwyntes** [JacquesLucke/animation_nodes#1913]
![image](https://user-images.githubusercontent.com/78665317/231766113-4eeefb2d-a3c5-4c21-bbac-07f3141cd246.png)

As far as I know, the viewer should create a little textbox under it containing the input data, however I seem to only be able to view the data by outputting it to a text block.

**Comment by OmarEmaraDev** [comment]
Can you toggle the system console and see if there are any errors printed?
