### ISSUE TITLE
Animation_Nodes nodes show up in Serpens3 when using shift+a search

### ISSUE THREAD

**Issue by BrahRah** [JacquesLucke/animation_nodes#1916]
Here is the log: https://paste.ofcode.org/3b53dGJ4cYGAnYQpsVbNZ3L

Pic of the animations node in SP3:
![Screenshot 2023-05-09 08:58:27](https://user-images.githubusercontent.com/40721994/237018694-15ffc430-303e-4709-b9a1-053926401bea.png)

I'm using animation nodes 2.3.0 in blender 3.4 (linux)

**Comment by OmarEmaraDev** [comment]
This should be fixed in d302171a4aa8f0ed5a050520327ff2c6ad2228e0. maybe you using an outdated version?
