### ISSUE TITLE
Pause/Block executing current node tree.

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#192]
Today I worked with two node trees setups in one scene.  First node tree was complex and slow. I was working on second node tree, which was faster, but it lagged, because every time I hit "force update" or I changed some parameter, first node tree was also executed. 
I wish there was some some button 'Skip Update' or 'Disable' to turn off node trees, that I do not want to update.
![image](https://cloud.githubusercontent.com/assets/13521338/9369888/95dd0baa-46cc-11e5-8b69-3bb19bdd3d40.png)

**Comment by JacquesLucke** [comment]
Well there is a way in the current master version. You can use the "Update Settings" node.

btw: this is already planned (and partly implemented) in the refactor branch. You will be able to set the "Auto Execution" properties on a per node tree basis:
![auto execution](https://cloud.githubusercontent.com/assets/5881326/9370105/1753d08c-46ce-11e5-9d02-0bc1c38fa4bd.PNG)

**Comment by JoseConseco** [comment]
Ah, my bad I didn't know that. Great! and thanks for fast answer.
