### ISSUE TITLE
running animation nodes on Blender 4.0 throw an error

### ISSUE THREAD

**Issue by luckychris** [JacquesLucke/animation_nodes#1923]
i am using Blender 4.0 alpha on a Mac M1 and i get this error:

Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Blender/4.0/scripts/addons/animation_nodes/ui/problems_panel.py", line 61, in drawWarningOverlay
    rectangle.draw(
  File "/Users/chris/Library/Application Support/Blender/4.0/scripts/addons/animation_nodes/graphics/rectangle.py", line 71, in draw
    shader = gpu.shader.from_builtin('2D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'

is there already a solution for this?

the error appears even with no nodes in the node tree

**Comment by OmarEmaraDev** [comment]
Fixed in 7697f9d.

**Comment by meikasahara** [comment]
Are there compiled versions of Animation Nodes with this latest commit available?

**Comment by OmarEmaraDev** [comment]
We are currently having difficulties compiling AN for Windows, that's why the builds are delayed.
If you want a Linux or a MacOS build, I can disable Windows for now and get you those builds.

**Comment by meikasahara** [comment]
You also need to replace 3d_UNIFORM_COLOR with UNIFORM_COLOR in the viewer_3d.py file as well, because the Viewer3d node returned a ValueError as well.

**Comment by OmarEmaraDev** [comment]
@meikasahara Done, thanks!
