### ISSUE TITLE
Does not work with blender 3.6

### ISSUE THREAD

**Issue by Justiniscoding** [JacquesLucke/animation_nodes#1926]
I downloaded the "latest" version from your website, and it is telling me that the build does not work at the moment. I am on a 2022 MacBook air with an M2 chip running the latest MacOS version (ventura)

**Comment by OmarEmaraDev** [comment]
We do not have daily builds for Arm Mac, only x86. So the latest build you downloaded only works for x86 Mac.

**Comment by Justiniscoding** [comment]
OK thanks, is there a way where I can compile from source?

**Comment by Justiniscoding** [comment]
Nevermind, I found out how to do it. You can compile it from source by running the follow commands in terminal:
```
cd ~/Downloads/
git clone https://github.com/JacquesLucke/animation_nodes
cd animation_nodes
brew install python@3.10
pip3.10 install cython
python3.10 setup.py build --export --noversioncheck
```
After running these commands(which will take a while) a zip file will be created in `~/Downloads/animation_nodes` that you can import in blender
**NOTE:** This will only work on a mac

**NOTE 2:** You will need the xcode developer tools installed. You can install them by running `xcode-select --install` in terminal

**NOTE 3:** You will need to install homebrew if you do not have it already by running `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` in terminal

**NOTE 4:** For future blender versions, a different version of python may be required. To check the python version used by your version of blender follow the guide at https://blender.stackexchange.com/questions/45528/how-to-get-blenders-version-number-from-python/45529. If your blender version does use a different python version, replace the numbers 3.10 in the commands with the new python version number.
