### ISSUE TITLE
Every socket in Animation Nodes appears pink in Blender 4.0 and 4.1

### ISSUE THREAD

**Issue by meikasahara** [JacquesLucke/animation_nodes#1927]
Platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.35 
Graphics: 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
Blender version:  4.1.0 Alpha, branch: main, commit date: 2023-10-03 05:41, hash: 818ae7b1499b

This is an example of the sockets as they appear in Blender 4.1.
![image](https://github.com/JacquesLucke/animation_nodes/assets/29499027/b32fa2d5-7f37-440c-8592-5f2525d4b5b4)

The nodes work properly. Only the sockets appear pink, regardless of socket type.

**Comment by OmarEmaraDev** [comment]
This is a Blender bug, reported in [112716](https://projects.blender.org/blender/blender/issues/112716).
