### ISSUE TITLE
Few ideas (creating new object in AN, parenting, Object Visibility/Select-ability/RenderVis)

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#193]
Some thoughts I had while working with AN:
- we can create instance in easy way, but what about creating new Object in AN? There could be node 'Add obj' or 'Add null Obj'. We could add mesh data to it with 'set mesh on obj' node. May be usefull
- by default objects created in AN are parented to autogenerated null. But I often see people copy loc, rot, scale from one obj to another, to emulate Parenting. I'm not sure how optimal it is (in terms of script speed). New node 'Parent to', 'Clear parent' would be nice.
- Sverchock has great feature on geometry output node. That is ability to enable/disable object select-ability, render-ability, visibility. We can do this now using outliner and ctrl+clicking on parent autogenerated empty. But if previous point gets implemented in anim nodes, then it wont be so easy. It would be great to have option to enabe disable those properties, directly in Instancer node.  I guess we can do this with 'attribute input/output' node, but the way it is implemented in Sverchock is convenient. Sverchock bmesh output node has also ability to: group output mesh, 1 click select/deselect generated objects, assigh material. Useful stuff imo.
![image](https://cloud.githubusercontent.com/assets/13521338/9372217/43dcdc76-46dc-11e5-9404-0d7cdaf16ea0.png)

**Comment by og76** [comment]
- set mesh on object / set spline on object just creates the empty target (the (+) button!)
- for 2 and 3 I used obj attribute node, separated or in a loop. 
would be convenient to have otherwise.

**Comment by JacquesLucke** [comment]
1. This is planned for the future because it will be easier to make operators with the nodes that you only execute once.

2. you know the right side bar in the node editor? Quite a few nodes have some advanced properies which aren't displayed in the node directly because that would would not look good. The object instancer has a checkbox there you can toogle to have unparented objects. The main reason for this paren object is to keep the outliner clean

3. I won't put that into the mesh output node but in general this is a good idea for an extra node.

**Comment by JoseConseco** [comment]
ok, I see now that instancer has parent option on right panel. And 'obj attribute' node works for parenting, so there is no need for parent node.
3. Actually hiding, restricting selection or rendering, works with 'obj attribute' node too. So no need for that too. Thanks for answers! I'm closing this

**Comment by og76** [comment]
Just to note:
The Instancer right panel button is actually "Baking" the objects by "Unparenting". 

It does not just set the parent/no parent. From that point on, those are current B objects, not monitored by it.
