### ISSUE TITLE
ImportError: dlopen(.../implementations.cpython-310-darwin.so, 2): Symbol not found: ___chkstk_darwin

### ISSUE THREAD

**Issue by miguelmorin** [JacquesLucke/animation_nodes#1934]
I have Blender 3.2.2 running on macOS High Sierra (yes indeed!). I download animation-nodes, version 3.10 for macOS from https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build , and copy it to the Blender add-ons directory. I go to Preferences to enable it and I see this error:

![Screen Shot 2023-11-20 at 5 19 54 PM](https://github.com/JacquesLucke/animation_nodes/assets/32396311/bd40a6e3-7f93-4cef-b6b8-9e0167d26dfe)

It seems to work out-of-the-box for other people, and I couldn't find this particular error related to `animation-nodes` or in general, so I'm reporting it.

**Comment by OmarEmaraDev** [comment]
The builds you downloaded are for x86 Mac. We do not provide daily builds for ARM Mac. See my comment here: https://github.com/JacquesLucke/animation_nodes/discussions/1933.

**Comment by miguelmorin** [comment]
Thanks for the quick reply. The host system seems x86 with Processor 3.06 GHz Intel Core i3, not ARM requiring that community build. Here is the system settings screenshot:

![Screen Shot 2023-11-22 at 4 43 53 PM](https://github.com/JacquesLucke/animation_nodes/assets/32396311/f65d3b42-1274-4ddc-b20c-b4e8531d47c8)

**Comment by OmarEmaraDev** [comment]
I see, my bad. It seems we build using a more modern version of MacOS, so older versions don't work. The lowest version we can use seem to be MacOS 11, not sure if that will fix it.

**Comment by miguelmorin** [comment]
Thank you for the clarification. I'll try the `animation-nodes` add-on again if and when I upgrade Blender to run on macOS 11.

**Comment by OmarEmaraDev** [comment]
I wouldn't close this just yet, we can try couple of things first.

**Comment by OmarEmaraDev** [comment]
@miguelmorin Can you try this build? https://github.com/JacquesLucke/animation_nodes/actions/runs/6966034741
You can download it in the "Artifacts" section. The downloaded file will contain three builds, one of them should be for MacOS.
