### ISSUE TITLE
Unable to Build .ZIP File

### ISSUE THREAD

**Issue by ewhac** [JacquesLucke/animation_nodes#1935]
I've been successfully building animation-nodes on my own for some time.  It had been several months since I updated my copy.  When I went to update and build it recently, the build failed, with Cython unable to find symbols/defs.

The build command:

    python3.10 setup.py build --export --noversioncheck

The versions:

  - OS: Debian "Sid"
  - Cython: 0.29.36

Build output attached.

[OUTPUT.txt](https://github.com/JacquesLucke/animation_nodes/files/13434411/OUTPUT.txt)

**Comment by ewhac** [comment]
...Well the build outpt was *supposed* to be attached....
[OUTPUT.txt](https://github.com/JacquesLucke/animation_nodes/files/13434405/OUTPUT.txt)

**Comment by OmarEmaraDev** [comment]
Can you try Cython 3.0?

**Comment by ewhac** [comment]
Apologies -- I'm running Cython3:

```
$ cython3 --version
Cython version 0.29.36
```

**Comment by OmarEmaraDev** [comment]
@ewhac  The 3 in `cython3` is for the 3 in `python3`. Your actual version is `0.29.36`, the latest version of Cython is 3.0.2 (released 2023-08-27). So you need to update Cython.

**Comment by ewhac** [comment]
Thank you.  I installed Cython v3.0.5 from Debian's experimental repo, and now it builds fine.
