### ISSUE TITLE
Python version mismatch, Blender 4.1a

### ISSUE THREAD

**Issue by Cubism77** [JacquesLucke/animation_nodes#1938]
Python version mismatch, tested today on Blender 4.1a blender-4.1.0-alpha+main.0fb89c2301f2-windows.amd64-release

**Comment by OmarEmaraDev** [comment]
I will update the version once all Blender builds are on the same version. Maybe in a week or so.

**Comment by Gerstmann-Bradley** [comment]
I am also looking for an update. especially it's already close to BCON3.
