### ISSUE TITLE
Windows compile error: LINK : fatal error LNK1181: cannot open input file 'FastNoiseSIMD_windows.lib'

### ISSUE THREAD

**Issue by mhzhao** [JacquesLucke/animation_nodes#1939]
I tried to compile the animation node, but it failed by giving the following errors on windows but no problems on Macbook pro M2 max:
63/123:
wrapper.cpp
C:\Users\mhzhao\blenders\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cpp(11499): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Users\mhzhao\blenders\animation_nodes\animation_nodes\libs\FastNoiseSIMD\wrapper.cpp(16011): warning C4551: function call missing argument list
LINK : fatal error LNK1181: cannot open input file 'FastNoiseSIMD_windows.lib'
error: command 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe' failed with exit code 1181

I tried in a different windows computer by refresh installations of python,cpython and microsoft visual studio, giving me the same errors.
I got succssful compilation and installation on Macbook pro M2 Max.

I am using the version of blender 4.0.2. The latest animation nodes addon of windows version from the release page (https://animation-nodes.com/) is okay to install, but having bugs about the edgeCreases, bevelVertexWeights and bevelEdgeWeights, the corresponding codes are:
line 97 -- 110 in extend_bpy_types.py
line 36 --37, 68 --69, 95 -- 100 in nodes/mesh/mesh_object_input.py

without comment out these lines, it gives errors like no attributes of edge creases, bevel vertex/edge weights, so I need to comment out them and do the compilation.

My two trying compilation environments are:
  1. Python 3.10.6 + Cython 3.0.2 + 2022 Microsoft Visual Studio Community version
  2. Python 3.10.13 + Cython 3.0.7 + 2022 Microsoft Visual Studio Community version

Appreciate any help of the windows version compilation!!

**Comment by mhzhao** [comment]
There was an exact same problem and answered already, it solved my problem, thx. https://github.com/JacquesLucke/animation_nodes/issues/1888

**Comment by indrajit-kanjilal** [comment]
Great help !!!! I just completed compilation after following #1888. Thnx!!!
