### ISSUE TITLE
Node that sets vertex positions on a mesh object

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#194]
Inputs: object, vector list
Outputs: object

This works only if the existing vertex amount is the same as in the input list so this is only useful for transforming an existing object. 
It can give us a nice speed boost because we don't need to create a bmesh first and replace the total mesh object

**Comment by og76** [comment]
+1 :grinning: 
Questions: **should that also use shape keys?**

I was thinkin of that, cause we don't have a ID key or a way to "initial verts", but the truth is, shapekeys are just that, a set of vert positions.

I see 2 ways here: 
- **1 node [set vertex positions]** that where you can also specify an existing(!) shapekey 
- **separate nodes for shapekeys [get/set]** that also include value (and others)

note: I don't put it in the mesh data, tough it really belongs there. That is cause **we should not create shapekeys now**, but just use existing for this very purpose of speed.
It is not a problem of manually creating a shapekey for 100 obj as instancer already copy that for you (deep copy). This avoids errors in managing shapekeys and a whole new set of mesh structure stuff

here's a try with quick scripts
[AN shapekeys Script 1.blend](https://drive.google.com/file/d/0BzzAoBwXO8dsQldtZXlzTmxLalk/view?usp=sharing)
![script 1](https://cloud.githubusercontent.com/assets/11709974/9382394/19a97398-4749-11e5-822d-1e4ca5057c5b.PNG)
