### ISSUE TITLE
Mesh execution problem in Blender 4.0.2

### ISSUE THREAD

**Issue by Powaildi** [JacquesLucke/animation_nodes#1941]
It seems that crease and bevel_weight are no longer exist in Blender4.0.2 (or earlier, I haven't tested every version of Blender.)
But Animation Nodes try to get them, which caused problems.
These problems can be triggered by connecting Mesh sockets or Vertex/Edge Crease/Bevel Weight.
![Issue-0](https://github.com/JacquesLucke/animation_nodes/assets/51799461/b3dba652-20e1-4b66-978c-75e2b80541c9)
![Issue-1](https://github.com/JacquesLucke/animation_nodes/assets/51799461/cb7fa99b-4ce8-4192-982e-31a60cb796be)

animation_nodes_v2_3_windows

**Comment by Cubism77** [comment]
Scatter Points node is broken too

**Comment by indrajit-kanjilal** [comment]
Major breaking updates in blender 4.0 python API is causing all mesh inputs to fail. Check out:

![Screenshot 2024-01-27 104803](https://github.com/JacquesLucke/animation_nodes/assets/43871864/c68ac80f-5e4f-4766-8a18-b18bb46e3c89)
