### ISSUE TITLE
Animation Nodes for Python 3.10 ?

### ISSUE THREAD

**Issue by chlowden** [JacquesLucke/animation_nodes#1944]
Hello
Is there a possibility to recompile the great animation nodes package for python 3.10, please ? I would to get it working with recent versions of blender. Thank you

**Comment by OmarEmaraDev** [comment]
Compiled versions for 3.11 and 3.10 are available here. https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build

**Comment by chlowden** [comment]
Sorry, I have found it.Thanks
https://github.com/JacquesLucke/animation_nodes/releases/download/master-cd-build/animation_nodes_v2_3_linux_py310.zip
