### ISSUE TITLE
Python Version Mismatch

### ISSUE THREAD

**Issue by TetraGenesis** [JacquesLucke/animation_nodes#1947]
Would it be possible to get a build for Python 3.10.13 and MacOS M1 ARM Apple Silicon? No other versions work for me, or I'm blind and can't find it.

**Comment by OmarEmaraDev** [comment]
Here you go, download the `animation_nodes_v2_3_macOS_arm64_py310.zip` build from here:
https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build
