### ISSUE TITLE
make Object Visibility nodes

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#195]
from #193 discussion
Could be 2 nodes to get/set on Object:
Object.hide
Object.hide_render
Object.hide_select

**Comment by og76** [comment]
*and here are the nodes*
[mn_object_visibility_input v1.py](https://drive.google.com/file/d/0BzzAoBwXO8dselM3VnE3VEZnUlk/view?usp=sharing) 
[mn_object_visibility_output v1.py](https://drive.google.com/file/d/0BzzAoBwXO8dsbkFWSm1wbUx0SG8/view?usp=sharing)

- I should add the following settings, as I have used some: show name / show axis / xray
- to be onest, the input is not that useful,maybe keep it hidden ..

![v1](https://cloud.githubusercontent.com/assets/11709974/9388688/c69503f8-476f-11e5-8659-332d6b4a0404.PNG)

**Comment by JoseConseco** [comment]
Awesome! It will simplify selecting objects, when scene is populated with lots of instances, and you do not want to select generated geometry. And there is no need to go to outliner every time, when new objects are generated.

**Comment by og76** [comment]
v2
**make sure to replace the old ones, the file name is different, but the internal is not.**
added name, axis, xray

I wonder about the buttons, I need them like in the obj transform out where you only affect what is checked, but it seams to grow  ...

[mn_object_visibility_input v2.py](https://drive.google.com/file/d/0BzzAoBwXO8dsdUU4VG5UQi1WUm8/view?usp=sharing)
[mn_object_visibility_output v2.py](https://drive.google.com/file/d/0BzzAoBwXO8dsNkdIZHJsOXQ1NGM/view?usp=sharing)

![v2](https://cloud.githubusercontent.com/assets/11709974/9395035/8443526e-4794-11e5-8bee-04b1ece86c8f.PNG)

**Comment by og76** [comment]
**v3 
and that's it**

*replace the old files, file name differ,  internal name is the same with old ones*
[mn_object_visibility_input v3.py](https://drive.google.com/file/d/0BzzAoBwXO8dsT3hjbGcwc2Nydkk/view?usp=sharing)
[mn_object_visibility_output v3.py](https://drive.google.com/file/d/0BzzAoBwXO8dsSTFjMWltd09QdWc/view?usp=sharing)


see the help in the right panel ... ha!
* I wonder if it make sense to have such for other nodes ... doc inside the node.
* does such (help popup) have any impact on performance?

![v3](https://cloud.githubusercontent.com/assets/11709974/9398503/675a4b50-47b0-11e5-9bfe-69fde260a5a1.PNG)

**Comment by JacquesLucke** [comment]
Such a help popup (when correct implemented) does have absolutely no impact on performance.
I also thought about it already and had a small discussion about it with guy. I think it is possible to design a system around that. :)

**Comment by og76** [comment]
I tought so. 
So it could be like the W pie, so I don't have to define the class in every node ...
Maybe I should open a dedicated issue...

Is this implementation correct? :)

**Comment by JacquesLucke** [comment]
yes lets talk about that specific issue in another issue :D

You implementation does **not** influence the performance!

**Comment by og76** [comment]
I've put them on the forum
there is no difference to the last, but the file names do not have v3...

[mn_object_visibility_input.py]
[mn_object_visibility_output.py]

however, how and when can I look into the new codelines/inline etc execution variant? 
(to update these and list nodes and whatnot .. before it lands.)

**Comment by JacquesLucke** [comment]
well you can follow my progress all the time. I upload every change I make in the refactor branch. 
I also already started with the execution system again. It works so far. And group nodes are implemented as well
there are still a lot of nodes that doesn't work correcly yet but feel free to download it and do some simple math or whatever with nodes.

**Comment by og76** [comment]
ok
(you where saying before no execution yet, but if it's there already I'll look again)
