### ISSUE TITLE
Animation nodes do not update in viewport when linked with Geo Nodes

### ISSUE THREAD

**Issue by freakinweird** [JacquesLucke/animation_nodes#1958]
Animation nodes do not update in viewport when I linked Geo Nodes parametar via expression, they update when enable/disable viewport display of the geo nodes modifier. However it works in blender 2.93LTS and python version 3.9.2.

https://github.com/JacquesLucke/animation_nodes/assets/162923746/c1fd77de-d4a8-427a-a674-c943f06f4b1e

**Comment by OmarEmaraDev** [comment]
Seems like a Blender bug instead of an Animation Nodes one. Because I can reproduce from the python console as well.
Would you be able to open a bug report in Blender for this?
