### ISSUE TITLE
Ctrl+A Typing will cause instant Crash

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1960]
![image](https://github.com/JacquesLucke/animation_nodes/assets/55994236/cfc56c56-4ece-4634-b7ea-8dfc30a4b5f1)
There are two searches, blender original one on top and animation nodes Ctrl+A below.
using Ctrl+A will cause instant crash in 4.2.

the issue doesn't occur in 4.1.1.

**System Information**
Operating system: Windows-10-10.0.19045-SP0 64 Bits
Graphics card: NVIDIA GeForce RTX 2060/PCIe/SSE2 NVIDIA Corporation 4.6.0 NVIDIA 531.61

**Blender Version**
Broken: version: 4.2.0 Alpha, branch: main, commit date: 2024-05-16 05:18, hash: `6e6ce17e3472`

**Comment by Gerstmann-Bradley** [comment]
I assume it's related to https://projects.blender.org/blender/blender/issues/121865 for now.

**Comment by OmarEmaraDev** [comment]
I can't reproduce the crash myself. Do you have a stack trace/crash report I can look at?

**Comment by Gerstmann-Bradley** [comment]
[AN Crash.crash.txt](https://github.com/JacquesLucke/animation_nodes/files/15374702/AN.Crash.crash.txt)

**Comment by Gerstmann-Bradley** [comment]
Unfortunately, despite some crash fixes in 4.2, AN crash hasn't been solved yet.

**Comment by OmarEmaraDev** [comment]
I tried to reproduce that in order to fix it in Blender or report it, but I unfortunately couldn't reproduce.
What are the exact reproduction steps? Does it happen when clicking the menu, or using the shortcut?
Does it happen when adding the node when when opening the search menu itself?

**Comment by Gerstmann-Bradley** [comment]
Basically "Ctrl+A" you see the pop up of search, and typing any character will cause instant crash to me.
I can confirm it in factory settings with AN enabled. so I don't think there are other more factors beyond blender, AN and OS.

**Comment by Gerstmann-Bradley** [comment]
I find it resolves between
Broken: version: 4.2.0 Alpha, branch: main, commit date: 2024-05-16 05:18, hash: 6e6ce17e3472
Working: 4.2.0 Alpha, branch: main, commit date: 2024-05-31 20:55, hash: `0d7d6b00c9ec`

since it's resolved, will close.
