### ISSUE TITLE
Crash When Clicking Outliner in Rendered Mode

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1964]
**System Information**
Operating system: Windows-10-10.0.19045-SP0 64 Bits
Graphics card: NVIDIA GeForce RTX 2060/PCIe/SSE2 NVIDIA Corporation 4.6.0 NVIDIA 531.61

**Blender Version**
Broken: version: 4.2.0 Beta, branch: blender-v4.2-release, commit date: 2024-07-02 18:32, hash: `edd1749e2222`

**Short description of error**
1. Open the Attached File.
2. Switch to Rendered Mode (otherwise the crash won't happen)
3. Click the camera in Outliner, should instantly crash

Would you be able to check if it's an issue of AN or blender?

[AN EEVEE Crash.zip](https://github.com/user-attachments/files/16111455/AN.EEVEE.Crash.zip)

**Comment by OmarEmaraDev** [comment]
Can you provide a stack trace, since I can't seem to reproduce?

**Comment by Gerstmann-Bradley** [comment]
would you tell me how to provide stack trace?
not sure if crash.txt can work.
[AN EEVEE Crash2.crash.txt](https://github.com/user-attachments/files/16118624/AN.EEVEE.Crash2.crash.txt)

**Comment by OmarEmaraDev** [comment]
This should be reported upstream. It is crashing in the compositor.

**Comment by Gerstmann-Bradley** [comment]
Would you help to do that and forward a ticket to here? Or I will do that.

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley It would be good if you can do that. Because I can't reproduce the crash myself.
