### ISSUE TITLE
loops/groups should update names when importing with same name

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#197]
**This maybe worth dealing with in the refactor
concerning #186 , #173 , #190**

-
When **importing tree** (append) from another file, 
a tree that **has loop with same name** (loop) 
*the loop start accepts both with same name and gets confused on callers.*

Result: manually rename one and refresh callers, but also implies reconnecting respective nodes to callers. I had to eventually force update.

now, the behavior is not quite wrong in not updating one to another (so you can manually change one's name and then refresh the callers) If such would happen blindly, it could be worse.

-

This situation should be considered when importing.
**Ideally, a warning or option panel would :**
- tell what happens (Node tree renamed to Node tree001,  2 loops with same name)
- propose renaming and allow input 
- if no input, then add random end part to name

There is also the case where I import a tree without having AN active. Then, AN could pop this as soon as it finds such in the loaded/loading tree...

One extra step to make this better is to have all names with random chars at the end, default **no simple loop** (This still leaves the situation where I manually gave same name like. So back in black, but less often, and encourage users to rename.)

-
*Example I bumped into practice:*
**Source file**
make a loop (name loop)
do something
**Another file:**
make a loop (name loop)
do something
import from Source File respective tree

=> both loops (loop start) have same name (loop)
AN confused on what to update ... lots of the caller socks disconnected
I had trouble refreshing and had to plug / unplug a lot again

**Comment by JacquesLucke** [comment]
I solved this problem already but in another way. Each node has a unique identifier now. A subprogram (loop or group (and soon also scripts)) isn't identified by its name anymore but by this identifier. So when two subprograms have the same name the "Invoke Subprogram" node is not confused and everything is stable.Beside that subprograms can also have a description now that can help when you append node trees from other files.

**Comment by og76** [comment]
good, I really used that and it was kinda scary ...
I'll have to go thru this new ui when I can

**Comment by JacquesLucke** [comment]
yeah i know.. but it works very good now in my opinion
also I had a first go to implement a way to cache data. Works pretty good so far. I tested it on multiple mesh animations. Before it took around 0.5s to calculate one frame. With the cache the playback is nearly 25fps :)
