### ISSUE TITLE
combine color and convert color node (rgb, hsv ...)

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#198]
we should have such
for now, done a full workin convert color (actually **a replacement of the rgb** that has **hsv etc**)
[here, on forum] (http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2929472&viewfull=1#post2929472)

the real deal would maybe be to have this as combine color, and another to really convert from one to another, 2 dropdowns, alternative in/outputs ...
but I just needed to vary the hue ...

**Comment by JacquesLucke** [comment]
right, this can replace the combine color node. I will look at your code and integrate it in the next couple of days. Thanks

**Comment by og76** [comment]
Just tell me if it's ok. I can do the rest. :)
I should also look into other color spaces to convert, maybe to add yuv or so
i just used here what is already in py as funcion ...

**Comment by og76** [comment]
maybe it will also help me to get into the new codelines ways  or so
I have other, more interesting things to integrate that I cannot handle immediately myself, than this or  object visib or so.
will post when can ..
