### ISSUE TITLE
Failed to control color attribute

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#208]
While trying linking like below, it doesn't work for color, but boolean attributes are fine:
![text](https://cloud.githubusercontent.com/assets/494788/10121718/7cf14b3c-652c-11e5-9354-331a000deeb9.jpg)

**Comment by JacquesLucke** [comment]
I didn't test it yet but maybe it has something todo with the fact that in an wie use 4 floats per color (rgba) but the diffuse color property has no alpha value. This isn't very pretty but you can try to use an expression:
x[:3]
This will remove the alpha value

**Comment by LeonCheung** [comment]
You are right. that solves it. Thx

**Comment by LeonCheung** [comment]
But there is no alpha setting on**Color Input** node (so far), why there is alpha output?

**Comment by JacquesLucke** [comment]
I fixed that and renamed the node to "Choose Color" because previously there was a name conflict with two "Color Input" nodes in the search
![choose color node](https://cloud.githubusercontent.com/assets/5881326/10123552/f3d516b0-653c-11e5-818a-fe976b82eed3.PNG)

**Comment by LuisBurdallo** [comment]
Hi, I am trying to control an object color but this isn't recognized as an attribute. I did copy the data path and put data. in front. Not entirely sure how I should be doing it. "color" is accepted but it doesn't change the color. So what is this color attribute for?
