### ISSUE TITLE
Vertices from polygon info master vs refactor

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#211]
Master:
![image](https://cloud.githubusercontent.com/assets/13521338/10123835/12dd82a2-6544-11e5-9def-0def40939767.png)

Refactor:
![image](https://cloud.githubusercontent.com/assets/13521338/10123840/3e6b2122-6544-11e5-9508-c7025ed5d2c7.png)
Imo, master way was better, because we could access more info in polygon vertices data. Not sure if this is bug or feature..

**Comment by JoseConseco** [comment]
To be more specific - in refactor we only get vertices locations. But in mater we get loc, normal, weight

**Comment by JacquesLucke** [comment]
Well this isn't a bug nor a feature. I found that I could archieve a major performance boost by not giving access to that data by default (3-4 times faster). I'm still working on a way to make this available optional but it isn't ready yet.

**Comment by JoseConseco** [comment]
Ok, in my case location is sufficient. So no problem for me, and speed gain is awesome.

**Comment by JoseConseco** [comment]
On a second thought, I could use vertices data from polygon. I hope maybe you find a way to get it back to refactor branch with decent speed.
