### ISSUE TITLE
Scripts cannot be linked with other nodes...

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#213]
![image](https://cloud.githubusercontent.com/assets/13521338/10124048/ac81a202-654a-11e5-9a58-69e1c8589ef2.png)

Animatin nodes, wont allow me to connect any input, output of script node  to existing nodes.

**Comment by JacquesLucke** [comment]
http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2942368&viewfull=1#post2942368

Please read that. This isn't a bug but a feature ;)
