### ISSUE TITLE
Any attribute input / output

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#214]
I wonder if it would be possible to reference or control any non-obdata attributes. I mean how can I call, for example, render resolution_y or text.sequence location in AN? Do I have to use script node?

**Comment by LeonCheung** [comment]
p.s. Oops, for text sequence location, I see it is already in the N panel. But for other props like resolution?

**Comment by JacquesLucke** [comment]
Render resolution is a property of the scene.
Currently you can acces it through the expression or script node

**Comment by LeonCheung** [comment]
Cool, Through using expression is a read-only behavior, but with drivers and custom props, I think I can drive most props in the scene. Thanks for the info. :)

**Comment by og76** [comment]
Be careful with drivers, they overwrite AN and is not clear how u can combine with an driven things.

**Expression is Not read only**. U can say:
x.location = y (where x - plug an object, y - plug the vector desired..)
or
x.resolution = y
x - plug scene from scene node etc
y - plug value

**Comment by LeonCheung** [comment]
Ah. You are right. Thanks a lot!

**Comment by LeonCheung** [comment]
Thanks guys, now I've cleaned up the subtitle converter a bit. http://pasteall.org/blend/38356

Anyway, in this case you can see why I was expecting an sorta "datablock from name" thing, check the group "Color Control" (as discussed (here)[https://github.com/JacquesLucke/animation_nodes/commit/813bd534673d099b1a55a320820b2fb82b3c9b9b#commitcomment-13538715]). Maybe there can be any better workaround?

BTW, I met another problem: When renaming the scene, the whole tree failed to work. Any idea please? Or is this a bug?

BTW*2, in this particular case, you can see the color swatch on the node is diffrerent from the one on the final texts. I think that's because the different range between them.(one is from 0 to 1, another is from 0 to 2) . Not critical, but the result is not convincible visually for sure. I assume that's something we can do nothing here?

BTW*3, this one maybe a bit off topic: @o.g. About failing to render animation, remember I mentioned on BA that the dynamic parenting case cannot render animation properly, do you think they are caused by the same "unkown" issue?

**Comment by JacquesLucke** [comment]
The scene thing is a bit complicated. I will need to test that more. The biggest problems appear when you have multiple scenes in your blend file. I would need some more info about what failed (console output would be best)

Beside that I updated the text sequence output to work with newer blender versions. There were some little changes in the api. You will have to update your node tree as well.
![text sequence output 2 76](https://cloud.githubusercontent.com/assets/5881326/10242476/61842d06-68f1-11e5-9c1c-7273aaee08b0.PNG)

**Comment by LeonCheung** [comment]
Thanks. And I've taken your advice about using further group to remove duplicated nodes, for both SRT and SBV. [v 1.2 blend file](http://pasteall.org/blend/38357). Hope it may help to simply the whole thing.

**Comment by LeonCheung** [comment]
PLUS:

![input_socket](https://cloud.githubusercontent.com/assets/494788/10242745/94455196-6925-11e5-86f1-98f9a1bdcc5a.jpg)

A bit related to the second image in #220.  it would be even better if the bottom loop can be totally saved by the possible solution above.

**Comment by og76** [comment]
![color manag](https://cloud.githubusercontent.com/assets/11709974/10242786/14d1f820-68fc-11e5-9e4c-62551c7fb09b.PNG)

datablock from name? in this case u have the datablock, so u only continue with the rest ...modifier[xxx].etc (as in the pic)

BTW2 = color management in blender (this has nothing to do with AN)
some things show in linear space, others gamma corrected
(even in the colorpicker, set rgb to 0.5 0.5 0.5 ans see the hsv as  0 0 0.78...)

if u wanna see the VSE color in the node too, go to scene, color management, display device >None


Btw3: I failed to even preview the motion, so the render I can only speculate.
was that refactor or old one?

**Comment by JacquesLucke** [comment]
I cannot have a subprogram socket. The data that flows through links is not allowed to have any impact on the state of the node (sockets etc). Only exception to that rule are nodes that must not be in a subprogram like the instancer node.

**Comment by LeonCheung** [comment]
@JacquesLucke  I see.

Another problem I noticed is that the output noodle of certain subprogram will break after being switched.

![nooble broken](https://cloud.githubusercontent.com/assets/494788/10243038/4e715ce8-6928-11e5-8287-7e21d6e13590.jpg)

Say, I switch from Loop_SRT to Loop_SBV, the output noodle will break. And I've tried to make a duplicate of Loop_SRT, then switch, it also broke.

**Comment by JacquesLucke** [comment]
Hm yes. This is due to the way it internally works. Not sure if I can do something to work around that nicely. Normally you should not have to change the group more than once in the life time of a node tree :D

**Comment by LeonCheung** [comment]
@og76 Thanks a lot for the very useful information! I've listed you and Jacques in the credit. :package: 

Here is the [updated v1.2 version](http://pasteall.org/blend/38362) for the latest AN and Blender, with a few more things added. (Just... I feel the text pre-processing subprogram can be improved, but that is all I can do based on my current limited py-regex knowledge)
