### ISSUE TITLE
Possible to support input socket for Group Input?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#219]
Basically it would be like this:
![input](https://cloud.githubusercontent.com/assets/494788/10239390/17803d04-68ff-11e5-85b4-a3733a623490.jpg)

Is it possible to save some noodles to a sub-subgram by doing so?

**Comment by JacquesLucke** [comment]
No, unfortunally this is definitly not possible..

**Comment by LeonCheung** [comment]
Alright, I don't hate noodles anyway. :P
