### ISSUE TITLE
Some nodes missing in menu?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#225]
Currently I cannot find some key nodes like Expression and Grid Mesh in the menu, instead of searching. As for other commonly used nodes, I'm not sure yet... You know, so many nodes to check... :P

btw, should the Debug interpolation node be moved to the Debug menu?

**Comment by JacquesLucke** [comment]
Ok yes. You're right. I will fix that soon. Also if you have the time, you can make that yourself and make apull request :p

btw: may I use your animations in the showreel I want to create?

**Comment by LeonCheung** [comment]
Sure, though I'm a bit busy right now. :P

And sure, Be my guest! I saw your calling for demoreel, haha. I hope I can get something better to show. But the time is a bit limited here (I was translating [Oliver's book](http://www.blendtuts.com/) for a local publisher), not sure if I could finally catch it. (what's the deadline btw?)

Do you mean that you're about to use the subtitler to add something on the screen? Then go for it. LOL

**Comment by JacquesLucke** [comment]
haha okay. Then I will make it today :)

I want to finish the demoreel before the blender conference. I have already quite many videos. I contacted some people on youtube who used the addon and I can take their vids.

Haha maybeeee, :p

**Comment by LeonCheung** [comment]
Cool. BTW, maybe you don't know I'm the member of BlenderCN.org, the largest Blender user community in China. We are very interested in this great addon. Donation is on the way... :) :euro:

**Comment by JacquesLucke** [comment]
No I didn't know that. 
Oh WOW, just got the donation. Thank you so much!

**Comment by JacquesLucke** [comment]
I don't really know where to answer to the text on paypal...

**Comment by LeonCheung** [comment]
No problem. Let's try BA message box.  :D

**Comment by JacquesLucke** [comment]
ok

**Comment by JacquesLucke** [comment]
I don't really know where to put the Expression node. It doesn't fit in any of the existing categories

**Comment by LeonCheung** [comment]
Hmm, a bit awkrard... :sweat:

**Comment by LeonCheung** [comment]
Perhaps we can have a new "Convert" category? to put all things doing converting things in, such as Convert, Convert Angle, Direction to Rotation, Quaternion to Euler, Euler to Quaternion, and... maybe Expression?  (Hmm, it seems I cannot find the q > e thing in the menu o_O? )

**Comment by JacquesLucke** [comment]
Took some time until I found out what you mean by "q > e thing" haha

Hm no, I had this 'convert' category in the beginning of the addon I think but it can get a real mess when all the totally different conversion come into one category.
Expression has nothing to do with conversion...

**Comment by LeonCheung** [comment]
I see. Then cry for Exp thing. lol

**Comment by LeonCheung** [comment]
I think that's why I proposed long long time ago that we need a "Misc" category lol

**Comment by JacquesLucke** [comment]
haha right. I remember :D

**Comment by kmeirlaen** [comment]
nice, another donation :+1: 

we added most of the missing menus now.

for reference, still missing are:

an_BlendDataByNameNode
an_ConvertNode
an_ExpressionNode
an_MixDataListNode
an_PrototypeNode
an_ObjectMeshDataNode
an_PolygonInfoNode
an_VertexInfoNode
an_LoopGeneratorOutputNode
an_ReassignLoopParameterNode
an_CharacterPropertiesOutputNode
an_ConvertToStringNode
