### ISSUE TITLE
Interpolation from curve map / copy/paste does not take vector handle type into account

### ISSUE THREAD

**Issue by kmeirlaen** [JacquesLucke/animation_nodes#226]
When changing the handle type of one of the curve handles to "Vector Handle", if you copy/paste that node the handle type is not taken into account and it is set to its default value (auto).
I noticed this when copy/pasting a node setup from one nodetree to another... :)

**Comment by JacquesLucke** [comment]
das that fix it?
Otherwise you should maybe provide an image whats wrong

**Comment by kmeirlaen** [comment]
No, it did not.
![image](https://cloud.githubusercontent.com/assets/4618798/10310907/a6d1bc42-6c44-11e5-9068-d4c3348e2e70.png)

**Comment by JacquesLucke** [comment]
now?

**Comment by kmeirlaen** [comment]
Solved!

![image](https://cloud.githubusercontent.com/assets/4618798/10311293/6c158c08-6c46-11e5-9b0e-e24d1f9cbeac.png)

**Comment by JacquesLucke** [comment]
Great :)
