### ISSUE TITLE
Interpolation from curve map / CTRL-Z causes error

### ISSUE THREAD

**Issue by kmeirlaen** [JacquesLucke/animation_nodes#227]
When using the "undo" feature of blender, the interpolation from curve map consistently throws an error. One has to press the "retry" button for the node tree to be executed again.

Error in console:

Traceback (most recent call last):
  File "C:\Users\Kristof Meirlaen\AppData\Roaming\Blender Foundation\Blender\2.7
6\scripts\addons\animation_nodes-master\execution\main_execution_unit.py", line
39, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'NodeTree'", line 10, in <module>
  File "C:\Users\Kristof Meirlaen\AppData\Roaming\Blender Foundation\Blender\2.7
6\scripts\addons\animation_nodes-master\algorithms\interpolation.py", line 220,
in curveMapping
    return min(max((curve.evaluate(x) - 0.25) * 2, -0.5), 1.5)
RuntimeError: Error: CurveMap table not initialized, call initialize() on CurveM
apping owner of the CurveMap

**Comment by JacquesLucke** [comment]
does that solve it?
