### ISSUE TITLE
Feature Request - Separate Text Object - Set Origin option

### ISSUE THREAD

**Issue by kmeirlaen** [JacquesLucke/animation_nodes#228]
Do you think it is possible to add an option to change the origin of the generated objects?
I have to change the origin of the object each time I change the text manually.

Blender has these options:

![image](https://cloud.githubusercontent.com/assets/4618798/10311184/f87528a8-6c45-11e5-927a-ffa4261b554d.png)

Maybe add a "none" as well to leave the current behaviour.

**Comment by JacquesLucke** [comment]
yes that is possible. Give me some time :D

**Comment by kmeirlaen** [comment]
No rush, it's not blocking...

**Comment by kmeirlaen** [comment]
Well, if this is not challenging enough, I could think of some more positions too :)
Like "top middle", "top left", "bottom right", etc... hehe

**Comment by JacquesLucke** [comment]
haha that would make it much more challenging :D
But I think the normal 'Set Origin' modes will be enough :p

**Comment by JacquesLucke** [comment]
![change text origin](https://cloud.githubusercontent.com/assets/5881326/10312531/f8c9eb76-6c4b-11e5-8062-825d2daae91e.PNG)

**Comment by kmeirlaen** [comment]
Works like a charm!
