### ISSUE TITLE
add guided track node (alternative to direction to rotation)

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#237]
as per pull #232 

as largely discussed with @JoseConseco on the forum regarding extra rotation around direction (track axis) for polygon dupli etc

for testing, get the [guided_track.py] (https://drive.google.com/file/d/0BzzAoBwXO8dselg3czZFTkY4aWc/view?usp=sharing)

**Comment by og76** [comment]
@JoseConseco :
if you can, please test with all possible cases,
- as vector and as matrix output,
- with 0 inputs for one or another and so on, 
- even for all XYZ variants.
I just wanna make sure it works without exception, and as expected, **especially when it comes to matrix output.**

For the node I have to deal with exceptions for  for matrix:
000 vectors that would give a 0 scale  (as the cross vectors give 000 for 000 input.) The vector is ok without those..
And I'm complicating my life with all xyz variants, to pair with classic direction to rotation.

**Comment by JoseConseco** [comment]
ok. I will test that. But for now I see one problem that may occur:
- guided track - is made of two euler rotations (up, and forward) this may cause gimball lock. Quaternion may be safer output. As far as I know it do not have gimbal lock problem
- maybe instead creating new node, just modify 'dir to rotation' node. And just add bool input 'use target'. It would be simpler sollution, and not need for new node.

**Comment by og76** [comment]
thank you.
there will be no gimbal lock here. That implies parallels, while I use cross vec and cross vec here. the cross gives 000 for the euler if axes are same, paralel etc.

the problem occurs for the matrix output, as this 3x3 matrix when .to_4x4() will have 0 scale if one of those vectors are 0 or the cross is 0. 

but now, that you said that, I just found I'm not escaping the right way, still have a 0 scale in one case... :(
I have to rethink the escaping or just drop the matrix...

**Comment by JoseConseco** [comment]
Here is test setup,
https://dl.dropboxusercontent.com/u/26878362/AnimNodes/TrackNode.blend

Where you can compare new dir track to blender trackt_to constraint.
Unfortunately guided_track node, matrix output is not predictable when one input is not connected.

**Comment by JacquesLucke** [comment]
The new Direction to Rotation node supports a guide now.

**Comment by og76** [comment]
see  #257 for the right variant
it's not that I skip the Direction variations, but the variant merged is not right as exceptions
