### ISSUE TITLE
eulers should not use vector socket, but dedicated

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#239]
I just realized that we use vector socket for euler rotation, and that is not the right vehicle.
Basically the vector socket here is used as a small list of 3. 

This gives errors in expression or script, like this:
![euler1](https://cloud.githubusercontent.com/assets/11709974/10327304/844c2666-6cae-11e5-84ea-d3602231fee8.PNG)

On the bright side, having separate euler sockets will 
- eliminate any confusion for vector direction / "vector" rotation
- allow transform node (and maybe some math..) to accept direct euler/quaternion besides matrix
[this would eliminate some extra conversions for just such ops]

-
affected nodes are:
- matrix compose / decompose
- euler to quat / q to euler
- object tranform in/out
- dir to rotation (and guided track, same) 

and *transform vector/vector list/polygon*, if we accept also euler/quat
![euler2](https://cloud.githubusercontent.com/assets/11709974/10327391/6936fd5a-6caf-11e5-931a-8c3d8b0b0e2b.PNG)

-
ps: yes, yet another socket. but I do think is better than just making vector to also present the euler data type ...

**Comment by JacquesLucke** [comment]
I thought about that before.. I think you're right..
Maybe we can even have a switch on an euler socket input wether it uses radians or degree. But found no icon for that yet that clearly communicates that so maybe I leave it away...

**Comment by JacquesLucke** [comment]
hehe amazing. Blender uses degree automatically when it is selected in the "Units" panel.
![euler degree](https://cloud.githubusercontent.com/assets/5881326/10335860/6a8f7296-6cf4-11e5-8927-644446f71ed2.PNG)

**Comment by og76** [comment]
is that just ui and the socket gives radians? or the sock also goes degree?
that is nice but could be quite confusing if different...

**Comment by JacquesLucke** [comment]
![euler output](https://cloud.githubusercontent.com/assets/5881326/10336165/0eb72862-6cf7-11e5-887e-e765cc7d386e.PNG)

That should answer your question

**Comment by og76** [comment]
hm,
 then I guess we need a "compose euler" just to 'see' radian xyz to euler ? like the compose vector ...
or maybe an advanced option ...

or not. I'll have to use this...

**Comment by JacquesLucke** [comment]
Ok you can try that now :)

**Comment by og76** [comment]
bit later, the guided track tries to kill me. I have to kill it first.

**Comment by JacquesLucke** [comment]
except for direction to rotation. Is there still an issue with eulers?
