### ISSUE TITLE
Call Validate object after setting mesh/bmesh on object

### ISSUE THREAD

**Issue by kmeirlaen** [JacquesLucke/animation_nodes#240]
So... Blender was crashing on me when I was trying to edit a generated plane.
I filled a bug report (https://developer.blender.org/T46400) and Campbell suggested to run the validation on the object.
So I did it in the sample file and indeed, the object had some invalid references:

BKE_mesh_validate_arrays: verts(4), edges(4), loops(4), polygons(1)
        Vertex 0: has zero normal, assuming Z-up normal
        Vertex 1: has zero normal, assuming Z-up normal
        Vertex 2: has zero normal, assuming Z-up normal
        Vertex 3: has zero normal, assuming Z-up normal
        Poly 0 has invalid edge reference (0), fixed using edge 1
        Poly 0 has invalid edge reference (0), fixed using edge 2
        Poly 0 has invalid edge reference (0), fixed using edge 3
BKE_mesh_validate_arrays: finished

So I had a look at my node structure. It seems the issue was that I was using
Combine Mesh Data => Set Mesh data on object.

Chaning it to
Combine Mesh data => Create BMesh => Set BMesh on Object

solved the problem :

BKE_mesh_validate_arrays: verts(4), edges(4), loops(4), polygons(1)
        Vertex 0: has zero normal, assuming Z-up normal
        Vertex 1: has zero normal, assuming Z-up normal
        Vertex 2: has zero normal, assuming Z-up normal
        Vertex 3: has zero normal, assuming Z-up normal
BKE_mesh_validate_arrays: finished

So I guess my susggestion is to have the "set mesh/bmesh on object" nodes perform a validation if the generated object is indeed valid and if not provide feedback on what is invalid.

![image](https://cloud.githubusercontent.com/assets/4618798/10331779/5710e978-6cd8-11e5-8b5c-5490bfb4de31.png)

(had to attach screenshot as .blend files are not accepted here)

**Comment by JacquesLucke** [comment]
Thanks for the report! I will change that today :)

**Comment by kmeirlaen** [comment]
No thanks, I hope these bug reports help to improve the stability of AN :)
