### ISSUE TITLE
[Idea] Create Object Group List

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#241]
I know, the group can be a list of objects itsself, but just wonder if we can have such kind of list that contains multiple object groups? Lately I found it can be useful in some cases.

**Comment by JacquesLucke** [comment]
Yes that is totally possible.
Can you give me an example use case?

**Comment by LeonCheung** [comment]
Sure. Take [this one](http://pasteall.org/blend/38442). Remember that?

There are three groups for each house, and I want to build each house from -z to z, but want to build the three houses one after another. If I put them all in one single group, they will be built together. I know there still other solutions, just appears not as convenient as a group list. What's your idea?

**Comment by LeonCheung** [comment]
Tested and works perfect! Hopefully I could make a short video to show massive architecture animation powered by AN. :D

**Comment by JacquesLucke** [comment]
Haha please do that!!
And send me the video. (You don't have to render it now, although you can of course :D )
