### ISSUE TITLE
Grid Mesh: Support Z Division

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#245]
It would be even cooler to support Z. :)

**Comment by JacquesLucke** [comment]
This doesn't work with Polygons. 
I can make another node that just calculates the points using X, Y and Z divisions in a cube. (Maybe also edges but I think that is not thaat important)
I don't know how to call this node yet..

**Comment by LeonCheung** [comment]
3D Grid?

**Comment by og76** [comment]
u can always have
 line mesh with Z > grid arrange on xy >>> 3d grid ... ;)

**Comment by JacquesLucke** [comment]
Coool idea haha. 
I'm currently working on all the Euler socket stuff but maybe after that. There are still quite a few other issues and pull requests -.-

**Comment by og76** [comment]
BTW, I was thinking that maybe poly /edge indices should fall into separate node than vectors.

That is, for ex. I made these extrusions with several variants, matrix (product..), vector list, spline etc, but in the end they all had same meshing algo. 
So I'm thinkin that algorithm may just go into a separate node so that it can be used for meshing other cases, made with a tree. The circle @kmeirlaen was doing could benefit of such extrusion, but you can also generate random circles and then, the poly indices would use same algo

ok, I'll have to show what I mean ...

**Comment by LeonCheung** [comment]
@og76  I tried, failed with an error. What is wrong with that?

![subprogram](https://cloud.githubusercontent.com/assets/494788/10338872/f75c5130-6d3a-11e5-947a-20c2a3746352.jpg)

**Comment by og76** [comment]
just that.
instancer node cannot be in a loop or group. (object instancer 001 = second instancer node..)

**Comment by og76** [comment]
also same for text separate..

**Comment by LeonCheung** [comment]
Then I was puzzled by that idea... I wonder how you make your 3d grid solution happen.  0.0

**Comment by og76** [comment]
u create the new list (blue), then use that for the normal instances (pink)

![3d grid](https://cloud.githubusercontent.com/assets/11709974/10339907/50fc97d8-6d16-11e5-80b1-b2aac6332a77.PNG)

**Comment by JacquesLucke** [comment]
![3d grid](https://cloud.githubusercontent.com/assets/5881326/10339943/1a88f14a-6d0e-11e5-8c8b-f2cad048dd3b.PNG)

**Comment by JacquesLucke** [comment]
oh within 6 seconds haha

**Comment by LeonCheung** [comment]
Thumb up to both! :100:

**Comment by Leroy-X** [comment]
the same function in Cinema 4D called "Cloner", similar to "object instancer" node, just you can set distribution in 3D space by xyz division, hope add this function by a node, maybe can set the grid shape, eg.cube and sphere, thanks to JacquesLucke & LeonCheung : )

**Comment by Leroy-X** [comment]
Hi , how about distribute instance object by the mesh volume, it's will cool, maybe called it "Volume sampling", but not for the cycles, the grid of volume, can make pixel style, like the "Pixel" film. god ,and used with rigid body, it's  great idea,ha-ha

**Comment by LeonCheung** [comment]
@JacquesLucke I think it can be simply put into the Templates list?
@Leroy-X I think volume sampling is not very likely to happen currently. As Jacques said AN is more on animation than simultion. For grid volume, you can always turn to the pure particle system. ;)

**Comment by JacquesLucke** [comment]
Yes I can make a template from that.

**Comment by Leroy-X** [comment]
I'm sure the template is good for the beginner, like me :P
