### ISSUE TITLE
generate splines by the path or index of particles

### ISSUE THREAD

**Issue by Leroy-X** [JacquesLucke/animation_nodes#248]
Hi, I'm a beginner, now you can use the "find close vertices" generate edges though  the particle system, but I don't  know how to generate edges by the local path or the index (0-1-2-3....connection the particle by the index ).  

the local path will achieve growing spline. every particle generate one path , and convert to spline, and can set the spline length by the time or special value. even can influence the shrink/fatten(Alt+S) .

and connection index of particle will make all particles connected by one spline.

just idea, cool function! sorry for  my poor English, hope you can understand! thanks :yum:

**Comment by og76** [comment]
![spline from particles](https://cloud.githubusercontent.com/assets/11709974/10367266/1733d972-6dd8-11e5-888a-4d0f3c9aa5d0.PNG)

**Comment by Leroy-X** [comment]
@og76 very thanks your idea, it's amazing, does any method to achieve generates splines by the location path of particles, each particle have one move path, and each particle generate an spline along the move path

**Comment by JacquesLucke** [comment]
this is a bit more complicated because I can only read the current state of the particle and not the whole path.
Maybe it can work with some caching but as I said, it difficult..

**Comment by Leroy-X** [comment]
maybe can make one node that can convert frames range to the list, e.g. we can Set the start frame and end frame, and step. sorry, I don't understanding programming, just one idea, thanks

**Comment by JacquesLucke** [comment]
Hmmm I will close this for now. If someone finds a good way to access cached data we should open an extra Issue extra for that :)

**Comment by og76** [comment]
see #372 for a manual way to convert cached data to mesh/spline points
then splines are just usable ..

**Comment by YorsLosilla** [comment]
Well that's a pretty decent solution for hair particles which will allow to create some cool things.

It's a potty the cache thing for emmiter particles.


-----Mensaje original-----
De: "og76" <notifications@github.com>
Enviado: ‎21/‎01/‎2016 17:44
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
Asunto: Re: [animation_nodes] generate splines by the path or index ofparticles (#248)

see #372 for a manual way to convert cached data to mesh/spline points
then splines are just usable ..
