### ISSUE TITLE
[Request] Group Name Filter

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#249]
Since we got a cool Object Name FIlter, It would be even cooler for filtering object group name. Can we do that?  :D

**Comment by kmeirlaen** [comment]
I'm not sure what you mean.

Like this?

![image](https://cloud.githubusercontent.com/assets/4618798/10366148/b2c12fee-6dc8-11e5-968c-57bc019d6fbd.png)

Or like this?

![image](https://cloud.githubusercontent.com/assets/4618798/10366204/1fda0c2c-6dc9-11e5-9929-57cf2a32a618.png)

**Comment by LeonCheung** [comment]
The 1st one. Though the other one seems interesting.

**Comment by kmeirlaen** [comment]
I guess last one can be acheived with
![image](https://cloud.githubusercontent.com/assets/4618798/10366777/ea53d156-6dcc-11e5-8b96-ef93d0194fea.png)

**Comment by JacquesLucke** [comment]
I can make a generalisation of the name filter node to work with different types

**Comment by og76** [comment]
I guess I could make it more like Data Name filter, the way object from name is data from name.

**Comment by og76** [comment]
ah, just a sec before me..
ok, u win
