### ISSUE TITLE
Option: Mute

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#250]
To temporarily enable / disable certain nodes in the tree for convenience, like what blender node system always does. Should we have one anyway?

**Comment by LeonCheung** [comment]
I feel it cannot be so universal here...

**Comment by JacquesLucke** [comment]
unfortunally I cannot use the muting in custom nodes.
Beside that it would be quite complicated because we have so many socket types:

I will close this because it is very unlikely to happen.

**Comment by LeonCheung** [comment]
No problem, I can also feel it is very unlikely to happen... :P
