### ISSUE TITLE
Request: re-arrange input/output nodes for Subprogram

### ISSUE THREAD

**Issue by kmeirlaen** [JacquesLucke/animation_nodes#251]
I would like to re-arrange the nodes of a subprogram, but current the visibility and up/down arrows for the socket inputs do not work in the panel.
![image](https://cloud.githubusercontent.com/assets/4618798/10360845/5d5e04e2-6da4-11e5-9d56-10f8ff35ce8d.png)

**Comment by kmeirlaen** [comment]
Priority: now :)

**Comment by og76** [comment]
they work in the input, not the invoke.

**Comment by kmeirlaen** [comment]
they do! thanks!
