### ISSUE TITLE
New Euler Node

### ISSUE THREAD

**Issue by kmeirlaen** [JacquesLucke/animation_nodes#253]
I'm a bit puzzled with the new "Euler" socket.
How can I achieve a vector animate for an euler? Is there a "Vector from Euler" ? Or an "animate euler"?
Also, Seems object ID Key does not have Euler yet for rotation.

![image](https://cloud.githubusercontent.com/assets/4618798/10410978/d95a7948-6f54-11e5-9f74-db15e369f55d.png)

**Comment by kmeirlaen** [comment]
Woow, just pulled the latest version, and the "not possible" is possible :+1:

**Comment by JacquesLucke** [comment]
Oh good that you say that. The euler in Object ID Key is still missing.

**Comment by kmeirlaen** [comment]
Also verify if it is set properly :)
