### ISSUE TITLE
Update ID Key system. Once more...

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#254]

**Comment by kmeirlaen** [comment]
While you are at it, can you make it also a node so we can use it. (Set Initial Transforms Node)
Node with 4 inputs (Object, Location, Rotation, Scale), 1 output (Object) ?

**Comment by JacquesLucke** [comment]
This node is possible with the current design.
What do you need this for?

Please make this suggestion into a new Issue so that I can close this one here.
