### ISSUE TITLE
random point on surface of mesh

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#255]
I made script node that is generating random point on surface of mesh. It returs point location, and polygon data - on which random point was choosen.
Is anyone interested in coding this into anim nodes from my script?
![image](https://cloud.githubusercontent.com/assets/13521338/10412468/20ce4426-6f87-11e5-89a5-f83c17a31900.png)

**Comment by og76** [comment]
interesting
where can I see the script?

**Comment by JoseConseco** [comment]
Here it is.
https://dl.dropboxusercontent.com/u/26878362/AnimNodes/SurfacePointRefactor_01.blend
It is probably not optimal, but  script uses 'weight' in two modes (I should change name for both weights as they have different mining):
if  use_weight  - then scripts uses vertices weight paint to spread more objects where vertex weight is bigger,
if not use_weight - then weight is used to reduce probability  of choosing small faces (in this case weith has nothing to do with vertex weight, so I probably should rename it to probability_weight). Without it, smaller faces would tend to get move instaned objects, so I would end with uneven distribution.
In second case algorith goes as this:
- assing weight for each face, based on face area;
- sum of weights  - is used to divide (0,1) length into parts - bigger part = more weight. 
- then I pick random point from (0,1),  and get poly form that. It is made by python function:
random.choice(Object.data.polygons, p=weights)
Here is more info about choosing element from weighted list (second method):
http://codetheory.in/weighted-biased-random-number-generation-with-javascript-based-on-probability/

**Comment by JoseConseco** [comment]
On second thought, weight should be calculated outside node. This way used would have more control:
- is weight based on poly vert weight,
- or weight based on areas
- or something else
this would requite 2 inputs: - polygon list, and - weight list.

**Comment by og76** [comment]
I've looked at it and I have a pretty good idea on how to do this, but I'm lacking 1 trick.

I don't like the fact that it uses a function that is per object. It's kind of reverse logic from what I'd do. 
I'd do per polygon and avoid needing the whole object/mesh data inside the loop.
I don't like that about any of these functions, I was also looking at ray cast that does same (well there's a new bvh tree that may do better)

However:
1.1 The factor/ resolution/ weight per poly can be taken outside like (the polygon info has area):

take area of poly, mult with a factor/resolution
factor =1 , area = 4  => 4 instances, if area =0.5 --> 0 instances (or may use a random on/off here)

So we don't need to process all faces areas in advance, but we give a resolution, not a nr of instances like in particles.

1.2 If u want a fixed nr of instances per obj, it means we have to process that in advance (it's actually doable with the nodes today..) We can get the areas per all faces out of polys and the weight out of verts per poly(indices)

Or we get the sum of areas and make a factor with the resolution (ignoring weight groups..)
Or we can use 1.1 above and get a list of positions, shuffle the list, slice to desired nr.
-

2. The rest is pretty easy, but I'm lacking a decent, simple way to distribute random points on 1 polygon. 
If I try to fake it by triangles (x=random base, y= random on height or so) it will not give a decent uniform distribution.

Still searchin for this..

**Comment by JoseConseco** [comment]
https://www.blender.org/api/blender_python_api_2_61_release/bpy_extras.mesh_utils.html
here is function: 'face_random_points()'
It does what you want. I used it in script above too. Example below - gives location of one random point  on polygon 'choosenOne'
Location = bpy_extras.mesh_utils.face_random_points(1, [chooseOne])[0].

As for raycast it may be ok, for spheres, but for more complex shapes it may give us not uniform distribution. Eg more points close to source of rays. Unless source location of rays would change location in volume of object over each iteration of loop...
And yep, I agree this node should preferably work on polygon data, not on obj data.
 factor/resolution - I like that. Seems easier to precalculate than poly area weights. But it will be problematic if, eg you scale object. Then areas would change eg. 4 times when object is scaled 2x. This would give 4x as many objects, even though no input parameter was changed. It could be solved by 'normalizing' areas by sum(all areas). So eg, when object is scaled 2x, we divide areas by factor of 2 to have same ammount of generated instances. But this is basically the same algorithm as in my node script.

**Comment by og76** [comment]
yes, I know that and looked around for other variants
for example with raycast , this, taken from fibermesh by liero 

![fibermesh](https://cloud.githubusercontent.com/assets/11709974/10488317/d3826fc2-72a0-11e5-9c43-91fae3746cb0.PNG)

but it again works per whole object. 
I just don't know a simple way to give a random per poly and I don't wanna reinvent the wheel...
