### ISSUE TITLE
RuntimeError: Error: Node type an_ConvertQuaternionAndEulerNode undefined

### ISSUE THREAD

**Issue by kmeirlaen** [JacquesLucke/animation_nodes#258]
As reported by ArtistSpot

http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2949990&viewfull=1#post2949990

**Comment by og76** [comment]
I updated the node to more operations and eventually renamed convert rotations
did not update the menu..
but in search should be ok.

**Comment by og76** [comment]
it's merged, should be ok now.
