### ISSUE TITLE
Type Conversion Failed

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#263]
Strange that the convert node cannot be created automatically if the expression output type is set as **List**.

![convert](https://cloud.githubusercontent.com/assets/494788/10448111/12f473ba-71bd-11e5-900c-a14010910de9.jpg)

**Comment by og76** [comment]
I guess it's the generic socket that is too ... generic to know what to do with it. 
The biggest problem with it it's that it may pass to certain socs data they do not accept. I've had quite some errors using the conversion node like this. 
For certain socs if u plug just the convert (no input ) it basically gives None to the sock and some just freeze. (blend data, obj, mesh etc)

However, maybe the expression should allow to chose an output type. Tough it may lead to the very same issue, serving none to mesh data or obj data...

**Comment by JacquesLucke** [comment]
Right. I prefer to have a generic output for the expression node for that exact reason.

I can make it so that a convert node will created automatically  for generic list sockets as well
