### ISSUE TITLE
Suggestion: ID Keys batch removal support

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#265]
Yeah, we can click the "Use Current Transforms" button for batch ID Key creation, but it seems we don't have a batch removal operator yet...

Another problem is: When deleting the whole ID Key category, the custom props still exist. Maybe better provide an option to decide whether or not custom props can be removed too?

Btw, what's your idea on #167 ?

**Comment by JacquesLucke** [comment]
Problem is I'm still not absolutely sure how what the best way is to implement the id key stuff.. So I cannot give clear statements yet on this topic..

**Comment by JacquesLucke** [comment]
I just rewrote the ID Key system. The rewrite is not finished yet but it is in a state that is already useable with "Initial Transforms, ..
What is still missing is the ability to easily create new id key types.
Also note that there is a new "Animate Individual Letters" template.

If you have time, feel free to test the changes in the "new-id-key-system" branch.
