### ISSUE TITLE
[Idea] Adding node stats info

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#266]
IMHO, something like **Node Count**, **Loop Count**, **Group Count**, **[Specific_Nodetype] Count** blablabla would be nice to have.

I know it's not such a functional feature. I found people always asked me "how many nodes are you using in this tree?", or, sometimes we want to compare setups based on how many nodes that were used, in order to see if it has already been optimized by using less nodes..

(Or, simply more for fun? :P)

**Comment by JacquesLucke** [comment]
Yeah. Yesterday I started thinking about an "Overview" Panel. This can be a part of it.

**Comment by og76** [comment]
Interesting, I was just lookin for some node tricks too :D
till a serious sys, may use
![node count](https://cloud.githubusercontent.com/assets/11709974/10465540/01976678-71f8-11e5-900e-2a0c0836c76a.PNG)
