### ISSUE TITLE
[Suggestion] Support vector list math

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#269]
As what the title says. Thanks. :)

**Comment by og76** [comment]
what operation would that include besides say + and  -  ?
the float math also does min max, but here that is not logical

as for any cumulative op like this, now we have the 'Reassign' in loops (adv panel)

![reassign](https://cloud.githubusercontent.com/assets/11709974/10466361/a383caf4-71fc-11e5-8fd5-6b70894fb649.PNG)

**Comment by LeonCheung** [comment]
Well, this idea came from generating bounding box center. :tongue:  First I thought it could be generated like this:
![bbox center](https://cloud.githubusercontent.com/assets/494788/10473044/56bf9556-7259-11e5-9688-7551a667cce0.jpg)

**Comment by og76** [comment]
well, if it's only for +, maybe use like above

**Comment by JacquesLucke** [comment]
![vector list math](https://cloud.githubusercontent.com/assets/5881326/13557875/001871b2-e3f8-11e5-81f2-19ba6b06520b.PNG)
