### ISSUE TITLE
Import/Export Templates

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#270]
How about build a tool for importing or exporting nodetree presets (templates)? It could be a better way for sharing and collecting py files than appending from blend files.

**Comment by JacquesLucke** [comment]
hmm i made a small operator that helps me creating these templates but I have to edit them manually all the time. I mean I could improve this operator, but some things are very hard to automate.
I find the operator when you hit spacebar end search for "Generate Template Code". After that look in the text editor

**Comment by enzyme69** [comment]
I tried this template node. For example, it is generating this code:

RandomNumber = self.newNode('an_RandomNumberNode', x = -397, y = 66)

Debug = self.newNode('an_DebugNode', x = -156, y = 68)

self.newLink(RandomNumber.outputs[0], Debug.inputs[0])


What should I do with this? I run the Python script, it gives error.

**Comment by JacquesLucke** [comment]
No this not supposed to run directly. I always tweak it manually. It just speeds up the progress of creating templates for me.
If you have a setup that should maybe be a template, you can send it to me and if its ok I can make the template from it.
