### ISSUE TITLE
Unicode Display Support

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#272]
I wonder if there is any solution to solve this:
![unicode](https://cloud.githubusercontent.com/assets/494788/10575470/3e2d22b2-768f-11e5-8165-412bb56abb60.jpg)

Thanks!

**Comment by JacquesLucke** [comment]
Hm I don't think that I have any influence on that via python... but I'm not sure..

**Comment by JacquesLucke** [comment]
Tell me if you have any idea how can possibly influence this...

**Comment by LeonCheung** [comment]
OK, I'll try to figure it out. Luckily it's not so critical.
