### ISSUE TITLE
Expression does not understand math function

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#274]
I am using version 1.0.0 that I installed 2 days ago. The expression node does not seem to understand either sin(x) or math.sin(x). Kind of strange. Maybe a bug or I did it wrong.

**Comment by og76** [comment]
in the advanced panel there is a field to specify modules to import
(say math there and it's ok)

But it is an issue, as I thought math was loaded anyway, as it used to...

**Comment by enzyme69** [comment]
aha, I got it. yes it works now. 

I need to watch for Advanced panel from now on. 

Now, it would be nice if we know what module got loaded, or some kind of indicator of option. Math is almost always the first thing I have in mind. I had wish we can just use sin(x) instead of math.sin(x).

More question, apart from math, what other module is out there that is useful or used often?

Supposed that this kind of import math module behaviour of the node might change again in the near future? I am thinking to write about Animation Node in my blog. I have to tell readers / users to always watch for ever changing nodes.

**Comment by LeonCheung** [comment]
Hey Jimmy, I think besically you can use quite amount of supported modules (there are just tooooo many...). I've seen people used numpy, and I use re quite often for regex thing, and math too, or use them all  together like "math re fractions sys" blablabla, and everything can be useful as you need it, right? :)

Btw, thanks for the nice Sverchok reviews on your site. I've learnt it a lot there. Long time ago...
