### ISSUE TITLE
Text List > Text Block List --- Failed

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#275]
![screen shot 2015-10-21 at 11 52 31 am](https://cloud.githubusercontent.com/assets/3952687/10625043/6842e17a-77ea-11e5-85e6-f4cdc0691ad5.png)

I am trying to understand the basic of subprogram and loops in AN. Seems almost all very logical, but sometimes I am stuck when Debug does not give me anything, or when my loop is not working as expected.

Basically what I am trying to do is to spawn bunch of random text, of supplied list of text.

I understand how to scatter objects using transforms, using Object Instancer for 1 object only. Soon I will need to understand how to have [LIST OF OBJECTS] and then random instance them. 

So, similar to the above problem, I am trying to make AN to:
[LIST OF TEXT] >> Create X number of text objects, in which each text get the string value from my provided text >> then scatter/animate them in 3D space.

**Comment by enzyme69** [comment]
I get this far:
https://www.dropbox.com/s/tng63nbpsnujdkt/text_list_010.blend?dl=0

Still not quite sure where I did wrong...

**Comment by enzyme69** [comment]
Ok, I figure it out. It's "Deep Copy" that I did not check.

And I had the node tree network a little bit wrong. Was sligthly confused regarding LOOP Iterator and Parameter.

Now it's good.

![screen shot 2015-10-21 at 11 52 31 am](https://cloud.githubusercontent.com/assets/3952687/10626238/d4b31268-77f8-11e5-9177-70e392deab05.png)

**Comment by LeonCheung** [comment]
[My reedited file](http://pasteall.org/blend/38707) FYI (the one s I edited)

Two cents:

1. Use Deep Copy.
2. Since you input two separate lists into one single loop, that means they have to share the same index list, in which case, AN have to use the one with shortest length. So, it is always recommended to keep the same lengths for all input lists if you have to use them in one loop.

**Comment by enzyme69** [comment]
Gotcha! Thanks for the answer and extra explanation. I will study more. Cheers.

**Comment by LeonCheung** [comment]
Btw, Imho, **Group** subprogram is almost a "simplified" **Loop** with parameter(s) only (no iteration, no index). As for **Script** subprogram can be almost the same, just more powerful.
