### ISSUE TITLE
[Suggestion] Add a create button on debug nodes

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#276]
Maybe things like this can be of a bit more conveniency?

![0](https://cloud.githubusercontent.com/assets/494788/10627509/1b4fef5e-77ed-11e5-80a0-55883ce7eaf3.jpg)

**Comment by JacquesLucke** [comment]
good idea. I will implement that when I find some time :)

**Comment by JacquesLucke** [comment]
Finally we have this too. And even much cooler now hehe

![create text block in debug nodes](https://cloud.githubusercontent.com/assets/5881326/14588230/3609c2b6-04c4-11e6-99c9-438d492a0be6.gif)

**Comment by LeonCheung** [comment]
Oh, my... can't be cooler than that!!!
