### ISSUE TITLE
The first Search menu desn't work

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#277]
So far it seems doesn't funtion at all. Maybe it can be removed from the menu or replaced by the second one?

**Comment by JacquesLucke** [comment]
I know. This is due to a limitation/feature in blender. Blender comes with its own way for creating the node menu, search and all the panels at the same time but I needed more control, so I had to implement my own search.
 Yes we will have to discuss this with a Blender dev.

**Comment by aditiapratama** [comment]
I agree, it's bit confusing. I'm always working with node, and always use `shift+a+s` than `ctrl+a`. But honestly `ctrl+a` is far more simpler to use.

**Comment by LeonCheung** [comment]
I see. Btw, I'm thinking about another possible search tool, which allows user to search for certain node by its name/label, and automatically focus on (jump to) it in a flash. You know, when tree grows larger, we have to spend quite some seconds to target on a specific one (and more often to switch between some of them), by zooming, panning, blablabla... (of course, it only makes sense for those who got good node-renaming habit). I remember Blender got such feature before, just not sure about it now, since I cannot find it anymore.

I know we can split it into more node editor windows, however it's not good for performance (FPS drops down quite a lot).

What's your idea?

**Comment by JacquesLucke** [comment]
I cannot test it now but I think ctrl f opens a search box that allows you to search for existing names.  If it doesn't it should not be very hard to implement such an operator :)

About fps problem.... I have no idea why that happens. Maybe its a blender problem or there is a draw function by me that causes this slowdown. I don't know.

**Comment by LeonCheung** [comment]
Oh, you are right about the shortcut... I just forgot it, Thanks for reminding. :P

**Comment by LeonCheung** [comment]
close #277

**Comment by LeonCheung** [comment]
Oh... it seems I cannot close my own issue in this way. :(
