### ISSUE TITLE
Animation Pose to Pose / Sequence

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#278]
![screen shot 2015-10-21 at 6 42 43 pm](https://cloud.githubusercontent.com/assets/3952687/10630637/c495ac9e-7823-11e5-902f-a5dcdd0f8146.png)

Following one of Lucke's video, I saw him using one node, and piggy back with same node, to get the effect of object moving from A to B to C.

I cannot get this to happen. The node seems to be missing the before and after time? Maybe I am doing this wrong or some nodes have changed?

**Comment by LeonCheung** [comment]
the 2nd Start needs to be the Result on the 1st animation Matrix node, actually, if you want to make a sequenced animation.

**Comment by enzyme69** [comment]
This is the video I was talking about:
https://youtu.be/QZNxIEdwaek?list=PLFSQhJg6cGLKq8WbouMNBOHbMd7xUhuom

He is using Animate Vector.

**Comment by enzyme69** [comment]
2nd start needs to be the result of 1st anim.... I will try.

**Comment by enzyme69** [comment]
You are right! So this work more like I expected, however I hit some kind of weird "Gimbal" already. What I am really trying to do is to push the object so that as if the Cube is rotating to the side, and to another side, to another side, until it is back into original position. As if the cube is rolling on the floor trying to make a Circle.

**Comment by LeonCheung** [comment]
Hmm, I'm still drawing it in my brain... Maybe one of my old post can be useful [here](http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2946189&viewfull=1#post2946189) I hope?

**Comment by LeonCheung** [comment]
are u pingpong fx?

**Comment by enzyme69** [comment]
Box rolling but in 4 direction from X until Y back into X. I will study your old post. Thanks a lot man.
