### ISSUE TITLE
Object from Group

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#279]
![screen shot 2015-10-21 at 11 08 50 pm](https://cloud.githubusercontent.com/assets/3952687/10636083/ce4fc146-7848-11e5-8c9c-068c670c1691.png)

It might be a bug, but I am not sure.

Every now and then, if I group some objects and try plugging the Object from Group node into Invoke Subprogram, it does not want to.

**Comment by LeonCheung** [comment]
Can you mark on the image which two sockets you want to connect exactly?

**Comment by LeonCheung** [comment]
I assume you actually mean "plugging the **Combine Lists** node into Invoke Subprogram". In that case, you need to select the combine lists node and go to N panel > Advanced Node Settings > Change Type, then search for *Object Group List*.

**Comment by enzyme69** [comment]
![screen shot 2015-10-22 at 6 15 56 am](https://cloud.githubusercontent.com/assets/3952687/10647487/63f82d92-7884-11e5-8c90-3c18f37f288b.png)

Ok I think I got those two confused. *Group List* and *Get Object from List*, and one is dark red and the other is dark grey.

This is my third times got those two mixed up. I feel a bit dumb.

Thanks also for explanation on Combine List, I didn't know it can become a different node via Advanced Option. AN has a lot of neat things underneath.

It works!

![screen shot 2015-10-22 at 6 25 23 am](https://cloud.githubusercontent.com/assets/3952687/10647709/b6e7da9c-7885-11e5-97ea-27a07538848f.png)

**Comment by LeonCheung** [comment]
A socket with solid color means it was a parameter type, while a transparent one indicates a list type. So, parameter <-> parameter, and list <-> list.

But true that the group thing here is a bit different, A Object Group indicates a list of in-group objects (usually containing more than one objects), while a Object Group List indicates a list of object groups. It only treats group as unit, not the objects in them (for that you may want to use another nested loop to handle in-group objects).

(I thought it was my bad that I persuaded Jacques to added that "confusing" thing... :tongue: )
