### ISSUE TITLE
Confusion regarding Vectorization

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#280]
![screen shot 2015-10-22 at 9 32 06 am](https://cloud.githubusercontent.com/assets/3952687/10652228/9e613502-78a0-11e5-8c11-330af8b5ee7e.png)

http://www.pasteall.org/blend/38718

I use the template that creates Animation Clones with Offset. But now, I would like to use Mesh Vertices Point positions to place the clones.

Now, the issue that sometimes I do not understand is how we can "vectorize" the index. I can select element of the list from index, but whenever I am plugging a list (of numbder range) into the index, it will create another "get element from index" node. 

I think I am missing a concept here.

**Comment by enzyme69** [comment]
![screen shot 2015-10-22 at 9 43 57 am](https://cloud.githubusercontent.com/assets/3952687/10652327/78cda3c4-78a1-11e5-854a-8144bda714af.png)

Above is a similar example. I keep getting "Get List Element" node appearing.

My logic is like... ok that is neat that I can now select the list from index, maybe I should supply the index with range of number. But this is not right.

My guess is that I need to create yet another subprogram that loop and iterate the list?

**Comment by enzyme69** [comment]
![screen shot 2015-10-22 at 9 48 54 am](https://cloud.githubusercontent.com/assets/3952687/10652423/3a7e045a-78a2-11e5-846b-fce5aaa20711.png)

In this simpler example, it actually works as I expected. But I am wondering: do we really need "GetListElement" node and LoopInput Index get plugged into it, all the time?

**Comment by LeonCheung** [comment]
![re](https://cloud.githubusercontent.com/assets/494788/10656323/33032e04-78b0-11e5-8dde-21c9c434adb8.jpg)

**Comment by og76** [comment]
2 things:
- if you have 3-5 elements, you may do it manually, but if you have 100 you need an automation for doing this. **Loops are an automation** (Subprograms). Just like Groups, but dedicated to lists (ordered bunch of items)
- Loops can be called (invoke..) many times. you define that input etc and then you can invoke that rule by as many lists of obj and vec as you want.

they are a concept very much used in scripting, though a very simple and logical way with many items. I have found myself growing to learn scripting while understanding this. 

ps. I do not use the group (blender groups) but rarely, exactly cause they have inconsistent order, that changes whenever you  add something or so. 
+The lists, if turned to object type, also provide a selection tool in the advanced panel. So you select some obj and then just make a list of it... And the panel also has socket list that allows to move elements up/down etc..

**Comment by enzyme69** [comment]
Aaah, thanks again Leon Chung and og76. That clears up something. I did make similar mistake in the past. Indeed, I am forced to think logically in script while noding like this. I like it.

Yes, Group is ... kind of handy, but I understand it needs to be sorted, or sometimes the sorting changes. I have to keep reading the thread, so far I am up to Page 23. Lots of examples from Nikos. 

Slowly understanding this better. I will atttempt to write in my blog. But I try not to make wrong statements.

**Comment by og76** [comment]
you may wanna open a dedicated "issue" like 'tips and tricks' for all these questions, instead of separate for each case.
Just a matter of easier to follow. And some things come back again and again...
