### ISSUE TITLE
Pause - Move - Pause

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#282]
I am doing an exercise, trying to move animate Cube from position A to position B to position C and so on. But with a Pause in between. Is this currently possible to do the elegant way?

I think so far I know how to get the old position of the object. I am not sure how to control and move the actual Time Duration thing. In one of video example by Jacques, I remember he piggy back a Animate Vector node to create this effect. However, I don't know how to do this now.

http://www.pasteall.org/blend/38746

In my Blend, I created 4 positions using Create Vector List. However, if I want to create list generatively, is this possible without loop? Say, is there a node that actually generate this list of X number of Vectors?

**Comment by enzyme69** [comment]
![screen shot 2015-10-23 at 3 00 56 pm](https://cloud.githubusercontent.com/assets/3952687/10684282/e587db88-7996-11e5-9928-e5495df3e2cb.png)

Startup node tree. It's not yet doing much. I could setup duration of 200, and then change the index, that sort of working. But not as I wanted.

**Comment by enzyme69** [comment]
![screen shot 2015-10-23 at 3 09 37 pm](https://cloud.githubusercontent.com/assets/3952687/10684384/200ec112-7998-11e5-90b9-14d4d5f15827.png)

This loop actually kind of doing what I am wanted, it generates X number of vector. Although would be nicer if I could just specify the total number of Vector I wanted by Int, instead of clicking "New Input". And I cannot seem to remove Input.

**Comment by LeonCheung** [comment]
One way I can think of is by creating a long enough list manually, then control visibility of each element by the integer you set, which is doable, but kinda stupid....

Another more possible way is by setting value via text editor, then use Textblock reader to read that and split into a list of lines, we can get that list length. So acually the total index will depend on how many lines you typed in textblock, instead of an manually-typed integer. Doable, but silly too.

Btw, another problem in your setup is that the animation cannot be played backward, since the cube location was changed (hard coded) everyframe, not just the "next" frame. That's why ID Key is more wanted, though it cannot be setup as simple as this one.

**Comment by enzyme69** [comment]
I started doing this exercise is to kind of simulate the simple effect of an example in Processing called "random walk".

In Processing, basically creating variable like: (Processing is 2D)
startPosX, startPosY, curPosX, curPoY, or targetPosX, targetPosY.

there is also speed  = random(-1, 1);

in one example, it is simply moving and tracing point, by pushing it with speed.

in a more advance example, it is tracking mouse position, and the object would follow the mouse, sometimes with lag, until it is close enough to the target position.

I don't want to get too crazy yet, I just need to know whether Animation Nodes can do this in an elegant way?

Because using Vector Wiggle, I could create motions of many Instance that is kind of like Insect Fly.

But I kind of want to do a motion like when Fly stops and land, and then it sort of pause a bit, maybe move to random position a bit, then pause again, and then fly.

How about I go back to question on how I can piggyback AnimateVector? It does not seem to have Time Before and After anymore. Is there an explanation to this?

**Comment by LeonCheung** [comment]
It used to have Delay socket. But you can still use Delay node or Math node to make that pause.

**Comment by enzyme69** [comment]
Yes, that one. I'll study Delay node and come back...

**Comment by enzyme69** [comment]
Ok, it seems to kind of doing what I wanted now with piggy back style. I think I probably can remove this piggy back style using yet another loop....

Currently, I have 3 positions, manually I specify:
- origin pos
- pos A
- pos B
- back to origin

http://www.pasteall.org/blend/38747

It's weird I cannot seem to get element from Vector.

**Comment by enzyme69** [comment]
![screen shot 2015-10-23 at 3 53 17 pm](https://cloud.githubusercontent.com/assets/3952687/10684890/364b4418-799e-11e5-8a11-7fa63ed83622.png)

**Comment by enzyme69** [comment]
The Random Vector output is a list, however when I plug it into GetListLenth, I am only getting 1 Vector value.... so I am guessing I need to use LoopGeneratorOutput node, but I can't get that value out... :8ball:

**Comment by LeonCheung** [comment]
Yes, that's what sequence animation work in AN. Getting element from list is a bit tricky here. but doable.

My solution:

![avs](https://cloud.githubusercontent.com/assets/494788/10685280/cecaa4c2-798a-11e5-8beb-832e762dbfb0.jpg)

[example file] (http://pasteall.org/blend/38748)

**Comment by LeonCheung** [comment]
And.... the little *stupid* thing I mentioned:

![control](https://cloud.githubusercontent.com/assets/494788/10685298/10b644d6-798b-11e5-8b4a-2c3750a1bbe1.gif)

**Comment by enzyme69** [comment]
Interesting....! But what did you plug that into?

**Comment by enzyme69** [comment]
![screen shot 2015-10-23 at 4 39 22 pm](https://cloud.githubusercontent.com/assets/3952687/10685347/c376241a-79a4-11e5-90df-d3efec4a1824.png)
I figure out the loop inside the loop... now working for what I like it, but not yet elegant because it is like hardcoded and I cannot keep manually adding the Animate Vector.

**Comment by enzyme69** [comment]
Oh wait, I will check your example.

**Comment by LeonCheung** [comment]
Vector is basically a 3-item list [x ,y, z], so...

**Comment by enzyme69** [comment]
So far my noob version:
http://www.pasteall.org/blend/38749

**Comment by LeonCheung** [comment]
Btw, why not talk about all these things on BA? There would be more guys out there, you'll collect more useful things I bet. :)

**Comment by enzyme69** [comment]
Yeah, BlenderArtist thread is a bit difficult to follow after a while. I am only up to page 21. I can't keep track of how many inspiring posts and Q&A. 

This way, I could keep track my own question and find answers. I will try.

Thanks for that PRO answers. I am shocked basically with how complex it become. But excited at the same time by the possibility.

I guess this thread can be closed. It sort of answered, although to create setup where the positions input can grow and having everything work still a question I must find.

It should not be complex. I mean maybe it is much easier if I create my own node to do what I am trying to do.

**Comment by enzyme69** [comment]
Thanks @LeonCheung ! Much appreciated.

**Comment by LeonCheung** [comment]
I see. Oh [here](http://pasteall.org/blend/38750) is the setup for the illusion you are curious about. Beieve me, it's not what you really expect. Anyway. :tongue:

**Comment by JacquesLucke** [comment]
This is my solution to the problem: 
![animate to multiple targets with delay](https://cloud.githubusercontent.com/assets/5881326/10686339/66af3122-7963-11e5-93ce-52d2927d90a7.PNG)

It is not totally efficient when you have many vectors and many vectors but it works good enouph for me.
You can create the "Reassign Loop Parameter" nodes from the advanced Panel of the Loop Input node.

**Comment by LeonCheung** [comment]
Cool solution!
