### ISSUE TITLE
Loop Conflict on Multiple Nodetrees

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#285]
When I append nodetree from other blend file, it seems the new imported loops are broken, have to be renamed and relinked, even though the nodetrees names are different.

**Comment by JacquesLucke** [comment]
Ok. that shouldn't be that way...
Can you provide an example file?

**Comment by LeonCheung** [comment]
Oh, I mean eventhough the **subprogram** names are different.
Hmm, seems it occurs only when the appended nodetree got the same name with the current one.

**Comment by og76** [comment]
Blender renames trees automatically to  tree.001 , 002... etc
(also if u create a group in cycles or compositor and name it same as the AN tree)

**Comment by LeonCheung** [comment]
I know. But it just... kinda break the old loop...

![screenshot](https://cloud.githubusercontent.com/assets/494788/10788637/bc97f5b6-7db3-11e5-8d90-a7dea19c0703.jpg)

**Comment by LeonCheung** [comment]
You can simply test it by appending nodetree from a copy of the current file.

**Comment by og76** [comment]
if the name was name.001 it kinda works:

I made a tree name.001, 
new file with a tree name.001
append name.001
the imported one renamed to name.000 and works :eyes: 

![import1](https://cloud.githubusercontent.com/assets/11709974/10788951/6695149e-7d83-11e5-9975-ed1a15f06019.PNG)

**Comment by og76** [comment]
btw, tested in compositor, made a group and renamed to NodeTree, 
it renames the AN to 001 but all is ok for now ..

**Comment by LeonCheung** [comment]
[Here](https://youtu.be/VNnOD0LGZqk) is a video recorded just now. Using the latest master.

**Comment by JacquesLucke** [comment]
as I said. Would be useful to have your files. 
Were the files A.blend and B.blender the same at the beginning?

**Comment by LeonCheung** [comment]
Yep, The two files are exactly the same.

To repeat it:

1. File > New to start a new blender project,
2. Pick one setup from the template list (say, Radom Vertices Offset in my video).
3. File > Save Copy..., name it as B.blend.
4. Then Shift F1 to append the nodetree from B.blend.

Here is my [A.blend](http://pasteall.org/blend/38836) if helpful.

**Comment by JacquesLucke** [comment]
Ok then this is an issue I know. Problem is that the both loop input nodes have the same identifier. Not sure yet how to fix that. Maybe I will just implement a check that you will see the reason for the error

**Comment by og76** [comment]
I have also tried with files that are different and I still get an error
The loops are not red, but the execution is stalled and the sockets look weird ..

**Comment by og76** [comment]
still trying to repro the halt error

however, I get this constantly if I import twice the same tree (001 and 002 are same, imported)
it's all fine if I delete one of the faulty loops
![import2](https://cloud.githubusercontent.com/assets/11709974/10799704/dd4ece76-7db6-11e5-9966-a2216775877e.PNG)

**Comment by og76** [comment]
Sorry, the one with the complete halt is a different issue.
Try to Link instead of Append a node tree and see the pandora's box.. may have to restart B completely

but that is not an issue now, and it may be a B bug also ...

**Comment by JacquesLucke** [comment]
![node identifier exists twice](https://cloud.githubusercontent.com/assets/5881326/10864862/63b52d20-7ffb-11e5-8e64-68cae6354d41.PNG)

**Comment by JacquesLucke** [comment]
8ff9b9b
