### ISSUE TITLE
[bug] auto execution and overview panel interferes with compositor and cycles preview

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#288]
auto execution (continuous update) is continuously updating the:
1.
**overview panel** makes all trees continuously update, compositor mainly, but probably others 
- solution seams to be to run only for AN, as pull here #287 , hope is enough, WFM

2.
even so, the **cycles material output** is updating other trees **while a prop is set** so:
- compositor updates continuously, as if autorender ... (just like render preview used to do..)
- cycles material preview panel unusable (like the preview render used to be ..) - minor thing imho

guess the continuous bpy. blabla.. node_tree keeps them all busy :(
so here we need a broader solution, like with render preview I guess ..

ps extra fun:
    .I tried to make a similar _compositor nodes out_, heavy copy from _cycles mat out_, but targeting scene.node_tree. I bumped into this, but even with expressions, the behavior was the same.
    .The super funnier thing is that if u use an expression or node or script to set a value on the compositor node, while that prop is accessed you cannot pan in any node tree (AN, compositor..). you can zoom but not pan 8(

**Comment by og76** [comment]
Of course, in all the above cases, including overview panel, the Uncheck Always + check tree, frame prop works very well (including the very funny pan issue..)
But this is very hard to see for someone new to AN ..

**Comment by JacquesLucke** [comment]
Good catch. Can you make a small examples file I can work with?

**Comment by og76** [comment]
[compositor issues 2015-10-26.zip]
(https://drive.google.com/file/d/0BzzAoBwXO8dseV9TRmQ2RU44c1k/view?usp=sharing)

this has 3 blends + compositor.node....py:

- the cycles material is an example of how things update when a cyc parameter is set from AN
- the other 2 are the same file but using *expressions* or the *compositor....py* node to drive the compositor nodes (it is irrelevant, may use either..)

see the impossible pan in the nodes if auto execution is on!

**Comment by JacquesLucke** [comment]
Is this solved with the cleanup of the cycles material output node?
Now the node only updates the value in the material node if its different. (I found that this doesn't work with vectors because they are used differently in cycles, but I guess you only need color and float in your daily work)
