### ISSUE TITLE
Feature request: A checker to invert loop execution

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#290]
Just a simple idea, a checkbox to invert the loop execution. Instead of executing from 0 to N, the user could have the ability to execute it from N to 0.

**Comment by JacquesLucke** [comment]
Can't you just use a revert list before the invoke subprogram node?

**Comment by YorsLosilla** [comment]
Well maybe  that should work.


-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎27/‎10/‎2015 17:36
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Feature request: A checker to invert loopexecution (#290)

Can't you just use a revert list before the invoke subprogram node?
