### ISSUE TITLE
Wiggling individual letter of text

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#292]
I am trying to separate and then wiggle each individual letters of Text I supplied. I am stuck and confused with the result.

![screen shot 2015-10-31 at 3 20 19 pm](https://cloud.githubusercontent.com/assets/3952687/10862714/2644bf82-7fe7-11e5-83ca-02cd54dea9ef.png)
![screen shot 2015-10-31 at 3 49 56 pm](https://cloud.githubusercontent.com/assets/3952687/10862716/269945b6-7fe7-11e5-9386-332717ce5bdc.png)

PROBLEM 1
I know that Wiggle + Vector (world position of object) = object that animates in wiggle fashion.

With text, after separating, I try to get the Vector position of each letter using Loops. And I did that, it works fine, however, plugging that Vector positions and adding it to wiggle, I am getting double deformation bad looping that send the letter far far away. I think it's a bad cyclic.

PROBLEM 2
I try this solution by trying to bake the position of every letter into Text and bring it back via Text Block ready. Unfortunately, I am stuck again and getting just string text. I can't figure out how to make the text back into Vector List.

???

http://www.pasteall.org/blend/38901

**Comment by JacquesLucke** [comment]
The main problem with text animation is that you overwrite the original location of an object. To store some values per object there is the "ID Key" system (note: it's very likely that this system will change with the next release). The Separate Text Object node saves the original location + text on the object. You can access this data with the "Objet ID Key" node like I show in the image below.
Does that solve your problem?

![text animation](https://cloud.githubusercontent.com/assets/5881326/10862813/770c23b2-7fb8-11e5-9a70-2bf7a2e6873d.PNG)

**Comment by enzyme69** [comment]
Yes! That's exactly it, Object ID Key. That's interesting additional information. So it is more or less like the Initial position like in Particles environment?

Should I save the question regarding how to make List of Strings back into Number/Vector list for later? Is it already possible to do?

**Comment by JacquesLucke** [comment]
Yes, it's just the initial location. You can also use it for other stuff but as I said. This system is likely to change in the next release.
Basicly the ID Key system provides you an interface custom properties on objects.
![object custom properties](https://cloud.githubusercontent.com/assets/5881326/10881778/174b37e2-8166-11e5-9004-4d84e1bafeee.PNG)

Hm, you can do it with the expression or convert node..
