### ISSUE TITLE
Vertices not unique in Mesh Data

### ISSUE THREAD

**Issue by pjbarendrecht** [JacquesLucke/animation_nodes#293]
Hi, in the node "Mesh Data from Polygons" a vertex is added to the list of vertices for each polygon it is part of. As a result, the Mesh Data for a cube contains 3x8=24 vertices, the Mesh Data for an icosphere (once subdivided) contains 5x12=60 vertices, and so on.

The only way to create a BMesh at the moment seems to be to use the "Create BMesh" node, which uses the Mesh Data as input. The BMesh created does therefore also contain multiple copies of the same vertices (and edges).

**Comment by pjbarendrecht** [comment]
Perhaps something like this to create a BMesh —

```python
import bpy, bmesh
from ... base_types.node import AnimationNode

class BMeshFromObject(bpy.types.Node, AnimationNode):
    bl_idname = "an_BMeshFromObject"
    bl_label = "BMesh from Object"

    def create(self):
        self.inputs.new("an_ObjectSocket", "Object", "obj")
        self.outputs.new("an_BMeshSocket", "BMesh", "bm")

    def execute(self, obj):
        bm = bmesh.new()
        bm.from_mesh(obj.data)
        return bm
```

And this node to check some BMesh elements —

```python
import bpy, bmesh
from ... base_types.node import AnimationNode

class BMeshInfo(bpy.types.Node, AnimationNode):
    bl_idname = "an_BMeshInfo"
    bl_label = "BMesh Info"

    def create(self):
        self.inputs.new("an_BMeshSocket", "BMesh", "bm")
        self.outputs.new("an_IntegerSocket", "NumVerts", "nv")
        self.outputs.new("an_IntegerSocket", "NumEdges", "ne")
        self.outputs.new("an_IntegerSocket", "NumFaces", "nf")
    
    def getExecutionCode(self):
        isLinked = self.getLinkedOutputsDict()
        
        if isLinked["nv"]:
            yield "nv = len(bm.verts)"
        
        if isLinked["ne"]:
            yield "ne = len(bm.edges)"
            
        if isLinked["nf"]:
            yield "nf = len(bm.faces)"
```

Results for the default Cube:

![bmeshinfo](https://cloud.githubusercontent.com/assets/794704/10864207/5a2812d0-7fde-11e5-9207-36d92e5bbd57.png)

**Comment by pjbarendrecht** [comment]
This, in turn, allows for nodes like

```python
import bpy, bmesh
from ... base_types.node import AnimationNode

class BMeshVertValencies(bpy.types.Node, AnimationNode):
    bl_idname = "an_BMeshVertValencies"
    bl_label = "BMesh Vertex Valencies"

    def create(self):
        self.inputs.new("an_BMeshSocket", "BMesh", "bm")
        self.outputs.new("an_IntegerListSocket", "Valencies", "vals")
    
    def execute(self, bm):
        vals = []
        for v in bm.verts:
            vals.append(len(v.link_edges))
          
        return list(vals)
```

Example, using the "Index Visualiser (BMesh)" Addon —

![tripod](https://cloud.githubusercontent.com/assets/794704/10864269/71c52aca-7fe0-11e5-91f2-505cf7e74313.png)

**Comment by JacquesLucke** [comment]
It is intentional that the "Mesh Data from Polygons" node creates the vertices for each polygon individually. If you want to remove doubles you will have to create a bmesh from the mesh data and use the remove doubles node then. 
You are right. The "BMesh from Object node" is definitly needed. Do you want to create a pull request for that node or shall I quickly commit the node myself?

I will still have to think about the other nodes you propose but it's definitly possible to have nodes like these later :)

**Comment by pjbarendrecht** [comment]
Ah, I see. Thanks for clearing that up :). Please feel free to commit the "BMesh from Object" node yourself.

As for the other nodes, they were just for checking/debugging. I do have some ideas for a general BMesh Neighbours node though, I'll try to post a draft later this week. 

By the way, it might be useful to have BMesh Vertex, Edge and Face sockets. What do you think?

**Comment by JacquesLucke** [comment]
I'm not sure about the BMesh Vertex etc sockets because they have a problem. It seems like they are always linked to a specific bmesh -> what should be the default BMesh Vertex? 'None'?

**Comment by pjbarendrecht** [comment]
Yes, setting it to 'None' might work. I'm trying to come up with a user-friendly approach to modify individual BMesh components using the Animation Nodes.

Being able to use the connectivity information stored in a BMesh (e.g. lookup of neighbouring elements in constant time) has a lot of potential for animation I think. For instance, one could displace a single Vertex, then in the next frame displace the Vertices linked to the initial Vertex, and so on (with some constraints of course) in order to animate a ripple through a mesh. Or given a Face, assign a certain colour to its neighbouring Faces.

By the way, I'm experiencing some issues with a Loop and a BMesh (resulting in an "Invalid Network", I'll open another GitHub issue for this.
