### ISSUE TITLE
BMesh nodes development and issues

### ISSUE THREAD

**Issue by pjbarendrecht** [JacquesLucke/animation_nodes#301]
I'm experiencing some issues with a Loop and a BMesh. Using the "BMesh from Object" proposed in [this Issue](https://github.com/JacquesLucke/animation_nodes/issues/293), I'm trying to displace vertices along their normals using the following "BMesh Custom" node (just for the purpose of experimenting) —

```python
import bpy, bmesh
from ... base_types.node import AnimationNode

class BMeshCustom(bpy.types.Node, AnimationNode):
    bl_idname = "an_BMeshCustom"
    bl_label = "BMesh Custom"

    def create(self):
        self.inputs.new("an_BMeshSocket", "BMesh", "bm_in")
        self.inputs.new("an_IntegerSocket", "Index", "k")
        self.inputs.new("an_FloatSocket", "Factor", "s")
        self.outputs.new("an_BMeshSocket", "BMesh", "bm_out")
    
    def execute(self, bm_in, k, s):
        bm_in.verts.ensure_lookup_table()
        print(k)
        print(bm_in.verts[k].co)
        bm_in.verts[k].co += s*bm_in.verts[k].normal
        return bm_in
```

Using an "Integer" node input for the Index works just fine (setting Index to 7 is a rather random choice though). However, when I try to use a Loop which uses a List of Integers to iterate over (which should set Index to 3, 5 and 6 in succession), all nodes are coloured red and Blender displays "At least one invalid network exists". See the screenshots below. Am I overlooking something?

![nodes1](https://cloud.githubusercontent.com/assets/794704/10903692/405d93ac-8204-11e5-8d76-a6d811304caa.png)
![nodes2](https://cloud.githubusercontent.com/assets/794704/10903693/438df918-8204-11e5-8706-7c4f5309c46d.png)

**Comment by JacquesLucke** [comment]
The Problem you have there is that you must have a clear Separation between you main 'program network' and the subprogram. In your examples, you try to call the subprogram within itself. 
You should create a separate Loop. Then make a "New Parameter" with the type "BMesh".

**Comment by JacquesLucke** [comment]
btw: great that you started writing real nodes :)
Is the api for nodes ok for you or is there something you don't like?

**Comment by pjbarendrecht** [comment]
Ah, I see! Thanks, problem solved. Yes, the API and documentation is concise and clear :).
