### ISSUE TITLE
Boolean operators for lists (sets)

### ISSUE THREAD

**Issue by pjbarendrecht** [JacquesLucke/animation_nodes#304]
I thought it would be useful to have a Boolean node for lists (or rather, sets). This is a draft, only tested for Integer Lists. Feel free to modify and submit :)

```python
import bpy
from bpy.props import *
from ... base_types.node import AnimationNode

bool_types = ["Union", "Intersection", "Difference", "Sym. Diff."]
bool_types_items = [(t, t, "") for t in bool_types]

class ListBoolean(bpy.types.Node, AnimationNode):
    bl_idname = "an_ListBoolean"
    bl_label = "List Boolean"
    boolType = EnumProperty(name = "Bool Type", items = bool_types_items)

    def create(self):
        self.inputs.new("an_GenericSocket", "List", "list1")
        self.inputs.new("an_GenericSocket", "List", "list2")
        self.outputs.new("an_GenericSocket", "List", "list")
    
    def draw(self, layout):
        layout.prop(self, "boolType", text = "Type")
        
    def execute(self, list1, list2):
        sel = self.boolType
        set1 = set(list1)
        set2 = set(list2)
        if sel == "Union":
            return list(set1.union(set2))
        if sel == "Intersection":
            return list(set1.intersection(set2))
        if sel == "Difference":
            return list(set1.difference(set2))
        if sel == "Sym. Diff.":
            return list(set1.symmetric_difference(set2))
```

**Comment by og76** [comment]
sets are the fastest, but:
- we should preserve the order
- the sets are eliminating duplicates
- there is the issue of hashable/non hashable
- there is the issue of sublists, but we probably should not go there, instead having cascade 2 nodes like we do with get element


out of my poor reading, that would go like :

1. union:
I think we already combine, respectively join some lists, with special cases (i.e mesh data)
2. intersection (having 1 lookup as set to make it faster ..)
```
set2 = set(list2)
result = [item for item in list1 if item in set2]
```
3. difference:
```
set2 = set(list2)
result = [item for item in list1 if item not in set2]
```
4. symetric diff
```
set1 = set(list1)
set2 = set(list2)
result = [item for item in list1 if item not in set2]
result.extend([item for item in list2 if item not in set1])
```

ps: boolean nodes work on lists so maybe the name should be list operations or something

**Comment by pjbarendrecht** [comment]
Good points OG. For the application I have in mind I actually need to get rid of duplicates (and the order of the elements is irrelevant), but in general this should be considered.

I thought of introducing Set sockets, but it would be more efficient to just add a checkbox to the Advanced Panel for this node (remove duplicates).

**Comment by og76** [comment]
or to have 2 separate: remove duplicates / list to set nodes or so
(removing duplicates and order are different things depending on case, imho)

**Comment by JacquesLucke** [comment]
I implemented a first version of this node in a custom branch
Currently it is called "List Boolean Operations".
Does someone have a better idea how to call it?

**Comment by og76** [comment]
List Operations, List Interaction, List compare (uh, that should be another I guess)

**Comment by JacquesLucke** [comment]
yeah list compare can come later :D

List Operations is a bit generic, isn't it? I mean shuffling and reversing a list is also a *Operation*

**Comment by og76** [comment]
List Combinations, List COmbinator, List Mix ... Ah, all good names are taken..
List stuff, List vs List >< List clash, List Wars ... ok, I'm in th wrong direction..
