### ISSUE TITLE
Custom Attribute Read Issue

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#313]
I believe there are 3 nodes that can read and write values to Custom Attribute. I am using latest AN and none of them seems to work... unless I missed something again here.

I tried custom attribute: prop, prop1, prop2. but can't get it to work.

Would it be nice to also see "all keyable attributes" from an object and we can just select from drop down. But I can't remember Blender having this.

Supposed I have a Control for a Rig, and I have many attributes, would be great if AN can actually spit out list of all Attributes.

**Comment by enzyme69** [comment]
Oh crap, I realized I need to use ["prop"]... nvm.

**Comment by og76** [comment]
fwiw, the **object attribute out** and **expression** also *Create custom props if not there already*.
this is interesting if you create 100 instances and need them to have the same prop
(unfortunately, the deletion/removal is not there yet)

ps:
the id keys are a different thing as those keys are monitored by the id node, so they should be manipulated with that node.
The above refers to usual props, not the ID key created ones..

![custom attr1](https://cloud.githubusercontent.com/assets/11709974/11025355/a8f327e0-86a2-11e5-842f-9d5a94514348.PNG)
