### ISSUE TITLE
Question about Direction to Rotation

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#318]
I suppose Direction to Rotation node is very similar to a Track constraint? If so, I wonder if I have to do vector math like below to "fix" the relative positions of direction and guide objects. Or, is that made by design? I mean, it seems it always take the world origin (0, 0, 0) by default, instead of the target object(s) itself.

![778](https://cloud.githubusercontent.com/assets/494788/11056919/a9edb474-87c1-11e5-899e-933fb5ce0281.jpg)

**Comment by JacquesLucke** [comment]
Thats correct. The direction to rotation node does not know anything about the location of the object.
I know it seems like a lot more work in your example but quite often you only have the direction given. Eg if you want to distribute objects along a spline or on mesh vertices.

**Comment by LeonCheung** [comment]
I see, and agree on the direction cases. Thanks. Closing. :)
