### ISSUE TITLE
Create a new node: Interpolation list

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#319]
I´m working on a new project in which I have to animate tenths of objects in a radnom way. Having this node will be really helpfull in order to create more random transitions.

**Comment by JacquesLucke** [comment]
I think you mean I should create a new socket type?

**Comment by YorsLosilla** [comment]
Sure. I didn't considered that way


-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎12/‎11/‎2015 10:01
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Create a new node: Interpolation list (#319)

I think you mean I should create a new socket type?

**Comment by JacquesLucke** [comment]
OK.

**Comment by YorsLosilla** [comment]
Thank you very much Jacques.

**Comment by JacquesLucke** [comment]
Done :D

**Comment by YorsLosilla** [comment]
Wow!! That was really fast. Is it on master or in 1.5?

**Comment by JacquesLucke** [comment]
in both

**Comment by YorsLosilla** [comment]
Tested an worked

**Comment by JacquesLucke** [comment]
Cool. Thanks :)
