### ISSUE TITLE
Object Transform Update

### ISSUE THREAD

**Issue by kopias** [JacquesLucke/animation_nodes#320]
Is it possible to have update only if object transforms are changed via "r", "t", "s"
(maybe just objects that are specified in node tree object fields would trigger an update)

since most of the time when experimenting i only move some things in view-port or change properties
(and don't want to drain battery and heat up my laptop when making coffee :P )
i imagine the update would be just after i confirm the transformation but maybe doing it while in operator could be possible as well.

P.S. not sure if I am making sense here, having some trouble to express in English
P.S.2 its too much fun.

**Comment by JacquesLucke** [comment]
It is not possible to monitor th objects to only update when eg the location changes.
But in the left sidebar of the node editor you have the option to disable the auto execution at all. Or you say you want to update only once a second. Or only when you change the node tree..
Just play a bit with the settings there.
