### ISSUE TITLE
Two suggestions for Separate Text Object node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#325]
1. Turn off the renderability for source text too, if not, it will still show in the final render.
2. It would be useful to provide a option to unlink the shared material for each object output, which means to make them having unique material datablock.

**Comment by JacquesLucke** [comment]
2. I have to think about this. I would need a good way to make sure that all these materials don't clutter your scene too much.

**Comment by og76** [comment]
my 2 cents:

1. renderability can be turned off with obj vis out and you have full control
after all you may wanna turn it of only at a certain moment (switch the original for the separated..)

2. this is a more general set material on obj thing
of course it can be part of separate node, but material is broader than this

but also:
- do we need dif material for each instance or 2-3 materials to swap ? 
creating 140 material "instances" is not always good (manage that in cycles or in a loop etc) and monitoring such ..

- if u wanna do some simpler thing like swap 2-3 materials (initial-transition(fade?)-final) we have obj characters prop for just that and it covers more issues than expected. I know it's not the most obvious but it already works for part of the issue, switchin material

- I guess a big part of it comes from the cycles not allowing more per object props, so we gotta use obj index or vert color

**Comment by LeonCheung** [comment]
1. Hmm, IMHO, the source is only useful in case you want to re-edit it, otherwise it should be always turned off both on visibility and renderability, because we finally need to render it anyway, hding from 3D view is not enough for sure.

2. One specific useage to having individual materials could be something like this:

![colored_text](https://cloud.githubusercontent.com/assets/494788/11201821/9858c374-8d1c-11e5-9783-01584dbbfc21.jpg)

See, pre-assigned colors are lost here...

But, yes, separating materials afterwards is mainly useful for further individual material controlls, with help of obj id perhaps to control something like fading (you may have seen my latest BA thread post I suppose :) ). But I found object ID is not convenient enough and very limited to fully control the shared material on multiple objects, especially for Cycles mat.

What I'm thinking here is to leave that as an option, if possible. (Wait.. I suddenly got other things to suggest on material animation, I'll start a new issue. :P )

**Comment by JacquesLucke** [comment]
can we close this?

**Comment by LeonCheung** [comment]
Until Cycles got better per-obj mat control, there seems nothing better we can do imho. So closing. :)
