### ISSUE TITLE
Separate Text Object Issue

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#328]
Try clicking the three Update buttons on all three green nodes, to see what's going on...

[example file](http://pasteall.org/blend/39266)

**Comment by JacquesLucke** [comment]
Ah I think I know the issue. Will check the code now

**Comment by JacquesLucke** [comment]
it's fixed in the v1.5 branch

**Comment by LeonCheung** [comment]
Cool for the flash fix!
