### ISSUE TITLE
list dealing with expression

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#329]
I know we already have some list nodes, just wonder why some list operations still cannot be simply used in expression node, such as append, extend, insert, etc, but some can, like count, min, max, len...

**Comment by JacquesLucke** [comment]
not sure what you mean. What exactly doesn't work? Can you give an example?
maybe it's because the Expression you type in there has to have a return type but operations like append return None and not the original list.

**Comment by LeonCheung** [comment]
So they all cannot be used this way?

![list_exp](https://cloud.githubusercontent.com/assets/494788/11318174/0783210a-9082-11e5-9efe-bf7806f39f19.jpg)

**Comment by JacquesLucke** [comment]
Well, the expression works but you don't have access to the list afterwards, so yes, it's pretty much useless..

**Comment by LeonCheung** [comment]
Haha， I see. That's the answer I expected. Thanks.
