### ISSUE TITLE
any way to created duplicated, can-be-updated text mesh from Text?

### ISSUE THREAD

**Issue by retsyo** [JacquesLucke/animation_nodes#331]
What I mean is about http://blenderartists.org/forum/showthread.php?216113-Brecht-s-easter-egg-surprise-Modernizing-shading-and-rendering&p=2905496&viewfull=1#post2905496

if we can change the text easily by inputing new character, then it will become a text cloud generator.

**Comment by JacquesLucke** [comment]
I'm not sure what you want exactly.
Do you want that you have a text object that will automatically be converted to a mesh when the text changes, or what?

**Comment by retsyo** [comment]
Yes, a text object that will automatically be converted to a mesh when the text changes

**Comment by JacquesLucke** [comment]
This will be a bit ineffecient but should be possible in theory. I will try to make an example later today.

**Comment by JacquesLucke** [comment]
Hm sorry. I did not found the time to do it yet and I still think that AN isn't really ment for things like this..
Maybe you want to ask in the forum or on stackexchange instead..

**Comment by og76** [comment]
I think I found a way to do it with a weirder setup, but maybe a video is more explicit than a blend.
However, the stackexchange  is the place to ask/post such answer.
