### ISSUE TITLE
A few missing menu items

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#337]
Euler Wiggle
Random Euler (Randomize)
Timecode Generator
plus a few "xxx by Name" nodes

If they are hidden for a reason, then let them go...

**Comment by og76** [comment]
on euler and quat I have more 
and planned to put in the menu once I have the whole bunch, to figure a logic for it..
I'll try to make some time to finish these ..

**Comment by LeonCheung** [comment]
Just "xxx by Name" nodes left.

**Comment by og76** [comment]
also #417 ;)
