### ISSUE TITLE
Object Attribute Output doesn´t wor as expected

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#338]
Every time I trye to use it the node returns me a Attribute not found error

![sample](https://cloud.githubusercontent.com/assets/12479570/11363069/cc33b700-9297-11e5-8f7d-e220e5af5eda.png)

Ver. 1.0.1

**Comment by JacquesLucke** [comment]
I cannot test it now because I'm in university, but I guess the problem is that this property isn't part of the object. Instead it belongs to the curve data block that is inside the object.
To access these properties you need to write *data.curve_property_name*

**Comment by YorsLosilla** [comment]
Thanks. Worked perfectly

**Comment by JacquesLucke** [comment]
Beside that you don't need this node in your example. You can set the property using the curve objects output node. The socket for that is hidden by default to not clutter the interface with all the sockets you only need in rare cases.
You can unhide the socket in the right toolbar when the curve object output node is selected.
