### ISSUE TITLE
Have been removed the velocity sockets from the transform input node on the latest versions? 

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#339]
I can´t find them on any place.

**Comment by gabrielmontagne** [comment]
Yes, they were removed. 
You can still figure the velocity out by taking the current position and the position one frame ago.
The general solution [was sketched here](http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2959157&viewfull=1#post2959157)

Vector distance will always return absolute (positive) values, but you can also use vector subtraction.

**Comment by LeonCheung** [comment]
Right. It was removed in the new version. Btw, here is some useful posts worth to see. You can find link to "How to generate velocity" at line# 115.

**Comment by LeonCheung** [comment]
interesting, we answered almost by the same second...

**Comment by JacquesLucke** [comment]
And I answered the question at the same Moment on stackexchange haha

**Comment by YorsLosilla** [comment]
Well. If you take a look to stackexchange you will see that this solution doesn´t fit well for my problem.

**Comment by JacquesLucke** [comment]
I see...

I will close this now. I think the answer should be clear now :D
