### ISSUE TITLE
[Suggestion] Quicker way to invoke subprogram

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#340]
Possible options:

1. A new button on the Subprogram node, click it to create one (since we are going to invoke it anyway).
2. Via a possible pie menu.
3. A new header menu (maybe next to the Templates. similar to what o.g. implemented to his branch).

I believe either of them can be way faster, convenient and effective than having to  **Shift + A** > **Subprograms**, then choose one from the menu list.  :)   FYI.

**Comment by JacquesLucke** [comment]
![create invoke node pie](https://cloud.githubusercontent.com/assets/5881326/11407354/927166ae-93b2-11e5-8904-f33e5ecc7413.PNG)

**Comment by LeonCheung** [comment]
That's cool!
