### ISSUE TITLE
Upgrading Animation Nodes addon breaks older blend files? Help?

### ISSUE THREAD

**Issue by AdmiralPotato** [JacquesLucke/animation_nodes#341]
A few weeks ago, I created a new animation using a then-up-to-date version of the Animation Nodes addon from the "Download Zip" button on this repo. I have updated the addon in the same manner and saved the Bledner default user settings since then. My problem is, now that I have time to post the design and a screenshot/explanation of its Animation Nodes setup - the addon no longer works when I open the file. The nodes look like they're all in place and like they should be working, and I don't see any errors in the Node Editor, but there is no output to my scene.

First question - is there a way to see what version (or date?) of the Animation Nodes addon was used in a particular blend file? I now realize that it may just be best practice to download the zip of a particular commit and keep it in the same folder as the blend file for any new designs that I make... but is this the best way to future-proof my designs while also getting the advantages of using newer versions of the system?

Second question - How does one begin to debug a problem like this, and migrate a design from a previous version of the addon to a newer version?

Here's the blend file I'm having problems with at the moment:
http://root.nuclearpixel.com/misc/torus_tear_2015-11-11.zip

Here's a preview render of what it's supposed to look like when it's working/animating properly:
![swarm_test-0](https://cloud.githubusercontent.com/assets/820844/11419211/148554ea-93e3-11e5-9bce-1a4e2352b7b9.gif)
![swarm_test-1](https://cloud.githubusercontent.com/assets/820844/11419209/1481e198-93e3-11e5-889a-eedb8ea0d2a8.gif)
![swarm_test-2-b](https://cloud.githubusercontent.com/assets/820844/11419222/24398fd2-93e3-11e5-9c64-84af2fca7ebc.gif)
![swarm_test-3](https://cloud.githubusercontent.com/assets/820844/11419210/148240a2-93e3-11e5-93ae-126df9c405d6.gif)

Any help would be greatly appreciated.

**Comment by JacquesLucke** [comment]
The Motion in the viewport seems to work correctly. Just Rendering doesn't really work here. I will have to test more before I can understand whats going on..

**Comment by AdmiralPotato** [comment]
Okay, I've done a little more looking into this myself. Seems that the Animation Nodes addon is actually creating all of the children objects in whichever scene is sorted first alphabetically. This is where my confusion was - I always use one scene for the mesh/render, and another scene for any compositing/FX. In this file, my mesh scene was named "Scene" and my compositing scene was named "Compositing".

The objects created by the node loop were placed in the "Compositing" scene on startup/load, and had been removed from my  mesh "Scene". When I renamed "Compositing" to "Wat" and set the instance count in the loop to 0 and then 27 again, it re-spawned all of the objects in "Scene". It was also able to find and control the base shape object on layer 13 of that scene again.

I wonder - is there a way to tell Animation Nodes to pick a particular scene for its output, or could it be added?

**Comment by JacquesLucke** [comment]
In fact the Object Instancer node has a hidden Scene socket. You can unhide it in the right toolbar of the node editor while the instancer node is selected. Maybe you will have to recreate the instances atm to make sure they are in the other scene.
Support for multiple Scenes is still something i have to work on. Currently there it is implemented that each node tree has a "Global Scene" in which everything executed. The global Scene on each node tree is the first Scene in bpy.data.scenes which is a list of all Scenes in the blend file.
https://github.com/JacquesLucke/animation_nodes/blob/master/base_types/node_tree.py#L106-L110
There is already a property called "sceneName" for each node tree but this is currently not accessable through the user Interface.

**Comment by JacquesLucke** [comment]
To control in which layers an object is you can use the *Object Layer Visibility Output* node.

**Comment by AdmiralPotato** [comment]
Thank you for taking the time to inform me about the _Object Layer Visibility Output_ node and the hidden _sceneName_ input on the _Object Instancer_! I'm quite happy that I was able to salvage this file and continue work on it. :)

Even though the scene priority related behavior that lead me to believe that my file was broken was completely unrelated to upgrading to a new version of the addon, I do actually have a few older blends which now display their nodes as all red - so at least one of my original questions still stand.

Is there a way to see what version (or date?) of the Animation Nodes addon was used in a particular blend file?

**Comment by JacquesLucke** [comment]
Sure, that is the deal. You make the art and give you the tools :D

Hm no there is no way to see in which version you created the node tree, but that all nodes are red is a good indicator that you made them in a version before the big refactor I developed this summer.
I cannot promise but maybe your files work in this release: https://github.com/JacquesLucke/animation_nodes/releases/tag/before_refactor_1
unfortunally you won't be able to automatically convert these files to a newer version.

**Comment by AdmiralPotato** [comment]
That was exactly what my older file needed, and it helps a lot to know that my files will need basically one of two major versions. I'm very glad that I will not have lost any work. Thank you so much!

:bread::bread::bread::bread::bread::bread::bread::bread::bread::bread:
