### ISSUE TITLE
[Suggestion] Show a few end elements

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#342]
Just found it can be sometimes useful to know what's going on at the end of a loooong list debug. :tongue:  

Mockup:

![list_end_draw](https://cloud.githubusercontent.com/assets/494788/11444765/72c81f0e-9561-11e5-911f-f7d620af05a9.png)

**Comment by JacquesLucke** [comment]
Yes, I see, I will implement it when I work the next time in this area.

**Comment by JacquesLucke** [comment]
![debug drawer end elements](https://cloud.githubusercontent.com/assets/5881326/11633263/b2f6a81a-9d0a-11e5-843c-aa5368ebcbf7.PNG)

**Comment by LeonCheung** [comment]
Oh that is so sweet. :D
