### ISSUE TITLE
Dose any way to receive the light information [suggestion]

### ISSUE THREAD

**Issue by Leroy-X** [JacquesLucke/animation_nodes#344]
Dose any way to receive the light information, that I can use the light information at somewhere to drive others, for example, have one cube or the cube grids on the scene, and I can use the light strength that the cube have received to influence the cube size. in other words, I can get the light strength at somewhere at the scene.

Just one suggestion, that one node, you can input position vector, and assign the light object, and from the strength output get the position's illuminate strength, and maybe have an other output get the  light's color. so let's you can use the received light strength drive others. and maybe can add this node in the material menu that from add nodes menu.

My English is very poor, hope you can understand, thanks:)

**Comment by JacquesLucke** [comment]
You can always measure the distance between an object and a point light, and calculate a approximated strength from that but that method ignores objects between the light source and the target object. Getting the real amount of light that is on an object is nearly impossible.

**Comment by Leroy-X** [comment]
yeah, I can through the distance do the same effect, but it's only for point light, and if the light source is sport light, it's have direction, strength and  transition, So I am think the light can illuminate the object, inverse, the object can be illuminated by the light, and maybe can use this strength to driver others properties. just one idea~

**Comment by JacquesLucke** [comment]
I can access the strength of a lamp with python but not how much light actually hits the object.
Can maybe create a small example to give me a better idea about what you want to archieve?

**Comment by Leroy-X** [comment]
![01](https://cloud.githubusercontent.com/assets/13515498/11456798/e759ffee-96cf-11e5-9dd8-ea8a8a6ebd14.png)
![02](https://cloud.githubusercontent.com/assets/13515498/11456800/eeb6803c-96cf-11e5-9d5d-867212390247.png)

Sorry, I just saw it
this is an example to explanation, I used the Grid Object make the grid cube, and by the distance node influence the Z position to simulate the light ray influenced on the cube. and I used the node group to simulate the light node, just for reference. 

on the node, I can assigned the light which I wanted, and one Position Vector, with this node can output the light strength(the position by input vector received) and the light color(if possible) .

Very thanks you can care this, sorry my bad English:P

**Comment by JacquesLucke** [comment]
Should be possible but there is a bit more math involved.
I think I will not find the time to try this today...

Maybe someone else wants to experiment with this? @LeonCheung @og76  :p

**Comment by sfire** [comment]
Maybe we can assume that the light from the source distribute evenly along all direction，the light amount of light is linear related with light strength. </br> Then we can use some method like projection to calcate the **amount of light** that hit the object and the **density of hit points**. </br> The two values can be used as output to influence other object properties.
![light_hit](https://cloud.githubusercontent.com/assets/5409756/11456939/00f59800-96d5-11e5-8c89-5110cec9b21a.png)

**Comment by Leroy-X** [comment]
very thanks, Just one idea that I find when I get sleep on yesterday, I think it's interesting and useful at  sometime, so report this suggestion, Hope Animation Node will be much better and better : )

**Comment by LeonCheung** [comment]
For spot light with no blend value, it can be doable/simulatable for now. However, what's reallly hard is to handle more complex cases, such as spot blend, and Cycles light falloff (The strengh falloff is not always linear...). So I don't think there is an easy solution is on the table, but maybe on the way. Possible solution could be to generate a fake based on the spot cone, then casting fake rays (with user-defined number), then generate a list of intersection points with the surface, each point has a normalized strength property value within the list range based on the distance to light source, then using KDTree to match a nearest point to each object within an obj list, then assign the normalized strengh as multiplier to object scale.

But all in all, unless we can access the true camera ray data when hitting on the target surface (I mean Cycles), the it has to be kind of a raycast-kdtree-bvh simulation I guess.

**Comment by Leroy-X** [comment]
Thanks @sfire , @LeonCheung.  Sorry, I don't understand programming, just have an idea, does any way generate the information from material, or any way can analyze which shader point is bright or black. or use the light falloff and the direction to simulate this effects, if have one node to simulation, we can adjust more by manual.
