### ISSUE TITLE
Little Ideas on Time Repeater

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#345]
A picture paints a thousand words:

![pp1](https://cloud.githubusercontent.com/assets/494788/11455254/2ca50642-9690-11e5-8519-55c4a62a9fff.png)
![pp2](https://cloud.githubusercontent.com/assets/494788/11455255/31455cf6-9690-11e5-8d64-ce758db5b0de.png)
![pp3](https://cloud.githubusercontent.com/assets/494788/11455256/36725ae4-9690-11e5-9f80-867de8e37de1.png)

PS: End Pause could be used for both PingPong and Loop mode. fyi  :)
(and how about interpolations?)

**Comment by JacquesLucke** [comment]
I think a time repeater node shouldn't deal with delays. Therefor we have the delay time node. You can always insert a delay time node directly behind the repeat node to create a delay in the beginning. Or increase the *Rate* of the repeat node to get a delay in the end.

About interpolation: hmm I think this would make animations much more confusing.  It's hard to imagine how an animation looks like when you interpolation the time AND the indidvidual movements...
Beside that it would complicate the, so far straight forward, code of the repeat time node.. But you can always fake this effect using a normal animate float node.

**Comment by LeonCheung** [comment]
The problem with a single Delay node before/after a repeater isn't a real "end pause", but a "start pause".

The only way I can simulate the real "pause at the end (not at start)" is by using a couple of nodes:

![with_end pause](https://cloud.githubusercontent.com/assets/494788/11456153/4a1cd820-96b9-11e5-8229-9aefe5093fdf.png)

However, there is no convenient way to pause between ping and pong, so, another couple of nodes are needed again I guess. :-|

**Comment by JacquesLucke** [comment]
yes. seems like you will need these extra nodes atm..

**Comment by LeonCheung** [comment]
Hmm, still think a "pausable" Ping Pong is kind of useful. :tennis: 

There seems to be quite a lot of work for the workaround: http://www.pasteall.org/blend/41360

Your two more cents?

**Comment by JacquesLucke** [comment]
will think about the delay thing again. But the repeat definitly won't deal with interpolations. :)
