### ISSUE TITLE
Cannot completely hide Debug Drawer/Interpolation panel

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#347]
When trying to temporarily hide the these nodes to save screen space, the data viewer area cannot be hidden together with them, unless breaking the connection.

**Comment by JacquesLucke** [comment]
Does this help? :)
the change is also in master

Btw: when you locally setup git it will be much easier to switch between the branches for you :D

**Comment by LeonCheung** [comment]
Ya, that's it, Thanks!
BTW, just found issue #330 still occur in latest version...

**Comment by JacquesLucke** [comment]
Oh I see. I fixed it only in the v1.5 branch

**Comment by LeonCheung** [comment]
Got it. :)
