### ISSUE TITLE
[crash] on Boolean Modifier + set Bmesh On obj + get mesh from object /apply modifiers

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#348]
see the [file here](https://drive.google.com/file/d/0BzzAoBwXO8dseDM2U1pGeVBVLWM/view?usp=sharing),  check use Modifiers for a crash, all the time

it occurs only if:
target has [set bmesh on obj]
object mesh data > use modifiers

not for set mesh data on obj
not other modifiers, but bool

steps
- have an object (mesh)
- add a Object mesh data node to extract respective mesh data
- add a debug so that is used
- add a boolean modifier (that needs another object)
- !! for the other object use a generated one with set Bmesh..(Target.001 ..)

Now, on the Object mesh data check use Modifiers
crash ..

**Comment by JacquesLucke** [comment]
I see the problem but I don't know if I can fix it..
Seems to be a Blender problem. Maybe also related to threading but I don't.. 
Maybe we should try to write a small python script that reproduces this error, so that it is reproducable without animation nodes

**Comment by og76** [comment]
still, it goes only for the very specific set bmesh , boolean,, obj mesh data

there was also a specific issue with boolean/bmesh, that I had to recalc normals and sometmes invert them to get the right result Even if the mesh is very simple and if tab into edit mode the normals look right.

Maybe is worth exploring a bit the bmesh part? Or maybe the order things get executed?
