### ISSUE TITLE
Implement "Tip View"

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#350]
The name may change if someone comes up with a better name.

The main idea is that you can enable an overlay for the node editor that shows you tips on how to improve your node tree. eg I often see people doing unnecessary conversions. Tip View will be able to highlight these nodes.

**Comment by og76** [comment]
speed tips, optimization tips

**Comment by JacquesLucke** [comment]
right. that was part of the plan :)

**Comment by JacquesLucke** [comment]
This won't make it in the v1.5 release.
