### ISSUE TITLE
New Data Type: Fonts

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#354]
Setting fonts is useful in many cases (even in traditional information), but not yet supported by Character Properties node. Can we maybe implement a new data type for controlling fonts?

Currently it's not ideal to set fonts like below because vector font IDs can be unsafe to use:

![font](https://cloud.githubusercontent.com/assets/494788/12037284/727d84d6-ae88-11e5-8394-4f4e1be1a49a.png)

**Comment by og76** [comment]
1. If u wanna have a list of loaded fonts to switch, there is always the issue of fake user/ users that will keep or not the list for next time.
A safe way for this would be to use the 4 slots:
*bpy.data.curves["Text"].font
bpy.data.curves["Text"].font_bold
bpy.data.curves["Text"].font_italic
bpy.data.curves["Text"].font_bold_italic*
and chose by character props what font for what characters
That is actually how these work, bold, italic are just names, u can use whatever font

2. if that is not enough or not what you mean, character properties is not the place anyway. 
That deals with props that can differ per character in the same text obj ( respective implemented props).
That only chooses out of the 4 slots

What you do here is setting the font per text, then in char props you chose use_bold, use italic etc
So either goes in text object  or a separate thing

**Comment by LeonCheung** [comment]
Ehh, not exactly. :)

Just worked out a safe way to set font by name:

![font3](https://cloud.githubusercontent.com/assets/494788/12038283/bf68b6ae-ae91-11e5-9664-80eb89250bf7.png)

You can see the "inconvenience"...

**Comment by og76** [comment]
Just curious. How safe is it?

1. does it work after you reopen the file? is the list bpy.data.fonts intact? 
(assuming they are not used in any of the 4 slots, that gives them fake user)

2. what if you send it to me and I don't have the font file? (the search is giving -1), but if the list is [] ?
I guess blender would replace with default font, not tried, not sure

3. for 3 - 4 fonts u can still use the 4 slots and switch by bold, italic etc, that being safe
(In the blender docs they say that is actually the point of it, whatever..)
But for more, hm..

**Comment by LeonCheung** [comment]
1. I'll surely make fake users for all fonts that I want to project. Or simply set it within AN like this:

![set_fake_user](https://cloud.githubusercontent.com/assets/494788/12045445/9ef141b4-aede-11e5-83d8-0929c85ffd1e.png)

2. I'll pack them into the file before sending to others if I really want to share it, since they are packable (regardless the file size).

3. Yeah, so I think fake users can be well enough to handle that.

What I mean "safe" is that it will no longer depend on font index, but on font name itself. Font indices  are really not safe because they will change when you load or remove any other fonts.

![font_switch](https://cloud.githubusercontent.com/assets/494788/12045515/2f0ba298-aee0-11e5-903b-3d344715a682.gif)

[example file](https://drive.google.com/file/d/0B1ojv5B6Lb-3LThlV1NoZTJMelU/view?usp=sharing)

**Comment by JacquesLucke** [comment]
I just implemented font sockets (only AN-1.5 branch atm).

![font sockets](https://cloud.githubusercontent.com/assets/5881326/12278094/670e144c-b97f-11e5-9d8e-89d5e7b1b032.PNG)

The font is referenced by name. So the user has to make sure that "Fake User" is active for the fonts that are not assigned to an object.

The 'eyedropper button' selects the font that is on the current object.
The font list socket is also implemented.
A font socket can carry 'None'. If you set this on an object the text will disappear.

**Comment by JacquesLucke** [comment]
Is there something else you want to do with fonts?
If not you can close this issue :)

**Comment by og76** [comment]
1. just a note:
with this you only replace *the first of the 4* available fonts in the list
*bpy.data.curves["Text"].font
bpy.data.curves["Text"].font_bold
bpy.data.curves["Text"].font_italic
bpy.data.curves["Text"].font_bold_italic*
that can be switched inside a single object by character props
(despite the naming they are just a list of 4 fonts to switch)
it would be nice to have all 4 accessible, but not a big deal if not

2. @LeonCheung said:

 > BTW, I never got bold, italic, bold & italic working (though I never use them), even I did exactly what the manual told, Probably because of my asian language?

How exactly did you try to use bold etc and did not work?
Manually (b way) or with the character prop node?
(I think it has nothing to do with font/language)

**Comment by JacquesLucke** [comment]
You can set the other font properties using the Text Object Output node now :)

**Comment by og76** [comment]
thank you.
the question for @LeonCheung remains, (even if off topic, it's still somewhat in the area)
or maybe that should be better asked in stackexchange ?

**Comment by LeonCheung** [comment]
Hi, I think Jacques made it very well. For what I mentioned on "failing to set bold / italic", it was my bad... I just figured out they are per-character property (very special case among all blender data). So no problem for now. Thank you guys.

**Comment by og76** [comment]
ok, thank you. and yes, this implementation is ok and probably can be closed.

ps.
the blender way is weird. if in edit mode you select a part of text and hit bold it will do nothing. It matters only from that moment on. (what you type while the bold is on).

This is the very reason I made the node, besides material per character. The node acts like selecting part of the text (by slicing ...) and apply that bold etc

And you can always select the whole text /characters. it works like the slice..
