### ISSUE TITLE
[Suggestion] Adding mesh name output to Object Mesh Data node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#356]
Very useful to reference more data properties conveniently.

**Comment by LeonCheung** [comment]
I mean, "x.data.name" by expression can be sort of boring. It's OK to just keep it hidden by default. :)

**Comment by JacquesLucke** [comment]
![mesh name](https://cloud.githubusercontent.com/assets/5881326/12278614/64668b7c-b982-11e5-9ffc-4cbaab6e8954.PNG)
