### ISSUE TITLE
About keying in AN

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#359]
I got this question since the early days of AN: 

You know, we can insert keys for AN node values, and they do seem working while playing back, but we can't see or edit them in all BL animation editors such as Graph Editor or Dopesheet, etc? Can't they be exposed to "foreground"?

I noticed that it happens to Sverchok, Motion Tool and other py node editors.

**Comment by JacquesLucke** [comment]
Unfortunally not. This is a limitation of Blender... I know somewhere is some more info about this in the release notes or so, but I'm not able to find it atm...

http://blender.stackexchange.com/questions/42540/how-to-create-keyframes-for-animation-nodes-which-i-can-see-in-dope-sheet/42569#42569

**Comment by LeonCheung** [comment]
I see. So it is a blender limitation. Thanks.

**Comment by AdmiralPotato** [comment]
Is there any bug or issue in the Blender tracker that we can star or watch that might provide a solution to this, other than having to create empties in the scene to carry these values?

**Comment by JacquesLucke** [comment]
hmm maybe, I'm not sure. you can search on developer.blender.org
maybe you can create a bug report on it in the tracker although I don't really know if they consider this being a bug.

**Comment by LeonCheung** [comment]
Before that, using helper objects is not bad solution, actually you can put many custom props on one empty if you really have that many values to key.

![custom_prop](https://cloud.githubusercontent.com/assets/494788/12574626/a683b66a-c440-11e5-9e46-d13606249d26.gif)

**Comment by LeonCheung** [comment]
Just got something from Lukas in irc. FYI:

> iirc this is a problem of animation editors (and possibly old depsgraph wrt. evaluating animation). Animation editor needs a clear path of "active" DNA data from the scene up to the animated data. e.g. selected object -> selected material -> selected ***. With nodes this is not so easy because they are not usually uniquely "active". Some other data types have that issue too (e.g. image stuff is not animatable directly afaik, only via material). its a design problem of the animation system beside that the old depsgraph doesn't really allow proper eval of animation in such node trees (the new depsgraph does though).

**Comment by JacquesLucke** [comment]
ah interesting. thanks for the info
