### ISSUE TITLE
Some Opinions on Animation Catetory Nodes

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#360]
When experiencing nodes like Animate Number / Vector etc, a few local users and me noticed that it's usually a pain to switch the concept in mind bwtween procedural-based time (animation starts from 0) and real frame based time (mostly starts from 1), and sometimes it just cause problems when working with other non-AN animations in the scene. Surely we can try deplaying one frame before these nodes, but when working with many many nodes like this it can be boring, and the whole setup will also get messy and messy. Hope you understand what I'm talking about. :)

My idea is to put that Delay option into the Animate nodes, if the user want to "switch" to align the BI frame timeline, they can certainly one-click to make that delay on the nodes.

P.S.: I know we used to have a Delay option on them, but it disappeared since v1.0 (and highly suggest to bring it back! I miss it so much! :D ), and it only delays AFTER the animation done, not BEFORE. So my two cents is to bring back both. Because delay before / after can be usually needed imho.

Another pain is that we cannot "visualize" when the current animation starts and ends upon BI time. I mean, this can be very useful for those users (who tend to be pure artists) who like to create something with AN, but not so good at to design and think "time" in procedual way. So I wonder if it is possible to indicate this information visually for everyone. Because we have to admit that timing control in AN can be powerful, flexible, but definately not "visualizable" for many users, especially artists.

If possible, my two cents for this kind of work flow would be:

1. First, select one or more Animate nodes to activate them;
2. then, one or more couple of markers will display on Timeline, indicates where the actual start / end point would be by evaluating the Time input dependencies.
3. Last, indicators (markers on Timeline) will desappear by deselecting the node(s).

Further thought:
a.) For easy evaluation, I think it's better to warn or limit users that only linear time input are evaluatable (I'm not sure about this).

b.) Maybe it's better to allow users to enable / disable this feature as they wish.

c.) Or simply display the information on the node itself?

If you think mockup is needed, I'll try to make it. I believe this can be very cool. :)

FYI. Thank you.

**Comment by JacquesLucke** [comment]
Well I understand the issue but it is a very very complex thing to solve..
The execution system can't evaluate nodes up a a specific point. Also in some scenarios it just wouldn't make sense.
Where should the markers be when the Animate node is in a loop and animates 100s of objects. And what if the subprogram is called by multiple Invoke nodes. And what if each of these Invoke nodes have different Delays in front of them... 
Not to say that it wouldn't be good in some scenarios to have those markers but coding this would be an absolute mess with hacks all over the place! And I'm not even sure if it is possible to find a generic solution where to place the markers and how many.

So again. I definitly know how good it would be but it doesn't fit well into the whole picture... unfortunally. This is the price we have to pay for so much flexibilty.

Maybe we will have other node systems in the future that would allow this kind of visualization, but not AN :/

**Comment by LeonCheung** [comment]
Yep, roger that.

**Comment by LeonCheung** [comment]
And how about the delay before/after part?

**Comment by JacquesLucke** [comment]
Oh sry, forgot that.

Well that is possible in theory but there was a reason why I removed it. I guess it is the same reason why you want it back haha :p

The network at the top has more nodes but I find it much easier to understand whats going on compared to the second network, although they should do the same thing.

![time delay example](https://cloud.githubusercontent.com/assets/5881326/12421999/10dd84e0-bec5-11e5-834d-78c09e0c87b6.PNG)

**Comment by LeonCheung** [comment]
Yep. That's what I'm talking about. Anyway, you got my point, and I got yours.  :)

**Comment by JacquesLucke** [comment]
yeah, as I said, implementing these two extra sockets is easy. But I would definitly hide them by default.
I can imagine that these sockets can become problematic when you get "delay lags" :D

**Comment by LeonCheung** [comment]
Cool. your choice now. :zzz:

**Comment by JacquesLucke** [comment]
Good night haha :D
