### ISSUE TITLE
vector angle and vector rotation difference

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#367]
Question is:
Should it be 2 nodes? Or one?

I made it as one, though the 2 functions are independent. Then I thought that :
- vector angle is more like distance or dot and goes in vectors
- rot difference is very much like dir to rotaion (and to track quat) only much simpler, so it may go under rotation, next to dir to rotation

What do you think?
2 nodes or 1?
(then I'll just propose them..)

![rot diff](https://cloud.githubusercontent.com/assets/11709974/12423465/50eb68b8-bed4-11e5-88ad-941457d67d7c.PNG)

**Comment by JacquesLucke** [comment]
I think we can have both in one node.

Should we hide the "Rotation Difference" socket by default?

**Comment by og76** [comment]
That is exactly the point, I find that very useful. instead of hiding, I was thinking of a separate node :)
I made it one node till I started using it.

What bothers me is they have very different uses, and outputs. and seams that rot belongs near dir to rot. hmm

There is also the thing that maybe vector dot, length, distance, and angle could be into math node in the future?

**Comment by og76** [comment]
does all this makes any sense or I'm just making too big a philosophy here?

![vector angle2](https://cloud.githubusercontent.com/assets/11709974/12426809/5ffb44b2-bee4-11e5-9dd0-13e7440e8a0f.PNG)

**Comment by JacquesLucke** [comment]
your questions are hard to answer -.-

Yes, I think we may include vector dot etc into the vector math node (unfortunally that will break files, so definitly for the AN-1.5 version).
Maybe we can even put the Rotation Difference into the vector math node..

**Comment by og76** [comment]
hard to answer means I'm making it bigger that it is. 
I'll put them later in a pull or so...

**Comment by JacquesLucke** [comment]
Can we close this?

**Comment by og76** [comment]
sure, it's already in master
