### ISSUE TITLE
List Remove Doubles / Element

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#371]
Another two ideas on list control. Current workaround:

![remove](https://cloud.githubusercontent.com/assets/494788/12452606/40630e5a-bfca-11e5-8d44-4908e1821b76.jpg)

For Remove Element, maybe it's sort of duplicate to the upcoming list boolean feature?

**Comment by og76** [comment]
Note that set is not keeping the original order!
(Probably in boolean in a way ..)

A use case?

**Comment by LeonCheung** [comment]
True, That's why I look for better solution here from you coders. :) Later for the case.

**Comment by og76** [comment]
ok, I had a solution that preserved order, so not quite set, I'll look for it in the files ...

**Comment by LeonCheung** [comment]
Nice. And [here](http://pasteall.org/blend/40206) is a case in which preserved order isn't quite necessary. But it would be good to preserve it in many cases for sure.

**Comment by LeonCheung** [comment]
The case also exposes that we are lacking of concurrent processing, which cannot be provided by the loop IDs, since they are unique.

**Comment by JacquesLucke** [comment]
OMG so many e-mails haha

I think this is a bit related to this: https://github.com/JacquesLucke/animation_nodes/commit/e6b5abc4fde96c2d06ac83428b139e9736c1613d
I'm not sure why it isn't merged already :D Will check it again.
This node doesn't directly provide a function for removing doubles but I can use the "Union" function for it... Well I didn't test it, but I think so.
An extra node fore removing doubles would be nice anyway :)

**Comment by og76** [comment]
I'm dusting off some files for the right formula I had around on that (and no, it's not in bool list)

Till then, the Loop would look like this:
![remove dupli list](https://cloud.githubusercontent.com/assets/11709974/12457341/9ad35340-bfac-11e5-9099-a9443babe18f.PNG)

note the reuse ..

**Comment by LeonCheung** [comment]
I wonder if this is a safe way to remove doubles, or other better workround?

![remove doubles](https://cloud.githubusercontent.com/assets/494788/13385005/a658747c-ded6-11e5-822b-3e1ec073989f.png)

**Comment by LeonCheung** [comment]
I wonder if this is a safe way to remove doubles, or other better workround?

![remove doubles](https://cloud.githubusercontent.com/assets/494788/13385005/a658747c-ded6-11e5-822b-3e1ec073989f.png)

**Comment by JacquesLucke** [comment]
This here is the fastest solution atm:

![list boolean operations](https://cloud.githubusercontent.com/assets/5881326/13395521/99cd3a94-deef-11e5-99ee-2199a9f5623f.PNG)

**Comment by LeonCheung** [comment]
Ahhh!!! So simple!!! I think we may close this topic?

**Comment by JacquesLucke** [comment]
yep hehe
