### ISSUE TITLE
Suggestion: Particle trajectory sampler node

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#372]
Last weeks I´m doing some experiments to recreate cool motion design examples done with other software like C4D and  Houdini. And I have found some functionality that could make AN better.

In this case the idea it´s to obtain samples from the location of a particle trough time which will help a lot to make effects like growing hair. Something similar to the Btrace plugin but with the control and flexibility that AN brings.

The idea behind this node is something similar to the curve samples nodes but applied to particles.

**Comment by og76** [comment]
same as #248 
you don't have access to that data in script

the only way is to : 
- use render > path
- cache > bake
- in the modifier (particle sistems) you'll hace a convert button
- respective converted object is a mesh so you have to again convert to curves

and you get an obj with cute splines that are the paths of the partc
they can further be used as any spline in AN

**Comment by YorsLosilla** [comment]
I guess that this answers my next suggestion that was a node that can retrieve from the points of each strand from a particle hair system.

Here ares some links that I can´t understand but maybe they could be usefull:

http://code.blender.org/2011/01/a-look-at-point-cache/
http://blender.stackexchange.com/questions/15577/how-to-extract-convert-data-from-blender-cache-files-bphys-into-a-human-readabl
http://blenderartists.org/forum/showthread.php?340983-How-do-you-set-hair-dynamics-and-particle-cache-with-Python
http://stackoverflow.com/questions/10581133/load-baked-particle-system-cache-in-blender

**Comment by YorsLosilla** [comment]
Would it be possible  to access somehow to particle trail data?

**Comment by og76** [comment]
just  proposed hair data (points etc)

they result in lists per particle, so NOT adding to particle list info
this breaks the existing node by adding other sockets, so **adding only to v1.5** !!

Not about cache, about normal hair data, as several points per particle
(the splines in the pic are generated per hairs)

![hair partc](https://cloud.githubusercontent.com/assets/11709974/12574707/fc545b6c-c40e-11e5-8b94-9c8e560f1727.PNG)

**Comment by YorsLosilla** [comment]
I just can say one thing: awesome. A new Pandora's box has been opened.


-----Mensaje original-----
De: "og76" <notifications@github.com>
Enviado: ‎26/‎01/‎2016 8:28
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Suggestion: Particle trajectory sampler node(#372)

just proposed hair data (points etc)
they result in lists per particle, so NOT adding to particle list info
this breaks the existing node by adding other sockets, so adding only to v1.5 !!
Not about cache, about normal hair data, as several points per particle
(the splines in the pic are generated per hairs)

**Comment by LeonCheung** [comment]
@og76 Thanks for the contribution! I found it's very useful for putting hairdresses. BTW, I did some test and wonder why the instance at the tip of the hair was jittering in [this case](http://pasteall.org/blend/40309), I used the same hair point amount for spine sampling (4 in this case). However, when I set it to 5 or so, it seems fine.

**Comment by JacquesLucke** [comment]
I'm not absolutly sure but I guess it has something to do with the fact the handles of the bezier spline are exactly on the points -> there is no tangent at that point, which leads to jittering.

You can fix it by changing the *End* value in the *Get Spline Samples* node to 0.99 or so.

**Comment by LeonCheung** [comment]
It seems so. Thx for the solution.

**Comment by LeonCheung** [comment]
Five months ago, I asked **[something](http://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=2928398&viewfull=1#post2928398)** about that, now you made it! :)

**Comment by og76** [comment]
Glad it's useful. Truth is, I don't use that part (hair) that much.
Maybe it happened more like recycling, cause I worked for a while on a commercial of women getting rid of hair (bad hair...) So they lose hair, AN gets hair :D. (Nothing is lost, all is converted ..)

- for the general trajectory, cache etc, I guess having *the manual baked mesh is the right way*. And I don't think atm that AN should do much on the conversion, it would be probably a very slow (like text separate) and even more complicated to monitor/manage. Point is you need all the points and do the rest in An.

- 5 months? I promised some features (I already knew of earlier) and still postpone them ..  -_-  (err, see euler math..) Hair? it took a while to learn that, I don't use much hair (in 3d, ok)

**Comment by og76** [comment]
1. I have already described how to sample trajectory of an object, particle or deformed vertex etc in some of the vids on the forum. Unlikely to become a node, But for a simplified case, maybe a q in stack would do.(I have to make simplified vids or explanations of that anyway)

**Comment by YorsLosilla** [comment]
Well maybe you can take a look to the bTrace addon. This addon is a particle tracer for Blender. Which works very well but doesn´t offer you the same level of control. If we somehow be able to create and intermediate that can´t take position and frame info for each particle and save to a CSV. We will have the ability to create awesome particle trail effects.
