### ISSUE TITLE
Question: Ability to create mesh and assign UV coordinates?

### ISSUE THREAD

**Issue by AdmiralPotato** [JacquesLucke/animation_nodes#373]
So far, working on the 1.0/master branch of Animation Nodes, I've been having a rather hard time creating procedural mesh data, and I eventually ended up just writing a python script to create the data that I wanted output - but I've just come to a barrier that would actually prohibit my next phase of the design I'm currently working on: I want to assign procedural UV coordinates to the procedural mesh that I've just created. I guess this question is two part:

1: Is there currently an efficient workflow for generating procedural meshes in Animation Nodes?
2: Is there any way to create procedural UV coordinates for that same mesh?

I was also having a hard time finding documentation or examples of the above, so if there are any currently available resources on this topic, I would really appreciate some links covering the topic.

Thanks! :D

**Comment by og76** [comment]
for meshes, yes. 
a clear example would be better, asking about it in stackexchange would even make it easier to find.

about uv, I experimented with it a bit, but never had time to take a serious approach.
(both vertex color and uv are having a slightly different approach on how they fit on poly/vertex)
but yes it's doable, at least on scripting atm

**Comment by AdmiralPotato** [comment]
Thank you for the suggestion tobask this on SO, I will need to post it a bit later though. Perhaps I should clarify on my previous usage of a script - I was using a Script Node to output (VectorList, PolygonIndicesList) data for a Mesh Data node, and assigning that Mesh to an Object in the scene. I think that it is here where I seem to be lacking the options for UV data...?

**Comment by og76** [comment]
yes, that could be the place for UV.  or not quite so ...

*Mesh to obj* or *set bmesh on obj* ! as mesh>bmesh ... bmesh> obj allows for some extra bmesh ops in between (recalc nor, remove doubles etc)

This can be a bit tricky: 
- if u have a clean direct mesh output, then the UVs would match some indices 
- If u have to use bmesh ops or so, may end up with different indices on the object.

The UVs may be eventually specified **on object or on bmesh**, as those can carry such data. mesh data is just vert/pol index.

Setting *on the bmesh before* some extra ops (remove doubles?) may help Not alter the UVs. Hard to say now, some ops preserve such data, some not. 

However, eventually there will be a get/set UV node(s)  ...
