### ISSUE TITLE
Grouping objects by AN

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#375]
I wonder if we can define which group(s) an object can be in? It seems the deep copy doesn't work for it. Besides, it could also be useful in some cases I bet.

**Comment by JacquesLucke** [comment]
what do you mean with "can be in". Any object can in any group, or not?

**Comment by LeonCheung** [comment]
Oh, or I mean "is". :)  I actually mean a way to assign or create group for specific object or objects. One  useful case is to create group with dynamic amount of objects, which can be used by group-related node for example.

**Comment by JoseConseco** [comment]
Plus + for this one. I'm creating groups this way:
![image](https://cloud.githubusercontent.com/assets/13521338/13412766/e7557604-df45-11e5-81af-eddf3923fb41.png)
And then assign instances  with another expression. But It is kind of ugly...

**Comment by JacquesLucke** [comment]
d57f57795cc1891442d2bab642b504c94c48f8fc

**Comment by JacquesLucke** [comment]
d57f57795cc1891442d2bab642b504c94c48f8fc

**Comment by JoseConseco** [comment]
Sweet. I tried to make group create node (from string output new group), but thing is AN is creating new group for each letter I type in...
`import bpy
from ... base_types.node import AnimationNode

class ObjectGroupOperationsNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_ObjectGroupCreateNode"
    bl_label = "Object Group Create"

    def create(self):
        self.inputs.new("an_StringSocket", "Group Name", "groupName")
        self.outputs.new("an_ObjectGroupSocket", "Group", "group")

    def execute(self, groupName):
        if not groupName: return None

        if not groupName in bpy.data.groups.keys():
            bpy.data.groups.new(groupName)
        return bpy.data.groups[groupName]`

**Comment by JoseConseco** [comment]
Jacques any chance making above code work?

**Comment by JacquesLucke** [comment]
oh sry, I forgot this one -.-
have you tried the "Object Group by Name" node?
It doesn't create new groups but that would be a bit risky.. for the same reason you mentioned... better you create the groups you need manually..

**Comment by JoseConseco** [comment]
Yep I tried it. Works ok, but only if group is already created... Well I guess manual creation of groups is way to go. Thanks!
