### ISSUE TITLE
Suggestion: Quads from points

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#376]
Could it be possible to create some node that creates no overlapping and interconnected quad or tri meshes from lists of vectors?

Guess probabily not. But it would defnitively be cool.

**Comment by og76** [comment]
yes, in a very limited way.

There are many issues there and I have explored quite a bunch of situations for such.
There are methods to create a reasonable organized mesh using some sorting methods and comparisons. 

But what generates the points? That will make a difference.

(However, the easy and safe one will use convex hull (2d or 3d). That will not include all points and may not always be quite right and it's not a grid really, but only a "perimeter".)
