### ISSUE TITLE
Some list operations are unneccesarily type limited.

### ISSUE THREAD

**Issue by raingloom** [JacquesLucke/animation_nodes#383]
Edit: explicit conversion works, however, inputs for some operations are still limited and implicit conversion to generic types would be a huge help

I have a simple subprogram that selects N elements from a doubly linked list, which I want to use for lists of any kind, yet I can't find any way to get AN accept the string list output of a script as a generic list input for this one.
Since list operations seem to operate on simple Python lists, I see no reason why they should be limited like that.

**Comment by og76** [comment]
an example blend? wfm
![convert to generic](https://cloud.githubusercontent.com/assets/11709974/13032013/e00421a4-d2eb-11e5-89ad-c4abc1a6f280.PNG)


yes, the convert node you get from menu/search and it's not automated (added on plug..)

cause generic list is not recommended, ex. it can easily give None that is not accepted in lots of cases (a vector is the easy one, but meshes are a hell ..) and will give an error. Btw, scripts should avoid None too ..

But if you know what you are doing, it should just work..

**Comment by raingloom** [comment]
[Here](http://www.theorysend.com/view/694345fcfab78e7d49a77df5299624b77a052c00) is an example file.

**Comment by raingloom** [comment]
Ah, turns out I can use explicit conversion.
Still, the list combine node should not be limited to numeric lists, so the issue is still valid.

**Comment by og76** [comment]
see the advanced panel (or hit U) and manually change type of list
some nodes do not do that auto/by connection,

There is no difference/ limit of type   in the list nodes, just some are not auto ..doing stuff

and the advanced panel / U is something to watch.

**Comment by raingloom** [comment]
Ah, I had no idea it had that setting. Thanks, it'll probably work now. Closing.
