### ISSUE TITLE
Node Statistics

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#385]
1. The total nodes count seens not working so great with multiple trees (node datablocks). (To test it, try duplicating an existing one, then adding / removing nodes there).

2. Suggestion: Maybe it is better to also provide counts for individual tree?

3. Discussion: Is it really cool that node types like *Reroute* and *Frame* should be taken into account?

**Comment by JacquesLucke** [comment]
Yes this Overview panel is not yet finished...

I thought about making an "overlay" that you can show and hide in the node editor. This way I could show more information in a more compact way.

**Comment by LeonCheung** [comment]
Nice idea.

**Comment by JacquesLucke** [comment]
Is someone willing to make a mockup for the overlay?
Like so:
![overview mockup mockup](https://cloud.githubusercontent.com/assets/5881326/13640851/958cb97c-e616-11e5-9c9e-aacd9ee78083.png)
if there are more stats you may find useful just write them on the mockup

ps: I just made a mockup for a mockup hehe

**Comment by LeonCheung** [comment]
No idea right now.... I think useful info may include:
- Total count
- Functional nodes count (excluding nodes like Retoute or Frame, since they are more like helper node).
- Subprogram count
- Time display (we've already had it)
- Enabled / disabled / error stat
- ID Key count maybe?

**Comment by JacquesLucke** [comment]
Thanks, I'm working on it now

**Comment by JacquesLucke** [comment]
![statistics](https://cloud.githubusercontent.com/assets/5881326/13724060/6c5754e4-e879-11e5-9347-ece2480f5231.PNG)

This can be extended later, I think it's already quite cool :)

**Comment by LeonCheung** [comment]
Yes. Cool enough :)
