### ISSUE TITLE
Animation_Nodes and scenes

### ISSUE THREAD

**Issue by adallafontana** [JacquesLucke/animation_nodes#388]
Seem there is no way to use more than one scene for file.
The Animation_Node node graph is the same for all scenes.
Is so or I'm wrong.

**Comment by LeonCheung** [comment]
There are some nodes that got a **Scene** input hidden by default, which can be toggled in N panel, to make certain sense in more than one scene.

![scene](https://cloud.githubusercontent.com/assets/494788/13164046/497b7786-d6ed-11e5-8ceb-f4a117d07bd0.png)

Currently there are a few nodes hidden in Ctrl A searcher, try keyword *Scene*.

**Comment by adallafontana** [comment]
Thank you Leon,
the "Scene" in "Time Info"  what I was researching.
