### ISSUE TITLE
What does Update Matrices node do?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#390]
I noticed that one for a while, but didn't see any visible difference by using it. When we should use it? And how?

**Comment by JacquesLucke** [comment]
https://www.blender.org/api/blender_python_api_2_76_2/info_gotcha.html#no-updates-after-setting-values

Calculating a matrix based on location rotation and scale takes some time. So blender doesn't update the world matrix of each object immediatly after you change eg the location. 
Some times in AN you want to set the locations etc and then use the world matrix for further transformation (eg in the FCurve Animation Offset template), so this is when you can use the Update Matrices node :)

**Comment by LeonCheung** [comment]
Thanks! I'll have more look on that. :)
