### ISSUE TITLE
Fallback idea

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#391]
For Get element, A possible new option that allows taking specific item from the list can be convenient. I believe most of the time the fallback would be expected to be the last/first item from list, while we usually have to add at least an extra Get Element node to do so. FYI.

**Comment by JacquesLucke** [comment]
This sounds more like a "Clamp Index" checkbox

**Comment by LeonCheung** [comment]
Could be. :)

**Comment by JacquesLucke** [comment]
ok, I've added this in the v1.5 branch.
