### ISSUE TITLE
Conditional Debug node

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#394]
This can eg be used in loop to debug a custom iteration and not always the last one. Maybe also extend the existing debug node with a boolean input

**Comment by JacquesLucke** [comment]
What do you think about conditional debug nodes? @LeonCheung @og76 

![gif](https://cloud.githubusercontent.com/assets/5881326/13332792/0804ea50-dc04-11e5-9488-40018d44e563.gif)

**Comment by JacquesLucke** [comment]
and would you name "Condition" differently?

**Comment by LeonCheung** [comment]
Interesting! Actrually I was sometimes tired of having to find a specific item in the Debug List result, so this one would be really nice for that. 

I think Conditional Debug is okay for me. (Or what? Selective Debug? Filtered Debug? LOL )

Just curious about two things:

1. What will be displayed when receive False?
2. For multiple items, Draw style like "One Element per Line" would be more expected? Just like Debug Drawer node.

**Comment by JacquesLucke** [comment]
The normal debug nodes work all with the same principle. They hold a string until it is overwritten by another value.
So when the condition is always false the debug node will show the last value or "None" if there was no value before. I know that this can lead to confusion but it is the only way I know atm on how it can work.
This also means that it doesn't work with multiple values. So when the condition is True multiple times in a loop you'll only see the last value.

**Comment by og76** [comment]
I'll have to test this ...
but what about the loop debug (that currently writes to txt) ? any (related or not) plans? 
+ the logic where you can plug more than one param? (In the example above that would be ex obj , vector )
