### ISSUE TITLE
Remove List Debug node?

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#399]
I would like to get rid of the "Debug List" node because I think we don't need it anymore.

Without we still have the normal Debug node, the Debug Drawer and Debug Loop node. I think that is enouph. What do you think?

**Comment by og76** [comment]
I sometimes use normal debug instead of list debug, to see what is actually there.
i see the idea, but, at least if there's an option/advanced or so... to keep the normal mode on? :)

**Comment by LeonCheung** [comment]
I think it can still be useful to output spefic list data, say user may want to output a list of vertex locations of a mesh, then disconnect re-use it by other nodes. I kinda use it like this before.

**Comment by JacquesLucke** [comment]
ok, then it can stay in :)
I just wasn't sure if someone actually needs it .
