### ISSUE TITLE
Logo for Animation Nodes

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#400]
I think it would be nice to have a logo for AN. 

masterxeon was so nice to make some mockups:
![img_27022016_073750](https://cloud.githubusercontent.com/assets/5881326/13373170/40f29c4c-dd60-11e5-9e92-e84424051ed8.png)

What do you think about them? do you have other ideas? Or do you think we don't need a logo at all?

**Comment by LeonCheung** [comment]
I just wonder where can we use it. The interface? I'm not sure if it is possible since I never saw any other addons using customized icon.

**Comment by JacquesLucke** [comment]
not sure haha
maybe in videos or so. I guess it's more a nice-to-have atm...
Just some thought :)

**Comment by LeonCheung** [comment]
Aha, Alirght. Then some of my thoughts:

![logos](https://cloud.githubusercontent.com/assets/494788/13377792/781b7e3a-de25-11e5-8589-58e2532a1b30.png)

Concepts: 

- A and n.
- A molecule.
- A 3D-style cube custructed with 2D-style node elements, 
- A magician's box. (too many possibilies, who knows what will come out of it.  :)

**Comment by kopias** [comment]
![an-logo](https://cloud.githubusercontent.com/assets/3462746/13390832/20dd7766-ded1-11e5-80d0-7f32ca2034b0.png)

[an-logo_inkscape.zip](https://github.com/JacquesLucke/animation_nodes/files/150618/an-logo_inkscape.zip)

**Comment by JacquesLucke** [comment]
Thanks for the suggestions!
I personally prefer flat simplistic logos without many different colors and details..
Beside that I really like the concepts that went into yours designs!!

@LeonCheung Is there a specific why you textured the cube this way?

**Comment by LeonCheung** [comment]
Nah, just try some variants with different color sets. [Here](http://pasteall.org/blend/40864) is the blend file, you can tweak freely if you like.

**Comment by LeonCheung** [comment]
P.S.:
1. The Camera is located at (5,-5, 5), with rotation of (90, 0 45), which is the standard 2.5D angle.  :P
2. Ideas from masterxeon and kopias are also interesting. I have to admit that. :)

**Comment by JacquesLucke** [comment]
Thanks

yeah I like them too, but they don't as much deepness as your idea :D
Deepness in a flat logo ^^

**Comment by JoseConseco** [comment]
I like the black version from LeonCheung the most. My  take:
![image](https://cloud.githubusercontent.com/assets/13521338/13413228/52a1db66-df49-11e5-8c42-a55616649af2.png)

**Comment by LeonCheung** [comment]
Or something like this? Behold the big generic socket.

![v2b](https://cloud.githubusercontent.com/assets/494788/13419044/420928fa-dfb6-11e5-8d52-de948757beb3.png)

**Comment by LeonCheung** [comment]
Evolution:

![logo_rev](https://cloud.githubusercontent.com/assets/494788/13421293/813bb01c-dfc8-11e5-96c6-5e5d2d06ee66.png)
click for full size preview (2048 * 2048)

What's your opinion?

**Comment by LeonCheung** [comment]
BTW, it seems blender can now support custom icons for addon. See [here](http://blenderscripting.blogspot.cl/2015/05/custom-icons-in-blender-add-on-scripts.html) or some answers on SE.

**Comment by JacquesLucke** [comment]
oh also interesting! that's why I like to work with artists haha
I will look at them in more detail later.

yes I already have some experience with custom icons, because I reimplemented the icon system used by the HardOps addon. but I don't know yet where we can use custom icons to our advantage.

**Comment by JacquesLucke** [comment]
@LeonCheung 
I still wonder if there is a specific reason for these sides:
![logo test](https://cloud.githubusercontent.com/assets/5881326/13424055/b33b377e-df9e-11e5-94b3-52e5a40b4bdf.PNG)
Sry, if I'm missing something obvious.

@JoseConseco I like that you combined 'A' and 'N' in a good way. One thing I don't like is this wobly effect (not sure if that word exists^^) I prefer straight lines like in the adaption of Leon.

Of the 6 logos by Leon I like the two on the right the most. The one at the top is very clean while the one at the bottom contains a connection to Blender. GJ!
I wonder if there is way to make it more clear that AN is a node system.. I have no idea how :D


I want to thank you all in that moment for these great ideas, and sorry if I seem to be a bit picky!

**Comment by YorsLosilla** [comment]
For me the logo that stated more clearly that AN is nodal was the one from kopias

-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎01/‎03/‎2016 11:25
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
Asunto: Re: [animation_nodes] Logo for Animation Nodes (#400)

@LeonCheung 
I still wonder if there is a specific reason for these sides:

Sry, if I'm missing something obvious.
@JoseConseco I like that you combined 'A' and 'N' in a good way. One thing I don't like is this wobly effect (not sure if that word exists^^) I prefer straight lines like in the adaption of Leon.
Of the 6 logos by Leon I like the two on the right the most. The one at the top is very clean while the one at the bottom contains a connection to Blender. GJ!
I wonder if there is way to make it more clear that AN is a node system.. I have no idea how :D
I want to thank you all in that moment for these great ideas, and sorry if I seem to be a bit picky!

**Comment by JacquesLucke** [comment]
Yes that's true, but as I said, in my opinion it contains to much stuff. That makes it difficult to recognize when the logo is very small.

**Comment by LeonCheung** [comment]
@JacquesLucke Well, those two parts are just simply to representing the two letters. nothing else. In the last image, I sort of beautified of both parts to make them of the same height (from G to Y).

Btw, the red point is clearly representing a node socket. And a logo with :black_circle: :red_circle: :white_circle: color sets can have very strong visual impact to eyes. imho.

To be honest, nowadays design concept of having too many details on logo is not that popular and recommended unless it has to (e.g. a portrait). I do think kopias' design is quite fresh, just... a bit too  "representational" imho. Again, visual impact is the soul to VI (visual identification), e.g. we don't have to know what Blender is only by looking at Blender logo, right?  :)  Just try letting people remember that, then you win.

So I tried not making them that representational. Here comes the easter egg:
![node_tip](https://cloud.githubusercontent.com/assets/494788/13425358/2aeda7e2-dfe1-11e5-9a11-0589d9330149.png)

**Comment by YorsLosilla** [comment]
Maybe you can put a node pictogram on the top  face of the cube

-----Mensaje original-----
De: "Leon Cheung" <notifications@github.com>
Enviado: ‎01/‎03/‎2016 12:15
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Logo for Animation Nodes (#400)

@JacquesLucke Well, those two parts are just simply to representing the two letters. nothing else. In the last image, I sort of beautified of both parts to make them of the same height (from G to Y).
Btw, the red point is clearly representing a node socket. And a logo with    color sets can have very strong visual impact to eyes. imho.
To be honest, nowadays design concept of having too many details on logo is not that popular and recommended unless it has to (e.g. a portrait). I do think kopias' design is quite fresh, just... a bit too "representational" imho. Again, visual impact is the soul to VI (visual identification), e.g. we don't have to know what Blender is only by looking at Blender logo, right? :) Just try letting people remember that, then you win.
So I tried not making them that representational. Here comes the easter egg:

**Comment by LeonCheung** [comment]
True, the top face can have too many things to put on. Brainstorming, guys!

**Comment by JacquesLucke** [comment]
haha very good. In that last image you clearly see that AN has something to do with nodes xD

I tried to modify Leons logo a tiny bit. What do you think about that? 
![420928fa-dfb6-11e5-8d52-de948757beb3](https://cloud.githubusercontent.com/assets/5881326/13425592/3cc14eda-dfa8-11e5-9239-1e70c22d6d2e.png)

**Comment by LeonCheung** [comment]
LOL, very nodal indeed, sharing quite a similar concept to the "top face" hint.

**Comment by JacquesLucke** [comment]
Yes,

what I like about this is that it 'contains' the blender color scheme, an A for animation and a node -> Blender Animation Nodes.

But I'm still just brainstorming..
I also like that box but in my opinion it doesn't really represent AN.. but maybe I'm wrong. I never designed a logo before ^^

**Comment by LeonCheung** [comment]
Actually I had something hidden there, exposed as below:
![node](https://cloud.githubusercontent.com/assets/494788/13426427/37561a80-dfe8-11e5-938b-b5baf4f33b29.png)

Maybe I like to hide things too much...

**Comment by LeonCheung** [comment]
Well, brainstorming, right? Forgive me, haha :smiling_imp: 

![jl2](https://cloud.githubusercontent.com/assets/494788/13428085/14fc9558-dff3-11e5-86fb-c2490f7b30d9.png)

**Comment by JacquesLucke** [comment]
hahahahaha that looks strange!! :D

**Comment by YorsLosilla** [comment]
Ultrasupercool!!!!!

-----Mensaje original-----
De: "Leon Cheung" <notifications@github.com>
Enviado: ‎01/‎03/‎2016 14:21
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Logo for Animation Nodes (#400)

Well, brainstorming, right? Forgive me, haha

**Comment by LeonCheung** [comment]
@JacquesLucke, assuming this is what you want to do:

![v3](https://cloud.githubusercontent.com/assets/494788/13454498/9f2b114c-e092-11e5-856b-3da99f1bd44d.png)

I think it's mainly a combination of ideas from JoseConseco and kopias... and you.

**Comment by JacquesLucke** [comment]
Yes I really like this direction,  but I wonder if we need these additional details compared to my last proposal?
Your logos look a bit like two logos in one with the gear in the middle.
Nevertheless, I like yours too and I can imagine to pick one of these as the official logo but it's hard to choose the right one haha

**Comment by LeonCheung** [comment]
I see. That's why share the source file for further refinement from you or others assuming the direction is good. (Anyway, still more a fan of the toy brick style personally. ;p)

**Comment by JacquesLucke** [comment]
Ahhhhhh ok that is a shame. I had a totally wrong view on your cube idea -.- I had a very selective perception on it -.- (maybe that doesn't make sense to you haha)

Ok so now I also like your idea even more haha But I will have to take a look at them again.
Do you have a favorite?

**Comment by LeonCheung** [comment]
Ah, it's also a tough decision for me. It seems I'm a bit of a perfectionist (you too? :D). So in fact I'm still not so satisfied with any of them (hmm, perhaps excluding the one with your portrait lol). Personally I'm willing to see more ideas, maybe from someone like Gottfried Hofmann afaik. :)

Or, there can be other options:

- Simply by decorating the words "Animation Nodes".
- It's also okay for you to say that we do not need any logo for now.

**Comment by GottfriedHofmann** [comment]
We also did a kind of visualization of nodes once: http://www.blenderdiplom.com/cache/resized/9055d474c91f9032a56e8543c9783143.jpg

Creating a logo from a concept like "nodes" is really difficult. My favs atm are the ones on the right of the first post.

**Comment by JoseConseco** [comment]
Lots of cool stuff, but I liked the black box the most. Anyway remade colors on this:
![image](https://cloud.githubusercontent.com/assets/13521338/13490889/579540ee-e12f-11e5-9f2f-1c88f4682671.png)

**Comment by DavidBoura** [comment]
I'd see each letter of Animation Nodes in a node, all nodes connected. Just my 2 cents..

**Comment by Leroy-X** [comment]
I like blender style much more, white and blue, and some orange, more unified, keep simple...

**Comment by anuprao** [comment]
While I realise this is an old thread, but still marked open, here is my suggestion:

![an_logo_anup](https://cloud.githubusercontent.com/assets/7333789/23579864/88ca2cfc-011c-11e7-
9c03-8ae4adabadd3.png)

**Comment by GottfriedHofmann** [comment]
@anuprao that idea is the best imho!

**Comment by Pswida** [comment]
My 2 cents

![obraz](https://cloud.githubusercontent.com/assets/17111356/25923055/0b5de926-35dc-11e7-9b7f-dac3fb1ab068.png)

**Comment by JacquesLucke** [comment]
I like those a lot too. very simple, as a logo should be.
Can you tell me more about why you designed them the way they are?

**Comment by Pswida** [comment]
The idea was to form small caps "a" and "n" or just "a" with graphical reference to:
- connection
- modularity/pattern
But now I think it was too blurry

So I did other project with clear nodes representation and words. I also have started to like this sheared rectangle giving some dynamism. What do you think?
![animation_nodes_logo2](https://cloud.githubusercontent.com/assets/17111356/26019938/c1682f4e-3779-11e7-8296-45fa4b9208bd.PNG)

**Comment by JacquesLucke** [comment]
ah I see. I like that the A in you first examples also looks a bit like an N :D

The sheared rectangle looks good as well. The dynamism fits to Animation Nodes.
My main concern with those is that the image itself (without the text) might not look very good and not very representative for AN.
It would be best to have an logo/icon that works good with and without text next to it.

Anyway, thanks a lot for your suggestions so far. I think I like them the most. They look a bit more timeless than the others.

**Comment by Pswida** [comment]
Ok, thank you for comment. I will do some other tries (maybe with light connection to logo of Blender), so soon I will show them.

**Comment by Singh-KS** [comment]
Here I made a logo for animation nodes. 
![an_logo](https://user-images.githubusercontent.com/30294746/28744859-28c9bfe0-7488-11e7-889f-d47b00c90264.png)

[AN_logo1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1184948/AN_logo1.blend.zip)
