### ISSUE TITLE
Object Mesh Data should be able to output the correct mesh when it has shape keys

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#401]
This seems to be relatively complicated. There is a way to apply the current shape key mix on a mesh but it doesn't work well and needs the context..

**Comment by og76** [comment]
? what is the actual goal? or issue?

It is simple to just get/set the shapekeys on an object as a separate node
shapekeys is just a vector list (vert loc), so let the mix be done in AN further

**Comment by JacquesLucke** [comment]
My goal was that the Object Mesh Data node outputs the same mesh that you see in the viewport..
Maybe you're right but the problem is the mixing of multiple shape keys. I'm sure it can be done in python but I guess it's much slower..

**Comment by og76** [comment]
could you give an example of not working right ?
at least, I don't get it on the usual/basic attempts.
![shapekeys01](https://cloud.githubusercontent.com/assets/11709974/13397851/6a704f1a-df04-11e5-829a-3b167f21a0d5.PNG)

**Comment by JacquesLucke** [comment]
Oh damn it haha
you're right. Looks like I messed something up in my scene when I tested this.
Perfect hehe
