### ISSUE TITLE
AN 1.5 big usage of CPU, while idle.

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#405]
Hi I have tested AN 1.5 today and I noticed my cpu fan was bit loud. And blender report 18% cpu usage while all node tress are disabled (disabled auto execution). When I reverted to older AN version, same scene - 0 cpu usage. 
Unfortunately I cannot share the scene. But maybe later I will try to test this on blend file that I can share.

**Comment by JacquesLucke** [comment]
Hm okay, thanks fo the report.. I will have to fix that.
