### ISSUE TITLE
Navigating through multiple node trees

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#406]
Lets say I have node tree, which uses group subprogram from another node tree. I is becoming hard to remember where do I have to go, to find definition of my groupSubprogram. I would like to see something like in cycles materials:
a) 'tab' on group opens temporary nodeTree with group definition, 'tab' again to go back to edited node tree
b) or if this is impossible - maybe add option for pie menu: 'open subprogram definition' which would switch  us to node tree with  group definition...

I think a) could be great way to clean up all the busy node trees. Basically user would only see the invoke nodes, and if he wanted to edit them - enter 'tab' key.

**Comment by og76** [comment]
same as #407
