### ISSUE TITLE
Holding v1.5 a bit

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#408]
Just a quick note for Jacques:

Before [this bug](https://developer.blender.org/T47651) being fixed, I think it's better to hold the coming release. I bet it may confuse quite a few guys when installing the .zip file. Just my two cents.

**Comment by JacquesLucke** [comment]
yes I've seen it...
But releasing means that I merge everything into master. so nobody gets this installation problem.

anyway, there is still some work left before the release.
