### ISSUE TITLE
Error with Expression List

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#413]
It seems debug nodes fails to debug single item list output from expression node? 
![exp](https://cloud.githubusercontent.com/assets/494788/13554383/5790fbd8-e3e1-11e5-98a3-9a710fbd6957.png)

**Comment by JacquesLucke** [comment]
Well that is because the Debug Drawer expects a list and not a single item.
Not sure if it makes much sense to fix it. Maybe I can catch the error message and write it in the node.
but it's better to show an error here because it indicates that you are using the expression node in a wrong way

**Comment by JacquesLucke** [comment]
3bead84a5ac5a05f31405804d20b0bd6735db012
