### ISSUE TITLE
[Suggestion] Remove Element Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#414]
Since we already got Get Element (read) and Set Element (replace), removing can also be of some usefulness.

**Comment by LeonCheung** [comment]
Got it, but also something I don't quite follow: Why not remove by index number? 0.0

**Comment by JacquesLucke** [comment]
yes ok, we can have both :) I'll add it later

**Comment by LeonCheung** [comment]
Haha, ok. Btw, the current behavior seems to remove the first matched element, isn't it?

**Comment by JacquesLucke** [comment]
right

**Comment by LeonCheung** [comment]
cool.

**Comment by JacquesLucke** [comment]
Can you test all the different cases? And also that the node correctly changes it's type when you connect to different types.
ff30fb52735be0ae8c404279ffac8a34197a36b3

**Comment by LeonCheung** [comment]
Sure, will do in 10 hrs  ;)

**Comment by LeonCheung** [comment]
For normal lists, so far so good! Just... for list types like mesh data, polygon, etc, it seems different. Is that sort of an exception?

**Comment by JacquesLucke** [comment]
Oh, good catch!
I'll have to exclude some list types from this node

**Comment by JacquesLucke** [comment]
This was quite a bit more complicated than I thought in the first place.
I hope it works now..

**Comment by LeonCheung** [comment]
I see the point. Here is the test on every possible list types, Green means works fine, yellow means that I thought it would work, but not?

![test](https://cloud.githubusercontent.com/assets/494788/13622992/3200cdae-e5de-11e5-904e-9104589aa415.png)

[test file](http://www.pasteall.org/blend/40979)

**Comment by og76** [comment]
vec, eul, quat, matrix, color   will always have an issue with float precision, so comparison will fail in some cases. 
same with search list.

**Comment by JacquesLucke** [comment]
yes o.g. is right.
I'll consider this node as done now :)
thanks for your effort

**Comment by LeonCheung** [comment]
got it.
