### ISSUE TITLE
Suggestion: Internal Outputs for Loops

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#419]
The idea is to give some recursiveness to loops by adding outputs that instead of being out of the loop will available inside the loop for the next iteration of the same element.

This will be a nice way to pass data from the previous iteration an introduce some sort of responsive content inside the loops making them more aware of their previous state. For example locations, etc.... This will allow also to calculate speed.

What are your thoughts about?

**Comment by JacquesLucke** [comment]
This is already implemented
Here is a simple examle:
![reassign loop parameter](https://cloud.githubusercontent.com/assets/5881326/13604470/196b6ac4-e543-11e5-9763-cce2d7513d7b.PNG)

**Comment by YorsLosilla** [comment]
Sorry the spam. Didn´t know. Really, really, cool feature.
