### ISSUE TITLE
node to check wether a point is in a volume defined by a bvh tree or not

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#420]

**Comment by og76** [comment]
I'll take on to that if u like, did previous testing on how, but dropped it for a while.

1. A method is **using bvh nearest** or object/mesh closest point (both have same issue) that give also a normal of that closest point. Then compare with the normal (dot vector). The issue appears if point is on an edge or a vertex, as the normal reported /polygon indicated are randomly chosen from the ones that contain that point/projection. Here, the normal of the vert or edge (an average of the polys or the 2 verts) has to be used. 

Even so, the results are not always reliable and when it comes to distance to respective surface, that can lead to some ugly results.

2. The other common method is **to shoot a ray** and count (even /odd) how many times it intersects the surface. Here I'll have to test how to use ray cast to do so, considering, again, the exceptions of edge/vertex overlap that can give errors. Usually this is the used one, but I'll have to test in detail.

If you know of other methods, pls say so.

-

For 2d geometry I have studied this more and got reliable and pretty efficient methods, but that cannot translate into 3d directly. Or maybe it could, if I create a 2d section of the obj in that place. But not tested such. Yet.

**Comment by JacquesLucke** [comment]
yes I think the first method is the one I used here: 
http://blender.stackexchange.com/questions/48519/how-can-i-use-the-new-bvh-nodes-to-know-if-a-certain-object-is-inside-a-volume/48524#48524
(this is where the idea came from, to make this node now)

But feel free to write that node yourself. I have enouph other stuff to do :)

**Comment by og76** [comment]
same issue there, if the nearest is on edge or vert. so extra check for such exception is needed.

example: see the Z of the empty 001 that shows the normal ...
(The empty is outside, but in relation to the normal is inside)
![bvh edge issue](https://cloud.githubusercontent.com/assets/11709974/13639651/5f8c8b82-e61a-11e5-9c74-a4318a97c2b1.PNG)

**Comment by JacquesLucke** [comment]
How do you want to check for that?
I guess the easiest (fastest) way would be to shoot in a "very random" direction and use the inaccuracy of floats to our advantage

**Comment by JacquesLucke** [comment]
This way it's very unlikely to hit an edge exactly.

To be even more sure that the result is correct you can also shoot out 2 or more rays

**Comment by og76** [comment]
Not so uncommon. More than expected really. Try with a grid of cubes if inside a torus, animated, and see if respective condition (size or so) really works (It's prone to be used for many points and in animation)

I was doing that in one of my YouTube vids, and even with extra check on the edge and vert is was still failing at a certain point.

**Comment by og76** [comment]
Ah, as extra comparison I was taking that poly and check if the projected point is on the edge or a vert, and if so, the normal would come from the vert or avg verts of the edge. 

I'll check again

but hey, seams the the vertex normal is waiting for you on every corner :D  (this time literally)

**Comment by JacquesLucke** [comment]
can you finish this node within the next week?

**Comment by og76** [comment]
here are some raw variants:
[is inside ](https://drive.google.com/file/d/0BzzAoBwXO8dsVjZLT0dEbDFONjg/view?usp=sharing)
[find nearest](https://drive.google.com/file/d/0BzzAoBwXO8dsUGVqVUZPYzZxOGc/view?usp=sharing)
and a blend to test
[closest2.blend](https://drive.google.com/file/d/0BzzAoBwXO8dsekFvR0lZZWRXNXc/view?usp=sharing)

The py nodes are both bvh find nearest, only the _is inside_ has this extra check on the verts/edges and if the case, it replaces the normal from bvh nearest (poly normal) with the appropriate vertex or edge normal.

-

the logic is the following:
If the hit is on an edge or vert, the polygon and normal reported are random chosen, so it can be the one facing away from the point. giving false inside result. 

This goes even for the basic cube sometimes, but mostly for edge angles less than 90.
- In this case, ray cast can give any angle to that edge/poly, at least find_nearest will limit this to under 90deg angle of faces
- even so, the hit on edge will give errors especially for verts or edges that are pointy ..
- the trick is to extra check if the point is on verts then edges

Maybe this schema is more explanatory:
![extra check edges 1](https://cloud.githubusercontent.com/assets/11709974/13725337/25d947e2-e8a7-11e5-9b02-f7a5b8c7d7af.jpg)

 -

The extra code does:
- see the hit poly index 
- check for verts of that poly first / if hit, replaces normal with vertex one
- if not vert, check the edges / if hit, replaces nor with the avg of the 2 edge vert nor

the rest is point dot normal to see if inside/on surf/outside

**Comment by og76** [comment]
As UX or node logic, considering I have the same base of the bvh find nearest,  I see 3 possible cases here:

1.**2 nodes**, one simple find nearest, one complex is inside. As the ones posted above
2. **single find nearest node** with option to "advanced normals", no inside job, the rest, the dot operations on normal is done outside the node
3.  **single find nearest node** with option to "advanced normals/ is inside volume", that also has the point dot normal stuff

The 1. is weird cause the find nearest is part of the is inside anyway, it's just faster and sometimes you don't need the rest, just the distance or so...

The 2 and 3 seam saner, I just don't know if I should include the dot(normal) in the node or not.
Seams cleaner to just have advanced normals, but it's not obvious to users that the dot normal will do such a job

Thus, **probably v3 is the best**, with the "advanced normal/ inside volume" option that basically:
- creates the extra poly indices + vertex sockets
- extra is inside/ on surface outputs (or a simple -1/0/1 integer?)
- adds the extra code to codelines

That would be like the posted 2 nodes, but one with an option.

**what do you think?**

-

Please test extensively, As you'll see in the blend, if u use the simple find_nearest you'll get a lot of exceptions in the grid (play animated). So far the complete seams ok, but who knows..

-

Notes:
- the basic code as much as the extra code could go into an algorithm file. the basic goes for more than one node..
- I check for vert first and than for edges. I found that this goes faster, but also better 
- The all in one variant has the advantage of the point.dot(norma)l also being compared against a precision/tolerance, yet another thing that a user has to do (rounding?) for a better result. **Without the tolerance, the float precision error will fail here too in some cases**
