### ISSUE TITLE
How to delete unused NodeTree?

### ISSUE THREAD

**Issue by allkhor** [JacquesLucke/animation_nodes#421]
Unlink datablock has no effect. Tested on both version master and 1.5 with blender  2.76b, 2.77 rc2. 
OS: Xubuntu 14.04 x64, core: 3.19.0-51-generic.
Maybe i not understand how it's work? Thanks!

**Comment by LeonCheung** [comment]
Hit space then search for ”animation nodes". Good luck. :)

**Comment by allkhor** [comment]
Ohh, thank you! There I was not looking. Remove Animation Node Tree.
