### ISSUE TITLE
Text Issue with Stat

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#425]
Just wonder if there is anything we can do on AN's side:

![stat](https://cloud.githubusercontent.com/assets/494788/13726699/92a495a4-e90e-11e5-9df9-8d54dc8db9bb.png)

I was trying to localize AN, and it seems the Frame and Reroute aren't translatable here? Even with i18n turned on.

**Comment by JacquesLucke** [comment]
Hm it may be possible to fix this somehow. But I wonder if it's really worth it..
I guess it has something todo with these lines:
https://github.com/JacquesLucke/animation_nodes/blob/AN-v1.5/ui/statistics.py#L179-L180

**Comment by LeonCheung** [comment]
Actually I did replace those two labels too, but it seems they are sort of hardcoded internally so it failed.

Not a critical issue anyway. Close it if it should be. :)
