### ISSUE TITLE
"Copy" for list parameter

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#426]
How does the "Copy" option work?  :)

**Comment by JacquesLucke** [comment]
![loop copy option](https://cloud.githubusercontent.com/assets/5881326/13733218/39bad200-e990-11e5-8345-c8e5c418efa2.PNG)

**Comment by JacquesLucke** [comment]
basicly it means that the value is copied at the begin of each iteration., it's turned off by default for performance reasons.

**Comment by LeonCheung** [comment]
I see, thanks.
