### ISSUE TITLE
[Suggestion] New option for color input

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#427]
Allowing to choose whether it outputs a color with or without the alpha value is useful to control most of the color values in Blender.

E.g. for diffuse_color, which is a  RGB only value instead of RGBA, it has to be clipped by [:3].

**Comment by JacquesLucke** [comment]
hmm, well the convention in AN is that each color is RGBa
I know that isn't ideal in all cases but it's better than just having rgb everywhere because then we would be limited...

**Comment by LeonCheung** [comment]
True. Just thought whether it's better to add a hidden-by-default toggle to convert the color to remove alpha, when they want to control colors orther than Cycles mat (such as BI mat). It seems expression will be used, in which case, it might be unlikely for them that they don't know how to convert it, by [:3] for example.
