### ISSUE TITLE
AN v1.5 Status

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#428]
Currently there is only one node left that will be included in the v1.5 release: "Sort List"

Are there any last missing bits you would like to see in v1.5 that can break compability? Then please tell them now.

@LeonCheung, @og76, @JoseConseco, @YorsLosilla

**Comment by og76** [comment]
I'll open issues for each:

1.
I'd like to have the old simple transform polygon and a generic/general change pivot in matrices.
this way : 

- it would work for any case, not just polys, 
- will be more flexible, allowing more even for the polygon
- the transform poly would be slim again, if not using such pivot stuff

also, there could be a brother get polygon matrix, if the case. though it's kinda like composing the matrix out of the current poly info, so not necessarily

2.
I would like to have a better implement of distance to line / distance to plane along with other geometry tools of this kind. they could stay as is, but will be redundant with nodes that do a bit more (out of same code)
So 

- that would go into a separate geometry folder
- a algo /geometry may be needed
- I'll add more to it

3.
*not sure if matters here but could be*
 I'd like to move the dir to rotation code to an algorithm, cause I need it in other places
(and maybe change it a bit, to make the 4x4 directly, as it should have been, so the output of the formula is matrix ... )

4.
*not sure if matters here*
I have to take a look in the matrix to point/normal, the 2d/3d plane definition and also make the reversed point/normal to matrix. I used this  lots and  I will need this extensively in the 2d/3d geometry part and I wanna make sure it has all needed conditions or so.

5.
*not sure if matters here*
plus couple of little ones, but that is no showstopper / breaker

**Comment by YorsLosilla** [comment]
While it will be Nice custom pivot points for matrices. I must disagree with the idea of removing custom pivot point for transform polys. It's pretty convenient and  more user friendly than matrices.


-----Mensaje original-----
De: "og76" <notifications@github.com>
Enviado: ‎18/‎03/‎2016 14:35
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] AN v1.5 Status (#428)

I'll open issues for each:
1.
I'd like to have the old simple transform polygon and a generic/general change pivot in matrices.
this way : 
it would work for any case, not just polys, 
will be more flexible, allowing more even for the polygon 
the transform poly would be slim again, if not using such pivot stuff 
also, there could be a brother get polygon matrix, if the case. though it's kinda like composing the matrix out of the current poly info, so not necessarily
2.
I would like to have a better implement of distance to line / distance to plane along with other geometry tools of this kind. they could stay as is, but will be redundant with nodes that do a bit more (out of same code)
So 
that would go into a separate geometry folder 
a algo /geometry may be needed 
I'll add more to it 
3.
not sure if matters here but could be
I'd like to move the dir to rotation code to an algorithm, cause I need it in other places
(and maybe change it a bit, to make the 4x4 directly, as it should have been, so the output of the formula is matrix ... )
4.
not sure if matters here
I have to take a look in the matrix to point/normal, the 2d/3d plane definition and also make the reversed point/normal to matrix. I used this lots and I will need this extensively in the 2d/3d geometry part and I wanna make sure it has all needed conditions or so.
5.
not sure if matters here
plus couple of little ones, but that is no showstopper / breaker

**Comment by og76** [comment]
not if u have same stuff in a node that outputs matrix and just plug into poly transform. 

what I don't like is that the poly trs is limited to certain cases. for example u can change pivot / vector but cannot indicate an axis for the rotation (around an edge or so)

and in combination with other matrix combinations can be quite confusing, at least if default would be world ..

however, workin on that right now ..

**Comment by YorsLosilla** [comment]
I understand your Point. But it's important  to keep things as simple as possible.


-----Mensaje original-----
De: "og76" <notifications@github.com>
Enviado: ‎18/‎03/‎2016 15:32
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] AN v1.5 Status (#428)

not if u have same stuff in a node that outputs matrix and just plug into poly transform. 
what I don't like is that the poly trs is limited to certain cases. for example u can change pivot / vector but cannot indicate an axis for the rotation (around an edge or so)
and in combination with other matrix combinations can be quite confusing, at least if default would be world ..
however, workin on that right now ..
