### ISSUE TITLE
make general change pivot node instead of extra options in the transform polygon

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#429]
this would be a convenience, for the "hard to understand" combine matrix list operations needed to do such. 
point being, we need that elsewhere and should be bit more flexible

that may render the extra options in polygon transform useless (or confusing)

I'll post an attempt

**Comment by JacquesLucke** [comment]
Yes, please make a simple prototype, or tell me the inputs/outputs this node should have.
We can have such a node but I think we should keep the pivotType property in the anyway. If you calculate the matrix somewhere else you just have to set the pivot type to World.

**Comment by og76** [comment]
added several input types, default is matrix
(not adding different pivot types, as they would be substitutes of vector math or rot etc)

they are needed for certain cases as list, as you'll make a complex op in a loop and having change pivot for all is not easy (transform  * mat.invert, do stuff, transform * mat)

sure, now that I look at it, may wonder why is that not as an extra in the transform nodes. guess it is possible with an option, so that we still have the basic speedy transform.

![pivot](https://cloud.githubusercontent.com/assets/11709974/13926434/fc9fa926-ef94-11e5-8f3d-65616d167156.PNG)

**Comment by og76** [comment]
as per #428 comments

**Comment by JacquesLucke** [comment]
I'm still trying to understand how to use this node in context.. Can you provide some simple use cases for the different modes?
also, what exactly is a "Pivot Matrix"?

**Comment by og76** [comment]
Pivot Point Matrix, 
(but actually it also changes the orientation/scale .. so it's **more like parent** than just pivot. )

This replaces the 
- combine matrices node case, where you'd have matrix invert, do stuff, matrix
- transform vector by matrix inverted, do stuff, transform by matrix
- if that is the only operation, it also has list variants, to skip a loop just for that (or for a transform Vector List )

For example, the flip polygons around edge case: The node is equivalent to the frame below and also can be used as rotation variant)
![pivot1](https://cloud.githubusercontent.com/assets/11709974/14005097/380c8658-f168-11e5-9a09-daf428e3741a.PNG)


This is where it all started, really (flip polys). And currently, the transform poly does not cover it

2.
**Should I also include Polygon and spline** into the accepted inputs? It kinda pairs with transform nodes. I did not, so that I leave the polygon as is

**Comment by og76** [comment]
I remade the pivot, actually with some variants to see.
but first, have to check dir to rot algo as it is wrong in a case ( #445 )

**Comment by og76** [comment]
#467 
I think this is the formula.
In the end, this should make a complicated matrix operation understandable.

-

I tried more axe variants, but they are more confusing than helping imho
The variants should cover
- specific use cases (like the polygon) 
- provide different approaches/inputs

to have more variations on the same set (axes) is almost like redoing whole nodes inside another

it looks like this now: in the right, the options, the left, poly flip usage
![piv1](https://cloud.githubusercontent.com/assets/11709974/14226329/1fe6dea2-f8e8-11e5-83a6-c75d170ea59f.PNG)

I only kept 2 var of axes, the one with the poly and the one with xx zz as start end this being very different than dir to rot node, that uses 2 directions. 

another example is "parent/changin coord sys" of a motion
the sphere is rotated, but the x axe depends on cube
![piv2](https://cloud.githubusercontent.com/assets/11709974/14226349/7d8fb236-f8e8-11e5-8427-b1b29f2bce71.PNG)

more examples can go..

-

just as example, another attempt with more variants don't really make more sense, at least 2 being dir to rot in poor form
![piv3](https://cloud.githubusercontent.com/assets/11709974/14226388/8149b7fe-f8e9-11e5-998a-a89c8d58a3d6.PNG)

also adding extra xyz ops or extra menu is too much

**Comment by JacquesLucke** [comment]
We'll keep it the way it is for the v1.6 release.
Maybe we can clean up all the options in a later release
