### ISSUE TITLE
add new set of geometry tools

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#430]
I have tackled this for a while now and should start adding some

For this, I think we need a **dedicated folder/menu/category** called geometry
It contains ops that are not quite vector, not quite mesh stuff and so on, so I see it as a separate thing. For example the vector nodes are somewhat more basic than these 

Also, the recent distance to edge/plane are already part of it in a slightly different way

**Comment by JacquesLucke** [comment]
I think we should make the new category now, but making more nodes for these category can be done later, because adding nodes doesn't break existing files etc.

**Comment by og76** [comment]
the only break can be in the recent distance to line/plane that is redundant to my project point on line/plane . others indeed are no break


that also gives the location and a factor/parameter that is needed in some cases (just like the nearest bvh also gives not just distance)

also using another mathutils geometry for the edge
also, I wanna use edge as name elsewhere, when I actually use edge (socket ..) not any line ..

coming soon with these two and couple more related, like matrix to plane point/nor and inverse, or maybe, others, in time

**Comment by og76** [comment]
added geometry folder (+ init)

adding:
- project point on line (includes _distance to line_ and _factor,_ as parameter 0-1 start line >> end line)
- project point on plane (includes _signed distance_ to plane)
- convert plane types: does point/normal to matrix and matrix to point/normal, 

as sometimes it's easier to refer to object matrix instead of point/normal, while point/normal is gonna be used everywhere to define a plane (cheaper). I avoid having this as option inside node, as it will repeat in many nodes

should remove : 

- distance to plane/line as those are redundant (and not more efficient)

examples:

![project point on line](https://cloud.githubusercontent.com/assets/11709974/13924919/f4203992-ef8e-11e5-8cc4-ca0d21cb9470.PNG)
![project point on plane](https://cloud.githubusercontent.com/assets/11709974/13924923/fac152e0-ef8e-11e5-80e8-3ec2f09ddcfb.PNG)

**Comment by og76** [comment]
this also needs dedicated menu (and some more stuff in time)
#428

**Comment by og76** [comment]
I will add more to this. 

But I just realized that I forgot to remove the distance to line/plane nodes (redundant)
I did change the vector menu to point to the Project... nodes and the proj nodes do have search tags Distance to ..

Even so, I should have removed the redundant :(.  But now the version is out ... now what?

**Comment by JacquesLucke** [comment]
I'm not at the pc now, but I think I removed these redundant nodes

**Comment by og76** [comment]
true . sorry, my bad ...  :)

I'll keep posting here the new geometry nodes, 
separate issues only if the case ..

**Comment by og76** [comment]
For further geometry nodes, for v1.51 or so.

Please take a look here 
https://github.com/og76/animation_nodes/tree/geometry-intersections/nodes/geometry

New stuff with respective questions are:
- point list normal, (just calculates normal for some points) this is it.
- barycentric transform (deform a point using source/target triangle(sets of 3 v as reference))
 Should I include transform _point list_ besides _single point_? The rest is just as is ..
- a set of intersect nodes:
 - should I group them as [line x line/plane/sphere] [planes x spheres] etc? 
  Not sure and not sure how convenient ..
 - the polyline x plane is a special case, so it will be separated. probably gonna add a polyline x mesh variant etc  (may add sphere here, but it's kinda useless)

Now generally:
+ Should I go for some algorithm here too?
+ in lots of them I used isLinked for everything, vecs, bool, not just lists. ok?

otherwise they are fully workin, tested such for quite a while now, and may give examples of use

**Comment by og76** [comment]
actually the **barycentric** is a very interesting transform tool (transform vector)
it works as an **adaptive for triangles**. 
and only requires 3 points, no other data ;)

This is why I ask if I should do a list version already, cause that is the way, not for one point
However, it will not replace the adaptive as is more directed to 2,5D tricks. 
afaik, it is used for UVs and other mesh 2d-ish data, or could be used for mesh deform (using a mesh as lattice to deform another)

I'll make an example of that later. Now I'm concerned of how to implement right..

example basic, source tri to target tri, deform a cube
![barycentric](https://cloud.githubusercontent.com/assets/11709974/14169615/78a6c1c8-f731-11e5-965a-9057cd736392.PNG)

used in a loop as adaptive for tris. I'll work later on a more serious version, but this is why a list would do too.
![barycentric adaptive tris](https://cloud.githubusercontent.com/assets/11709974/14169668/dc6442da-f731-11e5-9c85-edb190ba6657.PNG)


ps. in comparison to quad adaptive:
- less controllable, it uses the tri for loc/rot/sca, though the Z scale is automated here...
- for other than tris, should have much control over the triangulation / tessellating way in order to get cute results
- the original adaptive is as efficient as it goes as math, this one would imply +triangulate+detect what point goes in what tri, +deform + assamble back the original poly from tris ...
- this has nothing to do with mesh normals, so there will be no continuity for higherZ, as the curvature of surface goes (the essential trick of adaptive)

**Comment by og76** [comment]
for the others I'll make examples later. 

just to give you an idea, on the polyline/plane special case, some basic examples

using as edges (actually I'll make a poly too) to make points out of a section (somebody asked this a while ago)
![edge sectioning](https://cloud.githubusercontent.com/assets/11709974/14170633/780c92dc-f737-11e5-89ca-519e9566af9d.PNG)

or cuttin the polygons and makin splines
![spline sections](https://cloud.githubusercontent.com/assets/11709974/14170655/8d0ad6bc-f737-11e5-976e-16998adb0d16.PNG)

or sample a spline and cut the "polyline" with some planes and make splines of it
![hatch1](https://cloud.githubusercontent.com/assets/11709974/14170685/ab085798-f737-11e5-95af-a0af4a6d05dd.PNG)

**Comment by YorsLosilla** [comment]
That's really cool. New things to learn

-----Mensaje original-----
De: "og76" <notifications@github.com>
Enviado: ‎31/‎03/‎2016 10:57
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
Asunto: Re: [JacquesLucke/animation_nodes] add new set of geometry tools(#430)

for the others I'll make examples later. 
just to give you an idea, on the polyline/plane special case, some basic examples
using as edges (actually I'll make a poly too) to make points out of a section (somebody asked this a while ago)

or cuttin the polygons and makin splines

or sample a spline and cut the "polyline" with some planes and make splines of it

**Comment by og76** [comment]
just the tip of the isceberg..

on the functions / algo case, I'm never sure how to approach this

The self.fuction in the mesh example goes for some, and I kinda like it more than "abstract" code lines

but where you have lots of options getCode is skippin a lot of "if" , like if useDegree just adds some lines or not 
the dir to rot is a good example as it normally skip lots of lines in the pivot, cause I choose from the start ZX. so all that part is gone in the final script

hm

**Comment by og76** [comment]
just added pulls for intersections
intersecting lines planes sphere like this:
(a special one for polyline plane)

#528 

![int line line](https://cloud.githubusercontent.com/assets/11709974/15177219/aaf4a080-1777-11e6-8eee-0c0907cc2c1b.PNG)

 #529 
![int line plane](https://cloud.githubusercontent.com/assets/11709974/15177231/b5e604b6-1777-11e6-83ea-315aa889823c.PNG)

 #530 
![int line sphere](https://cloud.githubusercontent.com/assets/11709974/15177237/baa65bae-1777-11e6-8800-ce50b5a48ef3.PNG)


A special one here. Initially this was meant to be able to evaluate a spline/ or polyline on a world axis, as we cannpt do this today (we can project or eval by factor but not as world X)

 #531 
![int polyline plane](https://cloud.githubusercontent.com/assets/11709974/15177239/c21e1e94-1777-11e6-9658-7b8a54a39a9a.PNG)
more examples can be given here..

 #532 
![int plane plane](https://cloud.githubusercontent.com/assets/11709974/15177242/c65bf170-1777-11e6-806a-775ad4d4f5e9.PNG)

 #533 
![int sphere plane](https://cloud.githubusercontent.com/assets/11709974/15177252/cc725b8a-1777-11e6-8cc5-1882333f4fb6.PNG)

 #534 
![int sphere sphere](https://cloud.githubusercontent.com/assets/11709974/15177261/d1650d36-1777-11e6-89c2-7c3b9c587a94.PNG)

**Comment by og76** [comment]
also added barycentric transform, normal and triangulate (tesselate) #535 #536 #537 
like this:

an idea about barycentric
![barycentric01](https://cloud.githubusercontent.com/assets/11709974/15177435/bebb4d66-1778-11e6-9bce-21287dd95ad3.PNG)

some normal stuff
![normal](https://cloud.githubusercontent.com/assets/11709974/15177444/c6f64efe-1778-11e6-99d6-1317ef531628.PNG)
![normal2](https://cloud.githubusercontent.com/assets/11709974/15177458/d8f70882-1778-11e6-8dfd-0e7f51354410.PNG)

the (big) triangulator / tesselator with all options
![tesselate](https://cloud.githubusercontent.com/assets/11709974/15177478/ece7de2a-1778-11e6-9566-bd032c0334d2.PNG)

Note on tesselate / triangulate (outside bmesh, that has it's own thing and faster than all)

I would have used the only the simple variant, no ngon etc as it is 2x to 5x faster , but is unpredictable in flipping the indices/normal in a way i cannot figure, so I leave the others too

The case where it goes flip is actually the very polygon indices / mesh data / polygons list, the very listish ones. hm

(I may have another formula later, as I have looked deeper into delaunay formulas and such, but we'll see)

**Comment by YorsLosilla** [comment]
I´m really excited about this new nodes. One of the few things that AN lacks is recursiveness and ways to implement some sort of simulated behaviours, where elements are aware of other elements conditions an react based on changes on such conditions. Some sort of IA. This is partially due to the limited recursiveness of loops and their deterministic approach.

However it seems that with these new nodes we will be able to implement more complex rules of behaviour to objects. Needless to say that it will take time to explore all the possibilities.

As you mentioned before this is just the tip of the iceberg.

Great job o.g. Congratulations new widgets have been added to swiss knife.

**Comment by JacquesLucke** [comment]
@og76 can you also write the release notes for these new nodes? Please try to keep it short :D
I guess you can put all into one section: "New Geometry Nodes" or so

**Comment by og76** [comment]
bit later.
guess more or less using the above examples? maybe not all
guess I could rather point to doc pages and just add more there ..

**Comment by og76** [comment]
oh, and also I'll put stuff into menu, for this and other missing..

**Comment by JacquesLucke** [comment]
yes, you can also write the node descriptions into the node-docs and link there... (not sure how linking works though -.-)

**Comment by og76** [comment]
ok.
guess there is still
#535 barycentric, 
#536 normal, 
#537 triangulate/tesselate
and #533 intx sphere plane, #534 intx sphere sphere

whenever u have the time :)
  I actually made the small changes since the others, but workin on desktop git, I guess I somehow I've not synced or so..

**Comment by JacquesLucke** [comment]
Yes I'll check them a bit later. Have to do some homework atm...
Learning about cpu modes hehe: http://blog.codinghorror.com/understanding-user-and-kernel-mode/ :D

I guess I can merge these last few pull requests soon when you updated them (haven't checked today if you already did) :)

**Comment by og76** [comment]
done

ps: see this cpu too :D 
http://www.wired.com/2016/05/ibm-letting-anyone-play-quantum-computer/
