### ISSUE TITLE
Suggestion: Offstet animation data with the Object Instance node

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#434]
The idea which maybe could be hard  to apply is to have an option to offset by frame the recorded keyframes from instanced objects, something like what the AREWO addon from Blenderdiplom does without the need of loops.

**Comment by LeonCheung** [comment]
Select the Object Transform Input node then hit U. If you mean sommething like that.

**Comment by YorsLosilla** [comment]
Not exactly. The idea is to offset animation data on instanced objects on fixed rate. Like for example one frame per copy.
  

-----Mensaje original-----
De: "Leon Cheung" <notifications@github.com>
Enviado: ‎22/‎03/‎2016 9:26
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] Suggestion: Offstet animation data with theObject Instance node (#434)

Select the Object Transform Input node then hit U. If you mean sommething like that.

**Comment by og76** [comment]
u are talking about #235 , that does what I used to do with attribute nodes in some examples

**Comment by JacquesLucke** [comment]
The Object Instancer node should not have to care about moving animations around.
