### ISSUE TITLE
Object Renaming in Object Socket

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#439]
I'm thinking about the possibility to rename the object that is assigned to an object socket by shift-clicking on the eyedropper icon.

**Comment by og76** [comment]
should be somehow obvious, (like a pop or so?)
what happens when renaming a AN managed object (instance..) ? being inside AN, can have a warning or so

**Comment by JacquesLucke** [comment]
yes. there should be a little popup dialog. I guess this is faster than searching the object in the outliner

Hmmmm no, unfortunally that doesn't work well...

**Comment by og76** [comment]
speaking of witch, what about a "show/select object/objectList in Blender" (advanced?)  
a reversed variant of add selection to list

**Comment by JacquesLucke** [comment]
no entirely sure what you mean... Does this have anything to do with this renaming issue?

**Comment by og76** [comment]
no, sorry

**Comment by JacquesLucke** [comment]
8a151caf4e4b2b7c868173e87f746c4884f69e3e

This new functionality works in the object and spline socket.

![rename object popup](https://cloud.githubusercontent.com/assets/5881326/14140651/9f4b7376-f67a-11e5-9753-52fe269eec97.PNG)
