### ISSUE TITLE
I wish there was tilt output in 'getSplineSamples' node

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#443]
Here  I did simple arranging of objects on spline.
![image](https://cloud.githubusercontent.com/assets/13521338/14055908/143a5d52-f2e6-11e5-8387-73988c1ef046.png)
But there is no option to set monkey guide axis with spline tilt. I think it may be usefull for people...

**Comment by JacquesLucke** [comment]
I know, it's currently not part of the Spline system of AN, but I think we can add this later.

**Comment by sambler** [comment]
I'll expand on this and say that the `radius` and `weight_softbody` properties are also missing. There is also a `weight` property used with nurbs which is the nurbs equivalent to the bezier handles.

The radius allows the size of the bevel to be adjusted at each point and with the tilt would be two properties that are often used with curves.
