### ISSUE TITLE
change rotation algorithm to code lines instead of yield ?

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#445]
Before starting to use it in other nodes, stopped to decide this:

**Should I change it to code lines**, so that it returns clear, **joined strings**?
Or leave as generator using yield? What is best here ..?

1. it does not matter to dir/rot node, as that has simple
`    return  generateDirectionToRotationCode(...) `
so it works same in both cases

2. difference is:
 - if I need other lines too, today I have to 
 ```
    yield stuff..
    for codeLine in  generateDirectionToRotationCode(...):
        yield codeLine 
    yield stuff..
 ```
 - if I move the algo/function to codelines, returning joined, I'll have a plain
 ```
    yield stuff..
    yield generateDirectionToRotationCodde(...) 
    yield stuff..
 ```
   
At least, I should document that .. (in the comments inside algo ..)
??

**Comment by JacquesLucke** [comment]
I prefer to have generators because they look much cleaner and are a bit faster I think (not sure).

Not sure if you mean this: Since Python 3.3 there is a great new syntax feature, which is the "yield from" statement.
https://docs.python.org/3/whatsnew/3.3.html

It yields every element in a list (or from another generator function) separately

**Comment by JacquesLucke** [comment]
Also maybe you should rename the function to "iterDirectionToRotationCode" so that it is clear that it is a generator and doesn't return a string directly

btw: as soon as you have one yield keyword in a function, it is automatically a generator function. That also means that any return value is ignored. So you just type 'return' instead of 'return ""'.

**Comment by og76** [comment]
ok, I'll try the iter from. 
it's not a big deal to use the generator, just not obvious 
(hm. obvious to who? us? ;) )

**I prefer not to rename the function, so that I do not change the direction to rotation node**
guess it will broke it
I think I should just comment in the algo function "instructions" after I try the iter/from etc

ps:  as speed, guess this only impacts execution code changes, when tree changes, sockets etc
as code, there is no difference, as long as it is already generated

**Comment by og76** [comment]
yeah, works with yield from
We should just leave it to that

example with pivot node ..
![pivot2](https://cloud.githubusercontent.com/assets/11709974/14060854/7a5903d4-f379-11e5-85d3-b149a31a9c93.PNG)

**Comment by JacquesLucke** [comment]
it's very important to write code that is obvious to us! Otherwise it will be very hard to maintain a project with thousands of functions.

Renaming the function shouldn't break the node as long as you don't change the sockets.

**Comment by JacquesLucke** [comment]
Yes these getExecutionCode functions are only called when the tree changed but for big nodetrees this should make it fast as well (I know, it doesn't make much difference here..)

**Comment by JacquesLucke** [comment]
The code on the image looks good! :)

**Comment by og76** [comment]
and works good
flippin polys around edges etc ..

**Comment by JacquesLucke** [comment]
perfect hehe

**Comment by og76** [comment]
**the Dir to Rot algo is broken for matrix output** in the last ver
it does affect scale on exception, X (guide) being 000

I'll have to check if it's the current implement or the prev one too (since matrix 4x4)

**Comment by og76** [comment]
I checked shortly.
The current implement is wrong, the prev, with codelines is ok.
I'll dig later.

try this file in master and in 1.6 and you'll see the difference if X is 000 (both x points are same)
https://drive.google.com/file/d/0BzzAoBwXO8dsTEtPMUFEdDdHNFk/view?usp=sharing

**Comment by JacquesLucke** [comment]
Hmm I see I couldn't figure out why this happenes yet... I'm sure it is something super simple -.-

**Comment by JacquesLucke** [comment]
ahh got it

**Comment by og76** [comment]
yes, if it's scale issue, the guide exceptions that return 0 ;)

**Comment by JacquesLucke** [comment]
yes. should work now.
I also made a very little change here: fe79eb3b7deb8b083817ce92d8521b17c529129b
it should still give the same result but one less cross operation and comparison. (I use the "Make the common case fast" principle here, as it can be slower in corner cases) Not sure if it is noticeable though..

**Comment by og76** [comment]
still same fault ?! wtf!
I mean after the change in the guide exceptions
and I looked at it in comparison with the old code lines var, in master ..
(same file as above, master vs v1.6 , X guide  being 0)

I guess I have to check it all, but I assume all the xyz craziness in the dicts is just copied ..


as about the second change, I don't know, seams logical, but not sure
I wanna check the first before any other change ..

**Comment by JacquesLucke** [comment]
What really ?! :o
Your file seemed to work with this change here..

Yes the dicts should be correct. They are copied and I think I tested all of the entries individually.

**Comment by og76** [comment]
same file, same settings, 1.5 / 1.6, (there is a rot on x and it affects/not the scale too)
https://drive.google.com/file/d/0BzzAoBwXO8dsdDNyaURLSDFLaTA/view?usp=sharing

1.5 master
![dir1 5](https://cloud.githubusercontent.com/assets/11709974/14225503/9b4a49dc-f8cd-11e5-81d5-ba78599a16ad.PNG)

1.6
![dir1 6](https://cloud.githubusercontent.com/assets/11709974/14225504/a399cf68-f8cd-11e5-8cd6-391972273999.PNG)

have you tested also? this exct file

**Comment by JacquesLucke** [comment]
Works here.
Looks like you didn't download my latest changes. At least it isn't visible in the code on the image. (maybe you need to pull v1_6 again)
Maybe git got confused because I had some trouble renaming v1_5_1 to v1_6.

**Comment by og76** [comment]
ok, it's good now and I see no reason for any other issue.
(it was git or blender keeping old stuff, restarted all and got ok)
now back to pivot ...
