### ISSUE TITLE
Speedup Compose Matrix node

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#446]

**Comment by JacquesLucke** [comment]
This commit speeds up the compose matrix function by about 40%.
So on my laptop the creation of 50,000 matrices takes only 110 ms instead of 188 ms.

**Comment by JacquesLucke** [comment]
Does someone see room for more improvements without going into C code?

**Comment by JacquesLucke** [comment]
def composeMatrix(location, rotation, scale):
        # Scale
        scaleMatrix = Matrix.Identity(3)
        scaleMatrix[0][0] = scale[0]
        scaleMatrix[1][1] = scale[1]
        scaleMatrix[2][2] = scale[2]
        # Rotation
        matrix = (rotation.to_matrix() * scaleMatrix).to_4x4()
        # Translation
        matrix[0][3] = location[0]
        matrix[1][3] = location[1]
        matrix[2][3] = location[2]

        return matrix

**Comment by og76** [comment]
have you tried directly 4x4 ?, just to compare, who knows, like:
(actually only rot part is really different, the rest is style :) ..)

``` py
# 4x4 variant
def composeMatrix(location, rotation, scale):
    matrix =  Matrix()
    
    # Scale
    matrix[0][0], matrix[1][1], matrix[2][2] = scale

    # Rotation
    matrix = rotation.to_matrix().to_4x4() * matrix

    # Translation
    matrix.col[3].xyz = location

    return matrix
```
 
mostly the same, just make 4x4 only for rot, who knows ..

**Comment by JacquesLucke** [comment]
have you tested if it is faster?
I wanted that the matrix multiplication on 3x3 matrices instead of 4x4

**Comment by og76** [comment]
not tested, not really sure how, just an idea

4x4 seams more off-road :D

**Comment by JacquesLucke** [comment]
Ok I think I'll close this now :)
40% speedup is good enouph for today hehe

**Comment by og76** [comment]
aha, so you're more of a SUV guy than real 4x4  ...
