### ISSUE TITLE
Slice List node options. Start/End Index or Start Index/Length

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#450]

**Comment by LeonCheung** [comment]
True. Length is more user-friendly. ;)

**Comment by og76** [comment]
guess the min value only covers for ui 
![slice step](https://cloud.githubusercontent.com/assets/11709974/14155583/01d8c8a4-f6cb-11e5-8f57-1f0826487539.PNG)

**Comment by JacquesLucke** [comment]
Oh thx for the info.
