### ISSUE TITLE
Feature Request: Remove from list node

### ISSUE THREAD

**Issue by Norrolith** [JacquesLucke/animation_nodes#453]
I have a node tree that rays casts into the scene to fill a list of vector at which I will place objects.
I have the hit attribute, but if it doesn't hit I have no way of saying don't include that in the list, and so I have a bunch of objects hanging out at 0,0,0
The node might be organized like this.

Inputs
list socket(The input list)
integer socket(The position in the list)
boolean socket(hidden, an override to allow interfacing with boolean logic)
Output
list socket.(The trimmed list)
list socket(hidden, the entries removed from the list)

this is one way to solve the problem that might also be more generally useful.
One could build a node tree say that compares two lists, or one list twice with an offset index, and based on the result of those tests, remove unwanted entries, or separate them out for a different process.

I hope I have made my case well.

**Comment by og76** [comment]
you are looking for this, in loop output generator, condition
(lots of nodes have hidden default socks)
![condition](https://cloud.githubusercontent.com/assets/11709974/14101019/3ff5bf0c-f59a-11e5-8062-fe187a4e9463.PNG)

**Comment by og76** [comment]
sorry, also there is a remove from list node, but somehow it got out of the menu
use the search in the menu or Ctrl+A

**Comment by Norrolith** [comment]
Ah... I should have known. I didn't think to check the loop output, but that is a good place for that.

**Comment by og76** [comment]
ok, is this still on?
remove element from list does exist as a node, just was not in the menu.
