### ISSUE TITLE
Implement a way to do IF statements

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#454]

**Comment by clankill3r** [comment]
Maybe this helps:

http://softimage.wiki.softimage.com/xsidocs/ICE_trees_ControllingExecutioninICETrees.htm

**Comment by JacquesLucke** [comment]
Thanks.

My current idea is to implement a "Condition/Enabled" socket for the Invoke Subprogram node. When it is True everything works as normal but when it is False the node will be skipped (the outputs will be some default values or the unprocessed input...)

**Comment by KoFish** [comment]
Too me it seems better to implement it as only filters on lists. Having "undefined" or "null" values that are valid besides an empty list usually turns out really badly. I would imagine even more so in a node based language.

**Comment by JacquesLucke** [comment]
We would not have "undefined" values (which would be bad indeed). Instead there would just be some default values. Like an empty list for example.

And you are right, Animation Nodes is pretty strongly typed. Null values are only allows for some specific data types like Object. A number or a list must never be None.
