### ISSUE TITLE
Get List Element Node: Make Clamp Index turned on by default

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#456]
I believe this is the expected / savest behavior for most cases?

**Comment by JacquesLucke** [comment]
Why do you think it is a savor behavior?

I think it should stay turned off. eg if you have an object list with 5 objects und you use the Get List Element node to get the object at index 10. I would expect to get None as result instead of the last object...

**Comment by LeonCheung** [comment]
Hmm, OK. Maybe it's just about those of my own.  :)
