### ISSUE TITLE
Animation Nodes 1.6 Release Notes

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#459]
http://animation-nodes-manual.readthedocs.org/en/latest/release_notes/v1_6.html

**Comment by JacquesLucke** [comment]
I plan to release within the next two weeks.
Therefor I'm currently writing the release notes.
If there is something that you definitly want to have in v1.6, please post it here.

After that release I want to spend more time exploring cython and how to integrate it into AN.

**Comment by YorsLosilla** [comment]
Well the only thing that I missed is some sort of way to bake particles. Something similar to what the bTrace Addon does.

**Comment by JacquesLucke** [comment]
I just checked out this btrace addon and I agree. It would open many possibilities. Unfortunally this won't be part of the v1.6 release because its a larger project when I want to do it right (and yes, I want to do it right :D)

**Comment by YorsLosilla** [comment]
That´s really great news. Looking forward to this enhancement. I have some ideas to put some cool artwork with these features.

**Comment by og76** [comment]
Added a release description to pivot, but for some reason pics seam formatted in a weird way after this edit, with a strip on the left. ??

Also on release the slice node is there twice. ??

-

besides the geometry pulls and the necessary menu modifications (later) I would like to see 2 more things in this release:

1. convert (auto insert) vector / euler should present 
 - vector > direction to rotation > euler
 - euler > rotation to direction > vector
(the direct triplet conversion does not make any sense, was there for using vector math while not having eul math I guess)

2. the NLA strip socket / data type (can make a new pull for that)
it would really help to further explore respective nodes without generics

**Comment by JacquesLucke** [comment]
Will check the release notes later..

Yes, we can have both other things. And yes you can do a pull request for the NLAStrip socket.

**Comment by JacquesLucke** [comment]
Can you maybe make a more compact example of the pivot node? (so that the nodes are larger, it's hard to read atm)

**Comment by JacquesLucke** [comment]
@og76 good that you started to write some documenation. however I think not all this information should be in the release notes because it is much more text than all the other things. I'd prefer if you keep it shorter and maybe show all Intersection nodes in one screenshot and one simple example below. We don't need an example for each of these nodes in the release notes as they all work very similiar.
