### ISSUE TITLE
Add "N Char" option to Split Text node

### ISSUE THREAD

**Issue by GottfriedHofmann** [JacquesLucke/animation_nodes#461]
The Split Text node uses re.split() for RegExp splitting. A special case where re.split() is not suitable is when you want to split after n characters, because "keep delimiters" will create newlines between each split.

A new option "after n characters" would solve this corner case.

**Comment by JacquesLucke** [comment]
![split_text](https://cloud.githubusercontent.com/assets/5881326/14189930/3c193998-f790-11e5-90df-af0ad3b58c16.png)
