### ISSUE TITLE
[Idea] Divider in Subprogram nodes

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#463]
Currently I used a trick like below:

![divider](https://cloud.githubusercontent.com/assets/494788/14195547/1730fb04-f7ed-11e5-9957-a50c02eb2a10.png)

Maybe a kinda divider can be useful when trying to divide the panel into sections for better organization. Just a rough idea. FYI

**Comment by JacquesLucke** [comment]
Hmm, thinking about it now. It shouldn't be hard to do a hacky implementation for this but I don't like it so far.. I see the need for this if you have so many sockets but I'd prefer to wait with this until I get an idea for a better way to solve this issue.

Currently you have to do it the way you did it, should work too I think :) My hacky implementation wouldn't look much better.

**Comment by LeonCheung** [comment]
Yes, it looks not bad,  I like it too, except the unhidable and confusing Input soclket. :)

**Comment by JacquesLucke** [comment]
yes, unfortunally I can't hide the complete sockets in Blender

**Comment by og76** [comment]
you can have an extra space/height for some sockets, like the loop new iterator/ new parameter have
not sure how to present that in the ui for the user to add as a spacer 

or a blanc (transparent socket and --- name) that does not allow connection (like in the script)
it would still show the soc circle ..

not that I like workarounds like these, but just saying :)

**Comment by JacquesLucke** [comment]
Yes I actually I tested this. I made a simple ui separator socket but there are a few more problems... I'll leave this out. I'm sure we will have a good solution for this later, it doesn't have much priority for me atm..

**Comment by LeonCheung** [comment]
True, like reroute  or frame, it's just a helper thing for usability, not a functional one. I also agree to set the priority as Low before any better solutions flashing. :)
