### ISSUE TITLE
[request] Boolean node

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#470]
It would be really nice if there was a node for Boolean operations (union, intersect, difference).
And if that node could also be used to test if 2 meshes intersect.

**Comment by og76** [comment]
a direct **boolean op in py** would be very slow, not impossible, but really slower than modifier etc
(as of today there is no boolean or bmesh boolean exposed to py scripts to use)

- I've been exploring some variants of 2d and 3d boolean, but still have a (long?) way to go. we'll see..

- chenckin if 2 intersect. 
 You can use a raycast for each edge to tell if edges do touch another mesh. It's no easy setup, but it should work.


Also, I'm exploring a decent way to use/implement a build in function of **bvh tree (overlap)** that checks if the poly of 2 meshes touch. But it needs to be extended as the exceptions (coplanar, colinear edge, point etc) are not handled well. 

I'll post examples if I come up with a decent solution.

**Comment by YorsLosilla** [comment]
Maybe modifiers nodes could be the next big thing in AN.



-----Mensaje original-----
De: "og76" <notifications@github.com>
Enviado: ‎03/‎04/‎2016 21:01
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
Asunto: Re: [JacquesLucke/animation_nodes] [request] Boolean node (#470)

a direct boolean op in py would be very slow, not impossible, but really slower than modifier etc
(as of today there is no boolean or bmesh boolean exposed to py scripts to use)
I've been exploring some variants of 2d and 3d boolean, but still have a (long?) way to go. we'll see..
chenckin if 2 intersect. 
You can use a raycast for each edge to tell if edges do touch another mesh. It's no easy setup, but it should work.
Also, I'm exploring a decent way to use/implement a build in function of bvh tree (overlap) that checks if the poly of 2 meshes touch. But it needs to be extended as the exceptions (coplanar, colinear edge, point etc) are not handled well. 
I'll post examples if I come up with a decent solution.

**Comment by JacquesLucke** [comment]
Will close this for now because it is not in the scope of AN atm.
