### ISSUE TITLE
Automatic Socket Insertion in List Nodes

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#472]
I just talked to Lukas Tönne and he showed me a new api function with which I might be able to implement this functionality into AN:
https://www.youtube.com/watch?v=eAgVgs7oMlE

Do you think we should have it or not?

**Comment by og76** [comment]
seen that and played a bit once with that branch
The only diff I see now is not having to delete some socks if u wanna shorten the list.

But I'm not sure if this should be the default behavior. Sometimes a field is not connected intentionally. 

Also, this should only go along with the ability to switch inputs by dragging one into another socket. 
A behavior that now(v1.5?) is lost (was it @keepNode vs keepLinks?) and I used a lot on matrix list for ex to switch order
(and no, the up/down arrows are not that)

Btw, math nodes would benefit a lot of this too. ok off topic but related/conditional

**Comment by JacquesLucke** [comment]
yes I agree, we shouldn't delete sockets automatically. It's more about the creation of new sockets when you connect to a socket in a list node that already has a link.

About keepNodeLinks vs keepNodeState:
keepNodeState is the newer decorator. It does the same as keepNodeLinks but also a bit more. Most importantly it saves the socket value, hide status and isUsed properties for each socket before the function starts and sets these values back onto the new sockets.

The switch link behavior should also be possible now in some nodes but that will be another topic

**Comment by og76** [comment]
but we do have creation of new sock where needed, lists, subprograms etc.
