### ISSUE TITLE
Node API change

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#473]
Lukas Tönne said that he will remove the identifier property of sockets eventually (most likely in Blender 2.8). The problem is that we use this property a lot to store the variable names of sockets.
Also I guess that the ``self.inputs.new(type, name, identifier)`` function will be ``self.inputs.new(type, name)`` then.

I will only talk about inputs now but everything applies to ouputs too.

I think we should change the node api so that we don't call the ``inputs.new(...)`` anymore inside the node code. Instead we make an abstraction in the AnimationNode base class. That means I'll implement a ``AnimationNode.newInput(dataType, name, identifier)`` function that will be used by all other code.

Benefits:
- we can write the node code without depending on the ``self.inputs.new`` function.
- we can create sockets from a given data type. So we can use "Object" instead of "an_ObjectSocket". (in fact we can also use both ways but using "Object" is cleaner)
- we can prepare for the time when the identifier property does not exist anymore. When it is removed in Blender we can simply replace it with our own property (not sure if it will break all files or not... but it will be Blender 2.8 so most files may be broken anyway).
- the current way to create sockets can coexist with the new way as long as we didn't change all node files.
- Maybe we can have more parameters in the ``newInput`` function later to simplify socket creation even more.

This is a rather big change and we will need to modify a lot of files (I guess I can automate some stuff but it's still a lot of work..), but I still think we should do it.

**Comment by og76** [comment]
I guess this will impact all nodes + sockets but also:
- the connections/allowed data automated connections etc
- all the isLinked parts
- probably all the nodes in terms of generateSockets() et co

automation will still have to be checked manually, as it is a black box..
(but by doing so, some consistency in the naming etc can be imposed (ex not naming as function ..)
and also it's a good time to rethink (if any) issues like copy etc)

how do you propose to do this?
deadline /target? ver?
starting with an overhaul of sockets .. folder ?

**Comment by JacquesLucke** [comment]
Well this proposed api change should really only target the socket creation parts. Everything else should stay the same. This is why we have abstractions.

this also should not change the sockets yet.

What do you mean with this?:
> some consistency in the naming etc can be imposed (ex not naming as function ..)

I'll just start with this when I have time. As I said, I don't have to change everything at once. Also this api change does not break any files!

I'll start by making the functions in the base_types/node.py file and then change the nodes folder by folder.

This should all be very easy, it just takes some time.

**Comment by og76** [comment]
If the node sockets don't really change, as in breaking old, then I guess is not such a major impact
I'm not sure I get how to 's on this so ... in terms of any help, I don't know.

**Comment by JacquesLucke** [comment]
You don't need to help with that. I mainly made this issue so that I don't forget it and that you'll notice that something will change.

**Comment by JacquesLucke** [comment]
I replaced the old socket creation code with the new function now (everywhere!)
Now some cleanup can happen to make the nodes nicer by using the new functionality :)

**Comment by JacquesLucke** [comment]
the new api is used everywhere now (at least I think so...)
