### ISSUE TITLE
Improve TAB feature to jump between subprograms

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#480]

**Comment by JacquesLucke** [comment]
My proposed behavior is this:

If the active node is a:
- invoke subprogram node: jump to the subprogram and select all nodes inside
- subprogram node (loop input, group in/out, script):
    - the subprogram is called once: jump to the invoke node (also switch tree if necessary)
    - the subprogram is called multiple times:
        - it is only called once in the active tree: jump to that invoke node
        - it is called multiple times in the active tree: zoom out and select all corresponding Invoke nodes
- a node in a subprogram is selected: zoom out so that you can see the whole subprogram network - select the subprogram node (eg loop input) so that you can jump to the invoke node by hitting tab twice
- a node in a main network is selected: zoom out so that you can see the whole main network + select all nodes inside that network

what do you think?

**Comment by og76** [comment]
good

1. what will the be priority for an invoke inside another subprogram tree? guess tab into it's own subprogram like any invoke 
2. a node in subprogram/main network should work also for more than 1 node
 (I f I select 2 nodes in 2 networks, should perform on both)
3. if I select 1 invoke and another node? does work like invoke case or like nodes in a network case?
 guess like network
4.  Select 2 invokes? what happens? should pop a msg to say "this is gone too far !" and then close Blender.

**Comment by JacquesLucke** [comment]
Yes, priority is to jump to the subprogram.
The operation only works on the active node. I don't care about the other selected nodes here :)
(To make it easier for me :D)

**Comment by og76** [comment]
you remember that when deselect all, it still considered the last active, so the extra not selected needed. 
guess it's still covered, just a reminder 

+ a situation where you get an ugly message and blender closes would still be a very .. human touch

**Comment by JacquesLucke** [comment]
yes, I can check if the active node is also selected but I don't really care. Because if you unselect everything and hit tab it's your own fault haha

**Comment by og76** [comment]
come on, that was on the pie menu long time ago and I see is gone there too
it's kinda silly to have nothing selected and have pie allowing you to do stuff

plus the nothing selected should be a case for another pie / tab case, like
- tab to cycle nodetrees, or maybe something else
- pie to present current subprograms (including new ..)

or at least an ugly message :D

**Comment by JacquesLucke** [comment]
hm I think tab shouldn't be used to cycle nodetrees as this is a completely different operation (imo). It's something we can have on another key but it's not soo important I think.
there aren't many people with multiple AN nodetrees and if you have more than one, you can always use the overview panel to switch between them

**Comment by og76** [comment]
ok. 
still, tab and pie acting on nothing selected on the ghost of last active, is silly... 
maybe not a big deal now, but after u make the whole tab sys, may wanna look into it too

**Comment by JacquesLucke** [comment]
yes :)
I'll just disable the tab feature if nothing is selected

**Comment by JacquesLucke** [comment]
All the cases I described above should work now, can someone test?
