### ISSUE TITLE
[Suggestion] Remove change subprogram button

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#482]
I suggest to remove the big change subprogram button:

![changesub](https://cloud.githubusercontent.com/assets/738650/14308019/9222ba7a-fbd3-11e5-8444-25ae0bb3fdc4.PNG)

Cause we can invoke here:

![subprogram](https://cloud.githubusercontent.com/assets/738650/14308100/220cc644-fbd4-11e5-87e0-e352d9b3c40b.png)

And it makes the tree look much cleaner and nicer. Space should be used conservative.
just my 2 cent

**Comment by LeonCheung** [comment]
Though we have more than one ways to invoke a subprogram, I still think it is good to keep it as it is, for stronger visualization, I mean it can benefit like a "landmark", the big button and the name makes it much easier to identify among the node forest, my cent 1.

Also, you can create / switch to another subprogram by one or two dlicks, without having to create a new one from the ground, my cent 2.  :)

**Comment by JacquesLucke** [comment]
Hm, I agree with Leon. I think the button and it shows which subprogram is called there.
I could however make the button and the free space a bit smaller if it looks better; I have to test that.
It would also be possible to have a global option to turn the visibility of this button on or of, but I think that isn't a good idea because it'll confuse others a lot when the button is sometimes there and sometimes not.

**Comment by clankill3r** [comment]
Ok, here a better proposal.
Just like the other node systems in blender, we could have a few icons in the top right corner:

![subprogram3](https://cloud.githubusercontent.com/assets/738650/14368025/7caf277a-fd1b-11e5-981e-f9c089e47105.PNG)

![subprogram2](https://cloud.githubusercontent.com/assets/738650/14368036/88a7b074-fd1b-11e5-986b-ad31c56e2826.PNG)

Instead of using the name "Invoke Subprogram" we can use the name of whatever the name is of the invoked subprogram.

**Comment by JacquesLucke** [comment]
How did you get this icon there?
I'm still not totally convinced but I haven't tried yet how it looks... We'll see.

**Comment by clankill3r** [comment]
The icon is from the shader node tree. I didn't do it myself.
I would like to program it for testing, also to gain some insight.

**Comment by og76** [comment]
I have not found a way to get that into script nodes. Seams hard coded for shaders/groups
So if you do, that would be something ..

**Comment by clankill3r** [comment]
Yeah I saw your post on stackexchange :)
There is a bugfix for it but It hasn't yet been reviewed.
https://developer.blender.org/D1578

So not much to do for now.
