### ISSUE TITLE
AN Documentation

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#484]
I would like to work on documentation for AN.
(Not that I like working on that but good documentation is important).

What I also would like is to create really basic examples, inspired by:
https://processing.org/examples/

More later. (sry for this empty start...)

**Comment by JacquesLucke** [comment]
To contribute to the documentation you can make a pull request for the corresponding repository.
https://github.com/JacquesLucke/animation_nodes_manual

For the examples: yes you can do those, question is where and how to publish them. Should we only publish images of the node trees with a small description or the .blend files. I prefer the first option.
And should we put them in the documentation? In an extra category, or in the node description pages to show a specific node in context?

For more complex examples I have an open google drive folder here: https://drive.google.com/folderview?id=0B7m1nartBYvrcTBmcDJ3QWk0YlE&usp=sharing
It is linked in the first post of the Animation Nodes thread.

**Comment by clankill3r** [comment]
I think the node description pages should show a minimal to make the node clear.
If you have this for example:
http://animation-nodes-manual.readthedocs.org/en/latest/user_guide/nodes/number/integer_list.html
I think that example is way to specific (and there is to much space around the nodes).

I also prefer to show images with a small description. Its good practise for a user to recreate something instead of downloading it.

**Comment by JacquesLucke** [comment]
yes, i agree. Just make a pull request for the manual repo. it is very very likely that I'll merge your changes there immediatly :D
