### ISSUE TITLE
Change cycles with expresion

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#485]
Assuming there is a material called Material with a Emission node.
Why is this not a valid expresion with the expresion node:

```bpy.data.materials['Material'].node_tree.nodes['Emission'].inputs['Strength'].default_value = Strength```

Since this is a valid python console input:

```bpy.data.materials['Material'].node_tree.nodes['Emission'].inputs['Strength'].default_value = 10```

**Comment by LeonCheung** [comment]
It does work. I wonder if the data type you set is incorrect. Not float?

**Comment by JacquesLucke** [comment]
Maybe the problem here is that you use Strength as variable name and it is the name of the socket...
The function that processes the expression is very simple..

For the same functionality you could also use the Cycles Material Output node.

**Comment by JacquesLucke** [comment]
Hmm, just tested it myself, seems to work as expected. A screenshot would be helpful.

**Comment by clankill3r** [comment]
I got it. I only don't understand why.
When I have the 3d view in solid view it updates, when I have it in rendered it does not update.

**Comment by JacquesLucke** [comment]
ah, yes that is intentionally.
"always"-auto execution is disabled during preview rendering because it restarts the rendering all the time. You can activate the other auto execution settings instead.
