### ISSUE TITLE
Enable Dynamic Labels feature for more nodes

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#486]
I think it should be like so. Yes?

**Comment by og76** [comment]
right.
I'll look into it right now, as I have also looked into 2 other bool stuff ;)

**Comment by JacquesLucke** [comment]
Yes, I guess dynamic labels should be used in quite a few more nodes, maybe you can make a list?

**Comment by og76** [comment]
ok, here's the booleans for now

#487 
![bool labels](https://cloud.githubusercontent.com/assets/11709974/14379142/4711f32a-fd81-11e5-9f37-df35e37ee428.PNG)

compare: dyna labes, also as numeric for float/int
logic: dyna labels

compare and switch also have now the_ advanced type chooser_

**Comment by og76** [comment]
ok, this is in 1.6
any other label nodes?

**Comment by og76** [comment]
#489 here for angle convert and round number

**Comment by og76** [comment]
I also looked into mix nodes, to show the factor, but they have already dyna labels
I dropped it  so we should not complicate it further

**Comment by og76** [comment]
some more on #488 (also label)

**Comment by LeonCheung** [comment]
A few more:
- List Boolean Operations
- Set List Element
- Delay Time
- Repeat Time

BTW, I wonder if the dynamic label should have dynamic value display? I'm sure you get my point, don't you?  :)  Is there performance concern involved or so? Just curious.

**Comment by og76** [comment]
you mean like a debug? hm, would be like having debugs all over the place

**Comment by LeonCheung** [comment]
Haha, thought so. It sounds... crazy... ok forget it.
