### ISSUE TITLE
[request] atan2 node

### ISSUE THREAD

**Issue by robert-trirop** [JacquesLucke/animation_nodes#488]
Adding atan2(x,y) to the math nodes would make angle calculations more efficient and much more convenient.

**Comment by og76** [comment]
there should be more to math node
specifically atan2 is loved for angle (2d world) like result, but others too
we'll see

though we have vector angle and there will be another 2d vector signed angle (where angle_signed() is used..)

**Comment by clankill3r** [comment]
Meanwhile you can use an expression
![atan2](https://cloud.githubusercontent.com/assets/738650/14382795/b5c4d49a-fd90-11e5-86b5-54d9faccf9e8.PNG)

**Comment by robert-trirop** [comment]
Thank you for the advise!

**Comment by og76** [comment]
I made #490 for this and seams not to break the prev files
atan2, hypotenuse, 
(+ numeric dyna labels on step and log)

![math labels2](https://cloud.githubusercontent.com/assets/11709974/14383004/be1fa6ce-fd9a-11e5-833b-48acae43c9c7.PNG)


issues

1. I just wonder if atan2 B/A should not be A/B?
 This is more of a y/x idea, to refer to world X,  but not necessarily logical outside context 

2. Should I include in the math this  ?
 https://github.com/og76/animation_nodes/blob/working-tests/nodes/number/constant.py
 Or should I keep it for a separate node?

It's just a convenience, we can already type pi or e in a field, but it's more for the sake of visual noodle clarity

**Comment by clankill3r** [comment]
1.
I would not name it 'Arctangent B/A', no matter what programming language I used, it is always called atan2. And instead of naming it A and B name it X and Y.

Also, I really don't understand your Hypotenuse node.

**Comment by og76** [comment]
https://docs.python.org/3.5/library/math.html#trigonometric-functions see hypo 

atan2(a, b) could be, 
as about xy, all math refers to xy, but I kept the ab as in the node

**Comment by og76** [comment]
is this better?
the trick is the menu has these long names arctangent, arccosine etc 
+I need to say that is a/b not b/a, as the atan2(a, b) shows it, but the long name should too
![atan2 1](https://cloud.githubusercontent.com/assets/11709974/14385588/f4cafa7a-fda9-11e5-815c-84005baa2f20.PNG)

**Comment by robert-trirop** [comment]
Actually it is B/A oder (A,B)

**Comment by og76** [comment]
I made it atan2(a, b) This way it is expected, like A - B,   A / B etc.
(SO I don't need the A/b in the name here really)
So the name in the menu remains Arctangent 2 . and in the label as in the pic above.
.

First time I was thinkin of the inversion specific to the xy angle to X case, but that is not expected, and needs further explanation

[To get the angle vs Xworld you'll have to have  y to A and x to b (as in the expression u used)]

**Comment by clankill3r** [comment]
I think it is doomed to fail if you use A/B over Y/X.

**Comment by robert-trirop** [comment]
Just use (X,Y) or (A,B)
