### ISSUE TITLE
Dragging toggle feature doesn't work well?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#49]
While in other area of Blender UI, we can toggle multiple things by dragging over adjacent items (such as toggling the visibility of many objects in Outliner), but the experience seems doesn't work farely well with nodes like "Transforms Output" or "Copy Transforms", which are with many toggles, that are ususally needed to be toggled by the internal quick toggling way.

EDIT:
Toggling in N panel would get better a bit, but still failed sometimes, occasionally.

**Comment by LeonCheung** [comment]
I'm not sure if someone did something on this, it appears no problem (so far) to me with the latest build. Jacques could you try to confirm it again?

**Comment by JacquesLucke** [comment]
ok thanks. I also have problems to reproduce it with my current build..

**Comment by LeonCheung** [comment]
Campbell fixed it in the latest commit. (see the report link above).  Let's try it again?

**Comment by LeonCheung** [comment]
https://developer.blender.org/rBbfa7586ba33bd090af13b8671326cdffd4c7592b

**Comment by LeonCheung** [comment]
Thanks to Campbell, I think it is finally fixed! :smile:

**Comment by JacquesLucke** [comment]
Ok. thanks for your (and Campbells of course) effort
