### ISSUE TITLE
float min and max value bugged

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#493]
Not talking about float precision here.

The max using nodes is 100000.0 and the min is -100000.0

![float_bug](https://cloud.githubusercontent.com/assets/738650/14396198/7c0ecf08-fdd6-11e5-9974-919e44d2bcd4.PNG)

Where I expect a maximum value of 3.40282347E+38 and a minimum value of -3.40282347E+38.

**Comment by JacquesLucke** [comment]
yes, you're right. Not sure why this is.. I'll check

**Comment by JacquesLucke** [comment]
looks like Blender limits us here. You can actuall type in larger numbers, but the precision gets very low for larger numbers.
