### ISSUE TITLE
[suggestion] debug node

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#494]
If we print a list now:

![debug_node](https://cloud.githubusercontent.com/assets/738650/14396645/0eb7454a-fdd9-11e5-89e4-2ef325dfc35a.PNG)

It would be nice if you can make the node vetical as well, it makes more sense for a list.

**Comment by JacquesLucke** [comment]
the debug node just calls the str function on the object that comes in without further modifications.
If you want more control you'll need to use the debug drawer.

I'm justing think if we could put all the other options in the debug drawer node into the advanced settings panel, I rarely use them.

**Comment by og76** [comment]
+1 for the options away from the debug drawer
(I was lookin for ways to make them smaller, or one liner, but advanced would really be enough)

as for this, we still need a debug that shows unformatted things, as is
