### ISSUE TITLE
Loop output nodes

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#495]
One of my goals is to make AN strong for data visualisation.
I freelance a lot for catalogtree (www.catalogtree.net check it out! (click on years in index)).

Tonight I thought how data from a csv / tsv could be converted to something useable.
I came up with this so far:

![csv_to_arrays](https://cloud.githubusercontent.com/assets/738650/14400071/95db5894-fdf3-11e5-9d33-4d4a5cb9025f.PNG)

I'm pretty happy with that. Also cause a data layout like that is quite fast (SOA vs AOS).

What I wondered, is it technical required to have each output node a separete node?
To use less space I collapsed them all: 
![all_collapsed](https://cloud.githubusercontent.com/assets/738650/14400151/6373b260-fdf4-11e5-8ef1-3722f1c268c9.PNG)

But expanded, it takes up quite a lot.
![all_expanded](https://cloud.githubusercontent.com/assets/738650/14400156/67da6b96-fdf4-11e5-8512-1a8719807213.PNG)

That is npt the only problem. I think one thing that is important that it is clear what goes in and what goes out. Now with separate nodes it can be very verbose what goes out (unless you place them all together).

Another nasty thing is that it's not possible to change the order:
![order](https://cloud.githubusercontent.com/assets/738650/14400105/03bb9a9a-fdf4-11e5-8bad-7d41ea3bb358.PNG)

**Comment by JacquesLucke** [comment]
You can change the order of the generator outputs now (in the advanced settings of the Loop Input Node)
