### ISSUE TITLE
[WIP] processing data

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#496]
AS mentioned in the other 'topic', one of my goals is to visualise data.
Here I will post process, this is also for myself.

![csv_to_arrays](https://cloud.githubusercontent.com/assets/738650/14400490/17aff348-fdf9-11e5-81e1-4070f2b39f25.PNG)

**Comment by clankill3r** [comment]
Using Generic lists to create structures:

![generic_list](https://cloud.githubusercontent.com/assets/738650/14400504/33b46560-fdf9-11e5-8cfb-182d65de4056.PNG)

@JacquesLucke it is really really really cool that arrays in arrays is possible. This was always a shortcoming of ICE!

**Comment by clankill3r** [comment]
Continueing on previous: Getting an array out of the array of arrays:

![get_data_element](https://cloud.githubusercontent.com/assets/738650/14400680/5720626c-fdfc-11e5-8ab5-e8eea7bd63d3.PNG)

**Comment by clankill3r** [comment]
I still think the way with all the different arrays is better. Its just that it so much fun to continue with the other one.

Get Data:
![get data](https://cloud.githubusercontent.com/assets/738650/14400767/fbdff7b2-fdfd-11e5-9f6b-8c2512724ffc.PNG)

**Comment by clankill3r** [comment]
Get Data Element Data

![get_data_element_data](https://cloud.githubusercontent.com/assets/738650/14400840/4a440424-fdff-11e5-9cf1-4a121d7c1413.PNG)

**Comment by clankill3r** [comment]
Back to SOA

![root](https://cloud.githubusercontent.com/assets/738650/14403047/796b48c2-fe48-11e5-849d-3a761153654a.PNG)

![get_data](https://cloud.githubusercontent.com/assets/738650/14403048/846a2d6a-fe48-11e5-8cab-948f74e5c5c3.PNG)

![get_data_single](https://cloud.githubusercontent.com/assets/738650/14403049/88cac946-fe48-11e5-9461-8dae34740429.PNG)

**Comment by clankill3r** [comment]
Pretty happy now. It looks clean.
It doesn't convert anymore which probably gains a lot of speed on big data sets.
I made a node tree to load the data that doesn't auto execute. Now time to find some actual data to work with and work on a node to read a text file.

![get_data2](https://cloud.githubusercontent.com/assets/738650/14403171/bba1651e-fe4d-11e5-9e6c-917ffe28e790.PNG)

![get_data_element2](https://cloud.githubusercontent.com/assets/738650/14403174/bf1f3e46-fe4d-11e5-8e1f-10ff8fdc5bb0.PNG)

![root2](https://cloud.githubusercontent.com/assets/738650/14403175/c6e5b8e4-fe4d-11e5-81f4-e64647071984.PNG)

**Comment by JacquesLucke** [comment]
You can open the text file in blenders text editor and use the Text Block Reader node

**Comment by clankill3r** [comment]
Cool. I dont know all the nodes we have that good cause I use ctrl + a all the time :)

**Comment by og76** [comment]
A very interesting pursuit and exploration.
fwiw, just mentioning, I used this for infographics, but really without using a single generic or expression.

Basically took data over the net and saved as csv (to have my own separators ; )
Then did exactly the very first post you have (but reading from txt block). 
Converting to names and floats or vectors was enough.
Then used in whatever way, having "paralel lists" like that or by "unpacking" only when needed.

_What I'm saying is I never needed to repack to a mixed data (generic) list, as I have that data as a string (could split or extract whatever at any point)_

![infog1](https://cloud.githubusercontent.com/assets/11709974/14422548/0bdc6cb6-ffe0-11e5-8a48-3222efbd6a1b.PNG)


what you see here is using the data immediately in the loop, after converting it to name/number/vector
if u like it cleaner, u can generate the string/float/vector lists first, but then a simple loop can take them in parallel (zip really) and just use them  ..

ps
not my point to stop your journey, just hope is giving you more ideas

**Comment by clankill3r** [comment]
@og76 That image is sadly to small to read.

**Comment by og76** [comment]
oh, I was just making a point
is just using txt numbers to locate text (names) and scale / color saturation  for cubes
(the grid is separate)

**Comment by clankill3r** [comment]
It's not really a problem, I was just interested in what you did there :)

**Comment by og76** [comment]
![basic_infographic_1](https://cloud.githubusercontent.com/assets/11709974/14580918/1e8f0e6c-03e7-11e6-8c9e-7e9dcd9e67cf.png)
