### ISSUE TITLE
[Bug] AttributeError: 'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#497]
I think (hope) that this is a bug in AN.
I think the sketch can explain it better then I could here, I think it's pretty straight forward.

[read_data_04.zip](https://github.com/JacquesLucke/animation_nodes/files/211057/read_data_04.zip)

**Comment by JacquesLucke** [comment]
Looks like you tried to do an invalid conversion before the one of the get list element nodes. If you are using the v1.6 branch you can enable "Monitor Execution" in the developer panel to find the exact node that raises the exception.

I have plans on how to avoid errors like this one in the future but there is still a lot of other things to do...

**Comment by clankill3r** [comment]
Cool, I switch to 1.6 branch. I fixed the problem anyway. I only don't know how.
