### ISSUE TITLE
[BUG] Not possible to delete a node tree

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#499]
Maybe I do it wrong but no matter what I try, I can't delete a node tree.

**Comment by JacquesLucke** [comment]
hit space bar and type "Remove Animation Node Tree"

**Comment by clankill3r** [comment]
This remove's all the nodetrees. I would like to remove one specific node tree.

**Comment by JacquesLucke** [comment]
no, this only removes the active node tree, at least it should (I just tested it)

**Comment by clankill3r** [comment]
your right. It looked like it didn't cause it doesn't switch to the next tree on deletion. Therefor the Animation Nodes pannel dissapears making it look like all trees are deleted.
If you want I can make it so that it goes to the previous used node tree.

**Comment by JacquesLucke** [comment]
yes, that would be nice
