### ISSUE TITLE
possible bug in expression node or debug loop node

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#500]
With this simple expresion I have a varying amount of spaces in front for single elements:

![bug_01](https://cloud.githubusercontent.com/assets/738650/14404506/4d7bb28a-fe78-11e5-83dd-ae6b792fe272.PNG)

If I change the expresion to just return the input then all is fine: 

![bug_02](https://cloud.githubusercontent.com/assets/738650/14404507/5203e926-fe78-11e5-9876-e575ef77d7f5.PNG)

**Comment by JacquesLucke** [comment]
Not sure why this happens, can you share your .blend file?

**Comment by clankill3r** [comment]
[venice_01_broke-2_do_bug_report.zip](https://github.com/JacquesLucke/animation_nodes/files/215933/venice_01_broke-2_do_bug_report.zip)

**Comment by JacquesLucke** [comment]
Ah, this isn't really a bug. the problem here is that the output is right-aligned with a width of 10 characters by default. When you increase this value in the advanced settings you'll see that it looks correctly.

**Comment by clankill3r** [comment]
Why do you align it to the right? Are you half german half arabic? :smile:

**Comment by JacquesLucke** [comment]
haha because in most cases (like numbers) aligning to the right looks much better.

**Comment by clankill3r** [comment]
Ah ok, now I get it :)
That's a nice thing to have but wouldn't it be better to have a default of 0?
Also, atm a negative width i allowed, but I would like to look into that to gain some baby steps experience.

**Comment by JacquesLucke** [comment]
hmm, what do others think about this. I don't use this node very often so someone else might know this better.

Should the default be 0?
@LeonCheung, @og76

**Comment by LeonCheung** [comment]
True that width=0 can be nicer for numbers, just like how every speadsheet does:

![77](https://cloud.githubusercontent.com/assets/494788/14591363/d1200f02-0542-11e6-9ec2-a9c5c6c62bd6.png)

However, there can always be exceptions:

![excption](https://cloud.githubusercontent.com/assets/494788/14591788/be94ee96-0549-11e6-81db-ebfe3277692f.png)

Plus I doubt width=10 can be fairly enough for most cases, even for single number (maybe 100? I doubt too :smiling_imp: ):

![88](https://cloud.githubusercontent.com/assets/494788/14591352/78b2dcb4-0542-11e6-90a9-04ee46b243c4.png)

Thus it will quite possibly confuse users if they don't know there are advanced options for it.

I think in MOST cases, it should be either adapt to zero (align to left) or the length of the longest item(align to right). If the latter one causes performance issue, then a default value 0 might be a compromise (maybe I should call it "sure card"?). Anyway, here comes Doeke's case, right? :)
