### ISSUE TITLE
Output to List with Loop

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#502]
As far as I can see there is no way to use a loop and append items to an existing List.

![loop_problem](https://cloud.githubusercontent.com/assets/738650/14406717/5c930ae2-feb0-11e5-95a5-be065bde7e80.PNG)

(You can pass an List as parameter, but then it's the end of the line inside the loop tree)

**Comment by JacquesLucke** [comment]
Here are two possible way on how to extend an existing list:
![extend list](https://cloud.githubusercontent.com/assets/5881326/14408974/38bd37ba-ff09-11e5-801e-44061c13a37c.PNG)

The first way should be prefered.
Also note that 'Output' has to be enabled and 'Copy' disabled to make the second approach work.
The second approach does only work in simple cases like this when you don't use the list somewhere else in the loop (if you use it somewhere else AN will make copies of it). You could also use the Reassign Parameter node to make the second approach saver to use but it's easier to just use the approach above :D

**Comment by clankill3r** [comment]
This doesn't work in my case.
For each element in my loop it creates an array, not a single element.

Here is a half example (cause I can't go further)

![problem](https://cloud.githubusercontent.com/assets/738650/14421112/0fdcc7ee-ffd0-11e5-949b-1b2c34d30662.PNG)

**Comment by LeonCheung** [comment]
For the last image, can you illustrate what result will be expected?

**Comment by LeonCheung** [comment]
Is this what you want?

Method 1:
![method1](https://cloud.githubusercontent.com/assets/494788/14421627/488adcb8-0005-11e6-8587-85d91e5668e1.png)

Method 2:
![method2](https://cloud.githubusercontent.com/assets/494788/14421626/488ac6d8-0005-11e6-8cee-09ae6a132873.png)

**Comment by og76** [comment]
0. it is a bad example as you can get this done without all this trouble, by having normal output, but with extend.
 but assuming it could be more complicated, I follow.
1. the right way is actually to use reassign, assuming you have a more complicated procedure than an append/extend
(it is a convenience, but not a very nodal and natural way to right to left like append)
2. don't need to create list, unless it contains something
  is enough to have the parameter, I even uncheck the input, to show only as out, (for coolness)

![reassign](https://cloud.githubusercontent.com/assets/11709974/14421782/25de98ea-ffdc-11e5-821d-ad863904b52d.PNG)

**Comment by clankill3r** [comment]
All thanks. I just need some time to look into this. I always jump around.
And I just got a new place to live so I need to move, and I broke my keybone, and I have a deadline next week. So it might take some time but in the end I will read the replies in detail!

**Comment by JacquesLucke** [comment]
Can we close this issue?
