### ISSUE TITLE
Get List Element -1

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#504]
Not sure if possible, also I didn't put much thought in it.
But using -1 on Get List Element to get the last value, just like you can in python.
(Maybe then also -2 etc. but it could also be that this opens a gate to hell)

**Comment by LeonCheung** [comment]
Have u tried to find the **Allow Negative Index** option in Advanced Node Settings panel?

**Comment by clankill3r** [comment]
tried :)

No, I should look more often there. So for it didn't have much use for me that I kinda stopped looking at it.
