### ISSUE TITLE
Some nodes not yet exposed to menu

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#506]
Just a quick memo here:

Change Text Case
Change Matrix Pivot
a few Mix xx List nodes

**Comment by LeonCheung** [comment]
Maybe the Mix XX List nodes can be nested in List category, as sibling to Create / Combine / Append.

**Comment by prubini87** [comment]
Is there a "Change Matrix Pivot" node?

**Comment by prubini87** [comment]
Some of the new nodes that are not displayed in the menu include the "Mesh Info" node, which I suppose should appear in the Mesh category of the menu, right?

**Comment by OmarEmaraDev** [comment]
Added in f54d9e9.
