### ISSUE TITLE
Bake Protocol

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#511]
The idea is to implement an easy way to bake (most of) the animations someone did with AN. 

**Advantages** of having a bake system:
- Increase playback performance for more complicated movements of many objects because the AN trees don't have to execute in order to update the animation.
- When the animation is baked it also works when someone opens the .blend file without having AN installed (This also includes renderfarms! (most renderfarms don't allow the user the use custom addons during rendering))
- Sometimes there are problems when AN changes the Scene during rendering (most crashes can be avoided by locking the UI during rendering (thx Thomas Beck for this important tipp!)). These problems cannot occure when the animation is baked.

There are a few **limitations** because we can only bake animations into keyframes:
- Mesh animations cannot be baked. Blender unfortunally doesn't have a nice way to do this afaik. Please tell me if I'm wrong.
- Objects aren't created or removed during the animation ((un)hiding is ok). This is mainly a problem when you animate the Instances input of the Object Instancer node.
- If you change properties of Blender objects within expression or script nodes they won't be baked.

**Usage**:
My goal is that the user just has to enable one checkbox named "Bake Animation" in the Node Tree panel. Then he has to play the whole animation once and can disable the checkbox afterwards. During the playback some nodes will write keyframes onto the objects. 

**Implementation Details**:
All nodes implement two new functions. We don't have to write them for all nodes because they will have a default implementation in the AnimationNode class. This way most nodes don't have to care about baking. 
The two new functions are the following (all names can change):
```python
def getBakingSupport(self):
    '''
    The return type is in: 
      NONE: the node does nothing that requires baking (default)
      NO: the node changes the scene but doesn't support 
             baking (like Mesh Object Output)
      PARTIALLY: the node changes the scene but not all 
             properties can be baked (like Text Object Output)
      FULL: the node changes the scene and can be baked 
             completely (like the Object Transforms Output)
    '''
    return "NONE"
```
and
```python
def getBakeCode(self):
    '''
    Works similiar to the getExecutionCode function but returns code 
    that will be executed after the node has been executed.
    The returned code should set the keyframes when executed.
    '''
    return ""
```

When "Bake Animation" is enabled AN will regenerate the Execution Code and 'asks' every node for its bake support type. When the node can bake at least partially the generator code will insert the code returned by getBakeCode directly after the execution code of the node.

**Benefits** or this approach:
- Absolutely no overhead when baking is disabled.
- We only need to change code were baking is important. Most nodes can ignore this protocol completely.
- When new ways come up to resolve the limitations it will be easy to implement them as well.

**Other UI features**:
Beside the very simple usage we can also change the color of the nodes to show the user the baking capability of each nodes (like blue for nodes which don't care about baking, green for nodes that fully support baking etc)

**Comment by clankill3r** [comment]
That would be the panel on the left side?
And I assume you can choose for each node tree if it should bake or not. Just like with the execution options.

**Comment by JacquesLucke** [comment]
Yes exactly. The option will be for every node tree separately.

**Comment by og76** [comment]
http://www.coyhot.com/blender-addon-amination-joiner/
this one does "baking animation" using MeshCache modifier, so it works for mesh data 

(+) it may solve mesh data anim
(+) it may even solve add/delete obj/mesh data phenomenon , not sure here
(-) is "distructive" in the way you cannot do much edit after, unlike keyframes

**Comment by JacquesLucke** [comment]
Yes I've seen this. The main problem is that the mesh cache modifier only allows deforming meshes. So you can't create/remove mesh data within the animation...

**Comment by og76** [comment]
hm, that can also be "baked" to shapekeys, that can further be edited
guess the add/remove mesh data can also use hide, (or at least vgroup to be used with hide modifier)
but that is pretty tedious to animate

**Comment by JacquesLucke** [comment]
I think it will be better to wait with that until blender has a better way to cache all kinds of meshes.

**Comment by clankill3r** [comment]
Wouldn't it be good if we work on a proposal somewhere for blender changes?

**Comment by JacquesLucke** [comment]
Caching is currently a big topic in Blender development anyway. 
http://code.blender.org/2016/03/proposal-for-caching-nodes-and-physics-development-in-blender-2-8/

I think we can't help much here.. And I'm pretty sure that they are aware of the current limitation.

**Comment by JacquesLucke** [comment]
I implemented initial support for an easy baking. The goal is that you just have to press this button:
![bake](https://cloud.githubusercontent.com/assets/5881326/14834298/ec397b8a-0c03-11e6-9c8b-a99e949003ad.PNG)

Currently it only works with these nodes:
  - Object Transforms Output
  - Object Matrix Output
  - Object Attribute Output

Other nodes can come later (but most likely before the next release)

As I said only values that can be keyframed can be baked (this excludes eg text and meshes).

Main Todos:
  - Support for more nodes
  - Show a warning when not everything can be baked

The mechanism works by:
  1. Rewrite the execution code with included insert_keyframe calls
  2. Visit each frame once
  3. Update the execution code again (now without the keyframe stuff again)

**Comment by clankill3r** [comment]
Great work.
What if you have multiple nodetrees? Is it possible to bake only a specific one?

**Comment by JacquesLucke** [comment]
No, currently it bakes everything that changes when you change the frame. So it bakes all node trees.
Doing it for only one specific one is a bit more trickey and I'm not sure if it's worth the effort (you can also turn of "Auto Execution" for the node trees you don't want to bake)
