### ISSUE TITLE
Change Order [Proposal]

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#512]
As far as I know the trees are executed in the order of overview:
![overview](https://cloud.githubusercontent.com/assets/738650/14475291/94987870-0101-11e6-9bc0-07de427d3cec.PNG)

Which is alphabetic.

It would be nice to have up and down arrows to change the order of execution:
![up_down_2](https://cloud.githubusercontent.com/assets/738650/14475299/9d96e5c4-0101-11e6-99ad-4d9cbd7e4421.PNG)

I kind of like the way the material system works:
![mat](https://cloud.githubusercontent.com/assets/738650/14475424/342df8d8-0102-11e6-9f87-09a8658bb4f6.PNG)

I already tried myself to create the up and down buttons for the overview but it was harder then I hoped. And I prefer to focus more on stuff that learns me more about what is already done for AN.

**Comment by JacquesLucke** [comment]
This is harder than it seems at first indeed. Not sure if it will ever be possible to change that order....
At least the straight forward way (changing the order of the trees in bpy.data.node_groups) doesn't work. Maybe there are other ways (not so straight forward) to do this.

**Comment by clankill3r** [comment]
Maybe I can do it when I gained some more experience with blender API and how AN is structured :)

**Comment by JacquesLucke** [comment]
Yes sure, whenever you feel ready. The file is here: https://github.com/JacquesLucke/animation_nodes/blob/master/operators/remove_nodetree.py

**Comment by clankill3r** [comment]
That comment is meant for https://github.com/JacquesLucke/animation_nodes/issues/499#issuecomment-207819157 I assume?

**Comment by JacquesLucke** [comment]
oh right ^^ sry
I have multiple tabs open haha
