### ISSUE TITLE
Object Instancer on Empty looses it's shape

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#519]
If I have an empty with a shape sphere for example and I use an instanced on it then the instanced become axis.

**Comment by JacquesLucke** [comment]
does it help when you active "Copy Full Object"?

**Comment by JacquesLucke** [comment]
Btw: you can create empties with the Object Instancer without a source object. 

![instance empties](https://cloud.githubusercontent.com/assets/5881326/14582837/27838718-0410-11e6-8074-b2d1dc6f854a.PNG)

**Comment by clankill3r** [comment]
No, 'Copy Full Object' does not help. (Apart from matching scale and rotation)

**Comment by JacquesLucke** [comment]
should be fixed now. thx for the report

**Comment by og76** [comment]
great
just to note, I used to solve this by Copy Full Object and then Reset source Data (Advanced)
that is also necessary on other objects that change something, so you may need it on other cases
