### ISSUE TITLE
AN doesn't support linked node trees.

### ISSUE THREAD

**Issue by clankill3r** [JacquesLucke/animation_nodes#520]
Don't know if it is on purpose but it would be great if linked node trees would be supported.
That way a library could be made of reusable nodes (compounds).

**Comment by JacquesLucke** [comment]
No, unfortunally this is not possible at all because AN needs to be able to change properties on the nodes. And nodes in linked node trees are 'locked'.

**Comment by clankill3r** [comment]
Is that also the case for group nodes or loop nodes?

**Comment by JacquesLucke** [comment]
That is the case for all nodes, ...
