### ISSUE TITLE
Picker on Text File Reader Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#525]
The path picker (eyedropper icon) fails to expose itself on subprogram invoke node, unlike the new Text Block Reader node (which is expected).

BTW, imho the Encoding type can also be useful to expose as a string input socket, isn't it?

**Comment by JacquesLucke** [comment]
Hm yes. You may be right with the encoding type.

About the other thing with the path chooser is unfortunally not possible.. It is just a property of the String socket and I don't know a nice way to 'link it up' to the invoke subprogram node.
https://github.com/JacquesLucke/animation_nodes/blob/v1_6/nodes/text/text_file_reader.py#L29

**Comment by LeonCheung** [comment]
Ok, I see. :)  So just have to use a workaround like this:

![subtitleimporter](https://cloud.githubusercontent.com/assets/494788/15092296/2d1fdcd8-1498-11e6-80b8-6f6c6cb24aa9.png)

**Comment by JacquesLucke** [comment]
![text_file_reader](https://cloud.githubusercontent.com/assets/5881326/15092537/3e09b666-146d-11e6-9c4d-ddac09bca67b.png)

**Comment by LeonCheung** [comment]
Cool, thanks!
