### ISSUE TITLE
The problems panels shows some error and advices of possible Bug

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#526]
Whe rendering this file:

https://drive.google.com/file/d/0B9SDRZRP7NzVbXh5Mk8ybjExWDg/view?usp=sharing

Tried with 1.5  and 1.6

**Comment by YorsLosilla** [comment]
Forget it was an error caused by an unconnected node on the scene compositor.

**Comment by YorsLosilla** [comment]
It seems that bug has arised again when trying to render.

**Comment by JacquesLucke** [comment]
Will check it again.. can you make a screenshot?

**Comment by YorsLosilla** [comment]
![captura de pantalla 2016-05-10 a las 23 25 50](https://cloud.githubusercontent.com/assets/12479570/15163056/9934341c-1706-11e6-90b1-c424cfa8e737.png)

**Comment by YorsLosilla** [comment]
By the way I have tried the new Bake option and it seems to work fine with it. But anyway I think this is a very interesting bug to investigate on.

**Comment by JacquesLucke** [comment]
hm can you also show me the error message in the console? :)
