### ISSUE TITLE
math module not imported , see combine euler for example

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#541]
using latest 1_6

are you gonna put all math / mathutils by default or we have to add again the getModules where needed?

(guess combine euler is thinking you already did it ..)
![math module](https://cloud.githubusercontent.com/assets/11709974/15235219/0ba141e0-18c2-11e6-946f-8538ae583a83.PNG)

**Comment by JacquesLucke** [comment]
no, only mathutils is in the global namespace. Look here: https://github.com/JacquesLucke/animation_nodes/blob/v1_6/execution/code_generator.py#L38
