### ISSUE TITLE
Suggestion: Subprogram Template Improvement

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#543]
If users want to create subprogram from Template menu (e.g, loop), they have to first, click on the Templates, then Empty Subprogram, then click on the dropdown menu, then click on Loop, then click OK, then click again to confirm position. 6 clicks in Total...

Possible solutions for a better workflow:

A. Use three buttons instead of a dropdown menu.
B. Make them as three sliblings to Templates. (not recommended for sure)
C. Move "Empty Subprogram" out of Templates menu, make it a separate 3-item menu.

Results:

A. 4 clicks needed.
B. 2 clicks needed.
C. 3 clicks needed.

I know it appears not kinda high priority issue. FYI.

**Comment by og76** [comment]
agreed. 

- should it be 3 buttons (add ..) ?
- or a separate menu next to template (the complete subprograms menu, as in shiftA)?
I used to do that in my branches ..

**Comment by og76** [comment]
var 1
![templates sub](https://cloud.githubusercontent.com/assets/11709974/15272782/e1ab954e-1a8c-11e6-95bd-6a25be64e2e3.PNG)

var 2
![templates sub2](https://cloud.githubusercontent.com/assets/11709974/15272784/ea894e7c-1a8c-11e6-9366-514a9acd7eb9.PNG)

var 3
![templates sub3](https://cloud.githubusercontent.com/assets/11709974/15272785/ef4f2daa-1a8c-11e6-88f5-047591f3ca41.PNG)

(I also include the struct part into the add / subprograms menu anyway, point is if we need it here too..)

I kinda prefer 2 or 3

**Comment by og76** [comment]
I'm modifying the main menu anytway to add missing nodes etc, so it's a good time to do this also 
So?

**Comment by JacquesLucke** [comment]
yes we can have the subprograms menu at the bottom next to the Templates menu.
I wonder, why did you insert the Struct nodes there? I don't think that they belong there.

**Comment by og76** [comment]
where else? yet another dedicated menu? they are very .. generic ..
lists? 
I also redo the menu so.. ?

btw, I guess the subprogram menu should be just the one subprograms _menu py and in the node menu I should import it? 
It's basically duplicated, same class ..

**Comment by JacquesLucke** [comment]
hmmm not sure where to put them, but definitly not next to the subprograms because there is no connection. Yes maybe a new menu category..... "Generic" or "Misc"... someone proposed this a long time ago (maybe you, not sure haha), or we call the cateogry "Struct"....

Yes if it really is the same menu you can just reuse it. Maybe rename the template_menu.py file to node_editor_header.py
And then fill in one above/below this line here:
https://github.com/JacquesLucke/animation_nodes/blob/master/ui/template_menu.py#L33

**Comment by og76** [comment]
I actually made another subprograms_menu just like the template.
but they can also go in the same file

and import the sub from main node menu ..

for struct, I'd go now for lists menu, they are somewhat related, and lists are kinda generic too
we can always change later, it's just a menu..

**Comment by og76** [comment]
ok?

so it's gonna be like this
![templates sub4](https://cloud.githubusercontent.com/assets/11709974/15273495/faad87fc-1aa3-11e6-8746-c4cf494323eb.PNG)


and with struc, I'd say to leave it fro now here
![struct](https://cloud.githubusercontent.com/assets/11709974/15273485/930e3d6c-1aa3-11e6-8283-9e6ca1c5d0f5.PNG)

**Comment by JacquesLucke** [comment]
ok.
One little change: you don't need this line: ``from . node_menu import SubprogramsMenu``

**Comment by og76** [comment]
so what, is already imported?

**Comment by JacquesLucke** [comment]
just try to leave this line away, you only need the identifier of the menu which is ``an_subprograms_menu``. And this identifier is in blenders global namespace.

**Comment by og76** [comment]
ok, see, and tested already ..

**Comment by og76** [comment]
done.

If there are more nodes to add to the menu, say so..

**Comment by JacquesLucke** [comment]
not sure, will close this for now.
