### ISSUE TITLE
A few missing menu items

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#547]
Text File Reader
Convert
Convert to Text
Convert Plane Type
Convert to Integer List

Not sure if they all should deserve a chance to suvive.

**Comment by JacquesLucke** [comment]
text file reader, yes
convert, no
convert to text, no (is always inserted automatically)
convert plane type, is already in the menu, geometry category
convert to integer list, no (is always inserted automatically)

**Comment by LeonCheung** [comment]
Haha, I see. Then request has been pulled.
