### ISSUE TITLE
math popup should have no OK confirmation

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#549]
unlike advanced popups where you may do several things before closing it, 
math popup is a 1 click choice (replacement for enum)

**Comment by og76** [comment]
may wanna merge the copysign pull first :)

**Comment by JacquesLucke** [comment]
Unfortunally I don't know how to do this... Not sure if it is even possible.

**Comment by og76** [comment]
I think you did for a while in 1_6 in advanced popup, now it's back
(that was the wrong place to do this as there are many options)

**Comment by JacquesLucke** [comment]
the fact that the popup for advanced settings closed immediately was a bug, not intended!

**Comment by og76** [comment]
then we need a bug in math :D 
well, how was that bug doin that?

**Comment by JacquesLucke** [comment]
not sure anymore haha
also I think the bug did not close the menu completely, only the 'body'

**Comment by LeonCheung** [comment]
I agree with o.g, one more click for confirmation makes little sense here. I don't know how things works, but one click selection is the most expected behavior imho, just like the two Data Transfer operators in 3D view (Tool Tab > Tools).

In case it has to be the way, at least we can make it disappear while mouse going off the popup, just like the F6 panel for 3D view operators.

**Comment by JacquesLucke** [comment]
I know that it makes sense here! I'm just not sure if it is possible, because it is a generic function that I plan to use in other nodes later maybe.
Also you don't have to press ok! just click somewhere outside the menu.

**Comment by og76** [comment]
I was thinkin about an option or 2 separate invoke popup 
Well, for one thing I am unable to find a standard decent way to do it. witch makes it more intriguing .:)

It seams that we are into a discussion about replacing an Enum menu with a popup. 
otherwise, it's not a big deal really.
