### ISSUE TITLE
separate triangulate bmesh node and find better tesselate method for rest

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#556]
triangulation method is not best now (as I see it and described further) so the node will change at least as algo

so 
1. I'm separating bmesh case cause **bmesh triangulation is ok** as it is and bmesh nodes are a separate species anyway +
   bmesh also has now indices of former ngons if required (most of the time not, so it's hidden)
   minor cleanups in triang polygons
   #555
2. The triangulation methods present are 
   - [tessellate_polygon](https://www.blender.org/api/blender_python_api_current/mathutils.geometry.html#mathutils.geometry.tessellate_polygon) : faster but with issues on the flip order of the result
   - [ngon_tessellate](https://www.blender.org/api/blender_python_api_current/bpy_extras.mesh_utils.html#bpy_extras.mesh_utils.ngon_tessellate) : slower 2x to 6x but caring for flip and good order

The way we use this, I'd go for the first, but the flip is annoing. The second is not that useful especially with preserving loop features but is more accurate.

I'm also looking already for more optimal ways to triangulate stuff (delaunay rule, but not only), so we'll further discuss on this. With the advent of cyton it may make sense to further explore ..

**Comment by JacquesLucke** [comment]
thanks for linking the different triangulate functions, I did not know about these.
I commented in the pull request on the code, the separation of the node can go into v1.6
