### ISSUE TITLE
[request] A node to manipulate spline parameters inside a loop

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#557]
The idea is to have the ability to manipulate spline parameters like bevel end inside a loop to sequentiate the animation of instanced spline objects.

**Comment by JacquesLucke** [comment]
Isn't this possible already?
(Bevel End etc are only stored per curve object, not per spline in blender. So you need to make instances of Curve objects, maybe?)

**Comment by og76** [comment]
twist and size are the only per spline (points), 
rest is in obj out

**Comment by YorsLosilla** [comment]
Yes I was doing something wrong. I didn´t renember that close curves doesn´t allow bevel animation. But that´s a Blender issue.

Sorry for the spam.
