### ISSUE TITLE
Struct Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#564]
![struct](https://cloud.githubusercontent.com/assets/494788/15804513/dbb8ea4e-2b3d-11e6-804e-5dfde845021e.png)

Just wonder is that the newer behaviour or a possible bug?

**Comment by JacquesLucke** [comment]
that doesn't look right, have to check

**Comment by JacquesLucke** [comment]
can you check please?

**Comment by LeonCheung** [comment]
So far so good. Nice fix. :)
