### ISSUE TITLE
Execution time display overlaps on Debug node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#565]
![drawer2](https://cloud.githubusercontent.com/assets/494788/15804642/ae874f34-2b42-11e6-969e-703ddebdf553.png)

No big deal, just point it out.

**Comment by JacquesLucke** [comment]
I know that this happens... But I think I won't change it. Because for that I'd have to create dependencies between different code parts that should stay indenpendent
