### ISSUE TITLE
need a new branch after 1_6 for further new nodes

### ISSUE THREAD

**Issue by og76** [JacquesLucke/animation_nodes#568]
just to keep master as is

for L-sys fractals, NLA strips, more bmesh ops, custom props etc etc .. some are already on the way :)

**Comment by YorsLosilla** [comment]
It will be also cool to have some Blender mesh operators as Tris-to-quads
or beautify faces.

2016-06-09 18:00 GMT+02:00 og76 <notifications@github.com>:

**Comment by og76** [comment]
will do, exactly these kind of "global mesh" ops I'm talkin

**Comment by YorsLosilla** [comment]
Oh men!! You have just make me happy 😂

2016-06-09 18:05 GMT+02:00 og76 <notifications@github.com>:

**Comment by JacquesLucke** [comment]
Sorry for the delay!
I will make a new branch when I have a clearer view on my new goals. Also I'll need some time to make bigger internal changes this summer. During this time I won't merge pull requests most likely. Please develop the stuff you want to create in your branches :)
