### ISSUE TITLE
not easy to get from bounding box to new object/mesh

### ISSUE THREAD

**Issue by jeske** [JacquesLucke/animation_nodes#569]
I wanted the bounding box of one object to be a mesh, so I could run a particle system on it. In the process of recreating the "cubeification" effect from this Houdini video.

  https://vimeo.com/16548929

Object Bounding box exports "polygons" (which is polygon indicies). However, this can't be wired to "Mesh Data from Polygons", as that polygon input is of a different type. This seems like a problem, as they both have the same name. 

Mesh Object Output has a "Vertices" input, but no edge indicies or polygon indicies inputs.

Object Bounding box exports a vertex list in a different order than the default cube, so wiring the verticies to a Mesh Object Output "vertices" input for the default cube doesn't work.

I was able to get what I wanted by wiring the vertices to a default cube, then deleting and recreating edges and faces to get a cube based on the vertex order from Object Bounding Box. It seems like it should be easier than this.

**Comment by og76** [comment]
Mesh object out has  (default ) mesh data. If u plug the vector list into this a node that makes mesh data out of vectors and polygon indices will be automatically inserted. 

This mesh data, in form of vectors and indices,  is found in other nodes and is the fastest method of manipulating this. 

Also, this is not the only place where nodes are inserted automatically to convert or combine data
