### ISSUE TITLE
[Request] Baking of Start and End Bevel Factor on Curve Output Object Node

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#571]
As long as most of the animations of splines rely heavily on those two fields if we can somehow bake them, the usability of the addon on render farms will be much more improved.

**Comment by JacquesLucke** [comment]
hmm I thought you can already bake these. will check again..

**Comment by YorsLosilla** [comment]
As far as I know only location, rotation and scale can be baked.

**Comment by JacquesLucke** [comment]
how did you try to bake it?

**Comment by YorsLosilla** [comment]
Sorry,  it was my mistake.
