### ISSUE TITLE
Animation Nodes 

### ISSUE THREAD

**Issue by prakashketkar** [JacquesLucke/animation_nodes#572]
Animation Node not uploading in my Blender 2.77

**Comment by JacquesLucke** [comment]
you have to give some more information..
did you uninstall previous versions of the addon?
can you take a look into the console and tell me if there is an error message? 
maybe there is also already an answer for your problem.

**Comment by prakashketkar** [comment]
hellow There is no error message however it is not appearing in Addon
nodes. I went to the guidelines page and it says as under. I am bored of
trying now. However I wached the tutorials and I wish to have it on my
blender versions. I tried for versios 2.69,2.73 & 2.77. Thanks. Script
requiremenots

To have your script show up in the Add-Ons panel, it needs to:

   - be in the addons/ directoryg
   - contain a dictionary called "bl_info
   <https://wiki.blender.org/index.php/Dev:Py/Scripts/Guidelines/Addons#Script_meta_informations>
   "
   - define register() / unregister() functions.

Script meta informationsYou have to include a python dictionary named
"bl_info" at the top of your addon .py file or __init__.py if it is a
module.mesge

**Comment by prakashketkar** [comment]
I don't know how but I was able to upload add-on Animation nodes in my Blender version 2.77. where i would get latest version of Animation nodes? Thanks.

**Comment by JacquesLucke** [comment]
Hey, sorry for the late answer... I have to do a lot for university atm..

Glad that your problem seems to be solved.
You can get the latest version at the startpage of Animation Nodes here on github. Just use the "Download Zip" button.
