### ISSUE TITLE
Add Option to link instances into the same group the source is in

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#574]

**Comment by JacquesLucke** [comment]
http://blender.stackexchange.com/questions/57395/duplicating-objects-with-rigid-body-settings

**Comment by ecksell** [comment]
Hi !
I'm trying to apply/keep rigid body settings to instanced objects. I wonder if you have progress on this issue because I haven't found the feature proposed here in this great add-on :).
