### ISSUE TITLE
Plugging vertex to color input

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#575]
![prtscr capture_2](https://cloud.githubusercontent.com/assets/3952687/16950790/45780552-4e05-11e6-93e8-4db9675a859d.png)

Why is it that in AN, we cannot just plug Vertex data into Color?

**Comment by JacquesLucke** [comment]
Both are completely different data types.. it would not make sense to connect a vertex with a color. 

I admit, the color looks quite similiar, but it is different.
