### ISSUE TITLE
Script Node bug when using variable called "radius"

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#577]
Not sure exactly what's happening, but this bug almost drive me mad. I was doing the simple Circle formula, and somewhat for no reason, the part with Radius seems to go to zero or something, causing the script node to fail.

I made video because Blender file just does not explain it.

https://www.youtube.com/watch?v=LpYP-K2oZN8

Around 14:00 >> I have to make new variable named "r" to bypass the bug in "radius".

Thanks!

**Comment by JacquesLucke** [comment]
This looks weird indeed. I cannot reproduce it right now. Can you share the file that is broken here?

**Comment by JacquesLucke** [comment]
nevermind, I get the same error when I rebuild your setup completely. Need some time to check. Wasn't your fault!

**Comment by JacquesLucke** [comment]
I just uploaded a potential fix for the bug.
Can you update your version and test if it works as expected now?
(don't forget to remove the old installation first)
