### ISSUE TITLE
[Suggestion] About Remove All Inputs

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#578]
When clicking Remove All Inputs button, I would suggest it removes all unused slots only, and keeps all already-connected slots. IMHO, this is more of a cleanup feature than a purging one.  :)

![remove](https://cloud.githubusercontent.com/assets/494788/17237538/ab2ef874-5585-11e6-8067-db863ee673ee.png)

**Comment by JacquesLucke** [comment]
Agreed.

btw: are you interested in creating an animation like this again?: https://youtu.be/hnlUhlkxQZU?t=18s
(I can do the rendering as I wrote in the BA thread) I'd really like to have a similiar animation in the next showreel, because it looks awesome :D

**Comment by LeonCheung** [comment]
Hah, appreciated for the invitation. Of course I did saw your _Call of Duty_. :P   Actually I was working on the Archimator v5.4 pushed by LuigiCasilli's latest post on BA. Hope we can make some cooler results this time, will try for sure. 

And I'm also trying to retouch the Rubik's Cube setup. Do you think that could be an interesting one to show, too? There are still something wierd that drives me crazy and I cannot find out why... we'll see.

Plus I'm planning to design a bunch of text motion graphs in one screen to show the power of AN from that field. Do you think that's also worth to do? (and make them as free temps for others to download)

I'm not sure if I can contribute all three cases. If not, which one or two of them do you prefer?

**Comment by JacquesLucke** [comment]
Coool hehe, I'd definitly like to see this archimator thing.
I mean, the animation was already good last year, but I think we can do better with materials and lighting ;D

Hmm, the rubiks cube is interesting but I still think AN is not really great for that, so I'd prefer the text animations over the rubiks cube.

Sure some free templates for test motion graphics would be awesome. I'm also currently thinking about how to make text animations etc a little bit easer but that is a long way to go. Fortunally I have a lot of free time in the next two months hehe

**Comment by LeonCheung** [comment]
Oh how time flies, here comes your summer holidays again. So we can count on a possible performance leap by the cython implementation? :D

**Comment by JacquesLucke** [comment]
Exactly. I wrote 4 exams in the last 7 days and next week is my last exam. Then I have lot's of time.

Yes. Some nodes will have a BIG speedup (loops themselves cannot be speedup though, only individual nodes). We are talking about 10-100x speedup.
I'm currently implementing some basic list types (Float List, Integer List, etc..) On top of that I'll implement more complex list types (Vector List, Matrix List, ...). You can work with these lists as normal in python, but you can also access them super fast from cython.
Of course we'll need some nodes that benefit from this speedup. I currently try to come up with a new concept in AN that includes Influencers etc. We'll see :)

**Comment by LeonCheung** [comment]
Cool!
