### ISSUE TITLE
Problem on Create Generic List node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#579]
Not sure why the loop affects the input data, and not sure if this is something related to the create list node.

![ddd](https://cloud.githubusercontent.com/assets/494788/17250623/b53869d4-55d7-11e6-9a94-566ab8406d47.gif)

[test file](https://drive.google.com/file/d/0B1ojv5B6Lb-3OXh3RU9NaF9XZzQ/view?usp=sharing)

**Comment by JacquesLucke** [comment]
AN can't do certain operations in generic lists. like deep copies for example. maybe the issue you have here can be fixed somehow, but not the underlying issue. slowly you are finding all the reasons why it is better to use specific sockets when possible :D

**Comment by LeonCheung** [comment]
I know, generic lists is not perfect, just found I have to use it that way in my archimator case to make life easier. I'll explain later maybe you can help to advise other workround for that.
