### ISSUE TITLE
Issue about empty slot

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#580]
Not sure why empty slots cause error here. Any solution?

![error](https://cloud.githubusercontent.com/assets/494788/17251659/45163b7c-55dc-11e6-87ad-bc69c24474c2.png)

[test file](https://drive.google.com/file/d/0B1ojv5B6Lb-3YXdpU081dzUxek0/view?usp=sharing)

**Comment by JacquesLucke** [comment]
I haven't look at in the file, but I guess it has something todo with what you do with that element in the loop. some node expects a list but it gets None.

**Comment by LeonCheung** [comment]
Yes, it seems so. So I was thinking if there can be an advanced setting to replace all Nones (here, for example) to [ ], which is what I was trying to do in case #549 to avoid problems instead of cleaning all unlinked inputs by the x button, in order to make it more user-friendly, because AN will reports error for that and not all users know the way to solve that....

**Comment by LeonCheung** [comment]
Oops, I mean #579 :P

**Comment by JacquesLucke** [comment]
Unfortunally that isn't really possible. There is no way for AN to tell when to use [] or None or something else as default. Also, nodes and sockets are a bit separated.
