### ISSUE TITLE
blender 2.78 beta instant crash when opening blend file with AN nodes

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#581]
Files that were made in blender 2.77 and AN 1.6 are causing blender 2.78 beta builds to crash on  file load.  I'm unable to get console output.
Creating new node setups in fresh blend file, seems to work ok.  Also opening blend file (with AN nodes)  made in blender 2.78 works ok too.

**Comment by JacquesLucke** [comment]
thx for the report. I already reported it earlier today here: https://developer.blender.org/T48980

**Comment by JacquesLucke** [comment]
should be fixed already
