### ISSUE TITLE
Add perlin noise node or perlin noise options to wiggle node

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#582]
After watching this artwork from Jose Conseco: 
https://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=3076341&viewfull=1#post3076341

It seems that it could be very usefull to have Perlin noise option integrated on nodes.

**Comment by JacquesLucke** [comment]
In fact the wiggle nodes use the perlin noise internally. But maybe we can make it more explicit in other nodes :)
