### ISSUE TITLE
Spline Tilt data missing?

### ISSUE THREAD

**Issue by vOidSenses** [JacquesLucke/animation_nodes#583]
No matter what I try I can't seem to find a away to extract or sample a spline tilt data.

Am I missing something?

I was trying to recreate something like path following and while positioning works the tilt data is lost, debugging the spline in various forms doesn't reveal any data, is that correct?

**Comment by JacquesLucke** [comment]
Yes, unfortunally this is correct.
I'm doing some major refactoring of the spline internals right now. I still think we can have this. Just need more time. 

https://github.com/JacquesLucke/animation_nodes/issues/443

**Comment by vOidSenses** [comment]
Thx for the answer and sorry for the duplicate.

Looking forward for that update and meanwhile I'll use a curve or something to recreate that.
