### ISSUE TITLE
Skin Modifier and Skin Data did not work with Line Mesh Generator

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#584]
![prtscr capture](https://cloud.githubusercontent.com/assets/3952687/17503358/8c491f10-5e32-11e6-845c-9e97522b8391.png)

Just now, I tried using Skin Modifier with Animation Nodes, and just found out I cannot use Skin Modifier even for Line Mesh generator :( This makes me a bit sad.

I am wondering whether it is because of that mesh get generated each cycle? Or something else? Maybe current version 1.6 limitation?

I am curious about "Add Skin Data" portion. Can we have a way to access and play around with Skin Data more easily in Animation Nodes?\

Will try to make procedural insect. I will still need to understand way around object matrix and vector when using multiple objects.

Thanks!!

**Comment by JacquesLucke** [comment]
I just tried to do the same.. Looks like you're right..
I also found that when you disable Auto Execution you can press the "Add Skin Data" in the modifier and it works. This operator adds an additional data layer to the mesh object, which AN always resets/removes...
It looks like there is no straight forward way to add this layer using the python api...
Will try to look at it in more detail when I finished some other (bigger) tasks. Until than you cannot animate a mesh with AN and use the skin modifier. (static mesh is possible as I described above)

Another thing that works is when you set the mode of the Mesh Object Output node from "Mesh Data" to "Vertices". In this mode you can just move existing vertices in a mesh, no data is created or removed.
