### ISSUE TITLE
Baking attribute output

### ISSUE THREAD

**Issue by s-leger** [JacquesLucke/animation_nodes#588]
Hi, 
Trying to bake object's material opacity with an object attribute output, but with no luck until now.
Any idea, advice on how to do such things, or why this can't be done and what should we do to get it working ?

**Comment by JacquesLucke** [comment]
can you make a screenshot of the property you want to bake please?

**Comment by s-leger** [comment]
![Image bake material](https://raw.githubusercontent.com/s-leger/images/master/material.jpg)

**Comment by s-leger** [comment]
Found something:
C.object.keyframe_insert("data.materials[\"Material\"].alpha", index = -1)
ValueError: bpy_struct.keyframe_insert() path spans ID blocks

bpy.data.materials["Material"].keyframe_insert(data_path="alpha", index = -1)
True

C.object.data.materials[0].keyframe_insert(data_path="alpha", index=-1)
True

So code generation must insert keyframe on object path less property part


    def getBakeCode(self):

        yield "if object is not None:"
        yield "    try: object."++".keyframe_insert(path, index = arrayIndex)"
        yield "    except: pass"

**Comment by s-leger** [comment]
Try to get object path for baking this way seem to work in ObjectDataPathOutputNode

    def getPropertyPath(self, object, path):
        if "." in path:
            path_prop, path_attr = path.rsplit(".", 1)
            prop = object.path_resolve(path_prop)
        else:
            prop = object
            path_attr = path
        return prop, path_attr
        
    def getBakeCode(self):
        yield "if object is not None:"
        yield "    pathToProperty, propertyName = self.getPropertyPath(object, path)"
        yield "    try: pathToProperty.keyframe_insert(propertyName, arrayIndex)"
        yield "    except Exception as e:"
        yield "        print(\"Bake error : %s %s %s\" % (object.name, (\"{}.keyframe_insert({},{})\".format(pathToProperty, repr(propertyName), arrayIndex)), e))"
        yield "        pass"

**Comment by s-leger** [comment]
The same for ObjectAttributeOutputNode, but dont know how to handle indexed attributes in array

    def getBakeCode(self):
        if isCodeValid(self.attribute):
            yield "if object is not None:"
            yield "    pathToProperty, propertyName = self.getPropertyPath(object, {})".format(repr(self.attribute))
            yield "    try: pathToProperty.keyframe_insert(propertyName, -1)"
        #   yield "    try: object.keyframe_insert({})".format(repr(self.attribute))
            yield "    except: pass"
