### ISSUE TITLE
Avoiding Animate XXX nodes error

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#592]
Just take Animation Numbers node for example, when setting Duration value to 0, AN reports error and we have to, first, try a non-zero value, then click Retry or Execute Node Tree button to make AN running again.

Any hard coding way to improve it better? (maybe we can internally use a very small one like 0.000000001 while it was set to 0? )

**Comment by JacquesLucke** [comment]
Yes this should be fixed. I'll use the fix you suggested. Just need some time, maybe tomorrow

**Comment by JacquesLucke** [comment]
In fact I implemented this fix already. I just used the wrong variable during the division..
