### ISSUE TITLE
Problems creating Structs inside of a Loop?

### ISSUE THREAD

**Issue by AdmiralPotato** [JacquesLucke/animation_nodes#594]
In the AN 1.6 release, I'm trying to create a new Struct inside of a Loop, using a "Set Struct Elements" node, but it seems that I'm either getting back a Struct where none of its properties are set, or a single Struct instance is every element in the loop's reutrned list. I'm not exactly sure what's happening here.

In the case where it seems that nothing's being assigned to the struct, the "Set Struct Elements" node's "Performance -> dataIsModified" for the "Struct" checkbox -is- selected.

![image](https://cloud.githubusercontent.com/assets/820844/17794779/accfcba0-656f-11e6-92c6-f8866058a471.png)

In the case where it seems that a value is being assigned to the struct, but every element in the loop's return list is the same, the checkbox above is -not- selected.

![image](https://cloud.githubusercontent.com/assets/820844/17794791/ba5cf0ea-656f-11e6-9b64-f78fa1a64a46.png)

Is there a good/smart/correct method to create Structs within a loop?

**Comment by JacquesLucke** [comment]
there was a little bug in the initial AN 1.6 version.
Can you test if it works with the newest master version?

https://github.com/JacquesLucke/animation_nodes/issues/564
