### ISSUE TITLE
Can't create instance variables for node

### ISSUE THREAD

**Issue by The-Iron-Turky** [JacquesLucke/animation_nodes#595]
I am not sure whether this is a true issue or a fundamental misunderstanding of bpy on my behalf, but I can't seem to find a way to give a node instance variables. As a standalone my code works by adding instance variables in the class's __init__, however when run in blender I receive an error message "AttributeError: writing to ID class in this context is not allowed: NodeTree, NodeTree datablock, error setting (my class).(the variable I'm trying to initialize)"
I have a lot of data that needs to be saved in-between execute calls. If anyone has a solution or could point me in the right direction I would be very grateful.

**Comment by JacquesLucke** [comment]
You should not use the init (and __init__) function of nodes. instead write your code into the create function. 

http://animation-nodes-manual.readthedocs.io/en/latest/dev_guide/tutorials/new_node.html

Furthermore storing custom variables per node as not as easy as in normal python classes.
I wrote more about it here: http://blender.stackexchange.com/questions/57991/how-to-maintain-per-node-instance-state

Hope it helps
