### ISSUE TITLE
Suggestion for Baking: Allow the user to select baking every n frame

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#596]
Baking in AN is great. The problem is that when you bake a file with hundreds or thousands of objects the size of the file can become huge very fast.

This is partly due to the animation. However if you insert a keyframe only on 1 of every two frames the size of the file can drop drastically. And the result is quite good also.

It will be also great the that the system could check if there´s any change between the frame to be baked and the previous frame. If the value is the same then there won´t be any need to insert a new keyframe.

**Comment by JacquesLucke** [comment]
I thought about that before. Maybe I'll implement this as a post-processing effect -> At first all keyframes are set and afterwards another function optimizes them to need less keyframes for the same effect.
