### ISSUE TITLE
Caching for script nodes with generic outputs

### ISSUE THREAD

**Issue by raingloom** [JacquesLucke/animation_nodes#597]
If it can cause problems then just set it to "disabled" it by default but don't disable the whole setting.

why is this a problem for me: I am using the generic type for a script as there is no proper way of using multi-dimensional arrays (only 1D) and I did not want to hack around the problem by handling array sizes with the node network.

**Comment by JacquesLucke** [comment]
ah I think someone said that before. I just forgot to change it. Thanks for the remainder.

https://github.com/JacquesLucke/animation_nodes/commit/4f397a5f623a66f78b12d990b286944c2c2488f7

Does this solve your problem?

**Comment by raingloom** [comment]
Yes! Thanks a lot!
