### ISSUE TITLE
Feature Request: Vector Clamp

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#601]
Used to limit vector(s) to a certain "cubed" space by defining locations of two extreme points. e.g. using point (1,1,1) and (-1,-1,-1) to limit vectors in a 2x2x2 space. (Maybe as a new Vector Math type? or a separate node?) You know, using three Clamp nodes and separate/combine nodes is quite inenfficient in such cases.

And any chance to a possible Euler Clamp too?

**Comment by JacquesLucke** [comment]
yes, both are possible and will eventually make it in :)
