### ISSUE TITLE
Multiple scene rendering issues

### ISSUE THREAD

**Issue by s-leger** [JacquesLucke/animation_nodes#602]
Hi,
Facing issue on multiple scenes setup.
File with 2 scenes : A and B.
AN code build for scene A, with scene A explicitely set.
When rendering scene B, frame randomly jump at time 0 and render this instead of right one.
Any way to ensure the code only run when rendering scene A ?

**Comment by JacquesLucke** [comment]
hm not sure, Why does the frame randomly jump anyway? 
Can you maybe create a simple scene in which I can see the problem myself?

**Comment by s-leger** [comment]
Think something went wrong with context used for rendering, randomly jumping from scene A to scene B. Objects are scene B ones, camera is a linked one so i dont know if there is a swap, but time randomly jump from the one set on scene A timeline and the right one on scene B.
Scene currently a big one (more than 300Meg) so i've to narrow it down a bit.

**Comment by JacquesLucke** [comment]
Will close this for now. Please open a new issue when the problem still exists and provide a simple .blend file.
