### ISSUE TITLE
how to force module reloading?

### ISSUE THREAD

**Issue by diramazioni** [JacquesLucke/animation_nodes#605]
Hello, I'm following the dev guide to create new nodes, what I don't understand is how to force module reloading while developing. I see in `__init__` where is done but I can't just run `__init__` . So how to apply a change without having to restart blender?

**Comment by diramazioni** [comment]
Sorry I found [this has been already answered](http://blender.stackexchange.com/questions/52612/reloading-animation-nodes-node-development-workflow) maybe it should be mentioned in the guide.

**Comment by JacquesLucke** [comment]
Thanks, will take that into account when I work on the developer manual the next time!
