### ISSUE TITLE
"String" and "Text"

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#606]
Sometimes it is a bit annoying that both terms ("string" and "text") are used in AN, although they mean exactly the same

I'm thinking about renaming the `StringSocket` to `TextSocket`. This should solve most of these issues. Unfortunally this also means that all sockets of this type will be broken in the next release (unless I find a good way to solve it... working on it..)
(EDIT: also some nodes will be broken as I'll rename them too for consistency reasons..)

Is it worth it? I mean it is definitly more future proof to only have one term for one thing, but I'd to hear your opinions.

**Comment by adamearle** [comment]
Change it the world will get over it. Just put it in the release notes.
Better to future proof it now then later. I wouldn't waste your time on
trying to solve the cross over for users. If I was use i would move on to
something that i found much mor exciting and of more benift for the
developement of the AN.

Adam

**Comment by LeonCheung** [comment]
Agree. String is more terminological. It's better to let Text survive, if this is a life-or-death fight between the two, since it can indicate more things other than String.

**Comment by JacquesLucke** [comment]
done
