### ISSUE TITLE
using AN on the command line (-b)

### ISSUE THREAD

**Issue by cms-tc** [JacquesLucke/animation_nodes#612]
Hi,
might well be I'm just too dumb, but would very much appreciate some help,
regarding using 'animation nodes' while rendering from the command line :)

eg. using the provided 'Dominoes.blend' file...
eg. trying to modify the 'start' and/or 'end' Values in 'Get Spline Length' before rendering...
...this should change the number of dominoes

with GUI running, using:
- a custom property source for an object node
- directly doing something like bpy.data.node_groups[0].nodes['Get Spline Length'].inputs[1].value=.5
updating via:
- creating triggers 
- enabeling auto
- executing bpy.ops.an.execute_tree(name=node.name)
- using node.execute()
all of these work perfect :)
 
However, no matter how hard I try, 
'animation nodes' seems really unwilling to update before rendering 
when called from the 'command line' :(
(blender --addons animation_nodes -b ...blend -o ... -P doit.py ...)

I tried:
- triggers
- auto
- walking nodes calling bpy.ops.an.execute_tree(name=node.name)
- walking nodes callig node.execute() and/or node.update()
these all give no errors and even a correct 'finnished'
but the rendering wont change :(

Doing more evil things like
- bpy.ops.an.profile(function = 'EXECUTION', output = 'CONSOLE', sort='calls')
- bpy.ops.an.profile(function = 'UPDATE_EVERYTHING', output = 'CONSOLE', sort='calls')
ends up with an error :(

Any help or hint would be very much appreciated :)
many thanks!

**Comment by JacquesLucke** [comment]
I don't know much about running blender from the command line, but it should definitly work somehow.
Can you maybe provide me a simple test file and tell me exactly how to set it up so that your problem occures? 

(btw: you definitly don't have to call node.execute and node.update yourself, both functions are not intended to be used that way)

**Comment by cms-tc** [comment]
You already helped me a lot :) Thx!

While preparing a simple sample file, I noticed, it is working on my Windows env. but not working on my Linux env. :(

I'll attach the files anyhow, so if somebody has the time to throw that on his linux system, sure appreciated :) 
Would be nice to know if that happens on any linux or just my linux ;)
But please don't bother, I have a point to continue investigating now, so hope I'll get further...

Attached, a simple .blend and .py file:
- the 'Fin' Value moves the copied box, values from 0-3 make sense
- modifying the .py file, you should see both boxes overlapping (Fin=1) or separate (Fin=3)
- the .py prints some output so you can see when Fin was set and what execute returned
to render from the command line use:
.....blender --addons animation_nodes -b an-cmd-t1.blend -P an-cmd-t1.py -F PNG -f 1
(the order of arguments is imp. to have the .py running after loding the file but before rendering)

[an-cmd-t1.zip](https://github.com/JacquesLucke/animation_nodes/files/513209/an-cmd-t1.zip)

**Comment by cms-tc** [comment]
fixed :)

animation nodes has big trouble when there are no userprefs for the user it is running as!
make sure to copy some userprefs with animation nodes enabled over to the home dir of the user you run it in command line mode!

(JacquesLucke, maybe you want to add to use defaults in your preferences.py when there are no userprefs)

thx for the help :)

**Comment by JacquesLucke** [comment]
Thanks for the info! Will try to fix this semi-bug when I find the time.
I opened a new issue for that.
