### ISSUE TITLE
New Option Idea for Color Related Nodes

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#613]
It would be very convenient to have a toggle (or advance setting?) to allow user to choose whether to input / ouput a 3-item or 4-item data, in other words, we are talking about Alpha channel. In some cases  (e.g. when assigning color for vertex color), currently we have to manually create a 3-item list for that.

**Comment by JacquesLucke** [comment]
I'll take care of this and related issues when I'll work on all the color stuff again. A bigger rewrite is necessary.
