### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#615]
Though I tried to solve [this](http://blender.stackexchange.com/q/61847/696) problem, but I'm feeling there might be something odd based on the OP's file and result, which should not be like that.

@JacquesLucke If so, would you please look into it? Or, if not, what's wrong with the setup?

**Comment by JacquesLucke** [comment]
I think you identified the problem correctly. The cubes were not exactly in one row. You can solve this by selecting each row individually and then press S, X, 0, Enter. 

I found nothing else that is wrong in the file.

**Comment by LeonCheung** [comment]
Thanks for confirming. :)

**Comment by LeonCheung** [comment]
And why it cannot be solved even by using round math first?

**Comment by JacquesLucke** [comment]
not absolutely sure but I'd guess that there are still differences in the individual bits of each number. 
Same problem as that 0.3 * 3 is not always equal to 0.6 + 0.3 in computers.. (just an example)

**Comment by LeonCheung** [comment]
Hmm, so you mean it might be something about precision behind the math?

**Comment by JacquesLucke** [comment]
Hm yes.. However if you can make me an example file that uses the rouding/snap, I'll check it again.

**Comment by LeonCheung** [comment]
OK. Try [this](http://pasteall.org/blend/index.php?id=43948).

**Comment by JacquesLucke** [comment]
Ok, I tried to find out what's wrong with this file for 20 min now... I think I found something, but I'm not absolutely sure.

Looks like some objects in the Inprecise grid have wrong Initial Transforms. It worked after I selected all and pressed the "From Current Transforms" button again.

Can you confirm that?

**Comment by LeonCheung** [comment]
Hmm, you are right about that, it solves that, however, in my opinion, the "tiny inprecision" will be removed after snapping right? So it doesn't make the sense, imho.... Such a headache.

**Comment by LeonCheung** [comment]
Ooops, you are absolutely right. The initial tranformation need a damn correction XD, Sorry for all the time trouble!
