### ISSUE TITLE
Text Object Output align

### ISSUE THREAD

**Issue by Dihotom** [JacquesLucke/animation_nodes#617]
Text object output node shows error after enabling align input. It happens in 2.78 version, 2.77 works fine.
Console says "`TextCurve` object has no attribute `align`"

![error](https://cloud.githubusercontent.com/assets/22814165/19346987/1c2359a8-914f-11e6-96be-99ab01c28dff.png)

**Comment by JacquesLucke** [comment]
Ah thanks. Looks like there was a change in the Python API, because Blender now supports vertical and horizontal alignment instead of only horizontal. Will fix :)
