### ISSUE TITLE
Cython Branch Mesh Replicate Mesh Data questions

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#618]
Can we possibly have multiple mesh data items plug into the "template" and then randomize the data input? Kind of like when using Particles and Group of Objects as Instances.

**Comment by enzyme69** [comment]
![screen shot 2016-10-13 at 23 02 30](https://cloud.githubusercontent.com/assets/3952687/19348337/2491aa82-9199-11e6-92cd-c8b5b4bbfaf2.png)

And the Poly Normal and Poly Center Vector Add didn't work Jacques. And you mentioned that Falloff or Vector Offset can vectorize... no idea.

**Comment by JacquesLucke** [comment]
about the first question: not yet, but possibly in the future :)

second: To me this looks exactly right, not sure what you expected.

**Comment by enzyme69** [comment]
Ah, ok first question need some loop maybe.

Second question was expecting something like below. But not sure how to do it with "transformations". Does Matrix vectorize yet?
![screen shot 2016-10-14 at 09 59 16](https://cloud.githubusercontent.com/assets/3952687/19370042/e6807a1e-91f4-11e6-997b-dcfb7ab59c89.png)

**Comment by JacquesLucke** [comment]
Well in your example above you just added some vectors together. A vector is only a translation and does not contain rotation. To do that a matrix is needed, and the Direction to Rotation node as well. The Direction to Rotation node is not vectorized yet, so you'll have to wait a little longer..
