### ISSUE TITLE
Random Number Boolean Error

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#619]
![screen shot 2016-10-14 at 17 38 07](https://cloud.githubusercontent.com/assets/3952687/19377869/23bedb06-9235-11e6-9485-1ae4513d0b99.png)

I think it should work, but not sure why it is not working... 

And in this version, I think Debug List does not always work.

**Comment by enzyme69** [comment]
Ooh this works, but the Debug failing..
![screen shot 2016-10-14 at 17 40 43](https://cloud.githubusercontent.com/assets/3952687/19377903/6232582c-9235-11e6-9d33-bb680b5ce9c0.png)

**Comment by JacquesLucke** [comment]
oooh ok, thx for the report. It would be helpful of you could show me the error message in the console everytime you find a bug :)

will fix

**Comment by JacquesLucke** [comment]
I fixed the Debug List node :)
