### ISSUE TITLE
3D Grid Template is broken

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#620]
![screen shot 2016-10-15 at 11 18 36](https://cloud.githubusercontent.com/assets/3952687/19405926/38630c0a-92c9-11e6-904c-966e8d3eef52.png)

This template is broken I think.

**Comment by JacquesLucke** [comment]
Looks like so, I think I'll just remove it.. The method used in the template is old anyway. What do you think?

**Comment by LeonCheung** [comment]
Agree.
