### ISSUE TITLE
Mininum width for node frame

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#622]
Just wonder if this needs to be limited, or keep such flexibility to width adjustment.

![overlap](https://cloud.githubusercontent.com/assets/494788/19417393/4e0d3dda-93de-11e6-9c36-5c4c5855cbba.png)

**Comment by JacquesLucke** [comment]
I increased the min width a little. Did you mean that, or something else?

**Comment by LeonCheung** [comment]
Yes, if it can avoid that.

**Comment by JacquesLucke** [comment]
I think it can, otherwise tell me after the next build. Btw: are you interested in trying to build AN on your platform on your own? (windows?) 
It would be cool if more people have the ability to compile AN. Also to make sure that the manual instructions will be correct.

**Comment by LeonCheung** [comment]
Of course, just don't know how.... you know I'm not currently a coder...

**Comment by JacquesLucke** [comment]
Can you come online to hangouts?
Here is a WIP guide:
http://animation-nodes-manual.readthedocs.io/en/an2/dev_guide/setup/windows.html
