### ISSUE TITLE
Create loop from pie menu

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#623]
When create loop from pie for a relatively complex setup, sometimes the invoked node can be automatically created to a very long distance from it:

![invoke](https://cloud.githubusercontent.com/assets/494788/19424441/d52df188-945b-11e6-90f2-2fcd38d73098.png)

**Comment by JacquesLucke** [comment]
That definitly should not happen :D

can you send me this file so that I can test it myself?

**Comment by JacquesLucke** [comment]
should be fixed now, please confirm :)

**Comment by LeonCheung** [comment]
It seems to be fixed as tested. Thanks!
