### ISSUE TITLE
[Idea] Distance to Spline Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#624]
Though I managed to use some existing nodes to make it working, but it's a bit tricky and not so effective. Maybe it worth to be one possible node? Or even better solution? Just brainstorming here.  :)

Basically in my current project I want to make kinda "sort along spline" rule. [Here](https://drive.google.com/open?id=0B1ojv5B6Lb-3Y0lrM25FWmNmTjg) is what I got so far.

**Comment by JacquesLucke** [comment]
Not sure how efficient a "Sort Along Spline" setup can be... 
Beside that: you might want to use the Project on Spline and a Vector Distance node to calculate the distance between a point and a spline. Maybe your method is more efficient, but it's also less accurate.

**Comment by LeonCheung** [comment]
I mean maybe it would be better that the Project on Spline has a **Distance** output.  :)

**Comment by JacquesLucke** [comment]
ok, I can implement that when I find some time. I have to do some other things atm (family, university, etc)
