### ISSUE TITLE
List length display for more nodes

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#625]
For example, the three nodes here are missing that:
![length](https://cloud.githubusercontent.com/assets/494788/19468977/e8c8ef18-954b-11e6-98ae-b1865951d09a.png)

**Comment by JacquesLucke** [comment]
that is not possible because these list lenghts are determined at run time. while the Create List node knows the length at compile time.

**Comment by LeonCheung** [comment]
I see.
