### ISSUE TITLE
String Text is not Index Iterable in Loop :(

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#626]
I was trying to pipe in text string using Index Item, but apparently this is not possible :(

![screen shot 2016-10-19 at 20 38 47](https://cloud.githubusercontent.com/assets/3952687/19513657/679e4ac2-963c-11e6-8cdb-b39e648b2edf.png)

Is this like a bug, or I was doing it wrong?

**Comment by JacquesLucke** [comment]
looks like you are using the same base text object multiple times.

**Comment by LeonCheung** [comment]
My two cents:
![vector](https://cloud.githubusercontent.com/assets/494788/19525929/38a07a7e-9655-11e6-8f15-f29c8b7ada35.png)

**Comment by enzyme69** [comment]
Ok, interesting... will study.
