### ISSUE TITLE
Object Bounding Box seems to have failed

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#627]
![screen shot 2016-10-21 at 16 46 37](https://cloud.githubusercontent.com/assets/3952687/19587948/052a3ad6-97ae-11e6-9f59-c2f30fa17742.png)
![screen shot 2016-10-21 at 16 46 32](https://cloud.githubusercontent.com/assets/3952687/19587949/057666a4-97ae-11e6-8789-c3e82a142521.png)

**Comment by enzyme69** [comment]
However, this seems to work. Hmm.. wonder why.

![screen shot 2016-10-21 at 16 52 13](https://cloud.githubusercontent.com/assets/3952687/19588064/d866bc30-97ae-11e6-8c3a-383e4d7d672c.png)

**Comment by enzyme69** [comment]
On that note, is it possible to get the Bounding Box that's more like Sverchok? (blue lines)

![screen shot 2016-10-21 at 16 59 23](https://cloud.githubusercontent.com/assets/3952687/19588182/c7e8b98e-97af-11e6-9e40-b00120beb24a.png)

I kind of want to do this Bounding Box Place On Ground and Stacking.

**Comment by JacquesLucke** [comment]
ah thx, the first issue is a bug, I didn't update the node yet to use the new data structures.
(the convert node corrects this, this is why it works then)

Both bounding boxes should be possible, will implement this later :) (the one in AN uses the rotation and dimension of the Blender object, while Sverchok calculates it from the actual vertices)

**Comment by enzyme69** [comment]
Aha, thanks for checking this. I'll just wait for update, not urgent. Cheers~

**Comment by enzyme69** [comment]
Looks like BBOX also does not work for multiple objects yet?

![screen shot 2016-10-25 at 10 20 25](https://cloud.githubusercontent.com/assets/3952687/19667462/bfdd0ba6-9a9c-11e6-823b-3208e73abcaf.png)

In another setup, I have the BBOX node actually indeed outputting list of 8 vectors for each point of the bounding box, however, if I tried to select each one of the BBOX list and then try to get to the element of the list, I cannot do it because it is an array inside an array?

For example 3 monkeys in different size, gave me these 3 list of vectors. I wanted to measure the distance of vectors to get the dimensions...

[Vector((-10.709173202514648, 1.3159105777740479, 2.5156991481781006)), Vector((-10.709173202514648, 1.3159105777740479, 2.5156991481781006)), Vector((-10.709173202514648, 1.3159105777740479, 2.5156991481781006)), Vector((-10.709173202514648, 1.3159105777740479, 2.5156991481781006)), Vector((-10.709173202514648, 1.3159105777740479, 2.5156991481781006)), Vector((-10.709173202514648, 1.3159105777740479, 2.5156991481781006)), Vector((-10.709173202514648, 1.3159105777740479, 2.5156991481781006)), Vector((-10.709173202514648, 1.3159105777740479, 2.5156991481781006))]
[Vector((-4.037454605102539, 0.7126027941703796, 2.538907527923584)), Vector((-4.037454605102539, 0.7126027941703796, 2.538907527923584)), Vector((-4.037454605102539, 0.7126027941703796, 2.538907527923584)), Vector((-4.037454605102539, 0.7126027941703796, 2.538907527923584)), Vector((-4.037454605102539, 0.7126027941703796, 2.538907527923584)), Vector((-4.037454605102539, 0.7126027941703796, 2.538907527923584)), Vector((-4.037454605102539, 0.7126027941703796, 2.538907527923584)), Vector((-4.037454605102539, 0.7126027941703796, 2.538907527923584))]
[Vector((0.2771318256855011, 0.14830297231674194, 0.9471637010574341)), Vector((0.2771318256855011, 0.14830297231674194, 0.9471637010574341)), Vector((0.2771318256855011, 0.14830297231674194, 0.9471637010574341)), Vector((0.2771318256855011, 0.14830297231674194, 0.9471637010574341)), Vector((0.2771318256855011, 0.14830297231674194, 0.9471637010574341)), Vector((0.2771318256855011, 0.14830297231674194, 0.9471637010574341)), Vector((0.2771318256855011, 0.14830297231674194, 0.9471637010574341)), Vector((0.2771318256855011, 0.14830297231674194, 0.9471637010574341))]

I think the answer is to use Script Node for now?
