### ISSUE TITLE
Alembic Export of deforming mesh failed

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#630]
I tried to export animation of deforming mesh but not getting the result expected (only static mesh).

![screen shot 2016-10-23 at 10 55 34](https://cloud.githubusercontent.com/assets/3952687/19623279/67484034-990f-11e6-9612-2cbbb06885df.png)

Is this because of the Alembic Export itself that is not compatible? Same result with Sverchok.

In the past, I am using MDD and with MDD, as long the vertices number is the same, it will do it. And I can export deforming mesh.

However with Alembic I cannot get the result.

**Comment by JacquesLucke** [comment]
The next version of AN will have this new *Make Mesh Exportable* checkbox. When enabled AN will do some small things that allow the alembic exporter to export the mesh the way it is intended (as animation).

![screenshot from 2017-05-07 20-06-46](https://cloud.githubusercontent.com/assets/5881326/25783669/b779b6f0-3360-11e7-9b18-6909444d3b22.png)

Currently the exporter is not fully featured. There are some small issues (which AN currently works around). I created to issues for this on developer.blender.org:
https://developer.blender.org/T51351
https://developer.blender.org/T51311

**Comment by enzyme69** [comment]
My quick solution is to force it using Displacement Map set to zero.

**Comment by JacquesLucke** [comment]
you should not even have to do this anymore (also not sure if this would work reliably in Blender 2.79)

At least this is easy now =)
