### ISSUE TITLE
Project on Spline node Performance

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#631]
I just noticed that this node is extremely time consuming (e.g. when being used in loop) comparing to other nodes such as Project on Plane, not Line. Not sure if it is normal or not.

**Comment by JacquesLucke** [comment]
You are right. Projecting on a spline is quite complex. However it is much faster when you have a polyspline instead of a bezier curve. still relatively slow though because it has to check the distance to each individual segment.
