### ISSUE TITLE
getting the value of a List socket

### ISSUE THREAD

**Issue by diramazioni** [JacquesLucke/animation_nodes#634]
I'm writing my own custom nodes with a StringListSocket as one of the input, and I can't get to it's value in my own defined edit() method.
`    def create(self):
        self.newInput("String List", "opt in", "opt_in")`
`def edit(self): print(self.inputs["opt in"].value)` value it's not defined for StringListSocket.
value is present and readable for all not List type socket in edit() and I can read "opt in" in getExecutionCode() so why is not defined for StringListSocket and how to get to it's value or an iterator?

**Comment by JacquesLucke** [comment]
You must not access the data that flows through the node network from the ``edit`` function. Instead please use the ``execute`` function as I show in this example:

https://animation-nodes-manual.readthedocs.io/en/latest/dev_guide/tutorials/new_node.html

**Comment by diramazioni** [comment]
ok but I need to (re)create new sockets based on the values of the opt_in when is connected so I check if it has a dataOrigin and if not None I try to read the value. This works for all not List types why it's forbidden for Lists? execute/getExecutionCode it's not the place to check and recreate sockets right?
Maybe there is a better way to accomplish what I'm trying to do: I need to copy certain sockets from a node to another. The value is not important and even the type I can derive from my own dictionary, I just need to know which socket has .isUsed as property set to True and recreate those

**Comment by JacquesLucke** [comment]
very rarely you should read the value from the sockets directly. AN handles all of that for you.
If you have a dynamic amount of sockets you can use the ``getExecutionCode`` function. It allows you to generate code on the fly.

The ``getExecutionCode`` variable gets executed everytime the node tree changes (eg when a link is created). Also you can call other methods of the node from the generated code. 
Maybe this code helps you to understand the concept: https://github.com/JacquesLucke/animation_nodes/blob/master/nodes/spline/curve_object_output.py

**Comment by diramazioni** [comment]
I've already used extensively getExecutionCode but it wont help here I think because
my problem is creating new input sockets based on the value of the input socket of another node.
To dynamically create sockets I see that the common practice is to recreate it edit() or when an operation is made on the UI to call recreate() but you said I can't check for connected socket values there. right? I see that it works for normal values but not for list type of values. 
Hope I been more clear

**Comment by JacquesLucke** [comment]
Changing sockets based on the input is not supported. It might be possible with some hacks but it is not intended to work. For good reasons. Imagine you use your node in a group or loop. Then it can be executed multiple times with different inputs. Changing the inputs multiple times per execution is not good, also I don't think that it will work due to the execution system of AN.

You'll need to find another way to implement the behavior you are looking for. Maybe I can help you when you tell me what you are trying to do.

**Comment by diramazioni** [comment]
I think I bypassed the problem by attaching a list to the context.scene dictionary but I consider it an hack indeed. I still have to test it extensively, I just saw it working..
I'm at 90% from having the entire functions of Sonic-PI sent (with a separate osc server) using AN as an interface to generate it's commands. It's a set of about a hundred of nodes or even more but the most important ones are a handful (and works GREAT so far the sounds get changed live with their parameters!!!). As soon as I have this problem solved I'll make a video and send it to you :)

**Comment by JacquesLucke** [comment]
Wow, that are a lot of nodes! Hope you'll make that video soon and share it with the world ;D
Good luck, I hope you find a better solution than this hack :)

**Comment by diramazioni** [comment]
well, I hoped to have some suggestion from YOU in this regard :) Maybe I'll soon upload some code so you can give me some direct suggestion. however I think that by now you have understood what I'm trying to accomplish. It's there a way to iterate in the sockets of another node and derive it's properties while you are on the create() phase ?

**Comment by JacquesLucke** [comment]
Of course, I can help you when I know better what you do..

Well, it should be possible, but I'm really not sure if this is a good idea.. Usually there should be no connection between the create method and the sockets of another node..

**Comment by diramazioni** [comment]
ok thanks for now:)
