### ISSUE TITLE
Extra edge when copying a mesh

### ISSUE THREAD

**Issue by bkurdali** [JacquesLucke/animation_nodes#635]
I've made a simple test to illustrate the problem:
[http://cloud.urchn.org/index.php/s/YqqfcNXhZYrYzVg](http://cloud.urchn.org/index.php/s/YqqfcNXhZYrYzVg)
![an_bug](https://cloud.githubusercontent.com/assets/4793742/20034380/31c86208-a392-11e6-9769-308e0c5ee9b4.png)

basically creating a mesh by copying another in this way results in what looks like an extra edge connected to all faces, attempting to delete this (in edit mode) crashes blender here.
Is this a bug or am I doing it wrong?

**Comment by bkurdali** [comment]
btw, the reason I'm  copying to a 'one' and a 'two' mesh is because I was concerned if the existence of data in the mesh previous to running AN made a difference. It doesn't seem to.

**Comment by bkurdali** [comment]
It seems the bug is in the Mesh Object Output node, because the following workaround doesn't crate the phantom edge:
convert Mesh Data to BMesh
use the BMesh option on the Mesh Object Output node

**Comment by bkurdali** [comment]
seems like the problem is in the mesh.from_pydata() call in line 110 of mesh_object_output.py , which means either there is a problem with the mesh data coming into the node - somewhat unlikely since it works with bmesh - or that the bug is in blender itself.

**Comment by JacquesLucke** [comment]
I can only guess that the mesh.from_pydata call skips the mesh update in this results in some problems.
What happens when you remove the link between the "Edge Indices" sockets.

This might help because of this check: https://developer.blender.org/diffusion/B/browse/master/release/scripts/modules/bpy_types.py;818af9c3315cb883436a3d75d634f449133cd3d9$440
Internally the mesh.update method does more than just recalculating the edges.. 
In the cython branch this should be fixed by default. I don't use the from_pydata method anymore but replaced it with my own version.

**Comment by bkurdali** [comment]
Ok, I've found the real issue (and a potential fix):
- we don't need the edges list if we already have the faces list, since faces define their own edges, not linking the edges data will fix the result as you say.
- running mesh.validate() after doing mesh.py_data() seems to be good practice as it will remove the redundant edges (and have no effect on a clean mesh)

**Comment by JacquesLucke** [comment]
yes, that is true. However sometimes faces and edges are needed (sometimes someone wants edges that don't belong to faces)

I already updated this part in the cython branch some weeks ago: https://github.com/JacquesLucke/animation_nodes/blob/cython/animation_nodes/nodes/mesh/mesh_object_output.py#L127-L131
AN will now always update the mesh by default (unfortunally this is a real bottleneck for larger meshes). Furthermore the user will have the ability to en/disable it in the advanced settings. Same thing with the validate function.
