### ISSUE TITLE
Polygon socket hidden in AN 1.7

### ISSUE THREAD

**Issue by bupla** [JacquesLucke/animation_nodes#636]
Hi, I can't find the “polygons” socket in the object mesh data node in the 1.7 version.
How can I convert this from the 1.6 version?
Thanks.

**Comment by JacquesLucke** [comment]
Sorry for the late answer, I don't have much time these days due to university and other things.
It is not easy to convert this to 1.7. The workflow when working with Polygons changed quite a bit. Sorry for the inconvenience.

**Comment by enzyme69** [comment]
@JacquesLucke This official version is still 1.6 right? You said no 1.7? Or I can update to get the functionality of "latest" now? I am afraid to update to 1.7 yet :)

**Comment by JacquesLucke** [comment]
Yes, 1.6 is official atm. 1.7 is only temporary, It will become 2.0 in the next release.
To get the latest functionality just grab a build from graphicall (Cython branch/v1.7). This is still in development. Should be relatively stable, but maybe there are things missing.
