### ISSUE TITLE
Getting 'object mesh data' does not work error 

### ISSUE THREAD

**Issue by shhlife** [JacquesLucke/animation_nodes#638]
I was following this tutorial:
https://www.youtube.com/watch?v=19wRsmBIVBQ

and I'm getting Object Mesh Data does not work as soon as I get to about 1:17.. couldn't figure out how to fix it.

**Comment by JacquesLucke** [comment]
Which operating system are you working on?

**Comment by shhlife** [comment]
on a mac

**Comment by JacquesLucke** [comment]
That is a bug, it should be fixed already. I asked Jasper if he can update the build on github :)

**Comment by JacquesLucke** [comment]
A new build for has been uploaded an hour ago. Can you check if the problem still exists, please? 

http://graphicall.org/1204

**Comment by jasperges** [comment]
I just wanted to say that the new macOS build is up on graphicall, but @JacquesLucke  beat me. :)

**Comment by shhlife** [comment]
works great thanks! :)
