### ISSUE TITLE
Disney magic wand

### ISSUE THREAD

**Issue by antonvdh** [JacquesLucke/animation_nodes#639]
Is it possible to make a tutorial howto make the disney magic wand with the animation node add on.

**Comment by JacquesLucke** [comment]
Not sure what this is. Can you provide some more details please?

**Comment by antonvdh** [comment]
Moving a magic wand and then you see little stars called the disney dust. You can see it here the starbow at 0.22 https://youtu.be/kzYfRLMtP9c

**Comment by pohlt** [comment]
You wouldn't need AN for that. A particle emitter and some gravity would do the trick.

**Comment by JacquesLucke** [comment]
right, thx

**Comment by antonvdh** [comment]
Sounds easy but it is not that simple.

Op 14 feb. 2017 22:01 schreef "Jacques Lucke" <notifications@github.com>:
