### ISSUE TITLE
Issue with Bold Text

### ISSUE THREAD

**Issue by ricardoroehe** [JacquesLucke/animation_nodes#641]
When you use the Separate Text Object node with a Text object containing different Regular and Bold fonts (and possibly the same with Italic), the resulting characters have alignment problems.

Also, the resulting characters are not inheriting the original style (bold, italic).

[AN_Text_Bug.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/628040/AN_Text_Bug.blend.zip)

![bold1](https://cloud.githubusercontent.com/assets/9118434/20847818/be9cc9ba-b8b6-11e6-9f2b-fca0669a76c2.jpg)

![bold2](https://cloud.githubusercontent.com/assets/9118434/20847819/bebcd2dc-b8b6-11e6-896c-da4c1e33e69d.jpg)

**Comment by JacquesLucke** [comment]
Thanks for the report! That should definitly be fixed if possible. I think I did not know that this is even possible when I developed this node more than a year ago ;D
Will do it when I have more time again :)

**Comment by ricardoroehe** [comment]
A simple workaround for the style would be to manually set the "OBJ.data.body_format[index]" properties:

```
use_bold = obj.data.body_format[index].use_bold
use_italic = obj.data.body_format[index].use_italic
use_underline = obj.data.body_format[index].use_underline
use_small_caps = obj.data.body_format[index].use_small_caps
```

Maybe simply create a "Character Properties **Input**" node for those properties?

Look how this apparently solves the alignment issues too.

![text_bug_wa](https://cloud.githubusercontent.com/assets/9118434/20883415/32045dc4-bacd-11e6-956b-7d1038477083.jpg)

**Comment by ricardoroehe** [comment]
#645

**Comment by JacquesLucke** [comment]
Should be fixed now, please test it again.
