### ISSUE TITLE
[Feature Request] Preserve Selection Order for Get Selected Objects node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#646]
In some cases, the selection order is expected to be preserved, just like what the *From Selection* button does for Create Object List node. Thanks!

**Comment by JacquesLucke** [comment]
Should be possible. For what do you want to use this? Remember, the node is disabled during rendering.

**Comment by LeonCheung** [comment]
I know. just tried to link the output to a loop, to preview the animation, in which case, order matters a bit.

BTW, long time no see! missing you a bit :D

**Comment by JacquesLucke** [comment]
ok, I see. I'll implement it soon.

Haha thanks, I miss working here as well, unfortunately I still don't have much time.. I do have holidays atm for 2 weeks but have to do even more homework for university.. Not sure how much time I'll have to work on AN and Blender in general in the upcoming weeks :/

**Comment by LeonCheung** [comment]
Great!

Ah it makes sense then. No hurry, I believe your Blender day will finally come.  :)

At this right moment, the request here just lead us to another idea: Maybe it can be cool to set the selection order ID as a new type of ID Key?

For example, after selecting object A, then B, then C then D, and clicking on some magic button in ID Keys panel, orders can be recorded as 0 1 2 3 respectively , similar to initial transforms data. 

Well this kind of ID can be useful to, for example, replace the index in the loop subprogram for making sequenced animation. After all, creating object list from selection got its own limit (I guess that's basically why the Object from Group node was finally implemented? However group cannot preserve a controllable order simply by selection) I can foresee the potentials for this feature, Anway, just leave it here as a quick brainstorm.  that's another story.  :)

**Comment by JacquesLucke** [comment]
Preserving Selection Order in an ID Key is quite a good idea! Please feel free to create an extra issue for that :)

**Comment by JacquesLucke** [comment]
Well forget it, here is it:

![selection index](https://cloud.githubusercontent.com/assets/5881326/21959235/57f79834-dac1-11e6-9e98-fa6d08f41165.PNG)

**Comment by LeonCheung** [comment]
Oh my, that's exactly what I imagined! Actually by the end of last month I was about to make a detailed proposal to discuss the benefit of it,  was postponed due to the busy life. Now I can save that. You rocks again, Jacques! AN rocks. :dagger: 

Btw, although I think maybe more possible options like "Start from" and/or "Increment" option can be even nicer to see, however they can sort of be done by using extra math nodes.  :)

**Comment by JacquesLucke** [comment]
ah yes I see. I think I will abstract a bit from "Selection Index" to "Order Index". And maybe it should be a Float instead of Integer?

I'm now thinking of these additions:
- "Start From" setting
- "Increment" setting
- option to give objects that have been selected at the same time the same value

**Comment by LeonCheung** [comment]
Yes, order id makes a bit more sense here than selection id, considering the typical use of it. Hmm, I think integer would be ok here, floating will just make things a bit hard to "predict" results, (and can sometimes lead to imprecision issue?) so, unless other floating usages can be explored to make it a must-have, integer is just okay, imho. After all, it functions no fancy than a **Custom Index**?  (or AN Index? :P)

And actually I was thinking something more: Maybe it is possible that a single object can be assigned with more than one custom index? I mean some thing like this: when choosing  * Custom Index Set 1* from the Object ID Key node, it will use the particular index we set for that. When choosing * Custom Index Set 2*, it means we want to use another value to control the object for a list or loop. 

A more specific example would be: Use Custom Index Set 1 to control the location, and, at the same time, Use Custom Index Set 2 to control the Rotation / Scale, or even use other sets to control Cycles materials.

**Comment by JacquesLucke** [comment]
I'll change everything a little bit again. I will make it so that you can easily create more ID Keys yourself. Initial Transforms will still be there as default because it's the most important one, but other ID Keys can be added manually.
The backend for this is done for a while already, just the UI is not ready yet.

**Comment by JacquesLucke** [comment]
It is possible to create new ID Keys now:

![custom id keys](https://cloud.githubusercontent.com/assets/5881326/21965716/ce18e82a-db65-11e6-9889-26ef521688b9.PNG)

There is not really a way to remove them yet because that is a bit more difficult (and not all ID Keys can be deleted). The difficult thing with the ID Key system (which is the main reason why I redeveloped it multiple times) is that it has to be a distributed system. This means that there must not be a central place in the .blend file where all existing ID Keys are. This has several reasons:
- when appending objects from other files you want to be able to see the ID keys.
- when appending a node group from another file you want to have the ID Keys that this node tree uses in the Id Keys panel.

This is also the reason for the "Update" button. Pressing it triggers AN to check many places where ID Keys can occure to list them in the panel.
It might be useful to know that if you create an ID Key and don't use it, it will be gone after reloading the file (using it currently means that some object has a value in this key or there is an Object ID Key that uses the key).

**Comment by LeonCheung** [comment]
Just compiled and tried, it's cool enough. For deleting the properties created, before a better solution coming, I would turn to another addon you authored: Custom Property Editor, to be honest it helped me a lot in removing unused properties for huge amount of objects. However I can see the deletion issue you were talking about.

**Comment by JacquesLucke** [comment]
Haha cool, I did not remember this addon anymore to be honest ;D

I will implement deletion (and maybe renaming?) next weekend or a little bit later.

**Comment by LeonCheung** [comment]
Just a few quick notes on possible features related:

- Assign IDs for selected objects based on simple sorting rules like axis, names, etc. (a one-shot sorting can improve the performance a lot in many cases.)
- Use random values for ID assignment (with or without a range defined?).

**Comment by JacquesLucke** [comment]
Both things should be possible, I just have to find a good way to fit it all into the UI. Is sorting really a big performance issue in your setups?

**Comment by LeonCheung** [comment]
Sorry for late reply, just my busy days. :) As far as I tested on a simple setup for a scene with 2,500 objects, there seem to be a 7%-20% performance increase?

Possible Order ID Key (B) :
![post](https://cloud.githubusercontent.com/assets/494788/22974672/62a5c18c-f3be-11e6-8542-6bda86e4352d.png)

![ab](https://cloud.githubusercontent.com/assets/494788/22974932/9571b110-f3bf-11e6-9123-71a0a528aa96.png)

[example file](https://drive.google.com/file/d/0B1ojv5B6Lb-3R1dXTXdwdUZFVjQ/view?usp=sharing)

Besides, other concerns for the noded sorting method are:

- Performance issue when sorting things within subprograms (even nested ones);
- The concurrent order issue. about which I used to talk here or there. :). Currently, in order to generate a concurrent order for a list of objects, it seems I have to do things like below, and it's an everything-consuming thing (time, performance, maintainance...), To be specific, imho there should also be an option to allow assiging sharable ID. For example, objects that got the same X location could be assigned with the same ID(s). instead of unique one(s). If this can be done with the help of a pre-assignment mechanism, then maybe a boring setup (like below) can be saved sacredly:

![concurrent](https://cloud.githubusercontent.com/assets/494788/22976316/3fef34e6-f3c5-11e6-8497-d38d6c6883ab.png)

**Comment by JacquesLucke** [comment]
Yes that is right. ID Keys are a generalisation of Group ID and Initial Transforms in Motion Tool.

**Comment by JacquesLucke** [comment]
I've just implemented ID Key removal. There is now this little X icon which will only show if this specific ID Key can be removed. An ID Key is not removable in two cases (currently):
1. I is a default ID Key (only Initial Transforms atm)
2. There is an Object ID Key that uses this key.

Removing an ID Key means that it will be removed from all objects in the file.

![id key removal](https://cloud.githubusercontent.com/assets/5881326/24149637/7971bb4c-0e43-11e7-930e-a9a35af16904.PNG)

**Comment by LeonCheung** [comment]
Hmm, I met utf-8 problem with the name:
![utf-8](https://cloud.githubusercontent.com/assets/494788/24197999/ed6a13d6-0f3e-11e7-8519-7ca1e1a713f0.png)

**Comment by JacquesLucke** [comment]
hmm, can't really figure out if I can do something non-hacky to fix this. Seems to be a Blender issue. Did you ever have a Search Box in which this worked?

**Comment by LeonCheung** [comment]
Yes, the error message popped up while trying to select it via drop down box.
![searchbox](https://cloud.githubusercontent.com/assets/494788/24201628/985e3d2e-0f4b-11e7-8ee5-5b38d9b1f872.png)

**Comment by JacquesLucke** [comment]
Yeah, I know it shows up in the UI here as well, but for some reason I can't access the value in the code that runs when you clicked on it.

**Comment by LeonCheung** [comment]
Sure, not that critical anyway, will keep that in mind myself.

**Comment by JacquesLucke** [comment]
I managed to develop a simple fix, not totally nice but it does it's job well enouph.
Also note that you can always write the name manually in the advanced settings of this node.

**Comment by LeonCheung** [comment]
Oh my, just tested, cool and convenient. :+1:

**Comment by JacquesLucke** [comment]
Cool, I guess we can close this issue for now? ID Keys seem to be good enouph for the next release

**Comment by LeonCheung** [comment]
Hmm, Maybe I've tried to cover so many things here, like the **Start from**. **Increment**, Option to give objects that have been selected at the same time the same value (**Shareable ID**), **Assign IDs by Simple Sorting**..... which made this report long enough to follow. Maybe we will get chance to open new topics for that. So yeah, Let's close it. And appreciate again for all neat features you've done! :)

**Comment by JacquesLucke** [comment]
Yeah, please open a new issue for that. Would be much easier than trying to find the information here.
