### ISSUE TITLE
Use modifiers for mesh and spline object input.

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#648]
When using spline as input, it should be possible to get the modified result, for example if spline is deformed using hooks. The same would be good for mesh if displacement or other modifiers are used.
Now it's not possible and that is very limiting.

![screenshot 5](https://cloud.githubusercontent.com/assets/17803543/21630201/bdb0d876-d237-11e6-8bbd-6b1287d4c623.jpg)

**Comment by JacquesLucke** [comment]
I have some bad and some good news. 
Bad news first: I did not found a way to get the modified curve yet.
The good thing ist that I found that it is possible to extend the Mesh Object Data node to archieve something similiar. Blender has a function to convert all kinds of object types into a mesh (including curves, font objects, metaballs and nurbs). In fact I'm using this function for a long time already for mesh objects, I just did not know that it is possible to execute it on different object types.

Another problem with curve modifiers is, that some modifiers convert it into a mesh.

You can test the modified Object Mesh Data node by changing this line: https://github.com/JacquesLucke/animation_nodes/blob/master/nodes/mesh/object_mesh_data.py#L30
to ``yield "if getattr(object, 'type', '') in ('MESH', 'CURVE', 'SURFACE', 'FONT','META'):"``

Then restart Blender and create the node. Make sure that "Use Modifiers" is enabled when you want to test other object types.

![object mesh data metaball](https://cloud.githubusercontent.com/assets/5881326/21955446/a266a60e-da6b-11e6-8880-4149af1aa652.PNG)

Also note that this is not super efficient but it might still be very useful in some cases! I just did some tests so far but I'm confident that I can update the Object Mesh Data node soon. (The change will be in the Cython branch then).

**Comment by JacquesLucke** [comment]
This is how I like it: more functionality, less code haha

**Comment by karlisstigis** [comment]
Hi, I only now got time to test it out and somehow it doesn't work for me. It says there is an error.
![screenshot 9](https://cloud.githubusercontent.com/assets/17803543/22915344/42c3ebae-f27f-11e6-9e63-a54b760d4809.jpg)

**Comment by JacquesLucke** [comment]
Oh sry, my fault, I forgot to update the build on graphicall.org 

Here is the new build: http://graphicall.org/1202
I hope it works now.

**Comment by karlisstigis** [comment]
Yes, it works now! Will test it even more, thanks!

**Comment by JacquesLucke** [comment]
great. I'll close this for now. Just create another issue when you find a bug or so.

**Comment by OmarEmaraDev** [comment]
It is now possible to apply spline modifiers in 7328e0b.
