### ISSUE TITLE
Not downloading Zip for animation nodes

### ISSUE THREAD

**Issue by dltv** [JacquesLucke/animation_nodes#650]
Hello Jacques, 
I am super excited to experiment with your addon. I have tried several times to download, but it gives me a server error. It may be my problem(user error). I wanted to reach out and find out if there was an alternative download method. 
Thanks, 
David Leonard

**Comment by JacquesLucke** [comment]
It would be helpful if you provide the following things:
- your operating system
- which version did you try to download
- what is the error message

**Comment by dltv** [comment]
Thanks for the quick response. I restarted. It was a github issue. downloaded. I am starting now.
I appreciated the work on the addon. 
Happy Blending. 
Best, 
David

**Comment by JacquesLucke** [comment]
ok, thanks for the report anyway.
