### ISSUE TITLE
Calculate node tree before rendering animation

### ISSUE THREAD

**Issue by Norrolith** [JacquesLucke/animation_nodes#651]
Minor gripe here, but I have noticed that if I do not have 'always' evualuation turned on, then I can sometimes render desynchronised scenes, as I will press render animation, and it will render the first frame. The next frame has frame changed triggered and looks alright.

This is a minor gripe for me, I just re render the offending frame. But this could waste a lot of time on someone's renderfarm, if every machines first frame has to be redone.
So, when an animation is set to render, could AN update right before?

Example:
![0104](https://cloud.githubusercontent.com/assets/9922379/22378787/53d16a2c-e47c-11e6-9aac-1bc1601064bb.png)
The particle animation is on the right frame, whereas the animation nodes connections are on another frame.

**Comment by JacquesLucke** [comment]
This should not happen normally. Therr is one reason why this can happen in your case.

Do you only use AN? Do you have more than one node network (maybe they execute in an unexpected order)?  Basically, can I see how you made the effect?
If that is alright, I'll investigate further.

**Comment by Norrolith** [comment]
Here is the blend file.
[AN_particle_multi_mesh.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/737031/AN_particle_multi_mesh.blend.zip)
I have only AN, HardOps and some default blender addons enabled.
Also looking at the renders, it seems the frames also go out of sync by one a chunk of the time.
(a normal frame)
![0081](https://cloud.githubusercontent.com/assets/9922379/22398369/b46f3b5e-e54c-11e6-956b-aac949548ac6.png)
The preceding frame, note how the orbs are not centered on the junctions.
![0082](https://cloud.githubusercontent.com/assets/9922379/22398366/a20b15d2-e54c-11e6-98a9-6bdbcb2c2e50.png)

**Comment by JacquesLucke** [comment]
thanks! I see the problem now! Not sure what causes it so far, Another problem I noticed is that on each frame update the node tree is evaluated twice, not sure if this is a Blender bug. I will try to find solutions for these problems.
In the meantime you can just start rendering the animation while you are viewing at the first frame of the animation..

**Comment by LeonCheung** [comment]
I also experienced such  desynchronised thing when rendering animation, in some complex setup. I first thought that it might be something about the custom properties generated, but it still occurs after removing the *hops* property from all objects in this file (btw, a bit curious about why they exist). So I guess this coule be a update-missing issue when rendering animation.

My current workround is to  force updating by adding a trigger, e.g. in this scene, you can use field.002 as a trigger object. It works somehow, but definitely not a one-go cure.

**Comment by LeonCheung** [comment]
Just noticed: It seems that a more better workround is to first go to the start render frame, then press *Execute Node Tree* button, then render the animation, which works for me. FYI.

**Comment by JacquesLucke** [comment]
It should work now, at least it does for me..
The file crashed some times when I tried to render it. Often it helps to enable the "Lock UI" option in the Render panel.

This is not the best solution possible but it should work in all cases. The problem is that it is not really possible to decide with absolute accuracy wether the node tree should update or not when an event happens. There is always a trade off between "make sure it executes every time is has to execute" and "it should not execute more often than needed".
