### ISSUE TITLE
Cant install 1.7.3 cython branch

### ISSUE THREAD

**Issue by atoav** [JacquesLucke/animation_nodes#653]
I got the 1.7.3 Cython branch for Windows [from graphicall.org](http://graphicall.org/1202). When I tried to install it the usual way I was greated with [this message.](https://i.imgur.com/Rm0qIOO.png)

I then removed all versions of the plugin, restarted blender and installed only 1.7.3, the message reappeard despite everything I tried. I uninstalled everything again and installed the current master branch from github and it worked like a charm.

I'd really love to try the new text features for a project I am working on, is this a known issue?

**Comment by JacquesLucke** [comment]
Hmm I'm not sure why that happens. Can you show me a picture of your addon folder? (the folder that contains the "animation_nodes" folder)

**Comment by atoav** [comment]
Sure. This is a `tree -L 1` of `c/Program Files/Blender Foundation/Blender/2.78/scripts/addons`:
`.                                                               
├── add_curve_extra_objects                                     
├── add_curve_ivygen.py                                         
├── add_curve_sapling                                           
├── add_mesh_ant_landscape.py                                   
├── add_mesh_BoltFactory                                        
├── add_mesh_extra_objects                                      
├── animation_add_corrective_shape_key.py                       
├── animation_animall.py                                        
├── archimesh                                                   
├── blender_id                                                  
├── bone_selection_sets.py                                      
├── curve_simplify.py                                           
├── cycles                                                      
├── development_api_navigator.py                                
├── development_icon_get.py                                     
├── game_engine_publishing.py                                   
├── game_engine_save_as_runtime.py                              
├── io_anim_acclaim                                             
├── io_anim_bvh                                                 
├── io_anim_c3d                                                 
├── io_anim_camera.py                                           
├── io_anim_nuke_chan                                           
├── io_blend_utils                                              
├── io_coat3D                                                   
├── io_convert_image_to_mesh_img                                
├── io_curve_svg                                                
├── io_export_after_effects.py                                  
├── io_export_dxf                                               
├── io_export_pc2.py                                            
├── io_export_unreal_psk_psa.py                                 
├── io_import_dxf                                               
├── io_import_gimp_image_to_scene.py                            
├── io_import_images_as_planes.py                               
├── io_import_scene_lwo.py                                      
├── io_import_scene_unreal_psa_psk.py                           
├── io_mesh_pdb                                                 
├── io_mesh_ply                                                 
├── io_mesh_raw                                                 
├── io_mesh_stl                                                 
├── io_mesh_uv_layout                                           
├── io_online_sketchfab                                         
├── io_scene_3ds                                                
├── io_scene_fbx                                                
├── io_scene_ms3d                                               
├── io_scene_obj                                                
├── io_scene_vrml2                                              
├── io_scene_x                                                  
├── io_scene_x3d                                                
├── io_sequencer_edl                                            
├── io_shape_mdd                                                
├── light_field_tools                                           
├── materials_utils                                             
├── measureit                                                   
├── mesh_bsurfaces.py                                           
├── mesh_carver.py                                              
├── mesh_custom_normals_tools.py                                
├── mesh_f2.py                                                  
├── mesh_inset                                                  
├── mesh_looptools.py                                           
├── mesh_relax.py                                               
├── mesh_tiny_cad                                               
├── mocap                                                       
├── modules                                                     
├── netrender                                                   
├── node_wrangler.py                                            
├── object_add_chain.py                                         
├── object_animrenderbake.py                                    
├── object_boolean_tools.py                                     
├── object_cloud_gen.py                                         
├── object_edit_linked.py                                       
├── object_fracture                                             
├── object_fracture_cell                                        
├── object_grease_scatter.py                                    
├── object_print3d_utils                                        
├── oscurart_tools                                              
├── paint_palette.py                                            
├── pie_menus_official                                          
├── presets                                                     
├── __pycache__                                                 
├── render_auto_tile_size.py                                    
├── render_copy_settings                                        
├── render_freestyle_svg.py                                     
├── render_povray                                               
├── rigify                                                      
├── space_view3d_3d_navigation.py                               
├── space_view3d_copy_attributes.py                             
├── space_view3d_math_vis                                       
├── space_view3d_modifier_tools.py                              
├── space_view3d_pie_menus                                      
├── space_view3d_spacebar_menu.py                               
├── system_blend_info.py                                        
├── system_demo_mode                                            
├── system_property_chart.py                                    
├── ui_layer_manager.py                                         
├── ui_translate                                                
├── uv_bake_texture_to_vcols.py                                 
└── uv_texture_atlas.py                                         `

**Comment by JacquesLucke** [comment]
Thanks! However, unfortunately this was the wrong folder ;D My fault.

Blender has two addon folders. One for all the addons that Blender includes by default and another one for the addons you install yourself.

The path to the other folder should look something like this:
C:\Users\Jacques Lucke\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons

**Comment by atoav** [comment]
My bad, I didn't knew about that folder! There are definitly multiple versions there. I will delete them and then try again : )

```
.
├── animation_nodes  
├── animation_nodes-cython  
├── animation_nodes-master  
├── __pycache__  
└── space_view3d_screencast_keys.py
```

**Comment by JacquesLucke** [comment]
Cool :)

No problem, feel free to tell me your experiences with that new text stuff and show some results.
