### ISSUE TITLE
Feature request: Different interpolations for each element of the Animate Vector Node

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#654]
This could work also for the animate Euler node. The idea is to have a finer control over the animation and be able  to create more fine tuned animations.

So therefore three interpolation sockets instead of one, maybe this could be something to make it switchable.

**Comment by YorsLosilla** [comment]
I have look at the code to see if I can make this by my own. But it seems that you use one single file to create all the animate nodes, which are not in the animate folder.

From what I´ve see I´m unable to code this feature.

**Comment by JacquesLucke** [comment]
Why 3 interpolations? For each channel (x,y,z) one or what do you mean?
Not sure if this will make it into AN. For now you can make a group that does the same thing with 3 individual Animate nodes.

**Comment by YorsLosilla** [comment]
Yeah. I do this very oftenly. However as long as this is a very common operation in Mograph and animation in general I thought that it will be really usefulll to have it out of the box.

**Comment by JacquesLucke** [comment]
Oh ok, can you provide an example where you use this in practice?
It will definitly not be the default mode of the Animation nodes to have multiple interpolation inputs, but maybe we can have this as an option :)

**Comment by YorsLosilla** [comment]
https://www.youtube.com/watch?v=jHCyYOE-5Ss&feature=youtu.be


If you take a look this video you´ll see that animation on Z is different than the animation in X, Y.

This type of effects can only be achieved separating interpolations.

**Comment by JacquesLucke** [comment]
I can't watch the video, is it set to private?

**Comment by LeonCheung** [comment]
Typically like [this](https://www.youtube.com/watch?v=LoR2k3B0ifk) for example?

**Comment by YorsLosilla** [comment]
Now the video should work
