### ISSUE TITLE
[Solved] I cant install AN on Ubuntu 14

### ISSUE THREAD

**Issue by svnserendipity** [JacquesLucke/animation_nodes#655]
Hello, just want to let you know that I cant install AN on my Ubuntu 14 laptop. I already have blender 2.78 and still receive this error message.
![screenshot from 2017-02-21 21 42 40](https://cloud.githubusercontent.com/assets/25715052/23167510/ac611c52-f87f-11e6-84fd-4eff353b1af4.png)

Please help me, cos I want to learn more. Thank you!

**Comment by JacquesLucke** [comment]
ok thx for the report. That is really strange, someone else reported the same error for an official Blender version for windows lately..
Where did you download your build? Can you give me a link?

Also can you try if this command works without errors? Blender should normally come with "numpy" included, not sure why it is not in these builds..

![import numpy](https://cloud.githubusercontent.com/assets/5881326/23167848/4697d2dc-f846-11e6-8e2e-6c1561ed3a40.PNG)

**Comment by svnserendipity** [comment]
@JacquesLucke I install my blender from ppa:thomas-schiex. I import numpy
and get another error message.


​
​

**Comment by oktomus** [comment]
I had the same error and fixed it by installing numpy myself out of blender 
`pip install numpy`
If you can import numpy out of blender, it will work for sure. 
@svnserendipity

**Comment by svnserendipity** [comment]
@oktomus Its already solved. I had to install blender from the official site and problem solved :)
