### ISSUE TITLE
Provide export of animation setup as python classes and/or scripts

### ISSUE THREAD

**Issue by anuprao** [JacquesLucke/animation_nodes#663]
It will be a boon for _Motion Designers_ if it were possible to export the **Animation Node Tree** and underlying nodes as Python classes and/or scripts. Once these scripts are exported, they could be incorporated into other Python programs to duplicate the effect. This would lift a major burden on duplicating animation within applications or games. The export itself may not necessarily be stand alone, but detailed just enough to permit reuse.

_Of course, I am suggesting **Python** as it would be a good reference point to start with. Other languages could follow based on the Python template._

**Comment by JacquesLucke** [comment]
Thanks for the suggestion. I actually thought about that for a long time and came to the conclusion that (although it would be very useful!) it is not really possible. AN is just not designed for that. It does generate Python code in the background but it still depends on the addon being installed and running inside of Blender.
Also AN is heavily based on Python (eg with the expression and script nodes) and Python features. And with the advent of Cython in the next release, it will be even harder to create standalone modules based on node trees.

So it is unlikely that you will ever be able to export standalone code from an AN tree. However, I want to create a better template system that makes it easier to share node networks.
