### ISSUE TITLE
A Question on Convert Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#664]
Just wonder if this is one of the reasons why Parse Number node exists. Can Convert node make any sense by being used simply like this?
![parse](https://cloud.githubusercontent.com/assets/494788/23909623/342bef70-0912-11e7-8092-10bc7a1d214f.png)

**Comment by JacquesLucke** [comment]
There is no clear way how strings can be converted into booleans. This is why you should be more specific in this case (using the Parse Number node).
Otherwise AN just calls ``bool(value)`` which will return true when ``value`` is a string with at least one character,

**Comment by LeonCheung** [comment]
Right. Thanks.
