### ISSUE TITLE
Different behavior between 1.6.1 and 1.7.5 (Debug Drawer)

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#669]
For Debug Drawer node, is this a behavior by design for 1.7.x ? I mean display a single text element as a list.

![t](https://cloud.githubusercontent.com/assets/494788/24101331/d77644c4-0db2-11e7-88db-7bd9e2081a62.png)

**Comment by JacquesLucke** [comment]
no it is not, thanks for the report
