### ISSUE TITLE
Failed updating in VSE

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#670]
When trying to use a scene strip which contains text objects updated by AN, it failed to update to VSE by AN.

![6](https://cloud.githubusercontent.com/assets/494788/24155682/771328a8-0e8f-11e7-9464-80ed9be70477.gif)

It not only occurs in 1.7.x, but also in 1.6 and 1.5.

**Comment by JacquesLucke** [comment]
I never used scene strips in the VSE but it looks like Blender caches the rendered viewport for every frame. So when you change the scene the preview in the VSE shows not what is in the viewport, AN does not seem to be the reason for this. Once you hit Refresh Sequencer the cache is removed and every frame is rerendered and cached again.

**Comment by LeonCheung** [comment]
I just figured out that it has something to do with the start frame, when I set a start frame value other than 1, the scene strip needs a offset. Sitll wondering why and how to fix it in my setup, but you are right, it should not be an AN problem. Close it for now. Thanks.

**Comment by LeonCheung** [comment]
Solution is simple, just make the two properties here synced:
![startframe](https://cloud.githubusercontent.com/assets/494788/24206268/a8df5ea0-0f58-11e7-9104-602324af857e.png)
