### ISSUE TITLE
[Feature Request] "Start from" Option for ID Key Assignment

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#672]
**Start From** (or **Offset**?) for integer and/or float ID can be particularly useful while assigning IDs for large amount of objects.

**Comment by JacquesLucke** [comment]
This is only for the "From Selection Index" option, right?

**Comment by LeonCheung** [comment]
Agree on that.

**Comment by LeonCheung** [comment]
A bit off topic: A perfect example to show the advantage of From Selection Order feature, yes? Which can be very boring other wise. :stuck_out_tongue: 
![selection](https://cloud.githubusercontent.com/assets/494788/24209712/00795018-0f62-11e7-95f2-56b70abba189.gif)
