### ISSUE TITLE
Copy ID Key to selected objects

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#673]
I have not found a good place for that in the UI yet..

**Comment by LeonCheung** [comment]
Hmm, two years ago I posted something, #167 if it helps.

**Comment by LeonCheung** [comment]
My two cents for now:
![ee](https://cloud.githubusercontent.com/assets/494788/24208994/fe386b88-0f5f-11e7-86a5-ec5d0c330f20.jpg)

**Comment by JacquesLucke** [comment]
should there be a confirmation popup when clicking on the X?

**Comment by JacquesLucke** [comment]
Also how should it look like when the ID Key has not yet created for the object, just as it is now?

**Comment by LeonCheung** [comment]
I think there should be, since it is sort of a dangerous operation.
For a not-yet status, maybe replace x with +?

**Comment by JacquesLucke** [comment]
ah the plus icon is a good idea. Should the be text as well?

**Comment by LeonCheung** [comment]
Isn't that obvious enough? LOL. Or add as tip message when hovering cursor on them?

**Comment by JacquesLucke** [comment]
alright, will implement that later today

**Comment by LeonCheung** [comment]
Of course it will be okay if you think there are still enough place for it.

:zzz: see you then.
