### ISSUE TITLE
Auto Execution

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#674]
An interesting behavior:
![exe](https://cloud.githubusercontent.com/assets/494788/24233233/daa22a26-0fcb-11e7-991b-d0d38d4e1123.gif)

I don't think I've ever played animation there, so there should be no frame changed, but why AN kept executing here?

--
Update:   I just found it happens while VSE area is displayed on screen.

**Comment by JacquesLucke** [comment]
Hm, I think I can't change it. The reason for this behaviour seems to be how Blenders update system works..
