### ISSUE TITLE
[Feature Request] Order ID Assignment by Simple Sorting

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#676]
I think this is the last but not least useful feature to current ID Key system.

Possible sorting types would be:

- by Axis, (like what Motion Tool does) and it should allow calculating based on either object origin or bounding box center;
- by Distance to Object;
- by assigning Random ID;
- by Object Name (alphabetical order).

For the first two types, with a possible **threshold** parameter, it can well solve the concurrency order (shareable ID) problem I suppose, the importance of which, I've been trying to discuss for times. :)  Basically it can be particularly useful for things like architecture construction animation, etc,  in which, usually, large amount of objects are involved. (sometimes you want to animate something all together, instead of one after another)

You've been asking me about the performance difference beween pre-sorting and in-node sorting, I tried to do some tests and posted the result at #646 , hope it helps for the final decision making.
 
BTW, I know we got new Falloff ways, which can also achieve that somehow, but I still think that assigning by simple pre-sorting can be faster, more convenient, and even can work together with Falloff nodes (e.g. as offsets data for Delay Falloff). It has its own advantages.

**Comment by JacquesLucke** [comment]
I see that this is useful, and yes it works quite well together with falloffs.
How would you do the UI for this? I don't want to make a button for each of these cases.

Should "From Selection Order" stay where it is now or should there just be one more generic button "From ..." (don't know what to put there yet). Clicking on the button could open a menu in which you can choose the specific sorting-mode and settings.

**Comment by LeonCheung** [comment]
Maybe like this?
![mockup1](https://cloud.githubusercontent.com/assets/494788/24295151/68b7c24a-10d4-11e7-82fb-7acf5c6d4309.png)

Icon option 2:
![mockup2](https://cloud.githubusercontent.com/assets/494788/24295153/68bab112-10d4-11e7-8fa6-cefc0f0c6fdc.png)

Icon option 3:
![mockup3](https://cloud.githubusercontent.com/assets/494788/24295152/68b8c9c4-10d4-11e7-940e-6e0f5eae615b.png)

**Comment by LeonCheung** [comment]
V2:
![mockup5](https://cloud.githubusercontent.com/assets/494788/24295467/cce6efec-10d5-11e7-8272-567fdf75d038.png)

**Comment by JacquesLucke** [comment]
I guess the V2 is better because it is more scalable when we get more parameters over time. Like you did not use the threshold attribute you proposed yet.

**Comment by LeonCheung** [comment]
1 sec, v3 coming.

**Comment by LeonCheung** [comment]
Considering the threshold (or step size?):
![mockup6](https://cloud.githubusercontent.com/assets/494788/24295752/3a5fa05e-10d7-11e7-9ac5-cc8dac23d8ca.png)

**Comment by JacquesLucke** [comment]
Threshold for Selection Order? Does that make sense?

I think I still prefer V2.

**Comment by LeonCheung** [comment]
Hmm, then I don't know where should the Threshold guy sit...

**Comment by JacquesLucke** [comment]
Maybe just put it into the menu that opens when you press the little settings button?
Placing settings directly in the panel is not a good idea.. You always have to think about how to change it when we get more settings in the future (which we can't imagine yet). Therefor I think it is better to only of the enum property, the assign button and the settings button in the panel.

**Comment by LeonCheung** [comment]
I believe you are sure about how to handle the rest of it. :)

**Comment by JacquesLucke** [comment]
yep. Thanks.

**Comment by LeonCheung** [comment]
Just want to emphasize a bit on the option to choose between Origin or Bounding Box Center when sorting by Axis or Distance. Because the object location can be sometimes undesirable or even useless. e.g. imagine when multiple objects are sharing a same location. Like below:

![2](https://cloud.githubusercontent.com/assets/494788/24297266/1f2326f2-10dd-11e7-95ee-4df4e9a72984.png)

**Comment by JacquesLucke** [comment]
Yes I understand, should not be too hard to implement both options. More options are also possible, I'll leave that open to extend in the future.

**Comment by LeonCheung** [comment]
Hah, cool!

**Comment by JacquesLucke** [comment]
Here you go. All modes you proposed should work now. It's not the prettiest menu but it does its job :)
Have fun testing :D

![id key sort modes](https://cloud.githubusercontent.com/assets/5881326/24310938/297ae672-10d2-11e7-8b75-58539285a4ff.PNG)

**Comment by LeonCheung** [comment]
It looks amazing! Just compiled, it seems the Output sockets are gone?
![mockup1](https://cloud.githubusercontent.com/assets/494788/24318818/f3dcc6b4-1146-11e7-97f1-db085e12f820.png)

**Comment by JacquesLucke** [comment]
oops, looks like I did something wrong, will fix soon!

**Comment by JacquesLucke** [comment]
should be fixed now.
What do you think, should we have a default ID Key for "Order Index"/"ID"/... ? (similar to Initial Transforms)
If many people use it, it would make it easier to share files/objects.

**Comment by LeonCheung** [comment]
Worked!

New issue: Bounding Box Center not working well with non-zero threshold value.

And yes, a default order id can be nice if the usage frequency can be foreseen. About the name, maby call it **Initial Order Index** or **Initial ID**?

**Comment by JacquesLucke** [comment]
Do you have an example where bound box center does not work?

Hmm, I think "Initial" should not be part of the name. It does not really make sense in this context, right?

**Comment by LeonCheung** [comment]
Okay try [this](http://pasteall.org/blend/index.php?id=46057).

It is basically the object index used in AN (same as the Blender's object index, just exist in a multiverse :P). So, maybe call it AN Object ID, AN Index, or Object ID, or just simply.... ID?

**Comment by JacquesLucke** [comment]
The bounding box center method should be fixed now. Thanks for the file, that was helpful. Apparently I tested to few cases.

Ok thanks, I will make a decision a bit later.

**Comment by LeonCheung** [comment]
Now it works perfect. Thanks for bringing possibilities to life! :1st_place_medal:
