### ISSUE TITLE
Suggestion: Hide relationship lines for Separate Text Object node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#682]
The title simply tells everything. (similar to instancer node, as an advanced setting maybe?)

**Comment by JacquesLucke** [comment]
yes will do when I'm back home. Now I have to destroy and rebuild a wall in my new home haha.

**Comment by LeonCheung** [comment]
Uh.....good luck.....

**Comment by JacquesLucke** [comment]
Thanks :)
