### ISSUE TITLE
1.7.5: Index Assignment for Separate Text Object Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#686]
Shall we?
![default](https://cloud.githubusercontent.com/assets/494788/24954436/fe3737c4-1fb1-11e7-9dd8-b7a637b21bbe.png)

**Comment by JacquesLucke** [comment]
Yes I guess this makes sense, thanks for the suggestion

**Comment by LeonCheung** [comment]
Yeah, though workarounds can be used instead, just concerning about the performance cost:

![performance](https://cloud.githubusercontent.com/assets/494788/24961403/3a6c4a4a-1fcb-11e7-9a64-7b455af1af68.png)

**Comment by JacquesLucke** [comment]
well the object id key node does nothing in your case as the output is not connected. It will be slower when you connect it to something.
The Float Range node has pretty good performance, not sure if anything can top it.

The benefit will be more that the information is stored in the object which will make it easier when you combine multiple object lists.

**Comment by LeonCheung** [comment]
Ah, you are right about the performance talk. Then concern cancelled.  :)
