### ISSUE TITLE
List remove -> Polygon Indices bug

### ISSUE THREAD

**Issue by taserflanger** [JacquesLucke/animation_nodes#689]
Hi Jacques,

I am using a cython version of Animation Nodes (version 1.7.5).
When I try to remove a list element from a polygon indices list using basic nodes like object mesh data and remove list element (by index), it shows up an error (red border).

Here is a link of the question on BSE, is this a real issue in the an?

**Comment by JacquesLucke** [comment]
yes this is an issue in AN, thanks for the report. Looks like I forgot to implement this.

**Comment by taserflanger** [comment]
You are welcome!

**Comment by JacquesLucke** [comment]
Fixed it, thanks again :)
