### ISSUE TITLE
[Featue Request] IDkey to Object Pass Index

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#693]
It would be cool to have an option (a checkbox maybe?) to also assign ID key (integer) as object pass index, hoping it might not be that hard to implement. :)

**Comment by JacquesLucke** [comment]
The feature should work now.

I implemented similar features for Text and Transforms Id Keys as well. Should be easy to extend this now.

**Comment by LeonCheung** [comment]
Cool! Will try it out! Thanks!
