### ISSUE TITLE
Implement object groups triggers with multiple ID properties per trigger.

### ISSUE THREAD

**Issue by OmarSquircleArt** [JacquesLucke/animation_nodes#697]
Currently, if one were to add triggers for multiple object, he would have to add them manually. Instead, I propose that the user can just group the required objects and add this group as a trigger.

Also, each trigger allow only 1 property to watch over. Instead, I suggest user be able to enter multiple IDs per trigger separated by commas.

**Comment by OmarSquircleArt** [comment]
Implemented in a945cf7.

**Comment by OmarSquircleArt** [comment]
Finally! Thanks!

**Comment by OmarSquircleArt** [comment]
Glad I could help, should we close this then?

**Comment by OmarSquircleArt** [comment]
Yah sure.

**Comment by JacquesLucke** [comment]
That conversation was weird ^^

**Comment by Clockmender** [comment]
Sometimes the only way you hear sense is if you talk to yourself... 🥇

Cheers!

**Comment by OmarSquircleArt** [comment]
haha, never though someone would see this :smile: .

**Comment by JacquesLucke** [comment]
I got 4 mails, it's hard not to see those :p

**Comment by OmarSquircleArt** [comment]
Ah sorry, I though only those subscribed to the issue got those emails. :smile:

**Comment by Clockmender** [comment]
^^ If only that were true..... You never know who's watching you :-)
