### ISSUE TITLE
[Suggestion] Pie Menu: Better Data Input Creation for Some Datatypes

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#699]
Currently there are a few datatypes that can be optimized with better data input creation via pie menu:

![nodes](https://cloud.githubusercontent.com/assets/494788/25576001/62a1ba3c-2e8e-11e7-841d-d7049878f1ef.png)

**Comment by JacquesLucke** [comment]
I agree with the last three options but I'm not sure about the compose matrix node as it is very huge and often not all these options are needed.

I just got the idea that we could join the Translation/Rotation/Scale Matrix in one node (Compose Matrix). Not sure if it is a good idea though, so what do you think?

(there could be toggles similar to the one I use in the Offset Matrices node)

**Comment by LeonCheung** [comment]
You mean like those little X Y Z button on the latest Transforms Output node? Could be nice. However, it's just more meaningless by creating a matrix input node without any input allowed in that way, that's why I suggest a more meaningful one, the Compose Matix node, since things like this has been done for Vector / Euler etc.

**Comment by JacquesLucke** [comment]
no, just Loc/Rot/Scale buttons, similar to how I did it in the Offset Matrices node

**Comment by LeonCheung** [comment]
Not a bad idea. :)

**Comment by JacquesLucke** [comment]
I inserted all your suggestions.
