### ISSUE TITLE
[1.7.x] Disconnect  Hair

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#701]
Just wonder if it should be like this when trying to disconnect hair:
![hair](https://cloud.githubusercontent.com/assets/494788/25662050/a4540be8-3045-11e7-9818-a934920dc25c.gif)

**Comment by JacquesLucke** [comment]
Oh thanks for the report. Never used this option. Will try to fix it when I'm back home :)

**Comment by JacquesLucke** [comment]
Hm I don't really understand what this Disconnect Hair operator does..

**Comment by LeonCheung** [comment]
This is an greate feature born in Blender 2.5 back to 2009 by Janne Karhu. Basically when you do something in Particle Edit mode, you can hardly keep everything on track by editing emitter meshes after that,, you know, such as subdividing, applying scales etc, which causes so much pain when you have to reedit the mesh after editing hairs. But with this feature, you can do it by first click Disconnect Hair (or Disconnect All) for one or all hair particle systems on the same mesh), then edit the mesh, then click the same button to connect, [FYI](https://www.youtube.com/watch?v=w9s-2v0SCFI).

**Comment by JacquesLucke** [comment]
Ah I understand, not really sure what causes this offset when you disconnect the hair. However it looks like the hair is always only disconnected for a relatively short amount of time. So it does not really matter if AN handles that case. Disconnected hair is only temporary anyway.

**Comment by LeonCheung** [comment]
I see, wierd anyway, since the particle didn't change during disconnection, while the splines not, so the background data did change. Hmm... Anyway as you said, just a temporary state that is harmless to the final result after reconnection. Feel free to close it if AN is innocent. :)
