### ISSUE TITLE
Min Node Width

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#702]
A not-so-critical problem occuring again:
![width](https://cloud.githubusercontent.com/assets/494788/25662310/ab799018-3046-11e7-9cbe-8d6b65228835.png)

**Comment by JacquesLucke** [comment]
hm weird, does not happen for me in the latest build from buildbot on linux.
I can't even make the node that thin..

**Comment by LeonCheung** [comment]
Oops, it seems I cross used master and cython build. It occurs when using master, while cyhon build works fine. Sorry for misreporting. :P
