### ISSUE TITLE
[Discussion] Hide Object option for Instancer

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#705]
Not sure about that, but it seems we often need to do something to hide source object after that. So maybe it is not bad to implement a little feature to it, like what is for Separate Text Object node? (I can see things are not really the same between the two nodes, that's why I call this a discussion insead of suggestion )

**Comment by JacquesLucke** [comment]
![bildschirmfoto vom 2017-05-26 23-34-00](https://cloud.githubusercontent.com/assets/5881326/26513461/d6fc3c18-426b-11e7-8726-347dccdeff54.png)

I made this an option in the socket. In theory this could be visible in every object socket but I think that would be a bad idea as it is not needed in most cases.

Is this what you imagined?

**Comment by LeonCheung** [comment]
Yes, basically it is. I'll be afk for a few days, cannot test it yet. If it controlls both the visibility and renderability, if everything will be back to their initial state whle renoving the node, then I think it is nice enough.

**Comment by JacquesLucke** [comment]
It does not control renderability (the same is true in the Separate Text Object node). This could be changed but I'm not sure if it should be changed.

Also the object does not come back when the node is deleted, that would be much more difficult.

Should I revert the commit for this reason?

**Comment by LeonCheung** [comment]
Haha, well, at least it is a button that needs a manual click to function, then I bet ppl would know the consequence behind it. I think it indeed is a fast way to clean up the viewport, but it would be better to also control the renderability, right? ( btw I remember Separate Text node does control the renderability while updating it, no?)
