### ISSUE TITLE
Interpolation vs Easing function

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes#707]
I just found that we could have a better (and more correct name) for the interpolation socket.
If you search for Interpolation and Easing separately you will see why it might be a good idea to change the name.

All files won't work in the 2.0 files anyway so this is not a reason not to rename the socket/nodes/menu/...

However before changing it I wanted to get some feedback.
Which name do you prefer?

**Comment by anadin** [comment]
Easing makes sense to me

**Comment by LeonCheung** [comment]
I think "interpolation" is an interesting word in blender, it appears to be generalized, while sometimes specialized:
![bl](https://cloud.githubusercontent.com/assets/494788/26106619/0084c514-3a79-11e7-8962-073265b0098b.png)

![ipo](https://cloud.githubusercontent.com/assets/494788/26106820/c65a4246-3a79-11e7-9c18-f599060cd0c7.png)

I think for most ppl "interpolation" can be okay, while "easing" might be more technically correct. It depends on the way in which you expect users to understand it.

BTW, where is Thomas Beck @plasmasolutions? Maybe he can share some ideas on this. AFAIIK, he is one of the contributors for bringing Robert Penner Easing Equations into blender anyway.

Another concern is how to rename those interpolation nodes, such as "Interpolation Viewer". Will it be called Easing Function Viewer in this case?

**Comment by JacquesLucke** [comment]
I guess every occurence of `Interpolation` should just be replaced with `Easing`
So the node would be called Easing Viewer...

**Comment by plasmasolutions** [comment]
Hi Leon & Jacques, yeah that's right I committed those equations together with Joshua. "Interpolation" is and was chosen, because you define how you interpolate between two and more keyframes. Imho this explanation (and name) ist therefore still valid.

Easing is a term that describes how one of the penner equations behaves before or after the keyframe.

If you rename your interpolation stuff into easing you strike out 3 functions from the equation: Constant, Linear and Bezier. If those are not available inside AnimationNodes, go ahead and rename them...

Best, Thomas

**Comment by JacquesLucke** [comment]
In AN a interpolation currently is just a function `f` that takes a real number from the interval `[0,1]` and outputs a arbitrary real number. Most interpolations have these two properties as well: `f(0)=0` and `f(1)=1`. This is not guaranteed though and often it is useful to have functions that don't have these properties.
AN 2.0 introduces a new node that will never output an interpolation where both properties are true: http://animation-nodes-manual.readthedocs.io/en/an2/user_guide/nodes/interpolation/mirror_interpolation.html

**Comment by plasmasolutions** [comment]
Then I would definitely vote for leaving it as is. It's an interpolation function (that is not specified nearer). But as you both are definitely more Animation Node savvy it's of course up to you ;)

**Comment by anadin** [comment]
Agreed with @plasmasolutions then it does seem to be more an interpolation.

**Comment by YorsLosilla** [comment]
What maybe will make more sense is to join the animation an interpolation categories.

**Comment by JacquesLucke** [comment]
Thanks for the feedback. The name will stay "Interpolation" now.

Yes, it would indeed make sense. The animation category itself is not very powerful atm. It's pretty basic and not very useful in most many cases. Maybe this will change in a future release. I'm planning a new socket type which will be called "Animation" (most likely, maybe I find a better name). This will likely take over the whole category. For that reason I don't want to extend the animation category in this release.
