### ISSUE TITLE
[2.0 beta] Maybe a serious bug?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#708]
Wierd things happening when trying to rename subprogram inputs:

![bug](https://cloud.githubusercontent.com/assets/494788/26088807/9429630e-3a2b-11e7-9441-fb5f8f8a15a1.gif)

**Comment by JacquesLucke** [comment]
that looks serious -.- but should be easy to fix later today.
thx for the report.

**Comment by JacquesLucke** [comment]
ok, was not as serious as a thought at first but still important to fix.

Please test this extensively now. There should not be a single weird value change when renaming the sockets.

**Comment by LeonCheung** [comment]
So far so good, seems being a nice fix.

**Comment by JacquesLucke** [comment]
ok, will close it for now.
