### ISSUE TITLE
Reading a single pixel from an image texture

### ISSUE THREAD

**Issue by unfa** [JacquesLucke/animation_nodes#709]
Is it possible to read RGBA values from a single pixel in an image texture? I don't need any interpolation, just put in a single pair of UV coordinates and get RGBA values from a loaded PNG image.

I'd like to be able to move, rotate and hide my objects based on contents of a texture.

For example - if pixel under UV [0.2, 0.7] of Image.png has Alpha value of 0 - **Cube1** should be visible. If that Alpha value is 1 - **Cube1** should be hidden, and the camera should be rotated and placed differently.

Possibly the easiest way would be to prepare some animation for objects in the scene and make each object jump to a specific keyframe, based on the colors of various pixels, however I sometimes need to make various combinations. For example Hide Cube1, but also rotate Cube2 by 180° in Global Z axis. And preparing animation frames for all possible combinations sounds like a very inefficient way of doing this.

What am I trying to use that for?

I'm working on a system that uses Blender to create 3D visuals from 2D designs, using pre-prepared 3D scenes and 2D templates with gaps to fill. The 2D template is then converted to PNG image that  is mapped onto objects to change colors and other material properties, add prints or laser engravings on objects. Now I'd like to make it possible to rotate and hide objects, but I need to get the input from textures.

I wonder if Animation Nodes can help me with this - if not, do you think reading pixels values form textures could be useful anyway? This way people could make animations driven by textures, which could be an interesting way to approach the topic.

**Comment by JacquesLucke** [comment]
There are no special nodes for this yet. Accessing images will be part of the new-color-system-project I will work on later this year.

You can use a script to access individual pixels but it is very slow. I plan to work on the Blender Python API myself a bit soon to speed this up.

**Comment by unfa** [comment]
Ok. Having a dedicated node for this purpose would make things a lot easier.

I guess it could also have options for interpolating between pixels.

As I would only need to perform this a couple of times per render, poor performance isn't a big deal in my use case. I don't need thousands of samples per second :)
