### ISSUE TITLE
Spline falloff doesn´t take into account curve modifiers

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#711]
Well the title is pretty descriptive. When you use that node if the curve has some spline modifiers the node doesn´t take into account.

This could be very usefull for some deformation effects. 

Also if the bevel factor could be taken into account for doing animation or some sort of restricition of the parts of the spline to be evaluated, like the evaluate node, will help to make dinamic animations.

The idea will be animate that displacement like a snake.

![image](https://cloud.githubusercontent.com/assets/12479570/26145620/5cf21ada-3aed-11e7-8211-b892a10ee297.png)

**Comment by JacquesLucke** [comment]
Just to clear up the common misconception. The thing that does not take the modifiers into account here is the Spline input socket and not the spline falloff node. I know it is weird at first but that the spline falloff node just takes the spline it gets from the socket. The socket is responsible for loading the spline into AN. Therefor you see the same thing everywhere you have a spline socket.

Now to the real problem: Blender does not (to my knowledge) allow scripts to get the result of curve modifiers in a way that is suitable for AN. The only possible way to see atm is that AN makes a copy of the curve object, applies all modifiers, hopes that the result is only a single spline, loads that spline into AN and removes the copied spline. This would have to happen on every recalculation. While the performance might be good enough when the spline is small, there are other problems when using this approach. Specifically it requires AN to use certain operators that should not be used during rendering.

I'll try to find another way to solve this problem.

Another approach would be to not use modifiers at all but do the things you want to do in AN. However, I know that for that some more nodes would be needed (eg to simulate the hook modifier).

**Comment by YorsLosilla** [comment]
![image](https://cloud.githubusercontent.com/assets/12479570/26147693/981051e8-3af4-11e7-9b48-ad3aa85d4176.png)

Yeah. I have found this workaround. It´s slow but does the work

**Comment by YorsLosilla** [comment]
The thing is that the node tree brokes when rendering....

Even with lock UI

**Comment by JacquesLucke** [comment]
Oh ok, can you send me the file?

What exactly do you mean with "broke"? Some more details on what really happens are always helpful.

**Comment by YorsLosilla** [comment]
https://drive.google.com/open?id=0B9SDRZRP7NzVeEtCdmdFNUlZWTA

**Comment by YorsLosilla** [comment]
The message is the the standard execution message

**Comment by JacquesLucke** [comment]
Thanks! There is actually a bug that I have to fix.

Also the reason that this is so slow is that you increased the resolution in the advanced settings of the Spline Falloff node. When you set it to something around 5, everything is much faster.

**Comment by YorsLosilla** [comment]
The error appears specially when the animation ends and begin again. From end frame to first frame.

**Comment by JacquesLucke** [comment]
Yes I see, the problem happens when the start and end value in the Get Spline Samples node are out of range. (0-1)

**Comment by YorsLosilla** [comment]
Maybe a single if statement will fix the problem

**Comment by JacquesLucke** [comment]
almost true :+1: 

Should be fixed now. I think I won't upload a new build right now, but you can easily fix your setup now by inserting one Clamp node for the Start and one for the End input.

**Comment by YorsLosilla** [comment]
Thanks mate. I love this interactive bug fixing :)

**Comment by karlisstigis** [comment]
Yeah.. that spline not taking modifiers into account is still quite annoying, because must be only one spline in object. I hope Blender will allow that functionality someday. But still amazing possibilities.

**Comment by OmarEmaraDev** [comment]
It is now possible to apply spline modifiers in 7328e0b.
