### ISSUE TITLE
BVH Is Inside Volume - not really precise - AN 2.0

### ISSUE THREAD

**Issue by Pswida** [JacquesLucke/animation_nodes#712]
Hi,
I was trying to get bunch of random points from inside of geometry. So with setup below it gives some outside points too. 
Anyway its great that "Is Inside Volume" node is availaible for Vector Lists! It was still fast with 10000 points.

![bvh](https://cloud.githubusercontent.com/assets/17111356/26223771/cc4ff216-3c1f-11e7-843b-da4bd3072d9d.JPG)

P.

**Comment by JacquesLucke** [comment]
This is because the suzanne mesh is not a closed mesh (the eyes are not connected to the head). Without having a closed mesh "inside" is not really a term that makes sense at all.

**Comment by Pswida** [comment]
Thank you.
This was not so obvious - especially that error produced was marginal in this case (few bad points vs thousands solved as expected).
Yes, I know more about Suzanne now :-).

**Comment by JacquesLucke** [comment]
Yes, I guess there are better algorithms to determine if a point is in a mesh.
What I implemented in AN is rather simple. From each point I shoot a ray in a random direction and check how often it hits a polygon. If it is an odd number, the point is inside. If it is even, the point is outside.
Actually this is done up to three times for every point to improve accuracy.
