### ISSUE TITLE
Info Node Tangents missing.

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#714]
I love the new Spline Info node, but although I can get points from it, there are no tangents output like in Resample node. Kind of important thing.
![screenshot 1](https://cloud.githubusercontent.com/assets/17803543/26521563/25549788-42f4-11e7-8454-e0f439fd4c37.jpg)

**Comment by JacquesLucke** [comment]
Ah I see. I could add this in theory.

It is not there yet because the tangent is not stored for every point, it is recalculated every time when it is needed.

Also it is not quite clear what the tangent at each point of a poly spline is..

**Comment by karlisstigis** [comment]
Isn't tangent the direction of one point to the next basically? Or if it's the direction of the point itself, then it's those 2 directions mixed 50/50.
