### ISSUE TITLE
Edge info node

### ISSUE THREAD

**Issue by piegamesde** [JacquesLucke/animation_nodes#716]
With "Create edge indices", you can merge two Vertex indices to an edge. Please add a node to get the two vertex indices from the edge back again. (I'd call it "Edge info" or so)

**Comment by JacquesLucke** [comment]
In AN 2.0 there is already an Edge Info node. I'm not sure yet wether it should output the vertices of the edge as well because this does not "vectorize" as well. We'll see.

Also in thr new versionnyou can use the Get List Element node to get the vertices of a specific edge or polygon.

**Comment by piegamesde** [comment]
How can I get AN 2.0?

**Comment by JacquesLucke** [comment]
AN 2.0 is not final yet but you can get a beta version from http://graphicall.org
(make sure you download the addon for the correct os)

**Comment by piegamesde** [comment]
AN 2.0 first didn't execute anything (0.000ms execution time) and then killed all my node connections, so I reverted to the official release.

The Edge Info node does not provide the information needed, because I make calculations based on the angle of the edge. To do this, I either need their vertices' indices or their positions (I'd prefer the first because of re-usability in other situations). In the meantime, I managed to create a custom node providing this functionality with the following code:
```
Index1 = EdgeIndices[0]
Index2 = EdgeIndices[1]
```

It does kill the execution time though, so that's not a very good solution.

**Comment by JacquesLucke** [comment]
Ah I should have told you. Files created in the currently official version are not compatible with the newer version.

Will think about your problem again :)

**Comment by piegamesde** [comment]
I'll tell you more about my project, perhaps it will provide useful information for your decision:

I generate mesh by duplicating objects, but because that would be many objects and Blender doesn't like that and I only need the mesh, I do the following:

 - In a loop, for each object:
    - create Transformation Matrix, apply to object to duplicate (Object Matrix Output)
    - Read mesh data from Object (Object Mesh Data, Combine Mesh Data/Mesh Data from Polygons)
    - Output it as Mesh Data List
 - Combine duplicated Mesh to one (Join Mesh Data List)
 - Apply to output object (Mesh Object Output)

Now, I have a mesh with some edges. For each edge, I want to duplicate a Cylinder using the technique from above so that it fits the Edge. The effect is like a skin modifier, but with more control. Positioning the Cylinder takes two Vectors as edge data. From there it calculates the center to position the Cylinder and the distance to scale the Cylinder. The angle between the vectors is used to rotate the Cylinder based on some math copied from StackOverflow.

As you can tell, the center point and the length of the edge don't provide enough information to create this effect.

**Comment by JacquesLucke** [comment]
Yes, this is why I told you that you can use the Get List Element node to get the start and end point of an edge (in AN2). Maybe I'll find a good way to integrate that into the Edge Info node as well.

Beside that AN2 also has a new node called Edge to Tube which does pretty much what you are trying to do (it can also work on multiple edges at once).

**Comment by piegamesde** [comment]
> Yes, this is why I told you that you can use the Get List Element node

Sorry, I didn't test it because my node tree didn't work in AN2
> Beside that AN2 also has a new node called Edge to Tube

This is very exciting and will make things a lot faster. (Although 5.4s for now isn't too bad; have seen worse)

**Comment by JacquesLucke** [comment]
I updated the Edge Info node:
![edge info](https://user-images.githubusercontent.com/5881326/27007148-3dadb6ec-4e49-11e7-8aaa-6676b162e3f3.PNG)
