### ISSUE TITLE
Interpolation From Curve Node: Does Not Update "Tree Changed" State

### ISSUE THREAD

**Issue by Waffle-SS** [JacquesLucke/animation_nodes#718]
Changes made to the custom "From Curve" Interpolation node do not trigger a "Tree Changed" state (used when execution is not set to always).

It may not be very efficient to re-execute the tree while the user is dragging the curve points, but at the very least it should update when the user finishes making changes to the node.

**Comment by JacquesLucke** [comment]
The problem is, that this is technically not possible due to some limitations in Blender.
