### ISSUE TITLE
High memory consumption when animating Ocean modifier

### ISSUE THREAD

**Issue by jhaiduce** [JacquesLucke/animation_nodes#719]
When I try to animate properties of the Ocean modifier using Animation Nodes, the memory consumption grows continually while rendering. This only happens when I animate the Ocean modifier using animation nodes (not when I animate the Ocean modifier with 

fcurves or using a simple python script), and only while rendering (not during playback in the viewport). 

Steps to reproduce:
1. Add an Ocean modifier to a mesh
2. Set the resolution of the modifier to 24
3. Animate some property of the Ocean modifier using an "Object Attribute Output" node
4. Render the animation

(Step 2 is needed for the memory consumption to grow fast enough to be noticeable). Blender's memory consumption will grow steadily while the render proceeds.

**Comment by jhaiduce** [comment]
Here's an example .blend file
[AN_wave_test.zip](https://github.com/JacquesLucke/animation_nodes/files/1048505/AN_wave_test.zip)

**Comment by JacquesLucke** [comment]
Hm it seems to work fine here. The memory consumption jumps back and forth between 42 and 242mb in every frame. So looks like the memory is freed correctly. Can you test the newest Blender version from builder.blender.org ?

Also I experienced multiple crashes while trying to render this file. It is possible to fix this by enabling the "Lock UI" option in the render panel (just in case you have the same problem).
