### ISSUE TITLE
Error on install on OSX

### ISSUE THREAD

**Issue by JoelGodin** [JacquesLucke/animation_nodes#720]
I get an error when installing the zip file addon;

![3](https://user-images.githubusercontent.com/9205295/26859932-08d0169c-4b09-11e7-8074-82025da03850.png)

**Comment by jasperges** [comment]
Can you please paste the complete error message? The most helpful bit is now cut off.

**Comment by JoelGodin** [comment]
![a](https://user-images.githubusercontent.com/9205295/26878864-fcaa7688-4b5c-11e7-9227-05299fd96f72.png)


Okay, went to python panel, did import numpy with error.
That bug was supposed to be fixed.  I'll raise the issue again.
