### ISSUE TITLE
Viewport Material node freezes preview update, Causes High CPU usage, eventual crash.

### ISSUE THREAD

**Issue by JoelGodin** [JacquesLucke/animation_nodes#723]
Blender Version
2.78.5 version c2d285f0ffc 6-23-2017

In Animation Nodes addon, color to viewport color node freezes material preview update, causes high CPU usage, and eventual crash.  (video at bottom)

Exact steps for others to reproduce the error
Enable Animation nodes,
add material to cube,
add node tree, insert Color > 'Choose Color' node, 
insert Material > 'Viewport color' node
choose 'material' in viewport color node
(sequence of above not important)

Preview cannot change between cube, Suzanne, plane, ball etc unless you hide preview (turn triangle) and un-hide.

removing material in node frees it up, select material in node again and it freezes, causes high cpu usage, and eventual crash.

[ViewPortColorBug.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1120797/ViewPortColorBug.blend.zip)

[ViewPortColorBug.crash.txt](https://github.com/JacquesLucke/animation_nodes/files/1120798/ViewPortColorBug.crash.txt)

![system info](https://user-images.githubusercontent.com/9205295/27811589-f92545ae-6035-11e7-99de-b74601c8f873.png)

Video Here:
https://youtu.be/0STXpo_C_lU

**Comment by JacquesLucke** [comment]
Thanks, will check that.

**Comment by JacquesLucke** [comment]
Fixed it, thanks for the report.

**Comment by JoelGodin** [comment]
Awesome, thanks.

**Comment by JoelGodin** [comment]
I'm guessing it is not available yet, as it still crashes?

**Comment by JacquesLucke** [comment]
No it is not available yet, sry. You will have to wait some days most likely. I can't compile AN for macOS myself.

**Comment by JoelGodin** [comment]
I thought Addons are in python and not OS dependent?

**Comment by JoelGodin** [comment]
Okay, sorry for not knowing, but does that mean in the future 'download
zip' from 'clone' there will be OS specific downloads?

**Comment by JacquesLucke** [comment]
No problem.

In the future you will download the AN builds from a special release page. 
Test builds are available on graphicall.org/

**Comment by JoelGodin** [comment]
Gotcha, thanks.
