### ISSUE TITLE
[Feature Request] Random Integer

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#726]
It would be useful to have this one supported.  :)

**Comment by JacquesLucke** [comment]
Should the current Random Number node be renamed to Random Float?

What should be the inputs/outputs of a Random Integer node be?

Also AN supports implicit conversion between Float List and Integer List already.

**Comment by LeonCheung** [comment]
I know. It just turns out that at least two nodes have to be used to generate a random integer list. I think maybe Random Number should have an Integer Mode?

**Comment by JacquesLucke** [comment]
Why do you need a second node when you can just link a float list socket with an integer list socket.

Hmm will see. I think this node won't make it into the next release. I might implement it afterwards.

**Comment by LeonCheung** [comment]
Well it seems you are making sense that it would be not so needed if implicit conversion works nice. I'll close this for now until I found a convincable case.
