### ISSUE TITLE
Add Tab Character Output

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#727]
Can we have a Tab output for Characters node? You know, instead of doing by typing somewhere else then copying and pasting back to AN. (Found it would be convenient a bit when dealing with text blocks)

**Comment by JacquesLucke** [comment]
Sounds like a good idea.

**Comment by JacquesLucke** [comment]
I think I will remove the "All" output of the characters node. It is too unspecific. What do you think about that?

**Comment by LeonCheung** [comment]
Hmm, I think so. I seldom use **All**, except for some random flash fx.  :)
