### ISSUE TITLE
Feature request: Vectorize Shape Keys Nodes

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#731]
Sorry to bother again, but working in a project I have noticed that this could be handy.

Due to how slow this node works on loops I can imagine the problems that this may cause.

**Comment by JacquesLucke** [comment]
I vectorized the Shape Key Output node now.

The Shape Keys from Object is not yet vectorized as I'm not sure yet how to do that. It is not quite clear what the output of the node should be when there is a list of objects.

I think I won't finish this before the release.

**Comment by YorsLosilla** [comment]
Well, I think that I can´t help from this point, this is far beyond my technical knowledge. 

I just hope not having opened another Pandora´s box.
