### ISSUE TITLE
Freature request: include hair child strands in 'Hair Data' node.

### ISSUE THREAD

**Issue by JoseConseco** [JacquesLucke/animation_nodes#733]
Would be great if 'Hair data' node generated splines also for child strands:
![splinesinterpol](https://user-images.githubusercontent.com/13521338/28240638-b6024638-6985-11e7-86c8-b32ce3990348.jpg)
Maybe I will manage to code this myself, and push this change to master. I will try :)
It seems, Blender doesn't support accessing properties of child particles. Too bad :/

**Comment by JacquesLucke** [comment]
You're right, I haven't found a way to do this so far. Maybe we will be able to access this data in Blender 2.8 but I'm not sure about that.
