### ISSUE TITLE
Really long Blender start with AN 2.0 (Up to a minute!)

### ISSUE THREAD

**Issue by zachThePerson** [JacquesLucke/animation_nodes#734]
The issue is pretty simple to explain: Without AN 2.0 installed, Blender starts in about 5 seconds from clicking the button to splash screen from SSD. If I install AN 2.0, that start time goes up to about 1 minute.

Looking at the console, the pause seems to occur after "found bundled python: C:\Program Files\Blender Foundation\Blender\2.78\python" and before "Registered Animation Nodes with 499 modules," so I assume this is an Animation Nodes issue as the second that message is written to the console, Blender boots to splash.

Specs:
Win 10 x64
i7 6700k
Samsung EVO 250gb
Blender 2.78

EDIT: The same hiccup occurs every time I enable the plugin in User Preferences as well, so I am 100% sure this is an Animation Nodes 2.0 issue.

**Comment by JacquesLucke** [comment]
hmm that is weird. It definitely should not take that long, at least not after it loaded the first time.

An earlier test build worked without problems for you, right?

Are pycache folders created within the animation_nodes directory?

**Comment by zachThePerson** [comment]
Yes, the pycache directory is created in the Blender addons folder, and filled with 12 ".cpython.pyc" files

I have been experiencing this since I first started using AN 2.0 beta builds a few months back. I updated to the newest version today right after posting and the issue still occurs, although it might be a _tiny_ bit faster.

**Comment by JacquesLucke** [comment]
the first start ahould take around 2-5 s and afterwards less than a second, so something is wrong.

I will try to reproduce this today.

How much space is left on your ssd?
Does AN work at "full speed" once it is loaded?

**Comment by JacquesLucke** [comment]
You said you have a some programming experience, right?
Can you put a print statement into this loop?: https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/import_modules.py#L9

Than start Blender from the console and see how quickly the individual modules are loaded. This will help us to see if there is one module that is extremely slow, or if all are slow or if the problem is somewhere else.

**Comment by zachThePerson** [comment]
I have 118gb free, and yes it does work full speed.

I was thinking, and there is a small chance that for some weird reason Blender is just struggling to load bigger addons. The only other addons I have at the moment are small such as BLAM and BlenchMark. I will try disabling AN, and only enabling LuxRender tomorrow and see if that causes the same issue.

EDIT: I will also try putting the print statement in the loop, but its 2:00am right now and I'm going to bed -_- Zzzz

**Comment by JacquesLucke** [comment]
ok.. Report back when you tested this. Good night for now.

**Comment by zachThePerson** [comment]
Ok, so I tested it with only luxrender enabled, and it only took 3 seconds to boot, so it's definitely AN.

I added the print statement, and actually got the fastest boot yet, at only around 30 seconds: [https://youtu.be/ZR7fefNDIDc](https://youtu.be/ZR7fefNDIDc)

It's important to note, that I only get this on a fresh start of Blender. If I close the program, and open it again quickly after, it boots in about 5 seconds, but if I do something else and come back to it later it will be the 30-45 second boot time. This is probably something to do with Windows' memory cache

**Comment by zachThePerson** [comment]
What version of python are you using? Running "**print(**sys.version_info**)**" from inside blender looks like it's running 3.5, and I have 3.6 installed on my system. Do you think that could have something to do with it?

**Comment by JacquesLucke** [comment]
Thanks for the video! I still don't know what causes the problem but at least I know now what happens exactly.

Yes sounds a bit like a memory issue however I never experienced this before so I have no idea.. Will have to google a bit.

Blender comes with it's own Python build. In 2.78 and 2.79 this is Python 3.5
The builds for AN are also for Python 3.5 only.
They will switch to Python 3.6 in the Blender 2.8 branch at some point.

Blender is independent of the Python version you have installed on your system (at least this is the case on windows).

**Comment by oktomus** [comment]
Hey, it may come from your OS, I'm not sure but I don't see any reason why python would take so long. Indeed windows builds of python are slower because of backward hardware compatibility, but that's very long ^^ It is possible that windows limit your process resources. @JacquesLucke don't you use a subprocess, a fork or something somewhere in your init process ?

**Comment by JacquesLucke** [comment]
Well I personally use Windows as well as Linux and it loads much quickly on both platforms.
No, everything is in one process afaik.

**Comment by oktomus** [comment]
Really weird.
