### ISSUE TITLE
BLender no detecta el animation nodes

### ISSUE THREAD

**Issue by kone9** [JacquesLucke/animation_nodes#737]
NO Aparece el animatión nodes en los addons al instalarlo
Video donde muestro el problema.

version de blender 2.78 sistema operativo ubuntu studio 16.04 lts
https://www.youtube.com/watch?v=0FND1dDXzsc&feature=youtu.be

**Comment by JacquesLucke** [comment]
You should write in english here if possible.

You have to download the addon from here: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0

**Comment by kone9** [comment]
I downloaded it from the link that you passed me for linux and it works. Thanks a lot. Then upload a video to youtube explaining that error


________________________________
De: Jacques Lucke <notifications@github.com>
Enviado: domingo, 16 de julio de 2017 02:42 p.m.
Para: JacquesLucke/animation_nodes
Cc: kone9; Author
Asunto: Re: [JacquesLucke/animation_nodes] BLender no detecta el animation nodes (#737)


You should write in english here if possible.

You have to download the addon from here: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0

[https://avatars5.githubusercontent.com/u/5881326?v=4&s=400]<https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0>

JacquesLucke/animation_nodes<https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0>
github.com
animation_nodes - Node based visual scripting system designed for motion graphics in Blender.
