### ISSUE TITLE
Confusion regarding version 2.0 and issue when uninstalling old version 1.7.5.

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#738]
Jacques, with AN 2.0, should I install from Github or from Graphicall? --> Blender Nation should give you the link. I want the official release, but don't mind the development, as long most nodes are "vectorized".

I got issue uninstalling old version, actually.  I tried all methods, none works. I keep getting: You have more than 1 AN add-on installed.

Now I am going to try reinstalling Blender....

**Comment by enzyme69** [comment]
![prtscr capture_2](https://user-images.githubusercontent.com/3952687/28260445-6c442f8a-6b1e-11e7-9e18-806b5fc51dfb.png)

Nope still not working. I am using Windows 7 ....

How do I completely remove old AN add-on...? :(

**Comment by enzyme69** [comment]
Ok I managed to uninstall it by deleting all animation_nodes folder from add-on.

Using GraphicAll advanced version:
![prtscr capture_4](https://user-images.githubusercontent.com/3952687/28260618-3f02bafe-6b1f-11e7-80f5-97fbee4edb96.png)

But GitHub version is the same right?

**Comment by jasperges** [comment]
@enzyme69 You should use the version from Github. That's the official release (and also the latest version). Graphicall is/was used during development.

For the Linux and MacOS builds on graphicall I will add a warning.

**Comment by enzyme69** [comment]
Thanks @jasperges 

This should be linked:
https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0
