### ISSUE TITLE
Doea AN Cache Values?

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#739]
Just wondering, does AN have this concept of "caching data over time" similar to Houdini Cache SOP node where data can be cached as time goes by and if it hits a certain value, it will remain like that,

I can make offset like this but imagine below, but instead of going back to original values (Matrix Transform A), it remains at Matrix Transform B:
![an_offset_anim](https://user-images.githubusercontent.com/3952687/28262645-1d1f9224-6b27-11e7-88d6-338dce16e0ea.gif)

Kind of like Dynamic Paint where we pass Attribute A into the points and the Attribute will then remains at position B.

**Comment by JacquesLucke** [comment]
Currently this is only possible if you really know what you are doing. I think it should not be done atm. It is not part of the design lf AN yet.

However I have a few ideas on how this can work in the future. It will take quite a bit more time though..

Getting the details right and making it fit into AN is not an easy task. It's likely that I will need multiple iterations until it works in a way I like.

**Comment by enzyme69** [comment]
I think I probably asked you in Twitter about this at some point. You gave me some kind of math expression last time. 

Maybe I can trick this with "snap". Or Logic function. 

Ok I will think... Cheers Jacques~
