### ISSUE TITLE
Don't installing

### ISSUE THREAD

**Issue by samuelmnl** [JacquesLucke/animation_nodes#740]
Hi, i can't install this new version because there are an error. I have unninstalled the old versions, reinstall the Blender and tryed install directly in the directory of the Blender. But nothing sucess. How i dont have an experience wih Python Language don,t can solve this.
Thanks for your attention.

**Comment by JacquesLucke** [comment]
Can you show me an images the error message please?
Also what operating system do you use?

**Comment by samuelmnl** [comment]
So, i'm using Windows 10 64bits
Using install from file get the message, but not is ennable
![image](https://user-images.githubusercontent.com/30241428/28283624-a67595e6-6b04-11e7-9e65-25670f63a1be.png)

If install directly in the directory get this message.
![image](https://user-images.githubusercontent.com/30241428/28283790-418a4efa-6b05-11e7-8a66-5001020b1d38.png)

![image](https://user-images.githubusercontent.com/30241428/28284083-3f09b62e-6b06-11e7-9328-d97e833d9435.png)

**Comment by jasperges** [comment]
I think you just downloaded the source code. But for Animation Nodes v2.0 you should download a built version from here: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0 In your case you should download the [Windows version](https://github.com/JacquesLucke/animation_nodes/releases/download/v2.0/animation_nodes_v2_0_windows.zip).

**Comment by samuelmnl** [comment]
So, now show this error, but i have removed the old versions.
![image](https://user-images.githubusercontent.com/30241428/28286422-7b7798a8-6b0e-11e7-8adb-6d699c66cfdf.png)

**Comment by JacquesLucke** [comment]
Please open this path in your windows explorer:
C:\Users\samue\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\

You will see that there is more than one version of AN.

**Comment by samuelmnl** [comment]
Really. Excluded the files and it worked. But is not a old version. The same version that i tried oftentimes. Thanks.
![image](https://user-images.githubusercontent.com/30241428/28287216-2bbf5230-6b11-11e7-8239-71045d4fd963.png)

**Comment by JacquesLucke** [comment]
Right, delete the selected folders and download a version from the release page.

Does it work now?

**Comment by samuelmnl** [comment]
Yeah, it's working. Thanks.
