### ISSUE TITLE
Can't see AN in addon menu

### ISSUE THREAD

**Issue by sergeod9** [JacquesLucke/animation_nodes#741]
Hi, 
Here are the things I tried
I uninstalled the older version of AN, installed the new one (zip file), but I can't find it in usersettings> addon menu, even though I get a message that the modules are installed, I tried to find it in the the scripts directory in 2.78 directory in Program Files, there's nothing there, I'm running Blender 2.78c on Windows 10 64bit. I tried the following:

- Searched the device for all files that has "animation nodes" in them and deleted everything.
- Restarted Blender.
- Made sure that it's not in the addon menu.
- Install addon > animation nodes master.zip
- couldn't find the related addon in the menu.

The only thing that changes is that now I have it in Blender Foundation directory in User\AppData\Roaming\Blender Foundation\...
but not in the scripts directory in Program Files\Blender Foundation ...

-I already have VC++ installed, I checked in Blender's python, numpy and Cython are there.
-I checked config_default.py the path is in Users\... as discribed in the original file on Git.
-I checked the setup.py, there should be config.py? Couldn't find it anywhere.
-Opening the config_default.py again, I inserted my path instead of default, and ran setup.py, now I have config.py file created, but still no luck in Blender, still nothing in the scripts directory in Program Files.

Thank you,
Georges Dahdouh

**Comment by sergeod9** [comment]
Ok, thanks, I'll give it a shot, I followed the link in a tutorial's description on youtube.
https://www.youtube.com/watch?v=K3CwKkiJZN0

**Comment by JacquesLucke** [comment]
Yeah, most links send you to this page, and this is not wrong. Just a few days ago you would install exactly the way you tried it. But that changed, forever. 

You just have to press here to get to the download page:
![unbenannt](https://user-images.githubusercontent.com/5881326/28284284-b706aef0-6b30-11e7-9ab8-a9644c2d2876.PNG)

**Comment by sergeod9** [comment]
Thank you, it worked!!!
