### ISSUE TITLE
Offset Values?

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#742]
We got Offset Matrices and Offset Vector, but do we have Offset Values to animate Floating values? Or is it somewhere that I missed?

Basically just trying to animate multiples values, A to B, and offset it.

**Comment by enzyme69** [comment]
Ok... so I can just use Combine Vector and Separate Vector for values. Cool enough~

**Comment by JacquesLucke** [comment]
right, many falloffs don't make much sense on just numbers. However you can use the evaluate falloff node. This allows you to use the falloffs in other areas as well.
