### ISSUE TITLE
Uninstalled the older version, now new version will not install

### ISSUE THREAD

**Issue by ronboglcs** [JacquesLucke/animation_nodes#743]
I select the zip file in user prefs. and nothing happens, no msgs. nothing.

**Comment by JacquesLucke** [comment]
Where exactly did you download the newer versoon?

Please check if you have the same problem as here: https://github.com/JacquesLucke/animation_nodes/issues/740

**Comment by ronboglcs** [comment]
That solved it.  The version that I first downloaded only was half a mb,  this one works!  Thanks for developing this.
