### ISSUE TITLE
Cannot activate animation nodes.

### ISSUE THREAD

**Issue by trych** [JacquesLucke/animation_nodes#744]
Hi there,
when I try to activate Animation nodes I get some error messages:
![bildschirmfoto 2017-07-19 um 14 42 46](https://user-images.githubusercontent.com/9803905/28367385-0a4399f0-6c91-11e7-96a1-84572c8151cf.png)

Upon trying it again (as in clicking the checkbox once more), I get this message instead:
![bildschirmfoto 2017-07-19 um 14 43 09](https://user-images.githubusercontent.com/9803905/28367393-17b63552-6c91-11e7-8d75-ebe2b8dfffe5.png)

It reliably produces these two error messages in sequence. I tried removing and re-adding the plug-in, but no luck.

According to the plugin, it's version 2.0.4 and I'm on Mac OS X 10.8.5 using Blender 2.78c.

Am I doing something wrong?

**Comment by jasperges** [comment]
Mmmm, I'm not sure, but it might be because I compiled Animation Nodes on OSX 10.11 (El Capitan). I will see if I can find out more about this.

**Comment by trych** [comment]
Oh. Okay.
Let me know if there is anything I could try for debugging under 10.8.5.

**Comment by jasperges** [comment]
I didn't have time yet to properly look into the issue. But can you try this version and let me know if it works? 
[animation_nodes_v2_0_macos.zip](https://github.com/JacquesLucke/animation_nodes/files/1167157/animation_nodes_v2_0_macos.zip)

**Comment by trych** [comment]
Yes, it throws the same errors unfortunately.

If you could give me instructions how to build it myself, that would be very appreciated (although I am not too command line savvy), maybe there are others, who have the same problem.

**Comment by jasperges** [comment]
Okay, here goes:
If you don't have Python 3.5.3 already installed, download it from [here](https://www.python.org/ftp/python/3.5.3/python-3.5.3-macosx10.6.pkg) and install it. (You can't use the Python version that's included with Blender unfortunately.)
After that download the [source code of Animation Nodes](https://github.com/JacquesLucke/animation_nodes/archive/v2.0.zip).
Then open a Terminal and run the following command:

```bash
sudo -H pip3.5 install cython
```
After the password prompt, type your password and press enter. Then run the following commands.
```bash
unzip -d . ~/Downloads/animation_nodes-2.0.zip
cd animation_nodes-2.0
python3.5 setup.py --nocopy --export
```
After everything finishes, you now should have `animation_nodes.zip` in the directory `~/animation_nodes-v2.0`. Install this in Blender and you should be fine. Just don't forget to remove all previous versions of Animation Nodes, before installing the new one.

**Comment by jasperges** [comment]
@trych Can you try [this build](https://github.com/JacquesLucke/animation_nodes/files/1180983/animation_nodes_v2_0_macos.zip)? Don't get your hopes up, but I just noticed something when building Animation Nodes again. This was after I upgraded and cleaned my computer. If we are very, very lucky it might work.

**Comment by trych** [comment]
@jasperges Now I can activate it without complaints! So it seems to work. Thanks a lot for looking into this! Will close this, as this is fixed.

**Comment by jasperges** [comment]
@JacquesLucke Maybe you can update the macOS build on the release page with [this one](https://github.com/JacquesLucke/animation_nodes/files/1180983/animation_nodes_v2_0_macos.zip)? At least there is a 'backup' version for people when the current one is not working... :)

**Comment by JacquesLucke** [comment]
I uploaded this as an alternative build. What was the problem in the first build?

Btw: I'm currently rewriting the setup.py file completely for a future version (not v2.0a, that would be a too big change). 
The plan is that it will be possible to create a cythonized but uncompiled build, meaning that the build can be compiled without having cython installed. We will be able to share those builds to make it significantly easier for others too compile the builds themselves (maybe even using the python version blender comes with, haven't tried this yet though). The c files cython generates should be platform independent afaik.

**Comment by jasperges** [comment]
@JacquesLucke The first build doesn't seem to work on versions of macOS before 11.11. The alternative does work on at least 10.8 and I think even back to 10.6.

Nice. But as far as I know the compilation of the c files doesn't have anything to do with Python anymore (except that it's probably used as a library). It's just the 'normal' compilers installed on the system that do the work. Which means you have to have these installed, which is probably too much for the average user.

**Comment by leeseth** [comment]
Hello!

I could use some help getting up and running with Animation Nodes on OSX Mojave 10.14

I apparently installed the wrong version of Animation nodes (in both 2.8 & 2.79) and wasnt able to activate it. I went through your documentation on uninstalling, but regardless how I try to uninstall/reinstall either Blender or AN, I get the error message that an older version of AN is still installed, though it doesnt appear in my Addons list when I start up a new file. 

Id appreciate some help troubleshooting or finding the thread that gets me on the right track. 

Thank you!

**Comment by OmarSquircleArt** [comment]
@leeseth Blender have multiple paths to store addons. You have to go to each one and manually remove the folder called `animation_nodes`. See this for possible paths:

https://docs.blender.org/manual/en/latest/getting_started/installing/configuration/directories.html#macos

**Comment by Clockmender** [comment]
@leeseth on a Mac the animation nodes folder is here:

![Screen Shot 2019-03-31 at 07 41 08](https://user-images.githubusercontent.com/29657804/55285698-b511a180-5388-11e9-82ff-a087e106b7c5.png)

The Directory "mac" is my username BTW - You need to remove the `animation_nodes` folder for all versions of Blender if you want a new version to work in all Blenders.

Cheers, Clock.

**Comment by leeseth** [comment]
@Clockmender 
Thanks for the follow up, I tried finding that directory, but Library, isnt under my User for some reason. I have looked for that directory under other "library" directories, but am not finding the support for Blender. Any other suggestions would be greatly appreciated. 
<img width="1086" alt="Screen Shot 2019-03-31 at 3 16 04 PM" src="https://user-images.githubusercontent.com/49053262/55294492-566c1800-53c8-11e9-89a9-b1d343cb9744.png">
<img width="1437" alt="Screen Shot 2019-03-31 at 3 18 29 PM" src="https://user-images.githubusercontent.com/49053262/55294495-5ec45300-53c8-11e9-88e2-9b8dcb9400a5.png">

**Comment by Clockmender** [comment]
Wel, it **IS** there, but normally Apple don't want you poking around in there messing things up for your Mac, so they hide it, but to get there do this:

![Screen Shot 2019-04-01 at 08 44 50](https://user-images.githubusercontent.com/29657804/55311373-aeebf580-545a-11e9-8316-494e19b8c717.png)

Click "Go" => "Go to Folder".

![Screen Shot 2019-04-01 at 08 45 22](https://user-images.githubusercontent.com/29657804/55311541-21f56c00-545b-11e9-9e20-026da9f76918.png)

Type in "/Users/lee/Library" (mac is my username)

Go to Application Support, etc. as I said in previous post.

![Screen Shot 2019-04-01 at 08 45 37](https://user-images.githubusercontent.com/29657804/55311559-2b7ed400-545b-11e9-9a9d-bf6e7abb72e4.png)

DON"T Delete, rename, move, alter anything else in there other than deleting the animation_nodes folders.....

Cheers, Alan.

**Comment by OmarSquircleArt** [comment]
It should be noted that if you are using a portable version of Blender, the addon might be local to the build, that is, in the same directory as the executable.

**Comment by leeseth** [comment]
@Clockmender 
Thank you! That seems to have done the trick (in 2.79 at least) I appreciate it!
