### ISSUE TITLE
Error massage during enabling the addon 

### ISSUE THREAD

**Issue by Singh-KS** [JacquesLucke/animation_nodes#745]
Thank you very much for this addon.

I downloaded the latest version of animation nodes from this link https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0. But I'm getting an error message during enabling it. I have also tried with the newest version of blender but the error is still there. I'm also attaching the screenshot of the error message.

OS: Ubuntu 14.04 LTS 64bit
Blender: blender-2.78c-linux-glibc219-x86_64
Python: Python 3.6.0 |Anaconda 4.3.1 (64-bit) 

![error](https://user-images.githubusercontent.com/30294746/28376561-102cedf8-6cc8-11e7-949e-e6e6fc1cf8f3.png)

**Comment by Singh-KS** [comment]
I have found the solution. I remove the previous files of the add-on from the 'scripts' folder of the blender. Now it is working :)

**Comment by JacquesLucke** [comment]
Perfect :)
