### ISSUE TITLE
Why different nodes have different color for seed input ?

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#746]
I just want to know that is there any reason for a different color for seed input on different nodes or it is just a typo?

![correction1](https://user-images.githubusercontent.com/30294746/28533992-ab1d8028-70bc-11e7-8d2c-f3f69b0801dd.png)

**Comment by JacquesLucke** [comment]
This is just an inconsistency. I might correct it a bit later.

There is no special reason why different types are used.

**Comment by Singh-KS** [comment]
Thanks :)
