### ISSUE TITLE
Can't enable Linux Builds (cannot import name 'Linear')

### ISSUE THREAD

**Issue by unfa** [JacquesLucke/animation_nodes#749]
I found some AN builds on GraphicAlll, and I tried installing two of them. Blender installs the add-on from supplied zip file but when I want to enable it I get this message:

![spectacle jd1106](https://user-images.githubusercontent.com/491704/28591397-db2135a2-7185-11e7-9234-47e219753fbf.png)

The builds I tried are these:

http://graphicall.org/1207
http://graphicall.org/1205

I then saw a warning that an official release is available and I downloaded this:
https://github.com/JacquesLucke/animation_nodes/releases/download/v2.0/animation_nodes_v2_0_linux.zip

Only to see this:

![spectacle yj1106](https://user-images.githubusercontent.com/491704/28591519-54a5084a-7186-11e7-91c9-10190efef2de.png)

My operating system is Linux Mint 18.2 with KDE 5.

PS: I had trouble find an official build, there's no mention in the Documentation. I first downloaded the Github snapshot and tried installing that, like I used to do with AN 1.6.

Maybe some information on the main page where to download official builds would be a good idea?
I read this: http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html, and I didn't find a link to the Github releses page. It's silly I know, but I was lost.

**Comment by JacquesLucke** [comment]
I have exams this week so I don't have much time for AN. I will check this in more detail next week.

**Comment by unfa** [comment]
No problem. I'll manage :) Good luck with your exams!

I've noticed that AN 1.6 shows ythe same error, I'll try using a stable Blender build (not a nightly one) and see if it works.

**Comment by unfa** [comment]
Allright. I downloaded a fresh official Blender 2.78c build, and I manually removed all Animation Nodes -related files from ~/.config/blender/2.78/scripts/addons/

There was a folder **animation_nodes** and a file **setup.py** probably left after I mistakenly tried installing source code instead of a build.

After cleaning this up AN 2.0 enable without warnings.
