### ISSUE TITLE
Multithreaded Sound Baking?

### ISSUE THREAD

**Issue by unfa** [JacquesLucke/animation_nodes#750]
I'm planning to create an hour-long music visualisation with Blender, Animation Nodes and Natron.

I wonder if Baking Spectrum frequencies could be done in parallel? I have a 16-thread Ryzen 7 CPU that could really crunch these numbers, but I see that AN analyzes the sound 1 band at a time, in one thread.

That'd be a cool performance boost for longer animations (and a lot of bands too).

**Comment by JacquesLucke** [comment]
Unfortunately that is not really possible atm. For sound baking I currently use Blenders "bake sound to fcurve" operator. It is not possible to access this operator multiple times at the same time.

afaik Blenders sound system will get an update in Blender 2.80 which will allow me to get more low level access to the actual sound data. This would allow me speed this process up, but we are not there yet.

It might be possible to analyse the sound data in another program, convert that into a list of numbers and bring this list into Blender somehow. Not sure if it is worth the effort. This will likely require some python programming in Blender.

**Comment by unfa** [comment]
I wonder if there's anything new regarding this issue?

**Comment by OmarEmaraDev** [comment]
@unfa We rewrote the sound system. It is now realtime, so no baking is needed.
