### ISSUE TITLE
AN Separate Loose Parts and Center Pivot / Set Origin 

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#751]
With Animation Nodes, I wonder if we could have functions such as:
- Separate Loose Parts
- Center Pivot / Set Origin

Let say I have an object with million pieces, if I separate the objects, I will end up with so many 3D objects and then bring it into AN. It's always an extra step.

I wonder if we can SEPARATE it inside AN as a single process (so far I am using Sverchok for this), then also do the CENTER PIVOT for next animation process.

After some thinking....
In actual production, probably those separate pieces probably can be very complex and each already have UV, so maybe this is not the right way to do it though... BLEND referencing from outside, might be again the solution.

I don't know just a thought...

**Comment by JacquesLucke** [comment]
I think both ideas are possible and will become a part of AN within the next year. First I'll have to update the mesh system again a little (mostly under the hood though).

Afaik it should be possible to implement a separate loose parts algorithm that has nearly linear time complexity. So I hope it will be relatively fast. Will have to test it first though. Changing the pivot of a mesh will be the much more easy task then.

If all goes well, the new mesh data type I imagine will support UVs and other properties as well. I think by using the right abstractions, UVs won't make this process much harder. (It will just take a bit longer of course..)
