### ISSUE TITLE
Feature Request / Unexpected behaviour : Get List Element WRAP

### ISSUE THREAD

**Issue by lignazio** [JacquesLucke/animation_nodes#753]
In the "Get List Element" node I was expecting that the wrap option would "wrap" the index.
For example, in a list of three elements: 
0 > 0, 
1 > 1,
2 > 2,
3 > 0,
4 > 1,
etc.
Instead, if I use as input a number larger than the last element index the node will return null.
I know I can use a math node with the modulo operator but I was wondering if that shouldn't be the default behaviour for the wrap option.

**Comment by JacquesLucke** [comment]
good idea actually.
The wrap option allows you to use eg -1 as index to get the last element of the list. But I think you are right, it should also do what you suggest.
