### ISSUE TITLE
[Idea] Negative Value Output for Constants Node

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#761]
Not a big deal, just to keep the whole tree a bit more tidy.  :)

**Comment by OmarSquircleArt** [comment]
Was there some function that required negative Pi or e in your node tree?
I never encountered such function, at least not purely because sign can be introduced somewhere else using either subtraction in polynomials or negative multiplication in coefficient.

**Comment by LeonCheung** [comment]
As I said, , just keeping the whole tree a bit more tidy by saving extra math node(s). :)
