### ISSUE TITLE
Strange Installation Issue

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#762]
Hi AN Team, just wanted to report very strange and annoying installation issue on Windows 7 machine.

I downloaded a couple of Blender Build just now. I was testing Eevee Render, was trying to install Animation Nodes and failed right there. It does now show up.

So, I open my usual Blender official build and Animation Nodes is no longer there, not working, not displaying under Add-On. I tried removing and reinstalling but that makes things worst. It simply does not work.

I am now trying to clean any trace of previous install, maybe there was clashing issue. Hopefully can make it work again.

Installing and Updating == is actually quite painful process at the moment.

**Comment by enzyme69** [comment]
![prtscr capture_30](https://user-images.githubusercontent.com/3952687/29198908-624831e0-7e8b-11e7-86da-12957e416052.png)

Currently deleting these guys, maybe clashing...

**Comment by enzyme69** [comment]
Deleted all, reinstall, still not working. I think the latest AN from this Github is not installing properly. Something to investigate :(

**Comment by enzyme69** [comment]
![prtscr capture_31](https://user-images.githubusercontent.com/3952687/29198991-2af3f2a0-7e8c-11e7-9b86-e066cce1d467.png)

GraphicAll one works. Github one said: module installed, but then nothing. I installed GraphicAll one, it at least shows up under Preferences.

**Comment by enzyme69** [comment]
I actually really want this to work with Blender bleeding edge build with Eevee, but I think I have to wait.

Both Sverchok and Animation Nodes does not work with it yet. Maybe I can use driver or other means. 

![prtscr capture_31](https://user-images.githubusercontent.com/3952687/29199028-9c546c7c-7e8c-11e7-878d-b55540fbb69c.png)

Looking forward for improvement thanks!

But just that Github one really does not work on Windows 7.

**Comment by JacquesLucke** [comment]
you don't always need to close you own issues if it is not solved yet (though in this case it is correct).

Two things:
1. When you download the addon from GitHub, DON'T download it using the old "download as zip" approach. Instead, go to the releases page and download it from there.
2. AN does not support Blender 2.8 yet. Therefor.it is not possible to use it with Eevee atm.
