### ISSUE TITLE
Reassign and Vectorization

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#763]
After 2.0, I kept on realizing that in many cases I have to use loops to use reassign feature, which means I cannot enjoy the huge performance leap by vectorization instead, simply due to it. Not sure if these two things are really incompatible as fire and water. Or, is it possible to have them working together without using loop?

**Comment by JacquesLucke** [comment]
Totally depends on what you want to do..
In general the reassign feature only makes sense in a loop. However many of its use cases can be simulated in other ways in theory. 
For example we could have a node that takes a list like `[2, 5, 1, 3, 2]` and outputs `[2, 7, 8, 11, 13]` (adds the numbers together). This new list can then be used further.
The same can be done with vectors of course.

**Comment by LeonCheung** [comment]
However the reassigned values for the next input really reply on the previous round of calculation, especially for complex calculations (more complex than the case you exampled), which can be hardly simulated, e.g. with realtime logic.

**Comment by JacquesLucke** [comment]
True. I'm not quite sure what you want to suggest..

There are certainly more cases where you can do some precomputation but if you need all that control you'll have to go the more flexible route and use loops.

**Comment by LeonCheung** [comment]
Alright. Just wondering if it would be possible to implement similar mechanism to vectorization. Appearently not.

**Comment by JacquesLucke** [comment]
I cannot think of one atm, that does not mean that there is no way though.

Maybe, in a distant future, it will be possible to let loops run as fast as other vectorized nodes...
