### ISSUE TITLE
AN Bone Access via Object Attribute Output (Reloaded)

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#764]
I feel that maybe Animation Nodes next node can be Bone related? Bone Info is really cool, but would be nice to be able to access the Bone transform easier, not using Script Node.

I probably have asked something similar in the past. Funny thing is Object Attribute Output for Armature object cannot directly target the bone poses location? Or I am doing it wrong?

Sverchok:
![prtscr capture_37](https://user-images.githubusercontent.com/3952687/29209116-58c5facc-7ed0-11e7-8a4f-6e865a4bf7b6.png)

**Comment by enzyme69** [comment]
I feel that this should work. But ....

![prtscr capture_38](https://user-images.githubusercontent.com/3952687/29209253-ef2663bc-7ed0-11e7-8c71-9ff6dc5fae1f.png)

**Comment by enzyme69** [comment]
I am looking at this but feel dissatisfaction.
https://github.com/JacquesLucke/animation_nodes/issues/103

**Comment by LeonCheung** [comment]
If you mean the Armature Info node that has been implemented to 2.0.
