### ISSUE TITLE
Project on Spline Output

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#765]
I think it could cause possible error.

![project](https://user-images.githubusercontent.com/494788/29353115-b2049d40-829b-11e7-9587-dc1eddac97ac.png)

**Comment by LeonCheung** [comment]
Or it's just the Viewer gets its own precision limit?

**Comment by JacquesLucke** [comment]
This is just the viewer. Should be corrected anyway.

`9e-05 = 0.00009`

**Comment by LeonCheung** [comment]
k thx
