### ISSUE TITLE
How to Combine Matrix Euler and Matrix Position?

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#767]
![prtscr capture_26](https://user-images.githubusercontent.com/3952687/29439854-f25c801a-8403-11e7-895b-e2060ca9ed95.png)
[AN_Resampling_Basic_006_2017_08_18_00_56.zip](https://github.com/JacquesLucke/animation_nodes/files/1232999/AN_Resampling_Basic_006_2017_08_18_00_56.zip)

If we have Matrix Euler and wanting to combine with Matrix Points, do we need to firstly extract the Rotations and put it back again? Or is there a better way?

**Comment by JacquesLucke** [comment]
you can use the Compose Matrix node. No need for the Translation Matrix node then.
Also you can take the euler output of the  Direction to Rotation node instead of the Matrix output.

**Comment by enzyme69** [comment]
![prtscr capture_30](https://user-images.githubusercontent.com/3952687/29450677-f6e88270-8442-11e7-94d7-2cd0f0104b69.png)

Hmm.. ok make sense in this case. So apparently merging Matrix is not normal thing via node.
