### ISSUE TITLE
AN Project on Spline does not work with Looped Circle

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#768]
[project_spline_test_002_2017_08_18_01_01.zip](https://github.com/JacquesLucke/animation_nodes/files/1233009/project_spline_test_002_2017_08_18_01_01.zip)
![prtscr capture_27](https://user-images.githubusercontent.com/3952687/29439943-929478f8-8404-11e7-8c1a-7d1abe73f80c.png)

Not sure why looping Circle does not work as expected with Projection. Maybe I need to resample it first?

**Comment by enzyme69** [comment]
[project_spline_test_003.zip](https://github.com/JacquesLucke/animation_nodes/files/1233018/project_spline_test_003.zip)
![prtscr capture_29](https://user-images.githubusercontent.com/3952687/29440085-6e03d67c-8405-11e7-9aa1-871779d5f27f.png)

This seems to work though. But there should be documentation telling that closed Curve will not work and need to resample.

By the way, the Project On Curve is very cool, but I was wondering, if animator just want to slide an object across Curve, would normalized value Motion Path will be simpler? I realized, if I were to reference other object position, I get this jitter2 animation when trying to slide object along path.

**Comment by enzyme69** [comment]
And... it also Jitter Pop a lot with rotation.

**Comment by JacquesLucke** [comment]
Oh the fact that it does not work on a curved spline is actually a real Bug. Will fix that soon.

If you just want to slide an object along a spline you might want to use the Evaluate Spline node.

**Comment by JacquesLucke** [comment]
The flickering in you video is weird indeed, can you send me the file?
