### ISSUE TITLE
Naming suggestion... Spline Output or Spline Object Output instead of Object Output

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#769]
![prtscr capture_28](https://user-images.githubusercontent.com/3952687/29439994-e173cb54-8404-11e7-968f-ad83dafc0fc6.png)

Probably for more like a smooth usability thing. If we can kind of setup keyword to quickly search a node.

I always found I hit the wall whenever I try to Ctrl+A and search for Spline Output, I type "spline output" and nothing related to output.

**Comment by enzyme69** [comment]
I know there is Curve Object Output,... but yeah just Spline and Curve. Just like String and Text.

**Comment by JacquesLucke** [comment]
I see what you mean, thought of that myself as well multiple times but I'm not sure..

I just use Blenders terminology here. A spline is a single "curve". 
Also this node is part of a family, the naming is based on the object type names in Blender:
- Mesh Object Output
- Curve Object Output
- Text Object Output

Maybe the name will change at some point but not very soon except many more people want that.

**Comment by OgierM** [comment]
Maybe there is a way to make some meta tags that give you better search results?
