### ISSUE TITLE
Multi Vector Points Projection on Spline is surprisingly slow...

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#770]
![prtscr capture](https://user-images.githubusercontent.com/3952687/29451601-95b2bdc8-8446-11e7-8e37-f5cf8621af52.png)
[AN_projectSpline_007_2017_08_18_08_53.zip](https://github.com/JacquesLucke/animation_nodes/files/1233842/AN_projectSpline_007_2017_08_18_08_53.zip)

Wonder if I am doing it wrong, or maybe currently not optimized for this yet.

**Comment by JacquesLucke** [comment]
Finding the closest point on a bezier spline unfortunately is a complicated process. Therefor the node is currently not very optimised. You can expect better performance when you use a Polyspline (maybe create it dynamically in AN (not inside the loop)). 

There is still a lot of room for optimizations as well though :)
