### ISSUE TITLE
Spline Connect Invert

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#771]
Hi, 

Spline Connect node connects splines, but after it's connected, is it possible to get output of just the generated connections? Basically the inverted result of the spline list which is inputed.
I know it's possible with straight lines, but how to retain bezier handles?

![screenshot 1](https://user-images.githubusercontent.com/17803543/29456319-cfd64bc4-841d-11e7-88ac-25740d5e51f1.jpg)

**Comment by JacquesLucke** [comment]
I could add this as an option to the Connect node. What do you need this for?

For now you can recreate the behavior like so:
![spline connections](https://user-images.githubusercontent.com/5881326/29456982-59493a8e-8418-11e7-9cb4-627c4a5c36f2.PNG)

The performance is not optimal but maybe it is good enough for what you are trying to do.

**Comment by karlisstigis** [comment]
Thanks, will check this out. I need this to have the ability to resample the source splines and connection splines seperately. 

Also I want to say that constructing lines now is really powerful, but the handle control is somewhat confusing, because it needs 2 vectors per point and sometimes it's hard to understand which vector does what. A real mindbender. Not sure how it could be presented clearer tho.
