### ISSUE TITLE
"Get Spline Length" not effected by hooks

### ISSUE THREAD

**Issue by bartoszek** [JacquesLucke/animation_nodes#772]
Notice some quirk when trying to use `Get Spline Length` with _hooked_ spline.
Looks likes hook modifier isn't taken into account when calculating the `Length` value.
![screencast_20 08 2017_17 14 08](https://user-images.githubusercontent.com/1213348/29496204-4bf70372-85ce-11e7-9a6d-1cae5e2db19e.gif)

**Comment by JacquesLucke** [comment]
This is a known limitation. Checkout the discussion here: https://github.com/JacquesLucke/animation_nodes/issues/711
