### ISSUE TITLE
I cannot install Animation Nodes

### ISSUE THREAD

**Issue by Miszla** [JacquesLucke/animation_nodes#775]
Hi! I have already installed Animation Nodes and I wanted to update it, so I uninstalled earlier version and tried to install newer, but after clicking "Install from file" at User preferences and choosing animation nodes zip file addon is not visible on the addons list and I can't check it. Is it any way to install addon manualy?

**Comment by JacquesLucke** [comment]
Please checkout this: https://github.com/JacquesLucke/animation_nodes/issues/740

**Comment by Miszla** [comment]
Thank you. Sorry for my stupidity. You have to answer these questions all the time :/
