### ISSUE TITLE
Request: Bake Atribute Output Node

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#777]
Is this possible. It will be huge timesaver. I guess that the new Action Nodes will reduce the need for baking so maybe this feature won´t be needed  soon.

**Comment by JacquesLucke** [comment]
I don't really understand what you mean by a "Bake Attribute Output" node. (Maybe you need the Set Keyframes node?)

Also baking will still be needed with the new action nodes, more details on that later :)

**Comment by YorsLosilla** [comment]
I was refering to this one:

http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/object/object_attribute_output.html

**Comment by YorsLosilla** [comment]
Got it!!!  Didn´t know about that node. Is really powerfull!!!
