### ISSUE TITLE
Transform and Replicate Nodes

### ISSUE THREAD

**Issue by piegamesde** [JacquesLucke/animation_nodes#778]
The Transform XXX and the Replicate XXX nodes are basically the same, except that replicate takes in a list of Matrices and transform only one. This is a confusing behavior and I actually went to create my own replicate nodes because I didn't know of them and how they were called. The name does not say anything to me. My suggestion: merge the Replicate XXX into the Transform XXX nodes.

**Comment by JacquesLucke** [comment]
The difference is that the Replicate XXX nodes can be used to duplicate the incoming data multiple times while the Transform XXX nodes just move it. Their use cases are quite different.

I agree that this is not totally clear, however merging them is not as easy as it might seem at first (afaik).

**Comment by piegamesde** [comment]
I didn't know about this. So we have an object input and a transform input and both of them might be a single value or a list and depending on this the single value gets duplicated until it matches the size of the list? Does it work like this? Could it work like this? This is my intuitive understanding of those nodes.

**Comment by stansu** [comment]
i think Replicate XXX node can replace Transform XXX node.
