### ISSUE TITLE
Animation nodes does not install in 2.79

### ISSUE THREAD

**Issue by Dan0268** [JacquesLucke/animation_nodes#779]
Hi guys,

I wanted to give animation nodes a try and I managed to get it in 2.78c but in 2.79 I get this error:

![animation nodes error](https://user-images.githubusercontent.com/31425080/29799782-70156488-8ca9-11e7-95ff-1785f0cbd180.jpg)

What's a bit odd is that after doing the, in the same session there is an animation nodes button in the node editor. But it doesn't stay there. Could you help me fix this? The version is blender-2.79.0-git.738d942-windows64. Thanks!

I've tried the fixes that were suggested in the solved section, it worked for 2.78 (deleting them from the scripts folder and documents folder basically) but it doesn't for 2.79. And I've seen people with the same RC2 build using it and it works for them.

**Comment by JacquesLucke** [comment]
Please use the  release candidate for now.

More info about this problem can be found here: https://blenderartists.org/forum/showthread.php?436856-***-Addons-Breakages-2-79-master-Nightly-Builds)***

**Comment by Dan0268** [comment]
I could swear that's what I did! I got the one from the "Bleeding Edge" section, I thought that was the RC2 because it said that. I didn't see that there was an official one. Works now yay thanks!

**Comment by JacquesLucke** [comment]
I didn't know that either until yesterday..
