### ISSUE TITLE
Mix using Falloff Nodes. 

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#781]
Hi,

I love the new falloff system, but I think there is one important thing we're missing and that's to have a mix node which takes falloff as factor and not just a float number.

Current Offset Matrix/Vector nodes takes a parameter and adds some change on top of it, but if I have 2 lists of completely different coordinates, I still have to use the old principle of calculating distances and so on.
![falloff mix](https://user-images.githubusercontent.com/17803543/29921725-5bfb13cc-8e5b-11e7-9f74-34fc4c769d7f.jpg)

**Comment by JacquesLucke** [comment]
Have you checked the `Evaluate Falloff` node?

https://youtu.be/GF5krw0Z8QU?t=8m47s

**Comment by karlisstigis** [comment]
Oh, didn't know how exactly it works. This seems to solve my problem!
