### ISSUE TITLE
Install problem on Mac

### ISSUE THREAD

**Issue by GaviaImmer** [JacquesLucke/animation_nodes#782]
Downloaded both macos.zip & macos.alternative.zip

It downloads in Blender but when I tick the check box I get white letters on black background saying:

 /2B654B5C-1881-4E80A235449C44E79557/d/blender.app/Contents/MacOS/,,/Resources/2.78/scripts/modules/addon_utils.py", line 330, in enable  
 s/animation_nodes/_init_py", line 57, in <module> 

 
Computer: mac os Sierra   imac (Retina 4k 21.5 inch, late 2015)
Blender version: 2.78

**Comment by JacquesLucke** [comment]
Please send a screenshot of the error message.

Also try to find the addon folder of your Blender version and remove all folders that are called something with "animation nodes".

**Comment by GaviaImmer** [comment]
I sent the screen shot to your email...as I could not find an attachment here.....though I have removed all the Node animation downloads it says that I have multiple versions but cannot see where.....

**Comment by GaviaImmer** [comment]
I have looked and searched through all my download files and all files and nothing re: node animation or animation node(s) is there............

**Comment by JacquesLucke** [comment]
got it.
Take a look at the error message again. There is one line with "raise Exception". The line before that contains a file path. Try to find that in the Finder (or in another File Explorer, not sure how they are called on a mac).

**Comment by GaviaImmer** [comment]
Yes I saw that but cannot find the same trail…..but will keep checking and hopefully clean out any remnants……thanks!

**Comment by JacquesLucke** [comment]
Maybe the path is hidden by default. You can try to enable the visibility of all folders, however I don't know how that works on a mac, you should google this a bit..

**Comment by GaviaImmer** [comment]
Hey JacquesLucke, After about 2 hours of screwing around on my Mac I have located and deleted the rogue file…and I have re downloaded your files and successfully got it into Blender.

Thanks for the help…..I am so looking forward to delving into your amazing add on…..

all the best

**Comment by JacquesLucke** [comment]
ah great, sry for the circumstances.

Can you share what you did to help others in the future?

**Comment by GaviaImmer** [comment]
Solution to a download of the node animation add-on that went wrong on my Mac.

When it failed to work I removed it in the add on window and checked in my downloads to see if there was any node animation file…..there did not appear to be but when 
I tried to reload the add on there was a note that said under  “Exception” that it was still in my computer and therefore could not be added again….it also gave a File path.
Sounds simple….follow the file path and then delete it from there and start over…..but I was unable to follow the file path because since OS X Lion, Mac has been hiding 
the Library folder……

To un-hide the Library Folder and proceed with the path to the rogue file do as follows:  …..You have to hold down the option Key (alt key) and select the Go menu …see below:


Once in the Library File go to Application Support/Blender etc and find the bad file and delete it……

Having done all this I was able to successfully download and add JacquesLuckes’ animation_node add-on.  And as frustrating as the journey was it was well worth it.
The add on is absolutely amazing!

PS Thanks to Tom Nelson of lifewire for the help with my Mac.


Thanks for your help JacquesLucke.




>

**Comment by JacquesLucke** [comment]
thank you :)

**Comment by JoelGodin** [comment]
Had the same issue.
Small difference on my system was they were in >user/Library, not >Macintosh_HD/Library.

thanks

**Comment by jasperges** [comment]
@JoelGodin: Not that it matters much (anymore), but I think @GaviaImmer also had it in his <user>/Library folder. The system Library folder is always hidden (if I'm not mistaken) in Finder also when pressing <kbd>Option</kbd> (<kbd>Alt</kbd> for non-Apple keyboard).

@JacquesLucke Is it an idea to have the places where an older version of the addon could be installed mentioned in the documentation? For Mac and Linux I could do that. Or maybe even provide a separate script to remove older versions or make this an option in the Animation Nodes itself? I could help with that as well.
