### ISSUE TITLE
Feature Request: Spline radius and tilt in Evaluate Spline and Get Spline Samples

### ISSUE THREAD

**Issue by kurzemnieks** [JacquesLucke/animation_nodes#786]
Is it possible to add radius and tilt output for Evaluate Spline and Get Spline Samples nodes? 
This would be very very useful to use full potential of splines!!

**Comment by JacquesLucke** [comment]
I worked on this a few days ago. It will be available in the next release: https://twitter.com/JacquesLucke/status/904744028326985729
