### ISSUE TITLE
A problem with installation of animation node on 2.79 version

### ISSUE THREAD

**Issue by digitypo** [JacquesLucke/animation_nodes#788]
Hi, 
I installed animation node on 2.78c, Mac(10.12.6 / Sierra) It wasn't any problem.
However, I have a problem with 2.79 version. Even though I uninstalled animation node followed by instruction. I got this message.

https://www.dropbox.com/s/x6v3h3fk8etywa0/error.png?dl=0

How can I solve this problem?
Oh, I have been using python 2.7 and 3.6.
Thank you for your concern.

Best,

**Comment by JacquesLucke** [comment]
In the error message is the path to the `__init__.py` file.
When you follow this path and stop in the `addons` directory you will find multiple versions of AN. Delete them all and install AN again.

This is quite a common error atm. I will try to improve the error handling for this case in the next version.

**Comment by digitypo** [comment]
It works!!
Thank you.
