### ISSUE TITLE
Installation issue MacOS 10.12.6 blender 2.79

### ISSUE THREAD

**Issue by sshorter** [JacquesLucke/animation_nodes#791]
I don't see any clear error but the add-on is not installing from the file.  The python console message says "modules installed () ..." and the add-on does not show up in the list.  Here's a screenshot showing the message and the lack of add-on.

![screenshot 2017-09-21 11 13 30](https://user-images.githubusercontent.com/19290581/30703638-487cf900-9ebe-11e7-95ee-677695e4ae5d.png)

**Comment by JacquesLucke** [comment]
I guess you used the "Download Zip" button on the GitHub main page.
Please go to the release page and download the addon from there.

You will have to remove the old installation first. the path will be in the error message.

**Comment by sshorter** [comment]
You guessed correctly, that did the trick, thank you for the fast response.
