### ISSUE TITLE
Not working with Official 2.79 version of Blender

### ISSUE THREAD

**Issue by choyce7** [JacquesLucke/animation_nodes#792]
I downloaded the newest version of blender, installed the animation_node add-on and I am getting an error regarding numpy not being installed.  Is there a simple way to install numpy?

**Comment by JacquesLucke** [comment]
hmm numpy should definitely be installed in official builds. Except your system python version is used but this is relatively rarely the case. Which OS do you use?
And where exactly did you download the Blender build?

**Comment by choyce7** [comment]
I am on Windows 7 and I downloaded the file from Blender.org.

**Comment by choyce7** [comment]
This is what comes up when I open the console.


PYTHON INTERACTIVE CONSOLE 3.5.3 (default, May 20 2017, 19:10:40) [MSC 
v.1800 64 bit (AMD64)]

Command History:     Up/Down Arrow
Cursor:              Left/Right Home/End
Remove:              Backspace/Delete
Execute:             Enter
Autocomplete:        Ctrl-Space
Zoom:                Ctrl +/-, Ctrl-Wheel
Builtin Modules:     bpy, bpy.data, bpy.ops, bpy.props, bpy.types, 
bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports: from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

**Comment by JacquesLucke** [comment]
when happens when you type `import numpy` in the console in Blender?

**Comment by choyce7** [comment]
I get this:


Traceback (most recent call last):
   File "<blender_console>", line 1, in <module>
   File "C:\Program Files\Blender 
Foundation\Blender\2.79\python\lib\site-packages\numpy\__init__.py", 
line 180, in <module>
     from . import add_newdocs
   File "C:\Program Files\Blender 
Foundation\Blender\2.79\python\lib\site-packages\numpy\add_newdocs.py", 
line 13, in <module>
     from numpy.lib import add_newdoc
   File "C:\Program Files\Blender 
Foundation\Blender\2.79\python\lib\site-packages\numpy\lib\__init__.py", 
line 8, in <module>
     from .type_check import *
   File "C:\Program Files\Blender 
Foundation\Blender\2.79\python\lib\site-packages\numpy\lib\type_check.py", 
line 11, in <module>
     import numpy.core.numeric as _nx
   File "C:\Program Files\Blender 
Foundation\Blender\2.79\python\lib\site-packages\numpy\core\__init__.py", 
line 21, in <module>
     from . import _internal  # for freeze programs
   File "C:\Program Files\Blender 
Foundation\Blender\2.79\python\lib\site-packages\numpy\core\_internal.py", 
line 14, in <module>
     import ctypes
   File "C:\Program Files\Blender 
Foundation\Blender\2.79\python\lib\ctypes\__init__.py", line 7, in <module>
     from _ctypes import Union, Structure, Array
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by JacquesLucke** [comment]
do you have a 32 bit machine?
If yes, it might be that you can't use AN atm...

**Comment by choyce7** [comment]
No, I'm on a 64 bit

**Comment by choyce7** [comment]
Hello Jacques,

I was able to get the animation nodes back by uninstalling Blender 2.79 
and going back to 2.78c.  Of course, I am using the 1.6.0 version.  I 
was going to try reinstalling the 2.79 again to see if the animation 
nodes will be brought over to the new version.  If so, I will let you know.

Thanks for trying to help me.  You have a wonderful product and I have 
big plans for this add-on!

Deborah
