### ISSUE TITLE
Trigger Action on Particle Killed

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#795]
What would be the best way to trigger Action / Animation that happens once only, say, in scenario where particles hit floor and died. 

Instead of a pop, I would like to kind of start animation / action from that Time.

[particle_kill_004.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1352051/particle_kill_004.blend.zip)

**Comment by enzyme69** [comment]
![screen shot 2017-10-03 at 22 26 01](https://user-images.githubusercontent.com/3952687/31123102-39ef9a20-a88a-11e7-8a12-762b16a7d07b.png)

Can we have some kind of event watcher, checking for particles killed, get that value and run a certain action, one time only?

Maybe printing out: "particle died at position X, Y!"

**Comment by JacquesLucke** [comment]
That might be possible in the future but atm AN does not have this functionality. 
For now you need to do some scripting to be able to archieve this effect, it is not an easy task.

**Comment by enzyme69** [comment]
Ok thanks Jacques, maybe this question will be answered in the future.

I think I should look at some game programmings nodes.

Maybe each points / particles need some kind of state that can be logically does something.

State: if particle killed && state is OFF, then trigger something one time. And also track how long it has died.

To be continued....
