### ISSUE TITLE
Not available after installation - B 2.79 win7

### ISSUE THREAD

**Issue by 3pointedit** [JacquesLucke/animation_nodes#797]
I have downloaded official Blender release build of 2.79 (Hash: 5bd8ac9), cleaned all older AN versions from blenders install script folder AND the AppData\Roaming path.
I have checked that numpy is installed in this build of Blender (it does)
I have checked that my PC has VisualC++2015 installed (it does)
I made sure that Autorun Scripts is active.

When I install AN 2 from the zip file Blender tells me (in the Info window) that "Modules Installed () From .... into..." the AppData path, but the addon does not appear in the addon list.

**Comment by JacquesLucke** [comment]
This is more a "bug" in Blender than in AN. I guess you downloaded the source code instead of a compiled release. Please go to the Releases page and download a real build.

**Comment by 3pointedit** [comment]
Oops I did exactly that, I am so used to grabbing a .py from the clone/download button that I missed your download page. Thanks
