### ISSUE TITLE
Unable to install Animation Nodes on Blender 2.79

### ISSUE THREAD

**Issue by FlashBlaze** [JacquesLucke/animation_nodes#799]
I'm getting an error message telling me I have multiple versions of Animation Nodes installed. But I can't find any versions installed on searching. Please help.

**Comment by JacquesLucke** [comment]
https://github.com/JacquesLucke/animation_nodes/issues/798
It might be a different path in your case depending on your operating system. You can see the path of the addon directory in the error message.

**Comment by FlashBlaze** [comment]
Is it okay if I post a screenshot?

**Comment by JacquesLucke** [comment]
sure

**Comment by FlashBlaze** [comment]
![ss](https://user-images.githubusercontent.com/13968549/31316097-bca6a46a-ac43-11e7-86fd-bb66027e70dc.png)

**Comment by JacquesLucke** [comment]
Find this path in the windows explorer: `C:\Users\Neeraj\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\`
There you'll see multiple Blender versions. Remove them and then install AN again.

**Comment by FlashBlaze** [comment]
That solved it! Thanks a lot for replying early and solving my issue.

**Comment by JimCoote** [comment]
I have a slightly different issue with Animation Nodes. After selecting 'Install addon from file' I selected the entire folder I downloaded and this opened up OK. However I have no idea which file to select. Is it one of the .py ones? I'm on a Mac Book Pro using Blender 2.79

**Comment by JacquesLucke** [comment]
you have to select the .zip file you downloaded (don't unpack it manually).

**Comment by JimCoote** [comment]
The problem is that I cannot select the folder without unpacking it. I have tried both the macOS.zip files and the source code, and have exactly the same trouble.

**Comment by JacquesLucke** [comment]
hm I don't know why this happens. Maybe there is a filter activated in the file browser?
You need the macos release, the source code won't help you here.

If all of that does not work you can also install AN manually by copying the unpackt `animation_nodes` folder into blenders addons folder.

**Comment by JimCoote** [comment]
Thanks Jacques, I did as you advised and dropped the entire folder into the Addons folder, and it seems to be working fine. 

After downloading I was left with a folder called animation_nodes but no sign of anything with a .zip suffix, (I checked just about every subfolder). I tried adding .zip in case downloading caused some kind of misnaming, but no luck. Oddly when I looked in my trash bin, (where I dumped failed attempts), and there appeared to be some zip folders there. I suspect that the downloading of some types of zip files is going wrong on my Mac somewhere. Anyway, all OK now. Thanks again.

**Comment by JimCoote** [comment]
Doh! Found the answer. Safari was set to automatically open any safe files. This meant that any zipped folders were always unwrapped after downloading. Simply right clicking and choosing compress gave me the zip folder back. I presume this is why previously I could see the zip folder in the trash but not elsewhere.

**Comment by JacquesLucke** [comment]
ah that explains it! Haven't thought about that. Thanks for sharing the solution.

**Comment by unoseistres** [comment]
Where did you find the multiple add-on files? I cannot find them under my scripts, under add-ons....are they called something different other than "animation_node"?

**Comment by azwa1321** [comment]
i also have the same problem with him but i don't see the directory show in my laptop (c:\users\Windows10\AppData\.......) there are no AppData in my C:\  ..how can i solve this problem ..? thanks in advance ..

![untitled](https://user-images.githubusercontent.com/33181155/37389760-7df104c6-27a0-11e8-86ad-d03db1b7e365.jpg)

**Comment by JacquesLucke** [comment]
Hey, the `AppData` folder is hidden by default. 
Maybe that helps: https://www.howtogeek.com/howto/windows-vista/show-hidden-files-and-folders-in-windows-vista/

**Comment by videodromex** [comment]
I'm also using 2.79, when I add the .zip to my addons it does create a folder in my "...AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\" folder, but the add on is not visible in my preferences, thus I can't activate it. I've rebooted blender twice. nothing gets added to the _pycache_, not sure if this is relevant.

**Comment by JacquesLucke** [comment]
please tell me exaxtly where you downloaded the compiled AN build.

If you did not download a release from https://github.com/JacquesLucke/animation_nodes/releases, you can try that.

**Comment by videodromex** [comment]
Thanks a lot! that allowed me to install the addon, now, when I tried to bake average on an mp3 I get the following error:
![animationnodeerror](https://user-images.githubusercontent.com/5829573/38167907-3ebccf7e-34fc-11e8-8956-2138e2d2f937.PNG)

**Comment by JacquesLucke** [comment]
Hope that helps: https://github.com/JacquesLucke/animation_nodes/issues/885

**Comment by Eqysterika** [comment]
Hello, first I want to thank for the great work done with this addon, I am surprised with the magnificent things that it has. Unfortunately I got the error when I was installing it in the new **version 2.79 ... I have Mac** and I can't find the way to **uninstall the previous versions**. Could you help me?

![captura de pantalla 2018-06-27 a la s 12 43 40](https://user-images.githubusercontent.com/6155305/41990712-e78758da-7a08-11e8-86e4-47a19d19bdb1.png)
![captura de pantalla 2018-06-27 a la s 12 48 19](https://user-images.githubusercontent.com/6155305/41990713-e7993870-7a08-11e8-872b-96e74d5439ea.png)
![captura de pantalla 2018-06-27 a la s 12 48 29](https://user-images.githubusercontent.com/6155305/41990714-e7ada4cc-7a08-11e8-9fb3-dd61c03b4346.png)

**Comment by Omeleto** [comment]
I got an error message:
![image](https://user-images.githubusercontent.com/40064473/43064577-f971564a-8e67-11e8-891c-461b7aec088b.png)
I don't know how to solve this. Please respond

**Comment by skoorbatase** [comment]
I'm having the same problem on MacOSX.   "Uninstall the previous version" - but there doesn't seem to be a previous version anywhere


> Hello, first I want to thank for the great work done with this addon, I am surprised with the magnificent things that it has. Unfortunately I got the error when I was installing it in the new **version 2.79 ... I have Mac** and I can't find the way to **uninstall the previous versions**. Could you help me?
> 
> ![captura de pantalla 2018-06-27 a la s 12 43 40](https://user-images.githubusercontent.com/6155305/41990712-e78758da-7a08-11e8-86e4-47a19d19bdb1.png)
> ![captura de pantalla 2018-06-27 a la s 12 48 19](https://user-images.githubusercontent.com/6155305/41990713-e7993870-7a08-11e8-872b-96e74d5439ea.png)
> ![captura de pantalla 2018-06-27 a la s 12 48 29](https://user-images.githubusercontent.com/6155305/41990714-e7ada4cc-7a08-11e8-9fb3-dd61c03b4346.png)

**Comment by OmarSquircleArt** [comment]
This is not the only path where blender addons are installed. Addons installed through the install operator will be installed in a user specific path, in your case, it is in `/Users/minuto31/Library/Application Support/Blender/2.79/scripts/addons/`.

**Comment by skoorbatase** [comment]
Thank you!  by typing - bpy.utils.script_paths("addons") - into the console I was able to find an alternate path that'd I'd created when I was trying to get an older version to work last year.  After deleting that... ALL SYSTEMS GO!  Amazing Addon! Thank you Jaques!

**Comment by janmatys** [comment]
Hi there I installed the .zip using the Blender standards (from preferences) and the addon will appear in the list, but when clicked (activating) Ive got this message...

![img](https://user-images.githubusercontent.com/37245747/46489800-ac3f7900-c806-11e8-8bb7-0366326716ac.jpg)

...Im using Blender 2.79a and for sure DL the version for Windows. As an additional info I could provide the v1.6 of AN installed WITHOUT problems (only v2.0 and 2.1 are "broken")

  Sincerely, Jan

**Comment by OmarSquircleArt** [comment]
@janmatys Please check the [troubleshooting guide.](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html#troubleshooting).

**Comment by janmatys** [comment]
@OmarSquircleArt I found NOTHING in that guide...

**Comment by janmatys** [comment]
Anyone having the same issue try to install 14.14.26429 C++ Redist 2017 x64 cause I think that solves the problem (could be that one cause I have NO issue now ;) ).
