### ISSUE TITLE
Construct mesh from edges or vertices.

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#801]
Hi,

I wonder, is there an easy way of filling edges with polygons or constucting mesh just from vertices automatically? It could be hard to do it from just vertices, but vertices and edges should be enough to fill them. I know it's possible to do it if the vector sorting is possible, but if the mesh is a chaos, it's not really possible to do it. Or is it?

![screenshot 1](https://user-images.githubusercontent.com/17803543/31402145-cae71c24-adfd-11e7-8c99-773d4f2b3eb2.jpg)

This is what I get:

![screenshot 1](https://user-images.githubusercontent.com/17803543/31402322-529efc18-adfe-11e7-8980-eb8b01b35615.jpg)

**Comment by JacquesLucke** [comment]
hm I see the problem, where does the data come from?
I don't know a good algorithm to tackle this task right now.. maybe @OmarSquircleArt has an idea?

In your example you created one giant polygon that uses all the points as, this is definitly not what you want.

I guess I could come up with an algorithm that fills in triangles only relatively easily (especially using the new mesh data structures I developed a few days ago), filling quads and ngons feels much more difficult,

**Comment by OmarSquircleArt** [comment]
Not sure why you deleted the polygon info when know you are going to need it. It seems like your problem could be solved by changing your workflow.
The only method I know to polygonize a list of vectors is the Delaunay Triangulation method but it only works in 2D as far as I know, so it worn't work in your case.

I remember reading a paper about mesh reconstruction from point cloud data, may be I can take a look there.

**Comment by karlisstigis** [comment]
:) That is not a real project, I made it as an example to the problem. I have seen that Houdini can fill up edges quite easily in some videos. Cant say I remember if it was the same situation.

**Comment by OmarSquircleArt** [comment]
So you have the edge info and want to get the polygon indices? That seems very much doable.
I will get back to you.

**Comment by jayhouz** [comment]
# have you tried select all in edit mode and hitting the F key? <h3>

**Comment by stansu** [comment]
sverchok can do this by 'fill holes' node
![image](https://user-images.githubusercontent.com/9460236/37199462-abba0ca0-23bc-11e8-88da-04e1fbccfdf9.png)
[fill_hole.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1796210/fill_hole.blend.zip)
