### ISSUE TITLE
Not Working With 2.79 Official, Downloaded from Blender.Org

### ISSUE THREAD

**Issue by jayhouz** [JacquesLucke/animation_nodes#802]

**Comment by jayhouz** [comment]
The error I am getting is Python Version Conflict, 
Blender 2.79 is using Python 3.6.2

**Comment by jasperges** [comment]
Hi @jayhouz. The official release of Blender 2.79 (which you can download [here](https://www.blender.org/download/)) uses Python 3.5. You probably downloaded a version from the [buildbot](https://builder.blender.org/download/), that is using Python 3.6 (upcoming releases of Blender will use Python 3.6).
