### ISSUE TITLE
Not Working With 2.79 Official, Downloaded from Blender.Org

### ISSUE THREAD

**Issue by jayhouz** [JacquesLucke/animation_nodes#803]
The error I am getting is Python Version Conflict. 
Blender 2.79 uses Python Version  2.6.2

**Comment by jayhouz** [comment]
I am not good at coding, I tried compiling using both Anaconda and Visual Studio 2017 I keep getting an error "unable to find vcvarsall.bat"  even tried installing Visual C++ 14, still not working, getting same error. 

I am kindly requesting if you could compile with Python 2.6.2

I am not able to enable the addon in Blender User Preferences.

**Comment by jasperges** [comment]
Hi @jayhouz. Blender definitely doesn't use Python 2.6.2, you probably mean Python 3.6.2 For building on Windows I can't help you. But see my other answer to #802  about the Python version Blender is using.

**Comment by kacsavocsok** [comment]
I have same probleme :/

**Comment by jasperges** [comment]
@kacsavocsok Did you see my answer to #802 ? Are you sure you are running the official Blender 2.79 release? Builds from the buildbot are not supported.

**Comment by kacsavocsok** [comment]
https://www.blender.org/download/ (64 bit installer), as you said.
I have a 64 bit windows. I download the animation_nodes_v2_0_windows.zip and Instal Add-on from File...
I remove the old animation nodes versions. I try to reinstal, repair the blender.
 But does not work. If I try to enable:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Kacsavocsok\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes\__init__.py", line 57, in <module>
    raise Exception(message)
Exception: 

There are multiple versions of the Animation Nodes addon installed
Please uninstall/remove all older versions of the addon

**Comment by JacquesLucke** [comment]
go into this folder, there you'll see multiple AN versions: `C:\Users\Kacsavocsok\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\`

**Comment by Fondoloh** [comment]
I have the same problem as kacsavocsok above. Inside the "...\Blender Foundation\Blender\2.79\scripts\addons\" I don't see even one AN version file. Could you please help with how to locate and pinpoint theses AN version??

**Comment by kacsavocsok** [comment]
The folder is empty (C:\Users\Kacsavocsok\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons)
