### ISSUE TITLE
Help with Node Code

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#806]
I cannot see what I have done wrong here:

`
import bpy
from ... base_types import AnimationNode
from bpy.props import *
from ... events import propertyChanged

class MidiIndicesNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_MidiIndicesNode"
    bl_label = "MIDI Calculate Control to Key Indices"

    message = StringProperty("")
    controls = CollectionProperty(type="Object Group", description="Group_controls")
    keys = CollectionProperty(type="Object Group", description="Group_keys")

    def draw(self, layout):
        col = layout.column()
        col.scale_y = 1.5
        self.invokeFunction(col, "createIndices", icon = "NEW",
            text = "Create Index File")

        layout.prop(self, "controls")
        layout.prop(self, "keys")

        if (self.message != ""):
            layout.label(self.message, icon = "INFO")

    def createIndices(self):
        self.message = "Working"
        # Requires AN 2 & Blender 2.79.
        # Written by Clockmender.

        # Setup some variables.
        indk = []
        max = len(cont_objs)
        tst = 0
        cont_obs = self.controls
        keys_objs = self.keys
`

But my function "createIndices" doesn't work, it says that "cont_objs" is not defined....
I have left off the rest of this function as it all works as a script. The two inputs (layout.prop(self, "controls") & the other one do not display. I think it will be something silly, but I cannot see what.

I have scoured the 'net for clues - maybe my "CollectionProperty" definition is wrong?

The reason I want this node and not an invoked script is that it is only necessary to run this once, rather than every frame. This function tells AN where each "key" mesh lies in the "controls" object list, created by my MIDI node.

**Comment by JacquesLucke** [comment]
yes you used the collectionproperty incorrectly. Checkout the official documentation of it: https://docs.blender.org/api/current/bpy.props.html#collection-example

Well of course `cont_objs` is not defined because you never say anywhere what it is.. the `cont_objs` just does not exist in this variable.

btw: Why do you need empty objects in the first place? Wouldn't it be much easier to just store all the values in a python list or a collection in the node or somewhere else? Creating empty objects feels a bit unnecessary. not sure.

**Comment by Clockmender** [comment]
Yes, I read that page before, but I didn't understand it! So I don't know what is wrong.

I also tried this:

    def create(self):
        self.newInput("Object Group", "Control Objs", "cont_objs")
        self.newInput("Object Group", "Keys Objs", "keys_objs")
        self.newOutput("Integer List", "Index List", "indices")

But it still says cont_objs is not defined, yet I thought from your code:

    def create(self):
        self.newInput("Object", "Source", "source")
        self.newInput("Object", "Target", "target")
        self.newInput("Vector", "Offset", "offset")
        self.newOutput("Vector", "Target Location", "targetLocation")

    def execute(self, source, target, offset):
        if source is None or target is None:
            return Vector((0, 0, 0))

        target.location = source.location + offset
        return target.location

that the _def (create(self):_ lines created the variable "source" for example, so why doesn't my code above use cont_objs as the object list I wanted as an input?

Node is this:

![screen shot 2017-10-17 at 14 12 27](https://user-images.githubusercontent.com/29657804/31666776-506fcc8c-b345-11e7-82c0-1c3a6c96b1c4.png)

I am trying desperately to understand this, but things keep confusing me......

**Comment by JacquesLucke** [comment]
Ah now I understand your problem. The values from the input sockets are (in your case) only available in the `execute` function; not in any function you call from the user interface.

You could create two `StringProperty` that just store the names of the groups (or a `PointerProperty` with `bpy.types.ObjectGroup` as type, but I never tried that). Properties of a node are available in any method of the node.

**Comment by Clockmender** [comment]
OK so far so good:

![screen shot 2017-10-17 at 15 21 52](https://user-images.githubusercontent.com/29657804/31670225-0a75b1ce-b34f-11e7-8078-2ad1eb8e8cbb.png)

Now I shall read more to find out how to reference the object lists from these names....

**Comment by Clockmender** [comment]
So, I am getting nowhere!

I have a Script Sub-programme that does this easily - only issue is that AN runs the script every frame, which is unnecessary because the values don't change (unless you add new keys during the animation - dumb idea!). Therefore all I want to do is to have a node that runs the script once only. This seems way beyond my abilities. Using text entries for the names results in the node running correctly, but I cannot send the resultant Integer List to the output socket without having an execute function, which defeats the object of the node in the first place. I will give up on this, its not worth the effort and frustration. Also I need to select the Group Object list in a sensible fashion, not look up their names and type them in.

My current setup:

![screen shot 2017-10-17 at 17 20 44](https://user-images.githubusercontent.com/29657804/31676474-a33e9366-b35f-11e7-8f7c-ea2ddfb34c3e.png)

**Comment by JacquesLucke** [comment]
You could put your node into a separate node tree for which you disable Auto Execution completely. Then you can run this node tree manually.

Side note: yes, you would need two separate functions in your node. One that can be invoked from the UI that reads the midi file etc, and a separate `execute` function that is executed when the node tree is evaluated. The `execute` function can access data that has been generated in the other function that only has to run once (eg using a global variable).

**Comment by Clockmender** [comment]
I have never tried to communicate between two node trees, something new to learn! I could then easily make the node I was trying above, since all would be in the "execute" function. I need to do some reading....

**Comment by Clockmender** [comment]
Oh this is ridiculous!!!!!

```
import bpy
from ... base_types import AnimationNode

class MidiIndicesNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_MidiIndicesNode"
    bl_label = "MIDI Indices Node; Version 1.0"
    bl_width_default = 300

    def create(self):
        self.newInput("Object Group", "Controls", "cont_list")
        self.newInput("Object Group", "Keys", "key_list")
        self.newOutput("Integer List", "Indices", "indices")

    def execute(self, cont_list, key_list, indices):
        if cont_list is None or key_list is None:
            return

        max = len(cont_list)
```

gives this:

![screen shot 2017-10-17 at 19 33 12](https://user-images.githubusercontent.com/29657804/31682668-b337362a-b372-11e7-8c5b-880016612639.png)

Why is this so hard to achieve?

**Comment by JacquesLucke** [comment]
Did you actually read the error message it prints in the terminal?

You define that your node has 2 input sockets but your `execute` function has three inputs (ignoring `self`).

**Comment by Clockmender** [comment]
The third is the output socket...

**Comment by JacquesLucke** [comment]
I've seen that, is this still the case when you remove and recreate the node?

**Comment by Clockmender** [comment]
Yes, I restarted Blender, deleted the Node, added it back, still does the same.

**Comment by Clockmender** [comment]
No messages in the Info or Python windows...

**Comment by JacquesLucke** [comment]
Why is it a Object List socket in the first place? Did you save your code? Do you, maybe, have a second version of this code somewhere and Blender uses this?

**Comment by Clockmender** [comment]
The Object Lists are to select the controls and keys by group name. The output socket is the Index list that I need to feed the animation nodes to move the keys based upon the controls. I will rename the node and try again.

**Comment by Clockmender** [comment]
renaming the node makes no difference

**Comment by JacquesLucke** [comment]
so what is the current state. Were you able to remove error that triggers the red outline? (by removing the `indices` input of the `execute` function)

**Comment by Clockmender** [comment]
Yes, that worked... but why and how do I return the index list? Sorry, I am very tired and very confused!

**Comment by JacquesLucke** [comment]
You just return the list in the `execute` function.
eg with `return [1, 2, 3]`

Note: since v2.0 the example above does not work anymore because an Integer List in AN is not a normal python list but a specialized data type that I developed for better performance.
To use this type do `from ... data_structures import LongList` at the beginning of the file (`long` is integer data type, read [here](https://en.wikipedia.org/wiki/C_data_types) for more details).
Then do `return LongList.fromValues([1, 2, 3])` in the `execute` function.

**Comment by Clockmender** [comment]
This works, but the loop through the control list does not although t works as a script, I will debug this tomorrow - brain is fried!

```
import bpy
from ... base_types import AnimationNode
from ... data_structures import LongList

class Midi_Indices_Node(bpy.types.Node, AnimationNode):
    bl_idname = "an_Midi_Indices_Node"
    bl_label = "MIDI Indices Node; Version 1.0"
    bl_width_default = 300

    def create(self):
        self.newInput("Object Group", "Controls", "cont_list")
        self.newInput("Object Group", "Keys", "key_list")
        self.newOutput("Integer List", "Indices", "indices")

    def execute(self, cont_list, key_list):
        if cont_list is None or key_list is None:
            return
        indk = [1,2,3,4,5,6,7,8,9]

        return LongList.fromValues(indk)
```

**Comment by JacquesLucke** [comment]
alright, good night then :)

**Comment by Clockmender** [comment]
Goodnight :-) I seems so weird, I can do this complex midi node, but this simple one defeats me...

**Comment by Clockmender** [comment]
Had a brainwave, after some of Jack Daniel's finest:

![screen shot 2017-10-17 at 21 11 28](https://user-images.githubusercontent.com/29657804/31686996-dc43c102-b37f-11e7-8cb6-01826b6699f2.png)

Now I can sleep!

**Comment by Clockmender** [comment]
OK so things are better today!

I have made this node work properly and set it in a new Node Tree with manual execution:

![screen shot 2017-10-18 at 11 12 37](https://user-images.githubusercontent.com/29657804/31713513-60d5782c-b3f6-11e7-9b44-cb2b69a9dfea.png)

The main animation Node Tree looks like this:

![screen shot 2017-10-18 at 11 13 00](https://user-images.githubusercontent.com/29657804/31713532-706ed666-b3f6-11e7-9b95-fb5aadbffe08.png)

I need multiple instances of this Node and Group bits when I have multiple sets of controls and keys in the project, this I will now test!

The Node code is on my GitHub page.

Thanks for all the help and I apologies for getting a little frustrated with my progress, or lack thereof, yesterday!

Cheers, Clock.

**Comment by JacquesLucke** [comment]
Good that you made some more progress.
Unfortunately there is still a small problem here. It won't help that you disabled Auto Execution in the tree when you put the node into a group. A subprogram will never be called automatically anyway, only when it is invoked by another script. So in you case, the Midi Indices Node will still always be called when the frame changes.

An idea to solve this would be to have two nodes. One that is just for baking and one to access the baked data (similar to what I did for the sound system).

**Comment by Clockmender** [comment]
Oh MERDE! that's was my original thought - to have a node that just made the index file as a one off operation, however, I could not make such a node work, I could not get the variables from the input boxes other than with an Execute call! Can you give me any pointers here? I have studied the Bake node code, but cannot find a method that works.

**Comment by Clockmender** [comment]
Can I pass a variable defined in the Execute function to a separate Invoke function?

**Comment by JacquesLucke** [comment]
No, the functions invoked from the ui are separate from the `execute`. There are good reasons for that, but I don't want to go into details now.

I think you don't see this with right abstractions. Let's say you have a `Bake Midi` node. Currently you want to bake the animation into objects however I think that is not a good idea. No object should be touched when baking. This way you don't need any input socket in the Bake Midi node.

Instead of baking as keyframes in objects you should bake it differently. One possibility would be to store the baked data in the node itself (e.g. in a `CollectionProperty`, one value for each note).

The `Evaluate Midi` node can find this stored data somehow and output it for the current frame.

I'd do it something like this, obviously it is a bit more work and might be a bit over your head right now, not sure.

**Comment by Clockmender** [comment]
I am not **baking** the MIDI to the object - just making editable F-Curves on Empty Objects - that way I can manipulate them to suit my animations. this simple approach suits me for now - as you say the other option is way over my head for now, so I will go with this for a while until I can understand things better. I only started programming with python 1 month ago and it is a long time since I programmed for a living :-) I am retired and have been since I sold my IT business 16 years ago.

I have solved the problem of running the index calc only once with a new node, soon to be on my Github - it may not be perfect yet, but it seems to work in many circumstances. I know my system is simple, but it will take me time to get to a higher level of expertise with this. The old coding principles I worked to are just that - old! I got over the issue of passing variables from the execute function to the Invoke function using an old trick..... Please don't block this!!!!!

With these empties, I can for example get a biped robot to play chords and melody on a guitar and play a set of drums from these controls, I am not sure I could do that with baked note data inside a node, yet.

There are no input sockets on my node that generates the control empties from the MIDI file - that I learnt from your Bake Sound node. The only one that needs input is the node that relates the controls to the "keys" I don't want to have to order the keys exactly as the controls, so I do it with the index file, also I want to have more keys than notes played - a piano keyboard for example.

One never plays all the keys in one tune (impossible unless you keep changing key and that sounds awful) but I want the piano keys to play some tunes one after the other - this I can do with my method. I build one set of controls from frame 1 for say 3000 frames, then another set for a different MIDI file from frame 3050 for example, this is where the Offset setting on my node is used. This requires that the keys be accessible to both sets of controls and different notes used and they will be in different orders in the MIDI files. I might also want more than one instrument to play the same MIDI data. I also want to be able to alter the F-curves, like randomly scaling the Y values for example.

I have worked with MIDI and DAW's (Reason, to name but one) for many years and have developed my thinking based upon this rather than coming at it from a programmer's point of view. I understand how MIDI works and know of the many varied things that can crop up in a MIDI file.

Anyways, thank you so much for all your help with this, I know my system is not as good as it could be, but development of this is going to take a long time and a lot more understanding of your excellent Animation Nodes and Python from me.

Cheers, Clock.

Here's a quick screenshot:

![screen shot 2017-10-18 at 19 12 50](https://user-images.githubusercontent.com/29657804/31735014-6dffc394-b438-11e7-9956-be06bc9d76ae.png)

**Comment by Clockmender** [comment]
I have just realised my Index Node code is utter "crap" - re-write in progress following some more research....

**Comment by Clockmender** [comment]
Actually this was all a waste of time - I need multiple versions of this node for multiple instruments ( all nodes displayed the same Index although fed from different Object lists ??????, so I have gone back to using a simple script and invoke Sub-programme. I can have as many as I like and no problems. The animation runs slower at 5ms rather than 0.6ms if I stop it regenerating the index file.

Well that's no big deal as I render the frames anyway - what is 5ms compared to a frame render!
