### ISSUE TITLE
Storing F-Curves "in" a Node

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#807]
Is it possible to store collection of F-curves, by name on a Node?

Why? well taking on board what you said about my MIDI sync development, I want to look at storing the F-Curves in the Node the makes them, rather than on a series of Empties.

Why F-Curves? well if I store note position per frame I have two disadvantages; 1) Huge amount of data - my test song has 57 notes played over 6760 frames, another has 92 notes over 6 channels. One note may be played only twice, but I have to store it's position for every frame don't I? 2) the animation will be very "Blocky" in that I cannot smooth the movement of the piano key so it goes down over 2 frames for example, the MIDI file does not store this "easing" of the key movement as it is either on or off at a given velocity.

So this would be an improvement and more in line with the Bake Sound. I would also need a node to get the F-Curves from the MIDI node and I still need to index them to the keys - not a big issue, I could get the F-Cuvers in a Node, get the Keys in the same node and make the index inside that node, although I still need to solve the issue of multiple instances of this node having different index lists - I have some thoughts on this to test.

**Comment by JacquesLucke** [comment]
the two disadvantages you talk about can be resolved but don't have to be. I agree that it is be easier to just use fcurves for now.

I suggest you create a `bpy.types.PropertyGroup` subclass. It should have (at least) two properties: 
1. the `note` as `StringProperty` 
2. the `value` as `FloatProperty`

In the node create a new `CollectionProperty` to be able zo have multiple "instances" of your property group.

You can then keyframe the `value` property for each note. (note that the fcurve might not be visible in the graph editor or dope sheet; this is a limitation of Blender)

**Comment by Clockmender** [comment]
Great, I'll work on a specification today and let you see where I get later on.

Seeing the F-curves is not a requirement now - I can always alter the MIDI file in Reason if I want to slow things down. I have a requirement to make an animation of a clockwork toy playing a tune - this slows down at the end as the motor winds down, all can be done in Reason so I don't need to edit the F-curves in Blender.

My initial thoughts are to store something like [10-0.7, 30-0.7, 32-0, 45-0, 47-0.9, 70-0.9, 72-0 ......] and name each list, for example t2_c4 (track 2 note C4), then put these in a collection. Where the first number is the frame (could be a float also) and the second value is the note-on velocity (range 0 to 1). The Evaluation node would then read the current frame and compare it to the list to set the keys positions, changing the position of the key when it sees a change in the list.

The MIDI "Bake" node would build this collection from the MIDI CSV, json file.

I need to do a lot of reading to see how I create and use a new Property, so this will take some time to implement.

Would this work efficiently do you think? Hope I understood what you said correctly!!!

**Comment by JacquesLucke** [comment]
I'll prepare you a small example of what I meant later today. I'm in university atm.

**Comment by Clockmender** [comment]
Really appreciate that, this is how I am animating from the control empties:

![screen shot 2017-10-20 at 11 41 26](https://user-images.githubusercontent.com/29657804/31817415-c25a0b08-b58b-11e7-8362-8e0a4a907f02.png)

So using stored F-Curves is ideal!

**Comment by Clockmender** [comment]
I think I have a method:

My "Bake" Node needs to read the MIDI file and create, for each channel, a list of F-curves.
The F-Curve List is named by Channel - e.g. "Channel 1", or "Piano Ch1"
The Curves are named by note - e.g. C4, B5, etc.

These are then combined into a Master List for the MIDI File named by MIDI File name - e.g. "Entertainer". This caters for Multi-channel MIDI files.

This master list is stored in Blender (somewhere) and is an Output Socket from the Node, named the same as the MIDI file. It is also shown on the "Bake" node, like you do with Bake Sound.

It effectively does this, but in code:

![screen shot 2017-10-20 at 15 27 32](https://user-images.githubusercontent.com/29657804/31825804-3c2a3736-b5ab-11e7-95fc-b2f102fb1f9d.png)

The Animation is then done like this:

![screen shot 2017-10-20 at 15 28 31](https://user-images.githubusercontent.com/29657804/31825844-633584a2-b5ab-11e7-92e3-6b509528fe2f.png)

More simple than at present, but only just, and I have no control empties in the file.

A good refinement is for the "Bake" Node to also receive the Keys Objects as an input socket, so it can calculate the Indices to link "Notes" to "Keys" (note C4 is Keys object list[8] for example), as a one off operation and then store this with a output socket. This makes things more efficient.

So the user selects the MIDI File, selects the Keys Objects Group and presses Go. This produces the Master List of F-Curves, and the Index file. These are then fed into the Animation Node Tree to move the keys. The user can also select the Sound file and the Node adds this to the project at the same offset as the MIDI notes.

It may be better for the Master Lists (could we have several) and their Index Files and Keys Object Groups just to be stored in the "Bake" node and have an "Evaluation Node" that produces the outputs for the animation. then it is all in line with your Bake Sounds principles.

A lot of new work here, but already have a lot of it done in respect of getting the figures for the F-Curves and also the Index calculation. I want to keep the index calculation as a one off operation. I will continue to research how to do this, I appreciate any help you can give as I know you are very busy with other more pressing matters. I need to learn how to make the F-Curves and how to store them in a list and then store many of these in a master list.

Thanks again and let me know if you think this is a better solution.

**Comment by JacquesLucke** [comment]
https://gist.github.com/JacquesLucke/5ba7ca942fc7f6c7664e76f0fdec3847

**Comment by Clockmender** [comment]
Sorry to be a pain in the neck, but I appear to be making the same mistakes over and over, through lack of understanding. This code works nicely in a Script Sub-programme:

```
# Quick Fudge to get all the controls:
Objects = bpy.context.selected_objects
ob_name = ""
f_curves = []
nt_names = []
ind_obs = []

for ob in Objects:
    ob_name = ob.name
    nt_names.append(ob_name)
    tr_name = ob_name.split('_')[0]
    f_curves.append(list(ob.animation_data.action.fcurves)[0])

# Build index
ind_rec = ""
indx = 0
index = []
for key in keys:
    ke_name = key.name
    ke_name = ke_name.split('_')[0]
    ke_name = chanl + "_" + ke_name
    ind_obs = [obj for obj in nt_names if obj == ke_name]
    if len(ind_obs) == 1:
        ind_rec = ind_obs[0]
        index.append(indx)
    indx = indx + 1

index = LongList.fromValues(index)
```
Variables chanl and keys are inputs on the node:

![screen shot 2017-10-21 at 18 31 38](https://user-images.githubusercontent.com/29657804/31854292-1f96a44a-b68e-11e7-803b-c34a0730d80d.png)

But this node does not work, no errors but a res box around the Node Window:

```
import bpy
from ... base_types import AnimationNode
from bpy.props import *
from ... events import propertyChanged
from ... data_structures import LongList

class MidiCurvesNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_MidiCurvesNode"
    bl_label = "MIDI Curves Node; Vers 1.0"
    bl_width_default = 300
    fcurves = []
    index = []
    nt_names = []
    chanl = StringProperty()

    def create(self):
        self.newInput("Object Group", "Keys Obj Grp", "keys")
        self.newOutput("FCurve List", "F-Curves", "fcurves")
        self.newOutput("Integer List", "Note Index", "index")

    def draw(self, layout):
        col = layout.column()
        col.scale_y = 1.5
        self.invokeFunction(col, "createCurves", icon = "NEW",
            text = "Create Curve List")
        self.invokeFunction(col, "createIndex", icon = "NEW",
            text = "Create Index")

    def createCurves(self):
        Objects = bpy.context.selected_objects
        Objects = bpy.context.selected_objects
        ob_name = ""

        for ob in Objects:
            ob_name = ob.name
            self.nt_names.append(ob_name)
            tr_name = ob_name.split('_')[0]
            self.fcurves.append(list(ob.animation_data.action.fcurves)[0])

        return self.fcurves

    def createIndex(self):
        if not self.nt_names:
            return
        
        ind_obs = []
        ind_rec = ""
        indx = 0
        keysL = list(getattr(self.keys, "objects", []))
        for key in keysL:
            ke_name = key.name
            ke_name = ke_name.split('_')[0]
            ke_name = chanl + "_" + ke_name
            ind_obs = [obj for obj in self.nt_names if obj == ke_name]
            if len(ind_obs) == 1:
                ind_rec = ind_obs[0]
                self.index.append(indx)
                indx = indx + 1

        return LongList.fromValues(self.index)
```

I know I am doing something wrong, but cannot work it out, even from studying other nodes.

I am trying a little experiment - trying to store all the control F-Curves in a list on a Node, ideally I would like to store them in bpy.whatever so another node can get this list, then delete the objects in time (getting here is a way off too). This is as I also try to work a new system using the code you sent me, this is going to take much longer...

**Comment by Clockmender** [comment]
Ok so I am still trying:

here is the node:

```
import bpy
from ... base_types import AnimationNode
from bpy.props import *
from ... events import propertyChanged
from ... data_structures import LongList

class MidiCurvesNode(bpy.types.Node, AnimationNode):
    bl_idname = "an_MidiCurvesNode"
    bl_label = "MIDI Curves Node; Version 1.0"
    bl_width_default = 300
    Controls = StringProperty()
    Keys = StringProperty()
    index = []
    f_curves = []

    def create(self):
        self.newOutput("Integer List", "Index List", "index")
        self.newOutput("FCurve List", "Curves List", "f_curves")

    def draw(self, layout):
        col = layout.column()
        col.scale_y = 1.5
        self.invokeFunction(col, "createCurves", icon = "NEW",
            text = "Create Curve List")

        layout.prop(self, "Controls")
        layout.prop(self, "Keys")

    def execute(self, index):
        return self.index, self.f_curves

    def createCurves(self):
        f_curves = []
        index = []
        objects = bpy.data.groups[self.Controls].objects
        keysL = bpy.data.groups[self.Keys].objects

        chanl = objects[0].name.split('_')[0] + "_"
        ke_names = [chanl + obj.name.split("_")[0] for obj in keysL]

        for ob in objects:
            ob_name = ob.name
            f_curves.append(list(ob.animation_data.action.fcurves)[0])
            if ob_name in ke_names:
                indx = ke_names.index(ob_name)
                index.append(indx)

        index = LongList.fromValues(index)
```

Here is the Error:

```
# Node: 'NodeTree' - 'MIDI Curves Node; Version 1.0'
try:
    _index_znv0, _f_curves_znv1 = _znv51cquskffvp0.execute()
    if not ('_index_znv0' in globals() or '_index_znv0' in locals()): raise Exception("Socket output has not been calculated: 'Index List'")
    if not ('_f_curves_znv1' in globals() or '_f_curves_znv1' in locals()): raise Exception("Socket output has not been calculated: 'Curves List'")
    pass
```

Can you suggest why this might be please? I have tried repeatedly to sort this, but am getting nowhere.

**Comment by Clockmender** [comment]
I will just run this as a Invoke Sub-Programme Script, this works very well, I shall give up trying to make a node for this, I can not find any documentation anywhere to help me, very disappointing.

```
Objects = list(getattr(Controls, "objects", []))
keysL = list(getattr(Keys, "objects", []))
keys_out = Keys
f_curves = []
index = []

chanl = Objects[0].name.split('_')[0] + "_"
ke_names = [chanl + obj.name.split("_")[0] for obj in keysL]

for ob in Objects:
    ob_name = ob.name
    if ob_name in ke_names:
        indx = ke_names.index(ob_name)
        index.append(indx)
    f_curves.append(list(ob.animation_data.action.fcurves)[0])

index = LongList.fromValues(index)
```

My system works for me, so I shall stick with that, this is taking far too much time.
