### ISSUE TITLE
Particle velocity and rotation (and other data)

### ISSUE THREAD

**Issue by raingloom** [JacquesLucke/animation_nodes#808]
I noticed they were missing and I need at least rotation. I looked into the code and it seems there are traces of work with attributes other than location.

Are these being worked on and if not, how should I go about implementing them?

**Comment by JacquesLucke** [comment]
velocity and rotation are relatively unreliable attributes in my experience. This is why I removed them.

It should be quite easy to reimplement them just by "pattern-matching" with existing code

**Comment by OmarSquircleArt** [comment]
Related:
https://blender.stackexchange.com/questions/106848/blender-animation-nodes-particle-information/106875#106875

**Comment by OmarEmaraDev** [comment]
Implemented in 26e15e5.
