### ISSUE TITLE
Something wrong with Armature info...

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#809]
The Blend Zip example here used to work:
https://www.youtube.com/watch?v=FMDShDH38TM

Somewhat the Length output from Armature info node is misbehaving.

![screen shot 2017-10-22 at 20 50 46](https://user-images.githubusercontent.com/3952687/31860734-c57cd212-b76a-11e7-9ecd-f6e328ca7f40.png)
![screen shot 2017-10-22 at 20 50 39](https://user-images.githubusercontent.com/3952687/31860735-c5addce0-b76a-11e7-8562-bd221ee49ef8.png)

**Comment by JacquesLucke** [comment]
You're right, that looks like a real bug. Which AN version are you using atm?

**Comment by enzyme69** [comment]
Hi @JacquesLucke Version 2.1.0. Maybe not latest.
