### ISSUE TITLE
Question - can I sample a texture to receive a bool result?

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#812]
I'll put an example.

If you have a plane with a black and white texture, you want to distribute objects over the plane, but you want to use that texture to define what zones do you want to use and what zones you want to avoid.

Is there a way of doing that?

Thanks!

**Comment by JacquesLucke** [comment]
AN currently does not support using textures for anything. If you know some python you can probably do it with a script node somehow, otherwise no, there is no way of doing that, sry.

**Comment by juangea** [comment]
Wow! That was fast.

I was trying to keep it simple to be able to explain it to others, that is why I want to avoid scripting, but I'll find other ways.

Thanks JacquesLucke!
