### ISSUE TITLE
Question: Is possible to create an empty object group to fill it later in the execution?

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#814]
Tghat's the thing, I want to instance some objects, and I want them to be included in a new group with a new name I will generate procedurally during the execution, and I want that to use this group of objects in a different execution tree later.

Is it possible to create a completely new object group in the scene with animation nodes?

Thanks!

**Comment by JacquesLucke** [comment]
Groups can only be created using a script node. However you need to be really careful that you don't accidently create many groups when Auto Execution is enabled.
