### ISSUE TITLE
How to make each cube rotate with different degree and speed

### ISSUE THREAD

**Issue by ethan0124** [JacquesLucke/animation_nodes#816]
this is my node
https://drive.google.com/open?id=0B-2H1tGS2ukiS1FleTNnVzBrYzA

and i want each cube rotate with different degree and speed.
https://drive.google.com/open?id=0B-2H1tGS2ukidFpVclAwazZTYk0

this is my file
https://drive.google.com/open?id=0B-2H1tGS2ukianRmWWR1WWhYSFk

**Comment by stansu** [comment]
![image](https://user-images.githubusercontent.com/9460236/37197083-3689b96a-23b4-11e8-82fa-884027ffdf06.png)

[partially deprecated_stan.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1796049/partially.deprecated_stan.blend.zip)
