### ISSUE TITLE
Cannot Activate

### ISSUE THREAD

**Issue by mgbrobertson** [JacquesLucke/animation_nodes#817]
I'm not sure if this will be of help, but I was not able to activate the add-on. I presume I must install an earlier version of Blender. 

![animation-nodes-error-msg](https://user-images.githubusercontent.com/33429818/32456175-e286532e-c2e1-11e7-898a-7e4cee1320a1.png)

Thank  you for supporting open source.

Bruce

**Comment by JacquesLucke** [comment]
do you use a blender version from the buildbot? The official AN releases don't work with them.
Please use the official Blender 2.79 release instead :)

**Comment by mgbrobertson** [comment]
Hi Jacques,

Thanks for your response. I'm not sure what "buildbot" or "official AN release" means, beg pardon. I'm using a version of Blender that I downloaded from https://www.blender.org/ 

Bruce

**Comment by mgbrobertson** [comment]
I understand now. I did indeed download the official AN build from https://github.com/JacquesLucke/animation_nodes/releases and I'm using an official Blender 2.79.1 release. I hope this is of some help. 
Thank you.

**Comment by JacquesLucke** [comment]
I see, can you send me the link where exactly you downloaded Blender?
Please try again with the Blender version you can download here: https://www.blender.org/download/

**Comment by JacquesLucke** [comment]
Downloads from this page **won't** work with the official AN release: https://builder.blender.org/download/

**Comment by Draise14** [comment]
When 2.79a comes out, will AN be compatible? Or will it need to be recompiled with the new Python?

**Comment by JacquesLucke** [comment]
I'm not absolutely sure but I think 2.79a will use the same Python version as 2.79 (and not the same that is used in daily builds atm)
Maybe I'll still have to recompile it due to minor changes in Blender.
I'll definitly make sure that AN works with 2.79a when it comes out.
