### ISSUE TITLE
Cannot install Add-On Animation Nodes

### ISSUE THREAD

**Issue by Ottoblau** [JacquesLucke/animation_nodes#818]
I wanted to install the Animation Nodes Add-On, went to the official download link (https://github.com/JacquesLucke/animation_nodes), downloaded the zip file, went to Blender (2.79) User Preferences, Install from File and everything seemed okay, but I could not find the Add-On afterwards.

So I went to a subpage on Github (https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0), downloaded the windows-version zip file, installed it and it shows up in the Add-Ons list. Unfortunately, when I want to activate it, I get an error message "There are multiple versions installed.......remove older versions".

These are my machine specs: Intel i5-4200 CPU @ 1.6GHz 2.3GHz, 8Gb RAM, Windows 8.1, x64.
How can I uninstall a version that does not show up?

Soo many thanks upfront!

Ottoblau

**Comment by JacquesLucke** [comment]
`C:\Users\%username%\AppData\Roaming\Blender Foundation\Blender\2.xx\scripts\addons`

Find that folder, remove all AN related subfolders, install AN again.

The `AppData` folder is maybe hidden by default.

**Comment by Ottoblau** [comment]
I followed your suggested path, deleted the file and everything works great.
Thanks so much, you guys are amazing, special thanks Jacques!
Ottoblau
