### ISSUE TITLE
Opening my project in blender which uses Animation Nodes makes the 800kb project take up endless memory

### ISSUE THREAD

**Issue by enginpost** [JacquesLucke/animation_nodes#819]
My project is relatively simple including only 8 instance of a simple curve turned into a tube and animated along a winding path. When I save the project, it saves at exactly 866 KB. 

When I open blender 2.79, blender loads a bit over 10 MB and then drops to below 10 MB.  
![image](https://user-images.githubusercontent.com/641069/32704330-cb7b04e0-c7c8-11e7-9d2b-b1086b08ca55.png)

As soon as I attempt to load this project the memory start climbing like a millisecond timer and doesn't stop.  Honestly, I haven't waited to see how high that number climbs. As I am typing this, it has grown from hundreds of MBs to well over 12.5 GB when the app is full screen on a 4K monitor. Here is the funny thing.  if I take blender out of full-screen, the memory climb stops.

![image](https://user-images.githubusercontent.com/641069/32704368-6f15f402-c7c9-11e7-99c4-4aea59cf5c2e.png)
 
When I hit "Render" it crashes with a very generic "access" error. The quicker I load it and tell it to immediately render, then I can get it to render out a few PNGs before the app crashes. I don't get a text file error report unfortunately.  if I open a command window and start blender from there it spits out a fairly generic error right as it crashes:

Error: EXCEPTION_ACCESS_VIOLATION
![image](https://user-images.githubusercontent.com/641069/32704383-b6c43304-c7c9-11e7-965a-af4f8f7713f2.png)

You can download the project yourself and see if it happens for you:

https://www.dropbox.com/s/apyffjknzx2wfq0/ep-video-intro.blend?dl=0 

Environmental variables:
NVIDIA GTX 1080 w 8GB GPU ram w/ up-to-date drivers
16GB ram
Intel i7-6700K CPU @ 4GHz
4k display port monitor
Windows 10 pro (Version 10.0.16299 Build 16299)

Stuff I've tried so far:
1. Confirmed I should be able to write PNGs where I am writing them
2. Completely uninstalled Blender and rebooted
3. Reinstalled blender 2.79 after reboot and reinstalled the animation nodes v 2 for Windows

Still climbs the memory when I load the project and still crashes when I render.

I ran the project in OSX Blender 2.79 and I get the same error with a segment fault 11 message in the terminal.  
<img width="582" alt="screen shot 2017-11-12 at 8 27 22 pm" src="https://user-images.githubusercontent.com/641069/32707237-07fb37ae-c7e8-11e7-8f6b-386998ff9f7b.png">

OSX successfully generated a crash.txt file.
[ep-video-intro.crash.txt](https://github.com/JacquesLucke/animation_nodes/files/1465411/ep-video-intro.crash.txt)

**Comment by JacquesLucke** [comment]
Does the same thing happen when you disable AN in this project? At first it looks like a Blender bug but I'm not absolutely sure.

I'll try it myself a bit later today when I have time..

**Comment by jasperges** [comment]
I can confirm the issue of the climbing memory consumption (both on Linux and macOS). Disabling 'Auto Execution' (or disabling 'Always') for the Animation Nodes Tree stops this.

When trying to replicate the scene, I discovered that the problem lies in the Subsurf Modifier on 'Tube'. I you remove or disable it, the problem is gone.

**Comment by Clockmender** [comment]
I got here too late! I also confirm what @jasperges says above. It is my understanding that you cannot have _unapplied_ Modifers on objects that you want to use with the "Object Instancer" node. I guess this proves the point! I tried to do this with a bevel node as an experiment and got a similar result on my Mac.

**Comment by enginpost** [comment]
> Disabling 'Auto Execution' (or disabling 'Always') for the Animation Nodes Tree stops this.

@jasperges  How do I do this?

**Comment by enginpost** [comment]
For me, Blender still crashes with that enabled. I reinstalled blender to be certain and made the nodetree recommended change above.  I removed the modifiers. when I scrub the timeline everything looks great.  As soon as I hit "Animation" it crashes. Thoughts?

**Comment by enginpost** [comment]
I will try to recreate the animation today with that advice of subdividing in advance and then using AN after that.

**Comment by stansu** [comment]
i removed Subsurf and loop.
now seems ok.
![image](https://user-images.githubusercontent.com/9460236/37196358-73c1cd48-23b1-11e8-8d8f-12c6915acd71.png)
