### ISSUE TITLE
[POSSIBLE BUG] Animation Nodes not able to set up the execution units.

### ISSUE THREAD

**Issue by Nicholaslwd** [JacquesLucke/animation_nodes#821]
Hi Jacques, 
I was having a play around with Animation Nodes in Blender version 2,.79 RC2 and I was unable to set up an offset matrix using the loop input. The plug-in reports an error.

I might be doing something wrong here, appreciate your help in this. Please see the screenshot below to replicate the problem. Many thanks!

![image](https://user-images.githubusercontent.com/33675097/32813380-027f65bc-c9fe-11e7-9664-694da52905d4.png)

![image](https://user-images.githubusercontent.com/33675097/32813471-7cc2f172-c9fe-11e7-85a1-e8dd9872389a.png)

**Comment by stansu** [comment]
![image](https://user-images.githubusercontent.com/9460236/37194325-9ea52df6-23a8-11e8-8a2c-c37fb5f55749.png)
