### ISSUE TITLE
How to get keyframes data of an object ?

### ISSUE THREAD

**Issue by Singh-KS** [JacquesLucke/animation_nodes#822]
I'm trying to get keyframes data by using a simple script. It gives the wrong result like one keyframe data for all the frames. But I want all keyframes data as a list. Here I attached my blend file.

![keyframe_data](https://user-images.githubusercontent.com/30294746/32821875-c79284c2-c9fb-11e7-8b5b-116a17502e0f.png)

[keyframedata.zip](https://github.com/JacquesLucke/animation_nodes/files/1473567/keyframedata.zip)

**Comment by stansu** [comment]
![image](https://user-images.githubusercontent.com/9460236/37193931-ce584daa-23a6-11e8-86e0-9d64058f52a7.png)

[keyframes_data_stan.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1795840/keyframes_data_stan.blend.zip)
