### ISSUE TITLE
Loop Generator Output Bug or not?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#823]
I was testing the 2.0a build that shared [here](https://blenderartists.org/forum/showthread.php?350296-Addon-Animation-Nodes&p=3242298&viewfull=1#post3242298), with Blender daily build 2.79.1, One problem occured while I was tryinig to create any type of output for a loop:

![loop](https://user-images.githubusercontent.com/494788/32841176-a575fe9c-ca54-11e7-9d8b-4b22e9018678.jpg)

**Comment by JacquesLucke** [comment]
can't reproduce this right now. It seems to work in v2.0a
