### ISSUE TITLE
Keyframing Nodes does not update AN

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#824]
I tried a simple setup of keyframing node values to control visibility of multiple objects (hide, hide_render) using Animation Nodes and seems like I failed.

It seems to keyframe the attribute, but it does not update the AN. Wondering if this is a bug? Or something I am missing?

**Comment by JacquesLucke** [comment]
When you enabled "Frame Changed" in the auto execution settings it should work. AN does not recognize keyframed node sockets on its own.
