### ISSUE TITLE
Numpy error on install for 2.79

### ISSUE THREAD

**Issue by STC19** [JacquesLucke/animation_nodes#825]
![capture](https://user-images.githubusercontent.com/15341195/32870197-b7115bf6-ca72-11e7-966f-fface8fe213d.PNG)

Does anyone know how to fix the above error in blender 2.79 or is 2.79 just not compatible with animation nodes 2.0?

Windows 10 64 Bit 
Version 1709

Many thanks.

**Comment by Clockmender** [comment]
AN 2.0 works fine for me on my Mac, but, I only use the official release, I believe that is the only one supported rather than the daily builds.

**Comment by JacquesLucke** [comment]
AN should work in the official Blender releases. Other builds (buildbot, graphicall, ...) or not necessarily supported.

**Comment by STC19** [comment]
Hi guys, 

Thanks for the speedy replies. 

Problem solved. 

I completely removed all traces of blender from 'roaming/blender foundation/.......
as well as from 'C://program files/........'. 

Then restarted and reinstalled and now works fine. 


Many Thanks.
