### ISSUE TITLE
[Feature request] Drag from node, drop in empty space and get a context sensitive search menu 

### ISSUE THREAD

**Issue by cyaoeu** [JacquesLucke/animation_nodes#829]
Something I really liked from the UE4 node system was the feature where you could drag from any node and get nodes that worked with that as an input. So for example in AN if you dragged from an object node output you would get a search menu with everything in the shift+a object menu that takes an object node input. If you did it with an object node input you would get one for everything that takes an object node output. For a vector, get vector stuff, and so on. This added node gets automaticaly connected to the previous node (that you dragged from).

This makes the UI a lot more "hands on" because right now you've probably got an idea of what you want to do with some node, so instead of shift+a adding nodes and then connecting them manually it would be nice if you could just drag off nodes and quickly add+connect nodes that way.

**Comment by JacquesLucke** [comment]
Unfortunately Blender currently does not support this behavior. It was proposed multiple times already.
Not sure if we will get this at some point.
