### ISSUE TITLE
[Feature Request] Option to set defalut values and  saving presets in group loop node

### ISSUE THREAD

**Issue by Singh-KS** [JacquesLucke/animation_nodes#830]
First, thank you for new version 2.1. If it is possible to set default values in group loop node and to save presets as for future use then it will be very helpful :)

**Comment by JacquesLucke** [comment]
The currently official version is v2.0. v2.1 ist still in development.

Yes, you can set default values in the advanced settings of the Group Input and Loop Input node.
(select the node and press *U*)
