### ISSUE TITLE
Can't launch AN in daily build.

### ISSUE THREAD

**Issue by crantisz** [JacquesLucke/animation_nodes#832]
Can't launch AN with daily builds. This I've tried:
1) PPA: https://launchpad.net/~thomas-schiex/+archive/ubuntu/blender

![2017-11-21 10-51-14](https://user-images.githubusercontent.com/1749968/33060626-f07e9f08-cea9-11e7-92f6-05668321a636.png)

In PPA I found this:

> For NumPy to work with Python 3.6 on Python 3.5 based distributions (pre-artful), please install numpy with pip.

So I've installed it by typing `pip install numpy` in terminal. Now it looks like:

```
design@3dDesign:~$ pip install numpy
Requirement already satisfied: numpy in ./.local/lib/python2.7/site-packages
```
But problem still exists.

2) Daily build from blender.org, not raising a numpy error, but it raises python version mismatch:

![2017-11-21 10-49-39](https://user-images.githubusercontent.com/1749968/33060596-d38f1378-cea9-11e7-895c-9396536b28e0.png)

Blender 2.79.1 uses 2.6 version of python, PPA version also..

**Comment by JacquesLucke** [comment]
unfortunately AN is only supported for official Blender releases, not daily builds.
The problem is that the daily builds use a different python version than the official 2.79 release

**Comment by reanimastudios** [comment]
That's not unfortunate. The minimum requirements moving forward for Blender are Python 3.6.x. It effectively makes AN obsolete w/o being updated to meet minimum requirements for Blender 2.79.x and obviously the upcoming Blender 2.80.x. The first delta release for 2.79 will require it. It makes sense to put Animation Nodes 2.0 in maintenance mode for versions of Blender using Python 3.5.x and move master to Python 3.6.2+. But it's your project, your call.

**Comment by JacquesLucke** [comment]
I'll see which python version Blender 2.79a will use. I was told that it will use Python 3.5 as well.

I could support both Python versions at the same time, it just means more maintenance work.

**Comment by bliblubli** [comment]
@all you can compile it yourself and/or donate on paypal/patreon. It's not easy to work on such a good project parallel to studies, I know what I speak about. So help Jacques as he helps you.
