### ISSUE TITLE
Why does 'undo operation = Ctrl+z' remove materials of splines in AN

### ISSUE THREAD

**Issue by Singh-KS** [JacquesLucke/animation_nodes#833]
Here I have attached a simple blend file in which I generated two splines by the replicate node and then assigned them some different Materials. If I do 'undo operation' for other purposes it removes the Materials of the splines. Is it reinitializing the Node tree or something else?

![before_undo_operation](https://user-images.githubusercontent.com/30294746/33068909-c12fc446-ced8-11e7-9d0f-8535f8e7a9bc.png)

![after_undo_operation](https://user-images.githubusercontent.com/30294746/33068916-c6570772-ced8-11e7-94f1-6c71b72d5681.png)

[replicate_splines.zip](https://github.com/JacquesLucke/animation_nodes/files/1491026/replicate_splines.zip)

**Comment by Clockmender** [comment]
You are generating the splines using an object instancer - so the splines get generated by the node tree. Then I think you are adding the materials by hand, i..e not by the node tree, so the materials are not part of the node tree. To solve your problem you need to assign the materials to the _instances_ of the splines in your node tree, not as a separate operation using your mouse.

Cheers, Clock.

**Comment by Singh-KS** [comment]
Clock,
In AN, there is no Material Node and so we can't assign material to the instance object in the node tree. The second thing is we can't instance Material with animation node (AN).

**Comment by Clockmender** [comment]
Instanced objects carry the Material of the **source object**. Nodes exist to change that material in both the view port and rendered output. If you want separate materials, you need to find another way to build your node tree, i.e. not using instances.

**Comment by Clockmender** [comment]
You can do a great deal with AN and Materials.

Take this example:

![screen shot 2017-11-21 at 17 42 33](https://user-images.githubusercontent.com/29657804/33087841-a3b2743a-cee3-11e7-8041-cab84099c412.png)

With this Node Tree:

![screen shot 2017-11-21 at 17 41 57](https://user-images.githubusercontent.com/29657804/33087857-b0587eb4-cee3-11e7-8b38-de6e11f2e245.png)

All it needs is a very short Python Script Node thus:

```
if ob.data.materials:
    # assign to 1st material slot
    ob.data.materials[0] = mat
else:
    # no slots
    ob.data.materials.append(mat)
```

Here's the blend file, just press Play - your homework is to work it all out :-)

[materials.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1492410/materials.blend.zip)

Cheers, Clock.

PS. It is singularly ill-advised to say something does not exist or cannot be done, when a little reading of the manual will point the way. Instanced object cannot have separate materials, as can be seen in the demo file, that does not mean that a group of objects cannot be separately coloured, or have their colours randomly changed, which is also demonstrated.

**Comment by Singh-KS** [comment]
Thank you so much.
