### ISSUE TITLE
effector not working in imminent_collapse_demo

### ISSUE THREAD

**Issue by protovu** [JacquesLucke/animation_nodes#836]
Hello, and thank you for these tutorials and for Animation Nodes!. It is amazing.
I am at working my way through the AN tutorials, and currently at: Animation Nodes #6: Imminent Collapse (Imploding sphere effect).
The following the tutorial steps, .blend file I have made works correctly  until the point where the effector is meant to work ( corresponding to 7:36) of Zach's video.

![image](https://user-images.githubusercontent.com/25392354/33404629-d98d4bac-d519-11e7-889b-3342ceaf28da.png)

Additionally, the Zach Hixson .blend file, is showing an error.
![image](https://user-images.githubusercontent.com/25392354/33404681-193de482-d51a-11e7-8fe6-885cd8bc9c61.png)

I would love to try to progress with this amazing plugin.
my version of Blender is 2.78c
As I do not see v2.78.0 available, is there a fix I can try to get through this tutorial?
Any other recommendations?

windows7
dual xeon

Thank you for your help,
Rick

**Comment by JacquesLucke** [comment]
I can't do anything here right now. Please always provide a file that does not work.

The file by Zach Hixson does not work because it was created in another version (`v1.6`).
