### ISSUE TITLE
error on trying to activate add-on

### ISSUE THREAD

**Issue by msfielder** [JacquesLucke/animation_nodes#837]
dear jacques, 
got mac os x 10.6.8 (yeah ...), 64 bit sys, official blender 2.79 release ...
after installing it trying to activate i get this: 
![bildschirmfoto 2017-12-01 um 12 33 05](https://user-images.githubusercontent.com/34160390/33481695-f0e6f884-d695-11e7-80db-966b1310236a.png)

how can i solve that problem?
any help would be great!
thx!
m

**Comment by Pred3d** [comment]
Please try again with the official Blender version and the current release.

**Comment by msfielder** [comment]
hello! thanks for the reply! i got blender 2.79 official version (re-checked) and downloaded the latest animation node version. so doesnt that mean i m up to date?Peter Baintner <notifications@github.com> hat am 4. Dezember 2017 um 21:45 geschrieben:Please try again with the official Blender version and the current release.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
