### ISSUE TITLE
Dictionary Lookup setup, dealing with list inside list is confusing

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#839]
[AN_dictionary_lookup_002_2017_12_06_10_29.zip](https://github.com/JacquesLucke/animation_nodes/files/1534771/AN_dictionary_lookup_002_2017_12_06_10_29.zip)
![screen shot 2017-12-06 at 21 29 46](https://user-images.githubusercontent.com/3952687/33657215-b120bdb2-dacc-11e7-8348-d461a34e3850.png)

I am trying to do this Dictionary Lookup setup, which I kind of elaborate in my recent video.

Anyhow, the idea is to have Dictionary for Lookup, and List inside List.

I am using Script Node mostly here in this AN setup, hoping that I could process List inside List, but I am confused and stuck.

Questions:
- Wondering if AN already have something like this to do "dictionary lookup"?
- How does AN deal with generic list inside list, do I need to use "Literal Eval"?

**Comment by JacquesLucke** [comment]
AN has something called Structs which are essentially just dicts. However I don't really like them... so not sure if I would recommend you to use them. You can try at least.
