### ISSUE TITLE
"Fill Caps" option of curve doesn't work properly in AN

### ISSUE THREAD

**Issue by Singh-KS** [JacquesLucke/animation_nodes#840]
I try to close caps of a curve which I made with AN. But "Fill Caps" option only closes the one side of the curve. Here I have attached the blend file. 

![fill_caps](https://user-images.githubusercontent.com/30294746/33698966-1ca0c32a-db36-11e7-82d4-0248ffd507e6.png)

[Fill_Caps.zip](https://github.com/JacquesLucke/animation_nodes/files/1537823/Fill_Caps.zip)

**Comment by stansu** [comment]
i got it working when i change spline type from bezier to poly.

**Comment by JacquesLucke** [comment]
Looks like this is a bug in Blender itself because it does work when you change the Bevel End to something smaller than 1.
