### ISSUE TITLE
Compile Animation Nodes for blender 2.8

### ISSUE THREAD

**Issue by XLPmc** [JacquesLucke/animation_nodes#842]
Hey there,
I love animation nodes, because of its simplicity.
I wonder how it would be in EEVEE (Blender 2.8).
So I've tried to install it, but blender always gave me the same answer: Python version mismatch.
My next step would be to compile it in py3.6.2 but I didn't find an exact guide how to compile blender addons.
Thanks for reading I hope you can help me out.

**Comment by JacquesLucke** [comment]
AN does not work with Blender 2.8 yet. 
You would encounter much more problems when you managed to compile it.
It's just not possible for now, sry.

**Comment by jorshD** [comment]
Hello, I love animation nodes and I would like to use it in 2.8, I install it and create the folder in home / .config / blender / scripts / addons / an 2.8, but it does not appear in the addons window to activate it, I would like to know what I am doing wrong. thanks for this wonderful addon :).

**Comment by Clockmender** [comment]
Read the previous answer form Jacques, I quote:

"AN does not work in Blender 2.8 yet."

Seems pretty straight forward to me.

Cheers, Clock.

**Comment by jorshD** [comment]
la respuesta de Jacques es del 10 Dic. 2017, AN ya esta siendo portada y debería funcionar en 2.8.
