### ISSUE TITLE
New Nodes, New Type.

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#844]
Hi Jacques,

I have been busy creating new nodes to animate Objects and Bones:

![screen shot 2017-12-19 at 15 02 09](https://user-images.githubusercontent.com/29657804/34163261-2d6e1756-e4ce-11e7-9294-3ecc8f8bdd37.png)

This image shows all my nodes to date and the ui menu modified to access them. So I have a question:

For the Bone Nodes, I have used "Generic" and "Generic List" sockets to access the bones, this is not ideal I know, but it works, so would it be possible to add a new socket type of "Bone" with "Has List" as an option? This would make the whole set more controlled and less prone to other users getting into trouble by trying to plug other than bones or bone lists into them!

The Copy Offset node is from your manual pages, the others are my own work. I think I am now beginning to understand how this all works! Keep up the great work with AN.

If you are interested and have the time, to look at these nodes, let me know and I can upload them all to my GitHub, or send them via email. I have revised all the nodes previously uploaded (mainly the MIDI nodes) to cater for more complex MIDI scenarios and some bug fixes.

The MIDI nodes are working well, see some of the recent videos on my youtube Channel.

Cheers, Clock.

**Comment by JacquesLucke** [comment]
I don't have the time to look at it in detail right now but I can tell you that it is relatively easy to integrate a new socket type.
Just open the sockets folder, copy one file and modify it a little bit.
I suggest you copy [this](https://github.com/JacquesLucke/animation_nodes/blob/master/animation_nodes/sockets/nla_strip.py) because it contains the least functionality.

**Comment by Clockmender** [comment]
Thanks, I'll get my head around that!

Cheers, Clock.

**Comment by Clockmender** [comment]
This seems to work as far as I can tell, I have done many tests and it has not broken yet...

```
import bpy
from bpy.props import *
from bpy.types import Bone
from .. base_types import AnimationNodeSocket

class BoneSocket(bpy.types.NodeSocket, AnimationNodeSocket):
    bl_idname = "an_BoneSocket"
    bl_label = "Bone Socket"
    dataType = "Bone"
    allowedInputTypes = ["Bone"]
    drawColor = (0.33, 0.63, 0.83, 1)
    storable = False
    comparable = True

    @classmethod
    def getDefaultValue(cls):
        return None

    @classmethod
    def getDefaultValueCode(cls):
        return "None"

    @classmethod
    def correctValue(cls, value):
        if isinstance(value, Bone) or value is None:
            return value, 0
        return cls.getDefaultValue(), 2


class BoneListSocket(bpy.types.NodeSocket, AnimationNodeSocket):
    bl_idname = "an_BoneListSocket"
    bl_label = "Bone List Socket"
    dataType = "Bone List"
    baseDataType = "Bone"
    allowedInputTypes = ["Bone List"]
    drawColor = (0.33, 0.63, 0.83, 0.5)
    storable = False
    comparable = False

    @classmethod
    def getDefaultValue(cls):
        return []

    @classmethod
    def getDefaultValueCode(cls):
        return "[]"

    @classmethod
    def getCopyExpression(cls):
        return "value[:]"

    @classmethod
    def correctValue(cls, value):
        if isinstance(value, list):
            if all(isinstance(element, Bone) or element is None for element in value):
                return value, 0
        return cls.getDefaultValue(), 2
```

![screen shot 2017-12-19 at 17 01 21](https://user-images.githubusercontent.com/29657804/34169139-4e69da70-e4de-11e7-8f46-6511ccac2f28.png)

Thanks for the pointer, just one other point, I cannot find where the icons are stored, can you give me another pointer please.

Cheers, Clock.

**Comment by JacquesLucke** [comment]
The code looks correct.

AN does not come with its own icons. It uses the ones provided by Blender. There is a builtin Blender addon called "Icon Viewer". When you enable it you can see all the icon Blender has in the text editor. Just click on a icon to copy its name.

![image](https://user-images.githubusercontent.com/5881326/34169352-64c0485a-e4e7-11e7-80ef-200d48b925a3.png)

**Comment by Clockmender** [comment]
Thanks so much!

Cheers, Clock.
