### ISSUE TITLE
It´s not working with Blender 2.79.1 (or any buildbot build)

### ISSUE THREAD

**Issue by juangea** [JacquesLucke/animation_nodes#845]
Hi there.

That is the problem, just try to install it in any buildbot build on windows (I cannot try OSx or Linux) and you´ll see the error :)

Cheers!

**Comment by JacquesLucke** [comment]
AN 2.0 is not supposed to work with buildbot builds atm, sorry.
To use AN you should use the official Blender 2.79 release.

**Comment by juangea** [comment]
Ok, 2.79a should be released soon, will it work with it?

Right now we use buildbot builds becaue the ability to render using CPU + GPU, that´s a big win, and this will probably be in the updated 2.79 release.

Thanks for the fast answer!

Cheers.

**Comment by JacquesLucke** [comment]
Yes, I'll update AN to make it compatible with 2.79a when it is released.

With some luck AN will already be compatible with the 2.79a release. It all depends on the Python version that the official version will use. Blender 2.79 uses Python 3.5.x. The current buildbot build uses Python 3.6.x. AN is compiled just for Python 3.5.x, therefore it does not work in the nightly builds.

I was told some months ago that all released Blender 2.79x will use Python 3.5.x. Not sure if they changed their mind though.

**Comment by juangea** [comment]
Ah! Ok, understood.

I imagine that If I want to recompile it with Python 3.6.x would be harder than just click the "compile" button hehehe

Cheers and thanks again for your fast answer!

**Comment by JacquesLucke** [comment]
Here you go, hope it works:
[animation_nodes v2.0a Python 3.6 Windows.zip](https://github.com/JacquesLucke/animation_nodes/files/1572596/animation_nodes.v2.0a.Python.3.6.Windows.zip)

(I just don't want to support buildbots builds officially because that can cause all kinds of problems..)

**Comment by juangea** [comment]
Thanks!

Yeah, I totally understood, that´s why I asked about 2.79a :)

I´ll post here if it works.

Cheers!

**Comment by Copperplate** [comment]
I just had to say a huge thank you, Jacques! This custom build for Python 3.6 you made works beautifully. I am able to begin learning Animation Nodes for the first time using Blender 2.79.3 (f76d49e) which features the CPU + GPU rendering feature that is so needed for animation but is not included in the official build (this feature shaved off over 1 min 30 sec per frame in a 912 frame sequence, or 22.8 hours of render time). Being able to use AN with this build is so great. :-)
