### ISSUE TITLE
Sound nodes missing from menu

### ISSUE THREAD

**Issue by turnage** [JacquesLucke/animation_nodes#846]
On Blender 2.79, animation nodes July 15th release, on [Windows 10, Xubuntu 16.04], some sound nodes are missing from the `shift+a` add menu, and can only be found through `ctrl+a` search. Most notably `Evaluate Sound` is missing from the menu.

Maybe this is by intention, but I was confused trying to follow documentation for earlier versions.

Thank you for your work on animation nodes!

**Comment by JacquesLucke** [comment]
Yeah, that is actually my fault. I will fix that at some point. For now please just use the search.
