### ISSUE TITLE
Downloaded a version from GraphicAll just now and it does not work.

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#847]
<img width="774" alt="screen shot 2017-12-21 at 9 49 27 pm" src="https://user-images.githubusercontent.com/3952687/34252736-f0b2a0a8-e698-11e7-99ad-80e50ef701bb.png">

I think this kind of thing is frustrating. I will download the Github version.

**Comment by enzyme69** [comment]
Actually... I figured out that I should not download zip from Github anymore, but download the link....

DOWNLOAD FROM HERE:
https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0

Every single time I change computer and want to install. I took almost half hour figured this out.

In front of Animation Nodes Github Page, it should be made more obvious I think. Sticky.

**Comment by JacquesLucke** [comment]
![image](https://user-images.githubusercontent.com/5881326/34254942-ae270b74-e64e-11e7-846e-3f21bf7278ab.png)

![image](https://user-images.githubusercontent.com/5881326/34254998-e0d0c114-e64e-11e7-8066-ed986aa3aaec.png)


I don't know how to make it more obvious on the github page.
