### ISSUE TITLE
Unable to install Animation Nodes on Blender 2.79 (Mint 18.3)

### ISSUE THREAD

**Issue by kotlousko** [JacquesLucke/animation_nodes#848]
https://imgur.com/a/d1dsf

I included a jpg ( it says that something is missing. I installed (I think) but still not working.

**Comment by JacquesLucke** [comment]
Maybe you installed numpy for another python version... not sure.
Can you try to download an official Blender release build from blender.org?

**Comment by kotlousko** [comment]
I will try to uninstall and installed those in different order and see what happens
I ll tell you :-)

**Comment by kotlousko** [comment]
The Problem is solved.
There was a numpy installed but not numpy 3.0 . So I installed that too and not I dont get that message
Thanx again (for the plugin too) and I wish you happy holidays !
