### ISSUE TITLE
Animation Nodes not appearing after installation (Mac OS 10.12.6, Blender 2.79)

### ISSUE THREAD

**Issue by mattwolcott** [JacquesLucke/animation_nodes#851]
I am trying to build a layer of animating cubes, and my After Effects MIR is malfunctioning, so I thought I would try Animation Nodes in Blender.

However I went to upgrade from 1.6 to 2.0, and I think I messed something up.

Animation Nodes does not appear anywhere in my Addons. But I get a successful installation notice, and when I go to .../ApplicationSupport/Blender/.../scripts/addons I do in fact see the Animation Nodes files there.

![screen shot 2017-12-22 at 2 47 52 pm](https://user-images.githubusercontent.com/20137388/34314308-24080388-e727-11e7-92d6-76acf0d766ef.png)

I tried manually deleting the files from scripts, closing Blender, and reinstalling, but the same thing happens. 

I'm pulling out my hair because now TWO methods of creating what I need are both broken! Please help!

EDIT: I just tried manually moving the old AN 1.6 to the scripts/addons folder from a prior Blender installation, and this has been recognized by Blender for some reason. AN 1.6 is working but 2.0 is not, apparently.

**Comment by JacquesLucke** [comment]
I hope reading this helps: https://github.com/JacquesLucke/animation_nodes/issues/847

**Comment by mattwolcott** [comment]
YES! So simple, sorry to waste your time. Je te remercie!!
