### ISSUE TITLE
Baker Node or Function for every listed attributes

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#852]
Jacques or other AN devs, is there a nice good way to simply watch and bake all listed attributes on every frames?

AN already can bake some Output as keyframes, but not all. It failed on Blendshapes and Bones... sometimes.

**Comment by enzyme69** [comment]
So far my hacky solution is to use Blender "Button Keying Set" and brute force run this AN Script Node on every frame.
bpy.ops.anim.keyframe_insert()

I am using this with my iPhone X realtime animation.

I don't know if there is a simpler way.

**Comment by JacquesLucke** [comment]
there is the "Set Keyframe" node, maybe it can help you. Beside that, there is no good way of doing that.
