### ISSUE TITLE
This is the ...

### ISSUE THREAD

**Issue by adminradio** [JacquesLucke/animation_nodes#853]
... most beautiful Python code I've ever seen in my entire life! I mean this literally. :)

**Comment by JacquesLucke** [comment]
Thanks man, may I ask why you think that specifically?

**Comment by adminradio** [comment]
First of all: It's easy to follow!

- smart documentation
- well placed whitespace
- things are collected together in *small* files
- no overengeniering
- everything is focused

:)

**Comment by JacquesLucke** [comment]
Thanks a lot! :)
