### ISSUE TITLE
Script is not working during rendering (AN).

### ISSUE THREAD

**Issue by Singh-KS** [JacquesLucke/animation_nodes#854]
Hi,
I want to change the mode of a curve from 3D (FULL) to 2D (BOTH). So I make a small script but it works nicely in viewport animation but not during the rendering. Actually, I'm not expert in python, please help me.

Thank You

![problem](https://user-images.githubusercontent.com/30294746/34892824-ac591b02-f800-11e7-8e52-9271471197c6.png)

[problem1.zip](https://github.com/JacquesLucke/animation_nodes/files/1627296/problem1.zip)

**Comment by JacquesLucke** [comment]
I did not check this in detail yet however one note: You should not access the context while rendering. (-> you should not use the context in you script).

It looks like it would be easier to just run this script "outside" of AN. It would be quite unnatural to change a curve from 2D to 3D and the other way around all the time..

**Comment by Singh-KS** [comment]
Hi Jacques,
Now, I use this command "bpy.data.objects[Obj.name].data.dimensions". Instead of a script, I'm using the expression node and it is working.
 
Thanks, Jacques :)

**Comment by JacquesLucke** [comment]
Instead of `bpy.data.objects[Obj.name].data.dimensions` you could also just use `Obj.data.dimensions`. Those two expressions should be equal, but the second is faster.

**Comment by Singh-KS** [comment]
OK, :)
Thanks, Jacques.
