### ISSUE TITLE
2.0 doesn't work on windows 7

### ISSUE THREAD

**Issue by Retrax57** [JacquesLucke/animation_nodes#856]
Here's the error that shows up when I try to enable it:-

![animnodes bug](https://user-images.githubusercontent.com/30665831/35266178-c032d5f6-0065-11e8-9f28-550ea63b9f5f.png)

Here's my system properties:-

![animnodes bug2](https://user-images.githubusercontent.com/30665831/35266192-d3094e9e-0065-11e8-85cb-38bfaa553dee.png)

And yes I downloaded the correct version for Windows. I reinstalled visual c++ resist 2015 twice but it still didn't work.

**Comment by ikumi90s** [comment]
Same thing happening to me, Windows 7 64bit Japanese is having this issue. I cannot install the add-on at all. I am using Blender 2.79a

**Comment by JacquesLucke** [comment]
I haven't tested AN in Blender 2.79a yet, I might have to do some small fixes.

Will do that after my exams (so most likely on saturday)

Thanks for the report.

**Comment by JacquesLucke** [comment]
hmmm tbh I don't know what is the issue here.. The problem does not seem to be the Blender version. 2.79a seems to work for me.

Do you have any other windows machine to test it one? 

I need more time to figure out why it does not work on your machine,..

**Comment by Retrax57** [comment]
This was on the 2.79 stable release and not on 2.79a. I will try testing this on another machine.

**Comment by janmatys** [comment]
There is nothing like 2.79 stable release imo.

**Comment by JamesKessler** [comment]
I got the same issue when trying AN V2_0 with Blender 2.79 on Win10
