### ISSUE TITLE
Version 2.1 fails to compile C++ extension.

### ISSUE THREAD

**Issue by PrimaryFantasy** [JacquesLucke/animation_nodes#857]
Hi! I'm trying to compile version 2.1 on Linux, because I read that it's "Mesh Object Output" now supports UV maps.

Unfortunately it fails when it tries to compile FastNoiseSIMD, claiming that anything defined in wrapper.pyx is "not a constant, variable or function identifier". See the attached text file.
[an_compile_error1.txt](https://github.com/JacquesLucke/animation_nodes/files/1661592/an_compile_error1.txt)
The command I used was "python3.5 setup.py build --export".

Sorry if this is some really obvious issue. It's my first time compiling python code that includes c++.

**Comment by JacquesLucke** [comment]
I'm don't know why you get this error.. I've never had it.
Which os and cython version do you use specifically?

Yeah, it was also my first time I compiled c++ code at all haha
So I'm still learning from those errors hopefully.

**Comment by PrimaryFantasy** [comment]
Thanks for the quick reply! The OS is Ubuntu 16.04.3 LTS. Python is 3.5.2. Cython was 0.23.4, which turned out to be the problem. This was the latest version in the apt repository. I now installed Cython 0.27.3 using pip. Now it finishes compiling, so this issue is resolved.

Unfortunately Blender doesn't want to activate it now, displaying "ImportError: cannot import name 'Linear'".
![an_import_error_linear](https://user-images.githubusercontent.com/9411535/35359019-e958020a-0158-11e8-867a-193a1a35cf17.jpg)
This is the official version 2.79.

**Comment by JacquesLucke** [comment]
Hmmm :(
I really hate to see this problem because I don't an easy to explain way to solve it.
Maybe it helps when you checkout these issues: https://github.com/JacquesLucke/animation_nodes/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ainstallation

The reason seems to be some python library mismatch but I'm not 100% sure..

**Comment by PrimaryFantasy** [comment]
Thanks for the link. I guess it really is an old library version. I noticed that Python 3.5.2 is also really old. I start to wonder if anything on that apt repository is up to date. I will manually install the latest 3.5.4 tomorrow and re-compile it with that. Hopefully this will work. I will report my results then.

**Comment by PrimaryFantasy** [comment]
Okay, manually updating Python to version 3.5.4 and compiling animation nodes again fixed the issue. It compiled without errors and Blender was able to load it.
So to anyone who reads this: Don't trust apt-get to install the latest software versions.
