### ISSUE TITLE
AN node doesn't execute

### ISSUE THREAD

**Issue by YashPatel000** [JacquesLucke/animation_nodes#858]
When i do undo multiple times the execution doesn't. I try to off auto execution and turned on different mode but not working the i have to start new project. This happen multiple times.

**Comment by JacquesLucke** [comment]
I don't know if it is possible to solve this. Undo operations are quite complex..

**Comment by YashPatel000** [comment]
Ok..Try

**Comment by enzyme69** [comment]
I usually save blend before making any node tree changes. I save every few minutes, new Blend each time.
