### ISSUE TITLE
Ctrl-X not working like in other node systems

### ISSUE THREAD

**Issue by KTakahiro1729** [JacquesLucke/animation_nodes#862]
Hello. I'm rather new to animation nodes and not quite sure whether this is a bug report or a suggestion.

In other node systems, you can erase a node with <kbd>X</kbd> or with <kbd>Ctrl</kbd>-<kbd>X</kbd>. The differences are that the latter automatically connects between the node before and node after the deleted node.

I would like to know 
- whether I'm the only one without one 
and if not, 
- whether I'm not the only one who want this feature.

I use blender2.79, animation nodes 2.0.4, windows 10.

Thanks.

**Comment by Clockmender** [comment]
Personally I would think this will provide a huge overhead in terms of programming and execution and for what? In most cases I can think of,  you would not be able to connect the nodes before and after the deleted one anyway, or the system would not know which socket to use, if there was a choice. Perhaps if you have two Math nodes you might delete one and connect the output from the nodes either side, but I would not like to see the amount of code necessary to implement this, appearing in AN anytime soon.

Take this node tree:

![screen shot 2018-02-09 at 18 29 31](https://user-images.githubusercontent.com/29657804/36043443-4258687a-0dc7-11e8-9e28-f84c96998924.png)

There is not a single node that could be deleted and the two either side connected together. Trust me - I built the node tree.

Just my thoughts....

Cheers, Clock.

**Comment by JacquesLucke** [comment]
I think @Clockmender is right. It is not worth the effort.
