### ISSUE TITLE
Sound Bake Crashes Blender if it is not done first!

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#864]
Hi, got a major issue: I have built a complex node tree for AN and then wanted to add a Sound Bake Node, I get this every time:

![screen shot 2018-02-19 at 15 51 54](https://user-images.githubusercontent.com/29657804/36386259-10ae800c-158d-11e8-813e-1960e7d2d679.png)

Then Blender crashes - this does not happen if I use a new blend file and the same sound file.

Any Ideas? I don't want to have to move everything into a new file, but will if needs must...

Cheers, Clock.

**Comment by JacquesLucke** [comment]
hm that's weird. Can you share the file?

**Comment by Clockmender** [comment]
[music_1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1737408/music_1.blend.zip)

It's got some of my nodes in there also, so I guess that may cause you problems.

**Comment by Clockmender** [comment]
OK, so I made a new blend file, ran the Sound Bake, then appended everything from the previous file and all is OK. So I then made a new blend file, appended everything from the old file and then added the sound bake node and it worked - now I am really confused.

**Comment by Clockmender** [comment]
Sady, in the new project if I then add another Bake Node, this happens:

![screen shot 2018-02-19 at 18 27 49](https://user-images.githubusercontent.com/29657804/36392346-b2e7b7e8-15a2-11e8-81cf-f897e20727d4.png)

Also if I add a second bake node to a new project, the same thing happens.

I'll leave it with you.....

**Comment by Clockmender** [comment]
I had a similar issue with a script node that tries to make objects. If you have an armature in the 3D view, selected, the node fails with a context error. The answer to both problems is to simply make the 3D view something else while running you sound bake node. I have spent some time trying to isolate exactly what caused this, but it is taking to long and I have a simple fix and you are busy with your studies, etc. So I will wishe you well with your studies and close this.

Cheers, Clock.
