### ISSUE TITLE
Why the vertex paint does not work when the animation node addon is enabled

### ISSUE THREAD

**Issue by 765563652** [JacquesLucke/animation_nodes#865]
In blender2.79 and 2.79a.

**Comment by OmarSquircleArt** [comment]
Enabling Animation Nodes should not interfere with Vertex Paint, but if you are doing something with AN, such behavior would be explained as follows. If you are dynamically outputting meshes using the *Mesh Output* node, then any edits to the mesh (Including Vertex Paint) will be lost, that is, assuming the node tree is executing. If you are only editing the vertices locations and want to preserve vertex paint, you can use the Vertices Location output type in the *Mesh Output* node. If your vertex paint is solid color, you can use the *Set Vertex Color* node. If your vertex color map can be created procedurally, you can use some python scripting, I can elaborate on that if you want.
