### ISSUE TITLE
Cache feature of Group-Node does not work when the output socket is enabled, why? 

### ISSUE THREAD

**Issue by Singh-KS** [JacquesLucke/animation_nodes#868]
Hi,
Cache feature of Group-Node does not work when the output socket is enabled.
Here is the screen-shot and blend file:
![screenshot from 2018-02-26 00-45-57](https://user-images.githubusercontent.com/30294746/36645720-1d62f20a-1a93-11e8-9001-ff293e863e45.png)
[Cache_problem.tar.gz](https://github.com/JacquesLucke/animation_nodes/files/1756635/Cache_problem.tar.gz)

**Comment by JacquesLucke** [comment]
Due to a "limitation/design decision" in Blender I cannot/should not cache objects.
Also when you have a Object Transforms Output node in a subprogram it does not make much sense to cache the result because then the nodes in the subprogram won't be executed anymore.

**Comment by Singh-KS** [comment]
OK. Actually, this is just a example for illustration. 
Thanks Jacques :)
