### ISSUE TITLE
slice only accept vectors

### ISSUE THREAD

**Issue by bliblubli** [JacquesLucke/animation_nodes#869]
Hi,

when I plug a list in the slice list node, if the elements of the list are not vectors, it triggers an error. I workaround that by generating vectors from my floats and then separate each vector to floats again, but it's a bit cumbersome. I'm not sure if it's a known limitation or a bug, but I thought I would report it just in case.

**Comment by JacquesLucke** [comment]
hmm usually the slice list node should adapt to the Input type. Either you do something crazy or there is a bug :D
Can you show a screenshot of the node tree and of the terminal?
