### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by bliblubli** [JacquesLucke/animation_nodes#870]
Hi,
After using AN for some days, I thought some ideas may help make it easier to organize/use:
- the viewer node is awesome, but in very big nodetrees, it adds chaos. Having a material icon like in the texture and compositing nodes would make node trees consistent, would really help when moving things around, would also make it more clear what is previewed, is faster than adding a node and connect it and help keep things organized.
![tex_nodes](https://user-images.githubusercontent.com/29454545/36740129-d84fcf12-1be1-11e8-8a15-28bd596be5fc.png)
In this picture, it's the icon in the top right corner.
- an easy way to have custom nodes with dropdown menus (based on dict to know what to ouput for each possible choice, like the frame rate option in render tab-> dimensions) and slider (like the percentage slider in render tab -> dimensions) would allow to more efficiently represent some kinds of inputs in a user friendly manner.
- A way to organize the data inputs in viewport (adding categories, moving them up and down) would help to make complex models manageable.

**Comment by JacquesLucke** [comment]
I don't think that an additional checkbox in each node would be an improvement. It would just clutter the UI a lot.

You don't actually have to create the viewer node and connect it manually. When you have a node selected press and hold `W`, move the mouse down, then release `W`. This is the fastest way to create a viewer node without cluttering the UI.

Yes, customizable drop down are a good idea. Not sure how they should work exactly on the user level, but I'm sure we can find a way to do it.

**Comment by bliblubli** [comment]
regarding the preview, it's your call, but what I thought about wouldn't clutter the UI but make it consistent. There is already this preview function in the all nodes (texture, compositing, only cycles doesn't has it yet). Here how it looks in texture nodes, I would use the same icon:
![tex_nodes](https://user-images.githubusercontent.com/29454545/36740129-d84fcf12-1be1-11e8-8a15-28bd596be5fc.png)

**Comment by bliblubli** [comment]
I just write my ideas down as they come:
A way to organize the data inputs in viewport (adding categories, moving them up and down) would help to make complex models manageable.
