### ISSUE TITLE
I made a new Vertex Color Node

### ISSUE THREAD

**Issue by Lumpengnom** [JacquesLucke/animation_nodes#871]
Hi,
I wasn´t able to change Cycles materials with Animation Nodes, at least not with very much control. Specifically I wanted to control materials with AN Falloffs just like you are able to offset matrices and things like that.
I coded a node that lets the user control vertex color on a per vertex basis (actually on a loop/polygon vertex basis) which again can control Cycles materials with the "Attribute" node.

Here is a short Test Animation. The whole thing is controlled by an empty that moves along the X-Axis and has an "Object Controller Falloff" node.

Is anybody interested in a node like this? Or does something like this exist allready? Is there a website where users can upload and share their nodes somewhere or something like that?

https://youtu.be/2fg_cLfLMxc

**Comment by Clockmender** [comment]
I have posted my nodes here [https://github.com/Clockmender/My-AN-Nodes](url) on GitHub - with releases under the "Releases" tab, I don't know if that is any help for you to make your own releases in the same way, or add them to mine? I don't know how to add a new contributor, but could find out, if you are interested. My materials nodes work on the whole object, not individual vertices, so your work would be a nice add-on to what I have done. Let me know what you think and I can find out how to do this.

I have one material Input node that lists all materials in the project, or filters them, then another that assigns materials to slots, or switches two materials to material slots. I too couldn't find a node that did this although there are nodes to change the look of an assigned material.

![screen shot 2018-03-05 at 12 15 48](https://user-images.githubusercontent.com/29657804/36974565-ffc3ee02-206e-11e8-85c2-30c78e777944.png)

This node tree changes material slot 1 to Green from Blue after frame 50.

I liked the animation by the way, very slick.

Cheers, Clock.

**Comment by Lumpengnom** [comment]
Sure, why not.
If I understand correctly I have to add a pull request but I first have to figure out how to do that. I´m not a programmer, so I am not familiar with git hub and how all of this works.

Anyway, here some more information about the VertexColors node:

Note that the plane in the following examples has a pretty high resolution. IIRC it is a 50 X 50 grid.

This simple node tree was used for the two following clips:
![nodetree](https://user-images.githubusercontent.com/36137584/36999050-39cab360-20bf-11e8-87a6-2dd01d454762.PNG)

https://youtu.be/gT5YGG2qYdM
https://youtu.be/4zwFsqN1BAE


This node tree is a bit more complex and shows how to use the same falloff for the geometry deformation and color change in the material:
![nodetreecomplex](https://user-images.githubusercontent.com/36137584/36999117-6af6de50-20bf-11e8-8449-c623b5df5f34.PNG)

https://youtu.be/ecMaHXVtqFQ

Both node trees use the Attribute node in the Cycles material to blend based on vertex color:
![shader](https://user-images.githubusercontent.com/36137584/36999151-8ce0678e-20bf-11e8-8f51-2bc17ab71758.PNG)

**Comment by Clockmender** [comment]
You could just [mail](clockmender@icloud.com) me the code and I will add it to my GitHub release.

Might be easier until we get the correct procedure sorted out.

I like what you have done here!
