### ISSUE TITLE
Is it already possible to transform polygons from other than their median point? 

### ISSUE THREAD

**Issue by prubini87** [JacquesLucke/animation_nodes#872]
Hi, I'd like to know if it's possible to control how you transform polygons changing their individual "origin" to something like North, South, West, East, or even to an exact location with, say, a python expression? I'd like to be able to scale down all polygons of a mesh, however, I want them to scale from "top-down", instead of converging to the middle from all sides, if that makes sense? 
Any ideas?

**Comment by JacquesLucke** [comment]
Unfortunately this is not easy to do atm. It is something I wanted to do for quite a long time but never actually implemented it..

**Comment by JacquesLucke** [comment]
I decided to work on this today :D 
Unfortunately this is still work in progress and not ready for use.
![custom polygon pivot](https://user-images.githubusercontent.com/5881326/37651915-02cd461c-2c3a-11e8-9710-17f4f79a462e.gif)

**Comment by prubini87** [comment]
Awesome Jacques!! That's exactly what I meant! I'm sketching what I imagine
could be useful on the ui/node side and I'll post it as soon as I can,
hopefully tonight! Keep it up, please! \o

Em ter, 20 de mar de 2018 08:28, Jacques Lucke <notifications@github.com>
escreveu:

**Comment by prubini87** [comment]
Here's a pivot coordinate system I thought could be used (2D) for polygons and (3D) for objects. Of course this is a draft but it might work out? The 3D representation is for objects and is based on the object's bounding box.
![an_pivot_coordinates](https://user-images.githubusercontent.com/2468251/37807703-988c648e-2e25-11e8-9057-d312bc2c1af3.jpg)

**Comment by JacquesLucke** [comment]
I'm not sure what you suggest here. A node that creates this structure or what? If so, please tell me what inputs and outputs it should have. Is this in some way related to the original issue?

**Comment by prubini87** [comment]
I'm sorry for my huge delay in answering you. Here's another image I created to try to illustrate my idea... It's probably not ideal but a node like that would allow us to change the pivot of the polygons using XYZ coordinates...

![node](https://user-images.githubusercontent.com/2468251/38770239-25a9d65e-3fe6-11e8-8bce-2da2ec45ce29.jpg)
