### ISSUE TITLE
Export animation data to csv?

### ISSUE THREAD

**Issue by AhmedSalih3d** [JacquesLucke/animation_nodes#873]
Hello! I am able to view how my z location changes (I made a simple cube moving up), but is there anyway for me to export to .csv file format?

Or is this not supported and I have to do python?

Kind regards

**Comment by JacquesLucke** [comment]
There are no special nodes that deal with CSV files atm. Also what you are trying to is baking the animation. Best thing would be to write a small script that does exactly what you need.

```python
import os
import bpy

scene = bpy.context.scene
object = bpy.context.active_object

startFrame = 1
endFrame = 50

positions = []
for frame in range(startFrame, endFrame+1):
    scene.frame_set(frame)
    positions.append(object.location.z)
    
csv = ",".join(map(str, positions))

directory = os.path.dirname(bpy.data.filepath)
path = os.path.join(directory, "positions.csv")

with open(path, "w") as f:
    f.write(csv)
```

This script stores the z positions in a `positions.csv` file in the folder where the .blend file is.
