### ISSUE TITLE
[BUG?] get spline length error

### ISSUE THREAD

**Issue by stansu** [JacquesLucke/animation_nodes#875]
when i use spiral spline, the get length node become strange.
play attached blend file's animation for detail.
[spline_length_bug.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1809752/spline_length_bug.blend.zip)

**Comment by JacquesLucke** [comment]
To fix this you can increase the resolution in the advanced settings of the `Get Spline Length` node.
