### ISSUE TITLE
When animation nodes will continue to update

### ISSUE THREAD

**Issue by 765563652** [JacquesLucke/animation_nodes#876]
It has not been updated for several months.

**Comment by JacquesLucke** [comment]
I just finished my exams and came back from my vacation. Right now I'm working on another little project for learning purposes (it is also available on Github but probably not of great interest for most people). 
In a few days I'll start to do some stuff on AN again.

**Comment by stansu** [comment]
thanks for your hard works!

**Comment by enzyme69** [comment]
Looking forward to more updates. Hopefully keep being updated to Blender
2.8 transition.

**Comment by LeonCheung** [comment]
Finally, there comes the J boy!

**Comment by Tungee** [comment]
THATS SO GREAT!

**Comment by mirlip** [comment]
@765563652 don't forget to also update your donations :)

**Comment by JacquesLucke** [comment]
Started today, so I'll close this ;D
