### ISSUE TITLE
Animation Nodes for updated Blender Python?

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#877]
I am using Blender built that is being prepared for 2.8.

<img width="897" alt="screen shot 2018-03-15 at 10 23 36 pm" src="https://user-images.githubusercontent.com/3952687/37460550-a1125018-289f-11e8-961f-c617b064cec2.png">

Seems like I need AN that is built for this newer version of Python. Do we have updated AN?

**Comment by JacquesLucke** [comment]
1. yes you would need a an AN build for Python 3.6
2. AN does not support Blender 2.8 yet. 

I think supporting Blender 2.8 would still be a big mess for me because afaik it is still quite buggy and changes a lot.

**Comment by mirlip** [comment]
I agree, 2.8 makes no sens at this point, it's a moving target for coders and would eat a lot of time just to repair what would get broken on a regular basis. Building AN with python 3.6 is easy, (see doc) but even latest master seem to have broken something, so 3.6 makes no sens until AN works on latest master.
