### ISSUE TITLE
[BUG] {object mesh data} node's vertex normals is incorrect 

### ISSUE THREAD

**Issue by stansu** [JacquesLucke/animation_nodes#878]
check my attachment and toggle use modifiers on {object mesh data} node to see the error.
[bug_vertex_normal.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1817651/bug_vertex_normal.blend.zip)

**Comment by JacquesLucke** [comment]
I see the problem. In v2.0 AN does not calculate the normals itself.. You could use some bmesh nodes to calculate the normals.

In v2.1 this is already handled correctly. Thanks for the report but I think there is nothing for me to fix here that is not already fixed in v2.1.
