### ISSUE TITLE
Baking Sound doesn't work

### ISSUE THREAD

**Issue by giannagco** [JacquesLucke/animation_nodes#885]
Whenever I try to bake sound in animation nodes, this error pops up:
![error](https://user-images.githubusercontent.com/28737151/38014471-dcba7bae-3236-11e8-8c6d-7cf9d9811cbc.PNG)
I have versions 2.79 for Blender and 2.0 for AN downloaded.

**Comment by JacquesLucke** [comment]
I should investigate this bug in more detail. For now you could try out the solution that seemed to work here: https://github.com/JacquesLucke/animation_nodes/issues/864

**Comment by giannagco** [comment]
I looked into the solution for #864 and it didn't work for my situation, but I did find that because I didn't have the "Animation Nodes Object Container" selected in the Outliner, I received the context error message. Once I selected it, I was able to bake my sound 👍

**Comment by JacquesLucke** [comment]
Thanks for the additional information!

**Comment by videodromex** [comment]
@giannagco can you help me? I'm having the same problem as you did. I tried to change the view from the 3D view to different types and that didn't solve the problem. What do you mean with "I didn't have the Animation Notes Object Container Selected in the Outliner"? Blender newbie here. Thanks in advance!

**Comment by videodromex** [comment]
Nevermind, I googled "Blender Outliner" and understood what you were saying. Did what you say and it worked now. I really appreciate it. Thanks @JacquesLucke and @giannagco . Jacques, great work, what you did is awesome!
