### ISSUE TITLE
Cannot Evaluate Falloff With Matrices

### ISSUE THREAD

**Issue by videodromex** [JacquesLucke/animation_nodes#887]
While trying to complete the tutorial found at https://www.youtube.com/watch?v=HBCdC7r7Mp4 I got an error message that read "Cannot Evaluate Falloff With Matrices". Nodes images with error displayed and .blend file are included below. Thanks in advance.

I'm using Blender 2.79 with the 2.1 Animation Nodes Build.

![errornodes02](https://user-images.githubusercontent.com/5829573/38210434-07078a10-367d-11e8-9336-2fc2bfcff50c.PNG)
![falloffbypass](https://user-images.githubusercontent.com/5829573/38210436-071c80e6-367d-11e8-8328-3c7dcfe5358a.PNG)
![nodeserror](https://user-images.githubusercontent.com/5829573/38210437-073433b2-367d-11e8-9122-142751460128.PNG)
[audiovizhamster.zip](https://github.com/JacquesLucke/animation_nodes/files/1869006/audiovizhamster.zip)

**Comment by JacquesLucke** [comment]
Fixed it. I will upload new test builds within the next few days.

**Comment by JacquesLucke** [comment]
I uploaded the new builds: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_testbuilds
