### ISSUE TITLE
Congrats on 2.1 dev

### ISSUE THREAD

**Issue by reanimastudios** [JacquesLucke/animation_nodes#888]
Master version of Blender and the Python 3.6 version of Animation Nodes loads w/o throwing any errors.

Rendered the music animation nodes tutorial from YouTube.

[https://photos.app.goo.gl/FL8PBr7YuuSVjOUh2](https://photos.app.goo.gl/FL8PBr7YuuSVjOUh2)

**Comment by JacquesLucke** [comment]
Nice one :)
