### ISSUE TITLE
Feature request for 2.1's circle mesh generator

### ISSUE THREAD

**Issue by davidgilson** [JacquesLucke/animation_nodes#889]
Trying to use the new Circle generator to just create a simple circle of points.  There are currently two options:

- Set inner and outer radius to the same value, then run BMesh Remove Doubles.

- Enable "Merge Center", and then remove last vertex located at the center.

Clearly, when dealing with a vectorized radii input, this becomes a tedious and complicated task! Therefore, would it possible to have an option to create just single loop of edges per radii? One suggestion would be to make this the Zero Inner Loops state (i.e. no poligons, only single loop of edges).

For added context, I'm interested in using the vertex locations to drive other things, such as object instance locations, and splines.

Interestingly I was already working on a node tree to do a similiar job to this in AN 2.0 (see second screenshot)

Please see my screenshot for an example of the 'wrapping' I'm currently putting around this node.

![circle-node-logic-wrapper](https://user-images.githubusercontent.com/8432686/38280156-b43a960e-379b-11e8-80ac-158d32edb79c.PNG)

![an20-circle-node-logic-wrapper](https://user-images.githubusercontent.com/8432686/38280475-61784a4a-379d-11e8-946e-73ee51cae4e2.PNG)

**Comment by OmarSquircleArt** [comment]
The *Distribute Matrix Circle Option* already does exactly what you want. So I see no reason why we should implement that in the Circle **Mesh** Node.

The only difference is that you can't define the start angle and that the end angle is defined as a normalized value ([0, 1] --> [0, 2pi]) but this is easily solved by a z rotation matrix node.

**Comment by davidgilson** [comment]
Perfect, I had no idea that existed. I appreciate you pointing it out! I'll close this issue now.
