### ISSUE TITLE
Bug with Sound Falloff in 2.1

### ISSUE THREAD

**Issue by davidgilson** [JacquesLucke/animation_nodes#890]
When using the Sound Falloff node with vectorized input, it returns an error "This falloff cannot be evaluated for vectors". This error can be reproduced by following one of the examples in the AN 2.0 documentation.

(Using Blender 2.79b, and Python 3.5 build for Windows of AN 2.1).

![sound-falloff](https://user-images.githubusercontent.com/8432686/38314448-1eaf65dc-381e-11e8-96d7-145081e94b8c.png)

**Comment by JacquesLucke** [comment]
Fixed this yesterday: #887
Thanks for the report :)

**Comment by JacquesLucke** [comment]
New builds are up: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_testbuilds
