### ISSUE TITLE
Separate Text Object node crash when clicking on update

### ISSUE THREAD

**Issue by argentads** [JacquesLucke/animation_nodes#892]
![an 2 1 1 bug crash report](https://user-images.githubusercontent.com/38163143/38457601-b3bab1b8-3a8a-11e8-867f-3eda97c6dc85.jpg)

**Comment by JacquesLucke** [comment]
is it possible that you were in edit mode while pressing that button? (I'm asking because I had a very similar issue a few days ago in the Sound Bake node)

Also, can you share the .blend file?

**Comment by argentads** [comment]
Sure thing - also it seems to be working now! weird. I was not in edit mode though.
[text movement with an.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/1886571/text.movement.with.an.blend.zip)

**Comment by JacquesLucke** [comment]
I'm not sure if I fixed this exact bug because I could not reproduce it. I fixed something related though. Please reopen this issue when the bug still appears in the next version.
