### ISSUE TITLE
Animation Nodes  Python Version Troubles

### ISSUE THREAD

**Issue by DrChivago** [JacquesLucke/animation_nodes#898]
Hi Thanks for create the animation node addon its look great! but when i see a youtube tutorial about the animationnode  i dont see any kind of comment that it speaks about the python version it seem like noboby has the  problem of the versions, i work with the blender 2.79 but when i instal the zip file and cherckmark the option of nodes the warning versions appears saying that animation nodes has been compiled for the 3,6,1 Python version. And it says that i have 3 options one of them its "Compile animation nodes yourself using the correct Python version" (and look the developer manual) So there is the main problem i realy try to follow the steps that i seen in the description but there is a few things that can not made me forward like this indication ...     
![cython](https://user-images.githubusercontent.com/8557649/38781050-558e2496-40a5-11e8-8e85-434e6fbee4cb.JPG)
i think its to dificult to people that has no any knowledge about develop or programing. like me. Because i dont know where should i run "Conda install Cython" i realy try to made it by myself without ask to you or somebody else and take a little bit part of your time but it seem like i cant avoid that. 
Sorry for the extension of the issue an for my bad english. Its not my domain language. Can you help me wih this problem? Please do a tutorial to change the version of phyton in Blender! Thank you very Much!

**Comment by OmarSquircleArt** [comment]
There are builds in the release page for python 3.5. So no need to compile. You can use those.

**Comment by DrChivago** [comment]
Thanks for respond me  Omar Ahmad... Sorry for my next question,  so you say that i can download the 3.6 phyton version in the official site (https://www.python.org/downloads/windows/) and then when i save the version in my computer are the addon nodes availabe to use? how come be the procces to update the versions of phyton in my system?

**Comment by OmarSquircleArt** [comment]
Sorry about the confusion, I meant that that you can download Animation Nodes versions for python 3.5, the one you already have. You can download it from here:

https://github.com/JacquesLucke/animation_nodes/releases
