### ISSUE TITLE
Appending

### ISSUE THREAD

**Issue by LeanderSilur** [JacquesLucke/animation_nodes#899]
Can't execute node tree after appending to a new file.

File "...\utils\nodes.py", line 18, in idToNode return bpy.data.node_groups[nodeID[0]].nodes[nodeID[[1]]
KeyError:'bpy_prop_collection[key]: key "NodeTree" not found'

After restarting Blender and reopening the file, the error disappears.

**Comment by stansu** [comment]
can you provide blend file for detail?

**Comment by LeanderSilur** [comment]
Sorry, cannot reproduce.
