### ISSUE TITLE
add sverchok node to AN will cause error

### ISSUE THREAD

**Issue by stansu** [JacquesLucke/animation_nodes#904]
i use sverchok and AN, some times i'll forgot and pressed Ctrl+space then add sverchok node in AN.
then AN will not respone anything util  i restart blender.
sverchok will not respone Ctrl+a hotkey, so why AN will respone Ctrl+space?
just curious, thanks for reply.

**Comment by JacquesLucke** [comment]
I'm not 100% sure but this sounds more like a bug in Sverchok and not in AN.
They have to make sure that their shortcuts only work on a Sverchok tree.

**Comment by stansu** [comment]
but i can add sverchok's node in shader tree or compositing tree and still works.
why?
thanks your hard work.

**Comment by stansu** [comment]
i report to sverchok and they will fix it.
https://github.com/nortikin/sverchok/issues/2209
thanks!
