### ISSUE TITLE
libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jaggzh** [JacquesLucke/animation_nodes#906]
**The python3.6m on my system is the one provided by Blender.  It appears to have a static (.a) lib, but not a shared one.**

When installing the linux 3.6 .zip, in a fresh blender git build, enabling the addon results in the error:
"..... /animation_nodes/__init__.py", line 140, in <module>
    try: from . import test_compile
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

**Comment by jaggzh** [comment]
Fixed, for now. I had a miniconda version, with 3.6m, which I installed the other day for another project.
I set my LD_LIBRARY_PATH to the lib/ folder with the .so and re-ran blender -- Animation Nodes then activated without error.  Is it an issue that the Linux version of Blender, with its provided Python 3.6m, doesn't provide the .so?

**Comment by gireek** [comment]
sudo apt-get install libpython3.6 Try this once.

**Comment by spate141** [comment]
@gireek THANK YOU!!! Coming here from totally different issue, but had issues with `libpython3.5`. Didn't know that apt-get has this as package!

**Comment by sushrutt12** [comment]
All it needs is a link to the lib folder so add a link in the path
For Red Hat users: 
```
cd
vim .bashrc
export LD_LIBRARY_PATH=~/anaconda3/lib
```
