### ISSUE TITLE
help~ !  i don't find vertex in loop up !

### ISSUE THREAD

**Issue by WeijiaNing** [JacquesLucke/animation_nodes#910]
In mac os animation_nodes 2.0.4 ,   subprograms ->  loop input   ->  New Iterator . 
i don't find  vertex List , only have a vector List.
Please tell me how to find **vertex list** thank you！

**Comment by WeijiaNing** [comment]
![22be0eb7-c554-4777-a895-a7d856b7eda6](https://user-images.githubusercontent.com/13624072/39953850-eec02c6c-55e6-11e8-959b-5c4b365f44b9.png)

**Comment by OmarSquircleArt** [comment]
Vertex Data Type and its list were removed in version 2.0. Vertex info are now exposed in other nodes like Mesh Input Node.
