### ISSUE TITLE
Use current transforms checkbox is missing in 2.1

### ISSUE THREAD

**Issue by different55** [JacquesLucke/animation_nodes#911]
For the Object Transforms Input node, in the Advance Node Settings it used to have a "Use current transforms" checkbox, unselecting that would let you grab transformations from other frames. That's gone in 2.1, and AFAIK there's no way to do the same thing.

![screenshot from 2018-05-12 10-28-59](https://user-images.githubusercontent.com/585419/39958916-64a88004-55cf-11e8-92b3-14e91becc6b2.png)

**Comment by OmarSquircleArt** [comment]
You can get the same result by evaluating the corresponding F-Curces of the transfromations channels at the required frame. For more info, see documentation on [*FCurve From Object Node*][1] and [*Evaluate FCurve Node*][2].

[1]: http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/fcurves/fcurves_from_object.html
[2]: http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/fcurves/evaluate_fcurve.html
