### ISSUE TITLE
AN not working on blender 2.79b?

### ISSUE THREAD

**Issue by eslogan** [JacquesLucke/animation_nodes#913]
I've got this problem when attempting to install AN on Blender 2.79b:

There is a Python Version mismatch
Your blender build uses: (3, 6, 3)
Animation Nodes has been compiled for (3, 5, 3)

**Comment by OmarSquircleArt** [comment]
See [Troubleshooting Guide](http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html#troubleshooting). The only Python 3.6 builds are for version 2.1 beta which you can download from [the release page](https://github.com/JacquesLucke/animation_nodes/releases).
