### ISSUE TITLE
mesh from object error

### ISSUE THREAD

**Issue by argentads** [JacquesLucke/animation_nodes#914]
Following along your Cube Ocean and Polygon Effects tutorial and got this error when trying to add the Mesh from Object node
![screen shot 2018-05-23 at 08 17 54](https://user-images.githubusercontent.com/38163143/40409206-049e93e2-5e62-11e8-82d7-3d429fa7fede.png)
![screen shot 2018-05-23 at 08 18 15](https://user-images.githubusercontent.com/38163143/40409220-0e729332-5e62-11e8-8fcb-ad6650c4667c.png)
I am running on an imac and using Blender 2·79b and AN 2·1·2
Regards
Alex

**Comment by JacquesLucke** [comment]
unfortunately this is a bug. The menu is just not updated yet.
Please just use the Mesh Object Input node instead.

**Comment by Shujee** [comment]
Experiencing the same. Is this bug going to be fixed soon?
