### ISSUE TITLE
Uncompiled, platform independent version

### ISSUE THREAD

**Issue by piegamesde** [JacquesLucke/animation_nodes#916]
As an Arch Linux user, I always have Blender with the latest Python version. At this moment, it is matched by the 2.1 Pre-Releases but there is no way this will always be the case. This is a problem since every Python upgrade might potentially break the extension.

My proposal hence is: please provide a pure, interpreted version of the addon that is independent from any OS or Python configurations. I know the performance isn't that great, but in most of my projects I don't really care and it greatly reduces the amount of work I have to do to keep the extension up to date.

**Comment by OmarSquircleArt** [comment]
I don't think an OS independent version can be created. However, Animation Nodes exist in [AUR](https://aur.archlinux.org/packages/blender-plugin-animation-nodes-git/). If you don't know how to install it, simply follow the following steps.

Create a folder called `aur` somewhere, then in that path, execute the following:
```
git clone https://aur.archlinux.org/blender-plugin-animation-nodes-git.git
cd blender-plugin-animation-nodes-git
makepkg -sci
```

Wait till it finishes compiling and you are done. If you want to update it to the latest git, execute that again.

**Comment by piegamesde** [comment]
This is really cool. I knew I could find everything in the AUR, but I wasn't expecting it to be _literally_ everything. It is even simpler to install if you have `aurman` or similar.
