### ISSUE TITLE
I can't install the blender animation node-master in 2.79

### ISSUE THREAD

**Issue by Nicolae1234** [JacquesLucke/animation_nodes#918]
Help me! I need to install the animation node but from no reason after i install the add-on nothing happened, it should show a check box at the node categories but is not. Did i missed something? please help me!

**Comment by OmarSquircleArt** [comment]
Did you check the [Installation and Troubleshooting](http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html) guide?

**Comment by Nicolae1234** [comment]
thx a lot it worked!
