### ISSUE TITLE
Animation nodes add on not installing 

### ISSUE THREAD

**Issue by cambrowning96** [JacquesLucke/animation_nodes#919]
I go to load add on from files and go to file I downloaded from here but after I click it nothing happens. Not sure what to do. I’m pretty new to blender

**Comment by OmarSquircleArt** [comment]
Did you check the [Installation and Troubleshooting](http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html) guide?

**Comment by cambrowning96** [comment]
I did and still nothing

**Comment by OmarSquircleArt** [comment]
The addon doesn't appear when you search for it? Can you manually insert the animation nodes folder into your blender's addons directory?

**Comment by cambrowning96** [comment]
It does not appear and I tried manually inserting and still nothing

**Comment by cambrowning96** [comment]
I then tried changing the target path from default to ‘user prefs’ and I get “error failed to get addons path”

**Comment by OmarSquircleArt** [comment]
In the path `/blender/2.79/scripts/addons/`, is there a folder called `animation_nodes`? If so, is there a `__init__.py` filde inside it? What is the permission status of those files?

**Comment by cambrowning96** [comment]
I appreciate you trying to help a lot but I honestly have no idea how to do that

**Comment by JacquesLucke** [comment]
where/how did you download the .zip file exactly?

**Comment by cambrowning96** [comment]
From github and it downloaded to my downloads file

**Comment by JacquesLucke** [comment]
"from github" is not really specific. Did you download it from here? https://github.com/JacquesLucke/animation_nodes/releases

**Comment by cambrowning96** [comment]
Yes the 2.0 for Windows

**Comment by OmarSquircleArt** [comment]
Download the zip file again, extract it anywhere, copy it to `C:\Users\%username%\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\`. Then go to the addons panel, search for it and activate it. If this didn't work, I am not sure what the problem is.
