### ISSUE TITLE
Python version mismatch

### ISSUE THREAD

**Issue by yvesbodson** [JacquesLucke/animation_nodes#921]
I get the following error messages with both Blender 2.79 and 2.80 on Linux Platform, Ubuntu 18.04, Python version is 2.7
I suppose that you will or have proposed a solution at the time of this report.;

your Blender build uses (3.6.2)
Animation nodes has been compiled for (3.5.3)

**Comment by OmarSquircleArt** [comment]
See the [troubleshooting](http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html#troubleshooting) section in the installation guide. The [release page](https://github.com/JacquesLucke/animation_nodes/releases) contains 2.1 versions for python 3.6, you should use it instead.

Animation Nodes don't support 2.8 at the moment, no addon does as far as I know.
