### ISSUE TITLE
Problem installing the Add-on

### ISSUE THREAD

**Issue by Mardoek53** [JacquesLucke/animation_nodes#923]
I have downloaded the animation_nodes_master.zip file from

https://github.com/JacquesLucke/animation_nodes

After installing the Add-on in Blender, it was not visible in the blender Add-on list. I thought I might have downloaded a wrong version and I found the page with the releases ->

https://github.com/JacquesLucke/animation_nodes/releases

Here I downloaded the file animation_nodes_v2_0_windows.zip. 

If I now install this file in Blender, it is visible in the Add-on list. But if I try to check this, then I get the error message (see attachment) that there is still an old version of the Add-on and that it has to be removed first. But I can not find that old version in the Blender Add-on list and so I cannot delete it.

How can I solve this problem best?

![foutmelding](https://user-images.githubusercontent.com/41394112/42906824-7047d0f8-8adc-11e8-8891-cb79eba92dc6.jpg)

**Comment by JacquesLucke** [comment]
Try going into the addons folder of Blender. You can find the path in the error message you posted.
There should be more than one folder with "animation_nodes" in the name. Remove them all and install the version from the release site again.

**Comment by Mardoek53** [comment]
That has indeed solved the problem. Thank you for your fast reply and help!
