### ISSUE TITLE
problem installing AN

### ISSUE THREAD

**Issue by plvral** [JacquesLucke/animation_nodes#924]
Hello, I can't seem to find the zip file for the AN? I'm using a 2017 Macbookpro, please help me. Thank you!

**Comment by plvral** [comment]
![screen shot 2018-07-20 at 1 10 28 am](https://user-images.githubusercontent.com/41446103/42959081-1e359ba4-8bba-11e8-9099-ab1621c3c568.png)

**Comment by JacquesLucke** [comment]
https://github.com/JacquesLucke/animation_nodes/issues/923
