### ISSUE TITLE
Object Transforms Input missing Advanced setting.

### ISSUE THREAD

**Issue by LuisBurdallo** [JacquesLucke/animation_nodes#927]
Hi,

I was wondering if I am doing things right but I can't find the "Use Current Transformations" under the advanced node settings mentioned in the documentation in order to have the frame option available. I only have "Create Execution Trigger"

Thanks in advance.

**Comment by OmarSquircleArt** [comment]
This option was removed in version 2.1, it is still available in version 2.0. Maybe you confused versions.
The documentation for the *Evaluate F-Curve* node include an example for what you are looking for.

**Comment by LuisBurdallo** [comment]
I am on 2.1.2 and found a way to make it work using Fcurve, Thanks for pointing that out to another user.
