### ISSUE TITLE
Vectorized sockets stops automatic conversion upon duplication.

### ISSUE THREAD

**Issue by OmarSquircleArt** [JacquesLucke/animation_nodes#928]
This bug has been happening since the refactor of the vectorization code, in this issue, I shall report the situations where it happens to possibly narrow its cause.

## Situation 1

A node with a vectorized input is connected to a list, if this node is duplicated and the input of the duplicate is connected to another socket---Single or list(possibly the same socket as the original node), the original node gets disconnected. If the type connected to the duplicate was a list and not a single, the original node input won't accept lists, but only singles. If the type connected to the duplicate was a single, the original node accepts both as predicted.

![duplicating_bug](https://user-images.githubusercontent.com/25300994/43582069-5ee6ef3a-965b-11e8-9913-840ce0656287.gif)

***
I will try to add other situations if encountered.

**Comment by mattdw** [comment]
It's interesting that it disconnects the socket of the original copy – my guess would be that something isn't getting deep-copied on duplication and there's an unexpected shared object underneath? I have the code checked out and building now, so I might see if I can use this as a chance to explore the code a bit.
