### ISSUE TITLE
Combine Euler node will not connect to the Compose Matrix node

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#929]
The **Combine Euler node** will not connect to the **Compose Matrix node**
Using Ubuntu 18.04 64bit, Python 3.6.5, numpy 1.15.0, blender 2.79b, Animation Node addon 2.1.2

I'm trying to reproduce
[https://blender.stackexchange.com/questions/112423/converting-code-to-work-in-blender-with-sliders/112431]

(https://blender.stackexchange.com/questions/112423/converting-code-to-work-in-blender-with-sliders/112431)

What I have so far but the Combine Euler node will not connect to the Compose Matrix node see issue in red circle
![spiral_twist](https://user-images.githubusercontent.com/28985314/44008818-76e9397c-9e75-11e8-8d41-a650fd5ce683.png)

[spiral_twist.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/2281538/spiral_twist.blend.zip)

**Comment by stillpointx** [comment]
Strange...I closed blender again and the nodes connected...I guess that's why it's beta, but it works great for me.

**Comment by 3DSingh** [comment]
This problem happens mainly when duplicating a existing node and it is not only with compose matrix node but also for other nodes. To solve this, I just add new node from menu instead of duplicating the node. May be this a bug.

**Comment by OmarSquircleArt** [comment]
This is a bug in the new vectorization code added in 2.1. See #928
