### ISSUE TITLE
animation node is not adding to blender 2.79

### ISSUE THREAD

**Issue by FizzaFaiz** [JacquesLucke/animation_nodes#930]
there is a problem after downloading the animation node i'm add this zip file user preferences but it is not appearing so i can check the box in order add it... why? plz tell me.. is it 2.79 not allow animation node...or anyother reason?

**Comment by stillpointx** [comment]
I had a similar problem using Ubuntu 18.04 64bit linux you need to have the correct version of python, numpy, and blender.  Post your version of each along with your OS.  
https://github.com/JacquesLucke/animation_nodes/releases

**Comment by OmarSquircleArt** [comment]
Did you check the [troubleshooting guide](http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html#troubleshooting)?

**Comment by prubini87** [comment]
If you're running the "stable" release of Blender, you should install Animation Nodes for Python 3.5. If you're running the daily, experimental builds, you should use Animation Nodes for Python 3.6.
