### ISSUE TITLE
Animation Nodes won't be activated: This build doesn't work at the moment error (in Windows 7 64bit)

### ISSUE THREAD

**Issue by Omeleto** [JacquesLucke/animation_nodes#931]
I'm having the same problem with this: https://github.com/JacquesLucke/animation_nodes/issues/793
I see that he's in 32 bit, and that what makes AN not working for him. I'm in 64 bit, and I've followed the procedure listed on the error message(specifically about the Visual C++ 2015 Redistributable), but it's still not working. 
![image](https://user-images.githubusercontent.com/40064473/44086924-d13d7c88-9fc6-11e8-9f27-35b8dbe73362.png)
I hope someone would respond :) !

**Comment by OmarSquircleArt** [comment]
Did you check the [troubleshooting guide](http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html#troubleshooting)?

**Comment by Omeleto** [comment]
Yes, I've checked it earlier
but no solution found

**Comment by Omeleto** [comment]
I'm very sure that the build matches my OS,

**Comment by Omeleto** [comment]
I've tried every single version(in windows 7) and what only works is 1.6 version of AN

**Comment by OmarSquircleArt** [comment]
What is your python version? Where did you get your blender build.

**Comment by Omeleto** [comment]
I think my python version was 3.5.3 because I saw it from here:
![image](https://user-images.githubusercontent.com/40064473/44092269-a17ace6c-9fd8-11e8-8ebb-82635c2373f2.png)

Blender version :  2.79b
I get the build from here: https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.0 or here for attempting to install 2.1 in case it would work : https://github.com/JacquesLucke/animation_nodes/releases

Hey, thankk you for response :)

**Comment by OmarSquircleArt** [comment]
The 2.0 builds are built using python 3.5 so they should work.
I am not sure why it doesn't work for you, sorry.
Wait till the developer take a look at your issue.

**Comment by Omeleto** [comment]
I wish he should see this.

**Comment by OmarSquircleArt** [comment]
Is building Animation Nodes yourself an option? Getting it to work after compilling it yourself is more likely.

**Comment by Omeleto** [comment]
I don't even know how to compile :) , What I just remember is I put the file inside the downloaded zip names "animation_nodes" to the addons file directory folder.

**Comment by OmarSquircleArt** [comment]
I see. Sorry I couldn't help.

**Comment by janmatys** [comment]
In fact I had the same problem and finaly got it working so try to install 14.14.2649 C++ Redist 2017 x64 cause I think it solves it...

**Comment by Omeleto** [comment]
Oh my, can I get the download link? There's too many of them, really
Thank you for hope

**Comment by Omeleto** [comment]
I can't really find the link, most of them offers 14.14.27012, kinda annoying
