### ISSUE TITLE
Colors for nodes are erased when using SHIFT-D to duplicate nodes

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#932]
Colors for nodes are erased when using SHIFT-D to duplicate nodes
I'm using Ubuntu 18.04 64bit, Python 3.6.5, numpy 1.15.0, blender 2.79b, Animation Node addon 2.1.2

see animation below
![vokoscreen-2018-08-14_14-28-14](https://user-images.githubusercontent.com/28985314/44111030-5650ee70-9fcf-11e8-8aec-b76553c86e9e.gif)

**Comment by stillpointx** [comment]
This seems to happens no matter which nodes are used..
![vokoscreen-2018-08-14_14-43-37](https://user-images.githubusercontent.com/28985314/44111597-e51fa0b4-9fd0-11e8-9d7c-d02f7dfdc619.gif)

**Comment by OmarSquircleArt** [comment]
Animation Nodes overwrite the color of all nodes as defined in the addon preferences and Color Mode option. To control the color of nodes manually, simply disable *Use Network Color* in the color panel.

**Comment by stillpointx** [comment]
Thanks!!!
