### ISSUE TITLE
CTRL+G to group nodes is grayed out / work as expected is this the way it suppose to work?

### ISSUE THREAD

**Issue by stillpointx** [JacquesLucke/animation_nodes#933]
CTRL+G to group nodes isn't enabled / grayed out / work as expected is this the way it suppose to work?

I'm using Ubuntu 18.04 64bit, Python 3.6.5, numpy 1.15.0, blender 2.79b, Animation Node addon 2.1.2

![node_group_issue](https://user-images.githubusercontent.com/28985314/44125729-2c21ecac-a002-11e8-9922-bf32bb19d4ac.gif)

**Comment by OmarSquircleArt** [comment]
Animation Nodes doesn't have the standard blender groups. Instead, explicit groups are provided as a Subprogram. See the [documentation on groups](http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/group.html).

So yes, this is the expected behaviour.

**Comment by stillpointx** [comment]
Thanks
I did find a good video that explains how to use animation node groups
[https://youtu.be/fH7NjAQ7H74](url)

**Comment by OmarSquircleArt** [comment]
Do you mind if I ask why you resolved to watching a tutorial instead of viewing the official documentation?

**Comment by OmarSquircleArt** [comment]
That would be nice. Write those notes in the documentation [repository](https://github.com/JacquesLucke/animation_nodes_manual/issues) if you don't mind.

**Comment by stillpointx** [comment]
Ok will do
