### ISSUE TITLE
Feature Request: Honeycomb matrices distribution

### ISSUE THREAD

**Issue by prubini87** [JacquesLucke/animation_nodes#936]
Hello! I was wondering if it's possible to add another Mode to the "Distribute Matrices" Node, which would be a Honeycomb mode? I know the name is self-explanatory but I'm attaching an image to illustrate what this new mode would do. Thank you very very much, always!!
![screenshot_1](https://user-images.githubusercontent.com/2468251/44291652-28313200-a256-11e8-9898-2effdf5ca099.png)

**Comment by OmarSquircleArt** [comment]
But do you think it is worth creating as an option? Considering one can create this pattern by simply moving every 2th matrix by half the step size.

**Comment by prubini87** [comment]
Hey! Thanks for your reply! Yes, you are right, it's possible to do this in a rather simple fashion with what we already have. I've followed your advice and here's what I got. The only problem I'm facing is adjusting the values circled in red in a more "automatic" way (E.g.: Extracting them from the instanced object's bounding box or something... Can you englighten me as how to do that, please? Thanks a lot, again!

![image](https://user-images.githubusercontent.com/2468251/44314008-e7b5ed80-a3e8-11e8-8899-047d07af7a27.png)

**Comment by OmarSquircleArt** [comment]
This is not exactly how I was proposing to do it. I proposed we move every **2th row** not every 2th point.

If we have a 5x5 grid and we want to convert it into a honeycomb, we would have to move the first, third and fifth row along the x axis half the value of the distance between columns (X Distance).
The vector list used for translation will have 5 identical vectors `(XDistance/2, 0, 0)` follows by 5 zero vectors which basically means we move the first five vectors and leave the following five vectors intact. If you are using the latest version of AN, the vector math node will have virtual inputs and the vector list will be repeated automatically. Making the node tree as follows.

![Node Tree](https://user-images.githubusercontent.com/25300994/44333016-debb2f80-a46d-11e8-89f6-d475b31e298d.png)

![Result](https://user-images.githubusercontent.com/25300994/44333053-014d4880-a46e-11e8-8ceb-6e1129fe4904.gif)

**Comment by OmarSquircleArt** [comment]
Note that I am not saying we shouldn't implement this feature request. I am just stating the alternatives. Then, we will see what the developer has to say.

Also, note that the spiral option can be computed from the circle option much more easily that computing honeycomb from grid, so adding the honeycomb option will be much more plausible.

![Node Tree](https://user-images.githubusercontent.com/25300994/44333549-5fc6f680-a46f-11e8-96fb-8d67b4403fce.png)

**Comment by prubini87** [comment]
Hey! Oh, yes, I hear you... Seeing your node setup I really think a honeycomb distribution would be a nice addition to the list of built-in distribution modes... I was wondering though what version of AN you're using, is that 2.0? I'm using 2.1 beta and I tried to replicate your setup but I'm not getting the same results... Do you mind taking a look @OmarSquircleArt?

![image](https://user-images.githubusercontent.com/2468251/44430279-99cbf180-a570-11e8-93a2-68a75eb40280.png)

**Comment by OmarSquircleArt** [comment]
Sorry about that, I was using a version with an updated *Distribute Matrices node* as you can see in #937 , I changed the order of points in that version such that rows grow first.

So I think to make it work on your version, one can do the following:

- The divide node should be connected to the y input of the combine node instead of the x.
- The multiply node and fill node should be connected to the Y Division instead of the X one.

If the developer agrees to merge that pull request, we will have the new distribute node in 2.1.
