### ISSUE TITLE
Bake to keyframe not working

### ISSUE THREAD

**Issue by DahrCastro** [JacquesLucke/animation_nodes#938]
When I'm trying to bake to keyframe, I get an error message "text object output" does not work and blender hangs and stops responding
![screen shot 2018-08-23 at 1 10 18 am](https://user-images.githubusercontent.com/42635385/44510297-881e4300-a671-11e8-9e75-1ab205e6230b.png)
I have a simple AN setup where "time info" is converted into "integer" and updates every "100 frames" output through "text object output". Simple counting animation 1 to 10. 

**Blend file attached:**
[countToTenBakingError.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/2313358/countToTenBakingError.blend.zip)

**Comment by OmarSquircleArt** [comment]
This is a bug in the baking code of the node. First, note that the the text body is not animatable in blender, thus Animation Nodes can't keyframe the text input. So even if the baking code works, I don't think you will get what you are looking for.

If, however, you still want the baking to work, go to your addons directory and find the file `animation_nodes/nodes/text/text_object_output.py`. All you have to do is remove line 140 at the very end of the file:

```python
if s["Align"].isUsed:               yield "    textObject.keyframe_insert('align')"
```
Or instead replace it by the two lines:

```python
if s["Horizontal Align"].isUsed:               yield "    textObject.keyframe_insert('align_x')"
if s["Vertical Align"].isUsed:               yield "    textObject.keyframe_insert('align_y')"
```
