### ISSUE TITLE
can not activate 2.1 on ubuntu 18.04

### ISSUE THREAD

**Issue by stansu** [JacquesLucke/animation_nodes#939]
as title

**Comment by stansu** [comment]
sorry for lack info about my problem.
here is the detail...

i can install it, but i can not activate it. after i activate it, it shows error message
![screenshot from 2018-08-31 10-51-56](https://user-images.githubusercontent.com/9460236/44890337-69bce500-ad0c-11e8-91dc-7f685c51a01c.jpg)

my blender build is 2.79b, the python version is 3.5.3.

i checked troubleshooting guide, but no helps.

the only change factor is OS, i reinstall ubuntu from 16.04 to 18.04.
before i use 18.04, it's working on 16.04.

final, i use AN2.0 instead.

thanks for your time.

**Comment by OmarSquircleArt** [comment]
The problem probably lies in your python version. In the [release page](https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_testbuilds_2), there are two versions for linux, one for python 3.5 and one for 3.6. Can you try both?

**Comment by stansu** [comment]
i checked 3.5 and 3.6, can not activate.
so i continue using 2.0.
