### ISSUE TITLE
DOPS like node

### ISSUE THREAD

**Issue by alijaya** [JacquesLucke/animation_nodes#941]
Hi, I'm wondering if there's a node that looks like DOPS in Houdini.
I mean the node that could do dynamic thing or simulation, the node that can have access the data from previous frame.
For example make random walker without reevaluate the data for each frame, just take the previous frame data and add extend another data there.

**Comment by OmarSquircleArt** [comment]
There is no node specifically designed to do this. However, it can be done with relative ease as described in this answer:
https://blender.stackexchange.com/questions/105090/how-to-store-particle-locations-in-a-list/105178#105178

If you have further questions or clarification, I would be happy to help.

**Comment by alijaya** [comment]
ah I see... but it's not cached per frame isn't it? I mean after we run the simulation, can we scrub the timeline to see it change? Because the previous calculation doesn't mean previous frame.

**Comment by OmarSquircleArt** [comment]
Correct. If you want a per frame caching mechanism, simply alter the *get* expression to be `getattr(AN, f"frameCache{frame-1}")` where frame is the current frame, and alter the *set* expression to be `if not hasattr(AN, f"frameCache{frame}"): setattr(AN, f"frameCache{frame}", data)` which will set the only if it doesn't exist. There will be cases where the data might not exist, you should find a way to handle that appropriately, either use an inline if statement or let the exceptions happen and check for `None` outputs.

If you want a more practical example, let me know.

**Comment by cnisidis** [comment]
@OmarSquircleArt  so there must be a point cache first, right ?
I had a similar question in the past (aprox 2 years before) when I was looking to create a "damper" node and I ended up storing values on my HD and read them from there. Nice tut btw !

**Comment by OmarSquircleArt** [comment]
@cnisidis I am not sure what you mean, put in mind that I am not a Houdini user, so I might not be able to follow houdini related concepts. Can you clarify?

**Comment by cnisidis** [comment]
damper is not deriving from houdini, but I ll try to explain since I am not into math. Damper works like a LERP between values and giving back two values, one as the "result" and the other as "velocity" (or acceleration). In a short term, what I was expecting to do with it was to "damp" between given values, assuming that I have as an input an X and I want to go to X' with a velocity of X[i] =X'*time/1000. The thing is that I have always to calculate my current position knowing the the previous one X[i-1] otherwise I ll never have the proper stepping. I dont know if that was clear but I did my best to explain it so far :D

**Comment by OmarSquircleArt** [comment]
@cnisidis I was actually asking about your question:

> there must be a point cache first, right ?

Not sure what you mean by that.

**Comment by cnisidis** [comment]
I mean there must be already a point cache for particles in order to execute the expression as you described 
getattr(AN, f"frameCache{frame-1}") so you cant feed it with RT values.
