### ISSUE TITLE
about the 32 bits version

### ISSUE THREAD

**Issue by dzWhynot** [JacquesLucke/animation_nodes#942]
Hi, I have windows 7 32 bits, and I wonder why is the 32bits isn't supported yet ?
I will be very grateful if is there a way I can build my own 32bits version

**Comment by OmarSquircleArt** [comment]
I think 32 bit is no longer supported. I am not sure if it is possible to create a 32 bit build, but feel free to check the [developers guide](https://animation-nodes-manual.readthedocs.io/en/latest/dev_guide/index.html) and check it out yourself.
