### ISSUE TITLE
Please do not remove templates!!!

### ISSUE THREAD

**Issue by vertexpreacher** [JacquesLucke/animation_nodes#943]
Hello,
Thanks for all of the hard work, it is really appreciated even if sometimes it does not seem so. <3,

Lately i began using animall more an more in my animations but i noticed you made a change. A change that has given me huge frustrations. 

You removed templates. 

Some of us are more artistically focused and have a hard time comprehending loops and all the myriad of ways things interact. Just leave the examples there so we can build upon and explore. 

Why did you feel the need to totally remove so few templates? now i need to keep a older version of blender running just to understand small tweaks. 

And yes i am a noob, and this is a rant.  bad. sad. lost. head scratching. time wasted. noob....

**Comment by OmarSquircleArt** [comment]
It is true that *few* templates were removed. However, socket vectorization and high level nodes like *falloffs* rendered loops unnecessary for most of the existing templates if I remember correctly. Moreover, the plan was to reimplement the template system in a more flexible manner such that one be able to create and share templates oneself, but implementing this system got delayed in favour of other things as far as I know.

The documentation is full of examples, use that! Try to understand loops, not understanding them is plausible, but not trying to is not. Need help? Visite us at stackexchange and we will do what we can to help, just make sure to invest time in trying to solve your problem first.

**Comment by vertexpreacher** [comment]
Its not like i am not trying to learn.

Look yes, most of the loops are easy to understand but when i go off the beaten track i start to doubt my methodology. Splines work a bit weirder than normal objects from what i am seeing. Also all that beautiful documentation (it is better than before) barely scratches the surface and there are many cases where i, the inexperienced user, do mistakes because i would think that combining things (that in my head should work) should work results in them not working.

What i am trying to say is give steady improvements on what you are building and do not remove helpful aids as its getting quite tiring to keep building the same start node to do loops or what ever. I used templates to get me started.... because i cant load nodes any other way between projects.

Like for real i gave up on trying to figure what i was doing wrong and i did it manually when i wrote the feedback because i was trying to figure a solution i solved a few months ago and now was not working. (i genuinely thought i had a older version on it because i did not see the templates)

''However, socket vectorization and high level nodes like falloffs rendered loops unnecessary for most of the existing te...'' sure sure.... user confused:P

Big hugs, i truly believe you are doing a major leap for the animation community in general.

Just keep us more graphically inclined in mind pls when it comes to use cases. (small skeletons of examples that animation nodes can do really do help me fiddle fast with more than one solution to tackle a problem and in many ways improves the overall result, rather than rebuilding things from scratch over and over).

**Comment by OmarSquircleArt** [comment]
> I can't load nodes any other way between projects.

This is not exactly true. You see, subprograms—like loops—are reusable and can be used across projects by simply appending their node trees just like any blender data. For more info, check my answer [here](https://blender.stackexchange.com/questions/79711/process-of-turning-groups-of-animation-nodes-into-templates-for-easy-reuse).

> The documentation barely scratches the surface ...

Then help us improve the documentation by telling us what it is missing. Open an issue in the documentation project and tell us "I need a more detailed example on X and its relation with Y." or "This demonstration is not clear enough, can you improve and elaborate?" and I promise, we will provide you with what you need.

> Splines work a bit weirder than normal objects from what I am seeing. ... There are many cases where i, the inexperienced user, do mistakes because i would think that combining things (that in my head should work) results in them not working.

Again, if you don't understand something, ask for help from the community at stackexchange or from the documentation as I described before. We would love to help, just come to us.

> Keep us more graphically inclined in mind pls when it comes to use cases.

I believe that Jacques did an amazing job in developing Animation Nodes for everybody. If you are artists, developer, student or a scientist, Animation Nodes will be of use to you. But I think that he is more forward thinking, you can see that from the state of backward compatibility in Animation Nodes, he wanted to make a better template system, so he removed the old one and started planning for the new one—you can actually see a branch called *templates* in which the development is supposed to happen—, it hasn't been implemented till now, but hopefully it will at some point, so patience.

My advice, invest some more time into learning Animation Nodes, and I will personally provide you with help along the way, if you needed it.

**Comment by vertexpreacher** [comment]
Well, then i suck, what can i say i really did  look for the info for about 4 days , i have been living with the idea that nodes cant be used between projects for months. 

As for my problem i am to tired to go thru that again, probably the answer is somewhere i have not looked, anyway time for it already elapsed.

You do amazing job in developing Animation Nodes, i understand why Jacques is  doing what he is doing and its smart, but i reaaaly belive you are missing out in the lack of templates or what ever to quickly test what ever works best and then work on that. But i will just append my nodes i guess and its good enough.

Thank you.

/me shuffles to sleep, sry if i came as abrasive

**Comment by OmarSquircleArt** [comment]
I will talk to Jacques about the state of templates. Maybe even try to write a patch myself. :smiley:

**Comment by vertexpreacher** [comment]
Please don't rush on my behalf, make a nice full feature. Since you illuminated  me that i can save the nodes i am creating another one of those huge blender reference files and now i can switch with relative ease between effects.
