### ISSUE TITLE
Bevel object for splines geometry

### ISSUE THREAD

**Issue by derkarol** [JacquesLucke/animation_nodes#944]
I wondered if it is possible to have some more nodes for Splines e.g. bevel object. Is it something that you are planing to work on? In manual I can see as an object input this option among another, however I wasn't able to find them in nodes. Looks like this is list of Spline properties. 
Or control turning on/off smoothness etc.
Thanks for AN.

![Image of an manual](https://user-images.githubusercontent.com/17281059/45979946-f7140080-c050-11e8-9ff8-d40bf19cee7c.png)

![Image of Simple Spline setup](https://user-images.githubusercontent.com/17281059/45979695-2ece7880-c050-11e8-922b-f40deea38009.png)

**Comment by OmarSquircleArt** [comment]
Some nodes have hidden inputs and outputs. See the [documentation](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/getting_started/interface.html#node-panel) on *Node Panel Interface*.
