### ISSUE TITLE
Animation not working in rendering.

### ISSUE THREAD

**Issue by drnn1076** [JacquesLucke/animation_nodes#945]
Hello,

I've created a node animation of two empty plain-axes where the rotation of the second axis depends on the angle of the first one. It plays fine and in-sync on the 3D viewer, but when I try to render the animation to have a video file, the second axis is not synchronised with the first one.

I'm using Animation Nodes 2.1.2 on blender 2.79b

Thanks for any help. If needed I can send the *.blend file.

**Comment by OmarSquircleArt** [comment]
Can you try rendering through the command line? You can use the [Terminal Helper](https://github.com/JacquesLucke/terminal_helper).

**Comment by Clockmender** [comment]
Consider using an Execution Trigger:

![screen shot 2018-09-28 at 19 15 08](https://user-images.githubusercontent.com/29657804/46226052-f7631300-c352-11e8-99f1-fc3279b306d7.png)

That's what I do when the node tree either doesn't execute using Frame Changed, or executes incorrectly on Frame Change. This works for me, post your blend file for us to look at.....

I have had situations in the past that work perfectly fine in 3D viewer, but not when you render animation, this has always solved the situation.

Cheers, Clock.

**Comment by drnn1076** [comment]
@Clockmender 

>> post your blend file for us to look at ...
here it is.
[cruz_malta_carpetier_1896a.zip](https://github.com/JacquesLucke/animation_nodes/files/2429791/cruz_malta_carpetier_1896a.zip)

Thx

**Comment by drnn1076** [comment]
@Clockmender 
>> That's what I do when the node tree either doesn't execute using Frame Changed, or executes incorrectly on Frame Change.

I tried your suggestion but without Frame Changed tickled, nothing moves in my animation. Perhaps I misunderstood how to implement your solution.

**Comment by Clockmender** [comment]
OK, having looked at your file, I have spent an hour, or so, making an alternative, simpler method of doing this:

![screen shot 2018-09-29 at 18 51 03](https://user-images.githubusercontent.com/29657804/46248964-090eee00-c419-11e8-9d1b-db9ed9745226.png)

Here's the node tree:

![screen shot 2018-09-29 at 18 54 25](https://user-images.githubusercontent.com/29657804/46248980-3e1b4080-c419-11e8-83f2-a174f9f1c6c9.png)

And the blend file:

[exec-1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/2430915/exec-1.blend.zip)

Ask any questions you may have. You should check "Autorun Python Scripts" in User Prefs => File tab for the expressions in the node tree and the driver o work.

Cheers, Clock.

**Comment by drnn1076** [comment]
Hello Clock, 
that was very nice and kind! thank you very much.
I'm downloading the file right now and checking it.
