### ISSUE TITLE
Animation Nodes 2.1, Blender nightly's python version mismatch.

### ISSUE THREAD

**Issue by prubini87** [JacquesLucke/animation_nodes#946]
Blender 2.79b x64 (haven't checked 32bits) now ships with **Python 3.7.0**, so the [Test Builds](https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_testbuilds_2) need to be recompiled, I suppose, to match the new version. I haven't been able to activate the addon on Windows until I recompiled it using Python 3.7.0.

**Comment by juangea** [comment]
Same problem here

**Comment by prubini87** [comment]
I have recompiled it with the correct python version but I no longer have a copy. To be honest I'm not sure if Jacques will continue this project... I haven't asked him though!

**Comment by juangea** [comment]
He started the 2.8 port already, he said something in twitter :)
What I´m not sure is how much of the features will be ported over.

**Comment by juangea** [comment]
Still no news?

If someone has the Python 3.7 compiled version, please... send it!!!

@prubini87 if you happend to have it again... please send it :)

**Comment by prubini87** [comment]
@juangea unfortunately I don't have a copy or the tools to compile it but there's a detailed guide on the developers section of the documentation with all the steps you need to follow to compile it in your system! I hope that helps!

**Comment by juangea** [comment]
Hey guys, Jacques just published a Python 3.7 compiled version yesterday, you can find it in the releases section, sorry for not saying anything before, I´vé been busy.
I already tested it and it´s working perfectly :)

Cheers!

**Comment by prubini87** [comment]
Thanks @juangea, I'm closing this issue now!
For further reference, please check: [https://github.com/JacquesLucke/animation_nodes/releases](https://github.com/JacquesLucke/animation_nodes/releases)
