### ISSUE TITLE
Setting Maxima and Minima on Node Input

### ISSUE THREAD

**Issue by Clockmender** [JacquesLucke/animation_nodes#947]
I have a node with several Float Inputs:

```
def create(self):
        self.newInput("Color","Color","col")
        self.newInput("Float",'Red','red')
        self.newInput("Float",'Green','green')
        self.newInput("Float",'Blue','blue')
```

I want to limit the values to range 0-1. Changing the input to something like this:

`self.newInput("Float",'Red','red',min=0,max=1)`

Doesn't work, how can I do this please?

Cheers, Clock.

**Comment by derkarol** [comment]
Isn't it what a falloff node can manage? It would be my first guess, but I am not super familiar with AN yet. [https://animation-nodes-manual.readthedocs.io/en/latest/release_notes/v2_0/falloff.html?highlight=falloff%20node](url)

**Comment by Clockmender** [comment]
Aha! so you use "minValue" and "maxValue" in a NewInput call and "min" and "max" in a numerical property call - why are they different?

`self.newInput("Float",'Red','red',minValue = 0,maxValue = 1)`

`offset = IntProperty(name = "Offset", default = 0, min = -1000, max = 10000)`

Hmmm curious, thanks very much!

Cheers, Clock.
