### ISSUE TITLE
Can not activate AN 2.1 in Blender 2.79b

### ISSUE THREAD

**Issue by micschwarz** [JacquesLucke/animation_nodes#948]
![image](https://user-images.githubusercontent.com/20029553/46366565-a79a8980-c67b-11e8-9095-486915eee2e8.png)

### Blender
Version: 2.79 (sub 0), branch: master, commit date: 2018-03-22 14:10, hash: f4dc9f9d68b
Python Version: 3.5.3
### System
Platform: Windows 10 64bit
Python Version installed: 3.7.0 64bit
CPU: AMD Ryzen 5 (maybe this is important)

**Comment by prubini87** [comment]
Hello @micschwarz, is that the entire error message or there's more?

**Comment by micschwarz** [comment]
> Hello @micschwarz, is that the entire error message or there's more?

@prubini87 It's the whole errormessage

**Comment by prubini87** [comment]
Mmm, well, I don't know what's wrong from that error message alone... I suggest you completely uninstall Animation Nodes by deleting its directory (and subdirectories). On Windows it should be located at (e.g.: **"C:\Users\YOUR-USERNAME\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\animation_nodes"**). Completely delete that directory, restart Blender and then try to reinstall AN. If that doesn't work, you may try to compile AN yourself, but that will take a few extra steps and may be too complicated if you're not a developer... The steps you need to take are described here: [Developer Guide](https://animation-nodes-manual.readthedocs.io/en/latest/dev_guide/index.html).

Also, the python version you run on your system doesn't really matter (unless you're compiling AN). What's important is that Blender's internal python version matches AN's python's compiled version. So, if you compile AN for a Blender release that runs python 3.5, you have to compile it from a system python version 3.5 as well. To better manage that, you will see in the Develper Guide that using Anaconda is recommended (to create an isolated python environment for compiling AN without touching your system-wide python).

Cheers man, I hope that helps somehow!

**Comment by micschwarz** [comment]
@prubini87 Thank you for your quick answer. It's not important for me to run it in Blender 2.79.
My intention was to test in Blender 2.8 and therefor I recompiled it with Python 3.7. It didn't work and I wanted to check wether it works in 2.79 precompiled... and it didn't.

The porpos of the issue is to report a potential "Bug", even if its not clear if this is a real bug
