### ISSUE TITLE
Some Feature Requests

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#95]
(A) Split lines
1. Adding suport to Split by BlankLine, this is very useful for some imported format.
2. Allowing using list for "Split By" input, or to support splitting by multiple rules, (and also support additional rule upon the presets, for example, to split by lines AND other one or two specified characters)

(B) Expost Input for LIST nodes:
Currently we can only type values in, not input from other nodes, which limit its power a bit.

**Comment by azerupi** [comment]
For (A) this is about the "*split text*" node right?
I don't know how it is implemented but it would be simple to make that node super powerful by making it possible to split using a regexp. If I have time I can look into it :)

**Comment by LeonCheung** [comment]
Hi azerupi, cool! Yes, that is about rule definition especially for texts loaded by Text Block Reader.

**Comment by azerupi** [comment]
So, I  changed the Custom to Regexp. The layout was and is still not very slick, but it's working. The only drawback of this feature is that users have to know regular expressions. Can you test it and give me some feedback? https://github.com/azerupi/animation-nodes/tree/split-text

**Some examples:**

- Split on blank lines: ```\n```
- Split on dots: ```\.``` (you have to escape the dot because it has a special meaning in regular expressions)
- Split on vowels: ```[aeiou]``` or ```a|e|i|o|u``` (between the letters are not "L"s but vertical lines)

If you know how to use regular expressions you can do some great stuff ;)

**Comment by LeonCheung** [comment]
Yeah, it would be definitely great if regex is supported. LuckilyI did know some regex, will give it a try!  :D

**Comment by azerupi** [comment]
I am also considering an option for keeping the delimiters in the final list :)

**Comment by LeonCheung** [comment]
So far so good, it gives us much more possibilities for Animation Nodes! Thank you so much! Just one comment:

When leaving regex field blank, the result behaves exactly the same as when use "Character" from the list, is that make by design? If so, I bet "Character" can retire.  :). But I would suggest to keep it and try to leave the block un-split when the regex field is blank.  FYI

**Comment by azerupi** [comment]
Yes, that behaviour was already there before, I just left it like that because I didn't know anything better to do when it was blank ;) But I guess returning a one item list is not a bad idea. Thank you for your feedback :)

**Comment by LeonCheung** [comment]
Thanks for your enhancement on regex, now I can think of making a subtitle exractior all by animation nodes! I'll try to make an automatic subtitle importer in this way I can see the possibility. (Though it would be nice to have a specific node to do that job, you know, currently we haven't any good addon to take this job)
![sub](https://cloud.githubusercontent.com/assets/494788/6534678/333ce094-c47a-11e4-87db-4e1a422110f5.jpg)

**Comment by azerupi** [comment]
No problem :) 
I think a node for subtitles is a little to specific and it would be a lot better handled by an add-on specifically designed for that task.

**Comment by LeonCheung** [comment]
Sure, btw, it makes me thinking about a possible useful node: **Combine Text List**, which does the opposite work. I don't mean for a reversed usage, which is useless. What I mean is more like reorganize the "precessed", then maybe for another split rule to apply, this would be nice to make new cool text animations that will be very hard to make currently.

**Comment by azerupi** [comment]
Can't you do that already with the *list > sum elements* node ?
![screen](https://cloud.githubusercontent.com/assets/7647338/6535330/75726474-c444-11e4-9a43-399718faaa67.png)

**Comment by LeonCheung** [comment]
Grrr... nearly forgot this one. :P Thanks for reminding!

**Comment by azerupi** [comment]
Haha, yeah the name is not that obvious for text ;)

**Comment by azerupi** [comment]
#96 has been merged into master :)
