### ISSUE TITLE
Everything nodes

### ISSUE THREAD

**Issue by paperbenni** [JacquesLucke/animation_nodes#951]
Let's be honest here: when everything nodes is going to be released, most people are going to switch to it. Animation nodes can be pretty heavy on performance and the fact that it has to use the python API doesn't help. Lately I've been thinking about getting more into animation nodes but I wonder whether or not this would be worth it just like a beginner shouldn't learn 2.79 specific interface stuff when planning on switching to 2.8. Will everything nodes be more of a native port of an or is it going to be a completely independent project with different systems? How much of my knowledge about an will I be able to transfer to everything nodes, how many nodes/systems are going to be identical? Will an be continued to get developed in parallel to everything nodes?

**Comment by OmarSquircleArt** [comment]
- Everything Nodes is not about porting Animation Nodes to Blender, it is a different project that happened to be led by Jacques.
- Everything Nodes is not going to happen anytime soon, I would give it a year or two, maybe even more before Everything Nodes get to the point where we don't need Animation Nodes anymore.
- Animation Nodes is merely a tool to help you implement things based on algorithms and ideas, but it also help you develop your problem solving skills and knowledge in mathematics, when Everything Nodes comes to being, all this knowledge will still be with you, you will just need to adjust to the new system, which should be very easy as both projects are very similar.
- Will Animation Nodes continue to be developed? I am not sure, it will probably be developed for sometime while Everything Nodes is under development, but it will probably get deprecated as soon as Everything Nodes becomes able to replace it.

So should you learn Animation Nodes? Definitely, Animation Nodes is your best option for procedural content creation and advanced automation, at least until Everything Nodes comes to being. And as I said before, all your knowledge will be transferred easily when the time comes.
