### ISSUE TITLE
Get Spline Samples missing

### ISSUE THREAD

**Issue by arniswillow** [JacquesLucke/animation_nodes#952]
Hi!
First of all, this addon rocks! Thank you!

Secondly, the node "Get Spline Samples" is missing in the AN 2.1 version with 3.7 Python. I updated to a newer version of Blender and AN and then found out that the node is missing. Is there some kind node setup I could use to reproduce the GSS node?

**Comment by OmarSquircleArt** [comment]
The *Evaluate Spline* node can be used to get the same result. Enable *Evaluate Range* to get automatic evaluation.
