### ISSUE TITLE
Does version 2.0 and 2.1 work with Blender 2.79?

### ISSUE THREAD

**Issue by pilgrim333** [JacquesLucke/animation_nodes#954]
I tried both 2.0 and 2.1 and they both failed with:
An exception was raised during the execution of a node tree. …

These are the files I used:

[csv_path_vis_v3.blend.gz](https://github.com/JacquesLucke/animation_nodes/files/2544445/csv_path_vis_v3.blend.gz)
[movement.csv.gz](https://github.com/JacquesLucke/animation_nodes/files/2544446/movement.csv.gz)

**Comment by OmarSquircleArt** [comment]
It seems that blend file was created using an older version of Animation Nodes, and it is not backward compatible. So you have to recreate it from scratch.

**Comment by pilgrim333** [comment]
Thank you.
