### ISSUE TITLE
Fake Module bl_info

### ISSUE THREAD

**Issue by larenas** [JacquesLucke/animation_nodes#955]
Hi i made a big mistake installing the addon the fist time. I didnt select the zip file, I select the setup.py file............Now when I try to install from the zip file the console give me this

Read prefs: C:\Users\Pablo\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Pablo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\setup.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Pablo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\setup.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Pablo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\setup.py'
Modules Installed () from 'C:\\Users\\Pablo\\Documents\\blender\\addons\\animation_nodes-master.zip' into 'C:\\Users\\Pablo\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'

How can i deletes from addons the setup.py I can´t find it in the folder...

Thaanks for your help!

**Comment by OmarSquircleArt** [comment]
Animation Nodes can't be installed like normals addons. Please check the [Installation Guide](https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/install/install.html).

**Comment by JacquesLucke** [comment]
The path to the folder is right there in the error message. The appdata folder might be hidden by default.

**Comment by larenas** [comment]
Hi, yes I had read the Instllation Guide, thx!.

@JacquesLucke I have in the view option i showing the hidden files and I don't see a folder named Animation_nodes. 

This is my folder, can you see anything that could be installed when I press in setup.py to install the addons from the user preference instead  of the zip file.....


![1](https://user-images.githubusercontent.com/6202279/48002977-6891a500-e10d-11e8-9314-2319e6c016e7.jpg)
![2](https://user-images.githubusercontent.com/6202279/48002978-692a3b80-e10d-11e8-82b0-e71e8a7bfcdc.jpg)
![3](https://user-images.githubusercontent.com/6202279/48002979-692a3b80-e10d-11e8-8afa-86378a101b28.jpg)
![4](https://user-images.githubusercontent.com/6202279/48002980-692a3b80-e10d-11e8-904b-7e564616b687.jpg)
![5](https://user-images.githubusercontent.com/6202279/48002976-6891a500-e10d-11e8-8d78-eb5443772ab9.jpg)
 

thx again!

**Comment by JacquesLucke** [comment]
You are in the wrong directory...
`C:\Users\Pablo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons`

**Comment by larenas** [comment]
oh god shame on me, that was a little stupid from my part. ok problem resolve.

I deleted the floder animation_nodes_master and installed a different version from the first time (v 2.0)  and now seems to work fine.


THANKS for this addons and for helping me!
