### ISSUE TITLE
Trying to render this file crashes Blender

### ISSUE THREAD

**Issue by dutzi** [JacquesLucke/animation_nodes#959]
Hi,

First just wanted to say how much I love this project :)

The issue I encountered (could be an issue with Blender, I opened a ticket there too) is that when I try to render the file below Blender crashes.

https://drive.google.com/open?id=1uDzfK4GNAZMHGPTwQQ4ctIHsmfGuwLZi 

To reproduce just open this file and hit Render > Render Animation (or Render Image, crashes as well)

**Comment by OmarSquircleArt** [comment]
I tried on 2.8 and it worked. So, it is probably a bug in your blender version.

**Comment by dutzi** [comment]
Wait what? AN works on 2.8? How?

**Comment by OmarSquircleArt** [comment]
Mostly yes. If you want to test it, compile the blender2.8 branch, or wait for test builds to be release, probably this month.

**Comment by OmarEmaraDev** [comment]
Fixed in #1294 and b1ac938.
