### ISSUE TITLE
Baking crash, AN 2.1 in 2.80 Beta

### ISSUE THREAD

**Issue by NizarAmous** [JacquesLucke/animation_nodes#963]
Hello, i made a simple animation and i couldn't bake the animation, so i tried with a simpler setup ( see screenshot ) and it has the same problem 
![bug](https://user-images.githubusercontent.com/45922048/50057591-ff219f00-016c-11e9-99ee-92af958407d1.jpg)

**Comment by OmarSquircleArt** [comment]
Fixed in  f720dfe.
