### ISSUE TITLE
2.1 Bake Sound crashes Blender 2.80

### ISSUE THREAD

**Issue by Music-AMG** [JacquesLucke/animation_nodes#967]
Bake sound crashes Blender  with the error AttributeError: 'bpy_prop_collection' object has no attribute 'unlink'

This is with a daily build of Blender 2.80 and Win10

**Comment by OmarSquircleArt** [comment]
There is a bug in the sound spectrum bake system that is hard to fix. So we are most likely going to rewrite the whole sound system.

**Comment by Clockmender** [comment]
Hi Omar, are you going to put any MIDI integration into the next version, if you are, I have written nodes to do this, but my coding may need an expert eye casting over it as some of my methods, whilst they work, may not take advantage of all that is possible in Python, let me know if this is of interest. I worked with Jacques in the early stages until I got the basics in place, details on my website, or GitHub branch.

Cheer, Clock.

**Comment by OmarSquircleArt** [comment]
I am familiar with you work on the MIDI front. But I am not going to be looking at MIDI files for now. However, I am very interested about MIDI in general, so lets have an extended discussion about them, but maybe after everything in AN becomes stable.

**Comment by Clockmender** [comment]
> so lets have an extended discussion about them, but maybe after everything in AN becomes stable

Good idea! I look forward to helping on this in any way I can.

**Comment by OmarSquircleArt** [comment]
A new sound system was just introduced and should be available in the next build. So I guess this issue is resolved.
