### ISSUE TITLE
MacOS Mojave 10.14.2 unable to enable

### ISSUE THREAD

**Issue by emilsvidt** [JacquesLucke/animation_nodes#968]
Hello Jacques,

First of all, I am super excited about Animation Nodes being ported to Blender 2.80!

I have the newest **2.80** built, as of today (17th, dec. 2018 HASH: 1eafa91f647 )

With Animation Nodes **2.1.3**, I get this error message when I try and enable the addon:

![screenshot 2018-12-17 at 21 45 34](https://user-images.githubusercontent.com/45951374/50114815-d9b49400-0245-11e9-9c56-efb1fcedcf05.jpg)

Let me know if I can provide any additional information, and keep up the awesomeness!

**Comment by OmarSquircleArt** [comment]
See https://github.com/JacquesLucke/animation_nodes/issues/961.

**Comment by emilsvidt** [comment]
> See #961.

My apologies Omar, I didn't notice this was a duplicate. Thanks 👍
