### ISSUE TITLE
Baking Alembic is guaranteed crashing or error with AN 2.1 and Blender 2.80

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#969]
I am trying to bake some mesh animation as Alembic. So far I am getting a halt error without explanation or Blender simply crashes.

This is probably related to Blender 2.80 "bug" but I don't know. 

[dissolve_avocado_011.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/2688476/dissolve_avocado_011.blend.zip)

**Comment by enzyme69** [comment]
I imported the node tree into Blender 2.79 and seems that Alembic anim export works without issue. In this case it's issue and bug of Blender 2.80 beta. 

Should I leave it here until it's got fixed on that side?

**Comment by OmarSquircleArt** [comment]
I am not familiar with Alembic. How does one export mesh animation to alembic? I tried normal alembic export and everything seemed to be working.

**Comment by 3DSingh** [comment]
Hi @enzyme69, I have tried Alembic animation export and it works in blender 2.8. Actually, if you want to export AN animation as Alembic animation, you should first convert AN animation into keyframes (bake to keyframes) then export as Alembic animation and it will work. 
Blend file: [Alembic_1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/2694177/Alembic_1.blend.zip)

**Comment by OmarSquircleArt** [comment]
@enzyme69 Can you report back on this?

**Comment by OmarEmaraDev** [comment]
If you are still having issue, please continue the discussion in issue #1200 .
