### ISSUE TITLE
Mesh Output Node does not work for input mesh which does not has faces in AN2.1 Blender 2.8

### ISSUE THREAD

**Issue by 3DSingh** [JacquesLucke/animation_nodes#972]
Hi...
It seems that _Mesh Output Node_ does not work for input mesh which does not has faces in AN2.1 Blender 2.8. However it works nicely for input mesh has faces. Please help.

![screenshot from 2018-12-19 20-02-18](https://user-images.githubusercontent.com/30294746/50226687-dea25080-03c9-11e9-9f7a-6760e377caa0.png)

Blend File:
[Mesh1.blend.zip](https://github.com/JacquesLucke/animation_nodes/files/2695231/Mesh1.blend.zip)

**Comment by OmarSquircleArt** [comment]
Seems to be working fine here. What exactly isn't working for you?

![Node Tree](https://user-images.githubusercontent.com/25300994/50231597-d6d9b080-03b7-11e9-8541-e9cd5ea5ec6c.png)

**Comment by 3DSingh** [comment]
@OmarSquircleArt Edges of the target object are not visible in 'Object Mode', Why?? However, another object 'Cube_WOFace' edges are visible.

**Comment by OmarSquircleArt** [comment]
This is just how Blender display objects. Try adding an object with only vertices, the vertices will be visible from Object Mode, however, when you create at least a single edge, the vertices will disappear.
This has nothing to do with Animation Nodes, as far as I know.

**Comment by 3DSingh** [comment]
@OmarSquircleArt That is true. But as soon as on AN or 'auto execution' then edges disappeared.

![peek 2018-12-20 19-57](https://user-images.githubusercontent.com/30294746/50290596-30aea900-0492-11e9-81a2-064a593bea78.gif)

**Comment by OmarSquircleArt** [comment]
Still, I don't think we can anything about this. I will look into it again, but it is not essential for now.
