### ISSUE TITLE
Animation rendering doesn't work in 2.8.

### ISSUE THREAD

**Issue by pipipix** [JacquesLucke/animation_nodes#975]
Hello.I really like Animation nodes;)
I'm trying render this file with animation nodes 2.13 .
It looks good at view port.
but when I render this, animation doesn't work.
And I tried it bake to key frames,Blender crashed. 
How can I fix it?
[test02.zip](https://github.com/JacquesLucke/animation_nodes/files/2697394/test02.zip)

**Comment by OmarSquircleArt** [comment]
We fixed the baking issue, so it should work in the next build.
For the animation rendering issue, I can reproduce it, will look into it.

**Comment by pipipix** [comment]
Thank you for your reply!
I'm so glad about next build!
In my blender file, animation render results are all same frames ...
what is wrong?
![2018-12-21 011317](https://user-images.githubusercontent.com/46014571/50296338-a845fd80-04bd-11e9-888c-baa71eace597.jpg)

**Comment by pipipix** [comment]
Thank you very much!
Sorry for my poor English.
 I am looking forward to it.
Best Regard.
