### ISSUE TITLE
Exception Access Violation when connecting an input to the Script node in 2.1 2.80

### ISSUE THREAD

**Issue by CodyWinch** [JacquesLucke/animation_nodes#978]
When connecting any socket to the input of a Script node blender instantly crashes and only throws up a EXCEPTION ACCESS VIOLATION

I was able to trace it as far as the info_popups.py file in the animation_nodes\ui\ folder. It crashes once it hits the return drawPopup line. I tried to fix it myself but so far have not been successful.

**Comment by OmarSquircleArt** [comment]
We will not be looking into crashes for now, as blender itself is not fully stable yet.
