### ISSUE TITLE
animation nodes for blender 2.8 not work on Mac

### ISSUE THREAD

**Issue by kareem64** [JacquesLucke/animation_nodes#979]
blender 2.8 animation node not work when trying activate it some issue appear and not working 
please how to solve this problem
I,m using blender 2.8 beta and Mac OS 10.13.6

**Comment by 3DSingh** [comment]
See #961, this may help.

**Comment by OmarSquircleArt** [comment]
Does #961 fix your issue? Can you include the output of the terminal?

**Comment by OmarSquircleArt** [comment]
Replace the file `animation_nodes/nodes/viewer/matrix_shade.glsl` with this file:
https://raw.githubusercontent.com/JacquesLucke/animation_nodes/blender2.8/animation_nodes/nodes/viewer/matrix_shader.glsl

**Comment by kareem64** [comment]
Sorry I can,t open matrix_shader.also to replace it

**Comment by kareem64** [comment]
I opened the file in visual studio and replace it and save it . I tested but this message appeared:
![screen shot 2018-12-22 at 3 29 14 pm](https://user-images.githubusercontent.com/46063289/50375035-e6e3d100-05ff-11e9-88f1-846e3d0e1473.png)

**Comment by OmarSquircleArt** [comment]
Can you uninstall AN, download a new [build](https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_blender2.8_testbuild1), and install it? Does it work?

**Comment by kareem64** [comment]
Thank you very much I download last release blender 2.8 and replace matrix_shade.glsl file 
and it work
Thanks Alot
![screen shot 2018-12-22 at 4 55 57 pm](https://user-images.githubusercontent.com/46063289/50376485-ddfdfa00-0615-11e9-921c-3d155081d7bc.png)
