### ISSUE TITLE
Text Object Output

### ISSUE THREAD

**Issue by cflanagan** [JacquesLucke/animation_nodes#980]
I create a text object in the layout tab and go to Animation Nodes. I add a Text Object Output, select the text object I created, and select the text item below the object selector. I expect the text in my text object to disappear and for new text to appear when I enter it into the Text Object Output control. Nothing happens. The default text in the text object remains. I am unable to control it with the Text Object Output control.

**Comment by AbhaySharma-tp** [comment]
> I create a text object in the layout tab and go to Animation Nodes. I add a Text Object Output, select the text object I created, and select the text item below the object selector. I expect the text in my text object to disappear and for new text to appear when I enter it into the Text Object Output control. Nothing happens. The default text in the text object remains. I am unable to control it with the Text Object Output control.

Hey there, did you activated the text socket?

**Comment by cflanagan** [comment]
I was able to get AN working after downloading the source code and compiling it locally. I thought it might be helpful to anyone else running Ubuntu 18.04 to document my process. The instructions in the developer guide are out of date.

### Get the latest source
Download the latest [source code](https://github.com/JacquesLucke/animation_nodes/tree/blender2.8) and unzip.

### Install Anaconda
Go to [Anaconda.com](https://www.anaconda.com/download/) and download the latest version.
The file Anaconda3-5.2.0-Linux-x86_64.sh needs to be made executable.
`chmod +x /path/to/your/Anaconda3-5.2.0-Linux-x86_64.sh`

To install run:
`./path/to/your/Anaconda3-5.2.0-Linux-x86_64.sh`

Follow the prompts during installation. You'll need to answer quesitons and approve installation locations.

The installer offers to install MS VSCode at the end. No problem to decline.

After installation run
`source ~/.bashrc`

Run `conda list` to test installation. It will output all of the installed packages.

### Create a Anaconda Environment

Run `conda create --name your_env_name python=3`

### Activate / Deactivate 

To start the Anaconda Environment
Run `source activate your_env_name`

To stop the Anaconda Environment
Run `source deactivate your_env_name`

### Install Cython

Run `conda install cython`

### Compile Animation Nodes

With your Anaconda Environment activated (the command prompt should be prepended with your environment name), run the setup.py file in the Animation Nodes source code you downloaded and unzipped.
`python /path/to/file`

The first time you run this command, it creates a config.json file. You're supposed to open it and change the path to the location where you want AN installed. 

After updating the config.json file, run the command again to compile AN.
`python /path/to/file --noversioncheck`

I needed to include the --noversioncheck option in order to get it to compile. An error message on the first try provided the option name to use.

Anaconda creates a **build** folder in the source code folder and a **animation_nodes** folder at the location specified in config.json.

When I started Blender, everything in Animation Nodes was working again.
