### ISSUE TITLE
AN2.1 does not work properly with latest blender 2.8 beta build 

### ISSUE THREAD

**Issue by 3DSingh** [JacquesLucke/animation_nodes#981]
Hi...
I have downloaded the latest blender build,
![screenshot from 2018-12-23 19-19-29](https://user-images.githubusercontent.com/30294746/50384257-88dee880-06e8-11e9-8a83-83181ff0a6dc.png)

Then installed the addon AN2.1 on it without any error message. In the Animation Nodes editor, whole GUI works but not the nodes. Here a gif,
![peek 2018-12-23 19-18](https://user-images.githubusercontent.com/30294746/50384288-d52a2880-06e8-11e9-9315-5086bc59b89c.gif)

However, It showed an error message during uninstall,
![screenshot from 2018-12-23 19-21-51](https://user-images.githubusercontent.com/30294746/50384315-2cc89400-06e9-11e9-8519-24709833276a.png)

Please help.

**Comment by OmarSquircleArt** [comment]
Fixed in 461a2b7.

**Comment by 3DSingh** [comment]
Thanks @OmarSquircleArt
