### ISSUE TITLE
Animation nodes broken because of name change as of today (12 Dec 2018)

### ISSUE THREAD

**Issue by AbhaySharma-tp** [JacquesLucke/animation_nodes#982]
Animation nodes not working on my window machine after updating blender beta (24 Dec 2018).
because of some name change in blender beta (user_preferences to preferences) in preference.py and blender_ui.py file. I corrected that and it worked!

**Comment by OmarSquircleArt** [comment]
Yes, that was already fixed. Thanks for the report!
