### ISSUE TITLE
animation nodes not work on blender 2.8 release date after 17/12/ 2018

### ISSUE THREAD

**Issue by kareem64** [JacquesLucke/animation_nodes#986]
Hi, in first I thank MR Omar and MR JacquesLucke

I,m tested  animation nodes on my blender 2.8 beta release 17/12/2018 and MR Omar helped me and it work good but when I test animation nodes on blender 2.8 release after this Date it not work

**Comment by kareem64** [comment]
![screen shot 2018-12-28 at 7 41 48 am](https://user-images.githubusercontent.com/46063289/50504358-cbe8e500-0a75-11e9-979b-c0a0b57d891a.png)

**Comment by OmarSquircleArt** [comment]
There was a slight change in the API that resulted for AN builds to not work on latest blender builds. We already took care of it. You can either wait for a new build or change two lines of code as illustrated in 461a2b7.
