### ISSUE TITLE
Why does AN2.1 reset Group Node input parameters while reopening the blend file ?

### ISSUE THREAD

**Issue by 3DSingh** [JacquesLucke/animation_nodes#987]
Hi...
I have created a Group Node in AN2.1 and changed some input parameters then saved the file blend. When I reopened the file, AN2.1 reset Group Node input parameters to default values. This also happens to other nodes which have sub-menu. For example, vector Falloff Node, if I change the noise type then it reset input parameters (Amplitude, Frequency etc). Here the gif:

![peek 2018-12-28 11-58](https://user-images.githubusercontent.com/30294746/50505381-42e3a500-0a99-11e9-981b-bb5cb56a4f80.gif)

**Comment by OmarSquircleArt** [comment]
Fixed in e824cd2.
