### ISSUE TITLE
Blender frozen with too many instances

### ISSUE THREAD

**Issue by fredsprinkle** [JacquesLucke/animation_nodes#991]
It was probably dumb of me to instance 10K cubes. This froze blender 2.79 for me. And that particular blend file remains stuck in an endless freeze loop. I can't do anything to the file when I open it. It just keeps trying to process that many cubes.

I know it was my fault, but that file is now unusable, perhaps having an auto-break when there are too many instances might be cool.

**Comment by JacquesLucke** [comment]
Maybe you can start loading the file with AN being disabled.
Not sure what the next step should be though, maybe try to remove the instancer node, if that's possible, then save and restart.

Unfortunately implementing an auto-break is harder than it seems at first.
There is a `ctrl+shift+q` shortcut that disables auto execution, but only after the current execution finished.

**Comment by fredsprinkle** [comment]
Thanks for the response, I would imagine it would be hard. Thanks for the work you do. Animation Nodes is really cool man. Just digging in.
