### ISSUE TITLE
Properties don't affect object

### ISSUE THREAD

**Issue by McAsulys** [JacquesLucke/animation_nodes#994]
Hi, i'm fallowing this tuts : https://www.youtube.com/watch?v=e3kJlG9RVd0

But at a certain point, i change data in the node tree, but this do not affect the property of the mesh display. It was working before. I should do something wrong, my connected button is still check but nothing change in the viewport or in the property panelle of the object (not the node). It look like disconnected.

Using 2.8 beta from 2018-12-13 with animation nodes 2.1.3

**Comment by OmarSquircleArt** [comment]
Be specific about the issue. Show us your node tree. What node seems to be causing the problem? What is the expected behaviour and what did you get?

**Comment by Rob1008** [comment]
Hi,
I have the same problem.

![an_1](https://user-images.githubusercontent.com/46420034/50736804-27c41400-11c2-11e9-8370-b82fc5794f28.jpg)

Blender 2.8  build 2019-01-06
Windows 10

I tried with other builds and had the same problem.

**Comment by OmarSquircleArt** [comment]
@Rob1008 Your Animation Nodes build is outdated, download a new build and see if it works. Make sure to remove older versions before installing the new one.

**Comment by Rob1008** [comment]
Ok, can you give please the right link ?
Thanks

**Comment by OmarSquircleArt** [comment]
@Rob1008 https://github.com/JacquesLucke/animation_nodes/releases/tag/v2.1_blender2.8_testbuild1

**Comment by Rob1008** [comment]
Thanks, It works now!
