### ISSUE TITLE
Error after Update object

### ISSUE THREAD

**Issue by BrowePankin** [JacquesLucke/animation_nodes#997]
Hi,
can you help me with Animation nodes working? After Update (Separate Text Object) I get this error.
Thank you very much.
![animation_nodes_error](https://user-images.githubusercontent.com/6229204/50962586-dd48dd00-14ca-11e9-8af3-c09b59ca5790.jpg)

**Comment by OmarSquircleArt** [comment]
Thanks for the report. This was already fixed.

**Comment by BrowePankin** [comment]
Thanks again!
